-- Refactor candidate objects (sandbox) for DRILLBLAST_DRILL_CYCLE_CT.
-- Goal: same output as baseline, but faster.

CREATE OR REPLACE TABLE SANDBOX_DATA_ENGINEER.CCARRILL2.DRILLBLAST_DRILL_CYCLE_CT_REF
(
  ORIG_SRC_ID NUMBER(38,0),
  SITE_CODE VARCHAR(50),
  BENCH VARCHAR(16777216),
  PUSHBACK VARCHAR(16777216),
  PATTERN_NAME VARCHAR(510),
  ORIGINAL_PATTERN_NAME VARCHAR(510),
  DRILL_CYCLE_SK NUMBER(19,0),
  DRILL_HOLE_SHIFT_ID VARCHAR(16777216) COLLATE 'en-ci',
  DRILL_ID NUMBER(19,0),
  DRILL_BIT_ID VARCHAR(255),
  SYSTEM_OPERATOR_ID VARCHAR(16777216),
  DRILL_HOLE_ID VARCHAR(16777216),
  DRILL_HOLE_NAME VARCHAR(256),
  DRILL_PLAN_SK NUMBER(19,0),
  DRILL_HOLE_STATUS NUMBER(10,0),
  IS_HOLE_PLANNED_FLAG NUMBER(38,0),
  START_HOLE_TS_UTC TIMESTAMP_TZ(9),
  END_HOLE_TS_UTC TIMESTAMP_TZ(9),
  START_HOLE_TS_LOCAL TIMESTAMP_TZ(9),
  END_HOLE_TS_LOCAL TIMESTAMP_TZ(9),
  DRILL_HOLE_DURATION_SECONDS NUMBER(38,0),
  ACTUAL_DRILL_HOLE_DEPTH_FEET NUMBER(38,5),
  ACTUAL_DRILL_HOLE_DEPTH_METERS NUMBER(38,5),
  GPS_ACCURACY NUMBER(38,0),
  ACTUAL_DRILL_HOLE_START_FEET_X NUMBER(38,5),
  ACTUAL_DRILL_HOLE_START_FEET_Y NUMBER(38,5),
  ACTUAL_DRILL_HOLE_START_FEET_Z NUMBER(38,5),
  ACTUAL_DRILL_HOLE_END_FEET_X NUMBER(38,5),
  ACTUAL_DRILL_HOLE_END_FEET_Y NUMBER(38,5),
  ACTUAL_DRILL_HOLE_END_FEET_Z NUMBER(38,5),
  ACTUAL_DRILL_HOLE_LONGITUDE FLOAT,
  ACTUAL_DRILL_HOLE_LATITUDE FLOAT,
  ACTUAL_DRILL_HOLE_START_METERS_X NUMBER(38,5),
  ACTUAL_DRILL_HOLE_START_METERS_Y NUMBER(38,5),
  ACTUAL_DRILL_HOLE_START_METERS_Z NUMBER(38,5),
  ACTUAL_DRILL_HOLE_END_METERS_X NUMBER(38,5),
  ACTUAL_DRILL_HOLE_END_METERS_Y NUMBER(38,5),
  ACTUAL_DRILL_HOLE_END_METERS_Z NUMBER(38,5),
  AUTODRILL_DURATION_SECONDS NUMBER(38,0),
  AUTODRILL_USAGE_PCT NUMBER(38,0),
  DRILL_HOLE_PENETRATION_RATE_AVG_FEET_HOUR NUMBER(38,5),
  OPERATOR_LOGIN_TS_UTC TIMESTAMP_TZ(9),
  OPERATOR_LOGOUT_TS_UTC TIMESTAMP_TZ(9),
  OPERATOR_LOGIN_TS_LOCAL TIMESTAMP_TZ(9),
  OPERATOR_LOGOUT_TS_LOCAL TIMESTAMP_TZ(9),
  BEARING NUMBER(38,1),
  DRILL_TOWER_ANGLE_DEGREE_CALCULATED NUMBER(38,5),
  DRILL_TOWER_ANGLE_DEGREE_SYSTEM NUMBER(38,5),
  DRILL_HOLE_DUPLICATED_FLAG NUMBER(38,0),
  DRILL_HOLE_UPSIDE_DOWN_FLAG NUMBER(38,0),
  DRILL_HOLE_START_END_TIME_INVALID_FLAG NUMBER(38,0),
  DRILL_HOLE_START_END_TIME_OVERLAP_FLAG NUMBER(38,0),
  DRILL_HOLE_DEPTH_INVALID_FLAG NUMBER(38,0),
  DRILL_HOLE_ANGLE_INVALID_FLAG NUMBER(38,0),
  DRILL_HOLE_POSITION_INVALID_FLAG NUMBER(38,0),
  TIME_BETWEEN_DRILL_HOLES_SECONDS NUMBER(38,0),
  AIR_PRESSURE_PSI NUMBER(38,5),
  FEED_FORCE_NEWTONS NUMBER(38,5),
  ROTATION_TORQUE_NM NUMBER(38,5),
  BIT_SPEED_RPM NUMBER(38,5),
  WATER_FLOW_GPM NUMBER(38,5),
  INSTANTANOUS_PENRATE_MWD_METERS_HOUR NUMBER(38,5),
  INSTANTANOUS_PENRATE_MWD_FEET_HOUR NUMBER(38,5),
  DRILL_HOLE_OFF_TARGET_FEET NUMBER(38,5),
  DRILL_HOLE_OFF_TARGET_METERS NUMBER(38,5),
  DRILL_HOLE_HORIZONTAL_ACCURACY_PCT NUMBER(38,0),
  DRILL_HOLE_VERTICAL_ACCURACY_PCT NUMBER(38,0),
  OVERDRILL_UNDERDRILL_FLAG NUMBER(38,0),
  OVERDRILL_UNDERDRILL_FEET NUMBER(38,5),
  OVERDRILL_UNDERDRILL_METERS NUMBER(38,5),
  DRILLING_STOPS_COUNT NUMBER(38,0),
  DRILL_HOLE_REDRILL_FLAG NUMBER(38,0),
  PROPEL_START_TS_UTC TIMESTAMP_TZ(9),
  PROPEL_END_TS_UTC TIMESTAMP_TZ(9),
  PARK_POSITION_START_TS_UTC TIMESTAMP_TZ(9),
  PARK_POSITION_END_TS_UTC TIMESTAMP_TZ(9),
  LEVEL_START_TS_UTC TIMESTAMP_TZ(9),
  LEVEL_END_TS_UTC TIMESTAMP_TZ(9),
  DRILL_START_TS_UTC TIMESTAMP_TZ(9),
  DRILL_END_TS_UTC TIMESTAMP_TZ(9),
  RETRACT_START_TS_UTC TIMESTAMP_TZ(9),
  RETRACT_END_TS_UTC TIMESTAMP_TZ(9),
  PROPEL_START_TS_LOCAL TIMESTAMP_TZ(9),
  PROPEL_END_TS_LOCAL TIMESTAMP_TZ(9),
  PARK_POSITION_START_TS_LOCAL TIMESTAMP_TZ(9),
  PARK_POSITION_END_TS_LOCAL TIMESTAMP_TZ(9),
  LEVEL_START_TS_LOCAL TIMESTAMP_TZ(9),
  LEVEL_END_TS_LOCAL TIMESTAMP_TZ(9),
  DRILL_START_TS_LOCAL TIMESTAMP_TZ(9),
  DRILL_END_TS_LOCAL TIMESTAMP_TZ(9),
  RETRACT_START_TS_LOCAL TIMESTAMP_TZ(9),
  RETRACT_END_TS_LOCAL TIMESTAMP_TZ(9),
  PROPEL_DURATION NUMBER(36,6),
  PARK_POSITION_DURATION NUMBER(36,6),
  LEVEL_DURATION NUMBER(36,6),
  DRILL_DURATION NUMBER(36,6),
  RETRACT_DURATION NUMBER(36,6),
  SYSTEM_DRILL_STATE_DURATION_SECONDS NUMBER(38,0),
  SYSTEM_SETUP_STATE_DURATION_SECONDS NUMBER(38,0),
  SYSTEM_AUTO_LEVEL_DURATION_SECONDS NUMBER(38,0),
  SYSTEM_AUTO_DELEVEL_DURATION_SECONDS NUMBER(38,0),
  PLAN_CREATION_TS_LOCAL TIMESTAMP_TZ(9),
  SYSTEM_VERSION VARCHAR(11),
  ACTUAL_MCF_BLOCK_ID VARCHAR(16777216),
  DESIGN_MCF_BLOCK_ID VARCHAR(16777216),
  DW_LOGICAL_DELETE_FLAG VARCHAR(1) COLLATE 'en-ci',
  DW_LOAD_TS TIMESTAMP_NTZ(0),
  DW_MODIFY_TS TIMESTAMP_NTZ(0)
);

CREATE OR REPLACE PROCEDURE SANDBOX_DATA_ENGINEER.CCARRILL2.DRILLBLAST_DRILL_CYCLE_CT_P_REF(NUMBER_OF_DAYS VARCHAR DEFAULT '5')
RETURNS VARCHAR
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS
$$
function clampDays(v) {
  var n = parseInt(v, 10);
  if (isNaN(n)) n = 5;
  if (n < 1) n = 1;
  if (n > 30) n = 30;
  return n;
}

var days = clampDays(NUMBER_OF_DAYS);
var cutoff = `DATEADD(day, - ${days}, CURRENT_DATE)`;

var sp_result = "";

function nowIso() {
  // ISO-ish UTC timestamp for traceability
  return (new Date()).toISOString();
}

function runStep(stepName, sqlText) {
  var startedMs = Date.now();
  var stmt = snowflake.createStatement({sqlText: sqlText});
  var rs = stmt.execute();
  var endedMs = Date.now();

  var rowsAffected = null;
  try { rowsAffected = rs.getNumRowsAffected(); } catch (e) { rowsAffected = null; }

  return {
    step: stepName,
    ms: (endedMs - startedMs),
    query_id: stmt.getQueryId(),
    rows_affected: rowsAffected
  };
}

var tag = `snowrefactor:DRILLBLAST_DRILL_CYCLE_CT_P_REF:days=${days}:ts=${nowIso()}`;
var timings = [];

// 1) Retention cleanup: keep baseline semantics (date-window on TIMESTAMP_TZ).
var sql_delete_old = `DELETE FROM SANDBOX_DATA_ENGINEER.CCARRILL2.DRILLBLAST_DRILL_CYCLE_CT_REF
WHERE START_HOLE_TS_LOCAL::DATE < ${cutoff}`;

// Add an identifiable comment so Query History can be filtered by query text.
sql_delete_old = `/* snowrefactor_tag=${tag} step=delete_old */\n` + sql_delete_old;

// 2) Merge: avoid MINUS (set ops typically force sort/dedup). Let MERGE do the matching.
var sql_merge = `MERGE INTO SANDBOX_DATA_ENGINEER.CCARRILL2.DRILLBLAST_DRILL_CYCLE_CT_REF tgt
USING (
  SELECT
    orig_src_id,
    site_code,
    bench,
    pushback,
    pattern_name,
    original_pattern_name,
    drill_cycle_sk,
    drill_hole_shift_id,
    drill_id,
    drill_bit_id,
    system_operator_id,
    drill_hole_id,
    drill_hole_name,
    drill_plan_sk,
    drill_hole_status,
    is_hole_planned_flag,
    start_hole_ts_utc,
    end_hole_ts_utc,
    start_hole_ts_local,
    end_hole_ts_local,
    drill_hole_duration_seconds,
    actual_drill_hole_depth_feet,
    actual_drill_hole_depth_meters,
    gps_accuracy,
    actual_drill_hole_start_feet_x,
    actual_drill_hole_start_feet_y,
    actual_drill_hole_start_feet_z,
    actual_drill_hole_end_feet_x,
    actual_drill_hole_end_feet_y,
    actual_drill_hole_end_feet_z,
    actual_drill_hole_longitude,
    actual_drill_hole_latitude,
    actual_drill_hole_start_meters_x,
    actual_drill_hole_start_meters_y,
    actual_drill_hole_start_meters_z,
    actual_drill_hole_end_meters_x,
    actual_drill_hole_end_meters_y,
    actual_drill_hole_end_meters_z,
    autodrill_duration_seconds,
    autodrill_usage_pct,
    drill_hole_penetration_rate_avg_feet_hour,
    operator_login_ts_utc,
    operator_logout_ts_utc,
    operator_login_ts_local,
    operator_logout_ts_local,
    bearing,
    drill_tower_angle_degree_calculated,
    drill_tower_angle_degree_system,
    drill_hole_duplicated_flag,
    drill_hole_upside_down_flag,
    drill_hole_start_end_time_invalid_flag,
    drill_hole_start_end_time_overlap_flag,
    drill_hole_depth_invalid_flag,
    drill_hole_angle_invalid_flag,
    drill_hole_position_invalid_flag,
    time_between_drill_holes_seconds,
    air_pressure_psi,
    feed_force_newtons,
    rotation_torque_nm,
    bit_speed_rpm,
    water_flow_gpm,
    instantanous_penrate_mwd_meters_hour,
    instantanous_penrate_mwd_feet_hour,
    drill_hole_off_target_feet,
    drill_hole_off_target_meters,
    drill_hole_horizontal_accuracy_pct,
    drill_hole_vertical_accuracy_pct,
    overdrill_underdrill_flag,
    overdrill_underdrill_feet,
    overdrill_underdrill_meters,
    drilling_stops_count,
    drill_hole_redrill_flag,
    propel_start_ts_utc,
    propel_end_ts_utc,
    park_position_start_ts_utc,
    park_position_end_ts_utc,
    level_start_ts_utc,
    level_end_ts_utc,
    drill_start_ts_utc,
    drill_end_ts_utc,
    retract_start_ts_utc,
    retract_end_ts_utc,
    propel_start_ts_local,
    propel_end_ts_local,
    park_position_start_ts_local,
    park_position_end_ts_local,
    level_start_ts_local,
    level_end_ts_local,
    drill_start_ts_local,
    drill_end_ts_local,
    retract_start_ts_local,
    retract_end_ts_local,
    propel_duration,
    park_position_duration,
    level_duration,
    drill_duration,
    retract_duration,
    system_drill_state_duration_seconds,
    system_setup_state_duration_seconds,
    system_auto_level_duration_seconds,
    system_auto_delevel_duration_seconds,
    plan_creation_ts_local,
    system_version,
    actual_mcf_block_id,
    design_mcf_block_id,
    'N' as dw_logical_delete_flag,
    CURRENT_TIMESTAMP(0)::TIMESTAMP_NTZ AS dw_load_ts,
    CURRENT_TIMESTAMP(0)::TIMESTAMP_NTZ AS dw_modify_ts
  FROM prod_target.collections.drillblast_drill_cycle_dt
  WHERE START_HOLE_TS_LOCAL::DATE >= ${cutoff}
) src
ON  tgt.orig_src_id = src.orig_src_id
AND tgt.site_code = src.site_code
AND tgt.drill_hole_shift_id = src.drill_hole_shift_id
AND tgt.system_version = src.system_version
AND tgt.drill_id = src.drill_id
AND tgt.drill_hole_id = src.drill_hole_id

WHEN MATCHED AND HASH(
  src.bench,
  src.pushback,
  src.pattern_name,
  src.original_pattern_name,
  src.drill_cycle_sk,
  src.drill_bit_id,
  src.system_operator_id,
  src.drill_hole_name,
  src.drill_plan_sk,
  src.drill_hole_status,
  src.is_hole_planned_flag,
  src.start_hole_ts_utc,
  src.end_hole_ts_utc,
  src.start_hole_ts_local,
  src.end_hole_ts_local,
  src.drill_hole_duration_seconds,
  src.actual_drill_hole_depth_feet,
  src.actual_drill_hole_depth_meters,
  src.gps_accuracy,
  src.actual_drill_hole_start_feet_x,
  src.actual_drill_hole_start_feet_y,
  src.actual_drill_hole_start_feet_z,
  src.actual_drill_hole_end_feet_x,
  src.actual_drill_hole_end_feet_y,
  src.actual_drill_hole_end_feet_z,
  src.actual_drill_hole_longitude,
  src.actual_drill_hole_latitude,
  src.actual_drill_hole_start_meters_x,
  src.actual_drill_hole_start_meters_y,
  src.actual_drill_hole_start_meters_z,
  src.actual_drill_hole_end_meters_x,
  src.actual_drill_hole_end_meters_y,
  src.actual_drill_hole_end_meters_z,
  src.autodrill_duration_seconds,
  src.autodrill_usage_pct,
  src.drill_hole_penetration_rate_avg_feet_hour,
  src.operator_login_ts_utc,
  src.operator_logout_ts_utc,
  src.operator_login_ts_local,
  src.operator_logout_ts_local,
  src.bearing,
  src.drill_tower_angle_degree_calculated,
  src.drill_tower_angle_degree_system,
  src.drill_hole_duplicated_flag,
  src.drill_hole_upside_down_flag,
  src.drill_hole_start_end_time_invalid_flag,
  src.drill_hole_start_end_time_overlap_flag,
  src.drill_hole_depth_invalid_flag,
  src.drill_hole_angle_invalid_flag,
  src.drill_hole_position_invalid_flag,
  src.time_between_drill_holes_seconds,
  src.air_pressure_psi,
  src.feed_force_newtons,
  src.rotation_torque_nm,
  src.bit_speed_rpm,
  src.water_flow_gpm,
  src.instantanous_penrate_mwd_meters_hour,
  src.instantanous_penrate_mwd_feet_hour,
  src.drill_hole_off_target_feet,
  src.drill_hole_off_target_meters,
  src.drill_hole_horizontal_accuracy_pct,
  src.drill_hole_vertical_accuracy_pct,
  src.overdrill_underdrill_flag,
  src.overdrill_underdrill_feet,
  src.overdrill_underdrill_meters,
  src.drilling_stops_count,
  src.drill_hole_redrill_flag,
  src.propel_start_ts_utc,
  src.propel_end_ts_utc,
  src.park_position_start_ts_utc,
  src.park_position_end_ts_utc,
  src.level_start_ts_utc,
  src.level_end_ts_utc,
  src.drill_start_ts_utc,
  src.drill_end_ts_utc,
  src.retract_start_ts_utc,
  src.retract_end_ts_utc,
  src.propel_start_ts_local,
  src.propel_end_ts_local,
  src.park_position_start_ts_local,
  src.park_position_end_ts_local,
  src.level_start_ts_local,
  src.level_end_ts_local,
  src.drill_start_ts_local,
  src.drill_end_ts_local,
  src.retract_start_ts_local,
  src.retract_end_ts_local,
  src.propel_duration,
  src.park_position_duration,
  src.level_duration,
  src.drill_duration,
  src.retract_duration,
  src.system_drill_state_duration_seconds,
  src.system_setup_state_duration_seconds,
  src.system_auto_level_duration_seconds,
  src.system_auto_delevel_duration_seconds,
  src.plan_creation_ts_local,
  src.actual_mcf_block_id,
  src.design_mcf_block_id,
  src.dw_logical_delete_flag
) <> HASH(
  tgt.bench,
  tgt.pushback,
  tgt.pattern_name,
  tgt.original_pattern_name,
  tgt.drill_cycle_sk,
  tgt.drill_bit_id,
  tgt.system_operator_id,
  tgt.drill_hole_name,
  tgt.drill_plan_sk,
  tgt.drill_hole_status,
  tgt.is_hole_planned_flag,
  tgt.start_hole_ts_utc,
  tgt.end_hole_ts_utc,
  tgt.start_hole_ts_local,
  tgt.end_hole_ts_local,
  tgt.drill_hole_duration_seconds,
  tgt.actual_drill_hole_depth_feet,
  tgt.actual_drill_hole_depth_meters,
  tgt.gps_accuracy,
  tgt.actual_drill_hole_start_feet_x,
  tgt.actual_drill_hole_start_feet_y,
  tgt.actual_drill_hole_start_feet_z,
  tgt.actual_drill_hole_end_feet_x,
  tgt.actual_drill_hole_end_feet_y,
  tgt.actual_drill_hole_end_feet_z,
  tgt.actual_drill_hole_longitude,
  tgt.actual_drill_hole_latitude,
  tgt.actual_drill_hole_start_meters_x,
  tgt.actual_drill_hole_start_meters_y,
  tgt.actual_drill_hole_start_meters_z,
  tgt.actual_drill_hole_end_meters_x,
  tgt.actual_drill_hole_end_meters_y,
  tgt.actual_drill_hole_end_meters_z,
  tgt.autodrill_duration_seconds,
  tgt.autodrill_usage_pct,
  tgt.drill_hole_penetration_rate_avg_feet_hour,
  tgt.operator_login_ts_utc,
  tgt.operator_logout_ts_utc,
  tgt.operator_login_ts_local,
  tgt.operator_logout_ts_local,
  tgt.bearing,
  tgt.drill_tower_angle_degree_calculated,
  tgt.drill_tower_angle_degree_system,
  tgt.drill_hole_duplicated_flag,
  tgt.drill_hole_upside_down_flag,
  tgt.drill_hole_start_end_time_invalid_flag,
  tgt.drill_hole_start_end_time_overlap_flag,
  tgt.drill_hole_depth_invalid_flag,
  tgt.drill_hole_angle_invalid_flag,
  tgt.drill_hole_position_invalid_flag,
  tgt.time_between_drill_holes_seconds,
  tgt.air_pressure_psi,
  tgt.feed_force_newtons,
  tgt.rotation_torque_nm,
  tgt.bit_speed_rpm,
  tgt.water_flow_gpm,
  tgt.instantanous_penrate_mwd_meters_hour,
  tgt.instantanous_penrate_mwd_feet_hour,
  tgt.drill_hole_off_target_feet,
  tgt.drill_hole_off_target_meters,
  tgt.drill_hole_horizontal_accuracy_pct,
  tgt.drill_hole_vertical_accuracy_pct,
  tgt.overdrill_underdrill_flag,
  tgt.overdrill_underdrill_feet,
  tgt.overdrill_underdrill_meters,
  tgt.drilling_stops_count,
  tgt.drill_hole_redrill_flag,
  tgt.propel_start_ts_utc,
  tgt.propel_end_ts_utc,
  tgt.park_position_start_ts_utc,
  tgt.park_position_end_ts_utc,
  tgt.level_start_ts_utc,
  tgt.level_end_ts_utc,
  tgt.drill_start_ts_utc,
  tgt.drill_end_ts_utc,
  tgt.retract_start_ts_utc,
  tgt.retract_end_ts_utc,
  tgt.propel_start_ts_local,
  tgt.propel_end_ts_local,
  tgt.park_position_start_ts_local,
  tgt.park_position_end_ts_local,
  tgt.level_start_ts_local,
  tgt.level_end_ts_local,
  tgt.drill_start_ts_local,
  tgt.drill_end_ts_local,
  tgt.retract_start_ts_local,
  tgt.retract_end_ts_local,
  tgt.propel_duration,
  tgt.park_position_duration,
  tgt.level_duration,
  tgt.drill_duration,
  tgt.retract_duration,
  tgt.system_drill_state_duration_seconds,
  tgt.system_setup_state_duration_seconds,
  tgt.system_auto_level_duration_seconds,
  tgt.system_auto_delevel_duration_seconds,
  tgt.plan_creation_ts_local,
  tgt.actual_mcf_block_id,
  tgt.design_mcf_block_id,
  tgt.dw_logical_delete_flag
) THEN UPDATE SET
  tgt.bench = src.bench,
  tgt.pushback = src.pushback,
  tgt.pattern_name = src.pattern_name,
  tgt.original_pattern_name = src.original_pattern_name,
  tgt.drill_cycle_sk = src.drill_cycle_sk,
  tgt.drill_bit_id = src.drill_bit_id,
  tgt.system_operator_id = src.system_operator_id,
  tgt.drill_hole_name = src.drill_hole_name,
  tgt.drill_plan_sk = src.drill_plan_sk,
  tgt.drill_hole_status = src.drill_hole_status,
  tgt.is_hole_planned_flag = src.is_hole_planned_flag,
  tgt.start_hole_ts_utc = src.start_hole_ts_utc,
  tgt.end_hole_ts_utc = src.end_hole_ts_utc,
  tgt.start_hole_ts_local = src.start_hole_ts_local,
  tgt.end_hole_ts_local = src.end_hole_ts_local,
  tgt.drill_hole_duration_seconds = src.drill_hole_duration_seconds,
  tgt.actual_drill_hole_depth_feet = src.actual_drill_hole_depth_feet,
  tgt.actual_drill_hole_depth_meters = src.actual_drill_hole_depth_meters,
  tgt.gps_accuracy = src.gps_accuracy,
  tgt.actual_drill_hole_start_feet_x = src.actual_drill_hole_start_feet_x,
  tgt.actual_drill_hole_start_feet_y = src.actual_drill_hole_start_feet_y,
  tgt.actual_drill_hole_start_feet_z = src.actual_drill_hole_start_feet_z,
  tgt.actual_drill_hole_end_feet_x = src.actual_drill_hole_end_feet_x,
  tgt.actual_drill_hole_end_feet_y = src.actual_drill_hole_end_feet_y,
  tgt.actual_drill_hole_end_feet_z = src.actual_drill_hole_end_feet_z,
  tgt.actual_drill_hole_longitude = src.actual_drill_hole_longitude,
  tgt.actual_drill_hole_latitude = src.actual_drill_hole_latitude,
  tgt.actual_drill_hole_start_meters_x = src.actual_drill_hole_start_meters_x,
  tgt.actual_drill_hole_start_meters_y = src.actual_drill_hole_start_meters_y,
  tgt.actual_drill_hole_start_meters_z = src.actual_drill_hole_start_meters_z,
  tgt.actual_drill_hole_end_meters_x = src.actual_drill_hole_end_meters_x,
  tgt.actual_drill_hole_end_meters_y = src.actual_drill_hole_end_meters_y,
  tgt.actual_drill_hole_end_meters_z = src.actual_drill_hole_end_meters_z,
  tgt.autodrill_duration_seconds = src.autodrill_duration_seconds,
  tgt.autodrill_usage_pct = src.autodrill_usage_pct,
  tgt.drill_hole_penetration_rate_avg_feet_hour = src.drill_hole_penetration_rate_avg_feet_hour,
  tgt.operator_login_ts_utc = src.operator_login_ts_utc,
  tgt.operator_logout_ts_utc = src.operator_logout_ts_utc,
  tgt.operator_login_ts_local = src.operator_login_ts_local,
  tgt.operator_logout_ts_local = src.operator_logout_ts_local,
  tgt.bearing = src.bearing,
  tgt.drill_tower_angle_degree_calculated = src.drill_tower_angle_degree_calculated,
  tgt.drill_tower_angle_degree_system = src.drill_tower_angle_degree_system,
  tgt.drill_hole_duplicated_flag = src.drill_hole_duplicated_flag,
  tgt.drill_hole_upside_down_flag = src.drill_hole_upside_down_flag,
  tgt.drill_hole_start_end_time_invalid_flag = src.drill_hole_start_end_time_invalid_flag,
  tgt.drill_hole_start_end_time_overlap_flag = src.drill_hole_start_end_time_overlap_flag,
  tgt.drill_hole_depth_invalid_flag = src.drill_hole_depth_invalid_flag,
  tgt.drill_hole_angle_invalid_flag = src.drill_hole_angle_invalid_flag,
  tgt.drill_hole_position_invalid_flag = src.drill_hole_position_invalid_flag,
  tgt.time_between_drill_holes_seconds = src.time_between_drill_holes_seconds,
  tgt.air_pressure_psi = src.air_pressure_psi,
  tgt.feed_force_newtons = src.feed_force_newtons,
  tgt.rotation_torque_nm = src.rotation_torque_nm,
  tgt.bit_speed_rpm = src.bit_speed_rpm,
  tgt.water_flow_gpm = src.water_flow_gpm,
  tgt.instantanous_penrate_mwd_meters_hour = src.instantanous_penrate_mwd_meters_hour,
  tgt.instantanous_penrate_mwd_feet_hour = src.instantanous_penrate_mwd_feet_hour,
  tgt.drill_hole_off_target_feet = src.drill_hole_off_target_feet,
  tgt.drill_hole_off_target_meters = src.drill_hole_off_target_meters,
  tgt.drill_hole_horizontal_accuracy_pct = src.drill_hole_horizontal_accuracy_pct,
  tgt.drill_hole_vertical_accuracy_pct = src.drill_hole_vertical_accuracy_pct,
  tgt.overdrill_underdrill_flag = src.overdrill_underdrill_flag,
  tgt.overdrill_underdrill_feet = src.overdrill_underdrill_feet,
  tgt.overdrill_underdrill_meters = src.overdrill_underdrill_meters,
  tgt.drilling_stops_count = src.drilling_stops_count,
  tgt.drill_hole_redrill_flag = src.drill_hole_redrill_flag,
  tgt.propel_start_ts_utc = src.propel_start_ts_utc,
  tgt.propel_end_ts_utc = src.propel_end_ts_utc,
  tgt.park_position_start_ts_utc = src.park_position_start_ts_utc,
  tgt.park_position_end_ts_utc = src.park_position_end_ts_utc,
  tgt.level_start_ts_utc = src.level_start_ts_utc,
  tgt.level_end_ts_utc = src.level_end_ts_utc,
  tgt.drill_start_ts_utc = src.drill_start_ts_utc,
  tgt.drill_end_ts_utc = src.drill_end_ts_utc,
  tgt.retract_start_ts_utc = src.retract_start_ts_utc,
  tgt.retract_end_ts_utc = src.retract_end_ts_utc,
  tgt.propel_start_ts_local = src.propel_start_ts_local,
  tgt.propel_end_ts_local = src.propel_end_ts_local,
  tgt.park_position_start_ts_local = src.park_position_start_ts_local,
  tgt.park_position_end_ts_local = src.park_position_end_ts_local,
  tgt.level_start_ts_local = src.level_start_ts_local,
  tgt.level_end_ts_local = src.level_end_ts_local,
  tgt.drill_start_ts_local = src.drill_start_ts_local,
  tgt.drill_end_ts_local = src.drill_end_ts_local,
  tgt.retract_start_ts_local = src.retract_start_ts_local,
  tgt.retract_end_ts_local = src.retract_end_ts_local,
  tgt.propel_duration = src.propel_duration,
  tgt.park_position_duration = src.park_position_duration,
  tgt.level_duration = src.level_duration,
  tgt.drill_duration = src.drill_duration,
  tgt.retract_duration = src.retract_duration,
  tgt.system_drill_state_duration_seconds = src.system_drill_state_duration_seconds,
  tgt.system_setup_state_duration_seconds = src.system_setup_state_duration_seconds,
  tgt.system_auto_level_duration_seconds = src.system_auto_level_duration_seconds,
  tgt.system_auto_delevel_duration_seconds = src.system_auto_delevel_duration_seconds,
  tgt.plan_creation_ts_local = src.plan_creation_ts_local,
  tgt.actual_mcf_block_id = src.actual_mcf_block_id,
  tgt.design_mcf_block_id = src.design_mcf_block_id,
  tgt.dw_modify_ts = src.dw_modify_ts

WHEN NOT MATCHED THEN INSERT (
  orig_src_id,
  site_code,
  bench,
  pushback,
  pattern_name,
  original_pattern_name,
  drill_cycle_sk,
  drill_hole_shift_id,
  drill_id,
  drill_bit_id,
  system_operator_id,
  drill_hole_id,
  drill_hole_name,
  drill_plan_sk,
  drill_hole_status,
  is_hole_planned_flag,
  start_hole_ts_utc,
  end_hole_ts_utc,
  start_hole_ts_local,
  end_hole_ts_local,
  drill_hole_duration_seconds,
  actual_drill_hole_depth_feet,
  actual_drill_hole_depth_meters,
  gps_accuracy,
  actual_drill_hole_start_feet_x,
  actual_drill_hole_start_feet_y,
  actual_drill_hole_start_feet_z,
  actual_drill_hole_end_feet_x,
  actual_drill_hole_end_feet_y,
  actual_drill_hole_end_feet_z,
  actual_drill_hole_longitude,
  actual_drill_hole_latitude,
  actual_drill_hole_start_meters_x,
  actual_drill_hole_start_meters_y,
  actual_drill_hole_start_meters_z,
  actual_drill_hole_end_meters_x,
  actual_drill_hole_end_meters_y,
  actual_drill_hole_end_meters_z,
  autodrill_duration_seconds,
  autodrill_usage_pct,
  drill_hole_penetration_rate_avg_feet_hour,
  operator_login_ts_utc,
  operator_logout_ts_utc,
  operator_login_ts_local,
  operator_logout_ts_local,
  bearing,
  drill_tower_angle_degree_calculated,
  drill_tower_angle_degree_system,
  drill_hole_duplicated_flag,
  drill_hole_upside_down_flag,
  drill_hole_start_end_time_invalid_flag,
  drill_hole_start_end_time_overlap_flag,
  drill_hole_depth_invalid_flag,
  drill_hole_angle_invalid_flag,
  drill_hole_position_invalid_flag,
  time_between_drill_holes_seconds,
  air_pressure_psi,
  feed_force_newtons,
  rotation_torque_nm,
  bit_speed_rpm,
  water_flow_gpm,
  instantanous_penrate_mwd_meters_hour,
  instantanous_penrate_mwd_feet_hour,
  drill_hole_off_target_feet,
  drill_hole_off_target_meters,
  drill_hole_horizontal_accuracy_pct,
  drill_hole_vertical_accuracy_pct,
  overdrill_underdrill_flag,
  overdrill_underdrill_feet,
  overdrill_underdrill_meters,
  drilling_stops_count,
  drill_hole_redrill_flag,
  propel_start_ts_utc,
  propel_end_ts_utc,
  park_position_start_ts_utc,
  park_position_end_ts_utc,
  level_start_ts_utc,
  level_end_ts_utc,
  drill_start_ts_utc,
  drill_end_ts_utc,
  retract_start_ts_utc,
  retract_end_ts_utc,
  propel_start_ts_local,
  propel_end_ts_local,
  park_position_start_ts_local,
  park_position_end_ts_local,
  level_start_ts_local,
  level_end_ts_local,
  drill_start_ts_local,
  drill_end_ts_local,
  retract_start_ts_local,
  retract_end_ts_local,
  propel_duration,
  park_position_duration,
  level_duration,
  drill_duration,
  retract_duration,
  system_drill_state_duration_seconds,
  system_setup_state_duration_seconds,
  system_auto_level_duration_seconds,
  system_auto_delevel_duration_seconds,
  plan_creation_ts_local,
  system_version,
  actual_mcf_block_id,
  design_mcf_block_id,
  dw_logical_delete_flag,
  dw_load_ts,
  dw_modify_ts
) VALUES (
  src.orig_src_id,
  src.site_code,
  src.bench,
  src.pushback,
  src.pattern_name,
  src.original_pattern_name,
  src.drill_cycle_sk,
  src.drill_hole_shift_id,
  src.drill_id,
  src.drill_bit_id,
  src.system_operator_id,
  src.drill_hole_id,
  src.drill_hole_name,
  src.drill_plan_sk,
  src.drill_hole_status,
  src.is_hole_planned_flag,
  src.start_hole_ts_utc,
  src.end_hole_ts_utc,
  src.start_hole_ts_local,
  src.end_hole_ts_local,
  src.drill_hole_duration_seconds,
  src.actual_drill_hole_depth_feet,
  src.actual_drill_hole_depth_meters,
  src.gps_accuracy,
  src.actual_drill_hole_start_feet_x,
  src.actual_drill_hole_start_feet_y,
  src.actual_drill_hole_start_feet_z,
  src.actual_drill_hole_end_feet_x,
  src.actual_drill_hole_end_feet_y,
  src.actual_drill_hole_end_feet_z,
  src.actual_drill_hole_longitude,
  src.actual_drill_hole_latitude,
  src.actual_drill_hole_start_meters_x,
  src.actual_drill_hole_start_meters_y,
  src.actual_drill_hole_start_meters_z,
  src.actual_drill_hole_end_meters_x,
  src.actual_drill_hole_end_meters_y,
  src.actual_drill_hole_end_meters_z,
  src.autodrill_duration_seconds,
  src.autodrill_usage_pct,
  src.drill_hole_penetration_rate_avg_feet_hour,
  src.operator_login_ts_utc,
  src.operator_logout_ts_utc,
  src.operator_login_ts_local,
  src.operator_logout_ts_local,
  src.bearing,
  src.drill_tower_angle_degree_calculated,
  src.drill_tower_angle_degree_system,
  src.drill_hole_duplicated_flag,
  src.drill_hole_upside_down_flag,
  src.drill_hole_start_end_time_invalid_flag,
  src.drill_hole_start_end_time_overlap_flag,
  src.drill_hole_depth_invalid_flag,
  src.drill_hole_angle_invalid_flag,
  src.drill_hole_position_invalid_flag,
  src.time_between_drill_holes_seconds,
  src.air_pressure_psi,
  src.feed_force_newtons,
  src.rotation_torque_nm,
  src.bit_speed_rpm,
  src.water_flow_gpm,
  src.instantanous_penrate_mwd_meters_hour,
  src.instantanous_penrate_mwd_feet_hour,
  src.drill_hole_off_target_feet,
  src.drill_hole_off_target_meters,
  src.drill_hole_horizontal_accuracy_pct,
  src.drill_hole_vertical_accuracy_pct,
  src.overdrill_underdrill_flag,
  src.overdrill_underdrill_feet,
  src.overdrill_underdrill_meters,
  src.drilling_stops_count,
  src.drill_hole_redrill_flag,
  src.propel_start_ts_utc,
  src.propel_end_ts_utc,
  src.park_position_start_ts_utc,
  src.park_position_end_ts_utc,
  src.level_start_ts_utc,
  src.level_end_ts_utc,
  src.drill_start_ts_utc,
  src.drill_end_ts_utc,
  src.retract_start_ts_utc,
  src.retract_end_ts_utc,
  src.propel_start_ts_local,
  src.propel_end_ts_local,
  src.park_position_start_ts_local,
  src.park_position_end_ts_local,
  src.level_start_ts_local,
  src.level_end_ts_local,
  src.drill_start_ts_local,
  src.drill_end_ts_local,
  src.retract_start_ts_local,
  src.retract_end_ts_local,
  src.propel_duration,
  src.park_position_duration,
  src.level_duration,
  src.drill_duration,
  src.retract_duration,
  src.system_drill_state_duration_seconds,
  src.system_setup_state_duration_seconds,
  src.system_auto_level_duration_seconds,
  src.system_auto_delevel_duration_seconds,
  src.plan_creation_ts_local,
  src.system_version,
  src.actual_mcf_block_id,
  src.design_mcf_block_id,
  src.dw_logical_delete_flag,
  src.dw_load_ts,
  src.dw_modify_ts
)`;

sql_merge = `/* snowrefactor_tag=${tag} step=merge */\n` + sql_merge;

// 3) Archive missing rows: use NOT EXISTS (anti-join) and scope to the same window.
var sql_archive = `UPDATE SANDBOX_DATA_ENGINEER.CCARRILL2.DRILLBLAST_DRILL_CYCLE_CT_REF tgt
SET dw_logical_delete_flag = 'Y',
    dw_modify_ts = CURRENT_TIMESTAMP(0)::TIMESTAMP_NTZ
WHERE tgt.dw_logical_delete_flag = 'N'
  AND tgt.START_HOLE_TS_LOCAL::DATE >= ${cutoff}
  AND NOT EXISTS (
    SELECT 1
    FROM prod_target.collections.drillblast_drill_cycle_dt dt
    WHERE dt.orig_src_id = tgt.orig_src_id
      AND dt.site_code = tgt.site_code
      AND dt.drill_hole_shift_id = tgt.drill_hole_shift_id
      AND dt.system_version = tgt.system_version
      AND dt.drill_id = tgt.drill_id
      AND dt.drill_hole_id = tgt.drill_hole_id
  )`;

sql_archive = `/* snowrefactor_tag=${tag} step=archive */\n` + sql_archive;

try {
  snowflake.execute({sqlText: "BEGIN"});

  var delete_old_meta = runStep("delete_old", sql_delete_old);
  timings.push(delete_old_meta);
  var deleted_old = delete_old_meta.rows_affected;

  var merge_meta = runStep("merge", sql_merge);
  timings.push(merge_meta);
  var merged = merge_meta.rows_affected;

  var archive_meta = runStep("archive", sql_archive);
  timings.push(archive_meta);
  var archived = archive_meta.rows_affected;

  snowflake.execute({sqlText: "COMMIT"});

  sp_result = `Execution complete (refactor). days=${days}, deleted_old=${deleted_old}, merged=${merged}, archived=${archived}, tag_in_sql_comment=${tag}, timings=${JSON.stringify(timings)}`;
  return sp_result;
} catch (err) {
  snowflake.execute({sqlText: "ROLLBACK"});
  // Preserve observability data even on failure.
  sp_result = `Execution failed (refactor). tag_in_sql_comment=${tag}. ${err}`;
  return sp_result;
}
$$
;