

/******************************************************************    
* PROCEDURE : [CER].[UPSERT_CONOPS_PLAN_VALUES_SHOVEL]   
* PURPOSE : Upsert [UPSERT_CONOPS_PLAN_VALUES_SHOVEL]  
* NOTES     :   
* CREATED : mfahmi  
* SAMPLE    : EXEC CER.[UPSERT_CONOPS_PLAN_VALUES_SHOVEL]  
* MODIFIED DATE  AUTHOR    DESCRIPTION    
*------------------------------------------------------------------    
* {13 FEB 2023}  {mfahmi}   {Initial Created}    
* {01 MAR 2023}  {MFAHMI}   {ADD COLUMN SITEFLAG}   
* {05 DEC 2023}  {GGOSAL1}  {Add: update table monitoring}
*******************************************************************/    
CREATE  PROCEDURE [cer].[UPSERT_CONOPS_PLAN_VALUES_SHOVEL]  
AS  
BEGIN  
  
MERGE CER.PLAN_VALUES_SHOVEL AS T   
USING (SELECT 
'CER' AS SITEFLAG, 
CONTENTTYPEID,
TITLE,
COMPLIANCEASSETID,
FECHA,
TURNO,
PROCESO,
PALA,
NIVEL,
FASE,
TONELADAS,
PROPORCION,
TCU,
REC,
MOLY,
ASCU,
CNCU,
FEPPM,
ASPPM,
BWIKWHTC,
UCSMPA,
RQD,
SCLAY,
KAO,
TOTALCLAY,
OXID,
MAGD,
[IS],
PRIORIDADPALA,
TON_REMANENTE,
ID,
CONTENTTYPE,
MODIFIED,
CREATED,
CREATEDBYID,
MODIFIEDBYID,
OWSHIDDENVERSION,
VERSION,
PATH,
getutcdate() UTC_CREATED_DATE   
 FROM CER.PLAN_VALUES_SHOVEL_stg) AS S   
 ON (T.Id = S.Id AND T.SITEFLAG = S.SITEFLAG)   
  
 WHEN MATCHED   
 THEN UPDATE SET  
T.CONTENTTYPEID = S.CONTENTTYPEID
,T.TITLE = S.TITLE
,T.COMPLIANCEASSETID = S.COMPLIANCEASSETID
,T.FECHA = S.FECHA
,T.TURNO = S.TURNO
,T.PROCESO = S.PROCESO
,T.PALA = S.PALA
,T.NIVEL = S.NIVEL
,T.FASE = S.FASE
,T.TONELADAS = S.TONELADAS
,T.PROPORCION = S.PROPORCION
,T.TCU = S.TCU
,T.REC = S.REC
,T.MOLY = S.MOLY
,T.ASCU = S.ASCU
,T.CNCU = S.CNCU
,T.FEPPM = S.FEPPM
,T.ASPPM = S.ASPPM
,T.BWIKWHTC = S.BWIKWHTC
,T.UCSMPA = S.UCSMPA
,T.RQD = S.RQD
,T.SCLAY = S.SCLAY
,T.KAO = S.KAO
,T.TOTALCLAY = S.TOTALCLAY
,T.OXID = S.OXID
,T.MAGD = S.MAGD
,T.[IS] = S.[IS]
,T.PRIORIDADPALA = S.PRIORIDADPALA
,T.TON_REMANENTE = S.TON_REMANENTE
--,T.ID = S.ID
,T.CONTENTTYPE = S.CONTENTTYPE
,T.MODIFIED = S.MODIFIED
,T.CREATED = S.CREATED
,T.CREATEDBYID = S.CREATEDBYID
,T.MODIFIEDBYID = S.MODIFIEDBYID
,T.OWSHIDDENVERSION = S.OWSHIDDENVERSION
,T.VERSION = S.VERSION
,T.PATH = S.PATH
,T.UTC_CREATED_DATE = S.UTC_CREATED_DATE
 
 WHEN NOT MATCHED   
 THEN INSERT ( 
 SITEFLAG,
 CONTENTTYPEID,
TITLE,
COMPLIANCEASSETID,
FECHA,
TURNO,
PROCESO,
PALA,
NIVEL,
FASE,
TONELADAS,
PROPORCION,
TCU,
REC,
MOLY,
ASCU,
CNCU,
FEPPM,
ASPPM,
BWIKWHTC,
UCSMPA,
RQD,
SCLAY,
KAO,
TOTALCLAY,
OXID,
MAGD,
[IS],
PRIORIDADPALA,
TON_REMANENTE,
ID,
CONTENTTYPE,
MODIFIED,
CREATED,
CREATEDBYID,
MODIFIEDBYID,
OWSHIDDENVERSION,
VERSION,
PATH,
UTC_CREATED_DATE
  ) VALUES(   
  S.SITEFLAG,
  S.CONTENTTYPEID,
S.TITLE,
S.COMPLIANCEASSETID,
S.FECHA,
S.TURNO,
S.PROCESO,
S.PALA,
S.NIVEL,
S.FASE,
S.TONELADAS,
S.PROPORCION,
S.TCU,
S.REC,
S.MOLY,
S.ASCU,
S.CNCU,
S.FEPPM,
S.ASPPM,
S.BWIKWHTC,
S.UCSMPA,
S.RQD,
S.SCLAY,
S.KAO,
S.TOTALCLAY,
S.OXID,
S.MAGD,
S.[IS],
S.PRIORIDADPALA,
S.TON_REMANENTE,
S.ID,
S.CONTENTTYPE,
S.MODIFIED,
S.CREATED,
S.CREATEDBYID,
S.MODIFIEDBYID,
S.OWSHIDDENVERSION,
S.VERSION,
S.PATH,
S.UTC_CREATED_DATE
 ); 
 
 
  --remove    
DELETE  
FROM  CER.PLAN_VALUES_SHOVEL    
WHERE NOT EXISTS  
(SELECT 1  
FROM  CER.PLAN_VALUES_SHOVEL_STG  AS stg   
WHERE   
stg.Id = CER.PLAN_VALUES_SHOVEL.Id 
);

--Update Table Monitoring
UPDATE [dbo].[DI_JOB_CONTROL_ENTRY_TS_BASE]
SET dw_load_ts = GETUTCDATE()
WHERE job_name = 'CER_SP_To_SQLMI_PlanValuesShovel'
   
END  
  

