CREATE VIEW [BAG].[CONOPS_BAG_DRILL_OPERATOR_CONSECUTIVE_WORKDAYS_V] AS



-- SELECT * FROM [bag].[CONOPS_BAG_DRILL_OPERATOR_CONSECUTIVE_WORKDAYS_V] WITH (NOLOCK) WHERE Shiftflag = 'PREV'
CREATE VIEW [bag].[CONOPS_BAG_DRILL_OPERATOR_CONSECUTIVE_WORKDAYS_V] 
AS

	SELECT LASTSHIFTINDEX AS Shiftindex,
		   SITE_CODE,
		   OPERID,
		   NROFDAYS
	FROM dbo.OPERATOR_CONSECUTIVE_WORKDAYS WITH (NOLOCK)
	WHERE SITE_CODE = 'BAG' AND UNIT_CODE = 12



