CREATE VIEW [BAG].[CONOPS_BAG_EQMT_TOTALMATERIALDELIVERED_V] AS
  
   
--SELECT * FROM [bag].[CONOPS_BAG_EQMT_TOTALMATERIALDELIVERED_V]   
CREATE VIEW [bag].[CONOPS_BAG_EQMT_TOTALMATERIALDELIVERED_V]    
AS    
    
WITH CTE AS (  
SELECT  
 SITE_CODE AS SITEFLAG,  
 SHIFT_ID AS SHIFTID,  
 TRUCK_NAME AS TRUCKID,  
COALESCE(SUM(REPORT_PAYLOAD_SHORT_TONS),0) AS Tons  
FROM BAG.FLEET_TRUCK_CYCLE_V WITH (NOLOCK) 
GROUP BY SITE_CODE, SHIFT_ID, TRUCK_NAME   
)  
  
SELECT  
 a.siteflag,  
 a.shiftid,  
 TruckId,  
 Tons AS TotalMaterialDelivered  
FROM [bag].[CONOPS_BAG_SHIFT_INFO_V] a  
LEFT JOIN CTE b on a.shiftid = b.shiftid  
WHERE Truckid IS NOT NULL  
    
  
