CREATE VIEW [BAG].[CONOPS_BAG_PAYLOAD_MEASURETON_V] AS

--select * from [BAG].[CONOPS_BAG_PAYLOAD_MEASURETON_V]
CREATE VIEW [BAG].[CONOPS_BAG_PAYLOAD_MEASURETON_V]
AS

SELECT
	SITE_CODE AS SITEFLAG,
	SHIFT_ID AS SHIFTID,
	TRUCK_NAME AS TRUCK,
	SHOVEL_NAME AS EXCAV,
	MEASURED_PAYLOAD_SHORT_TONS AS MEASURETON,
	REPORT_PAYLOAD_SHORT_TONS AS PayloadTarget
FROM BAG.FLEET_SHOVEL_CYCLE_V a
WHERE PayloadFilter = 1

