CREATE VIEW [SAF].[CONOPS_SAF_SHIFT_BASE_TARGET_V] AS

--select * from [SAF].[CONOPS_SAF_SHIFT_BASE_TARGET_V] 
CREATE VIEW [saf].[CONOPS_SAF_SHIFT_BASE_TARGET_V]
AS

SELECT
	SITEFLAG,
	CAST(
		RIGHT(CAST(YEAR(DATEEFFECTIVE) AS VARCHAR), 2) +
		RIGHT('0' + CAST(MONTH(DATEEFFECTIVE) AS VARCHAR), 2) +
		RIGHT('0' + CAST(DAY(DATEEFFECTIVE) AS VARCHAR), 2) +
		RIGHT('000' + CAST(SHIFTINDEX AS VARCHAR), 3) AS NUMERIC) 
	AS ShiftId,
	TOTALMINETPD AS TonsMinedTarget,
	TOTALLSTPD AS TonsMovedTarget
FROM SAF.PLAN_VALUES WITH(NOLOCK)

