CREATE VIEW [SAF].[EQUIPMENT_HOURLY_STATUS] AS

--SELECT * FROM SAF.EQUIPMENT_HOURLY_STATUS
CREATE VIEW SAF.EQUIPMENT_HOURLY_STATUS
AS

SELECT *
FROM SAF.EQUIPMENT_HOURLY_STATUS_2 WITH(NOLOCK)

