CREATE VIEW [SAF].[PIT_WORKER] AS



--SELECT * FROM SAF.PIT_WORKER
CREATE VIEW SAF.PIT_WORKER
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM SAFOperational.dbo.PITWorker



