CREATE VIEW [SAF].[PIT_LOC] AS



--SELECT * FROM SAF.PIT_LOC
CREATE VIEW SAF.PIT_LOC
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM SAFOperational.dbo.PITPitLoc WITH(NOLOCK)



