CREATE VIEW [SAF].[SHIFT_EQMT] AS




--SELECT * FROM SAF.SHIFT_EQMT
CREATE VIEW SAF.SHIFT_EQMT
AS

SELECT
'SAF' AS SiteFlag,
*
FROM SAFOperational.dbo.SHIFTShifteqmt WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM SAF.SHIFT_INFO)




