CREATE VIEW [SAF].[SHIFT_LOAD] AS



--SELECT * FROM SAF.SHIFT_LOAD
CREATE VIEW SAF.SHIFT_LOAD
AS

SELECT
'SAF' AS SiteFlag,
*
FROM SAFOperational.dbo.SHIFTShiftload WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM SAF.SHIFT_INFO)



