CREATE VIEW [SAF].[SHIFT_OPER] AS




--SELECT * FROM SAF.SHIFT_OPER
CREATE VIEW SAF.SHIFT_OPER
AS

SELECT
'SAF' AS SiteFlag,
*
FROM SAFOperational.dbo.SHIFTShiftOper WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM SAF.SHIFT_INFO)




