CREATE TABLE [TYR].[PLAN_VALUES] (
    [SiteFlag] varchar(5) NOT NULL,
    [FormatShiftId] varchar(50) NULL,
    [ContentTypeID] varchar(100) NOT NULL,
    [Title] varchar(50) NULL,
    [ColorTag] varchar(100) NULL,
    [ComplianceAssetID] varchar(100) NULL,
    [Date] datetime NULL,
    [Shift] decimal(18,5) NULL,
    [MiningRateWaste] decimal(18,5) NULL,
    [MiningRateROM] decimal(18,5) NULL,
    [TruckPayloadTons] decimal(18,5) NULL,
    [LoadingUnit] varchar(50) NULL,
    [DeltaCMins] decimal(18,5) NULL,
    [IdleTimeMin] decimal(18,5) NULL,
    [SpotTimeMin] decimal(18,5) NULL,
    [LoadTimeMin] decimal(18,5) NULL,
    [DumpTimeMin] decimal(18,5) NULL,
    [OutTravelMins] decimal(18,5) NULL,
    [InTravelMins] decimal(18,5) NULL,
    [EFH] decimal(18,5) NULL,
    [Id] int NOT NULL,
    [ContentType] varchar(50) NOT NULL,
    [Modified] datetime NOT NULL,
    [Created] datetime NOT NULL,
    [CreatedById] int NOT NULL,
    [ModifiedById] int NOT NULL,
    [Owshiddenversion] int NOT NULL,
    [Version] decimal(10,5) NOT NULL,
    [Path] varchar(2000) NOT NULL,
    [UTC_CREATED_DATE] datetime NULL
);