CREATE VIEW [saf].[CONOPS_SAF_SUPPORT_EQMT_OPERATOR_CONSECUTIVE_WORKDAYS_V] AS

  -- SELECT * FROM [SAF].[CONOPS_SAF_SUPPORT_EQMT_OPERATOR_CONSECUTIVE_WORKDAYS_V] WITH (NOLOCK) 
CREATE VIEW [SAF].[CONOPS_SAF_SUPPORT_EQMT_OPERATOR_CONSECUTIVE_WORKDAYS_V]   
AS  
  
SELECT 
LASTSHIFTINDEX AS Shiftindex,  
SITE_CODE,  
OPERID,  
NROFDAYS  
FROM dbo.OPERATOR_CONSECUTIVE_WORKDAYS WITH (NOLOCK)  
WHERE SITE_CODE = 'SAF' AND UNIT_CODE NOT IN ('1','2','12')
  
