CREATE VIEW [saf].[CONOPS_SAF_EQMT_TIME_CATEGORY_V] AS


--select * from [SAF].[CONOPS_SAF_EQMT_TIME_CATEGORY_V] WITH(NOLOCK)
CREATE VIEW [SAF].[CONOPS_SAF_EQMT_TIME_CATEGORY_V] 
AS

SELECT
	siteflag,
	shiftid,
	eqmt,
	UNITTYPE,
	SUM(ISNULL([1],0)+ISNULL([2],0)+ISNULL([3],0)+ISNULL([4],0)+ISNULL([5],0)+ISNULL([6],0)+ISNULL([7],0)+ISNULL([8],0)+ISNULL([9],0)) AS TMCAT_00,
	ISNULL(SUM([1]),0) AS TMCAT_01,
	ISNULL(SUM([2]),0) AS TMCAT_02,
	ISNULL(SUM([3]),0) AS TMCAT_03,
	ISNULL(SUM([4]),0) AS TMCAT_04,
	ISNULL(SUM([5]),0) AS TMCAT_05,
	ISNULL(SUM([6]),0) AS TMCAT_06,
	ISNULL(SUM([7]),0) AS TMCAT_07,
	ISNULL(SUM([8]),0) AS TMCAT_08,
	ISNULL(SUM([9]),0) AS TMCAT_09
FROM(
SELECT
	siteflag,
	shiftid,
	EQMT,
	UNITTYPE,
	CATEGORYIDX,
	DURATION
FROM SAF.ASSET_EFFICIENCY WITH(NOLOCK)
) t
PIVOT(
    SUM(DURATION) 
    FOR CATEGORYIDX IN ([1],[2],[3],[4],[5],[6],[7],[8],[9])
) AS pivot_table
GROUP BY siteflag,
shiftid,
eqmt,
UNITTYPE

