CREATE VIEW [saf].[CONOPS_SAF_DB_DRILL_SCORE_TARGET_V] AS


--select * from [saf].[CONOPS_SAF_DB_DRILL_SCORE_TARGET_V] where shiftflag = 'curr'
CREATE VIEW [saf].[CONOPS_SAF_DB_DRILL_SCORE_TARGET_V]
AS

SELECT CAST(Right([Year], 2) + FORMAT(CAST([Month] AS numeric), '00') +
		FORMAT(CAST([Day] AS numeric), '00') + FORMAT(CAST(SHIFT_CODE AS numeric), '000') AS numeric) [ShiftId],
	   'SAF' AS [siteflag],
	   [DRILLAVAILABILITY],
	   [DRILLASSETEFFICIENCY],
	   [DRILLUTILIZATION],
	   [TARGETFEETDRILLED],
	   [TARGETHOLESDRILLED]
FROM (
	SELECT REVERSE(PARSENAME(REPLACE(REVERSE(DATEEFFECTIVE), '-', '.'), 1)) AS [Year],
		   REVERSE(PARSENAME(REPLACE(REVERSE(DATEEFFECTIVE), '-', '.'), 2)) AS [Month],
		   REVERSE(PARSENAME(REPLACE(REVERSE(DATEEFFECTIVE), '-', '.'), 3)) AS [Day],
		   Shiftindex AS [SHIFT_CODE],
		   ISNULL([DRILLAVAIL], 0) AS [DRILLAVAILABILITY],
		   ISNULL([DRILLAE], 0) AS [DRILLASSETEFFICIENCY],
		   ISNULL([DRILLUA], 0) AS [DRILLUTILIZATION],
		   ISNULL(FEETDRILLED, 0) AS [TARGETFEETDRILLED],
		   ISNULL(HOLESDRILLED, 0) AS [TARGETHOLESDRILLED]
    FROM [saf].[PLAN_VALUES] (NOLOCK)
) [target]

