CREATE VIEW [saf].[CONOPS_SAF_DB_DRILL_ASSET_EFFICIENCY_TARGET_V] AS

  
--SELECT * FROM [SAF].[CONOPS_SAF_DB_DRILL_ASSET_EFFICIENCY_TARGET_V] WHERE SHIFTFLAG = 'CURR'  
CREATE VIEW [SAF].[CONOPS_SAF_DB_DRILL_ASSET_EFFICIENCY_TARGET_V]  
AS  
  
SELECT CAST(RIGHT([YEAR], 2) + FORMAT(CAST([MONTH] AS NUMERIC), '00') +  
  FORMAT(CAST([DAY] AS NUMERIC), '00') + FORMAT(CAST(SHIFT_CODE AS NUMERIC), '000') AS NUMERIC) [SHIFTID],  
    'SAF' AS [SITEFLAG],  
    [DRILLAVAILABILITY],  
    [DRILLASSETEFFICIENCY],  
    [DRILLUTILIZATION]  
FROM (  
 SELECT REVERSE(PARSENAME(REPLACE(REVERSE(DATEEFFECTIVE), '-', '.'), 1)) AS [YEAR],  
     REVERSE(PARSENAME(REPLACE(REVERSE(DATEEFFECTIVE), '-', '.'), 2)) AS [MONTH],  
     REVERSE(PARSENAME(REPLACE(REVERSE(DATEEFFECTIVE), '-', '.'), 3)) AS [DAY],  
     SHIFTINDEX AS [SHIFT_CODE],  
     ISNULL([DRILLAVAIL], 0) AS [DRILLAVAILABILITY],  
     ISNULL([DRILLAE], 0) AS [DRILLASSETEFFICIENCY],  
     ISNULL([DRILLUA], 0) AS [DRILLUTILIZATION]  
    FROM [SAF].[PLAN_VALUES] (NOLOCK)  
) [TARGET]  
  
