CREATE VIEW [saf].[CONOPS_SAF_CM_INTERMEDIATE_STOCKPILE_V] AS

  
  
--SELECT * FROM [saf].[CONOPS_SAF_CM_INTERMEDIATE_STOCKPILE_V] WITH (NOLOCK) WHERE SHIFTFLAG = 'CURR'    
CREATE VIEW [saf].[CONOPS_SAF_CM_INTERMEDIATE_STOCKPILE_V]    
AS    


WITH CTE AS (
SELECT 
	shiftindex,
	CRUSHERLOC,
	COMPONENT,
	SENSORVALUE,
ROW_NUMBER() OVER (PARTITION BY SHIFTINDEX,CRUSHERLOC,COMPONENT ORDER BY VALUE_TS DESC) NUM
FROM [dbo].[IOS_STOCKPILE_LEVELS] WITH (NOLOCK)
WHERE SITEFLAG = 'SAF'
),

MFLStockpile AS(
SELECT
	SHIFTINDEX,
	SENSORVALUE AS MFLStockpile
FROM CTE
WHERE CRUSHERLOC = 'Crusher' 
	AND COMPONENT = 'CrusherStockpile'
	AND NUM = 1
),

MillStockpile AS(
SELECT
	SHIFTINDEX,
	SENSORVALUE AS MillStockpile
FROM CTE
WHERE CRUSHERLOC = '' 
	AND COMPONENT = ''
	AND NUM = 1
)


SELECT 
a.[SITEFLAG]
,a.[SHIFTFLAG]
,s.[MFLStockpile] --MFL should be hidden/ not shown for Bagdad, Chino, SAFrrita, Cerro Verde, Tyrone (only El Abra, Safford and SAFenci have MFL)
,0 AS [MillStockpile]
FROM [SAF].[CONOPS_SAF_SHIFT_INFO_V] a WITH (NOLOCK)
LEFT JOIN MFLStockpile [s] WITH (NOLOCK) 
	ON a.SHIFTINDEX = [s].SHIFTINDEX
LEFT JOIN MillStockpile [m] WITH (NOLOCK) 
ON a.SHIFTINDEX = [m].SHIFTINDEX
  

