CREATE VIEW [saf].[CONOPS_SAF_CRUSHER_STATUS_DETAIL_V] AS



--SELECT * FROM [SAF].[CONOPS_SAF_CRUSHER_STATUS_DETAIL_V]
CREATE VIEW [SAF].[CONOPS_SAF_CRUSHER_STATUS_DETAIL_V]
AS

WITH CrusherStatus AS(
SELECT
	SITE_CODE,
	PLANT_AREA_NAME,
	PRODCTN_DATE,
	SHIFT_INDICATOR,
	FORMAT(PRODCTN_DATE, 'yyMMdd') AS ShiftId,
	FIRST_VALUE(START_TS) OVER (PARTITION BY PLANT_AREA_NAME, PRODCTN_DATE, SHIFT_INDICATOR 
		ORDER BY START_TS 
		ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
		AS ShiftStartDateTime,
	START_TS,
	STOP_TS,
	DOWNTIME_TYPE,
	DOWNTIME_CAT,
	PROBLEM_ID,
	CAUSE_NAME,
	WORK_ORDER_COMMENT,
	LEAD(START_TS) OVER (PARTITION BY PLANT_AREA_NAME, PRODCTN_DATE, SHIFT_INDICATOR ORDER BY START_TS) AS NextStart
FROM dbo.CRUSHER_STATUS WITH(NOLOCK)
WHERE SITE_CODE = 'SAF'
),

Final AS(
SELECT
	SITE_CODE,
	CASE PLANT_AREA_NAME
		WHEN 'Primary Crushing' THEN 'CRUSHER'
	ELSE PLANT_AREA_NAME END AS Crusher,
	CASE SHIFT_INDICATOR
		WHEN 'DAY' THEN CONCAT(ShiftId, '001')
		WHEN 'NIGHT' THEN CONCAT(ShiftId, '002')
	ELSE NULL END AS ShiftId,
	ShiftStartDateTime,
	DATEADD(HOUR, 12, ShiftStartDateTime) AS ShiftEndDateTime,
	START_TS,
	STOP_TS,
	DATEDIFF(MINUTE, START_TS, STOP_TS) AS TimeInState,
	DOWNTIME_TYPE AS STATUS_TYPE,
	DOWNTIME_CAT AS STATUS,
	PROBLEM_ID AS REASON,
	CAUSE_NAME AS DESCRIPTION,
	WORK_ORDER_COMMENT AS COMMENT,
	LAST_VALUE(DOWNTIME_CAT) OVER (PARTITION BY PLANT_AREA_NAME, PRODCTN_DATE, SHIFT_INDICATOR 
		ORDER BY START_TS 
		ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
		AS CurrentStatus
FROM CrusherStatus
WHERE STOP_TS = NextStart
OR NextStart IS NULL
)

SELECT
	f.SITE_CODE,
	s.shiftflag,
	f.ShiftId,
	f.ShiftStartDateTime,
	f.ShiftEndDateTime,
	f.Crusher,
	f.START_TS,
	f.STOP_TS,
	f.TimeInState,
	f.STATUS_TYPE,
	f.STATUS,
	f.REASON,
	f.DESCRIPTION,
	f.COMMENT,
	f.CurrentStatus
FROM Final f
LEFT JOIN SAF.CONOPS_SAF_SHIFT_INFO_V s
	ON s.shiftid = f.ShiftId



