CREATE VIEW [saf].[CONOPS_SAF_ALERT_V] AS


-- SELECT * FROM [SAF].[CONOPS_SAF_ALERT_V] WITH (NOLOCK) WHERE shiftflag = 'CURR'
CREATE VIEW [SAF].[CONOPS_SAF_ALERT_V]
AS

	SELECT si.SHIFTFLAG
		  ,si.[SITEFLAG]
		  ,[EQMT_TYPE]
		  ,[EQMTID]
		  ,[OPERATOR_ID]
		  ,[ALERT_TYPE]
		  ,[ALERT_NAME]
		  ,[ALERT_DESCRIPTION]
		  ,[ALERT_DATE]
		  ,[DURATION]
		  ,[ALERT_GENERATED_DATETIME]
		  ,[UTC_CREATED_DATE]
	FROM [SAF].[CONOPS_SAF_SHIFT_INFO_V] si (NOLOCK)
	LEFT JOIN [SAF].[ALERT] a (NOLOCK)
	ON a.SHIFTINDEX = si.SHIFTINDEX
	   AND a.SITEFLAG = si.SITEFLAG

