CREATE TABLE [mor].[plan_hole] (
    [Id] varchar(36) NOT NULL,
    [DrillPlanId] varchar(36) NOT NULL,
    [HoleId] varchar(24) NULL,
    [OriginalHoleId] varchar(24) NULL,
    [RigSerialNumber] varchar(64) NULL,
    [StartPointX] decimal(19,0) NOT NULL,
    [StartPointY] decimal(19,0) NOT NULL,
    [StartPointZ] decimal(19,0) NOT NULL,
    [EndPointX] decimal(19,0) NOT NULL,
    [EndPointY] decimal(19,0) NOT NULL,
    [EndPointZ] decimal(19,0) NOT NULL,
    [TypeOfHole] int NOT NULL,
    [HoleStatus] int NOT NULL,
    [DrillBitDiameter] int NOT NULL,
    [DrillBitType] int NOT NULL,
    [MeasureWhileDrilling] bit NOT NULL,
    [DrillBitChange] decimal(19,0) NOT NULL,
    [IsDeleted] bit NOT NULL,
    [HoleName] varchar(256) NULL,
    [RawStartPointX] decimal(19,0) NOT NULL,
    [RawStartPointY] decimal(19,0) NOT NULL,
    [RawStartPointZ] decimal(19,0) NOT NULL,
    [RawEndPointX] decimal(19,0) NOT NULL,
    [RawEndPointY] decimal(19,0) NOT NULL,
    [RawEndPointZ] decimal(19,0) NOT NULL,
    [UTC_CREATED_DATE] datetime NOT NULL,
    [UTC_LOGICAL_DELETED_DATE] datetime NULL
);