CREATE TABLE [mor].[target_prod_summary_stg] (
    [Plan Name] varchar(30) NOT NULL,
    [Date Effective] date NULL,
    [Total Ore tpd] int NULL,
    [Total AC23 tpd] int NULL,
    [Total AC4 tpd] int NULL,
    [Total EH tpd] int NULL,
    [Total HG tpd] int NULL,
    [Total LG tpd] int NULL,
    [Total Oxide tpd] int NULL,
    [Total ROM tpd] int NULL,
    [Total Waste tpd] int NULL,
    [Total Ex-Pit tpd] int NULL,
    [Transfer Ore MFL] int NULL,
    [Transfer Ore Mill] int NULL,
    [Total Inpit Dump] int NULL,
    [Total Mined tpd] int NULL,
    [Total Moved tpd] int NULL,
    [Crusher MFL tpd] int NULL,
    [Crusher Mill tpd] int NULL,
    [910 tpd] int NULL,
    [Pit AMT tpd] int NULL,
    [Pit COR tpd] int NULL,
    [Pit FBK tpd] int NULL,
    [Pit GAR tpd] int NULL,
    [Pit LON tpd] int NULL,
    [Pit SHA tpd] int NULL,
    [Pit SUN tpd] int NULL,
    [Pit WCP tpd] int NULL,
    [Pit WCP 14 tpd] int NULL,
    [Pit WCP 10 tpd] int NULL,
    [Loading Availability] int NULL,
    [Loading Asset Efficiency] int NULL,
    [Truck Availability] int NULL,
    [Truck Asset Efficiency] float NULL,
    [Avg Count Ready Trucks] int NULL,
    [Equivalent Flat Haul] int NULL,
    [Empty EFH] int NULL,
    [Empty Travel Miles] int NULL,
    [Loaded Travel Miles] int NULL,
    [Total Cycle Time] int NULL,
    [Delta C] int NULL,
    [ElecShovelLoadTonsOnReadyHour] int NULL,
    [ElecShovelAvailability] int NULL,
    [ElecShovelAssetEfficiency] int NULL,
    [ElecShovelUseOfAvailability] int NULL,
    [ElecShovelAvgReadyNumber] int NULL,
    [HydShovelLoadTonsOnReadyHour] int NULL,
    [HydShovelAvailability] int NULL,
    [HydShovelAssetEfficiency] float NULL,
    [HydShovelUseOfAvailability] float NULL,
    [HydShovelAvgReadyNumber] int NULL,
    [EmptyOneWayHaul] float NULL,
    [EmptyLifts] float NULL,
    [EmptyDrops] int NULL,
    [Spoting] float NULL,
    [Loading] float NULL,
    [LoadedTravel] float NULL,
    [DumpingAtCrusher] float NULL,
    [DumpingatStockpile] float NULL,
    [EmptyTravel] float NULL,
    [EFH_GAR] int NULL,
    [EFH_SUN] int NULL,
    [EFH_WCP] int NULL,
    [Crrrr] int NULL,
    [TrkDumpTnReadyHr] int NULL,
    [WCPDeltaC] int NULL,
    [SUNDeltaC] int NULL,
    [GARDeltaC] int NULL,
    [TotalLoadTnsReadyHr] int NULL,
    [TotalDumpTnsReadyHr] int NULL,
    [TruckUtil] int NULL,
    [FuelBurnGal] float NULL,
    [FuelBurnHr] float NULL,
    [TireMiles] int NULL,
    [FrontTireRot] int NULL,
    [RockCut%] float NULL,
    [Miles/32nd] int NULL,
    [MTBME] int NULL,
    [Haulage $/ton] float NULL,
    [Fuel $/ton] float NULL,
    [MTTR] int NULL,
    [%OverExpected(DeltaC)] float NULL,
    [%Loaded] float NULL,
    [%Empty] float NULL,
    [Ready Drills] int NULL,
    [Drill Holes per Day] int NULL,
    [Delta C Loaded Travel] float NULL,
    [Delta C Empty Travel] float NULL,
    [Delta C Dump - Cr] float NULL,
    [Delta C Dump - Stk] float NULL,
    [AMT Tons] int NULL,
    [P10 Tons] int NULL,
    [P14 Tons] int NULL,
    [COR Tons] int NULL,
    [UTC_CREATED_DATE] datetime NULL,
    [LOGICAL_DELETED_FLAG] varchar(1) NULL
);