CREATE TABLE [mor].[XECUTE_PLAN_VALUES] (
    [Pit] varchar(255) NOT NULL,
    [Bench] varchar(255) NOT NULL,
    [Destination] varchar(255) NOT NULL,
    [Material] varchar(255) NOT NULL,
    [Shovel] varchar(255) NOT NULL,
    [PeriodStart] datetime NOT NULL,
    [PeriodFinish] datetime NOT NULL,
    [PeriodName] varchar(255) NOT NULL,
    [FormatShiftId] varchar(255) NOT NULL,
    [PolygonType] varchar(255) NOT NULL,
    [PolygonName] varchar(255) NOT NULL,
    [Ton] float NULL,
    [DTCUxTon] float NULL,
    [MKSxTon] float NULL,
    [MLTxTon] float NULL,
    [PYRxTon] float NULL,
    [RDTCUxTon] float NULL,
    [TCUxTon] float NULL,
    [TMOxTon] float NULL,
    [XCUxTon] float NULL,
    [XDIVTxTon] float NULL,
    [TruckHours] float NULL,
    [EFHxTon] float NULL,
    [CycleTimexTon] float NULL,
    [NetVal_Mill] float NULL,
    [NetVal_MFL] float NULL,
    [NetVal_MillReh] float NULL,
    [NetVal_MFLReh] float NULL,
    [NetVal_HG] float NULL,
    [NetVal_LG] float NULL,
    [NetVal_OX] float NULL,
    [NetVal_MEH] float NULL,
    [NetVal_AcidConsume] float NULL,
    [NetVal_Waste] float NULL,
    [dw_load_ts] datetime NOT NULL
);