CREATE TABLE [mor].[ZZZ_PLAN_VALUES_back202302] (
    [Formatshiftid] varchar(50) NULL,
    [ContentTypeID] varchar(100) NULL,
    [ShiftID] varchar(50) NULL,
    [ComplianceAssetId] varchar(100) NULL,
    [Shovel] varchar(50) NULL,
    [PB] varchar(50) NULL,
    [Level] int NULL,
    [Destination] varchar(50) NULL,
    [MaterialType] varchar(50) NULL,
    [Tons] decimal(18,5) NULL,
    [DTCU] decimal(18,5) NULL,
    [Mo] decimal(18,5) NULL,
    [EFH] decimal(18,5) NULL,
    [Id] int NOT NULL,
    [ContentType] varchar(50) NULL,
    [Modified] datetime NULL,
    [Created] datetime NULL,
    [CreatedById] int NULL,
    [ModifiedById] int NULL,
    [Owshiddenversion] int NULL,
    [Version] decimal(18,5) NULL,
    [Path] varchar(2000) NULL,
    [UTC_CREATED_DATE] datetime NULL
);