CREATE TABLE [mor].[ZZZ_DRILL_UTILIZATION_back202303] (
    [SITE_CODE] varchar(4) NULL,
    [SHIFTINDEX] numeric(38,0) NULL,
    [SHIFT_DATE] date NULL,
    [SHIFTSTART] time NULL,
    [SHIFTEND] time NULL,
    [SHIFT] varchar(35) NULL,
    [MACHINESTATUSCODE] real NULL,
    [EQUIPMENTNUMBER] varchar(50) NULL,
    [EQUIPMENTMODEL] varchar(35) NULL,
    [START_TIME_TS] datetime NULL,
    [END_TIME_TS] datetime NULL,
    [SHIFT_TIME] numeric(38,0) NULL,
    [HOS] numeric(38,0) NULL,
    [STARTTIME] numeric(38,0) NULL,
    [ENDTTIME] numeric(38,0) NULL,
    [STATUS_DURATION] real NULL,
    [READYTIME] real NULL,
    [OPERATIONALDOWNTIME] real NULL,
    [SCHEDULEDDOWNTIME] real NULL,
    [UNSCHEDULEDDOWNTIME] real NULL,
    [DELAYTIME] real NULL,
    [SPARETIME] real NULL,
    [SHIFTCHANGETIME] real NULL,
    [UNCLASSIFIEDTIME] numeric(38,0) NULL,
    [SOURCE_SYSTEM] varchar(20) NULL,
    [UTC_CREATED_DATE] datetime NULL
);