CREATE VIEW [TYR].[CONOPS_TYR_CM_HOURLY_INTERMEDIATE_STOCKPILE_V] AS



--SELECT * FROM [tyr].[CONOPS_TYR_CM_HOURLY_INTERMEDIATE_STOCKPILE_V] WITH (NOLOCK) WHERE SHIFTFLAG = 'CURR'    
CREATE VIEW [TYR].[CONOPS_TYR_CM_HOURLY_INTERMEDIATE_STOCKPILE_V]
AS    


WITH CTE AS (
SELECT 
shiftindex,
CRUSHERLOC,
COMPONENT,
SENSORVALUE,
CASE WHEN DATEPART(MINUTE,VALUE_TS) BETWEEN 15 AND 20 THEN VALUE_TS END AS TimeInHour
FROM [dbo].[IOS_STOCKPILE_LEVELS] WITH (NOLOCK)
WHERE SITEFLAG = 'TYR')


SELECT 
a.[SITEFLAG]  
,a.[SHIFTFLAG]  
,s.SENSORVALUE [MFLStockpile]  
,CAST(CONCAT(FORMAT(TimeInHour, 'yyyy-MM-dd HH'), ':15:00') AS Datetime) AS TimeInHour
FROM [tyr].[CONOPS_TYR_SHIFT_INFO_V] a WITH (NOLOCK)  
LEFT JOIN CTE [s] WITH (NOLOCK)   
ON a.SHIFTINDEX = [s].SHIFTINDEX 
--AND s.CRUSHERLOC = 'Crusher 2' AND s.COMPONENT = 'CrusherStockpile'  
WHERE TimeInHour IS NOT NULL


  



