CREATE VIEW [bag2].[VIEW_MACHINECLASS_ETL] AS

CREATE VIEW [bag2].[VIEW_MACHINECLASS_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.MACHINECLASS_OID') AS MACHINECLASS_OID,
JSON_VALUE(DATA_VALUE.value, '$.ECF_CLASS_ID') AS ECF_CLASS_ID,
JSON_VALUE(DATA_VALUE.value, '$.IS_ACTIVE') AS IS_ACTIVE,
JSON_VALUE(DATA_VALUE.value, '$.NAME') AS NAME,
JSON_VALUE(DATA_VALUE.value, '$.MANUFACTURER') AS MANUFACTURER,
JSON_VALUE(DATA_VALUE.value, '$.DESCRIPTION') AS DESCRIPTION,
JSON_VALUE(DATA_VALUE.value, '$.USEFUEL') AS USEFUEL,
JSON_VALUE(DATA_VALUE.value, '$.FUELCAPACITY') AS FUELCAPACITY,
JSON_VALUE(DATA_VALUE.value, '$.ALLOWALLMATERIALS') AS ALLOWALLMATERIALS,
JSON_VALUE(DATA_VALUE.value, '$.FUELTYPE') AS FUELTYPE,
JSON_VALUE(DATA_VALUE.value, '$.MINIMUMREFUELAMOUNT') AS MINIMUMREFUELAMOUNT,
JSON_VALUE(DATA_VALUE.value, '$.REFUELLEVEL') AS REFUELLEVEL,
JSON_VALUE(DATA_VALUE.value, '$.CRITICALFUELLEVEL') AS CRITICALFUELLEVEL,
JSON_VALUE(DATA_VALUE.value, '$.EXPECTEDDURATIONBETWEENREFUELS') AS EXPECTEDDURATIONBETWEENREFUELS,
JSON_VALUE(DATA_VALUE.value, '$.USEDYNAMICFUELBURNRATE') AS USEDYNAMICFUELBURNRATE,
JSON_VALUE(DATA_VALUE.value, '$.FUELBURNALGORITHM') AS FUELBURNALGORITHM,
JSON_VALUE(DATA_VALUE.value, '$.IDLEFUELBURNRATE') AS IDLEFUELBURNRATE,
JSON_VALUE(DATA_VALUE.value, '$.WORKINGFUELBURNRATE') AS WORKINGFUELBURNRATE,
JSON_VALUE(DATA_VALUE.value, '$.IGNORE_VIMS_FUEL_SENSOR') AS IGNORE_VIMS_FUEL_SENSOR,
JSON_VALUE(DATA_VALUE.value, '$.AUTO_STOP_DELAY_TYPE') AS AUTO_STOP_DELAY_TYPE,
JSON_VALUE(DATA_VALUE.value, '$.CATEGORY') AS CATEGORY,
JSON_VALUE(DATA_VALUE.value, '$.ONBOARD_PLATFORM_ID') AS ONBOARD_PLATFORM_ID,
JSON_VALUE(DATA_VALUE.value, '$.CONFIGURATION_NAME') AS CONFIGURATION_NAME,
JSON_VALUE(DATA_VALUE.value, '$.OPERATOR_INTERFACE') AS OPERATOR_INTERFACE,
JSON_VALUE(DATA_VALUE.value, '$.CAMERAS') AS CAMERAS,
JSON_VALUE(DATA_VALUE.value, '$.CAMERAS_AND_RADAR') AS CAMERAS_AND_RADAR,
JSON_VALUE(DATA_VALUE.value, '$.PROXIMITY_AWARENESS') AS PROXIMITY_AWARENESS,
JSON_VALUE(DATA_VALUE.value, '$.CUSTOM_CONFIGURATION') AS CUSTOM_CONFIGURATION,
JSON_VALUE(DATA_VALUE.value, '$.HEALTH_PLATFORM') AS HEALTH_PLATFORM,
JSON_VALUE(DATA_VALUE.value, '$.CANBETOWED') AS CANBETOWED,
JSON_VALUE(DATA_VALUE.value, '$.INFRASTRUCTURE') AS INFRASTRUCTURE,
JSON_VALUE(DATA_VALUE.value, '$.MAXIMUMSPEED') AS MAXIMUMSPEED,
JSON_VALUE(DATA_VALUE.value, '$.BODYWEIGHT') AS BODYWEIGHT,
JSON_VALUE(DATA_VALUE.value, '$.CHASSISWEIGHT') AS CHASSISWEIGHT,
JSON_VALUE(DATA_VALUE.value, '$.DUMPHEIGHT') AS DUMPHEIGHT,
JSON_VALUE(DATA_VALUE.value, '$.FRONTDISTRIBUTIONEMPTY') AS FRONTDISTRIBUTIONEMPTY,
JSON_VALUE(DATA_VALUE.value, '$.FRONTDISTRIBUTIONLOADED') AS FRONTDISTRIBUTIONLOADED,
JSON_VALUE(DATA_VALUE.value, '$.FRONTTYRETREAD') AS FRONTTYRETREAD,
JSON_VALUE(DATA_VALUE.value, '$.GROSSVEHICLEWEIGHT') AS GROSSVEHICLEWEIGHT,
JSON_VALUE(DATA_VALUE.value, '$.HEAPEDCAPACITY') AS HEAPEDCAPACITY,
JSON_VALUE(DATA_VALUE.value, '$.HEIGHTTOCANOPYROCKGUARDRAIL') AS HEIGHTTOCANOPYROCKGUARDRAIL,
JSON_VALUE(DATA_VALUE.value, '$.LOADINGHEIGHT') AS LOADINGHEIGHT,
JSON_VALUE(DATA_VALUE.value, '$.MAXPAYLOAD') AS MAXPAYLOAD,
JSON_VALUE(DATA_VALUE.value, '$.MAXSPEEDLOADED') AS MAXSPEEDLOADED,
JSON_VALUE(DATA_VALUE.value, '$.NOMINALPAYLOAD') AS NOMINALPAYLOAD,
JSON_VALUE(DATA_VALUE.value, '$.OVERLOAD') AS OVERLOAD,
JSON_VALUE(DATA_VALUE.value, '$.PAYLOADACCURACY') AS PAYLOADACCURACY,
JSON_VALUE(DATA_VALUE.value, '$.PAYLOADWITHSTDLINEARWEIGHT') AS PAYLOADWITHSTDLINEARWEIGHT,
JSON_VALUE(DATA_VALUE.value, '$.PRODMANSYSMOD') AS PRODMANSYSMOD,
JSON_VALUE(DATA_VALUE.value, '$.REARDISTRIBUTIONEMPTY') AS REARDISTRIBUTIONEMPTY,
JSON_VALUE(DATA_VALUE.value, '$.REARDISTRIBUTIONLOADED') AS REARDISTRIBUTIONLOADED,
JSON_VALUE(DATA_VALUE.value, '$.STANDARDLINEARWEIGHT') AS STANDARDLINEARWEIGHT,
JSON_VALUE(DATA_VALUE.value, '$.STRUCKCAPACITY') AS STRUCKCAPACITY,
JSON_VALUE(DATA_VALUE.value, '$.UNDERLOAD') AS UNDERLOAD,
JSON_VALUE(DATA_VALUE.value, '$.WHEELBASE') AS WHEELBASE,
J