CREATE VIEW [bag2].[VIEW_MACHINE_IN_PIT_ETL] AS

CREATE VIEW [bag2].[VIEW_MACHINE_IN_PIT_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.MACHINE_OID') AS MACHINE_OID,
JSON_VALUE(DATA_VALUE.value, '$.CLASS_NAME') AS CLASS_NAME,
JSON_VALUE(DATA_VALUE.value, '$.STATUS') AS STATUS,
JSON_VALUE(DATA_VALUE.value, '$.STATUS_LAST_UPDATED_UTC') AS STATUS_LAST_UPDATED_UTC,
JSON_VALUE(DATA_VALUE.value, '$.SOFT_STATE') AS SOFT_STATE,
JSON_VALUE(DATA_VALUE.value, '$.LOCATION_OID') AS LOCATION_OID,
JSON_VALUE(DATA_VALUE.value, '$.LOCATION_LAST_UPDATED_UTC') AS LOCATION_LAST_UPDATED_UTC,
JSON_VALUE(DATA_VALUE.value, '$.WAYPOINT_OID') AS WAYPOINT_OID,
JSON_VALUE(DATA_VALUE.value, '$.WAYPOINT_LAST_UPDATED_UTC') AS WAYPOINT_LAST_UPDATED_UTC,
JSON_VALUE(DATA_VALUE.value, '$.TIME_AT_WAYPOINT_UTC') AS TIME_AT_WAYPOINT_UTC,
JSON_VALUE(DATA_VALUE.value, '$.CURRENT_OPERATOR_OID') AS CURRENT_OPERATOR_OID,
JSON_VALUE(DATA_VALUE.value, '$.CURR_OPERATOR_LAST_UPDATED_UTC') AS CURR_OPERATOR_LAST_UPDATED_UTC,
JSON_VALUE(DATA_VALUE.value, '$.TIME_TILL_REFUEL') AS TIME_TILL_REFUEL,
JSON_VALUE(DATA_VALUE.value, '$.TIME_TILL_CRIT_REFUEL') AS TIME_TILL_CRIT_REFUEL,
JSON_VALUE(DATA_VALUE.value, '$.JOBCODE_OID') AS JOBCODE_OID,
JSON_VALUE(DATA_VALUE.value, '$.JOB_CODE_LAST_UPDATED_UTC') AS JOB_CODE_LAST_UPDATED_UTC,
JSON_VALUE(DATA_VALUE.value, '$.MATERIAL_OID') AS MATERIAL_OID,
JSON_VALUE(DATA_VALUE.value, '$.MATERIAL_LAST_UPDATED_UTC') AS MATERIAL_LAST_UPDATED_UTC,
JSON_VALUE(DATA_VALUE.value, '$.MATERIAL_DETERMINATION') AS MATERIAL_DETERMINATION,
JSON_VALUE(DATA_VALUE.value, '$.LAST_POSITION_REPORT_DATE_UTC') AS LAST_POSITION_REPORT_DATE_UTC,
JSON_VALUE(DATA_VALUE.value, '$.X') AS X,
JSON_VALUE(DATA_VALUE.value, '$.Y') AS Y,
JSON_VALUE(DATA_VALUE.value, '$.Z') AS Z,
JSON_VALUE(DATA_VALUE.value, '$.POSITION_ACCURACY') AS POSITION_ACCURACY,
JSON_VALUE(DATA_VALUE.value, '$.MACHINE_SHUTDOWN') AS MACHINE_SHUTDOWN,
JSON_VALUE(DATA_VALUE.value, '$.NOT_IN_USE') AS NOT_IN_USE,
JSON_VALUE(DATA_VALUE.value, '$.MSTATE_LOADSTATUS') AS MSTATE_LOADSTATUS,
JSON_VALUE(DATA_VALUE.value, '$.MSTATE_MANUALOVERRIDE') AS MSTATE_MANUALOVERRIDE,
JSON_VALUE(DATA_VALUE.value, '$.MSTATE_OLDLOADSTATUS') AS MSTATE_OLDLOADSTATUS,
JSON_VALUE(DATA_VALUE.value, '$.MSTATE_OLDSTATE') AS MSTATE_OLDSTATE,
JSON_VALUE(DATA_VALUE.value, '$.FIELD_BAD_GPS') AS FIELD_BAD_GPS,
JSON_VALUE(DATA_VALUE.value, '$.SERVICE_MACHINE_OID') AS SERVICE_MACHINE_OID,
JSON_VALUE(DATA_VALUE.value, '$.LAST_LOADER_OID') AS LAST_LOADER_OID,
JSON_VALUE(DATA_VALUE.value, '$.LAST_PROCESSOR_OID') AS LAST_PROCESSOR_OID,
JSON_VALUE(DATA_VALUE.value, '$.TIME_COMMENCED_SERVICE_UTC') AS TIME_COMMENCED_SERVICE_UTC,
JSON_VALUE(DATA_VALUE.value, '$.TIME_COMPLETED_SERVICE_UTC') AS TIME_COMPLETED_SERVICE_UTC,
JSON_VALUE(DATA_VALUE.value, '$.SERVICE_INFO_LAST_UPDATED_UTC') AS SERVICE_INFO_LAST_UPDATED_UTC,
JSON_VALUE(DATA_VALUE.value, '$.SPEED') AS SPEED,
JSON_VALUE(DATA_VALUE.value, '$.HEADING') AS HEADING,
JSON_VALUE(DATA_VALUE.value, '$.FREEDESTPERCENT') AS FREEDESTPERCENT,
JSON_VALUE(DATA_VALUE.value, '$.FREEGRPDESTPERCENT') AS FREEGRPDESTPERCENT,
JSON_VALUE(DATA_VALUE.value, '$.LOADED') AS LOADED,
JSON_VALUE(DATA_VALUE.value, '$.CURRENT_PAYLOAD') AS CURRENT_PAYLOAD,
JSON_VALUE(DATA_VALUE.value, '$.CURR_PAYLOAD_LAST_UPDATED_UTC') AS CURR_PAYLOAD_LAST_UPDATED_UTC,
JSON_VALUE(DATA_VALUE.value, '$.LAST_PAYLOAD') AS LAST_PAYLOAD,
JSON_VALUE(DATA_VALUE.value, '$.LAST_MATERIAL_OID') AS LAST_MATERIAL_OID,
JSON_VALUE(DATA_VALUE.value, '$.LAST_GRADE_BLOCK_OID') AS LAST_GRADE_BLOCK_OID,
JSON_VALUE(DATA_VALUE.value, '$.CURRENT_GRADE_BLOCK_OID') AS CURRENT_GRADE_BLOCK_OID,
JSON_VALUE(DATA_VALUE.value, '$.CUR_GRADE_BLK_LAST_UPDATED_UTC') AS CUR_GRADE_BLK_LAST_UPDATED_UTC,
JSON_VALUE(DATA_VALUE.value, '$.GRADE_BLOCK_DETERMINATION') AS GRADE_BLOCK_DETERMINATION,
JSON_VALUE(DATA_VALUE.value, '$.GRADE_BLOCK_OID') AS GRADE_BLOCK_OID,
JSON_VALUE(DATA_VALUE.value, '$.GRADE_BLOCK_GROUP_OID') AS GRADE_BLOCK_GROUP_OID,
JSON_VALUE(DATA_VALUE.