CREATE VIEW [bag2].[VIEW_SHIFT_ETL] AS

CREATE VIEW [bag2].[VIEW_SHIFT_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.OID') AS OID,
JSON_VALUE(DATA_VALUE.value, '$.VERSION') AS VERSION,
JSON_VALUE(DATA_VALUE.value, '$.STARTTIME_UTC') AS STARTTIME_UTC,
JSON_VALUE(DATA_VALUE.value, '$.ENDTIME_UTC') AS ENDTIME_UTC,
JSON_VALUE(DATA_VALUE.value, '$.SHIFTTYPE') AS SHIFTTYPE,
JSON_VALUE(DATA_VALUE.value, '$.CREW') AS CREW,
JSON_VALUE(DATA_VALUE.value, '$.NAME') AS NAME,
JSON_VALUE(DATA_VALUE.value, '$.DAY') AS DAY,
JSON_VALUE(DATA_VALUE.value, '$.WEEK') AS WEEK,
JSON_VALUE(DATA_VALUE.value, '$.MONTH') AS MONTH,
JSON_VALUE(DATA_VALUE.value, '$.QUARTER') AS QUARTER,
JSON_VALUE(DATA_VALUE.value, '$.HALF') AS HALF,
JSON_VALUE(DATA_VALUE.value, '$.YEAR') AS YEAR,
JSON_VALUE(DATA_VALUE.value, '$.REPORTING_DATE') AS REPORTING_DATE,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_TYPE') AS CHANGE_TYPE,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_ID') AS CHANGE_ID,
Getutcdate() AS UTC_CREATED_DATE
--NULL AS UTC_LOGICAL_DELETED_DATE
FROM [bag2].[SHIFT_STAGE] LS
CROSS APPLY OPENJSON (LS.SRC_JSON) AS DATA_VALUE
