CREATE OR REPLACE FUNCTION "SENSOR_SNAPSHOT_GET"("PARAM_SITE_CODE" VARCHAR(3), "PARAM_IS_AF_PATH_FLAG" BOOLEAN, "PARAM_ATTRIBUTE_PATH_LIST" ARRAY, "PARAM_PI_POINT_LIST" ARRAY)
RETURNS TABLE ("TAG_NAME" VARCHAR(16777216), "VALUE_UTC_TS" TIMESTAMP_NTZ(9), "SENSOR_VALUE" VARCHAR(16777216), "UOM" VARCHAR(16777216), "QUALITY" VARCHAR(16777216))
LANGUAGE SQL
AS '
WITH TBL_SENSOR_ID AS 
(
SELECT DISTINCT SENSOR_ID 
FROM PROD_DATALAKE.FCTS.PI_AF_ATTRIBUTE
WHERE ATTRIBUTEPATH IN (SELECT ATTRIBUTE_LIST.VALUE::STRING FROM TABLE(FLATTEN(INPUT => PARAM_ATTRIBUTE_PATH_LIST)) ATTRIBUTE_LIST)
AND PARAM_IS_AF_PATH_FLAG = TRUE

UNION 
  
SELECT DISTINCT SENSOR_ID AS SENSOR_ID
FROM PROD_DATALAKE.FCTS.PI_POINT
WHERE PIPOINTNAME IN (SELECT PI_POINT_LIST.VALUE::STRING FROM TABLE(FLATTEN(INPUT => PARAM_PI_POINT_LIST)) PI_POINT_LIST)
AND PARAM_IS_AF_PATH_FLAG = FALSE
)

--1-SAM
SELECT
CASE WHEN PARAM_IS_AF_PATH_FLAG THEN REPLACE(ANNT.ATTRIBUTEPATH,''\\\\DataReference'')::VARCHAR ELSE POINT.PIPOINTNAME END AS TAG_NAME,
RAW.VALUE_UTC_TS, RAW.SENSOR_VALUE::VARCHAR, RAW.UOM::VARCHAR, RAW.QUALITY::VARCHAR

FROM PROD_DATALAKE.FCTS.SENSOR_READING_SAM_B RAW
LEFT JOIN PROD_DATALAKE.FCTS.PI_AF_ATTRIBUTE ANNT ON RAW.SENSOR_ID = ANNT.SENSOR_ID
AND ANNT.ATTRIBUTEPATH IN (SELECT ATTRIBUTE_LIST.VALUE::STRING FROM TABLE(FLATTEN(INPUT => PARAM_ATTRIBUTE_PATH_LIST)) ATTRIBUTE_LIST)
LEFT JOIN PROD_DATALAKE.FCTS.PI_POINT POINT  ON  RAW.SENSOR_ID = POINT.SENSOR_ID

WHERE 
RAW.SITE_CODE = PARAM_SITE_CODE
AND (RAW.SENSOR_ID, RAW.VALUE_UTC_TS) IN (
    SELECT RAW_SUB.SENSOR_ID , MAX(RAW_SUB.VALUE_UTC_TS) AS VALUE_UTC_TS
    FROM PROD_DATALAKE.FCTS.SENSOR_READING_SAM_B RAW_SUB
    WHERE
    RAW_SUB.VALUE_UTC_TS > CAST(CURRENT_TIMESTAMP(0)- INTERVAL ''30 DAY'' AS TIMESTAMP_NTZ) 
    AND RAW_SUB.SENSOR_ID IN (SELECT SENSOR_ID FROM TBL_SENSOR_ID)
    GROUP BY RAW_SUB.SENSOR_ID)

UNION

--2-MOR
SELECT
CASE WHEN PARAM_IS_AF_PATH_FLAG THEN REPLACE(ANNT.ATTRIBUTEPATH,''\\\\DataReference'')::VARCHAR ELSE POINT.PIPOINTNAME END AS TAG_NAME,
RAW.VALUE_UTC_TS, RAW.SENSOR_VALUE::VARCHAR, RAW.UOM::VARCHAR, RAW.QUALITY::VARCHAR

FROM PROD_DATALAKE.FCTS.SENSOR_READING_MOR_B RAW
LEFT JOIN PROD_DATALAKE.FCTS.PI_AF_ATTRIBUTE ANNT ON RAW.SENSOR_ID = ANNT.SENSOR_ID
AND ANNT.ATTRIBUTEPATH IN (SELECT ATTRIBUTE_LIST.VALUE::STRING FROM TABLE(FLATTEN(INPUT => PARAM_ATTRIBUTE_PATH_LIST)) ATTRIBUTE_LIST)
LEFT JOIN PROD_DATALAKE.FCTS.PI_POINT POINT  ON  RAW.SENSOR_ID = POINT.SENSOR_ID

WHERE 
RAW.SITE_CODE = PARAM_SITE_CODE
AND (RAW.SENSOR_ID, RAW.VALUE_UTC_TS) IN (
    SELECT RAW_SUB.SENSOR_ID , MAX(RAW_SUB.VALUE_UTC_TS) AS VALUE_UTC_TS
    FROM PROD_DATALAKE.FCTS.SENSOR_READING_MOR_B RAW_SUB
    WHERE
    RAW_SUB.VALUE_UTC_TS > CAST(CURRENT_TIMESTAMP(0)- INTERVAL ''30 DAY'' AS TIMESTAMP_NTZ) 
    AND RAW_SUB.SENSOR_ID IN (SELECT SENSOR_ID FROM TBL_SENSOR_ID)
    GROUP BY RAW_SUB.SENSOR_ID)

UNION

--3-CMX
SELECT
CASE WHEN PARAM_IS_AF_PATH_FLAG THEN REPLACE(ANNT.ATTRIBUTEPATH,''\\\\DataReference'')::VARCHAR ELSE POINT.PIPOINTNAME END AS TAG_NAME,
RAW.VALUE_UTC_TS, RAW.SENSOR_VALUE::VARCHAR, RAW.UOM::VARCHAR, RAW.QUALITY::VARCHAR
FROM PROD_DATALAKE.FCTS.SENSOR_READING_CMX_B RAW
LEFT JOIN PROD_DATALAKE.FCTS.PI_AF_ATTRIBUTE ANNT ON RAW.SENSOR_ID = ANNT.SENSOR_ID
AND ANNT.ATTRIBUTEPATH IN (SELECT ATTRIBUTE_LIST.VALUE::STRING FROM TABLE(FLATTEN(INPUT => PARAM_ATTRIBUTE_PATH_LIST)) ATTRIBUTE_LIST)
LEFT JOIN PROD_DATALAKE.FCTS.PI_POINT POINT  ON  RAW.SENSOR_ID = POINT.SENSOR_ID

WHERE 
RAW.SITE_CODE = PARAM_SITE_CODE
AND (RAW.SENSOR_ID, RAW.VALUE_UTC_TS) IN (
    SELECT RAW_SUB.SENSOR_ID , MAX(RAW_SUB.VALUE_UTC_TS) AS VALUE_UTC_TS
    FROM PROD_DATALAKE.FCTS.SENSOR_READING_CMX_B RAW_SUB
    WHERE
    RAW_SUB.VALUE_UTC_TS > CAST(CURRENT_TIMESTAMP(0)- INTERVAL ''30 DAY'' AS TIMESTAMP_NTZ) 
    AND RAW_SUB.SENSOR_ID IN (SELECT SENSOR_ID FROM TBL_SENSOR_ID)
    GROUP BY RAW_SUB.SENSOR_ID)

UNION

--4-SIE
SELECT
CASE WHEN PARAM_IS_AF_PATH_FLAG THEN REPLACE(ANNT.ATTRIBUTEPATH,''\\\\DataReference'')::VARCHAR ELSE POINT.PIPOINTNAME END AS TAG_NAME,
RAW.VALUE_UTC_TS, RAW.SENSOR_VALUE::VARCHAR, RAW.UOM::VARCHAR, RAW.QUALITY::VARCHAR
FROM PROD_DATALAKE.FCTS.SENSOR_READING_SIE_B RAW
LEFT JOIN PROD_DATALAKE.FCTS.PI_AF_ATTRIBUTE ANNT ON RAW.SENSOR_ID = ANNT.SENSOR_ID
AND ANNT.ATTRIBUTEPATH IN (SELECT ATTRIBUTE_LIST.VALUE::STRING FROM TABLE(FLATTEN(INPUT => PARAM_ATTRIBUTE_PATH_LIST)) ATTRIBUTE_LIST)
LEFT JOIN PROD_DATALAKE.FCTS.PI_POINT POINT  ON  RAW.SENSOR_ID = POINT.SENSOR_ID

WHERE 
RAW.SITE_CODE = PARAM_SITE_CODE
AND (RAW.SENSOR_ID, RAW.VALUE_UTC_TS) IN (
    SELECT RAW_SUB.SENSOR_ID , MAX(RAW_SUB.VALUE_UTC_TS) AS VALUE_UTC_TS
    FROM PROD_DATALAKE.FCTS.SENSOR_READING_SIE_B RAW_SUB
    WHERE
    RAW_SUB.VALUE_UTC_TS > CAST(CURRENT_TIMESTAMP(0)- INTERVAL ''30 DAY'' AS TIMESTAMP_NTZ) 
    AND RAW_SUB.SENSOR_ID IN (SELECT SENSOR_ID FROM TBL_SENSOR_ID)
    GROUP BY RAW_SUB.SENSOR_ID)

UNION

--5-NMO
SELECT
CASE WHEN PARAM_IS_AF_PATH_FLAG THEN REPLACE(ANNT.ATTRIBUTEPATH,''\\\\DataReference'')::VARCHAR ELSE POINT.PIPOINTNAME END AS TAG_NAME,
RAW.VALUE_UTC_TS, RAW.SENSOR_VALUE::VARCHAR, RAW.UOM::VARCHAR, RAW.QUALITY::VARCHAR
FROM PROD_DATALAKE.FCTS.SENSOR_READING_NMO_B RAW
LEFT JOIN PROD_DATALAKE.FCTS.PI_AF_ATTRIBUTE ANNT ON RAW.SENSOR_ID = ANNT.SENSOR_ID
AND ANNT.ATTRIBUTEPATH IN (SELECT ATTRIBUTE_LIST.VALUE::STRING FROM TABLE(FLATTEN(INPUT => PARAM_ATTRIBUTE_PATH_LIST)) ATTRIBUTE_LIST)
LEFT JOIN PROD_DATALAKE.FCTS.PI_POINT POINT  ON  RAW.SENSOR_ID = POINT.SENSOR_ID

WHERE 
RAW.SITE_CODE = PARAM_SITE_CODE
AND (RAW.SENSOR_ID, RAW.VALUE_UTC_TS) IN (
    SELECT RAW_SUB.SENSOR_ID , MAX(RAW_SUB.VALUE_UTC_TS) AS VALUE_UTC_TS
    FROM PROD_DATALAKE.FCTS.SENSOR_READING_NMO_B RAW_SUB
    WHERE
    RAW_SUB.VALUE_UTC_TS > CAST(CURRENT_TIMESTAMP(0)- INTERVAL ''30 DAY'' AS TIMESTAMP_NTZ) 
    AND RAW_SUB.SENSOR_ID IN (SELECT SENSOR_ID FROM TBL_SENSOR_ID)
    GROUP BY RAW_SUB.SENSOR_ID)

UNION

--6-BAG
SELECT
CASE WHEN PARAM_IS_AF_PATH_FLAG THEN REPLACE(ANNT.ATTRIBUTEPATH,''\\\\DataReference'')::VARCHAR ELSE POINT.PIPOINTNAME END AS TAG_NAME,
RAW.VALUE_UTC_TS, RAW.SENSOR_VALUE::VARCHAR, RAW.UOM::VARCHAR, RAW.QUALITY::VARCHAR
FROM PROD_DATALAKE.FCTS.SENSOR_READING_BAG_B RAW
LEFT JOIN PROD_DATALAKE.FCTS.PI_AF_ATTRIBUTE ANNT ON RAW.SENSOR_ID = ANNT.SENSOR_ID
AND ANNT.ATTRIBUTEPATH IN (SELECT ATTRIBUTE_LIST.VALUE::STRING FROM TABLE(FLATTEN(INPUT => PARAM_ATTRIBUTE_PATH_LIST)) ATTRIBUTE_LIST)
LEFT JOIN PROD_DATALAKE.FCTS.PI_POINT POINT  ON  RAW.SENSOR_ID = POINT.SENSOR_ID

WHERE 
RAW.SITE_CODE = PARAM_SITE_CODE
AND (RAW.SENSOR_ID, RAW.VALUE_UTC_TS) IN (
    SELECT RAW_SUB.SENSOR_ID , MAX(RAW_SUB.VALUE_UTC_TS) AS VALUE_UTC_TS
    FROM PROD_DATALAKE.FCTS.SENSOR_READING_BAG_B RAW_SUB
    WHERE
    RAW_SUB.VALUE_UTC_TS > CAST(CURRENT_TIMESTAMP(0)- INTERVAL ''30 DAY'' AS TIMESTAMP_NTZ) 
    AND RAW_SUB.SENSOR_ID IN (SELECT SENSOR_ID FROM TBL_SENSOR_ID)
    GROUP BY RAW_SUB.SENSOR_ID)

UNION

--7-CVE
SELECT
CASE WHEN PARAM_IS_AF_PATH_FLAG THEN REPLACE(ANNT.ATTRIBUTEPATH,''\\\\DataReference'')::VARCHAR ELSE POINT.PIPOINTNAME END AS TAG_NAME,
RAW.VALUE_UTC_TS, RAW.SENSOR_VALUE::VARCHAR, RAW.UOM::VARCHAR, RAW.QUALITY::VARCHAR
FROM PROD_DATALAKE.FCTS.SENSOR_READING_CVE_B RAW
LEFT JOIN PROD_DATALAKE.FCTS.PI_AF_ATTRIBUTE ANNT ON RAW.SENSOR_ID = ANNT.SENSOR_ID
AND ANNT.ATTRIBUTEPATH IN (SELECT ATTRIBUTE_LIST.VALUE::STRING FROM TABLE(FLATTEN(INPUT => PARAM_ATTRIBUTE_PATH_LIST)) ATTRIBUTE_LIST)
LEFT JOIN PROD_DATALAKE.FCTS.PI_POINT POINT  ON  RAW.SENSOR_ID = POINT.SENSOR_ID

WHERE 
RAW.SITE_CODE = PARAM_SITE_CODE
AND (RAW.SENSOR_ID, RAW.VALUE_UTC_TS) IN (
    SELECT RAW_SUB.SENSOR_ID , MAX(RAW_SUB.VALUE_UTC_TS) AS VALUE_UTC_TS
    FROM PROD_DATALAKE.FCTS.SENSOR_READING_CVE_B RAW_SUB
    WHERE
    RAW_SUB.VALUE_UTC_TS > CAST(CURRENT_TIMESTAMP(0)- INTERVAL ''30 DAY'' AS TIMESTAMP_NTZ) 
    AND RAW_SUB.SENSOR_ID IN (SELECT SENSOR_ID FROM TBL_SENSOR_ID)
    GROUP BY RAW_SUB.SENSOR_ID)
'
