CREATE VIEW [bag].[asset_efficiency_v] AS





--SELECT * FROM [bag].[asset_efficiency_v] WITH (NOLOCK)
CREATE VIEW [BAG].[asset_efficiency_v]   
AS      

WITH Last3Shift AS(
SELECT TOP 3 
	SHIFT_ID,
	ROW_NUMBER() OVER(ORDER BY SHIFT_ID DESC) AS ROW_NO
FROM [ConnectedOperations].[bag2].MSMODEL_SHIFT
ORDER BY SHIFT_ID DESC
),

Base AS(
SELECT
	SITE_CODE,
	SHIFT_ID,
	EQUIP_NAME AS EQMT,
	FIELDUNIT,
	MACHINE_CATEGORY,
	REASON_CODE,
	REASON_NAME AS REASON,
	CATEGORY_CODE,
	CATEGORY,
	STATUS_CODE,
	STATUS_NAME AS STATUS,
	DATEADD(HOUR, -7, START_TIME_UTC) AS START_TIME_TS,
	DATEADD(HOUR, -7, END_TIME_UTC) AS END_TIME_TS,
	DURATION
FROM [ConnectedOperations].[bag2].[MSMODEL_EQUIPMENT_CURRENT_STATUS]
WHERE SHIFT_ID >= (SELECT SHIFT_ID FROM Last3Shift WHERE ROW_NO = 3)
AND EQUIP_NAME IS NOT NULL
),

EqmtHist AS(
SELECT
	SITE_CODE,
	SHIFT_ID,
	EQMT,
	FIELDUNIT,
	MACHINE_CATEGORY,
	REASON_CODE,
	REASON,
	CATEGORY_CODE,
	CATEGORY,
	STATUS_CODE,
	STATUS,
	CAST(START_TIME_TS AS DATETIME) AS START_TIME_TS,
	CAST(END_TIME_TS AS DATETIME) AS END_TIME_TS,
	DURATION,
	CASE WHEN LAG(EQMT, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS ) IS NULL
		THEN 1
		ELSE 
			CASE WHEN EQMT <> LAG(EQMT, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
				OR REASON_CODE <> LAG(REASON_CODE, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
				OR [STATUS_CODE] <> LAG([STATUS_CODE], 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
			THEN 1
			ELSE 
				CASE WHEN EQMT <> LEAD(EQMT, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
					OR REASON_CODE <> LEAD(REASON_CODE, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
					OR [STATUS_CODE] <> LEAD([STATUS_CODE], 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
				THEN 2
				ELSE 0
				END
			END
	END AS [StatusIndex]
FROM Base

),

HOS AS(
SELECT
	SITE_CODE,
	SHIFT_ID,
	EQMT,
	FIELDUNIT,
	MACHINE_CATEGORY,
	START_TIME_TS,
	CASE WHEN EQMT = LEAD(EQMT, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
		AND REASON_CODE = LEAD(REASON_CODE, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
		AND STATUS_CODE = LEAD(STATUS_CODE, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
		AND 2 = LEAD(StatusIndex, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
	THEN LEAD(END_TIME_TS, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
	ELSE 
		CASE WHEN 1 = LEAD(StatusIndex, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
			AND StatusIndex = 1
		THEN END_TIME_TS
		ELSE NULL
		END
	END AS END_TIME_TS,
	REASON_CODE,
	REASON,
	CATEGORY_CODE,
	CATEGORY,
	STATUS_CODE,
	STATUS
FROM EqmtHist eh
WHERE StatusIndex != 0
)

SELECT
	SHIFT_ID COLLATE SQL_Latin1_General_CP1_CI_AS AS SHIFTID,
	EQMT COLLATE SQL_Latin1_General_CP1_CI_AS AS EQMT,
	NULL AS FIELDEQMTTYPE,
	FIELDUNIT COLLATE SQL_Latin1_General_CP1_CI_AS AS EQMTTYPE,
	MACHINE_CATEGORY,
	CASE MACHINE_CATEGORY
		WHEN 'Truck Classes' THEN 'Truck'
		WHEN 'Shovel Classes' THEN 'Shovel'
		WHEN 'Loader Classes' THEN 'Loader'
		WHEN 'Track Drill' THEN 'Drill'
	ELSE REPLACE(REPLACE(MACHINE_CATEGORY, ' Classes', ''),' Unit', '') END COLLATE SQL_Latin1_General_CP1_CI_AS AS UNITTYPE,
	START_TIME_TS AS STARTDATETIME,
	END_TIME_TS AS ENDDATETIME,
	DATEDIFF(SECOND, START_TIME_TS, END_TIME_TS) AS DURATION,
	STATUS_CODE AS STATUSIDX,
	STATUS COLLATE SQL_Latin1_General_CP1_CI_AS AS STATUS,
	CATEGORY_CODE AS CATEGORYIDX,
	CATEGORY COLLATE SQL_Latin1_General_CP1_CI_AS AS CATEGORY,
	REASON_CODE AS REASONIDX,
	REASON COLLATE SQL_Latin1_General_CP1_CI_AS AS REASONS,
	NULL AS COMMENTS
FROM HOS
WHERE END_TIME_TS IS NOT NULL
AND START_TIME_TS <> END_TIME_TS






