CREATE VIEW [bag].[CONOPS_BAG_CM_DISPATCH_SUMMARY_V] AS




-- SELECT * FROM [bag].[CONOPS_BAG_CM_DISPATCH_SUMMARY_V] WITH (NOLOCK) WHERE SHIFTFLAG = 'CURR'  
CREATE VIEW [bag].[CONOPS_BAG_CM_DISPATCH_SUMMARY_V]  
AS  

WITH CrLocShift AS (
SELECT
	a.SHIFTINDEX,
	a.SHIFTFLAG,
	a.SITEFLAG,
	'CRUSHER 2' AS CrusherLoc,
	a.SHIFTSTARTDATETIME
FROM [bag].[CONOPS_BAG_SHIFT_INFO_V] a WITH (NOLOCK)
),

MaxArrive AS (
SELECT
	b.SITEFLAG AS SITE_CODE,
	b.SHIFTINDEX,
	MAX(QUEUINGATSOURCESTARTTIME_LOCAL_TS) AS MaxTimeArrive
FROM BAG.FLEET_TRUCK_CYCLE_V a
RIGHT JOIN BAG.CONOPS_BAG_SHIFT_INFO_V b
	ON a.SHIFT_ID = b.SHIFTID
WHERE DUMP_LOC_NAME = 'Crusher 2'
GROUP BY b.SITEFLAG, b.SHIFTINDEX, b.SHIFTSTARTDATETIME
),

RawDump AS (
SELECT
	b.SITEFLAG AS SITE_CODE,
	b.SHIFTINDEX,
	DUMP_HOS -1 AS HOS,
	DUMP_LOC_NAME AS LOC,
	TRUCK_NAME AS TRUCK,
	REPORT_PAYLOAD_SHORT_TONS AS TONS,
	DATEDIFF(SECOND, QUEUINGATSOURCESTARTTIME_LOCAL_TS, DUMPINGSTARTTIME_LOCAL_TS) / 60.0 AS IdleTime,
	DATEDIFF(SECOND, DUMPINGSTARTTIME_LOCAL_TS, DUMPINGENDTIME_LOCAL_TS) / 60.0 AS DumpTime,
	DATEDIFF(SECOND, QUEUINGATSOURCESTARTTIME_LOCAL_TS, DUMPINGENDTIME_LOCAL_TS) / 60.0 AS ServiceTime,
	IIF(ma.MaxTimeArrive > QUEUINGATSOURCESTARTTIME_LOCAL_TS, (DATEDIFF(SECOND, QUEUINGATSOURCESTARTTIME_LOCAL_TS, ma.MaxTimeArrive ) / 60.0), 0) AS IntraArrivalTime
FROM BAG.FLEET_TRUCK_CYCLE_V a
LEFT JOIN BAG.CONOPS_BAG_SHIFT_INFO_V b
	ON a.SHIFT_ID = b.SHIFTID
LEFT JOIN MaxArrive ma
	ON b.SHIFTINDEX = ma.SHIFTINDEX
WHERE DUMP_LOC_NAME = 'Crusher 2'
),

NrOfLoad AS (
SELECT
	b.SITEFLAG,
	b.SHIFTINDEX,
	LOAD_HOS - 1 AS HOS,
	'CRUSHER 2' AS CrusherLoc,
	COUNT(*) AS NrOfLoad
FROM BAG.FLEET_TRUCK_CYCLE_V a
LEFT JOIN BAG.CONOPS_BAG_SHIFT_INFO_V b
	ON a.SHIFT_ID = b.SHIFTID
WHERE DUMP_LOC_NAME = 'Crusher 2'
GROUP BY b.SITEFLAG, b.SHIFTINDEX, LOAD_HOS
),

DumpData AS (
SELECT [SHIFTINDEX]
	  ,[SITE_CODE]
	  ,[HOS]
	  ,[LOC]
	  ,COUNT(TRUCK) NrofDump
	  ,SUM([Tons]) [Tons]
	  ,AVG(ServiceTime) ServiceTime
	  ,AVG(IntraArrivalTime) IntraArrivalTime
	  ,IIF(
		AVG(ServiceTime) >= 0 AND AVG(IntraArrivalTime) >= 0, 
		(1 / AVG(IntraArrivalTime)) / ((1 / AVG(ServiceTime)) * 2) * 100, 
		0
		) TrafficIntensity
	  ,AVG(IdleTIme) IdleTIme
	  ,AVG(DumpTime) DumpTime
FROM RawDump
GROUP BY [SHIFTINDEX], [SITE_CODE], [HOS], [LOC]
)

SELECT cl.SHIFTFLAG
	  ,d.[SHIFTINDEX]
	  ,cl.SITEFLAG
	  ,d.[HOS] + 1 [HOS]
	  ,DATEADD(HOUR, d.[HOS], cl.SHIFTSTARTDATETIME) [Hr]
	  ,d.[LOC] [CrusherLoc]
	  ,ServiceTime [AvgTimeAtCrusher]
	  ,IntraArrivalTime [AvgIntraArrivalTime]
	  ,TrafficIntensity [AvgTrafficIntensity]
	  ,nl.NrofLoad
	  ,IdleTIme [AvgMinIdle]
	  ,DumpTime [AvgDumpTime]
	  ,[Tons]
	  ,NrofDump
FROM CrLocShift cl
LEFT JOIN DumpData d
	ON cl.SHIFTINDEX = d.SHIFTINDEX
	AND cl.CrusherLoc= d.[LOC]
LEFT JOIN NrOfLoad nl
	ON d.SHIFTINDEX = nl.SHIFTINDEX 
	AND d.HOS = nl.HOS 
	AND d.LOC = nl.CrusherLoc
WHERE d.SHIFTINDEX IS NOT NULL





