CREATE VIEW [bag].[FLEET_ASSET_EFFICIENCY_V] AS







CREATE VIEW [bag].[FLEET_ASSET_EFFICIENCY_V]
AS

WITH Last3Shift AS(
SELECT TOP 3 
	SHIFT_ID COLLATE SQL_Latin1_General_CP1_CI_AS AS SHIFT_ID,
	ROW_NUMBER() OVER(ORDER BY SHIFT_ID DESC) AS ROW_NO
FROM [ConnectedOperations].[bag2].MSMODEL_SHIFT
ORDER BY SHIFT_ID DESC
),

Base AS(
SELECT
	SITE_CODE COLLATE SQL_Latin1_General_CP1_CI_AS AS SITE_CODE,
	SHIFT_ID,
	EQUIP_NAME COLLATE SQL_Latin1_General_CP1_CI_AS AS EQMT,
	FIELDUNIT COLLATE SQL_Latin1_General_CP1_CI_AS AS FIELDUNIT,
	MACHINE_CATEGORY COLLATE SQL_Latin1_General_CP1_CI_AS AS MACHINE_CATEGORY,
	REASON_CODE,
	REASON_NAME COLLATE SQL_Latin1_General_CP1_CI_AS AS REASON_NAME,
	CATEGORY_CODE,
	CATEGORY COLLATE SQL_Latin1_General_CP1_CI_AS AS CATEGORY,
	STATUS_CODE,
	STATUS_NAME COLLATE SQL_Latin1_General_CP1_CI_AS AS STATUS_NAME,
	DATEADD(HOUR, -7, START_TIME_UTC) AS START_TIME_TS,
	DATEADD(HOUR, -7, END_TIME_UTC) AS END_TIME_TS,
	DURATION
FROM [ConnectedOperations].[bag2].[MSMODEL_EQUIPMENT_CURRENT_STATUS]
WHERE SHIFT_ID >= (SELECT SHIFT_ID FROM Last3Shift WHERE ROW_NO = 3)
AND EQUIP_NAME IS NOT NULL
),

EqmtHist AS(
SELECT
	SITE_CODE,
	SHIFT_ID,
	EQMT,
	FIELDUNIT,
	MACHINE_CATEGORY,
	REASON_CODE,
	REASON_NAME,
	CATEGORY_CODE,
	CATEGORY,
	STATUS_CODE,
	STATUS_NAME,
	CAST(START_TIME_TS AS DATETIME) AS START_TIME_TS,
	CAST(END_TIME_TS AS DATETIME) AS END_TIME_TS,
	DURATION,
	CASE WHEN LAG(EQMT, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS ) IS NULL
		THEN 1
		ELSE 
			CASE WHEN EQMT <> LAG(EQMT, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
				OR REASON_CODE <> LAG(REASON_CODE, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
				OR [STATUS_CODE] <> LAG([STATUS_CODE], 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
			THEN 1
			ELSE 
				CASE WHEN EQMT <> LEAD(EQMT, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
					OR REASON_CODE <> LEAD(REASON_CODE, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
					OR [STATUS_CODE] <> LEAD([STATUS_CODE], 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
				THEN 2
				ELSE 0
				END
			END
	END AS [StatusIndex]
FROM Base

),

HOS AS(
SELECT
	SITE_CODE,
	SHIFT_ID,
	EQMT,
	FIELDUNIT,
	MACHINE_CATEGORY,
	START_TIME_TS,
	CASE WHEN EQMT = LEAD(EQMT, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
		AND REASON_CODE = LEAD(REASON_CODE, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
		AND STATUS_CODE = LEAD(STATUS_CODE, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
		AND 2 = LEAD(StatusIndex, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
	THEN LEAD(END_TIME_TS, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
	ELSE 
		CASE WHEN 1 = LEAD(StatusIndex, 1, 0) OVER ( ORDER BY SHIFT_ID, EQMT, START_TIME_TS )
			AND StatusIndex = 1
		THEN END_TIME_TS
		ELSE NULL
		END
	END AS END_TIME_TS,
	REASON_CODE,
	REASON_NAME,
	CATEGORY_CODE,
	CATEGORY,
	STATUS_CODE,
	STATUS_NAME
FROM EqmtHist eh
WHERE StatusIndex != 0
)

SELECT
	SITE_CODE AS SITEFLAG,
	SHIFT_ID AS SHIFTID,
	EQMT,
	NULL AS FIELDEQMTTYPE,
	FIELDUNIT AS EQMTTYPE,
	SUBSTRING(MACHINE_CATEGORY, 1, CHARINDEX(' ', MACHINE_CATEGORY, 1) - 1) AS UNITTYPE,
	START_TIME_TS AS STARTDATETIME,
	END_TIME_TS AS ENDDATETIME,
	DATEDIFF(SECOND, START_TIME_TS, END_TIME_TS) AS DURATION,
	STATUS_CODE AS STATUSIDX,
	STATUS_NAME,
	CATEGORY_CODE AS CATEGORYIDX,
	CATEGORY,
	REASON_CODE AS REASONIDX,
	REASON_NAME AS REASONS,
	NULL AS COMMENTS
FROM HOS
WHERE END_TIME_TS IS NOT NULL
AND EQMT IS NOT NULL






