CREATE VIEW [bag].[FLEET_EQ_STATUS_V] AS

CREATE VIEW [bag].[FLEET_EQ_STATUS_V]
AS

SELECT
[SITE_CODE]
,[ECF_CLASS_ID]
,(SELECT SHIFTID FROM BAG.CONOPS_BAG_SHIFT_INFO_V WHERE SHIFTFLAG = 'PREV') AS SHIFT_ID
,(SELECT SHIFTSTARTDATE FROM BAG.CONOPS_BAG_SHIFT_INFO_V WHERE SHIFTFLAG = 'PREV') AS SHIFT_DATE
,(SELECT DATEADD(HH, 7, SHIFTSTARTDATETIME) FROM BAG.CONOPS_BAG_SHIFT_INFO_V WHERE SHIFTFLAG = 'PREV') AS SHIFT_START_TIME_UTC
,[FIELDUNIT]
,[MACHINE_CATEGORY]
,[EQUIP_NAME]
,[REASON_CODE]
,[REASON]
,[CATEGORY_CODE]
,[CATEGORY]
,[STATUS_CODE]
,[STATUS]
,[LOCATION_NAME]
,[FieldExcav]
,[FieldXloc]
,[FieldYloc]
,[FieldVelocity]
,[Fieldlaststatus]
,[FieldCurOper]
,DATEADD(DD, (SELECT DATEDIFF(DD, '2024-02-01', ShiftStartDate) FROM BAG.CONOPS_BAG_SHIFT_INFO_V WHERE SHIFTFLAG = 'PREV'), [START_TIME_UTC]) AS [START_TIME_UTC]
,DATEADD(DD, (SELECT DATEDIFF(DD, '2024-02-01', ShiftStartDate) FROM BAG.CONOPS_BAG_SHIFT_INFO_V WHERE SHIFTFLAG = 'PREV'), [END_TIME_UTC]) AS [END_TIME_UTC]
,[DURATION]
,[MACHINE_OID]
FROM [bag].[FLEET_EQ_STATUS]
WHERE SHIFT_ID = '240201001'

UNION ALL

SELECT
[SITE_CODE]
,[ECF_CLASS_ID]
,(SELECT SHIFTID FROM BAG.CONOPS_BAG_SHIFT_INFO_V WHERE SHIFTFLAG = 'CURR') AS SHIFT_ID
,(SELECT SHIFTSTARTDATE FROM BAG.CONOPS_BAG_SHIFT_INFO_V WHERE SHIFTFLAG = 'CURR') AS SHIFT_DATE
,(SELECT DATEADD(HH, 7, SHIFTSTARTDATETIME) FROM BAG.CONOPS_BAG_SHIFT_INFO_V WHERE SHIFTFLAG = 'CURR') AS SHIFT_START_TIME_UTC
,[FIELDUNIT]
,[MACHINE_CATEGORY]
,[EQUIP_NAME]
,[REASON_CODE]
,[REASON]
,[CATEGORY_CODE]
,[CATEGORY]
,[STATUS_CODE]
,[STATUS]
,[LOCATION_NAME]
,[FieldExcav]
,[FieldXloc]
,[FieldYloc]
,[FieldVelocity]
,[Fieldlaststatus]
,[FieldCurOper]
,DATEADD(DD, (SELECT DATEDIFF(DD, '2024-02-01', ShiftStartDate) FROM BAG.CONOPS_BAG_SHIFT_INFO_V WHERE SHIFTFLAG = 'CURR'), [START_TIME_UTC]) AS [START_TIME_UTC]
,DATEADD(DD, (SELECT DATEDIFF(DD, '2024-02-01', ShiftStartDate) FROM BAG.CONOPS_BAG_SHIFT_INFO_V WHERE SHIFTFLAG = 'CURR'), [END_TIME_UTC]) AS [END_TIME_UTC]
,[DURATION]
,[MACHINE_OID]
FROM [bag].[FLEET_EQ_STATUS]
WHERE SHIFT_ID = '240201002'

