CREATE TABLE [Arch].[PLAN_VALUES_PROD_SUM] (
    [CONTENTTYPEID] varchar(100) NOT NULL,
    [PLAN] varchar(50) NULL,
    [COMPLIANCEASSETID] varchar(100) NULL,
    [EFFECTIVEDATE] date NULL,
    [ORETPD] decimal(18,5) NULL,
    [ORETCU] decimal(18,5) NULL,
    [OREMO] decimal(18,5) NULL,
    [ROMTPD] decimal(18,5) NULL,
    [ROMTCU] decimal(18,5) NULL,
    [WASTETPD] decimal(18,5) NULL,
    [EXPITTPD] decimal(18,5) NULL,
    [INPITTPD] decimal(18,5) NULL,
    [TOTALTPD] decimal(18,5) NULL,
    [S08TPD] decimal(18,5) NULL,
    [S10TPD] decimal(18,5) NULL,
    [S11TPD] decimal(18,5) NULL,
    [S12TPD] decimal(18,5) NULL,
    [S22TPD] decimal(18,5) NULL,
    [S23TPD] decimal(18,5) NULL,
    [TRUCKAVAILABILITY] decimal(18,5) NULL,
    [TRUCKUSEOFAVAILABILITY] decimal(18,5) NULL,
    [TRUCKASSETEFFICIENCY] decimal(18,5) NULL,
    [SHOVELAVAILABILITY] decimal(18,5) NULL,
    [SHOVELUSEOFAVAILABILITY] decimal(18,5) NULL,
    [SHOVELASSETEFFICIENCY] decimal(18,5) NULL,
    [DRILLAVAILABILITY] decimal(18,5) NULL,
    [DRILLASSETEFFICIENCY] decimal(18,5) NULL,
    [ONEWAYHAUL] decimal(18,5) NULL,
    [EFH] decimal(18,5) NULL,
    [TOTALDELTAC] decimal(18,5) NULL,
    [STRIPPINGRATIO] decimal(18,5) NULL,
    [E1TONS] decimal(18,5) NULL,
    [S4TONS] decimal(18,5) NULL,
    [PLANNEDDRIVERS] decimal(18,5) NULL,
    [PLANNEDSUPPORT] decimal(18,5) NULL,
    [PLANNEDSHOVELS] decimal(18,5) NULL,
    [PLANNEDDRILLS] decimal(18,5) NULL,
    [SHIFTCHANGEEFFICIENCY] decimal(18,5) NULL,
    [S08EFH] decimal(18,5) NULL,
    [S10EFH] decimal(18,5) NULL,
    [S11EFH] decimal(18,5) NULL,
    [S12EFH] decimal(18,5) NULL,
    [S22EFH] decimal(18,5) NULL,
    [S23EFH] decimal(18,5) NULL,
    [CRUSHERTARGETTPD] decimal(18,5) NULL,
    [TRUCKLOADEDTRAVEL] decimal(18,5) NULL,
    [TRUCKEMPTYTRAVEL] decimal(18,5) NULL,
    [SHOVELIDLETIME] decimal(18,5) NULL,
    [SHOVELTONSPERHOUR] decimal(18,5) NULL,
    [TARGETFEETDRILLED] decimal(18,5) NULL,
    [TARGETHOLESDRILLED] decimal(18,5) NULL,
    [REHANDLETPD] decimal(18,5) NULL,
    [S08TPRH] decimal(18,5) NULL,
    [S10TPRH] decimal(18,5) NULL,
    [S11TPRH] decimal(18,5) NULL,
    [S12TPRH] decimal(18,5) NULL,
    [S22TPRH] decimal(18,5) NULL,
    [S23TPRH] decimal(18,5) NULL,
    [AVERAGEREADYTRUCKS] decimal(18,5) NULL,
    [AVERAGEREADYSHOVELS] decimal(18,5) NULL,
    [DRILLREADINESS] decimal(18,5) NULL,
    [SMALLCRUSHERTPD] decimal(18,5) NULL,
    [E1TPD] decimal(18,5) NULL,
    [N3TPD] decimal(18,5) NULL,
    [S4TPD] decimal(18,5) NULL,
    [ID] int NOT NULL,
    [CONTENTTYPE] varchar(50) NOT NULL,
    [MODIFIED] datetime NOT NULL,
    [CREATED] datetime NOT NULL,
    [CREATEDBYID] int NOT NULL,
    [MODIFIEDBYID] int NOT NULL,
    [OWSHIDDENVERSION] int NOT NULL,
    [VERSION] decimal(10,5) NOT NULL,
    [PATH] varchar(2000) NOT NULL,
    [UTC_CREATED_DATE] datetime NOT NULL,
    [SITECODE] varchar(4) NOT NULL
);