CREATE TABLE [Arch].[PLAN_VALUES] (
    [FORMATSHIFTID] varchar(50) NULL,
    [CONTENTTYPEID] varchar(100) NOT NULL,
    [SHIFTID] varchar(50) NULL,
    [COMPLIANCEASSETID] varchar(100) NULL,
    [TOTALMINED] decimal(18,5) NULL,
    [L01ORE] decimal(18,5) NULL,
    [L01WASTE_OXIDE] decimal(18,5) NULL,
    [L02ORE] decimal(18,5) NULL,
    [L02WASTE_OXIDE] decimal(18,5) NULL,
    [S08ORE] decimal(18,5) NULL,
    [S08WASTE_OXIDE] decimal(18,5) NULL,
    [S10ORE] decimal(18,5) NULL,
    [S10WASTE_OXIDE] decimal(18,5) NULL,
    [S11ORE] decimal(18,5) NULL,
    [S11WASTE_OXIDE] decimal(18,5) NULL,
    [S12ORE] decimal(18,5) NULL,
    [S12WASTE_OXIDE] decimal(18,5) NULL,
    [S22ORE] decimal(18,5) NULL,
    [S22WASTE_OXIDE] decimal(18,5) NULL,
    [S23ORE] decimal(18,5) NULL,
    [S23WASTE_OXIDE] decimal(18,5) NULL,
    [REHANDLE] decimal(18,5) NULL,
    [E1TONS] decimal(18,5) NULL,
    [E3TONS] decimal(18,5) NULL,
    [N1TONS] decimal(18,5) NULL,
    [N2TONS] decimal(18,5) NULL,
    [N3TONS] decimal(18,5) NULL,
    [S4TONS] decimal(18,5) NULL,
    [TOTALEXPITTONS] decimal(18,5) NULL,
    [EFH] decimal(18,5) NULL,
    [CRUSHER2] decimal(18,5) NULL,
    [DUMPINGATCRUSHER] decimal(18,5) NULL,
    [STOCKPILETARGETS] decimal(18,5) NULL,
    [ID] int NOT NULL,
    [CONTENTTYPE] varchar(50) NOT NULL,
    [MODIFIED] datetime NOT NULL,
    [CREATED] datetime NOT NULL,
    [CREATEDBYID] int NOT NULL,
    [MODIFIEDBYID] int NOT NULL,
    [OWSHIDDENVERSION] int NOT NULL,
    [VERSION] decimal(10,5) NOT NULL,
    [PATH] varchar(2000) NOT NULL,
    [UTC_CREATED_DATE] datetime NULL,
    [SITECODE] varchar(4) NOT NULL
);