CREATE TABLE [Arch].[SHIFT_ROOT_SHIFT_DATE] (
    [ID] decimal(19,0) NOT NULL,
    [FIELDSTART] int NULL,
    [FIELDTIME] int NULL,
    [FIELDYEAR] int NULL,
    [FIELDMONTH] decimal(19,0) NULL,
    [FIELDDAY] int NULL,
    [FIELDSHIFT] decimal(19,0) NULL,
    [FIELDCREW] decimal(19,0) NULL,
    [FIELDHOLIDAY] int NULL,
    [FIELDUTCSTART] int NULL,
    [FIELDUTCEND] int NULL,
    [FIELDDSTSTATE] decimal(19,0) NULL,
    [UTC_CREATED_DATE] datetime NOT NULL,
    [UTC_LOGICAL_DELETED_DATE] datetime NULL,
    [SITECODE] varchar(4) NOT NULL
);