CREATE VIEW [CLI].[CONOPS_CLI_CRUSHER_STATUS_V] AS



--SELECT * FROM [CLI].[CONOPS_CLI_CRUSHER_STATUS_V] WITH (NOLOCK) WHERE SHIFTFLAG = 'CURR'  
CREATE VIEW [CLI].[CONOPS_CLI_CRUSHER_STATUS_V]  
AS  

SELECT
	x.SITE_CODE AS siteflag,
	s.shiftflag,
	x.SHIFTINDEX,
	CASE WHEN x.DUMPNAME IN ('CRUSHER 1') THEN 'CRUSHER 1'
		ELSE x.DUMPNAME END AS Crusher,
	s.StatusName AS Status,
	s.ReasonDesc AS reasons,
	x.ShovelId,
	x.TIMEDUMP_TS AS StartTime
FROM(
	SELECT
		SITE_CODE,
		SHIFTINDEX,
		EXCAV AS ShovelId,
		DUMPNAME,
		TIMEDUMP_TS,
		ROW_NUMBER() OVER (PARTITION BY SITE_CODE, SHIFTINDEX ORDER BY TIMEDUMP_TS DESC) num
	FROM dbo.delta_c WITH (NOLOCK)
	WHERE SITE_CODE = 'CLI'
		AND DUMPNAME = 'CRUSHER 1'
) x
LEFT JOIN CLI.CONOPS_CLI_SHOVEL_INFO_V s
	ON x.shiftindex = s.shiftindex
	AND x.ShovelId = s.ShovelID
WHERE x.num = 1
AND s.shiftflag IS NOT NULL

