CREATE VIEW [CLI].[SHIFT_EQMT] AS




--SELECT * FROM CLI.SHIFT_EQMT
CREATE VIEW CLI.SHIFT_EQMT
AS

SELECT
'CMX' AS SiteFlag,
*
FROM CMXOperational.dbo.SHIFTShifteqmt WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM CLI.SHIFT_INFO)




