CREATE VIEW [CLI].[SHIFT_LOAD] AS



--SELECT * FROM CLI.SHIFT_LOAD
CREATE VIEW CLI.SHIFT_LOAD
AS

SELECT
'CMX' AS SiteFlag,
*
FROM CMXOperational.dbo.SHIFTShiftload WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM CLI.SHIFT_INFO)



