CREATE VIEW [CLI].[SHIFT_LOC] AS



--SELECT * FROM CLI.SHIFT_LOC
CREATE VIEW CLI.SHIFT_LOC
AS

SELECT
'CMX' AS SiteFlag,
*
FROM CMXOperational.dbo.SHIFTShiftloc WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM CLI.SHIFT_INFO)



