CREATE VIEW [MOR].[CONOPS_MOR_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V] AS


  -- SELECT * FROM [MOR].[CONOPS_MOR_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V] WITH (NOLOCK) 
CREATE VIEW [MOR].[CONOPS_MOR_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V]   
AS  
  
SELECT 
LASTSHIFTINDEX AS Shiftindex,  
SITE_CODE,  
OPERID,  
NROFDAYS  
FROM dbo.OPERATOR_CONSECUTIVE_WORKDAYS WITH (NOLOCK)  
WHERE SITE_CODE = 'MOR' AND UNIT_CODE = 2


