CREATE VIEW [MOR].[EQUIPMENT_HOURLY_STATUS] AS

--SELECT * FROM MOR.EQUIPMENT_HOURLY_STATUS
CREATE VIEW MOR.EQUIPMENT_HOURLY_STATUS
AS

SELECT *
FROM MOR.EQUIPMENT_HOURLY_STATUS_2 WITH(NOLOCK)

