CREATE VIEW [MOR].[SHIFT_LOC] AS



--SELECT * FROM MOR.SHIFT_LOC
CREATE VIEW MOR.SHIFT_LOC
AS

SELECT
'MOR' AS SiteFlag,
*
FROM MOROperational.dbo.SHIFTShiftloc WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM mor.SHIFT_INFO)



