CREATE VIEW [MOR].[SHIFT_OPER] AS




--SELECT * FROM MOR.SHIFT_OPER
CREATE VIEW MOR.SHIFT_OPER
AS

SELECT
'MOR' AS SiteFlag,
*
FROM MOROperational.dbo.SHIFTShiftOper WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM mor.SHIFT_INFO)




