CREATE VIEW [MOR].[SHIFT_EQMT] AS




--SELECT * FROM MOR.SHIFT_EQMT
CREATE VIEW MOR.SHIFT_EQMT
AS

SELECT
'MOR' AS SiteFlag,
*
FROM MOROperational.dbo.SHIFTShifteqmt WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM mor.SHIFT_INFO)




