"""
Create DRILL_CYCLE_IMO table type in DEV SQL Azure
Ticket: Requested by Vikas Uttam
"""
from azure.identity import InteractiveBrowserCredential
import pyodbc
import struct

# Get Azure AD token
print("Authenticating with Azure AD...")
credential = InteractiveBrowserCredential()
token = credential.get_token('https://database.windows.net/.default')

# DEV server
server = 'azwd22midbx02.eb8a77f2eea6.database.windows.net'
database = 'ConnectedOperations'

print(f"Connecting to DEV: {server}/{database}")

# Build connection
token_bytes = token.token.encode('utf-16-le')
token_struct = struct.pack(f'<I{len(token_bytes)}s', len(token_bytes), token_bytes)
conn_str = f'DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={server};DATABASE={database}'
conn = pyodbc.connect(conn_str, attrs_before={1256: token_struct})

cursor = conn.cursor()

# First check if type already exists
cursor.execute("""
SELECT name FROM sys.types WHERE name = 'DRILL_CYCLE_IMO' AND is_table_type = 1
""")
existing = cursor.fetchone()

if existing:
    print(f'Type DRILL_CYCLE_IMO already exists!')
else:
    print("Creating [dbo].[DRILL_CYCLE_IMO] table type...")
    
    # Create the table type based on DRILLBLAST_DRILL_CYCLE_V columns
    create_sql = '''
CREATE TYPE [dbo].[DRILL_CYCLE_IMO] AS TABLE (
    [ORIG_SRC_ID] NVARCHAR(100) NULL,
    [SITE_CODE] NVARCHAR(10) NULL,
    [BENCH] NVARCHAR(100) NULL,
    [PUSHBACK] NVARCHAR(100) NULL,
    [PATTERN_NAME] NVARCHAR(100) NULL,
    [ORIGINAL_PATTERN_NAME] NVARCHAR(100) NULL,
    [DRILL_CYCLE_SK] NVARCHAR(100) NULL,
    [DRILL_HOLE_SHIFT_ID] NVARCHAR(100) NULL,
    [DRILL_ID] NVARCHAR(100) NULL,
    [DRILL_BIT_ID] NVARCHAR(100) NULL,
    [SYSTEM_OPERATOR_ID] NVARCHAR(100) NULL,
    [DRILL_HOLE_ID] NVARCHAR(100) NULL,
    [DRILL_HOLE_NAME] NVARCHAR(200) NULL,
    [DRILL_PLAN_SK] NVARCHAR(100) NULL,
    [DRILL_HOLE_STATUS] NVARCHAR(50) NULL,
    [IS_HOLE_PLANNED_FLAG] NVARCHAR(10) NULL,
    [START_HOLE_TS_UTC] DATETIME2 NULL,
    [END_HOLE_TS_UTC] DATETIME2 NULL,
    [START_HOLE_TS_LOCAL] DATETIME2 NULL,
    [END_HOLE_TS_LOCAL] DATETIME2 NULL,
    [DRILL_HOLE_DURATION_SECONDS] FLOAT NULL,
    [ACTUAL_DRILL_HOLE_DEPTH_FEET] FLOAT NULL,
    [ACTUAL_DRILL_HOLE_DEPTH_METERS] FLOAT NULL,
    [GPS_ACCURACY] FLOAT NULL,
    [ACTUAL_DRILL_HOLE_START_FEET_X] FLOAT NULL,
    [ACTUAL_DRILL_HOLE_START_FEET_Y] FLOAT NULL,
    [ACTUAL_DRILL_HOLE_START_FEET_Z] FLOAT NULL,
    [ACTUAL_DRILL_HOLE_END_FEET_X] FLOAT NULL,
    [ACTUAL_DRILL_HOLE_END_FEET_Y] FLOAT NULL,
    [ACTUAL_DRILL_HOLE_END_FEET_Z] FLOAT NULL,
    [ACTUAL_DRILL_HOLE_LONGITUDE] FLOAT NULL,
    [ACTUAL_DRILL_HOLE_LATITUDE] FLOAT NULL,
    [ACTUAL_DRILL_HOLE_START_METERS_X] FLOAT NULL,
    [ACTUAL_DRILL_HOLE_START_METERS_Y] FLOAT NULL,
    [ACTUAL_DRILL_HOLE_START_METERS_Z] FLOAT NULL,
    [ACTUAL_DRILL_HOLE_END_METERS_X] FLOAT NULL,
    [ACTUAL_DRILL_HOLE_END_METERS_Y] FLOAT NULL,
    [ACTUAL_DRILL_HOLE_END_METERS_Z] FLOAT NULL,
    [AUTODRILL_DURATION_SECONDS] FLOAT NULL,
    [AUTODRILL_USAGE_PCT] FLOAT NULL,
    [DRILL_HOLE_PENETRATION_RATE_AVG_FEET_HOUR] FLOAT NULL,
    [OPERATOR_LOGIN_TS_UTC] DATETIME2 NULL,
    [OPERATOR_LOGOUT_TS_UTC] DATETIME2 NULL,
    [OPERATOR_LOGIN_TS_LOCAL] DATETIME2 NULL,
    [OPERATOR_LOGOUT_TS_LOCAL] DATETIME2 NULL,
    [BEARING] FLOAT NULL,
    [DRILL_TOWER_ANGLE_DEGREE_CALCULATED] FLOAT NULL,
    [DRILL_TOWER_ANGLE_DEGREE_SYSTEM] FLOAT NULL,
    [DRILL_HOLE_DUPLICATED_FLAG] NVARCHAR(10) NULL,
    [DRILL_HOLE_UPSIDE_DOWN_FLAG] NVARCHAR(10) NULL,
    [DRILL_HOLE_START_END_TIME_INVALID_FLAG] NVARCHAR(10) NULL,
    [DRILL_HOLE_START_END_TIME_OVERLAP_FLAG] NVARCHAR(10) NULL,
    [DRILL_HOLE_DEPTH_INVALID_FLAG] NVARCHAR(10) NULL,
    [DRILL_HOLE_ANGLE_INVALID_FLAG] NVARCHAR(10) NULL,
    [DRILL_HOLE_POSITION_INVALID_FLAG] NVARCHAR(10) NULL,
    [TIME_BETWEEN_DRILL_HOLES_SECONDS] FLOAT NULL,
    [AIR_PRESSURE_PSI] FLOAT NULL,
    [FEED_FORCE_NEWTONS] FLOAT NULL,
    [ROTATION_TORQUE_NM] FLOAT NULL,
    [BIT_SPEED_RPM] FLOAT NULL,
    [WATER_FLOW_GPM] FLOAT NULL,
    [INSTANTANOUS_PENRATE_MWD_METERS_HOUR] FLOAT NULL,
    [INSTANTANOUS_PENRATE_MWD_FEET_HOUR] FLOAT NULL,
    [DRILL_HOLE_OFF_TARGET_FEET] FLOAT NULL,
    [DRILL_HOLE_OFF_TARGET_METERS] FLOAT NULL,
    [DRILL_HOLE_HORIZONTAL_ACCURACY_PCT] FLOAT NULL,
    [DRILL_HOLE_VERTICAL_ACCURACY_PCT] FLOAT NULL,
    [OVERDRILL_UNDERDRILL_FLAG] NVARCHAR(20) NULL,
    [OVERDRILL_UNDERDRILL_FEET] FLOAT NULL,
    [OVERDRILL_UNDERDRILL_METERS] FLOAT NULL,
    [DRILLING_STOPS_COUNT] INT NULL,
    [DRILL_HOLE_REDRILL_FLAG] NVARCHAR(10) NULL,
    [PROPEL_START_TS_UTC] DATETIME2 NULL,
    [PROPEL_END_TS_UTC] DATETIME2 NULL,
    [PARK_POSITION_START_TS_UTC] DATETIME2 NULL,
    [PARK_POSITION_END_TS_UTC] DATETIME2 NULL,
    [LEVEL_START_TS_UTC] DATETIME2 NULL,
    [LEVEL_END_TS_UTC] DATETIME2 NULL,
    [DRILL_START_TS_UTC] DATETIME2 NULL,
    [DRILL_END_TS_UTC] DATETIME2 NULL,
    [RETRACT_START_TS_UTC] DATETIME2 NULL,
    [RETRACT_END_TS_UTC] DATETIME2 NULL,
    [PROPEL_START_TS_LOCAL] DATETIME2 NULL,
    [PROPEL_END_TS_LOCAL] DATETIME2 NULL,
    [PARK_POSITION_START_TS_LOCAL] DATETIME2 NULL,
    [PARK_POSITION_END_TS_LOCAL] DATETIME2 NULL,
    [LEVEL_START_TS_LOCAL] DATETIME2 NULL,
    [LEVEL_END_TS_LOCAL] DATETIME2 NULL,
    [DRILL_START_TS_LOCAL] DATETIME2 NULL,
    [DRILL_END_TS_LOCAL] DATETIME2 NULL,
    [RETRACT_START_TS_LOCAL] DATETIME2 NULL,
    [RETRACT_END_TS_LOCAL] DATETIME2 NULL,
    [PROPEL_DURATION] FLOAT NULL,
    [PARK_POSITION_DURATION] FLOAT NULL,
    [LEVEL_DURATION] FLOAT NULL,
    [DRILL_DURATION] FLOAT NULL,
    [RETRACT_DURATION] FLOAT NULL,
    [SYSTEM_DRILL_STATE_DURATION_SECONDS] FLOAT NULL,
    [SYSTEM_SETUP_STATE_DURATION_SECONDS] FLOAT NULL,
    [SYSTEM_AUTO_LEVEL_DURATION_SECONDS] FLOAT NULL,
    [SYSTEM_AUTO_DELEVEL_DURATION_SECONDS] FLOAT NULL,
    [PLAN_CREATION_TS_LOCAL] DATETIME2 NULL,
    [SYSTEM_VERSION] NVARCHAR(50) NULL,
    [ACTUAL_MCF_BLOCK_ID] NVARCHAR(100) NULL,
    [DESIGN_MCF_BLOCK_ID] NVARCHAR(100) NULL,
    [DW_LOAD_TS] DATETIME2 NULL,
    [DW_MODIFY_TS] DATETIME2 NULL
);
'''
    cursor.execute(create_sql)
    conn.commit()
    print('SUCCESS: Created [dbo].[DRILL_CYCLE_IMO] table type in DEV!')

# Verify it exists now
cursor.execute("""
SELECT t.name, SCHEMA_NAME(t.schema_id) as schema_name
FROM sys.types t
WHERE t.name LIKE '%DRILL_CYCLE%' AND t.is_table_type = 1
ORDER BY t.name
""")
print('\nTable types matching DRILL_CYCLE:')
for row in cursor.fetchall():
    print(f'  - [{row.schema_name}].[{row.name}]')

conn.close()
print("\nDone!")
