CREATE VIEW [MOR].[PIT_LOC] AS



--SELECT * FROM MOR.PIT_LOC
CREATE VIEW MOR.PIT_LOC
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM MOROperational.dbo.PITPitLoc WITH(NOLOCK)



