CREATE VIEW [MOR].[SHIFT_GRADE] AS



--SELECT * FROM MOR.SHIFT_GRADE
CREATE VIEW MOR.SHIFT_GRADE
AS

SELECT
'MOR' AS SiteFlag,
*
FROM MOROperational.dbo.SHIFTShiftgrade WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM mor.SHIFT_INFO)



