CREATE VIEW [MOR].[SHIFT_LOAD] AS



--SELECT * FROM MOR.SHIFT_LOAD
CREATE VIEW MOR.SHIFT_LOAD
AS

SELECT
'MOR' AS SiteFlag,
*
FROM MOROperational.dbo.SHIFTShiftload WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM mor.SHIFT_INFO)



