CREATE TABLE [MOR].[plan_values_prod_sum] (
    [siteflag] varchar(5) NOT NULL,
    [ContentTypeID] varchar(100) NOT NULL,
    [PlanName] varchar(50) NOT NULL,
    [ComplianceAssetId] varchar(100) NULL,
    [DateEffective] date NULL,
    [TotalOretpd] decimal(18,5) NULL,
    [TotalAC23tpd] decimal(18,5) NULL,
    [TotalAC4tpd] decimal(18,5) NULL,
    [TotalEHtpd] decimal(18,5) NULL,
    [TotalHGtpd] decimal(18,5) NULL,
    [TotalLGtpd] decimal(18,5) NULL,
    [TotalOxidetpd] decimal(18,5) NULL,
    [TotalROMtpd] decimal(18,5) NULL,
    [TotalWastetpd] decimal(18,5) NULL,
    [TotalExPittpd] decimal(18,5) NULL,
    [TransferOreMFL] decimal(18,5) NULL,
    [TransferOreMill] decimal(18,5) NULL,
    [TotalInpitDump] decimal(18,5) NULL,
    [TotalMinedtpd] decimal(18,5) NULL,
    [TotalMovedtpd] decimal(18,5) NULL,
    [CrusherMFLtpd] decimal(18,5) NULL,
    [CrusherMilltpd] decimal(18,5) NULL,
    [910tpd] varchar(50) NULL,
    [PitAMTtpd] decimal(18,5) NULL,
    [PitCORtpd] decimal(18,5) NULL,
    [PitPONtpd] decimal(18,5) NULL,
    [PitGARtpd] decimal(18,5) NULL,
    [PitLONtpd] decimal(18,5) NULL,
    [PitSHAtpd] decimal(18,5) NULL,
    [PitSUNtpd] decimal(18,5) NULL,
    [PitWCPtpd] decimal(18,5) NULL,
    [PitWCP14tpd] decimal(18,5) NULL,
    [PitWCP10tpd] decimal(18,5) NULL,
    [LoadingAvailability] decimal(18,5) NULL,
    [LoadingAssetEfficiency] decimal(18,5) NULL,
    [TruckAvailability] decimal(18,5) NULL,
    [TruckAssetEfficiency] decimal(18,5) NULL,
    [AvgCountReadyTrucks] decimal(18,5) NULL,
    [EquivalentFlatHaul] decimal(18,5) NULL,
    [EmptyEFH] varchar(100) NULL,
    [EmptyTravelMiles] varchar(100) NULL,
    [LoadedTravelMiles] varchar(100) NULL,
    [TotalCycleTime] decimal(18,5) NULL,
    [DeltaC] decimal(18,5) NULL,
    [ElecShovelLoadTonsOnReadyHour] decimal(18,5) NULL,
    [ElecShovelAvailability] decimal(18,5) NULL,
    [ElecShovelAssetEfficiency] decimal(18,5) NULL,
    [ElecShovelUseOfAvailability] decimal(18,5) NULL,
    [ElecShovelAvgReadyNumber] decimal(18,5) NULL,
    [HydShovelLoadTonsOnReadyHour] decimal(18,5) NULL,
    [HydShovelAvailability] decimal(18,5) NULL,
    [HydShovelAssetEfficiency] decimal(18,5) NULL,
    [HydShovelUseOfAvailability] decimal(18,5) NULL,
    [HydShovelAvgReadyNumber] decimal(18,5) NULL,
    [EmptyOneWayHaul] decimal(18,5) NULL,
    [EmptyLifts] decimal(18,5) NULL,
    [EmptyDrops] decimal(18,5) NULL,
    [Spoting] decimal(18,5) NULL,
    [Loading] decimal(18,5) NULL,
    [LoadedTravel] decimal(18,5) NULL,
    [DumpingAtCrusher] decimal(18,5) NULL,
    [DumpingatStockpile] decimal(18,5) NULL,
    [EmptyTravel] decimal(18,5) NULL,
    [EFH_GAR] decimal(18,5) NULL,
    [EFH_SUN] decimal(18,5) NULL,
    [EFH_WCP] decimal(18,5) NULL,
    [Crrrr] decimal(18,5) NULL,
    [TrkDumpTnReadyHr] decimal(18,5) NULL,
    [WCPDeltaC] decimal(18,5) NULL,
    [SUNDeltaC] decimal(18,5) NULL,
    [GARDeltaC] decimal(18,5) NULL,
    [TotalLoadTnsReadyHr] decimal(18,5) NULL,
    [TotalDumpTnsReadyHr] decimal(18,5) NULL,
    [TruckUtil] decimal(18,5) NULL,
    [FuelBurnGal] decimal(18,5) NULL,
    [FuelBurnHr] decimal(18,5) NULL,
    [TireMiles] decimal(18,5) NULL,
    [FrontTireRot] decimal(18,5) NULL,
    [RockCut_prctg] decimal(18,2) NULL,
    [Miles_32nd] decimal(18,5) NULL,
    [MTBME] decimal(18,5) NULL,
    [Haulage$_ton] decimal(18,5) NULL,
    [Fuel$_ton] decimal(18,5) NULL,
    [MTTR] decimal(18,5) NULL,
    [OverExpectedDeltaC_prctg] decimal(18,2) NULL,
    [Loaded_prctg] decimal(18,2) NULL,
    [Empty_prctg] decimal(18,2) NULL,
    [ReadyDrills] decimal(18,5) NULL,
    [DrillHolesperDay] decimal(18,5) NULL,
    [DeltaCLoadedTravel] decimal(18,5) NULL,
    [DeltaCEmptyTravel] decimal(18,5) NULL,
    [DeltaCDumpCr] decimal(18,5) NULL,
    [DeltaCDumpStk] decimal(18,5) NULL,
    [AMTTons] decimal(18,5) NULL,
    [P10Tons] decimal(18,5) NULL,
    [P14Tons] decimal(18,5) NULL,
    [CORTons] decimal(18,5) NULL,
    [Id] int NOT NULL,
    [ContentType] varchar(50) NOT NULL,
    [Modified] datetime NOT NULL,
    [Created] datetime NOT NULL,
    [CreatedById] int NOT NULL,
    [ModifiedById] int NOT NULL,
    [Owshiddenversion] int NOT NULL,
    [Version] decimal(10,5) NOT NULL,
    [Path] varchar(2000) NOT NULL,
    [UTC_CREATED_DATE] datetime NULL
);