CREATE VIEW [SIE].[SHIFT_LOAD] AS



--SELECT * FROM SIE.SHIFT_LOAD
CREATE VIEW SIE.SHIFT_LOAD
AS

SELECT
'SIE' AS SiteFlag,
*
FROM SIEOperational.dbo.SHIFTShiftload WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM SIE.SHIFT_INFO)



