CREATE VIEW [CER].[CONOPS_CER_DRILL_OPERATOR_CONSECUTIVE_WORKDAYS_V] AS



-- SELECT * FROM [cer].[CONOPS_CER_DRILL_OPERATOR_CONSECUTIVE_WORKDAYS_V] WITH (NOLOCK) WHERE Shiftflag = 'PREV'
CREATE VIEW [cer].[CONOPS_CER_DRILL_OPERATOR_CONSECUTIVE_WORKDAYS_V] 
AS

	SELECT LASTSHIFTINDEX AS Shiftindex,
		   SITE_CODE,
		   OPERID,
		   NROFDAYS
	FROM dbo.OPERATOR_CONSECUTIVE_WORKDAYS WITH (NOLOCK)
	WHERE SITE_CODE = 'CER' AND UNIT_CODE IN (14, 43)



