CREATE TABLE [TYR].[EQUIPMENT_HOURLY_STATUS_STG_2] (
    [SHIFTINDEX] numeric(38,0) NOT NULL,
    [SHIFTDATE] date NULL,
    [SHIFT_CODE] numeric(38,0) NULL,
    [SHIFT] varchar(64) NULL,
    [CREW] varchar(64) NULL,
    [SITE_CODE] varchar(4) NOT NULL,
    [CLIID] numeric(38,0) NULL,
    [DDBKEY] real NULL,
    [EQMT] varchar(50) NOT NULL,
    [UNIT] real NULL,
    [OPERID] varchar(21) NULL,
    [HOS] numeric(38,0) NULL,
    [START_TIME_TS] datetime NOT NULL,
    [STARTTIME] numeric(18,0) NULL,
    [END_TIME_TS] datetime NULL,
    [ENDTTIME] numeric(18,0) NULL,
    [DURATION] real NULL,
    [REASON] real NULL,
    [STATUS] real NULL,
    [CATEGORY] real NULL,
    [COMMENTS] varchar(90) NULL,
    [VEVENT] real NULL,
    [REASONLINK] real NULL,
    [LOC] varchar(256) NULL,
    [REGION] varchar(256) NULL,
    [GPS_X] real NULL,
    [GPS_Y] real NULL,
    [GPS_STATE] numeric(38,0) NULL,
    [GPS_HEADING] numeric(38,0) NULL,
    [GPS_VELOCITY] numeric(38,0) NULL,
    [SYSTEM_VERSION] varchar(50) NULL,
    [UTC_CREATED_DATE] datetime NULL
);