CREATE VIEW [CER].[EQUIPMENT_HOURLY_STATUS] AS

--SELECT * FROM CER.EQUIPMENT_HOURLY_STATUS
CREATE VIEW CER.EQUIPMENT_HOURLY_STATUS
AS

SELECT *
FROM CER.EQUIPMENT_HOURLY_STATUS_2 WITH(NOLOCK)

