CREATE VIEW [ABR].[CONOPS_ABR_DAILY_EOS_CRUSHER_STATS_V] AS
  
--SELECT * FROM [abr].[CONOPS_ABR_DAILY_EOS_CRUSHER_STATS_V] WITH (NOLOCK) WHERE SHIFTFLAG = 'CURR'    
CREATE VIEW [abr].[CONOPS_ABR_DAILY_EOS_CRUSHER_STATS_V]    
AS    
  
WITH RecursiveCTE AS (
    SELECT 
        SITEFLAG,
        SHIFTINDEX,
        CRUSHERLOC,
        NOOFTRUCKWAITING,
        UTC_CREATED_DATE,
        NEXT_DATE,
        minute_diff
    FROM (
        SELECT *,
        DATEDIFF(MINUTE, UTC_CREATED_DATE, NEXT_DATE) AS minute_diff
        FROM (
            SELECT *, 
            LEAD(UTC_CREATED_DATE) OVER(PARTITION BY SITEFLAG, SHIFTINDEX, CRUSHERLOC ORDER BY UTC_CREATED_DATE) AS NEXT_DATE
            FROM dbo.crusher_stats
            WHERE SITEFLAG = 'ABR'
        ) a
    ) b

    UNION ALL

    SELECT 
        r.SITEFLAG,
        r.SHIFTINDEX,
        r.CRUSHERLOC,
        NULL AS NOOFTRUCKWAITING,
        DATEADD(MINUTE, 15, r.UTC_CREATED_DATE) AS UTC_CREATED_DATE,
        r.NEXT_DATE,
        DATEDIFF(MINUTE, DATEADD(MINUTE, 15, r.UTC_CREATED_DATE), r.NEXT_DATE) AS minute_diff
    FROM RecursiveCTE r
    WHERE DATEDIFF(MINUTE, r.UTC_CREATED_DATE, r.NEXT_DATE) > 15
)

SELECT s.SHIFTFLAG  
   ,s.SITEFLAG  
   ,s.SHIFTSTARTDATETIME  
   ,s.SHIFTENDDATETIME  
   ,cs.CRUSHERLOC
   ,DATEADD(HOUR,s.current_utc_offset,cs.UTC_CREATED_DATE) AS DateTime
   ,cs.NOOFTRUCKWAITING
FROM [ABR].CONOPS_ABR_EOS_SHIFT_INFO_V s WITH (NOLOCK)
LEFT JOIN RecursiveCTE cs WITH (NOLOCK)
ON s.SHIFTINDEX = cs.SHIFTINDEX AND s.SITEFLAG = cs.SITEFLAG
--ORDER BY DateTime

