CREATE VIEW [ABR].[CONOPS_ABR_DRILL_OPERATOR_CONSECUTIVE_WORKDAYS_V] AS


-- SELECT * FROM [abr].[CONOPS_ABR_DRILL_OPERATOR_CONSECUTIVE_WORKDAYS_V] WITH (NOLOCK) WHERE Shiftflag = 'PREV'
CREATE VIEW [abr].[CONOPS_ABR_DRILL_OPERATOR_CONSECUTIVE_WORKDAYS_V] 
AS

	SELECT LASTSHIFTINDEX AS Shiftindex,
		   SITE_CODE,
		   OPERID,
		   NROFDAYS
	FROM dbo.OPERATOR_CONSECUTIVE_WORKDAYS WITH (NOLOCK)
	WHERE SITE_CODE = 'ELA' AND UNIT_CODE = 12

