CREATE VIEW [TYR].[CONOPS_TYR_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V] AS



  -- SELECT * FROM [tyr].[CONOPS_TYR_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V] WITH (NOLOCK) 
CREATE VIEW [TYR].[CONOPS_TYR_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V]   
AS  
  
SELECT 
LASTSHIFTINDEX AS Shiftindex,  
SITE_CODE,  
OPERID,  
NROFDAYS  
FROM dbo.OPERATOR_CONSECUTIVE_WORKDAYS WITH (NOLOCK)  
WHERE SITE_CODE = 'TYR' AND UNIT_CODE = 2
  

