CREATE VIEW [TYR].[CONOPS_TYR_AUTONOMOUS_TRUCK_V] AS


--select * from [TYR].[CONOPS_TYR_AUTONOMOUS_TRUCK_V]
CREATE VIEW [TYR].[CONOPS_TYR_AUTONOMOUS_TRUCK_V]
AS

SELECT DISTINCT
	FieldId AS TruckId,
	0 AS Autonomous
FROM TYR.pit_truck_c WITH(NOLOCK)
WHERE FieldId IS NOT NULL
	AND FieldId <> ''

