CREATE VIEW [CLI].[EQUIPMENT_HOURLY_STATUS] AS

--SELECT * FROM CLI.EQUIPMENT_HOURLY_STATUS
CREATE VIEW CLI.EQUIPMENT_HOURLY_STATUS
AS

SELECT *
FROM CLI.EQUIPMENT_HOURLY_STATUS_2 WITH(NOLOCK)

