CREATE VIEW [CLI].[PIT_WORKER] AS



--SELECT * FROM CLI.PIT_WORKER
CREATE VIEW CLI.PIT_WORKER
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM CMXOperational.dbo.PITWorker



