CREATE VIEW [CLI].[PIT_LOC] AS



--SELECT * FROM CLI.PIT_LOC
CREATE VIEW CLI.PIT_LOC
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM CMXOperational.dbo.PITPitLoc WITH(NOLOCK)



