CREATE VIEW [CLI].[SHIFT_GRADE] AS



--SELECT * FROM CLI.SHIFT_GRADE
CREATE VIEW CLI.SHIFT_GRADE
AS

SELECT
'CMX' AS SiteFlag,
*
FROM CMXOperational.dbo.SHIFTShiftgrade WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM CLI.SHIFT_INFO)



