CREATE VIEW [CLI].[SHIFT_OPER] AS




--SELECT * FROM CLI.SHIFT_OPER
CREATE VIEW CLI.SHIFT_OPER
AS

SELECT
'CMX' AS SiteFlag,
*
FROM CMXOperational.dbo.SHIFTShiftOper WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM CLI.SHIFT_INFO)




