CREATE VIEW [dbo].[ZZZ_CONOPS_DB_DRILL_ASSET_EFFICIENCY_TARGET_V] AS


--SELECT * FROM [dbo].[CONOPS_DB_DRILL_ASSET_EFFICIENCY_TARGET_V] where shiftflag = 'curr' 
CREATE VIEW [dbo].[CONOPS_DB_DRILL_ASSET_EFFICIENCY_TARGET_V]
AS

	SELECT [ShiftId],
	       [siteflag],
		   [DRILLAVAILABILITY],
		   [DRILLASSETEFFICIENCY],
		   [DRILLUTILIZATION]
	FROM [bag].[CONOPS_BAG_DB_DRILL_ASSET_EFFICIENCY_TARGET_V]

	UNION ALL

	SELECT [ShiftId],
	       [siteflag],
		   [DRILLAVAILABILITY],
		   [DRILLASSETEFFICIENCY],
		   [DRILLUTILIZATION]
	FROM [saf].[CONOPS_SAF_DB_DRILL_ASSET_EFFICIENCY_TARGET_V]

	UNION ALL

	SELECT [ShiftId],
	       [siteflag],
		   [DRILLAVAILABILITY],
		   [DRILLASSETEFFICIENCY],
		   [DRILLUTILIZATION]
	FROM [cer].[CONOPS_CER_DB_DRILL_ASSET_EFFICIENCY_TARGET_V]

	UNION ALL

	SELECT [ShiftId],
	       [siteflag],
		   [DRILLAVAILABILITY],
		   [DRILLASSETEFFICIENCY],
		   [DRILLUTILIZATION]
	FROM [sie].[CONOPS_SIE_DB_DRILL_ASSET_EFFICIENCY_TARGET_V]

	UNION ALL

	SELECT [ShiftId],
	       [siteflag],
		   [DRILLAVAILABILITY],
		   [DRILLASSETEFFICIENCY],
		   [DRILLUTILIZATION]
	FROM [chi].[CONOPS_CHI_DB_DRILL_ASSET_EFFICIENCY_TARGET_V]

