CREATE VIEW [dbo].[CONOPS_DB_DRILL_SCORES_V] AS

   
    
    
--SELECT * FROM [DBO].[CONOPS_DB_DRILL_SCORES_V] WITH (NOLOCK) WHERE SHIFTFLAG = 'PREV'    
CREATE VIEW [DBO].[CONOPS_DB_DRILL_SCORES_V]    
AS    
    
 WITH DRILLKPI AS (    
  SELECT [DS].[SHIFTINDEX],    
      CASE [DS].[SITE_CODE]    
     WHEN 'CLI' THEN 'CMX'    
     ELSE [DS].[SITE_CODE]    
      END  AS [SITE_CODE],    
      CASE [DS].[SITE_CODE]    
     WHEN 'CHI' THEN 'DRL' + LEFT(DRILL_ID, 2)    
     WHEN 'CLI' THEN LEFT(DRILL_ID, 2) + RIGHT('00' + RIGHT(DRILL_ID, 1), 2)    
     WHEN 'SAF' THEN 'D' + RIGHT('000' + SUBSTRING(DRILL_ID,CHARINDEX('-',DRILL_ID)+1,LEN(DRILL_ID)), 3)    
     WHEN 'SIE' THEN 'DR' + RIGHT(DRILL_ID, 2)    
     ELSE REPLACE(DRILL_ID, ' ','')     
      END  AS DRILL_ID,    
      CASE WHEN COUNT([DRILL_ID]) = 0 THEN 0    
        ELSE (SUM([HORIZ_DIFF_FLAG]) / COUNT([DRILL_ID])) * 100    
      END  AS [XY_DRILL_SCORE],    
      CASE WHEN COUNT([DRILL_ID]) = 0 THEN 0    
     ELSE (SUM([DEPTH_DIFF_FLAG]) / COUNT([DRILL_ID])) * 100    
      END  AS [DEPTH_DRILL_SCORE],    
      CASE WHEN COUNT([DRILL_ID]) = 0 THEN 0    
        ELSE (SUM([OVER_DRILLED]) / COUNT([DRILL_ID])) * 100    
      END  AS [OVER_DRILL],    
      CASE WHEN COUNT([DRILL_ID]) = 0 THEN 0    
        ELSE (SUM([UNDER_DRILLED]) / COUNT([DRILL_ID])) * 100    
      END  AS [UNDER_DRILL],    
      AVG([PENRATE]) AS [AVERAGE_PEN_RATE],    
      AVG([GPS_QUALITY]) * 100 AS [AVERAGE_GPS_QUALITY],    
      COUNT(DRILL_HOLE) AS [HOLES_DRILLED],    
      SUM(START_POINT_Z) - SUM(ZACTUALEND) AS [FEET_DRILLED],    
      AVG(HOLETIME) AS [AVERAGE_HOLETIME],    
      SUM([DEPTH]) AS [TOTAL_DEPTH]    
  FROM [DBO].[FR_DRILLING_SCORES] [DS] WITH (NOLOCK)    
  GROUP BY [DS].[SHIFTINDEX], [DS].[SITE_CODE], DRILL_ID    
 ),    
    
 DRILLTIME AS (    
  SELECT [SHIFTINDEX],    
      CASE [SITE_CODE]    
     WHEN 'CLI' THEN 'CMX'    
     ELSE [SITE_CODE]    
      END AS [SITE_CODE],    
      CASE [SITE_CODE]    
     WHEN 'CHI' THEN 'DRL' + LEFT(DRILL_ID, 2)    
     WHEN 'CLI' THEN LEFT(DRILL_ID, 2) + RIGHT('00' + RIGHT(DRILL_ID, 1), 2)    
     WHEN 'SAF' THEN 'D' + RIGHT('000' + SUBSTRING(DRILL_ID,CHARINDEX('-',DRILL_ID)+1,LEN(DRILL_ID)), 3)    
     WHEN 'SIE' THEN 'DR' + RIGHT(DRILL_ID, 2)    
     ELSE REPLACE(DRILL_ID, ' ','')     
      END AS DRILL_ID,    
      [START_HOLE_TS] AS STARTDATETIME,    
      [END_HOLE_TS] AS ENDDATETIME,    
      LEAD([START_HOLE_TS]) OVER ( PARTITION BY [DRILL_ID] ORDER BY [START_HOLE_TS] ASC ) AS [NEXTSTARTDATETIME] ,    
      ROW_NUMBER() OVER ( PARTITION BY [DRILL_ID] ORDER BY [START_HOLE_TS] ASC ) AS [DRILLINDEX]    
  FROM [DBO].[FR_DRILLING_SCORES] WITH (NOLOCK)    
 ),    
    
 FIRSTDRILLHOLE AS (    
  SELECT SITE_CODE,    
      SHIFTINDEX,    
      DRILL_ID,    
      CAST(AVG(CAST(DT.STARTDATETIME AS FLOAT)) AS DATETIME) AS [AVERAGESTARTDATETIME]    
  FROM DRILLTIME DT    
  WHERE DT.DRILLINDEX = 1    
  GROUP BY SITE_CODE, SHIFTINDEX, DRILL_ID    
 ),    
    
 DRILLTIMEBETWEENHOLES AS (     
  SELECT SITE_CODE,    
      SHIFTINDEX,    
      DRILL_ID,    
      AVG(DATEDIFF_BIG(SECOND, DT.ENDDATETIME, DT.NEXTSTARTDATETIME)) / 60.00 AS [AVERAGETIME]    
 FROM DRILLTIME DT    
 WHERE DT.NEXTSTARTDATETIME IS NOT NULL    
  GROUP BY SITE_CODE, SHIFTINDEX, DRILL_ID    
 )    
    
 SELECT A.SHIFTFLAG,    
     A.SITEFLAG,    
     [DRILL_ID],    
     ISNULL([XY_DRILL_SCORE], 0) AS [XY_DRILL_SCORE],    
     ISNULL([DEPTH_DRILL_SCORE], 0) AS [DEPTH_DRILL_SCORE],    
     ISNULL([OVER_DRILL], 0) AS [OVER_DRILL],    
     ISNULL([UNDER_DRILL], 0) AS [UNDER_DRILL],    
     ISNULL([AVG_TIME_BETWEEN_HOLES], 0) AS [AVG_TIME_BETWEEN_HOLES],    
     ISNULL([AVERAGE_PEN_RATE], 0) AS [AVERAGE_PEN_RATE],    
     ISNULL([AVERAGE_GPS_QUALITY], 0) AS [AVERAGE_GPS_QUALITY],    
     DATEDIFF(SECOND, A.SHIFTSTARTDATETIME, [AVERAGE_FIRST_LAST_DRILL]) / 60.00 AS [AVERAGE_