CREATE VIEW [dbo].[OPERATOR_PERSONNEL_MAP] AS

--SELECT * FROM dbo.OPERATOR_PERSONNEL_MAP
CREATE VIEW dbo.OPERATOR_PERSONNEL_MAP
AS

SELECT *
FROM dbo.OPERATOR_PERSONNEL_MAP_2 WITH(NOLOCK)

