CREATE VIEW [BAG].[CONOPS_BAG_EQMT_TRUCK_HOURLY_PAYLOAD_V] AS






--SELECT * FROM [bag].[CONOPS_BAG_EQMT_TRUCK_HOURLY_PAYLOAD_V] WHERE shiftflag = 'curr'   
CREATE VIEW [bag].[CONOPS_BAG_EQMT_TRUCK_HOURLY_PAYLOAD_V]  
AS  
  
WITH CTE AS(
SELECT
	b.SHIFTFLAG,
	SITE_CODE AS SITEFLAG,
	b.ShiftStartDateTime,
	SHIFT_ID AS SHIFTID,
	b.SHIFTINDEX,
	TRUCK_NAME AS EQUIPMENT,
	LOAD_HOS - 1 AS HOS,
	AVG(MEASURED_PAYLOAD_SHORT_TONS) AS PAYLOAD
FROM BAG.FLEET_TRUCK_CYCLE_V a
RIGHT JOIN BAG.CONOPS_BAG_SHIFT_INFO_V b
	ON a.SHIFT_ID = b.SHIFTID
WHERE MEASURED_PAYLOAD_SHORT_TONS >= (SELECT PayloadFilterLower FROM dbo.PAYLOAD_FILTER WHERE SITEFLAG = 'BAG')
GROUP BY SHIFTFLAG, SITE_CODE, ShiftStartDateTime, SHIFT_ID, SHIFTINDEX, TRUCK_NAME, LOAD_HOS
)

SELECT
	SHIFTFLAG,
	SITEFLAG,
	EQUIPMENT,
	PAYLOAD,
	dateadd(hour,HOS,ShiftStartDateTime) as TimeinHour 
FROM CTE
  




