CREATE VIEW [BAG].[CONOPS_BAG_PAYLOAD_MEASURETON_V] AS






--select * from [BAG].[CONOPS_BAG_PAYLOAD_MEASURETON_V] where shiftflag = 'curr'
CREATE VIEW [BAG].[CONOPS_BAG_PAYLOAD_MEASURETON_V]
AS

SELECT
	SITE_CODE AS SITEFLAG,
	SHIFT_ID AS SHIFTID,
	TRUCK_NAME AS TRUCK,
	SHOVEL_NAME AS EXCAV,
	MEASURED_PAYLOAD_SHORT_TONS AS MEASURETON,
	PayloadTarget
FROM BAG.FLEET_TRUCK_CYCLE_V a
LEFT JOIN dbo.PAYLOAD_TARGET t WITH(NOLOCK)
	ON a.site_code = t.siteflag
WHERE MEASURED_PAYLOAD_SHORT_TONS >= (SELECT PayloadFilterLower FROM dbo.PAYLOAD_FILTER WHERE SITEFLAG = 'BAG')

