CREATE VIEW [BAG].[CONOPS_BAG_SHIFT_INFO_V] AS





--SELECT * FROM [BAG].[CONOPS_BAG_SHIFT_INFO_V]    
    
CREATE VIEW [bag].[CONOPS_BAG_SHIFT_INFO_V]     
AS    

WITH TimeZone AS(
SELECT 
	name AS TimeZoneName,
	is_currently_dst,
	CAST(CAST(current_utc_offset AS VARCHAR(3)) AS INT) AS current_utc_offset,
	CAST(CAST(current_utc_offset AS VARCHAR(3)) AS INT) - DATEPART(TZ, SYSDATETIMEOFFSET()) / 60 AS current_server_offset
FROM sys.time_zone_info
WHERE name = 'US Mountain Standard Time'
),

CurrPrevShift AS(
SELECT TOP 2
CASE WHEN ROW_NUMBER() OVER(ORDER BY SHIFT_START_DATE_TIME DESC) = 1
	THEN 'CURR' COLLATE SQL_Latin1_General_CP1_CI_AS
	ELSE 'PREV' END COLLATE SQL_Latin1_General_CP1_CI_AS AS SHIFTFLAG
, *
FROM ConnectedOperations.bag2.MSMODEL_SHIFT
ORDER BY SHIFT_START_DATE_TIME DESC
),

NextShift AS(
SELECT
	'NEXT' AS SHIFTFLAG,
	SITE_CODE COLLATE SQL_Latin1_General_CP1_CI_AS AS SITE_CODE,
	CASE WHEN RIGHT(SHIFT_ID, 1) = 2    
		THEN RIGHT(CONCAT(REPLACE(CAST(DATEADD(DAY, 1, CAST(LEFT(SHIFT_ID, 6) AS DATE)) AS VARCHAR(10)), '-', ''), '001'), 9) COLLATE SQL_Latin1_General_CP1_CI_AS
		ELSE RIGHT(CONCAT(REPLACE(CAST(DATEADD(DAY, 1, CAST(LEFT(SHIFT_ID, 6) AS DATE)) AS VARCHAR(10)), '-', ''), '002'), 9) COLLATE SQL_Latin1_General_CP1_CI_AS
		END COLLATE SQL_Latin1_General_CP1_CI_AS AS SHIFT_ID,
	NULL AS SHIFT_NAME,
	NULL AS SHIFT_SUFFIX,
	CASE WHEN FULL_SHIFT_SUFFIX = 'Day Shift'
		THEN 'Night Shift' COLLATE SQL_Latin1_General_CP1_CI_AS
		ELSE 'Day Shift' COLLATE SQL_Latin1_General_CP1_CI_AS
		END COLLATE SQL_Latin1_General_CP1_CI_AS AS FULL_SHIFT_SUFFIX,
	NULL AS SHIFT_START_DATE,
	DATEADD(HH, 12, SHIFT_START_DATE_TIME) AS SHIFT_START_DATE_TIME,
	NULL AS STARTS,
	NULL AS CREW_NAME,
	0 AS SHIFT_DURATION,
	NULL AS SHIFT_DATE
FROM CurrPrevShift
WHERE SHIFTFLAG = 'CURR'
),

Last3Shift AS(
SELECT * FROM CurrPrevShift
UNION
SELECT * FROM NextShift
)

SELECT
	SITE_CODE AS SITEFLAG,
	SHIFTFLAG,
	SHIFT_ID COLLATE SQL_Latin1_General_CP1_CI_AS AS SHIFTID,
	(CONVERT(INT, (DATEDIFF(DD, '7/12/2007', CAST(SHIFT_START_DATE_TIME AS DATE))*2) + 27412 + (SELECT RIGHT([SHIFT_ID],1) - 1))) SHIFTINDEX,
	CAST(SHIFT_START_DATE_TIME AS DATETIME) AS SHIFTSTARTDATETIME,
	CAST(DATEADD(HH, 12, SHIFT_START_DATE_TIME) AS DATETIME) AS SHIFTENDDATETIME,
	CASE WHEN SHIFTFLAG = 'CURR'
		THEN DATEDIFF(SECOND, CAST(SHIFT_START_DATE_TIME AS DATETIME), GETDATE())
		ELSE SHIFT_DURATION 
		END AS SHIFTDURATION,
	REPLACE(CREW_NAME, 'Crew', '') AS CrewID,
	CAST(SHIFT_START_DATE_TIME AS DATE) AS SHIFTSTARTDATE,
	FULL_SHIFT_SUFFIX AS SHIFTNAME,
	TZ.TimeZoneName,
	TZ.is_currently_dst,
	TZ.current_utc_offset,
	TZ.current_server_offset
FROM Last3Shift S
CROSS JOIN TimeZone TZ






