CREATE VIEW [BAG].[CONOPS_BAG_SHIFT_BASE_TARGET_V] AS

--select * from [BAG].[CONOPS_BAG_SHIFT_BASE_TARGET_V] 
CREATE VIEW [bag].[CONOPS_BAG_SHIFT_BASE_TARGET_V]
AS

SELECT
	SITEFLAG,
	FORMATSHIFTID AS ShiftId,
	CAST(SUM(TOTALMINED) AS INT) AS TonsMinedTarget,
	CAST(SUM(TOTALMOVED) AS INT) AS TonsMovedTarget,
	MAX(EFH) AS EFHTarget
FROM [bag].[plan_values] WITH (NOLOCK)
GROUP BY SITEFLAG, FORMATSHIFTID;

