CREATE VIEW [BAG].[CONOPS_BAG_OPERATOR_EQMT_READY_HOURS_V] AS





--select * from [BAG].[CONOPS_BAG_OPERATOR_EQMT_READY_HOURS_V]
CREATE VIEW [BAG].[CONOPS_BAG_OPERATOR_EQMT_READY_HOURS_V]
AS

WITH OPER_SUM AS(
SELECT
	SITE_CODE,
	SHIFTINDEX AS SHIFTINDEX_ORI,
	CASE WHEN LOGINTIME > 38700 
		THEN SHIFTINDEX + 1
		ELSE SHIFTINDEX
	END AS SHIFTINDEX,
	UNIT,
	EQMTID,
	LOGINTIME,
	OPERID,
	NAME AS OPERNAME
FROM dbo.LH_OPER_TOTAL_SUM WITH(NOLOCK)
WHERE SITE_CODE = 'BAG'
	AND OPERID IS NOT NULL
	AND OPERID <> '000000'
),

EqStatus AS(
SELECT 
	SHIFTINDEX,
	EQMT,
	UNIT,
	PRIMARYOPERATOR_ID AS OPERID,
	SUM(DURATION) AS ReadyTimes,
	SUM(DURATION) / 3600.0 AS ReadyHours
FROM bag.FLEET_EQUIPMENT_HOURLY_STATUS WITH(NOLOCK)
WHERE CATEGORY IN (1,2)
GROUP BY 
	SHIFTINDEX,
	EQMT,
	UNIT,
	PRIMARYOPERATOR_ID
)

SELECT
	a.SITE_CODE,
	a.SHIFTINDEX,
	a.EQMTID AS EQMT,
	a.UNIT,
	a.OPERID AS OperatorId,
	a.OPERNAME AS OperatorName,
	ReadyTimes,
	ReadyHours
FROM OPER_SUM a
LEFT JOIN EqStatus b
	ON a.SHIFTINDEX_ORI = b.SHIFTINDEX
	AND a.EQMTID = b.EQMT
	AND a.OPERID = b.OPERID
WHERE a.UNIT = 'Haul Truck'


