CREATE VIEW [BAG].[CONOPS_BAG_TRUCK_SHOP_LOCATION_V] AS






-- SELECT * FROM [bag].[CONOPS_BAG_TRUCK_SHOP_LOCATION_V] WITH (NOLOCK)
CREATE VIEW [bag].[CONOPS_BAG_TRUCK_SHOP_LOCATION_V]
AS

Select
L.NAME COLLATE SQL_Latin1_General_CP1_CI_AS AS Name,
NULL AS Unit,
NULL AS Region,
V.ROUTE_POINT_X  AS X,
V.ROUTE_POINT_Y AS Y,
V.ROUTE_POINT_Z AS Z
from 
[ConnectedOperations].[bag2].[LOCATION] L WITH (NOLOCK)
LEFT JOIN [ConnectedOperations].[bag2].[LOCATION_WAYPOINT] LW WITH (NOLOCK)
	ON L.LOCATION_OID = LW.OID
LEFT JOIN [ConnectedOperations].[bag2].[VIRTUALBEACON] V WITH (NOLOCK)
	ON LW.WAYPOINT_OID = V.VIRTUALBEACON_OID
WHERE L.ISSTATION = 1



