CREATE VIEW [BAG].[CONOPS_BAG_EQMT_SHOVEL_HOURLY_PAYLOAD_V] AS


--SELECT * FROM [bag].[CONOPS_BAG_EQMT_SHOVEL_HOURLY_PAYLOAD_V] WHERE shiftflag = 'curr'   
CREATE VIEW [bag].[CONOPS_BAG_EQMT_SHOVEL_HOURLY_PAYLOAD_V]  
AS  

SELECT
	b.SHIFTFLAG,
	a.SITE_CODE AS SITEFLAG,
	b.SHIFTINDEX,
	SHOVEL_NAME AS EQUIPMENT,
	AVG(MEASURED_PAYLOAD_SHORT_TONS) AS PAYLOAD,
	DATEADD(HOUR, LOAD_HOS - 1, b.shiftstartdatetime) AS TimeInHour
FROM BAG.FLEET_TRUCK_CYCLE_V a
RIGHT JOIN BAG.CONOPS_BAG_SHIFT_INFO_V b
	ON a.SHIFT_ID = b.SHIFTID
WHERE MEASURED_PAYLOAD_SHORT_TONS >= (SELECT PayloadFilterLower FROM dbo.PAYLOAD_FILTER WHERE SITEFLAG = 'BAG')
GROUP BY SHIFTFLAG, SITE_CODE, ShiftStartDateTime, SHIFT_ID, SHIFTINDEX, SHOVEL_NAME, LOAD_HOS
  


