

  
  
    
    
    
/******************************************************************      
* PROCEDURE : [CLI].[UPSERT_CONOPS_PLAN_VALUES_MONTHLY_TARGET]     
* PURPOSE : Upsert [UPSERT_CONOPS_PLAN_VALUES_MONTHLY_TARGET]    
* NOTES     :     
* CREATED : mfahmi    
* SAMPLE    : EXEC CLI.[UPSERT_CONOPS_PLAN_VALUES_MONTHLY_TARGET]   
* MODIFIED DATE  AUTHOR    DESCRIPTION      
*------------------------------------------------------------------      
* {07 MAR 2023}  {mfahmi}   {Initial Created}
* {05 DEC 2023}  {GGOSAL1}  {Add: update table monitoring}
*******************************************************************/      
CREATE  PROCEDURE [cli].[UPSERT_CONOPS_PLAN_VALUES_MONTHLY_TARGET]    
AS    
BEGIN    
    
MERGE CLI.PLAN_VALUES_MONTHLY_TARGET AS T     
USING (SELECT    
'CMX' AS SITEFLAG,   
CONTENTTYPEID,
TITLE,
COMPLIANCEASSETID,
YEARVALUE,
MONTHVALUE,
TRUCKAVAILABILITY,
TRUCKUTILIZATION,
TRUCKASSETEFFICIENCY,
C_340AVAILABILITY,
C_340UTILIZATION,
C_340ASSETEFFICIENCY,
C_994AVAILABILITY,
C_994UTILIZATION,
C_994ASSETEFFICIENCY,
DRILLAVAILABILITY,
DRILLUTILIZATION,
DRILLASSETEFFICIENCY,
SHOVELAVAILABILITY,
SHOVELUTILIZATION,
SHOVELASSETEFFICIENCY,
DRIVERS,
SUPPORT,
DRILLS,
SHOVELS,
C_340SPOTTIME,
C_340LOADTIME,
C_340DIGRATE,
C_340TONSPERHOUR,
C_994SPOTTIME,
C_994LOADTIME,
C_994DIGRATE,
C_994TONSPERHOUR,
ERTRUCKS,
ERLOADERS,
ERDRILL,
ERSHOVELS,
TARGETFORLOADEDTRAVELDELTAC,
TARGETFOREMPTYTRAVELDELTAC,
ID,
CONTENTTYPE,
MODIFIED,
CREATED,
CREATEDBYID,
MODIFIEDBYID,
OWSHIDDENVERSION,
VERSION,
PATH,
getutcdate() UTC_CREATED_DATE     
 FROM CLI.PLAN_VALUES_MONTHLY_TARGET_stg) AS S     
 ON (T.Id = S.Id AND T.SITEFLAG = S.SITEFLAG)     
    
 WHEN MATCHED     
 THEN UPDATE SET     
--T.SITEFLAG = S.SITEFLAG
T.CONTENTTYPEID = S.CONTENTTYPEID
,T.TITLE = S.TITLE
,T.COMPLIANCEASSETID = S.COMPLIANCEASSETID
,T.YEARVALUE = S.YEARVALUE
,T.MONTHVALUE = S.MONTHVALUE
,T.TRUCKAVAILABILITY = S.TRUCKAVAILABILITY
,T.TRUCKUTILIZATION = S.TRUCKUTILIZATION
,T.TRUCKASSETEFFICIENCY = S.TRUCKASSETEFFICIENCY
,T.C_340AVAILABILITY = S.C_340AVAILABILITY
,T.C_340UTILIZATION = S.C_340UTILIZATION
,T.C_340ASSETEFFICIENCY = S.C_340ASSETEFFICIENCY
,T.C_994AVAILABILITY = S.C_994AVAILABILITY
,T.C_994UTILIZATION = S.C_994UTILIZATION
,T.C_994ASSETEFFICIENCY = S.C_994ASSETEFFICIENCY
,T.DRILLAVAILABILITY = S.DRILLAVAILABILITY
,T.DRILLUTILIZATION = S.DRILLUTILIZATION
,T.DRILLASSETEFFICIENCY = S.DRILLASSETEFFICIENCY
,T.SHOVELAVAILABILITY = S.SHOVELAVAILABILITY
,T.SHOVELUTILIZATION = S.SHOVELUTILIZATION
,T.SHOVELASSETEFFICIENCY = S.SHOVELASSETEFFICIENCY
,T.DRIVERS = S.DRIVERS
,T.SUPPORT = S.SUPPORT
,T.DRILLS = S.DRILLS
,T.SHOVELS = S.SHOVELS
,T.C_340SPOTTIME = S.C_340SPOTTIME
,T.C_340LOADTIME = S.C_340LOADTIME
,T.C_340DIGRATE = S.C_340DIGRATE
,T.C_340TONSPERHOUR = S.C_340TONSPERHOUR
,T.C_994SPOTTIME = S.C_994SPOTTIME
,T.C_994LOADTIME = S.C_994LOADTIME
,T.C_994DIGRATE = S.C_994DIGRATE
,T.C_994TONSPERHOUR = S.C_994TONSPERHOUR
,T.ERTRUCKS = S.ERTRUCKS
,T.ERLOADERS = S.ERLOADERS
,T.ERDRILL = S.ERDRILL
,T.ERSHOVELS = S.ERSHOVELS
,T.TARGETFORLOADEDTRAVELDELTAC = S.TARGETFORLOADEDTRAVELDELTAC
,T.TARGETFOREMPTYTRAVELDELTAC = S.TARGETFOREMPTYTRAVELDELTAC
--,T.ID = S.ID
,T.CONTENTTYPE = S.CONTENTTYPE
,T.MODIFIED = S.MODIFIED
,T.CREATED = S.CREATED
,T.CREATEDBYID = S.CREATEDBYID
,T.MODIFIEDBYID = S.MODIFIEDBYID
,T.OWSHIDDENVERSION = S.OWSHIDDENVERSION
,T.VERSION = S.VERSION
,T.PATH = S.PATH
,T.UTC_CREATED_DATE = S.UTC_CREATED_DATE

  
 WHEN NOT MATCHED     
 THEN INSERT (    
 SITEFLAG,   
CONTENTTYPEID,
TITLE,
COMPLIANCEASSETID,
YEARVALUE,
MONTHVALUE,
TRUCKAVAILABILITY,
TRUCKUTILIZATION,
TRUCKASSETEFFICIENCY,
C_340AVAILABILITY,
C_340UTILIZATION,
C_340ASSETEFFICIENCY,
C_994AVAILABILITY,
C_994UTILIZATION,
C_994ASSETEFFICIENCY,
DRILLAVAILABILITY,
DRILLUTILIZATION,
DRILLASSETEFFICIENCY,
SHOVELAVAILABILITY,
SHOVELUTILIZATION