CREATE VIEW [CLI].[CONOPS_CLI_AUTONOMOUS_TRUCK_V] AS



--select * from [CLI].[CONOPS_CLI_AUTONOMOUS_TRUCK_V]
CREATE VIEW [CLI].[CONOPS_CLI_AUTONOMOUS_TRUCK_V]
AS

SELECT DISTINCT
	FieldId AS TruckId,
	0 AS Autonomous
FROM CLI.pit_truck_c WITH(NOLOCK)
WHERE FieldId IS NOT NULL
	AND FieldId <> ''


