
/******************************************************************    
* PROCEDURE : [saf].[UPSERT_CONOPS_PLAN_VALUES]   
* PURPOSE : Upsert [UPSERT_CONOPS_PLAN_VALUES]  
* NOTES     :   
* CREATED : mfahmi  
* SAMPLE    : EXEC saf.[UPSERT_CONOPS_PLAN_VALUES]  
* MODIFIED DATE  AUTHOR    DESCRIPTION    
*------------------------------------------------------------------    
* {01 DEC 2022}  {mfahmi}   {Initial Created}  
* {01 MAR 2023}  {MFAHMI}   {ADD COLUMN SITEFLAG}
* {05 DEC 2023}  {GGOSAL1}  {Add: update table monitoring}
* {01 OCT 2025}  {GGOSAL1}  {Add: Shovel 8}
*******************************************************************/    
CREATE  PROCEDURE [saf].[UPSERT_CONOPS_PLAN_VALUES]  
AS  
BEGIN  
  
MERGE saf.PLAN_VALUES AS T   
USING (SELECT 
'SAF' AS SITEFLAG, 
CONTENTTYPEID,
PLANNAME,
COMPLIANCEASSETID,
DATEEFFECTIVE,
SHIFTINDEX,
TOTALCRUSHERTPD,
S1ORE,
S1WASTE,
S1STK,
S1P,
S2ORE,
S2WASTE,
S2STK,
S2P,
S3ORE,
S3WASTE,
S3STK,
S3P,
S4ORE,
S4WASTE,
S4STK,
S4P,
S5ORE,
S5WASTE,
S5STK,
S5P,
S6ORE,
S6WASTE,
S6STK,
S6P,
S7ORE,
S7WASTE,
S7STK,
S7P,
S8ORE,
S8WASTE,
S8STK,
S8P,
L002ORE,
L002WASTE,
L002STK,
L008ORE,
L008WASTE,
L008STK,
L013ORE,
L013WASTE,
L013STK,
TOTALORETPD,
TOTALORETPDSJ,
TOTALORETPDLS,
TOTALSTKTPD,
TOTALSJSTKTPD,
TOTALLSSTKTPD,
TOTALWASTETPD,
TOTALSJWASTETPD,
TOTALLSWASTETPD,
TOTALMINETPD,
TOTALLSTPD,
TOTALSJTPD,
LOADINGAVAILIBILITY,
LOADINGASSETEFFICIENCY,
TRUCKAVAILIBILITY,
TRUCKASSETEFFICIENCY,
AVGCOUNTREADYTRUCKS,
AVERAGECOUNTREADYTRUCKSSJ,
AVERAGECOUNTREADYTRUCKSLS,
EQUIVALENTFLATHAUL,
TOTALCYCLETIME,
TOTALCYCLETIMESJ,
TOTALCYCLETIMELS,
DELTAC,
TOTALEFH,
EFH_SJ,
EFH_LS,
ELECSHOVELLOADTONSONREADYHOUR,
ELECSHOVELAVAILABILITY,
ELECSHOVELASSETEFFICENCY,
ELECSHOVELUSEOFAVAILIBILITY,
ELECSHOVELAVGREADYNUMBERS,
SPOTING,
LOADING,
LOADEDTRAVEL,
DUMPINGATCRUSHER,
DUMPINGATSTOCKPILE,
EMPTYTRAVEL,
DRILLAE,
DRILLAVAIL,
DRILLUA,
FEETDRILLED,
HOLESDRILLED,
ID,
CONTENTTYPE,
MODIFIED,
CREATED,
CREATEDBYID,
MODIFIEDBYID,
OWSHIDDENVERSION,
VERSION,
PATH,
getutcdate() UTC_CREATED_DATE   
 FROM saf.PLAN_VALUES_stg) AS S   
 ON (T.Id = S.Id AND T.SITEFLAG = S.SITEFLAG)   
  
 WHEN MATCHED   
 THEN UPDATE SET  
 T.CONTENTTYPEID = S.CONTENTTYPEID
,T.PLANNAME = S.PLANNAME
,T.COMPLIANCEASSETID = S.COMPLIANCEASSETID
,T.DATEEFFECTIVE = S.DATEEFFECTIVE
,T.SHIFTINDEX = S.SHIFTINDEX
,T.TOTALCRUSHERTPD = S.TOTALCRUSHERTPD
,T.S1ORE = S.S1ORE
,T.S1WASTE = S.S1WASTE
,T.S1STK = S.S1STK
,T.S1P = S.S1P
,T.S2ORE = S.S2ORE
,T.S2WASTE = S.S2WASTE
,T.S2STK = S.S2STK
,T.S2P = S.S2P
,T.S3ORE = S.S3ORE
,T.S3WASTE = S.S3WASTE
,T.S3STK = S.S3STK
,T.S3P = S.S3P
,T.S4ORE = S.S4ORE
,T.S4WASTE = S.S4WASTE
,T.S4STK = S.S4STK
,T.S4P = S.S4P
,T.S5ORE = S.S5ORE
,T.S5WASTE = S.S5WASTE
,T.S5STK = S.S5STK
,T.S5P = S.S5P
,T.S6ORE = S.S6ORE
,T.S6WASTE = S.S6WASTE
,T.S6STK = S.S6STK
,T.S6P = S.S6P
,T.S7ORE = S.S7ORE
,T.S7WASTE = S.S7WASTE
,T.S7STK = S.S7STK
,T.S7P = S.S7P
,T.S8ORE = S.S8ORE
,T.S8WASTE = S.S8WASTE
,T.S8STK = S.S8STK
,T.S8P = S.S8P
,T.L002ORE = S.L002ORE
,T.L002WASTE = S.L002WASTE
,T.L002STK = S.L002STK
,T.L008ORE = S.L008ORE
,T.L008WASTE = S.L008WASTE
,T.L008STK = S.L008STK
,T.L013ORE = S.L013ORE
,T.L013WASTE = S.L013WASTE
,T.L013STK = S.L013STK
,T.TOTALORETPD = S.TOTALORETPD
,T.TOTALORETPDSJ = S.TOTALORETPDSJ
,T.TOTALORETPDLS = S.TOTALORETPDLS
,T.TOTALSTKTPD = S.TOTALSTKTPD
,T.TOTALSJSTKTPD = S.TOTALSJSTKTPD
,T.TOTALLSSTKTPD = S.TOTALLSSTKTPD
,T.TOTALWASTETPD = S.TOTALWASTETPD
,T.TOTALSJWASTETPD = S.TOTALSJWASTETPD
,T.TOTALLSWASTETPD = S.TOTALLSWASTETPD
,T.TOTALMINETPD = S.TOTALMINETPD
,T.TOTALLSTPD = S.TOTALLSTPD
,T.TOTALSJTPD = S.TOTALSJTPD
,T.LOADINGAVAILIBILITY = S.LOADINGAVAILIBILITY
,T.LOADINGASSETEFFICIENCY = S.LOADINGASSETEFFICIENCY
,T.TRUCKAVAILIBILITY = S.TRUCKAVAILIBILITY
,T.TRUCKASSETEFFICIENCY = S.TRUCKASSETEFFICIENCY
,T.AVGCOUNTREADYTRUCKS =