CREATE VIEW [CLI].[CONOPS_CLI_OPERATOR_EQMT_READY_HOURS_V] AS



--select * from [CLI].[CONOPS_CLI_OPERATOR_EQMT_READY_HOURS_V]
CREATE VIEW [CLI].[CONOPS_CLI_OPERATOR_EQMT_READY_HOURS_V]
AS

WITH OPER_SUM AS(
SELECT
	SITE_CODE,
	SHIFTINDEX AS SHIFTINDEX_ORI,
	CASE WHEN LOGINTIME > 38700 
		THEN SHIFTINDEX + 1
		ELSE SHIFTINDEX
	END AS SHIFTINDEX,
	UNIT,
	EQMTID,
	LOGINTIME,
	OPERID,
	NAME AS OPERNAME,
	TMCAT01,
	TMCAT02
FROM dbo.LH_OPER_TOTAL_SUM WITH(NOLOCK)
WHERE SITE_CODE = 'CLI'
	AND OPERID IS NOT NULL
	AND OPERID <> 000000
)

SELECT
	SITE_CODE,
	SHIFTINDEX,
	EQMTID AS EQMT,
	UNIT,
	OPERID AS OperatorId,
	OPERNAME AS OperatorName,
	SUM(TMCAT01 + TMCAT02) AS ReadyTime,
	SUM(TMCAT01 + TMCAT02) / 3600.0 AS ReadyHours
FROM OPER_SUM
GROUP BY 
	SITE_CODE,
	SHIFTINDEX,
	EQMTID,
	UNIT,
	OPERID,
	OPERNAME


