CREATE TABLE [CHI].[PLAN_VALUES] (
    [SITEFLAG] varchar(5) NOT NULL,
    [PlanName] varchar(50) NULL,
    [DateEffective] date NULL,
    [OreTPD] decimal(28,5) NULL,
    [ROMTPD] decimal(28,5) NULL,
    [WasteTPD] decimal(28,5) NULL,
    [TotalExPitTPD] decimal(28,5) NULL,
    [TotalMaterialtoCrusher] decimal(28,5) NULL,
    [OreRehandletoCrusherTPD] decimal(28,5) NULL,
    [EstrellaTPD] decimal(28,5) NULL,
    [HanoverTPD] decimal(28,5) NULL,
    [SouthPitTPD] decimal(28,5) NULL,
    [C_35TPD] decimal(28,5) NULL,
    [C_12TPD] decimal(28,5) NULL,
    [C_44TPD] decimal(28,5) NULL,
    [C_46TPD] decimal(28,5) NULL,
    [ElectricShovelAvailability] decimal(28,5) NULL,
    [ElectricShovelUofA] decimal(28,5) NULL,
    [ElectricShovelAssetEfficiency] decimal(28,5) NULL,
    [TruckAvailability] decimal(28,5) NULL,
    [TruckUofA] decimal(28,5) NULL,
    [TruckAssetEfficiency] decimal(28,5) NULL,
    [AvgReadyTrucks] decimal(28,5) NULL,
    [PlannedTruckFleet] decimal(28,5) NULL,
    [DeltaC] decimal(28,5) NULL,
    [EFH] decimal(28,5) NULL,
    [PlannedEmptyTravelTimeMin] decimal(28,5) NULL,
    [PlannedLoadedTravelTimeMin] decimal(28,5) NULL,
    [PlannedDumpTimeMin] decimal(28,5) NULL,
    [PlannedWaitTimeMin] decimal(28,5) NULL,
    [PlannedLoadTimePH2800Min] decimal(28,5) NULL,
    [PlannedLoadTimePH4100Min] decimal(28,5) NULL,
    [PlannedSpotTimeMin] decimal(28,5) NULL,
    [AveragePayload] decimal(28,5) NULL,
    [TotalCycleTimeMin] decimal(28,5) NULL,
    [AvgReadyElecShovels] decimal(28,5) NULL,
    [FeetDrilledDay] decimal(28,5) NULL,
    [ContentTypeID] varchar(100) NULL,
    [ComplianceAssetId] varchar(100) NULL,
    [ColorTag] varchar(100) NULL,
    [HolesDrilledDay] decimal(28,5) NULL,
    [DrillAvailability] decimal(28,5) NULL,
    [DrillUtilization] decimal(28,5) NULL,
    [DrillAssetEfficiency] varchar(50) NULL,
    [AvgReadyDrills] decimal(28,5) NULL,
    [ID] int NOT NULL,
    [ContentType] varchar(50) NOT NULL,
    [Modified] datetime NOT NULL,
    [Created] datetime NOT NULL,
    [CreatedById] int NOT NULL,
    [ModifiedById] int NOT NULL,
    [Owshiddenversion] int NOT NULL,
    [Version] decimal(10,5) NOT NULL,
    [Path] varchar(2000) NOT NULL,
    [UTC_CREATED_DATE] datetime NOT NULL
);