CREATE TYPE [dbo].[LOAD_HAUL__LH_BUCKET_IMO] AS TABLE (
    [BUCKET_ID] numeric(19,0) NOT NULL,
    [SITE_CODE] varchar(4) NOT NULL,
    [LOADING_CYCLE_ID] numeric(19,0) NULL,
    [LH_EQUIP_ID] numeric(38,5) NULL,
    [ORIG_SRC_ID] numeric(38,0) NULL,
    [BUCKET_OF_CYCLE] numeric(38,0) NULL,
    [SWING_EMPTY_START_TS_UTC] datetime2 NULL,
    [SWING_EMPTY_START_TS_LOCAL] datetime2 NULL,
    [SWING_EMPTY_END_TS_UTC] datetime2 NULL,
    [SWING_EMPTY_END_TS_LOCAL] datetime2 NULL,
    [DIG_START_TS_UTC] datetime2 NULL,
    [DIG_START_TS_LOCAL] datetime2 NULL,
    [DIG_END_TS_UTC] datetime2 NULL,
    [DIG_END_TS_LOCAL] datetime2 NULL,
    [SWING_FULL_START_TS_UTC] datetime2 NULL,
    [SWING_FULL_START_TS_LOCAL] datetime2 NULL,
    [SWING_FULL_END_TS_UTC] datetime2 NULL,
    [SWING_FULL_END_TS_LOCAL] datetime2 NULL,
    [TRIP_TS_UTC] datetime2 NULL,
    [TRIP_TS_LOCAL] datetime2 NULL,
    [DIG_X] float NULL,
    [DIG_Y] float NULL,
    [DIG_Z] float NULL,
    [TRIP_X] float NULL,
    [TRIP_Y] float NULL,
    [TRIP_Z] float NULL,
    [SWING_ANGLE_DEGREES] float NULL,
    [BLOCK_CENTROID_X] float NULL,
    [BLOCK_CENTROID_Y] float NULL,
    [BLOCK_CENTROID_Z] float NULL,
    [MEASURED_SHORT_TONS] numeric(38,6) NULL,
    [MEASURED_METRIC_TONS] numeric(38,6) NULL,
    [SWING_EMPTY_DURATION_MINS] numeric(38,6) NULL,
    [DIG_DURATION_MINS] numeric(38,6) NULL,
    [SWING_FULL_DURATION_MINS] numeric(38,6) NULL,
    [SYSTEM_VERSION] varchar(50) NULL,
    [DW_LOGICAL_DELETE_FLAG] varchar(1) NULL,
    [DW_LOAD_TS] datetime2 NULL,
    [DW_MODIFY_TS] datetime2 NULL
);