CREATE VIEW [dbo].[OPERATOR_CONSECUTIVE_WORKDAYS] AS

--SELECT * FROM dbo.OPERATOR_CONSECUTIVE_WORKDAYS
CREATE VIEW dbo.OPERATOR_CONSECUTIVE_WORKDAYS
AS

SELECT *
FROM dbo.OPERATOR_CONSECUTIVE_WORKDAYS_2 WITH(NOLOCK)

