CREATE VIEW [MOR].[CONOPS_MOR_DB_AUTO_DRILL_V] AS


--SELECT * FROM MOR.CONOPS_MOR_DB_AUTO_DRILL_V
CREATE VIEW [MOR].[CONOPS_MOR_DB_AUTO_DRILL_V]
AS

WITH AutoDrillHolesSUM AS(
SELECT
	SITE_CODE,
	SHIFT_DATE,
	SHIFT,
	RIG_NAME AS DrillID,
	SUM(AUTO_DRILLED_HOLES) AS NrOfAutoDrill
FROM SNOWFLAKE_WG.dbo.RCS_OPERATOR_AUTODRILLING_V
GROUP BY SITE_CODE, SHIFT_DATE, SHIFT, RIG_NAME
)

SELECT
	s.shiftid,
	--s.ShiftIndex,
	d.DrillID,
	NrOfAutoDrill,
	siv.shiftflag
FROM MOR.SHIFT_INFO s
RIGHT JOIN AutoDrillHolesSUM d
	ON s.ShiftStartDate = d.SHIFT_DATE
	AND s.FullShiftSuffix = d.SHIFT
LEFT JOIN MOR.CONOPS_MOR_SHIFT_INFO_V siv
	ON s.shiftid = siv.shiftid

