CREATE VIEW [MOR].[CONOPS_MOR_DB_PLAN_ACHIEVEMENT_V] AS

--SELECT * FROM MOR.CONOPS_MOR_DB_PLAN_ACHIEVEMENT_V
CREATE VIEW MOR.CONOPS_MOR_DB_PLAN_ACHIEVEMENT_V
AS

WITH base AS (
SELECT
	CAST(BLAST_DATE AS DATE) AS BLAST_DATE_D,
	-- Anchor on 1900-01-01 (Monday) and step back to that week's Monday
	DATEADD(
		DAY,
		- (DATEDIFF(DAY, '19000101', CAST(BLAST_DATE AS DATE)) % 7),
		CAST(BLAST_DATE AS DATE)
	) AS WEEK_START_DATE,
	ACTUAL_HOLE_COUNT,
	PATTERN_PLANNED_HOLE_COUNT,
	BLAST_DATE_COMPLIANCE
FROM MOR.CONOPS_MOR_DB_BLAST_FACT_V
),

agg AS (
SELECT
	WEEK_START_DATE,
	
	-- Pattern compliance: ratio >= 0.95 across all rows in the week
	CAST(SUM(
		CASE
			WHEN PATTERN_PLANNED_HOLE_COUNT IS NOT NULL
				 AND CAST(ACTUAL_HOLE_COUNT AS DECIMAL(18,6))
					 / NULLIF(CAST(PATTERN_PLANNED_HOLE_COUNT AS DECIMAL(18,6)), 0) >= 0.95
			THEN 1
			ELSE 0
		END
	) AS FLOAT) / NULLIF(COUNT(*), 0) AS PATTERN_COMPLIANCE_PCT,

	-- Blast date compliance: average of the flag across the week
	CAST(SUM(CAST(BLAST_DATE_COMPLIANCE AS FLOAT)) AS FLOAT) 
		/ NULLIF(COUNT(*), 0) AS BLAST_DATE_COMPLIANCE_PCT
FROM base
GROUP BY WEEK_START_DATE
)

SELECT
	WEEK_START_DATE,
	BLAST_DATE_COMPLIANCE_PCT * 100 AS BLAST_DATE_COMPLIANCE_PCT,
	PATTERN_COMPLIANCE_PCT * 100 AS PATTERN_COMPLIANCE_PCT
FROM agg
--ORDER BY WEEK_START_DATE;


