CREATE VIEW [MOR].[CONOPS_MOR_DB_BLAST_FACT_V] AS

--SELECT * FROM MOR.CONOPS_MOR_DB_BLAST_FACT
CREATE VIEW MOR.CONOPS_MOR_DB_BLAST_FACT_V
AS

WITH hole_rows AS(
SELECT
	dc.PATTERN_NAME
FROM SNOWFLAKE_WG.dbo.DRILL_CYCLE dc WITH(NOLOCK)
LEFT OUTER JOIN SNOWFLAKE_WG.dbo.DRILL_PLAN dp WITH(NOLOCK)
	ON dc.DRILL_PLAN_SK = dp.DRILL_PLAN_SK
WHERE dc.SITE_CODE = 'MOR'
)

SELECT 
	A.ID
	,A.NAME
	,A.STATUS
	,CAST(A.FIREDTIME AS DATE) AS BLAST_DATE
	,A.HOLECOUNT AS ACTUAL_HOLE_COUNT
	,CAST(B.PLANNEDDATE AS DATE) AS PLANNED_BLAST_DATE
	,CASE 
		WHEN CAST(A.FIREDTIME AS DATE) = CAST(B.PLANNEDDATE AS DATE)
			THEN 1
		ELSE 0
		END AS BLAST_DATE_COMPLIANCE
	,A.VOLUME
	,(A.VOLUME * 35.3146667 * 165) / 2000 AS TONS_PER_SHOT
	,COUNT(*) AS pattern_planned_hole_count
FROM SNOWFLAKE_WG.dbo.BL_DW_BLAST A WITH(NOLOCK)
LEFT JOIN SNOWFLAKE_WG.dbo.BL_DW_BLASTPROPERTYVALUE B WITH(NOLOCK)
	ON A.ID = B.BLASTID
LEFT JOIN hole_rows
    ON A.NAME = hole_rows.PATTERN_NAME
GROUP BY A.ID
	,A.NAME
	,A.STATUS
	,CAST(A.FIREDTIME AS DATE)
	,A.HOLECOUNT
	,CAST(B.PLANNEDDATE AS DATE)
	,A.VOLUME;


