CREATE VIEW [MOR].[CONOPS_MOR_CM_HOURLY_INTERMEDIATE_STOCKPILE_V] AS




  
  
--SELECT * FROM [mor].[CONOPS_MOR_CM_HOURLY_INTERMEDIATE_STOCKPILE_V] WITH (NOLOCK) WHERE SHIFTFLAG = 'CURR'    
CREATE VIEW [mor].[CONOPS_MOR_CM_HOURLY_INTERMEDIATE_STOCKPILE_V]
AS    


WITH CTE AS (
SELECT 
	shiftindex,
	CRUSHERLOC,
	COMPONENT,
	SENSORVALUE,
	CASE WHEN DATEPART(MINUTE,VALUE_TS) BETWEEN 0 AND 5 THEN VALUE_TS END AS TimeInHour
FROM [dbo].[IOS_STOCKPILE_LEVELS] WITH (NOLOCK)
WHERE SITEFLAG = 'MOR'
),

MFLStockpile AS(
SELECT
	SHIFTINDEX,
	SENSORVALUE AS MFLStockpile,
	TimeInHour
FROM CTE
WHERE CRUSHERLOC = 'Crusher 2' 
	AND COMPONENT = 'CrusherStockpile'
),

MillStockpile AS(
SELECT
	SHIFTINDEX,
	SENSORVALUE AS MillStockpile,
	TimeInHour
FROM CTE
WHERE CRUSHERLOC = '' 
	AND COMPONENT = ''
)


SELECT 
a.[SITEFLAG]
,a.[SHIFTFLAG]
,m.[MFLStockpile]
,0 AS [MillStockpile]
,CAST(CONCAT(FORMAT([m].TimeInHour, 'yyyy-MM-dd HH'), ':15:00') AS Datetime) AS TimeInHour
FROM [MOR].[CONOPS_MOR_SHIFT_INFO_V] a WITH (NOLOCK)
LEFT JOIN MFLStockpile [m] WITH (NOLOCK) 
	ON a.SHIFTINDEX = [m].SHIFTINDEX 
WHERE m.TimeInHour IS NOT NULL


  




