CREATE TABLE [BAG].[FLEET_EQUIPMENT_HOURLY_STATUS_STG] (
    [SHIFTINDEX] int NULL,
    [SHIFTID] varchar(64) NULL,
    [SHIFTDATE] date NULL,
    [SITE_CODE] varchar(5) NULL,
    [EQMT] varchar(50) NULL,
    [UNIT] int NULL,
    [HOS] int NULL,
    [START_TIME_TS] datetime2 NULL,
    [END_TIME_TS] datetime2 NULL,
    [DURATION] int NULL,
    [REASON] int NULL,
    [STATUS] int NULL,
    [CATEGORY] int NULL,
    [COMMENTS] varchar(90) NULL,
    [LOC] varchar(256) NULL,
    [PRIMARYOPERATOR_ID] varchar(254) NULL,
    [SECONDARYOPERATOR_ID] varchar(254) NULL,
    [UTC_CREATED_DATE] datetime NULL
);