CREATE VIEW [cer].[CONOPS_CER_DB_DRILL_SCORE_TARGET_V] AS

  
  
  
--select * from [cer].[CONOPS_CER_DB_DRILL_SCORE_TARGET_V] where shiftflag = 'curr'  
CREATE VIEW [cer].[CONOPS_CER_DB_DRILL_SCORE_TARGET_V]  
AS  
  
SELECT CAST(Right([Year], 2) + FORMAT(CAST([Month] AS numeric), '00') AS numeric) [ShiftId],  
    'CER' AS [siteflag],  
    [DRILLAVAILABILITY] * 100 AS [DRILLAVAILABILITY],  
    [DRILLASSETEFFICIENCY] * 100 AS [DRILLASSETEFFICIENCY],  
    [DRILLUTILIZATION] * 100 AS [DRILLUTILIZATION],  
    2372 AS TARGETFEETDRILLED,  
    153 AS TARGETHOLESDRILLED  
FROM (  
 SELECT REVERSE(PARSENAME(REPLACE(REVERSE(CAST([TITLE] AS date)), '-', '.'), 1)) AS [Year],  
     REVERSE(PARSENAME(REPLACE(REVERSE(CAST([TITLE] AS date)), '-', '.'), 2)) AS [Month],  
     REVERSE(PARSENAME(REPLACE(REVERSE(CAST([TITLE] AS date)), '-', '.'), 3)) AS [Day],  
     CASE WHEN ([PVDISPPRCTG] IS NOT NULL OR CAST([PVDISPPRCTG] AS decimal(3,2)) != 0) AND   
            ([RL8DISPPRCTG] IS NOT NULL OR CAST([RL8DISPPRCTG] AS decimal(3,2)) != 0)  
     THEN (CAST([PVDISPPRCTG] AS decimal(3,2)) + CAST([RL8DISPPRCTG] AS decimal(3,2))) / 2.0  
    WHEN ([PVDISPPRCTG] IS NOT NULL OR CAST([PVDISPPRCTG] AS decimal(3,2)) != 0)  
      THEN CAST([PVDISPPRCTG] AS decimal(3,2))  
    WHEN ([RL8DISPPRCTG] IS NOT NULL OR CAST([RL8DISPPRCTG] AS decimal(3,2)) != 0)  
      THEN CAST([RL8DISPPRCTG] AS decimal(3,2))  
    ELSE 0  
     END AS [DRILLAVAILABILITY],  
     CASE WHEN ([PVASSETEFFPRCTG] IS NOT NULL OR CAST([PVASSETEFFPRCTG] AS decimal(3,2)) != 0) AND   
            ([RL8ASSETEFFECTPRCTG] IS NOT NULL OR CAST([RL8ASSETEFFECTPRCTG] AS decimal(3,2)) != 0)  
     THEN (CAST([PVASSETEFFPRCTG] AS decimal(3,2)) + CAST([RL8ASSETEFFECTPRCTG] AS decimal(3,2))) / 2.0  
    WHEN ([PVASSETEFFPRCTG] IS NOT NULL OR CAST([PVASSETEFFPRCTG] AS decimal(3,2)) != 0)  
      THEN CAST([PVASSETEFFPRCTG] AS decimal(3,2))  
    WHEN ([RL8ASSETEFFECTPRCTG] IS NOT NULL OR CAST([RL8ASSETEFFECTPRCTG] AS decimal(3,2)) != 0)  
      THEN CAST([RL8ASSETEFFECTPRCTG] AS decimal(3,2))  
    ELSE 0  
     END AS [DRILLASSETEFFICIENCY],  
     CASE WHEN ([PVUTILPRCTG] IS NOT NULL OR CAST([PVUTILPRCTG] AS decimal(3,2)) != 0) AND   
            ([RL8UTILPRCTG] IS NOT NULL OR  CAST([RL8UTILPRCTG] AS decimal(3,2)) != 0)  
     THEN (CAST([PVUTILPRCTG] AS decimal(3,2)) + CAST([RL8UTILPRCTG] AS decimal(3,2))) / 2.0  
    WHEN ([PVUTILPRCTG] IS NOT NULL OR CAST([PVUTILPRCTG] AS decimal(3,2)) != 0)  
      THEN CAST([PVUTILPRCTG] AS decimal(3,2))  
    WHEN ([RL8UTILPRCTG] IS NOT NULL OR CAST([RL8UTILPRCTG] AS decimal(3,2)) != 0)  
      THEN CAST([RL8UTILPRCTG] AS decimal(3,2))  
    ELSE 0  
     END AS [DRILLUTILIZATION]  
    FROM [cer].[PLAN_VALUES] (NOLOCK)  
) [target]  
  
