CREATE VIEW [cer].[CONOPS_CER_EOS_IOS_STOCKPILE_HOURLY_V] AS








--SELECT * FROM [CER].[CONOPS_CER_EOS_IOS_STOCKPILE_HOURLY_V] WHERE shiftflag = 'PREV'
CREATE VIEW [cer].[CONOPS_CER_EOS_IOS_STOCKPILE_HOURLY_V]
AS

WITH CTE AS(
SELECT
	a.SITEFLAG,
	s.shiftflag,
	s.SHIFTINDEX,
	CASE a.CRUSHERLOC
		WHEN 'C1 MILLCHAN' THEN 'MILLCHAN'
		WHEN 'MILLCRUSH 1' THEN 'MILLCRUSH1'
		WHEN 'MILLCRUSH 2' THEN 'MILLCRUSH2'
		ELSE a.CRUSHERLOC END AS CRUSHERLOC,
	a.COMPONENT,
	a.VALUE_TS,
	CAST(CONCAT(FORMAT(a.VALUE_TS, 'yyyy-MM-dd HH'), FORMAT(SHIFTSTARTDATETIME, ':mm:00')) AS Datetime) AS DateTime,
	a.SENSORVALUE
FROM dbo.IOS_STOCKPILE_LEVELS a WITH (NOLOCK)  
LEFT JOIN [CER].[CONOPS_CER_SHIFT_INFO_V] s WITH (NOLOCK)  
	ON a.SITEFLAG = s.siteflag
WHERE a.siteflag = 'CER'
AND DATEADD(MINUTE, DATEDIFF(MINUTE, 0, a.VALUE_TS), 0) BETWEEN SHIFTSTARTDATETIME AND SHIFTENDDATETIME
AND CAST(FORMAT(a.VALUE_TS, 'mm') AS INT) - CAST(FORMAT(SHIFTSTARTDATETIME, 'mm') AS INT) BETWEEN 0 AND 5
AND CRUSHERLOC <> 'HIDROCHAN'
--AND DATEPART(MINUTE,VALUE_TS) = '30'
)

SELECT 
	SITEFLAG,
	shiftflag,
	SHIFTINDEX,
	CRUSHERLOC,
	"DateTime",
	RANK() OVER (PARTITION BY shiftflag, CRUSHERLOC ORDER BY "DateTime" ASC) AS shiftseq,
	CrusherStockpile,
	CrusherStockpileTons
FROM CTE
PIVOT  
(AVG([SENSORVALUE]) FOR [COMPONENT]  IN (CrusherStockpile, CrusherStockpileTons)) AS PivotTable




