CREATE VIEW [BAG].[CONOPS_BAG_TRUCK_SHOP_LOCATION_V] AS

-- SELECT * FROM [bag].[CONOPS_BAG_TRUCK_SHOP_LOCATION_V] WITH (NOLOCK)
CREATE VIEW [bag].[CONOPS_BAG_TRUCK_SHOP_LOCATION_V]
AS

Select
L.NAME COLLATE SQL_Latin1_General_CP1_CI_AS AS Name
from 
BAG_MSMODEL.dbo.LOCATION L WITH (NOLOCK)
WHERE L.NAME LIKE '%TRUCKSHOP%'