CREATE VIEW [BAG].[CONOPS_BAG_OPERATOR_EQMT_READY_HOURS_V] AS

--select * from [BAG].[CONOPS_BAG_OPERATOR_EQMT_READY_HOURS_V]
CREATE VIEW [BAG].[CONOPS_BAG_OPERATOR_EQMT_READY_HOURS_V]
AS

WITH OPER_SUM AS(
SELECT DISTINCT
	SHIFTID,
	MACHINE_CATEGORY AS UNIT,
	MACHINE_NAME AS EQMTID,
	LOGIN_TIME AS LOGINTIME,
	OPERATOR_ID AS OPERID,
	OPERATOR_NAME AS OPERNAME
FROM BAG.FLEET_OPERATOR_SHIFT_V
),

EqStatus AS(
SELECT 
	SHIFTINDEX,
	EQMT,
	UNIT,
	OPERID,
	SUM(DURATION) AS ReadyTimes,
	SUM(DURATION) / 3600.0 AS ReadyHours
FROM bag.EQUIPMENT_HOURLY_STATUS WITH(NOLOCK)
WHERE CATEGORY IN (1,2)
GROUP BY 
	SHIFTINDEX,
	EQMT,
	UNIT,
	OPERID
)

SELECT DISTINCT
	s.SITEFLAG AS SITE_CODE,
	s.SHIFTINDEX,
	a.EQMTID AS EQMT,
	'Haul Truck' AS UNIT,
	a.OPERID AS OperatorId,
	a.OPERNAME AS OperatorName,
	SUM(ReadyTimes) AS ReadyTimes,
	SUM(ReadyHours) AS ReadyHours
FROM BAG.CONOPS_BAG_SHIFT_INFO_V s
LEFT JOIN OPER_SUM a
	ON s.shiftid = a.shiftid
LEFT JOIN EqStatus b
	ON s.SHIFTINDEX = b.SHIFTINDEX
	AND a.EQMTID = b.EQMT
	AND a.OPERID = b.OPERID
WHERE a.UNIT = 'Truck Classes'
GROUP BY
	s.SITEFLAG,
	s.SHIFTINDEX,
	a.EQMTID,
	a.UNIT,
	a.OPERID,
	a.OPERNAME





