CREATE VIEW [BAG].[CONOPS_BAG_EQMT_SHOVEL_HOURLY_PAYLOAD_V] AS

--SELECT * FROM [bag].[CONOPS_BAG_EQMT_SHOVEL_HOURLY_PAYLOAD_V] WHERE shiftflag = 'prev'
CREATE VIEW [bag].[CONOPS_BAG_EQMT_SHOVEL_HOURLY_PAYLOAD_V]
AS

WITH CTE AS (
SELECT
	SITE_CODE,
	SHIFT_ID AS SHIFTID,
	SHOVEL_NAME AS EQUIPMENT,
	LOAD_HOS-1 AS HOS,
	COALESCE(AVG(MEASURED_PAYLOAD_SHORT_TONS),0) AS PAYLOAD
FROM BAG.FLEET_SHOVEL_CYCLE_V
WHERE PayloadFilter = 1
GROUP BY SITE_CODE, SHIFT_ID, SHOVEL_NAME, LOAD_HOS
)

SELECT
	siteflag,
	shiftflag,
	Equipment,
	AVG(PAYLOAD) Payload,
	dateadd(hour,HOS,ShiftStartDateTime) as TimeinHour
FROM [bag].[CONOPS_BAG_SHIFT_INFO_V] a
LEFT JOIN CTE b
	ON a.SHIFTID = b.SHIFTID
GROUP BY siteflag, shiftflag, Equipment, HOS, ShiftStartDateTime

