CREATE VIEW [BAG].[CONOPS_BAG_DB_DRILL_ASSET_EFFICIENCY_TARGET_V] AS

  
--select * from [bag].[CONOPS_BAG_DB_DRILL_ASSET_EFFICIENCY_TARGET_V] where shiftflag = 'curr'  
CREATE VIEW [bag].[CONOPS_BAG_DB_DRILL_ASSET_EFFICIENCY_TARGET_V]  
AS  
  
SELECT CAST(Right([Year], 2) + FORMAT(CAST([Month] AS numeric), '00') AS numeric) [ShiftId],  
    'BAG' [siteflag],  
    [DRILLAVAILABILITY],  
    [DRILLASSETEFFICIENCY],  
    [DRILLUTILIZATION]  
FROM (  
 SELECT REVERSE(PARSENAME(REPLACE(REVERSE([EFFECTIVEDATE]), '-', '.'), 1)) AS [Year],  
     REVERSE(PARSENAME(REPLACE(REVERSE([EFFECTIVEDATE]), '-', '.'), 2)) AS [Month],  
     REVERSE(PARSENAME(REPLACE(REVERSE([EFFECTIVEDATE]), '-', '.'), 3)) AS [Day],  
     [DRILLAVAILABILITY],  
     [DRILLASSETEFFICIENCY], 
	 CASE WHEN [DRILLAVAILABILITY] = 0 
		THEN 0
		ELSE ([DRILLASSETEFFICIENCY] / [DRILLAVAILABILITY]) * 100 END AS [DRILLUTILIZATION]  
    FROM [bag].[PLAN_VALUES_PROD_SUM] (NOLOCK)  
) [target]  
  


