CREATE VIEW [BAG].[FLEET_EQUIPMENT_HOURLY_STATUS_V] AS



--SELECT * FROM [bag].[FLEET_EQUIPMENT_HOURLY_STATUS_V]
CREATE VIEW [BAG].[FLEET_EQUIPMENT_HOURLY_STATUS_V]
AS

SELECT
	(CONVERT(INT, (DATEDIFF(DD, '7/12/2007', SHIFT_DATE)*2) + 27412 + (SELECT RIGHT([SHIFT_ID],1) - 1))) AS SHIFTINDEX,
	SHIFT_ID COLLATE SQL_Latin1_General_CP1_CI_AS AS SHIFTID,
	SHIFT_DATE AS SHIFTDATE,
	SITE_CODE COLLATE SQL_Latin1_General_CP1_CI_AS AS SITE_CODE,
	EQUIP_NAME COLLATE SQL_Latin1_General_CP1_CI_AS AS EQMT,
	CASE WHEN MACHINE_CATEGORY = 'Truck Classes' THEN 1
		WHEN MACHINE_CATEGORY IN ('Shovel Classes', 'Loader Classes') THEN 2
		WHEN MACHINE_CATEGORY = 'Dozer Unit' THEN 13
		WHEN MACHINE_CATEGORY = 'Track Drill' THEN 12
		WHEN MACHINE_CATEGORY = 'Grader Unit' THEN 14
		WHEN MACHINE_CATEGORY = 'Wheel Dozer Classes' THEN 15
		WHEN MACHINE_CATEGORY = 'Water Truck Classes' THEN 18
		WHEN MACHINE_CATEGORY = 'Grader Drill' THEN 14
		WHEN MACHINE_CATEGORY = 'Lowboy Classes' THEN 21
		WHEN MACHINE_CATEGORY = 'Dump Truck Classes' THEN 28
		WHEN MACHINE_CATEGORY IN ('Excavator Classes','Backhoe Classes') THEN 24
		WHEN MACHINE_CATEGORY = 'Compactor Classes' THEN 33
		ELSE NULL END AS UNIT,
	MACHINE_CATEGORY,
	DATEDIFF(HH, SHIFTSTARTTIMEUTC, START_TIME_UTC) AS HOS,
	DATEADD(HOUR, -7, START_TIME_UTC) AS START_TIME_TS,
	DATEADD(HOUR, -7, END_TIME_UTC) END_TIME_TS,
	DURATION,
	REASON_CODE AS REASON,
	STATUS_CODE STATUS,
	CATEGORY_CODE AS CATEGORY,
	NULL AS COMMENTS,
	LOCATION_NAME COLLATE SQL_Latin1_General_CP1_CI_AS AS LOC,
	PRIMARYOPERATOR_ID,
	SECONDARYOPERATOR_ID
FROM ConnectedOperations.bag2.Msmodel_Equipment_Current_Status eq
WHERE START_TIME_UTC <> END_TIME_UTC
AND EQUIP_NAME IS NOT NULL



