CREATE TABLE [sie].[PIT_LOC_C] (
    [siteflag] varchar(5) NOT NULL,
    [SHIFTINDEX] numeric(38,0) NOT NULL,
    [SHIFTID] decimal(9,0) NOT NULL,
    [DbPrevious] decimal(19,0) NULL,
    [DbNext] decimal(19,0) NULL,
    [DbVersion] int NULL,
    [Id] decimal(19,0) NOT NULL,
    [DbName] varchar(32) NULL,
    [DbKey] decimal(19,0) NULL,
    [FieldId] varchar(24) NULL,
    [FieldPit] decimal(19,0) NULL,
    [FieldRegion] decimal(19,0) NULL,
    [FieldBlendrec] decimal(19,0) NULL,
    [FieldPath] decimal(19,0) NULL,
    [FieldBean] decimal(19,0) NULL,
    [FieldInvbean] decimal(19,0) NULL,
    [FieldHaul] decimal(19,0) NULL,
    [FieldOre] decimal(19,0) NULL,
    [FieldDumpfeed] decimal(19,0) NULL,
    [FieldDumpcapy] decimal(19,0) NULL,
    [FieldBinsize] decimal(19,0) NULL,
    [FieldXloc] int NULL,
    [FieldYloc] int NULL,
    [FieldPathix] int NULL,
    [FieldTimedump] int NULL,
    [FieldZloc] decimal(19,0) NULL,
    [FieldSignid] int NULL,
    [FieldUnit] decimal(19,0) NULL,
    [FieldLoad] decimal(19,0) NULL,
    [FieldIstiedown] int NULL,
    [FieldStatus] decimal(19,0) NULL,
    [FieldLinestat] decimal(19,0) NULL,
    [FieldSpillage] int NULL,
    [FieldSignpost] int NULL,
    [FieldShoptype] decimal(19,0) NULL,
    [FieldDumpqueue] int NULL,
    [FieldPctcapy] int NULL,
    [FieldBays] int NULL,
    [FieldNopenalty] int NULL,
    [FieldTimelast] int NULL,
    [FieldRadius] int NULL,
    [FieldGpstype] decimal(19,0) NULL,
    [FieldReason] int NULL,
    [FieldIvtrec] decimal(19,0) NULL,
    [FieldTdset] int NULL,
    [FieldPrior] int NULL,
    [FieldAvailbays] int NULL,
    [FieldParkqueue] int NULL,
    [FieldLaststattime] int NULL,
    [FieldBcntime] int NULL,
    [FieldTagdate] decimal(19,0) NULL,
    [FieldTageqmt] varchar(10) NULL,
    [FieldTrucksenroute] int NULL,
    [FieldLastassign] decimal(19,0) NULL,
    [FieldLastarrive] decimal(19,0) NULL,
    [FieldSpeedtrap] int NULL,
    [FieldLvsproxcnt] int NULL,
    [FieldIgnunexarr] int NULL,
    [FieldMetadata] varchar(20) NULL,
    [FieldDisablearrchk] int NULL,
    [FieldIntf_data1] varchar(50) NULL,
    [FieldIntf_data2] varchar(50) NULL,
    [FieldIntf_data3] varchar(50) NULL,
    [UTC_CREATED_DATE] datetime NOT NULL,
    [UTC_LOGICAL_DELETED_DATE] datetime NULL
);