CREATE TABLE [sie].[SHIFT_EQMT_STG] (
    [DBPREVIOUS] decimal(19,0) NULL,
    [DBNEXT] decimal(19,0) NULL,
    [DBVERSION] int NULL,
    [SHIFTID] int NOT NULL,
    [ID] decimal(19,0) NOT NULL,
    [DBNAME] varchar(32) NOT NULL,
    [DBKEY] decimal(19,0) NOT NULL,
    [FIELDID] varchar(12) NULL,
    [FIELDPIT] decimal(19,0) NULL,
    [FIELDREGIONLOCK] decimal(19,0) NULL,
    [FIELDSIZE] decimal(19,0) NULL,
    [FIELDTMPH] decimal(19,0) NULL,
    [FIELDREASON] smallint NULL,
    [FIELDUNIT] decimal(19,0) NULL,
    [FIELDSTATUS] decimal(19,0) NULL,
    [FIELDEXTRALOAD] int NULL,
    [FIELDNOASSIGN] int NULL,
    [FIELDLOADSTART] decimal(19,0) NULL,
    [FIELDEQMTTYPE] decimal(19,0) NULL,
    [FIELDCOMMENT] varchar(90) NULL,
    [FIELDREASONREC] decimal(19,0) NULL,
    [FIELDOPER] decimal(19,0) NULL,
    [FIELDAUDIT] decimal(19,0) NULL,
    [FIELDSUBCODE] int NULL,
    [FIELDSUBCODE2] int NULL,
    [FIELDSITUATION] varchar(20) NULL,
    [FIELDUSER] int NULL,
    [FIELDMAINTSTART] decimal(19,0) NULL,
    [FIELDMAINTPROPOSE] decimal(19,0) NULL,
    [FIELDWARRANTY] int NULL,
    [FIELDENGHR] decimal(19,0) NULL,
    [FIELDENGHR2] decimal(19,0) NULL,
    [FIELDENGHRTIME] decimal(19,0) NULL,
    [FIELDENGHRTIME2] decimal(19,0) NULL,
    [FIELDISAUXIL] int NULL,
    [FIELDPMID] varchar(30) NULL,
    [CHANGE_TYPE] varchar(1) NOT NULL,
    [CHANGE_ID] decimal(19,0) NOT NULL,
    [UTC_CREATED_DATE] datetime NOT NULL,
    [UTC_LOGICAL_DELETED_DATE] datetime NULL
);