
-- ==================================================================================
-- Author:        David Purba
-- Create date:   2025-11-17
-- Description:   Returns a hardcoded dummy CO alert item
--                for a given SiteCode. No table access yet.
-- ==================================================================================
CREATE   PROCEDURE [dbo].[MyAction_Alerts_Get]
(
    @SITE varchar(4)
)
AS
BEGIN
BEGIN TRY

    SET NOCOUNT ON;

    SELECT
        CAST(NULL AS int)              AS ItemID,
        'CO Test Alert for ' + @SITE + ' (Dummy)' AS ItemTitle,
        'Generated by ConnectedOperations repository dummy.' AS ItemBody,
        CAST(NULL AS nvarchar(max))    AS ItemDetail,
        CAST(NULL AS nvarchar(200))    AS ItemIcon, 
        'https://conops.apps-dev.fmi.com/#/sites/' + @SITE + '/drillAndBlast' AS ItemUrl,
        CAST(NULL AS nvarchar(50))     AS AlertDateText,
        CAST(NULL AS datetime2(7))     AS UtcAlertDate,
        CAST(NULL AS datetime2(7))     AS UtcStartDate,
        CAST(NULL AS datetime2(7))     AS UtcEndDate,
        CAST(NULL AS nvarchar(50))     AS MobilePageDetailType,
        'ALE00001'                     AS AlertID,
        '0061036114'                   AS DestinationID;

END TRY
BEGIN CATCH
	PRINT ERROR_MESSAGE();
END CATCH
END
