


/******************************************************************      
* PROCEDURE : DBO.[UPSERT_CONOPS_PIT_TRUCK]    
* PURPOSE : UPSERT [UPSERT_CONOPS_PIT_TRUCK]    
* NOTES     :     
* CREATED : LWASINI    
* SAMPLE    : EXEC DBO.[UPSERT_CONOPS_PIT_TRUCK]     
* MODIFIED DATE  AUTHOR    DESCRIPTION      
*------------------------------------------------------------------      
* {25 OCT 2022}  {LWASINI}   {INITIAL CREATED}      
*******************************************************************/      
CREATE  PROCEDURE [DBO].[UPSERT_CONOPS_PIT_TRUCK]    
(    
@G_SITE VARCHAR(5)    
)    
AS    
BEGIN    
  
EXEC     
(  
  
' DELETE FROM ' +@G_SITE+ '.PIT_TRUCK'   
  
+' INSERT INTO ' +@G_SITE+ '.PIT_TRUCK'   
+' SELECT '   
+' DBPREVIOUS,'  
+' DBNEXT,'  
+' DBVERSION,'  
+' ID,'  
+' DBNAME,'  
+' DBKEY,'  
+' FIELDID,'  
+' FIELDQUEUE,'  
+' FIELDEXCAVNEXT,'  
+' FIELDLOC,'  
+' FIELDLOCNEXT,'  
+' FIELDEXCAVLOCK,'  
+' FIELDDUMPLOCK,'  
+' FIELDEXCAV,'  
+' FIELDDUMPASN,'  
+' FIELDLOCSTART,'  
+' FIELDLASTLOC,'  
+' FIELDVAN,'  
+' FIELDREGIONLOCK,'  
+' FIELDLASTEXCAV,'  
+' FIELDBAY,'  
+' FIELDLUNCHBREAK,'  
+' FIELDBEAN,'  
+' FIELDSIZE,'  
+' FIELDFUELAMT,'  
+' FIELDTONS,'  
+' FIELDSIMCODE,'  
+' FIELDSENDCOUNT,'  
+' FIELDRCVCOUNT,'  
+' FIELDTIME1,'  
+' FIELDTIME2,'  
+' FIELDBEANS,'  
+' FIELDTIMELATE,'  
+' FIELDTIMELAST,'  
+' FIELDTIMENEXT,'  
+' FIELDRATELOAD,'  
+' FIELDTIMESPOT,'  
+' FIELDCLOCK,'  
+' FIELDASNTIME,'  
+' FIELDTIMEBREAK,'  
+' FIELDTIMEPANEL,'  
+' FIELDCALCTIME,'  
+' FIELDMAXRATELOAD,'  
+' FIELDPANELID,'  
+' FIELDFUELTANK,'  
+' FIELDSIGNID,'  
+' FIELDREASON,'  
+' FIELDLINEREASON,'  
+' FIELDUNIT,'  
+' FIELDUNITLOC,'  
+' FIELDUNITLOCNEXT,'  
+' FIELDACTLAST,'  
+' FIELDACTNEXT,'  
+' FIELDACTSIM,'  
+' FIELDSTATUS,'  
+' FIELDLOAD,'  
+' FIELDPORT,'  
+' FIELDPRIOR,'  
+' FIELDLINESTAT,'  
+' FIELDLOGIN,'  
+' FIELDPRIORORE,'  
+' FIELDPRIORWASTE,'  
+' FIELDRETORQUE,'  
+' FIELDEQMTTYPE,'  
+' FIELDNOASSIGN,'  
+' FIELDTRAM,'  
+' FIELDLASTLOAD,'  
+' FIELDSIGNPOST,'  
+' FIELDDOUBLESPOT,'  
+' FIELDVSMSTBL,'  
+' FIELDCOMMENT,'  
+' FIELDLINECMT,'  
+' FIELDIRBEACON,'  
+' FIELDTRAMLOAD,'  
+' FIELDFREEARRIVE,'  
+' FIELDSAVEPRIOR,'  
+' FIELDDIST,'  
+' FIELDEFH,'  
+' FIELDXLOC,'  
+' FIELDYLOC,'  
+' FIELDRADIUS,'  
+' FIELDGPSTYPE,'  
+' FIELDLPEQMT,'  
+' FIELDTRAMSCHEDULE,'  
+' FIELDDIGLOCK,'  
+' FIELDVELOCITY,'  
+' FIELDHEADING,'  
+' FIELDDIRECTION,'  
+' FIELDTIEDOWNACCEPTED,'  
+' FIELDPROPFEED,'  
+' FIELDZ,'  
+' FIELDSHOVELDIST,'  
+' FIELDDUMPDIST,'  
+' FIELDLASTSTATUSTIME,'  
+' FIELDLASTSTATREASON,'  
+' FIELDTIEDOWNPROPOSED,'  
+' FIELDTHRESHOLD,'  
+' FIELDMINOUT,'  
+' FIELDTIRETIME,'  
+' FIELDTIRECTRL,'  
+' FIELDDUMPASNTIME,'  
+' FIELDSHOVELFULLTIME,'  
+' FIELDLASTBREAK,'  
+' FIELDCUROPER,'  
+' FIELDCURSCOPE,'  
+' FIELDCURBREAK,'  
+' FIELDORIGASNEXCAV,'  
+' FIELDORIGASNLOC,'  
+' FIELDREASNBY,'  
+' FIELDPATHTIME,'  
+' FIELDQUEUESIZE,'  
+' FIELDTIMEQUEUE,'  
+' FIELDPANTOREADY,'  
+' FIELDEXPTRAVELDIST,'  
+' FIELDEXPTRAVELTIME,'  
+' FIELDGPSTRAVELDIST,'  
+' FIELDFSGROUP,'  
+' FIELDGLOC,'  
+' FIELDHPGPS,'  
+' FIELDPV3SUP,'  
+' FIELDLASTRFTAGTIME,'  
+' FIELDACTPOLY,'  
+' FIELDPRESTARTDONE,'  
+' FIELDPRESUNIT,'  
+' FIELDPANDH,'  
+' FIELDFIRSTDIPPER,'  
+' FIELDLASTDIPPER,'  
+' FIELDBKTCNT,'  
+' FIELDCNT,'  
+' FIELDPANTOID,'  
+' FIELDPANTOUPLOC,'  
+' FIELDPANTOUPDIST,'  
+' FIELDPANTOUPVEL,'  
+' FIELDPANTOTIME,'  
+' FIELDPANTOERROR,'  
+' FIELDWSTATION,'  
+' FIELDLOCACTION,'  
+' FIELDLVSPROXCNT,'  
+' FIELDTDOWNTIME,'  
+' FIELDGPSOK,'  
+' FIELDSTART,'  
+' FIELDLASTGPS,'  
+' FIELDGPSTIME,'  
+' FIELDLASTGPSUPDATE,'  
+' FIELDTDBAR,'  
+' FIELDTDRELEASE,'  
+' FIELDIGNUNEXARR,'  
+' FIELDFUELED,'  
+' FIELDFUELTIME,'  
+' FIELDFUELFACT,'  
