
  
  
  
/******************************************************************    
* PROCEDURE : DBO.[UPSERT_CONOPS_DELTA_C]  
* PURPOSE : UPSERT [UPSERT_CONOPS_DELTA_C]  
* NOTES     :   
* CREATED : MFAHMI  
* SAMPLE    : EXEC DBO.[UPSERT_CONOPS_DELTA_C]   
* MODIFIED DATE  AUTHOR    DESCRIPTION    
*------------------------------------------------------------------    
* {28 NOV 2022}  {MFAHMI}   {INITIAL CREATED}    
*******************************************************************/    
CREATE  PROCEDURE [DBO].[UPSERT_CONOPS_DELTA_C]  
AS  
BEGIN  
  
DELETE FROM DBO.DELTA_C  
  
INSERT INTO DBO.DELTA_C  
 SELECT   
 CLIID  
,SITE_CODE  
,START_DATE_TS  
,DELTAC_TS  
,END_DATE_TS  
,SHIFTINDEX  
,SHIFTDATE  
,YEAR_CODE  
,MONTH_CODE  
,MONTHS  
,SHIFT  
,SHIFT_CODE  
,CREW_CODE  
,CREW  
,HARVHOS  
,DIGTYPE  
,SHVTYPE  
,DIPPER  
,TRKTYPE  
,PAYLOAD  
,IDLETIME  
,SPOTTIME  
,LOADTIME  
,DUMPINGTIME  
,CRUSHERIDLE  
,TRAVELEMPTY  
,TRAVELLOADED  
,TOTALCYCLE  
,CALCTRAVEMPTY  
,CALCTRAVLOADED  
,HOS  
,TIMEFULL  
,TIMELOADED  
,EXCAV  
,SOPERID  
,SOPER  
,TRUCK  
,TOPERID  
,TOPER  
,LOAD_CODE  
,MATERIAL  
,BENCH  
,UNIT_CODE  
,UNIT  
,DUMPNAME  
,TRUCK_IDLEDELTA  
,SPOTDELTA  
,LOADDELTA  
,DUMPDELTA  
,ET_DELTA  
,LT_DELTA  
,DELTA_C  
,TOAVGDELTAC  
,TOSTDEVDELTAC  
,TOAVGIDLEDELTA  
,TOSTDEVIDLEDELTA  
,TOAVGSPOTDELTA  
,TOSTDEVSPOTDELTA  
,TOAVGLOADDELTA  
,TOSTDEVLOADDELTA  
,TOAVGETDELTA  
,TOSTDEVETDELTA  
,TOAVGLTDELTA  
,TOSTDEVLTDELTA  
,TOAVGDUMPDELTA  
,TOSTDEVDUMPDELTA  
,VTODELTAC3  
,LOAD_SEQ_NO  
,GRADE  
,EXTRALOAD  
,LOADTYPE  
,LOADTONS  
,MEASURETONS_SHOVEL  
,OVER_TRUCK_FLAG  
,UNDER_TRUCK_FLAG  
,DUMP_FLAG  
,SHOVEL_IDLE  
,CRUSHER_DUMP_FLAG  
,DUMP_NUMBER  
,LDUMP_HOS  
,DUMP_HOS  
,DUMP_OPER_ID  
,SHOVEL_EQMTTYPE_CODE  
,TRUCK_EQMTTYPE_CODE  
,SHVL_OPS_PRTL_EQUIP_GROUP_NO_CODE  
,TRK_OPS_PRTL_EQUIP_GROUP_NO_CODE  
,SHOVEL_IDLEDELTA  
,ELIFTUP  
,ELIFTDOWN  
,DISTLOADED  
,FLIFTUP  
,FLIFTDOWN  
,DISTEMPTY  
,CRUSHERDELTA  
,DUMPINGDELTA  
,EMPTYHAUL  
,LOAD_TIMEARRIVE  
,TIMELOAD  
,BEGINSPOT  
,HANGTIME  
,DUMP_TIMEARRIVE  
,TIMEDUMP  
,TIMEEMPTY  
,DUMP_TIMEARRIVE_TS  
,TIMEDUMP_TS  
,TIMEEMPTY_TS  
,IDLEDELTA  
,REGION  
,UTC_CREATED_DATE  
 FROM DBO.DELTA_C_STG    
   
END  
  
