CREATE TABLE [chi].[drill_hole_stg] (
    [Id] varchar(36) NOT NULL,
    [DrillPlanId] varchar(36) NOT NULL,
    [HoleId] varchar(24) NULL,
    [RigSerialNumber] varchar(64) NULL,
    [StartPointX] decimal(19,0) NOT NULL,
    [StartPointY] decimal(19,0) NOT NULL,
    [StartPointZ] decimal(19,0) NOT NULL,
    [EndPointX] decimal(19,0) NOT NULL,
    [EndPointY] decimal(19,0) NOT NULL,
    [EndPointZ] decimal(19,0) NOT NULL,
    [TypeOfHole] int NOT NULL,
    [DrillBitDiameter] int NOT NULL,
    [DrillBitType] int NOT NULL,
    [MeasureWhileDrilling] bit NOT NULL,
    [DrillBitChange] decimal(19,0) NOT NULL,
    [StartHoleTime] datetime NULL,
    [EndHoleTime] datetime NULL,
    [AveragePenetrationRateInMetersPerMinute] decimal(19,0) NOT NULL,
    [SequenceNumber] int NOT NULL,
    [NumberOfStops] int NOT NULL,
    [Status] int NOT NULL,
    [PositioningMode] int NOT NULL,
    [AnchoringMode] int NOT NULL,
    [CollaringMode] int NOT NULL,
    [DrillMode] int NOT NULL,
    [ActivationMode] int NOT NULL,
    [StartLogTime] datetime NULL,
    [OperatorName] varchar(100) NULL,
    [GpsQuality] int NULL,
    [TowerAngle] decimal(19,0) NULL,
    [DrillBitId] varchar(100) NULL,
    [DrilledInRock] decimal(19,0) NULL,
    [HoleName] varchar(256) NULL,
    [RawStartPointX] decimal(19,0) NOT NULL,
    [RawStartPointY] decimal(19,0) NOT NULL,
    [RawStartPointZ] decimal(19,0) NOT NULL,
    [RawEndPointX] decimal(19,0) NOT NULL,
    [RawEndPointY] decimal(19,0) NOT NULL,
    [RawEndPointZ] decimal(19,0) NOT NULL,
    [IsEdited] bit NOT NULL,
    [Comment] varchar(512) NULL,
    [change_type] varchar(1) NOT NULL,
    [change_id] decimal(19,0) NOT NULL,
    [UTC_CREATED_DATE] datetime NOT NULL,
    [UTC_LOGICAL_DELETED_DATE] datetime NULL
);