CREATE TABLE [chi].[ZZZ_PLAN_VALUES_OLD_20230512] (
    [SITEFLAG] varchar(5) NOT NULL,
    [CONTENTTYPEID] varchar(100) NOT NULL,
    [ID] int NOT NULL,
    [COMPLIANCEASSETID] varchar(100) NULL,
    [PlanName] varchar(50) NULL,
    [DateEffective] date NULL,
    [OreTPD] decimal(28,5) NULL,
    [LTMillSTKTPD] decimal(28,5) NULL,
    [HGLeachTPD] decimal(28,5) NULL,
    [LGLeachTPD] decimal(28,5) NULL,
    [ROM_OXTPD] decimal(28,5) NULL,
    [WasteTPD] decimal(28,5) NULL,
    [TotalExPitTPD] decimal(28,5) NULL,
    [OreRehandletoCrusherTPD] decimal(28,5) NULL,
    [RehandleWasteTPD] decimal(28,5) NULL,
    [RehandleOxideTPD] decimal(28,5) NULL,
    [LeeHillTPD] decimal(28,5) NULL,
    [EstrellaTPD] decimal(28,5) NULL,
    [HanoverTPD] decimal(28,5) NULL,
    [SouthPitTPD] decimal(28,5) NULL,
    [994LDRTPD] decimal(28,5) NULL,
    [35TPD] decimal(28,5) NULL,
    [43TPD] decimal(28,5) NULL,
    [44TPD] decimal(28,5) NULL,
    [45TPD] decimal(28,5) NULL,
    [46TPD] decimal(28,5) NULL,
    [ElectricShovelAvailability] varchar(50) NULL,
    [ElectricShovelUofA] decimal(28,5) NULL,
    [ElectricShovelAssetEfficiency] varchar(50) NULL,
    [TruckAvailability] varchar(50) NULL,
    [TruckUofA] decimal(28,5) NULL,
    [TruckAssetEfficiency] varchar(50) NULL,
    [AvgReadyTrucks] decimal(28,5) NULL,
    [PlannedTruckFleet] decimal(28,5) NULL,
    [DeltaC] decimal(28,5) NULL,
    [EFH] decimal(28,5) NULL,
    [PlannedEmptyTravelTime] decimal(28,5) NULL,
    [PlannedLoadedTravelTime] decimal(28,5) NULL,
    [PlannedDumpTimeSEC] decimal(28,5) NULL,
    [PlannedWaitTimeSEC] decimal(28,5) NULL,
    [PlannedSpotTimeSEC] decimal(28,5) NULL,
    [PlannedAvgShiftchangeTrucks] decimal(28,5) NULL,
    [PlannedAvgOpDelayTrucks] decimal(28,5) NULL,
    [PlannedAvgSchDownTrucks] decimal(28,5) NULL,
    [OreEFH] decimal(28,5) NULL,
    [ROMEFH] decimal(28,5) NULL,
    [LGLEFH] decimal(28,5) NULL,
    [ROM_OXEFH] decimal(28,5) NULL,
    [WasteEFH] decimal(28,5) NULL,
    [793TonnageFactor] decimal(28,5) NULL,
    [FavorableLift] varchar(50) NULL,
    [OneWayHaul] varchar(50) NULL,
    [PlannedLoadTimeSec] varchar(50) NULL,
    [UnfavorableLift] varchar(50) NULL,
    [CONTENTTYPE] varchar(50) NOT NULL,
    [MODIFIED] datetime NOT NULL,
    [CREATED] datetime NOT NULL,
    [CREATEDBYID] int NOT NULL,
    [MODIFIEDBYID] int NOT NULL,
    [OWSHIDDENVERSION] int NOT NULL,
    [VERSION] decimal(10,5) NOT NULL,
    [PATH] varchar(2000) NOT NULL,
    [UTC_CREATED_DATE] datetime NOT NULL
);