CREATE TABLE [chi].[ZZZ_PLAN_VALUES_TEMP] (
    [ID] varchar(50) NULL,
    [PlanName] varchar(50) NULL,
    [DateEffective] date NULL,
    [OreTPD] decimal(28,5) NULL,
    [LT Mill STK TPD] decimal(28,5) NULL,
    [HG Leach TPD] decimal(28,5) NULL,
    [LG Leach TPD] decimal(28,5) NULL,
    [ROM_OX TPD] decimal(28,5) NULL,
    [Waste TPD] decimal(28,5) NULL,
    [Total Ex-Pit TPD] decimal(28,5) NULL,
    [Total In-Pit TPD] decimal(28,5) NULL,
    [Total Material to Crusher] decimal(28,5) NULL,
    [Ore Rehandle to Crusher TPD] decimal(28,5) NULL,
    [Rehandle Waste TPD] decimal(28,5) NULL,
    [Rehandle Oxide TPD] decimal(28,5) NULL,
    [Lee Hill TPD] decimal(28,5) NULL,
    [Estrella TPD] decimal(28,5) NULL,
    [Hanover TPD] decimal(28,5) NULL,
    [South Pit TPD] decimal(28,5) NULL,
    [994 LDR TPD] decimal(28,5) NULL,
    [35 TPD] decimal(28,5) NULL,
    [43 TPD] decimal(28,5) NULL,
    [44 TPD] decimal(28,5) NULL,
    [45 TPD] decimal(28,5) NULL,
    [46 TPD] decimal(28,5) NULL,
    [Electric Shovel Tons Ready Hour] decimal(28,5) NULL,
    [Electric Shovel Availability] varchar(50) NULL,
    [Electric Shovel UofA] decimal(28,5) NULL,
    [Electric Shovel Asset Efficiency] varchar(50) NULL,
    [Truck Availability] varchar(50) NULL,
    [Truck UofA] decimal(28,5) NULL,
    [Truck Asset Efficiency] varchar(50) NULL,
    [Avg Ready Trucks] decimal(28,5) NULL,
    [Planned Truck Fleet] decimal(28,5) NULL,
    [Delta C] decimal(28,5) NULL,
    [EFH] decimal(28,5) NULL,
    [Planned Empty Travel Time] decimal(28,5) NULL,
    [Planned Loaded Travel Time] decimal(28,5) NULL,
    [Planned Dump Time (sec)] decimal(28,5) NULL,
    [Planned Wait Time (sec)] decimal(28,5) NULL,
    [Planned Load Time P&H 2800 (min)] decimal(28,5) NULL,
    [Planned Load Time P&H 4100 (min)] decimal(28,5) NULL,
    [Planned Spot Time (sec)] decimal(28,5) NULL,
    [Planned Avg Shiftchange Trucks] decimal(28,5) NULL,
    [Planned Avg Op Delay Trucks] decimal(28,5) NULL,
    [Planned Avg Sch Down Trucks] decimal(28,5) NULL,
    [Ore EFH] decimal(28,5) NULL,
    [ROM EFH] decimal(28,5) NULL,
    [LGL EFH] decimal(28,5) NULL,
    [ROM_OX EFH] decimal(28,5) NULL,
    [Waste EFH] decimal(28,5) NULL,
    [793 Tonnage Factor] decimal(28,5) NULL,
    [Total Cycle Time (min)] decimal(28,5) NULL,
    [Avg Ready Elec Shovels] decimal(28,5) NULL,
    [Feet Drilled Day] decimal(28,5) NULL,
    [Holes Drilled Day] decimal(28,5) NULL,
    [Drill Availability] decimal(28,5) NULL,
    [Drill Utilization] decimal(28,5) NULL,
    [Drill Asset Efficiency] varchar(50) NULL,
    [Avg Ready Drills] decimal(28,5) NULL
);