CREATE TABLE [bag].[FLEET_EQ_STATUS] (
    [SITE_CODE] nvarchar(50) NULL,
    [ECF_CLASS_ID] nvarchar(50) NULL,
    [SHIFT_ID] int NULL,
    [FIELDUNIT] nvarchar(50) NULL,
    [MACHINE_CATEGORY] nvarchar(50) NULL,
    [EQUIP_NAME] nvarchar(50) NULL,
    [REASON_CODE] int NULL,
    [REASON] nvarchar(50) NULL,
    [CATEGORY_CODE] int NULL,
    [CATEGORY] nvarchar(50) NULL,
    [STATUS_CODE] int NULL,
    [STATUS] nvarchar(50) NULL,
    [LOCATION_NAME] nvarchar(50) NULL,
    [FieldExcav] nvarchar(50) NULL,
    [FieldXloc] nvarchar(50) NULL,
    [FieldYloc] nvarchar(50) NULL,
    [FieldVelocity] nvarchar(50) NULL,
    [Fieldlaststatus] nvarchar(50) NULL,
    [FieldCurOper] nvarchar(50) NULL,
    [START_TIME_UTC] datetime2 NULL,
    [END_TIME_UTC] datetime2 NULL,
    [DURATION] smallint NULL,
    [MACHINE_OID] int NULL
);