CREATE TABLE [bag].[PLAN_VALUES] (
    [SITEFLAG] varchar(5) NOT NULL,
    [FORMATSHIFTID] varchar(50) NULL,
    [CONTENTTYPEID] varchar(100) NOT NULL,
    [SHIFTID] varchar(50) NULL,
    [COMPLIANCEASSETID] varchar(100) NULL,
    [TOTALMINED] decimal(18,5) NULL,
    [L01ORE] decimal(18,5) NULL,
    [L01WASTEOXIDE] decimal(18,5) NULL,
    [L05ORE] decimal(18,5) NULL,
    [L05WASTEOXIDE] decimal(18,5) NULL,
    [S08ORE] decimal(18,5) NULL,
    [S08WASTEOXIDE] decimal(18,5) NULL,
    [S10ORE] decimal(18,5) NULL,
    [S10WASTEOXIDE] decimal(18,5) NULL,
    [S11ORE] decimal(18,5) NULL,
    [S11WASTEOXIDE] decimal(18,5) NULL,
    [S12ORE] decimal(18,5) NULL,
    [S12WASTEOXIDE] decimal(18,5) NULL,
    [S22ORE] decimal(18,5) NULL,
    [S22WASTEOXIDE] decimal(18,5) NULL,
    [S23ORE] decimal(18,5) NULL,
    [S23WASTEOXIDE] decimal(18,5) NULL,
    [REHANDLE] decimal(18,5) NULL,
    [W3TONS] decimal(18,5) NULL,
    [E3TONS] decimal(18,5) NULL,
    [N1TONS] decimal(18,5) NULL,
    [N2TONS] decimal(18,5) NULL,
    [N3TONS] decimal(18,5) NULL,
    [S4TONS] decimal(18,5) NULL,
    [TOTALEXPITTONS] decimal(18,5) NULL,
    [EFH] decimal(18,5) NULL,
    [CRUSHER2] decimal(18,5) NULL,
    [QUEUEDELTACTARGET] decimal(18,5) NULL,
    [SPOTTINGDELTACTARGET] decimal(18,5) NULL,
    [LOADINGDELTACTARGET] decimal(18,5) NULL,
    [LOADEDTRAVELDELTACTARGET] decimal(18,5) NULL,
    [DUMPINGDELTACTARGET] decimal(18,5) NULL,
    [STOCKPILETARGETS] decimal(18,5) NULL,
    [DUMPINGATCRUSHER] decimal(18,5) NULL,
    [EMPTYTRAVELDELTACTARGET] decimal(18,5) NULL,
    [ID] int NOT NULL,
    [CONTENTTYPE] varchar(50) NOT NULL,
    [MODIFIED] datetime NOT NULL,
    [CREATED] datetime NOT NULL,
    [CREATEDBYID] int NOT NULL,
    [MODIFIEDBYID] int NOT NULL,
    [OWSHIDDENVERSION] int NOT NULL,
    [VERSION] decimal(10,5) NOT NULL,
    [PATH] varchar(2000) NOT NULL,
    [UTC_CREATED_DATE] datetime NULL
);