CREATE TABLE [bag].[target_shovel_by_shift] (
    [Shiftid] varchar(15) NOT NULL,
    [TotalMined] int NULL,
    [L01Ore] int NULL,
    [L01Waste] int NULL,
    [L02Ore] int NULL,
    [L02Waste] int NULL,
    [S08Ore] int NULL,
    [S08Waste] int NULL,
    [S10Ore] int NULL,
    [S10Waste] int NULL,
    [S11Ore] int NULL,
    [S11Waste] int NULL,
    [S12Ore] int NULL,
    [S12Waste] int NULL,
    [S22Ore] int NULL,
    [S22Waste] int NULL,
    [S23Ore] int NULL,
    [S23Waste] int NULL,
    [Rehandle] int NULL,
    [E1Tons] int NULL,
    [E3Tons] int NULL,
    [N1Tons] int NULL,
    [N2Tons] int NULL,
    [N3Tons] int NULL,
    [S4Tons] int NULL,
    [TotalExpitTons] int NULL,
    [EFH] decimal(10,5) NULL,
    [Chrusher2] int NULL,
    [DumpingAtCrusher] int NULL,
    [StockpileTarget] int NULL,
    [UTC_CREATED_DATE] datetime NULL,
    [LOGICAL_DELETED_FLAG] varchar(1) NULL
);