/*
================================================================================
DRILLBLAST_INCR Objects - Deploy to TEST_API_REF.FUSE
================================================================================
Generated: 2026-01-26
Requested by: Vikas
Purpose: Move all 22 objects (11 tables + 11 procedures) to TEST environment

Instructions:
1. Execute this script in Snowflake with a role that has CREATE privileges on TEST_API_REF.FUSE
2. Each table is cloned from DEV_API_REF.FUSE (includes data)
3. Each procedure is created fresh

Alternatively, grant CREATE TABLE and CREATE PROCEDURE to SG-AZW-SFLK-ENG-GENERAL:
    GRANT CREATE TABLE ON SCHEMA TEST_API_REF.FUSE TO ROLE "SG-AZW-SFLK-ENG-GENERAL";
    GRANT CREATE PROCEDURE ON SCHEMA TEST_API_REF.FUSE TO ROLE "SG-AZW-SFLK-ENG-GENERAL";
================================================================================
*/

USE DATABASE TEST_API_REF;
USE SCHEMA FUSE;
USE WAREHOUSE WH_BATCH_DE_NONPROD;

-- ============================================================================
-- STEP 1: Clone all 11 tables from DEV to TEST
-- ============================================================================

-- 1. BL_DW_BLAST_INCR
DROP TABLE IF EXISTS TEST_API_REF.FUSE.BL_DW_BLAST_INCR;
CREATE TABLE TEST_API_REF.FUSE.BL_DW_BLAST_INCR 
    CLONE DEV_API_REF.FUSE.BL_DW_BLAST_INCR;

-- 2. BL_DW_BLASTPROPERTYVALUE_INCR
DROP TABLE IF EXISTS TEST_API_REF.FUSE.BL_DW_BLASTPROPERTYVALUE_INCR;
CREATE TABLE TEST_API_REF.FUSE.BL_DW_BLASTPROPERTYVALUE_INCR 
    CLONE DEV_API_REF.FUSE.BL_DW_BLASTPROPERTYVALUE_INCR;

-- 3. BL_DW_HOLE_INCR
DROP TABLE IF EXISTS TEST_API_REF.FUSE.BL_DW_HOLE_INCR;
CREATE TABLE TEST_API_REF.FUSE.BL_DW_HOLE_INCR 
    CLONE DEV_API_REF.FUSE.BL_DW_HOLE_INCR;

-- 4. BLAST_PLAN_INCR
DROP TABLE IF EXISTS TEST_API_REF.FUSE.BLAST_PLAN_INCR;
CREATE TABLE TEST_API_REF.FUSE.BLAST_PLAN_INCR 
    CLONE DEV_API_REF.FUSE.BLAST_PLAN_INCR;

-- 5. BLAST_PLAN_EXECUTION_INCR
DROP TABLE IF EXISTS TEST_API_REF.FUSE.BLAST_PLAN_EXECUTION_INCR;
CREATE TABLE TEST_API_REF.FUSE.BLAST_PLAN_EXECUTION_INCR 
    CLONE DEV_API_REF.FUSE.BLAST_PLAN_EXECUTION_INCR;

-- 6. DRILL_CYCLE_INCR
DROP TABLE IF EXISTS TEST_API_REF.FUSE.DRILL_CYCLE_INCR;
CREATE TABLE TEST_API_REF.FUSE.DRILL_CYCLE_INCR 
    CLONE DEV_API_REF.FUSE.DRILL_CYCLE_INCR;

-- 7. DRILL_PLAN_INCR
DROP TABLE IF EXISTS TEST_API_REF.FUSE.DRILL_PLAN_INCR;
CREATE TABLE TEST_API_REF.FUSE.DRILL_PLAN_INCR 
    CLONE DEV_API_REF.FUSE.DRILL_PLAN_INCR;

-- 8. DRILLBLAST_EQUIPMENT_INCR
DROP TABLE IF EXISTS TEST_API_REF.FUSE.DRILLBLAST_EQUIPMENT_INCR;
CREATE TABLE TEST_API_REF.FUSE.DRILLBLAST_EQUIPMENT_INCR 
    CLONE DEV_API_REF.FUSE.DRILLBLAST_EQUIPMENT_INCR;

-- 9. DRILLBLAST_OPERATOR_INCR
DROP TABLE IF EXISTS TEST_API_REF.FUSE.DRILLBLAST_OPERATOR_INCR;
CREATE TABLE TEST_API_REF.FUSE.DRILLBLAST_OPERATOR_INCR 
    CLONE DEV_API_REF.FUSE.DRILLBLAST_OPERATOR_INCR;

-- 10. DRILLBLAST_SHIFT_INCR
DROP TABLE IF EXISTS TEST_API_REF.FUSE.DRILLBLAST_SHIFT_INCR;
CREATE TABLE TEST_API_REF.FUSE.DRILLBLAST_SHIFT_INCR 
    CLONE DEV_API_REF.FUSE.DRILLBLAST_SHIFT_INCR;

-- 11. LH_HAUL_CYCLE_INCR
DROP TABLE IF EXISTS TEST_API_REF.FUSE.LH_HAUL_CYCLE_INCR;
CREATE TABLE TEST_API_REF.FUSE.LH_HAUL_CYCLE_INCR 
    CLONE DEV_API_REF.FUSE.LH_HAUL_CYCLE_INCR;

-- ============================================================================
-- STEP 2: Copy all 11 procedures from DEV to TEST
-- Use GET_DDL to extract DDL, then manually replace database name
-- ============================================================================

-- Execute these one by one in Snowflake:
-- For each procedure, run:
--   SELECT GET_DDL('PROCEDURE', 'DEV_API_REF.FUSE.<PROC_NAME>(VARCHAR)');
-- Then replace DEV_API_REF with TEST_API_REF and execute

-- Or run this PL/SQL to generate all DDLs:
/*
DECLARE
  ddl_stmt STRING;
  procs ARRAY := ARRAY_CONSTRUCT(
    'BL_DW_BLAST_INCR_P',
    'BL_DW_BLASTPROPERTYVALUE_INCR_P',
    'BL_DW_HOLE_INCR_P',
    'BLAST_PLAN_INCR_P',
    'BLAST_PLAN_EXECUTION_INCR_P',
    'DRILL_CYCLE_INCR_P',
    'DRILL_PLAN_INCR_P',
    'DRILLBLAST_EQUIPMENT_INCR_P',
    'DRILLBLAST_OPERATOR_INCR_P',
    'DRILLBLAST_SHIFT_INCR_P',
    'LH_HAUL_CYCLE_INCR_P'
  );
BEGIN
  FOR i IN 0 TO ARRAY_SIZE(procs) - 1 DO
    ddl_stmt := GET_DDL('PROCEDURE', 'DEV_API_REF.FUSE.' || procs[i] || '(VARCHAR)');
    ddl_stmt := REPLACE(ddl_stmt, 'DEV_API_REF.FUSE', 'TEST_API_REF.FUSE');
    EXECUTE IMMEDIATE ddl_stmt;
  END FOR;
END;
*/

-- ============================================================================
-- STEP 3: Verify all objects exist
-- ============================================================================

-- Check tables
SELECT 'TABLE' AS object_type, TABLE_NAME, ROW_COUNT
FROM TEST_API_REF.INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'FUSE' 
AND TABLE_NAME LIKE '%_INCR'
ORDER BY TABLE_NAME;

-- Check procedures
SELECT 'PROCEDURE' AS object_type, PROCEDURE_NAME, ARGUMENT_SIGNATURE
FROM TEST_API_REF.INFORMATION_SCHEMA.PROCEDURES 
WHERE PROCEDURE_SCHEMA = 'FUSE' 
AND PROCEDURE_NAME LIKE '%_INCR_P'
ORDER BY PROCEDURE_NAME;

-- ============================================================================
-- STEP 4: Quick test each procedure
-- ============================================================================

CALL TEST_API_REF.FUSE.BL_DW_BLAST_INCR_P('3');
CALL TEST_API_REF.FUSE.BL_DW_BLASTPROPERTYVALUE_INCR_P('3');
CALL TEST_API_REF.FUSE.BL_DW_HOLE_INCR_P('3');
CALL TEST_API_REF.FUSE.BLAST_PLAN_INCR_P('3');
CALL TEST_API_REF.FUSE.BLAST_PLAN_EXECUTION_INCR_P('3');
CALL TEST_API_REF.FUSE.DRILL_CYCLE_INCR_P('3');
CALL TEST_API_REF.FUSE.DRILL_PLAN_INCR_P('3');
CALL TEST_API_REF.FUSE.DRILLBLAST_EQUIPMENT_INCR_P('3');
CALL TEST_API_REF.FUSE.DRILLBLAST_OPERATOR_INCR_P('3');
CALL TEST_API_REF.FUSE.DRILLBLAST_SHIFT_INCR_P('3');
CALL TEST_API_REF.FUSE.LH_HAUL_CYCLE_INCR_P('3');
