/*******************************************************************************
 * DRILL_CYCLE_INCR - Incremental Table and Stored Procedure
 * 
 * Source: PROD_WG.DRILL_BLAST.DRILL_CYCLE
 * Target: DEV_API_REF.FUSE.DRILL_CYCLE_INCR
 * Business Key: DRILL_CYCLE_SK
 * Timestamp Column: DW_MODIFY_TS
 * 
 * Pattern: MERGE-driven upserts with hash-based conditional updates
 * Incremental Window: 3 days default, max 30 days
 * Soft Deletes: DW_LOGICAL_DELETE_FLAG = 'Y'
 ******************************************************************************/

-- =============================================================================
-- TABLE DDL
-- =============================================================================
CREATE OR REPLACE TABLE DEV_API_REF.FUSE.DRILL_CYCLE_INCR (
    -- Business Key
    DRILL_CYCLE_SK              BIGINT          NOT NULL,
    
    -- Source Identifiers
    ORIG_SRC_ID                 INT,
    SITE_CODE                   VARCHAR(5),
    
    -- Pattern Identifiers
    BENCH                       VARCHAR(5000),
    PUSHBACK                    VARCHAR(500),
    PATTERN_NAME                VARCHAR(500),
    ORIGINAL_PATTERN_NAME       VARCHAR(500),
    
    -- Drill/Shift/Operator
    DRILL_HOLE_SHIFT_ID         VARCHAR(500),
    DRILL_ID                    BIGINT,
    DRILL_BIT_ID                VARCHAR(255),
    SYSTEM_OPERATOR_ID          VARCHAR(50),
    
    -- Hole Identification
    DRILL_HOLE_ID               VARCHAR(500),
    DRILL_HOLE_NAME             VARCHAR(500),
    DRILL_PLAN_SK               BIGINT,
    DRILL_HOLE_STATUS           BIGINT,
    IS_HOLE_PLANNED_FLAG        BIGINT,
    
    -- Timestamps (UTC)
    START_HOLE_TS_UTC           VARCHAR(50),
    END_HOLE_TS_UTC             VARCHAR(50),
    OPERATOR_LOGIN_TS_UTC       VARCHAR(50),
    OPERATOR_LOGOUT_TS_UTC      VARCHAR(50),
    PROPEL_START_TS_UTC         VARCHAR(50),
    PROPEL_END_TS_UTC           VARCHAR(50),
    PARK_POSITION_START_TS_UTC  VARCHAR(50),
    PARK_POSITION_END_TS_UTC    VARCHAR(50),
    LEVEL_START_TS_UTC          VARCHAR(50),
    LEVEL_END_TS_UTC            VARCHAR(50),
    DRILL_START_TS_UTC          VARCHAR(50),
    DRILL_END_TS_UTC            VARCHAR(50),
    RETRACT_START_TS_UTC        VARCHAR(50),
    RETRACT_END_TS_UTC          VARCHAR(50),
    
    -- Timestamps (Local)
    START_HOLE_TS_LOCAL         VARCHAR(50),
    END_HOLE_TS_LOCAL           VARCHAR(50),
    OPERATOR_LOGIN_TS_LOCAL     VARCHAR(50),
    OPERATOR_LOGOUT_TS_LOCAL    VARCHAR(50),
    PROPEL_START_TS_LOCAL       VARCHAR(50),
    PROPEL_END_TS_LOCAL         VARCHAR(50),
    PARK_POSITION_START_TS_LOCAL VARCHAR(50),
    PARK_POSITION_END_TS_LOCAL  VARCHAR(50),
    LEVEL_START_TS_LOCAL        VARCHAR(50),
    LEVEL_END_TS_LOCAL          VARCHAR(50),
    DRILL_START_TS_LOCAL        VARCHAR(50),
    DRILL_END_TS_LOCAL          VARCHAR(50),
    RETRACT_START_TS_LOCAL      VARCHAR(50),
    RETRACT_END_TS_LOCAL        VARCHAR(50),
    PLAN_CREATION_TS_LOCAL      VARCHAR(50),
    
    -- Duration (Seconds)
    DRILL_HOLE_DURATION_SECONDS BIGINT,
    AUTODRILL_DURATION_SECONDS  BIGINT,
    TIME_BETWEEN_DRILL_HOLES_SECONDS BIGINT,
    SYSTEM_DRILL_STATE_DURATION_SECONDS BIGINT,
    SYSTEM_SETUP_STATE_DURATION_SECONDS BIGINT,
    SYSTEM_AUTO_LEVEL_DURATION_SECONDS BIGINT,
    SYSTEM_AUTO_DELEVEL_DURATION_SECONDS BIGINT,
    
    -- Durations (Decimal)
    PROPEL_DURATION             DECIMAL(36,6),
    PARK_POSITION_DURATION      DECIMAL(36,6),
    LEVEL_DURATION              DECIMAL(36,6),
    DRILL_DURATION              DECIMAL(36,6),
    RETRACT_DURATION            DECIMAL(36,6),
    
    -- Depth (Feet/Meters)
    ACTUAL_DRILL_HOLE_DEPTH_FEET    DECIMAL(38,5),
    ACTUAL_DRILL_HOLE_DEPTH_METERS  DECIMAL(38,5),
    
    -- Coordinates (Feet)
    ACTUAL_DRILL_HOLE_START_FEET_X  DECIMAL(38,5),
    ACTUAL_DRILL_HOLE_START_FEET_Y  DECIMAL(38,5),
    ACTUAL_DRILL_HOLE_START_FEET_Z  DECIMAL(38,5),
    ACTUAL_DRILL_HOLE_END_FEET_X    DECIMAL(38,5),
    ACTUAL_DRILL_HOLE_END_FEET_Y    DECIMAL(38,5),
    ACTUAL_DRILL_HOLE_END_FEET_Z    DECIMAL(38,5),
    
    -- Coordinates (Meters)
    ACTUAL_DRILL_HOLE_START_METERS_X DECIMAL(38,5),
    ACTUAL_DRILL_HOLE_START_METERS_Y DECIMAL(38,5),
    ACTUAL_DRILL_HOLE_START_METERS_Z DECIMAL(38,5),
    ACTUAL_DRILL_HOLE_END_METERS_X   DECIMAL(38,5),
    ACTUAL_DRILL_HOLE_END_METERS_Y   DECIMAL(38,5),
    ACTUAL_DRILL_HOLE_END_METERS_Z   DECIMAL(38,5),
    
    -- GPS/Location
    GPS_ACCURACY                BIGINT,
    ACTUAL_DRILL_HOLE_LONGITUDE FLOAT,
    ACTUAL_DRILL_HOLE_LATITUDE  FLOAT,
    
    -- Autodrill/Performance
    AUTODRILL_USAGE_PCT         BIGINT,
    DRILL_HOLE_PENETRATION_RATE_AVG_FEET_HOUR DECIMAL(38,5),
    INSTANTANOUS_PENRATE_MWD_METERS_HOUR DECIMAL(38,5),
    INSTANTANOUS_PENRATE_MWD_FEET_HOUR DECIMAL(38,5),
    
    -- Drill Angle
    BEARING                     DECIMAL(38,1),
    DRILL_TOWER_ANGLE_DEGREE_CALCULATED DECIMAL(38,5),
    DRILL_TOWER_ANGLE_DEGREE_SYSTEM DECIMAL(38,5),
    
    -- Quality Flags
    DRILL_HOLE_DUPLICATED_FLAG      BIGINT,
    DRILL_HOLE_UPSIDE_DOWN_FLAG     BIGINT,
    DRILL_HOLE_START_END_TIME_INVALID_FLAG BIGINT,
    DRILL_HOLE_START_END_TIME_OVERLAP_FLAG BIGINT,
    DRILL_HOLE_DEPTH_INVALID_FLAG   BIGINT,
    DRILL_HOLE_ANGLE_INVALID_FLAG   BIGINT,
    DRILL_HOLE_POSITION_INVALID_FLAG BIGINT,
    
    -- Accuracy Metrics
    DRILL_HOLE_OFF_TARGET_FEET      DECIMAL(38,5),
    DRILL_HOLE_OFF_TARGET_METERS    DECIMAL(38,5),
    DRILL_HOLE_HORIZONTAL_ACCURACY_PCT BIGINT,
    DRILL_HOLE_VERTICAL_ACCURACY_PCT BIGINT,
    
    -- Overdrill/Underdrill
    OVERDRILL_UNDERDRILL_FLAG       BOOLEAN,
    OVERDRILL_UNDERDRILL_FEET       DECIMAL(38,5),
    OVERDRILL_UNDERDRILL_METERS     DECIMAL(38,5),
    
    -- Drilling Stats
    DRILLING_STOPS_COUNT        BIGINT,
    DRILL_HOLE_REDRILL_FLAG     BIGINT,
    
    -- MWD Parameters
    AIR_PRESSURE_PSI            DECIMAL(38,5),
    FEED_FORCE_NEWTONS          DECIMAL(38,5),
    ROTATION_TORQUE_NM          DECIMAL(38,5),
    BIT_SPEED_RPM               DECIMAL(38,5),
    WATER_FLOW_GPM              DECIMAL(38,5),
    
    -- MCF Block
    ACTUAL_MCF_BLOCK_ID         VARCHAR(5000),
    DESIGN_MCF_BLOCK_ID         VARCHAR(5000),
    
    -- System Version
    SYSTEM_VERSION              VARCHAR(11),
    
    -- Data Warehouse Audit Columns
    DW_LOAD_TS                  TIMESTAMP_NTZ,
    DW_MODIFY_TS                TIMESTAMP_NTZ,
    DW_LOGICAL_DELETE_FLAG      VARCHAR(1)      DEFAULT 'N',
    DW_ROW_HASH                 VARCHAR(64),
    
    -- Primary Key
    CONSTRAINT PK_DRILL_CYCLE_INCR PRIMARY KEY (DRILL_CYCLE_SK)
);

-- =============================================================================
-- STORED PROCEDURE
-- =============================================================================
CREATE OR REPLACE PROCEDURE DEV_API_REF.FUSE.DRILL_CYCLE_INCR_P(
    P_DAYS_BACK FLOAT DEFAULT 3,
    P_MAX_DAYS FLOAT DEFAULT 30
)
RETURNS VARIANT
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
    var result = {
        procedure: 'DRILL_CYCLE_INCR_P',
        start_time: new Date().toISOString(),
        rows_purged: 0,
        rows_merged: 0,
        rows_inserted: 0,
        rows_updated: 0,
        rows_soft_deleted: 0,
        status: 'SUCCESS',
        error_message: null
    };
    
    try {
        // Validate parameters
        var daysBack = P_DAYS_BACK || 3;
        var maxDays = P_MAX_DAYS || 30;
        
        if (daysBack > maxDays) {
            daysBack = maxDays;
        }
        
        // Calculate cutoff timestamp
        var cutoffSQL = `SELECT DATEADD(day, -${daysBack}, CURRENT_TIMESTAMP())::TIMESTAMP_NTZ`;
        var cutoffStmt = snowflake.createStatement({sqlText: cutoffSQL});
        var cutoffResult = cutoffStmt.execute();
        cutoffResult.next();
        var cutoffTs = cutoffResult.getColumnValue(1);
        result.cutoff_timestamp = cutoffTs;
        
        // =====================================================================
        // STEP 1: PURGE - Delete old records beyond retention window
        // This prevents unbounded table growth (Vikas fix - 2026-01-26)
        // =====================================================================
        var purgeSQL = `
            DELETE FROM DEV_API_REF.FUSE.DRILL_CYCLE_INCR
            WHERE DW_MODIFY_TS < DATEADD(day, -${maxDays}, CURRENT_TIMESTAMP())
        `;
        var purgeStmt = snowflake.createStatement({sqlText: purgeSQL});
        purgeStmt.execute();
        result.rows_purged = purgeStmt.getNumRowsAffected();
        
        // =====================================================================
        // STEP 2: MERGE - Upsert new/updated records
        // =====================================================================
        // MERGE statement with hash-based conditional updates
        var mergeSQL = `
            MERGE INTO DEV_API_REF.FUSE.DRILL_CYCLE_INCR AS TGT
            USING (
                SELECT 
                    DRILL_CYCLE_SK,
                    ORIG_SRC_ID,
                    SITE_CODE,
                    BENCH,
                    PUSHBACK,
                    PATTERN_NAME,
                    ORIGINAL_PATTERN_NAME,
                    DRILL_HOLE_SHIFT_ID,
                    DRILL_ID,
                    DRILL_BIT_ID,
                    SYSTEM_OPERATOR_ID,
                    DRILL_HOLE_ID,
                    DRILL_HOLE_NAME,
                    DRILL_PLAN_SK,
                    DRILL_HOLE_STATUS,
                    IS_HOLE_PLANNED_FLAG,
                    START_HOLE_TS_UTC,
                    END_HOLE_TS_UTC,
                    OPERATOR_LOGIN_TS_UTC,
                    OPERATOR_LOGOUT_TS_UTC,
                    PROPEL_START_TS_UTC,
                    PROPEL_END_TS_UTC,
                    PARK_POSITION_START_TS_UTC,
                    PARK_POSITION_END_TS_UTC,
                    LEVEL_START_TS_UTC,
                    LEVEL_END_TS_UTC,
                    DRILL_START_TS_UTC,
                    DRILL_END_TS_UTC,
                    RETRACT_START_TS_UTC,
                    RETRACT_END_TS_UTC,
                    START_HOLE_TS_LOCAL,
                    END_HOLE_TS_LOCAL,
                    OPERATOR_LOGIN_TS_LOCAL,
                    OPERATOR_LOGOUT_TS_LOCAL,
                    PROPEL_START_TS_LOCAL,
                    PROPEL_END_TS_LOCAL,
                    PARK_POSITION_START_TS_LOCAL,
                    PARK_POSITION_END_TS_LOCAL,
                    LEVEL_START_TS_LOCAL,
                    LEVEL_END_TS_LOCAL,
                    DRILL_START_TS_LOCAL,
                    DRILL_END_TS_LOCAL,
                    RETRACT_START_TS_LOCAL,
                    RETRACT_END_TS_LOCAL,
                    PLAN_CREATION_TS_LOCAL,
                    DRILL_HOLE_DURATION_SECONDS,
                    AUTODRILL_DURATION_SECONDS,
                    TIME_BETWEEN_DRILL_HOLES_SECONDS,
                    SYSTEM_DRILL_STATE_DURATION_SECONDS,
                    SYSTEM_SETUP_STATE_DURATION_SECONDS,
                    SYSTEM_AUTO_LEVEL_DURATION_SECONDS,
                    SYSTEM_AUTO_DELEVEL_DURATION_SECONDS,
                    PROPEL_DURATION,
                    PARK_POSITION_DURATION,
                    LEVEL_DURATION,
                    DRILL_DURATION,
                    RETRACT_DURATION,
                    ACTUAL_DRILL_HOLE_DEPTH_FEET,
                    ACTUAL_DRILL_HOLE_DEPTH_METERS,
                    ACTUAL_DRILL_HOLE_START_FEET_X,
                    ACTUAL_DRILL_HOLE_START_FEET_Y,
                    ACTUAL_DRILL_HOLE_START_FEET_Z,
                    ACTUAL_DRILL_HOLE_END_FEET_X,
                    ACTUAL_DRILL_HOLE_END_FEET_Y,
                    ACTUAL_DRILL_HOLE_END_FEET_Z,
                    ACTUAL_DRILL_HOLE_START_METERS_X,
                    ACTUAL_DRILL_HOLE_START_METERS_Y,
                    ACTUAL_DRILL_HOLE_START_METERS_Z,
                    ACTUAL_DRILL_HOLE_END_METERS_X,
                    ACTUAL_DRILL_HOLE_END_METERS_Y,
                    ACTUAL_DRILL_HOLE_END_METERS_Z,
                    GPS_ACCURACY,
                    ACTUAL_DRILL_HOLE_LONGITUDE,
                    ACTUAL_DRILL_HOLE_LATITUDE,
                    AUTODRILL_USAGE_PCT,
                    DRILL_HOLE_PENETRATION_RATE_AVG_FEET_HOUR,
                    INSTANTANOUS_PENRATE_MWD_METERS_HOUR,
                    INSTANTANOUS_PENRATE_MWD_FEET_HOUR,
                    BEARING,
                    DRILL_TOWER_ANGLE_DEGREE_CALCULATED,
                    DRILL_TOWER_ANGLE_DEGREE_SYSTEM,
                    DRILL_HOLE_DUPLICATED_FLAG,
                    DRILL_HOLE_UPSIDE_DOWN_FLAG,
                    DRILL_HOLE_START_END_TIME_INVALID_FLAG,
                    DRILL_HOLE_START_END_TIME_OVERLAP_FLAG,
                    DRILL_HOLE_DEPTH_INVALID_FLAG,
                    DRILL_HOLE_ANGLE_INVALID_FLAG,
                    DRILL_HOLE_POSITION_INVALID_FLAG,
                    DRILL_HOLE_OFF_TARGET_FEET,
                    DRILL_HOLE_OFF_TARGET_METERS,
                    DRILL_HOLE_HORIZONTAL_ACCURACY_PCT,
                    DRILL_HOLE_VERTICAL_ACCURACY_PCT,
                    OVERDRILL_UNDERDRILL_FLAG,
                    OVERDRILL_UNDERDRILL_FEET,
                    OVERDRILL_UNDERDRILL_METERS,
                    DRILLING_STOPS_COUNT,
                    DRILL_HOLE_REDRILL_FLAG,
                    AIR_PRESSURE_PSI,
                    FEED_FORCE_NEWTONS,
                    ROTATION_TORQUE_NM,
                    BIT_SPEED_RPM,
                    WATER_FLOW_GPM,
                    ACTUAL_MCF_BLOCK_ID,
                    DESIGN_MCF_BLOCK_ID,
                    SYSTEM_VERSION,
                    TRY_TO_TIMESTAMP(DW_LOAD_TS)    AS DW_LOAD_TS,
                    TRY_TO_TIMESTAMP(DW_MODIFY_TS)  AS DW_MODIFY_TS,
                    'N'                             AS DW_LOGICAL_DELETE_FLAG,
                    SHA2(CONCAT_WS('|',
                        COALESCE(CAST(DRILL_CYCLE_SK AS VARCHAR), ''),
                        COALESCE(CAST(ORIG_SRC_ID AS VARCHAR), ''),
                        COALESCE(SITE_CODE, ''),
                        COALESCE(PATTERN_NAME, ''),
                        COALESCE(DRILL_HOLE_NAME, ''),
                        COALESCE(CAST(DRILL_HOLE_STATUS AS VARCHAR), ''),
                        COALESCE(START_HOLE_TS_UTC, ''),
                        COALESCE(END_HOLE_TS_UTC, ''),
                        COALESCE(CAST(ACTUAL_DRILL_HOLE_DEPTH_METERS AS VARCHAR), ''),
                        COALESCE(CAST(DRILL_HOLE_DURATION_SECONDS AS VARCHAR), ''),
                        COALESCE(CAST(OVERDRILL_UNDERDRILL_FLAG AS VARCHAR), '')
                    ), 256) AS DW_ROW_HASH
                FROM PROD_WG.DRILL_BLAST.DRILL_CYCLE
                WHERE TRY_TO_TIMESTAMP(DW_MODIFY_TS) >= '${cutoffTs}'
            ) AS SRC
            ON TGT.DRILL_CYCLE_SK = SRC.DRILL_CYCLE_SK
            
            WHEN MATCHED AND TGT.DW_ROW_HASH != SRC.DW_ROW_HASH THEN UPDATE SET
                TGT.ORIG_SRC_ID = SRC.ORIG_SRC_ID,
                TGT.SITE_CODE = SRC.SITE_CODE,
                TGT.BENCH = SRC.BENCH,
                TGT.PUSHBACK = SRC.PUSHBACK,
                TGT.PATTERN_NAME = SRC.PATTERN_NAME,
                TGT.ORIGINAL_PATTERN_NAME = SRC.ORIGINAL_PATTERN_NAME,
                TGT.DRILL_HOLE_SHIFT_ID = SRC.DRILL_HOLE_SHIFT_ID,
                TGT.DRILL_ID = SRC.DRILL_ID,
                TGT.DRILL_BIT_ID = SRC.DRILL_BIT_ID,
                TGT.SYSTEM_OPERATOR_ID = SRC.SYSTEM_OPERATOR_ID,
                TGT.DRILL_HOLE_ID = SRC.DRILL_HOLE_ID,
                TGT.DRILL_HOLE_NAME = SRC.DRILL_HOLE_NAME,
                TGT.DRILL_PLAN_SK = SRC.DRILL_PLAN_SK,
                TGT.DRILL_HOLE_STATUS = SRC.DRILL_HOLE_STATUS,
                TGT.IS_HOLE_PLANNED_FLAG = SRC.IS_HOLE_PLANNED_FLAG,
                TGT.START_HOLE_TS_UTC = SRC.START_HOLE_TS_UTC,
                TGT.END_HOLE_TS_UTC = SRC.END_HOLE_TS_UTC,
                TGT.OPERATOR_LOGIN_TS_UTC = SRC.OPERATOR_LOGIN_TS_UTC,
                TGT.OPERATOR_LOGOUT_TS_UTC = SRC.OPERATOR_LOGOUT_TS_UTC,
                TGT.PROPEL_START_TS_UTC = SRC.PROPEL_START_TS_UTC,
                TGT.PROPEL_END_TS_UTC = SRC.PROPEL_END_TS_UTC,
                TGT.PARK_POSITION_START_TS_UTC = SRC.PARK_POSITION_START_TS_UTC,
                TGT.PARK_POSITION_END_TS_UTC = SRC.PARK_POSITION_END_TS_UTC,
                TGT.LEVEL_START_TS_UTC = SRC.LEVEL_START_TS_UTC,
                TGT.LEVEL_END_TS_UTC = SRC.LEVEL_END_TS_UTC,
                TGT.DRILL_START_TS_UTC = SRC.DRILL_START_TS_UTC,
                TGT.DRILL_END_TS_UTC = SRC.DRILL_END_TS_UTC,
                TGT.RETRACT_START_TS_UTC = SRC.RETRACT_START_TS_UTC,
                TGT.RETRACT_END_TS_UTC = SRC.RETRACT_END_TS_UTC,
                TGT.START_HOLE_TS_LOCAL = SRC.START_HOLE_TS_LOCAL,
                TGT.END_HOLE_TS_LOCAL = SRC.END_HOLE_TS_LOCAL,
                TGT.OPERATOR_LOGIN_TS_LOCAL = SRC.OPERATOR_LOGIN_TS_LOCAL,
                TGT.OPERATOR_LOGOUT_TS_LOCAL = SRC.OPERATOR_LOGOUT_TS_LOCAL,
                TGT.PROPEL_START_TS_LOCAL = SRC.PROPEL_START_TS_LOCAL,
                TGT.PROPEL_END_TS_LOCAL = SRC.PROPEL_END_TS_LOCAL,
                TGT.PARK_POSITION_START_TS_LOCAL = SRC.PARK_POSITION_START_TS_LOCAL,
                TGT.PARK_POSITION_END_TS_LOCAL = SRC.PARK_POSITION_END_TS_LOCAL,
                TGT.LEVEL_START_TS_LOCAL = SRC.LEVEL_START_TS_LOCAL,
                TGT.LEVEL_END_TS_LOCAL = SRC.LEVEL_END_TS_LOCAL,
                TGT.DRILL_START_TS_LOCAL = SRC.DRILL_START_TS_LOCAL,
                TGT.DRILL_END_TS_LOCAL = SRC.DRILL_END_TS_LOCAL,
                TGT.RETRACT_START_TS_LOCAL = SRC.RETRACT_START_TS_LOCAL,
                TGT.RETRACT_END_TS_LOCAL = SRC.RETRACT_END_TS_LOCAL,
                TGT.PLAN_CREATION_TS_LOCAL = SRC.PLAN_CREATION_TS_LOCAL,
                TGT.DRILL_HOLE_DURATION_SECONDS = SRC.DRILL_HOLE_DURATION_SECONDS,
                TGT.AUTODRILL_DURATION_SECONDS = SRC.AUTODRILL_DURATION_SECONDS,
                TGT.TIME_BETWEEN_DRILL_HOLES_SECONDS = SRC.TIME_BETWEEN_DRILL_HOLES_SECONDS,
                TGT.SYSTEM_DRILL_STATE_DURATION_SECONDS = SRC.SYSTEM_DRILL_STATE_DURATION_SECONDS,
                TGT.SYSTEM_SETUP_STATE_DURATION_SECONDS = SRC.SYSTEM_SETUP_STATE_DURATION_SECONDS,
                TGT.SYSTEM_AUTO_LEVEL_DURATION_SECONDS = SRC.SYSTEM_AUTO_LEVEL_DURATION_SECONDS,
                TGT.SYSTEM_AUTO_DELEVEL_DURATION_SECONDS = SRC.SYSTEM_AUTO_DELEVEL_DURATION_SECONDS,
                TGT.PROPEL_DURATION = SRC.PROPEL_DURATION,
                TGT.PARK_POSITION_DURATION = SRC.PARK_POSITION_DURATION,
                TGT.LEVEL_DURATION = SRC.LEVEL_DURATION,
                TGT.DRILL_DURATION = SRC.DRILL_DURATION,
                TGT.RETRACT_DURATION = SRC.RETRACT_DURATION,
                TGT.ACTUAL_DRILL_HOLE_DEPTH_FEET = SRC.ACTUAL_DRILL_HOLE_DEPTH_FEET,
                TGT.ACTUAL_DRILL_HOLE_DEPTH_METERS = SRC.ACTUAL_DRILL_HOLE_DEPTH_METERS,
                TGT.ACTUAL_DRILL_HOLE_START_FEET_X = SRC.ACTUAL_DRILL_HOLE_START_FEET_X,
                TGT.ACTUAL_DRILL_HOLE_START_FEET_Y = SRC.ACTUAL_DRILL_HOLE_START_FEET_Y,
                TGT.ACTUAL_DRILL_HOLE_START_FEET_Z = SRC.ACTUAL_DRILL_HOLE_START_FEET_Z,
                TGT.ACTUAL_DRILL_HOLE_END_FEET_X = SRC.ACTUAL_DRILL_HOLE_END_FEET_X,
                TGT.ACTUAL_DRILL_HOLE_END_FEET_Y = SRC.ACTUAL_DRILL_HOLE_END_FEET_Y,
                TGT.ACTUAL_DRILL_HOLE_END_FEET_Z = SRC.ACTUAL_DRILL_HOLE_END_FEET_Z,
                TGT.ACTUAL_DRILL_HOLE_START_METERS_X = SRC.ACTUAL_DRILL_HOLE_START_METERS_X,
                TGT.ACTUAL_DRILL_HOLE_START_METERS_Y = SRC.ACTUAL_DRILL_HOLE_START_METERS_Y,
                TGT.ACTUAL_DRILL_HOLE_START_METERS_Z = SRC.ACTUAL_DRILL_HOLE_START_METERS_Z,
                TGT.ACTUAL_DRILL_HOLE_END_METERS_X = SRC.ACTUAL_DRILL_HOLE_END_METERS_X,
                TGT.ACTUAL_DRILL_HOLE_END_METERS_Y = SRC.ACTUAL_DRILL_HOLE_END_METERS_Y,
                TGT.ACTUAL_DRILL_HOLE_END_METERS_Z = SRC.ACTUAL_DRILL_HOLE_END_METERS_Z,
                TGT.GPS_ACCURACY = SRC.GPS_ACCURACY,
                TGT.ACTUAL_DRILL_HOLE_LONGITUDE = SRC.ACTUAL_DRILL_HOLE_LONGITUDE,
                TGT.ACTUAL_DRILL_HOLE_LATITUDE = SRC.ACTUAL_DRILL_HOLE_LATITUDE,
                TGT.AUTODRILL_USAGE_PCT = SRC.AUTODRILL_USAGE_PCT,
                TGT.DRILL_HOLE_PENETRATION_RATE_AVG_FEET_HOUR = SRC.DRILL_HOLE_PENETRATION_RATE_AVG_FEET_HOUR,
                TGT.INSTANTANOUS_PENRATE_MWD_METERS_HOUR = SRC.INSTANTANOUS_PENRATE_MWD_METERS_HOUR,
                TGT.INSTANTANOUS_PENRATE_MWD_FEET_HOUR = SRC.INSTANTANOUS_PENRATE_MWD_FEET_HOUR,
                TGT.BEARING = SRC.BEARING,
                TGT.DRILL_TOWER_ANGLE_DEGREE_CALCULATED = SRC.DRILL_TOWER_ANGLE_DEGREE_CALCULATED,
                TGT.DRILL_TOWER_ANGLE_DEGREE_SYSTEM = SRC.DRILL_TOWER_ANGLE_DEGREE_SYSTEM,
                TGT.DRILL_HOLE_DUPLICATED_FLAG = SRC.DRILL_HOLE_DUPLICATED_FLAG,
                TGT.DRILL_HOLE_UPSIDE_DOWN_FLAG = SRC.DRILL_HOLE_UPSIDE_DOWN_FLAG,
                TGT.DRILL_HOLE_START_END_TIME_INVALID_FLAG = SRC.DRILL_HOLE_START_END_TIME_INVALID_FLAG,
                TGT.DRILL_HOLE_START_END_TIME_OVERLAP_FLAG = SRC.DRILL_HOLE_START_END_TIME_OVERLAP_FLAG,
                TGT.DRILL_HOLE_DEPTH_INVALID_FLAG = SRC.DRILL_HOLE_DEPTH_INVALID_FLAG,
                TGT.DRILL_HOLE_ANGLE_INVALID_FLAG = SRC.DRILL_HOLE_ANGLE_INVALID_FLAG,
                TGT.DRILL_HOLE_POSITION_INVALID_FLAG = SRC.DRILL_HOLE_POSITION_INVALID_FLAG,
                TGT.DRILL_HOLE_OFF_TARGET_FEET = SRC.DRILL_HOLE_OFF_TARGET_FEET,
                TGT.DRILL_HOLE_OFF_TARGET_METERS = SRC.DRILL_HOLE_OFF_TARGET_METERS,
                TGT.DRILL_HOLE_HORIZONTAL_ACCURACY_PCT = SRC.DRILL_HOLE_HORIZONTAL_ACCURACY_PCT,
                TGT.DRILL_HOLE_VERTICAL_ACCURACY_PCT = SRC.DRILL_HOLE_VERTICAL_ACCURACY_PCT,
                TGT.OVERDRILL_UNDERDRILL_FLAG = SRC.OVERDRILL_UNDERDRILL_FLAG,
                TGT.OVERDRILL_UNDERDRILL_FEET = SRC.OVERDRILL_UNDERDRILL_FEET,
                TGT.OVERDRILL_UNDERDRILL_METERS = SRC.OVERDRILL_UNDERDRILL_METERS,
                TGT.DRILLING_STOPS_COUNT = SRC.DRILLING_STOPS_COUNT,
                TGT.DRILL_HOLE_REDRILL_FLAG = SRC.DRILL_HOLE_REDRILL_FLAG,
                TGT.AIR_PRESSURE_PSI = SRC.AIR_PRESSURE_PSI,
                TGT.FEED_FORCE_NEWTONS = SRC.FEED_FORCE_NEWTONS,
                TGT.ROTATION_TORQUE_NM = SRC.ROTATION_TORQUE_NM,
                TGT.BIT_SPEED_RPM = SRC.BIT_SPEED_RPM,
                TGT.WATER_FLOW_GPM = SRC.WATER_FLOW_GPM,
                TGT.ACTUAL_MCF_BLOCK_ID = SRC.ACTUAL_MCF_BLOCK_ID,
                TGT.DESIGN_MCF_BLOCK_ID = SRC.DESIGN_MCF_BLOCK_ID,
                TGT.SYSTEM_VERSION = SRC.SYSTEM_VERSION,
                TGT.DW_LOAD_TS = SRC.DW_LOAD_TS,
                TGT.DW_MODIFY_TS = SRC.DW_MODIFY_TS,
                TGT.DW_LOGICAL_DELETE_FLAG = SRC.DW_LOGICAL_DELETE_FLAG,
                TGT.DW_ROW_HASH = SRC.DW_ROW_HASH
            
            WHEN NOT MATCHED THEN INSERT (
                DRILL_CYCLE_SK, ORIG_SRC_ID, SITE_CODE, BENCH, PUSHBACK, PATTERN_NAME, ORIGINAL_PATTERN_NAME,
                DRILL_HOLE_SHIFT_ID, DRILL_ID, DRILL_BIT_ID, SYSTEM_OPERATOR_ID, DRILL_HOLE_ID, DRILL_HOLE_NAME,
                DRILL_PLAN_SK, DRILL_HOLE_STATUS, IS_HOLE_PLANNED_FLAG, START_HOLE_TS_UTC, END_HOLE_TS_UTC,
                OPERATOR_LOGIN_TS_UTC, OPERATOR_LOGOUT_TS_UTC, PROPEL_START_TS_UTC, PROPEL_END_TS_UTC,
                PARK_POSITION_START_TS_UTC, PARK_POSITION_END_TS_UTC, LEVEL_START_TS_UTC, LEVEL_END_TS_UTC,
                DRILL_START_TS_UTC, DRILL_END_TS_UTC, RETRACT_START_TS_UTC, RETRACT_END_TS_UTC,
                START_HOLE_TS_LOCAL, END_HOLE_TS_LOCAL, OPERATOR_LOGIN_TS_LOCAL, OPERATOR_LOGOUT_TS_LOCAL,
                PROPEL_START_TS_LOCAL, PROPEL_END_TS_LOCAL, PARK_POSITION_START_TS_LOCAL, PARK_POSITION_END_TS_LOCAL,
                LEVEL_START_TS_LOCAL, LEVEL_END_TS_LOCAL, DRILL_START_TS_LOCAL, DRILL_END_TS_LOCAL,
                RETRACT_START_TS_LOCAL, RETRACT_END_TS_LOCAL, PLAN_CREATION_TS_LOCAL,
                DRILL_HOLE_DURATION_SECONDS, AUTODRILL_DURATION_SECONDS, TIME_BETWEEN_DRILL_HOLES_SECONDS,
                SYSTEM_DRILL_STATE_DURATION_SECONDS, SYSTEM_SETUP_STATE_DURATION_SECONDS,
                SYSTEM_AUTO_LEVEL_DURATION_SECONDS, SYSTEM_AUTO_DELEVEL_DURATION_SECONDS,
                PROPEL_DURATION, PARK_POSITION_DURATION, LEVEL_DURATION, DRILL_DURATION, RETRACT_DURATION,
                ACTUAL_DRILL_HOLE_DEPTH_FEET, ACTUAL_DRILL_HOLE_DEPTH_METERS,
                ACTUAL_DRILL_HOLE_START_FEET_X, ACTUAL_DRILL_HOLE_START_FEET_Y, ACTUAL_DRILL_HOLE_START_FEET_Z,
                ACTUAL_DRILL_HOLE_END_FEET_X, ACTUAL_DRILL_HOLE_END_FEET_Y, ACTUAL_DRILL_HOLE_END_FEET_Z,
                ACTUAL_DRILL_HOLE_START_METERS_X, ACTUAL_DRILL_HOLE_START_METERS_Y, ACTUAL_DRILL_HOLE_START_METERS_Z,
                ACTUAL_DRILL_HOLE_END_METERS_X, ACTUAL_DRILL_HOLE_END_METERS_Y, ACTUAL_DRILL_HOLE_END_METERS_Z,
                GPS_ACCURACY, ACTUAL_DRILL_HOLE_LONGITUDE, ACTUAL_DRILL_HOLE_LATITUDE, AUTODRILL_USAGE_PCT,
                DRILL_HOLE_PENETRATION_RATE_AVG_FEET_HOUR, INSTANTANOUS_PENRATE_MWD_METERS_HOUR,
                INSTANTANOUS_PENRATE_MWD_FEET_HOUR, BEARING, DRILL_TOWER_ANGLE_DEGREE_CALCULATED,
                DRILL_TOWER_ANGLE_DEGREE_SYSTEM, DRILL_HOLE_DUPLICATED_FLAG, DRILL_HOLE_UPSIDE_DOWN_FLAG,
                DRILL_HOLE_START_END_TIME_INVALID_FLAG, DRILL_HOLE_START_END_TIME_OVERLAP_FLAG,
                DRILL_HOLE_DEPTH_INVALID_FLAG, DRILL_HOLE_ANGLE_INVALID_FLAG, DRILL_HOLE_POSITION_INVALID_FLAG,
                DRILL_HOLE_OFF_TARGET_FEET, DRILL_HOLE_OFF_TARGET_METERS, DRILL_HOLE_HORIZONTAL_ACCURACY_PCT,
                DRILL_HOLE_VERTICAL_ACCURACY_PCT, OVERDRILL_UNDERDRILL_FLAG, OVERDRILL_UNDERDRILL_FEET,
                OVERDRILL_UNDERDRILL_METERS, DRILLING_STOPS_COUNT, DRILL_HOLE_REDRILL_FLAG,
                AIR_PRESSURE_PSI, FEED_FORCE_NEWTONS, ROTATION_TORQUE_NM, BIT_SPEED_RPM, WATER_FLOW_GPM,
                ACTUAL_MCF_BLOCK_ID, DESIGN_MCF_BLOCK_ID, SYSTEM_VERSION,
                DW_LOAD_TS, DW_MODIFY_TS, DW_LOGICAL_DELETE_FLAG, DW_ROW_HASH
            ) VALUES (
                SRC.DRILL_CYCLE_SK, SRC.ORIG_SRC_ID, SRC.SITE_CODE, SRC.BENCH, SRC.PUSHBACK, SRC.PATTERN_NAME,
                SRC.ORIGINAL_PATTERN_NAME, SRC.DRILL_HOLE_SHIFT_ID, SRC.DRILL_ID, SRC.DRILL_BIT_ID,
                SRC.SYSTEM_OPERATOR_ID, SRC.DRILL_HOLE_ID, SRC.DRILL_HOLE_NAME, SRC.DRILL_PLAN_SK,
                SRC.DRILL_HOLE_STATUS, SRC.IS_HOLE_PLANNED_FLAG, SRC.START_HOLE_TS_UTC, SRC.END_HOLE_TS_UTC,
                SRC.OPERATOR_LOGIN_TS_UTC, SRC.OPERATOR_LOGOUT_TS_UTC, SRC.PROPEL_START_TS_UTC, SRC.PROPEL_END_TS_UTC,
                SRC.PARK_POSITION_START_TS_UTC, SRC.PARK_POSITION_END_TS_UTC, SRC.LEVEL_START_TS_UTC,
                SRC.LEVEL_END_TS_UTC, SRC.DRILL_START_TS_UTC, SRC.DRILL_END_TS_UTC, SRC.RETRACT_START_TS_UTC,
                SRC.RETRACT_END_TS_UTC, SRC.START_HOLE_TS_LOCAL, SRC.END_HOLE_TS_LOCAL, SRC.OPERATOR_LOGIN_TS_LOCAL,
                SRC.OPERATOR_LOGOUT_TS_LOCAL, SRC.PROPEL_START_TS_LOCAL, SRC.PROPEL_END_TS_LOCAL,
                SRC.PARK_POSITION_START_TS_LOCAL, SRC.PARK_POSITION_END_TS_LOCAL, SRC.LEVEL_START_TS_LOCAL,
                SRC.LEVEL_END_TS_LOCAL, SRC.DRILL_START_TS_LOCAL, SRC.DRILL_END_TS_LOCAL, SRC.RETRACT_START_TS_LOCAL,
                SRC.RETRACT_END_TS_LOCAL, SRC.PLAN_CREATION_TS_LOCAL, SRC.DRILL_HOLE_DURATION_SECONDS,
                SRC.AUTODRILL_DURATION_SECONDS, SRC.TIME_BETWEEN_DRILL_HOLES_SECONDS,
                SRC.SYSTEM_DRILL_STATE_DURATION_SECONDS, SRC.SYSTEM_SETUP_STATE_DURATION_SECONDS,
                SRC.SYSTEM_AUTO_LEVEL_DURATION_SECONDS, SRC.SYSTEM_AUTO_DELEVEL_DURATION_SECONDS,
                SRC.PROPEL_DURATION, SRC.PARK_POSITION_DURATION, SRC.LEVEL_DURATION, SRC.DRILL_DURATION,
                SRC.RETRACT_DURATION, SRC.ACTUAL_DRILL_HOLE_DEPTH_FEET, SRC.ACTUAL_DRILL_HOLE_DEPTH_METERS,
                SRC.ACTUAL_DRILL_HOLE_START_FEET_X, SRC.ACTUAL_DRILL_HOLE_START_FEET_Y, SRC.ACTUAL_DRILL_HOLE_START_FEET_Z,
                SRC.ACTUAL_DRILL_HOLE_END_FEET_X, SRC.ACTUAL_DRILL_HOLE_END_FEET_Y, SRC.ACTUAL_DRILL_HOLE_END_FEET_Z,
                SRC.ACTUAL_DRILL_HOLE_START_METERS_X, SRC.ACTUAL_DRILL_HOLE_START_METERS_Y,
                SRC.ACTUAL_DRILL_HOLE_START_METERS_Z, SRC.ACTUAL_DRILL_HOLE_END_METERS_X,
                SRC.ACTUAL_DRILL_HOLE_END_METERS_Y, SRC.ACTUAL_DRILL_HOLE_END_METERS_Z, SRC.GPS_ACCURACY,
                SRC.ACTUAL_DRILL_HOLE_LONGITUDE, SRC.ACTUAL_DRILL_HOLE_LATITUDE, SRC.AUTODRILL_USAGE_PCT,
                SRC.DRILL_HOLE_PENETRATION_RATE_AVG_FEET_HOUR, SRC.INSTANTANOUS_PENRATE_MWD_METERS_HOUR,
                SRC.INSTANTANOUS_PENRATE_MWD_FEET_HOUR, SRC.BEARING, SRC.DRILL_TOWER_ANGLE_DEGREE_CALCULATED,
                SRC.DRILL_TOWER_ANGLE_DEGREE_SYSTEM, SRC.DRILL_HOLE_DUPLICATED_FLAG, SRC.DRILL_HOLE_UPSIDE_DOWN_FLAG,
                SRC.DRILL_HOLE_START_END_TIME_INVALID_FLAG, SRC.DRILL_HOLE_START_END_TIME_OVERLAP_FLAG,
                SRC.DRILL_HOLE_DEPTH_INVALID_FLAG, SRC.DRILL_HOLE_ANGLE_INVALID_FLAG,
                SRC.DRILL_HOLE_POSITION_INVALID_FLAG, SRC.DRILL_HOLE_OFF_TARGET_FEET, SRC.DRILL_HOLE_OFF_TARGET_METERS,
                SRC.DRILL_HOLE_HORIZONTAL_ACCURACY_PCT, SRC.DRILL_HOLE_VERTICAL_ACCURACY_PCT,
                SRC.OVERDRILL_UNDERDRILL_FLAG, SRC.OVERDRILL_UNDERDRILL_FEET, SRC.OVERDRILL_UNDERDRILL_METERS,
                SRC.DRILLING_STOPS_COUNT, SRC.DRILL_HOLE_REDRILL_FLAG, SRC.AIR_PRESSURE_PSI,
                SRC.FEED_FORCE_NEWTONS, SRC.ROTATION_TORQUE_NM, SRC.BIT_SPEED_RPM, SRC.WATER_FLOW_GPM,
                SRC.ACTUAL_MCF_BLOCK_ID, SRC.DESIGN_MCF_BLOCK_ID, SRC.SYSTEM_VERSION,
                SRC.DW_LOAD_TS, SRC.DW_MODIFY_TS, SRC.DW_LOGICAL_DELETE_FLAG, SRC.DW_ROW_HASH
            )
        `;
        
        var mergeStmt = snowflake.createStatement({sqlText: mergeSQL});
        var mergeResult = mergeStmt.execute();
        mergeResult.next();
        result.rows_merged = mergeStmt.getNumRowsAffected();
        
        // Handle soft deletes for records no longer in source
        var softDeleteSQL = `
            UPDATE DEV_API_REF.FUSE.DRILL_CYCLE_INCR
            SET DW_LOGICAL_DELETE_FLAG = 'Y',
                DW_MODIFY_TS = CURRENT_TIMESTAMP()
            WHERE DRILL_CYCLE_SK NOT IN (
                SELECT DRILL_CYCLE_SK FROM PROD_WG.DRILL_BLAST.DRILL_CYCLE
            )
            AND DW_LOGICAL_DELETE_FLAG = 'N'
        `;
        
        var softDeleteStmt = snowflake.createStatement({sqlText: softDeleteSQL});
        softDeleteStmt.execute();
        result.rows_soft_deleted = softDeleteStmt.getNumRowsAffected();
        
        result.end_time = new Date().toISOString();
        
    } catch (err) {
        result.status = 'FAILED';
        result.error_message = err.message;
        result.end_time = new Date().toISOString();
    }
    
    return result;
$$;

-- =============================================================================
-- USAGE EXAMPLES
-- =============================================================================
-- Default execution (3 days lookback)
-- CALL DEV_API_REF.FUSE.DRILL_CYCLE_INCR_P();

-- Custom lookback period
-- CALL DEV_API_REF.FUSE.DRILL_CYCLE_INCR_P(7, 30);

-- Full reload (30 days max)
-- CALL DEV_API_REF.FUSE.DRILL_CYCLE_INCR_P(30, 30);
