-- ============================================================================
-- DRILLBLAST INCR Pipeline - E2E Verification Test
-- ============================================================================
-- Purpose: Verify all 14 INCR tables have data (no empty tables)
-- Environment: DEV_API_REF.FUSE
-- Date: 2026-01-29
-- Author: Carlos Carrillo
-- ============================================================================

USE ROLE DEV_API_REF_FR;
USE WAREHOUSE DEV_WH;
USE DATABASE DEV_API_REF;
USE SCHEMA FUSE;

-- ============================================================================
-- TEST 1: VERIFY ALL INCR TABLES EXIST AND HAVE DATA
-- ============================================================================
SELECT 
    'TEST RESULTS - DRILLBLAST INCR TABLES' AS test_name,
    CURRENT_TIMESTAMP() AS test_time;

SELECT 
    table_name,
    row_count,
    CASE WHEN row_count > 0 THEN 'PASS' ELSE 'FAIL - EMPTY TABLE!' END AS status
FROM (
    SELECT 'BLAST_PLAN_INCR' AS table_name, (SELECT COUNT(*) FROM BLAST_PLAN_INCR) AS row_count
    UNION ALL SELECT 'BLAST_PLAN_EXECUTION_INCR', (SELECT COUNT(*) FROM BLAST_PLAN_EXECUTION_INCR)
    UNION ALL SELECT 'BL_DW_BLAST_INCR', (SELECT COUNT(*) FROM BL_DW_BLAST_INCR)
    UNION ALL SELECT 'BL_DW_BLASTPROPERTYVALUE_INCR', (SELECT COUNT(*) FROM BL_DW_BLASTPROPERTYVALUE_INCR)
    UNION ALL SELECT 'BL_DW_HOLE_INCR', (SELECT COUNT(*) FROM BL_DW_HOLE_INCR)
    UNION ALL SELECT 'DRILLBLAST_EQUIPMENT_INCR', (SELECT COUNT(*) FROM DRILLBLAST_EQUIPMENT_INCR)
    UNION ALL SELECT 'DRILLBLAST_OPERATOR_INCR', (SELECT COUNT(*) FROM DRILLBLAST_OPERATOR_INCR)
    UNION ALL SELECT 'DRILLBLAST_SHIFT_INCR', (SELECT COUNT(*) FROM DRILLBLAST_SHIFT_INCR)
    UNION ALL SELECT 'DRILL_CYCLE_INCR', (SELECT COUNT(*) FROM DRILL_CYCLE_INCR)
    UNION ALL SELECT 'DRILL_PLAN_INCR', (SELECT COUNT(*) FROM DRILL_PLAN_INCR)
    UNION ALL SELECT 'LH_BUCKET_INCR', (SELECT COUNT(*) FROM LH_BUCKET_INCR)
    UNION ALL SELECT 'LH_EQUIPMENT_STATUS_EVENT_INCR', (SELECT COUNT(*) FROM LH_EQUIPMENT_STATUS_EVENT_INCR)
    UNION ALL SELECT 'LH_HAUL_CYCLE_INCR', (SELECT COUNT(*) FROM LH_HAUL_CYCLE_INCR)
    UNION ALL SELECT 'LH_LOADING_CYCLE_INCR', (SELECT COUNT(*) FROM LH_LOADING_CYCLE_INCR)
)
ORDER BY table_name;

-- ============================================================================
-- TEST 2: VERIFY ALL INCR PROCEDURES EXIST
-- ============================================================================
SELECT 
    'PROCEDURE VERIFICATION' AS test_name,
    COUNT(*) AS procedure_count,
    CASE WHEN COUNT(*) = 14 THEN 'PASS' ELSE 'FAIL - MISSING PROCEDURES!' END AS status
FROM INFORMATION_SCHEMA.PROCEDURES 
WHERE PROCEDURE_SCHEMA = 'FUSE' 
AND PROCEDURE_NAME LIKE '%_INCR_P';

-- ============================================================================
-- TEST 3: SUMMARY
-- ============================================================================
SELECT 
    'SUMMARY' AS section,
    SUM(CASE WHEN row_count > 0 THEN 1 ELSE 0 END) AS tables_with_data,
    SUM(CASE WHEN row_count = 0 THEN 1 ELSE 0 END) AS empty_tables,
    CASE WHEN SUM(CASE WHEN row_count = 0 THEN 1 ELSE 0 END) = 0 
         THEN '✅ ALL TESTS PASSED - NO EMPTY TABLES' 
         ELSE '❌ FAILED - EMPTY TABLES DETECTED' 
    END AS final_result
FROM (
    SELECT (SELECT COUNT(*) FROM BLAST_PLAN_INCR) AS row_count
    UNION ALL SELECT (SELECT COUNT(*) FROM BLAST_PLAN_EXECUTION_INCR)
    UNION ALL SELECT (SELECT COUNT(*) FROM BL_DW_BLAST_INCR)
    UNION ALL SELECT (SELECT COUNT(*) FROM BL_DW_BLASTPROPERTYVALUE_INCR)
    UNION ALL SELECT (SELECT COUNT(*) FROM BL_DW_HOLE_INCR)
    UNION ALL SELECT (SELECT COUNT(*) FROM DRILLBLAST_EQUIPMENT_INCR)
    UNION ALL SELECT (SELECT COUNT(*) FROM DRILLBLAST_OPERATOR_INCR)
    UNION ALL SELECT (SELECT COUNT(*) FROM DRILLBLAST_SHIFT_INCR)
    UNION ALL SELECT (SELECT COUNT(*) FROM DRILL_CYCLE_INCR)
    UNION ALL SELECT (SELECT COUNT(*) FROM DRILL_PLAN_INCR)
    UNION ALL SELECT (SELECT COUNT(*) FROM LH_BUCKET_INCR)
    UNION ALL SELECT (SELECT COUNT(*) FROM LH_EQUIPMENT_STATUS_EVENT_INCR)
    UNION ALL SELECT (SELECT COUNT(*) FROM LH_HAUL_CYCLE_INCR)
    UNION ALL SELECT (SELECT COUNT(*) FROM LH_LOADING_CYCLE_INCR)
);
