CREATE VIEW [CHI].[CONOPS_CHI_CM_INTERMEDIATE_STOCKPILE_V] AS


  
  
--SELECT * FROM [chi].[CONOPS_CHI_CM_INTERMEDIATE_STOCKPILE_V] WITH (NOLOCK) WHERE SHIFTFLAG = 'CURR'    
CREATE VIEW [chi].[CONOPS_CHI_CM_INTERMEDIATE_STOCKPILE_V]    
AS    

WITH CTE AS (
SELECT 
	shiftindex,
	CRUSHERLOC,
	COMPONENT,
	SENSORVALUE,
ROW_NUMBER() OVER (PARTITION BY SHIFTINDEX,CRUSHERLOC,COMPONENT ORDER BY VALUE_TS DESC) NUM
FROM [dbo].[IOS_STOCKPILE_LEVELS] WITH (NOLOCK)
WHERE SITEFLAG = 'CHI'
),

MFLStockpile AS(
SELECT
	SHIFTINDEX,
	SENSORVALUE AS MFLStockpile
FROM CTE
WHERE CRUSHERLOC = '' 
	AND COMPONENT = ''
	AND NUM = 1
),

MillStockpile AS(
SELECT
	SHIFTINDEX,
	SENSORVALUE AS MillStockpile
FROM CTE
WHERE CRUSHERLOC = '' 
	AND COMPONENT = ''
	AND NUM = 1
)


SELECT 
a.[SITEFLAG]
,a.[SHIFTFLAG]
,0 AS [MFLStockpile] --MFL should be hidden/ not shown for CHIdad, Chino, Sierrita, CHIro Verde, Tyrone (only El Abra, Safford and Morenci have MFL)
,0 AS [MillStockpile]
FROM [CHI].[CONOPS_CHI_SHIFT_INFO_V] a WITH (NOLOCK)
LEFT JOIN MFLStockpile [s] WITH (NOLOCK) 
	ON a.SHIFTINDEX = [s].SHIFTINDEX
LEFT JOIN MillStockpile [m] WITH (NOLOCK) 
ON a.SHIFTINDEX = [m].SHIFTINDEX

  
  


