CREATE VIEW [CHI].[SHIFT_OPER] AS




--SELECT * FROM CHI.SHIFT_OPER
CREATE VIEW CHI.SHIFT_OPER
AS

SELECT
'CHI' AS SiteFlag,
*
FROM CHNOperational.dbo.SHIFTShiftOper WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM CHI.SHIFT_INFO)




