




  
  
/******************************************************************    
* PROCEDURE : [BAG].[UPSERT_CONOPS_PLAN_VALUES]   
* PURPOSE : Upsert [UPSERT_CONOPS_PLAN_VALUES]  
* NOTES     :   
* CREATED : mfahmi  
* SAMPLE    : EXEC BAG.[UPSERT_CONOPS_PLAN_VALUES]  
* MODIFIED DATE  AUTHOR    DESCRIPTION    
*------------------------------------------------------------------    
* {01 DEC 2022}  {mfahmi}   {Initial Created}    
* {01 MAR 2023}  {MFAHMI}   {ADD COLUMN SITEFLAG}
* {06 NOV 2023}  {GGOSAL1}  {ADD NEW COLUMN: DELTA C}
* {05 DEC 2023}  {GGOSAL1}  {Add: update table monitoring}
*******************************************************************/    
CREATE  PROCEDURE [bag].[UPSERT_CONOPS_PLAN_VALUES]  
AS  
BEGIN  
  
MERGE BAG.PLAN_VALUES AS T   
USING (SELECT 
'BAG' AS SITEFLAG,
CASE WHEN RIGHT(shiftid,1) = 1 
THEN CONCAT(RIGHT(REPLACE(CAST(LEFT(shiftid, LEN(shiftid) - CHARINDEX('/', REVERSE(shiftid))) AS DATE),'-',''),6),'001')
ELSE CONCAT(RIGHT(REPLACE(CAST(LEFT(shiftid, LEN(shiftid) - CHARINDEX('/', REVERSE(shiftid))) AS DATE),'-',''),6),'002')
END AS FORMATSHIFTID,
CONTENTTYPEID,
SHIFTID,
COMPLIANCEASSETID,
TOTALMINED,
L01ORE,
L01WASTEOXIDE,
L05ORE,
L05WASTEOXIDE,
S08ORE,
S08WASTEOXIDE,
S10ORE,
S10WASTEOXIDE,
S11ORE,
S11WASTEOXIDE,
S12ORE,
S12WASTEOXIDE,
S22ORE,
S22WASTEOXIDE,
S23ORE,
S23WASTEOXIDE,
REHANDLE,
W3TONS,
E3TONS,
N1TONS,
N2TONS,
N3TONS,
S4TONS,
TOTALEXPITTONS,
EFH,
CRUSHER2,
QUEUEDELTACTARGET,
SPOTTINGDELTACTARGET,
LOADINGDELTACTARGET,
LOADEDTRAVELDELTACTARGET,
DUMPINGDELTACTARGET,
STOCKPILETARGETS,
DUMPINGATCRUSHER,
EMPTYTRAVELDELTACTARGET,
ID,
CONTENTTYPE,
MODIFIED,
CREATED,
CREATEDBYID,
MODIFIEDBYID,
OWSHIDDENVERSION,
VERSION,
PATH,
getutcdate() UTC_CREATED_DATE   
 FROM BAG.PLAN_VALUES_stg) AS S   
 ON (T.Id = S.Id AND T.SITEFLAG = S.SITEFLAG)   
  
 WHEN MATCHED   
 THEN UPDATE SET  
 T.FORMATSHIFTID = S.FORMATSHIFTID
,T.CONTENTTYPEID = S.CONTENTTYPEID
,T.SHIFTID = S.SHIFTID
,T.COMPLIANCEASSETID = S.COMPLIANCEASSETID
,T.TOTALMINED = S.TOTALMINED
,T.L01ORE = S.L01ORE
,T.L01WASTEOXIDE = S.L01WASTEOXIDE
,T.L05ORE = S.L05ORE
,T.L05WASTEOXIDE = S.L05WASTEOXIDE
,T.S08ORE = S.S08ORE
,T.S08WASTEOXIDE = S.S08WASTEOXIDE
,T.S10ORE = S.S10ORE
,T.S10WASTEOXIDE = S.S10WASTEOXIDE
,T.S11ORE = S.S11ORE
,T.S11WASTEOXIDE = S.S11WASTEOXIDE
,T.S12ORE = S.S12ORE
,T.S12WASTEOXIDE = S.S12WASTEOXIDE
,T.S22ORE = S.S22ORE
,T.S22WASTEOXIDE = S.S22WASTEOXIDE
,T.S23ORE = S.S23ORE
,T.S23WASTEOXIDE = S.S23WASTEOXIDE
,T.REHANDLE = S.REHANDLE
,T.W3TONS = S.W3TONS
,T.E3TONS = S.E3TONS
,T.N1TONS = S.N1TONS
,T.N2TONS = S.N2TONS
,T.N3TONS = S.N3TONS
,T.S4TONS = S.S4TONS
,T.TOTALEXPITTONS = S.TOTALEXPITTONS
,T.EFH = S.EFH
,T.CRUSHER2 = S.CRUSHER2
,T.QUEUEDELTACTARGET = S.QUEUEDELTACTARGET
,T.SPOTTINGDELTACTARGET = S.SPOTTINGDELTACTARGET
,T.LOADINGDELTACTARGET = S.LOADINGDELTACTARGET
,T.LOADEDTRAVELDELTACTARGET = S.LOADEDTRAVELDELTACTARGET
,T.DUMPINGDELTACTARGET = S.DUMPINGDELTACTARGET
,T.STOCKPILETARGETS = S.STOCKPILETARGETS
,T.DUMPINGATCRUSHER = S.DUMPINGATCRUSHER
,T.EMPTYTRAVELDELTACTARGET = S.EMPTYTRAVELDELTACTARGET
--,T.ID = S.ID
,T.CONTENTTYPE = S.CONTENTTYPE
,T.MODIFIED = S.MODIFIED
,T.CREATED = S.CREATED
,T.CREATEDBYID = S.CREATEDBYID
,T.MODIFIEDBYID = S.MODIFIEDBYID
,T.OWSHIDDENVERSION = S.OWSHIDDENVERSION
,T.VERSION = S.VERSION
,T.PATH = S.PATH
,T.UTC_CREATED_DATE = S.UTC_CREATED_DATE
 
 WHEN NOT MATCHED   
 THEN INSERT ( 
 SITEFLAG,
 FORMATSHIFTID,
CONTENTTYPEID,
SHIFTID,
COMPLIANCEASSETID,
TOTALMINED,
L01ORE,
L01WASTEOXIDE,
L05ORE,
L05WASTEOXIDE,
S08ORE,
S08WASTEOXIDE,
S10ORE,
S10WASTEOXIDE,
S11ORE,
S11WASTEOXIDE,
S12ORE,
S12WASTEOXIDE,
S22ORE,
S22WASTEOXIDE,
S23ORE,
S23WASTEOXIDE,
REHANDLE,
W3TONS,
E3TONS,
N1TONS,
N2TONS,
N3TONS,
S4TONS,
TOTALEXPITTONS,
EFH,
CRUSHER2,
QUEUEDELTACTARGET,
SPOTTINGDELTACTARGET,
LOADINGDELTACTARGET,
LOADEDTRAVELDELTA