CREATE VIEW [cer].[CONOPS_CER_DB_DRILL_ASSET_EFFICIENCY_TARGET_V] AS

  
  
--SELECT * FROM [CER].[CONOPS_CER_DB_DRILL_ASSET_EFFICIENCY_TARGET_V] WHERE SHIFTFLAG = 'CURR'  
CREATE VIEW [CER].[CONOPS_CER_DB_DRILL_ASSET_EFFICIENCY_TARGET_V]  
AS  
  
SELECT CAST(RIGHT([YEAR], 2) + FORMAT(CAST([MONTH] AS NUMERIC), '00') AS NUMERIC) [SHIFTID],  
    'CER' AS [SITEFLAG],  
    [DRILLAVAILABILITY] * 100 AS [DRILLAVAILABILITY],  
    [DRILLASSETEFFICIENCY] * 100 AS [DRILLASSETEFFICIENCY],  
    [DRILLUTILIZATION] * 100 AS [DRILLUTILIZATION]  
FROM (  
 SELECT REVERSE(PARSENAME(REPLACE(REVERSE(CAST([TITLE] AS DATE)), '-', '.'), 1)) AS [YEAR],  
     REVERSE(PARSENAME(REPLACE(REVERSE(CAST([TITLE] AS DATE)), '-', '.'), 2)) AS [MONTH],  
     REVERSE(PARSENAME(REPLACE(REVERSE(CAST([TITLE] AS DATE)), '-', '.'), 3)) AS [DAY],  
     CASE WHEN ([PVDISPPRCTG] IS NOT NULL OR CAST([PVDISPPRCTG] AS DECIMAL(3,2)) != 0) AND   
            ([RL8DISPPRCTG] IS NOT NULL OR CAST([RL8DISPPRCTG] AS DECIMAL(3,2)) != 0)  
     THEN (CAST([PVDISPPRCTG] AS DECIMAL(3,2)) + CAST([RL8DISPPRCTG] AS DECIMAL(3,2))) / 2.0  
    WHEN ([PVDISPPRCTG] IS NOT NULL OR CAST([PVDISPPRCTG] AS DECIMAL(3,2)) != 0)  
      THEN CAST([PVDISPPRCTG] AS DECIMAL(3,2))  
    WHEN ([RL8DISPPRCTG] IS NOT NULL OR CAST([RL8DISPPRCTG] AS DECIMAL(3,2)) != 0)  
      THEN CAST([RL8DISPPRCTG] AS DECIMAL(3,2))  
    ELSE 0  
     END AS [DRILLAVAILABILITY],  
     CASE WHEN ([PVASSETEFFPRCTG] IS NOT NULL OR CAST([PVASSETEFFPRCTG] AS DECIMAL(3,2)) != 0) AND   
            ([RL8ASSETEFFECTPRCTG] IS NOT NULL OR CAST([RL8ASSETEFFECTPRCTG] AS DECIMAL(3,2)) != 0)  
     THEN (CAST([PVASSETEFFPRCTG] AS DECIMAL(3,2)) + CAST([RL8ASSETEFFECTPRCTG] AS DECIMAL(3,2))) / 2.0  
    WHEN ([PVASSETEFFPRCTG] IS NOT NULL OR CAST([PVASSETEFFPRCTG] AS DECIMAL(3,2)) != 0)  
      THEN CAST([PVASSETEFFPRCTG] AS DECIMAL(3,2))  
    WHEN ([RL8ASSETEFFECTPRCTG] IS NOT NULL OR CAST([RL8ASSETEFFECTPRCTG] AS DECIMAL(3,2)) != 0)  
      THEN CAST([RL8ASSETEFFECTPRCTG] AS DECIMAL(3,2))  
    ELSE 0  
     END AS [DRILLASSETEFFICIENCY],  
     CASE WHEN ([PVUTILPRCTG] IS NOT NULL OR CAST([PVUTILPRCTG] AS DECIMAL(3,2)) != 0) AND   
            ([RL8UTILPRCTG] IS NOT NULL OR  CAST([RL8UTILPRCTG] AS DECIMAL(3,2)) != 0)  
     THEN (CAST([PVUTILPRCTG] AS DECIMAL(3,2)) + CAST([RL8UTILPRCTG] AS DECIMAL(3,2))) / 2.0  
    WHEN ([PVUTILPRCTG] IS NOT NULL OR CAST([PVUTILPRCTG] AS DECIMAL(3,2)) != 0)  
      THEN CAST([PVUTILPRCTG] AS DECIMAL(3,2))  
    WHEN ([RL8UTILPRCTG] IS NOT NULL OR CAST([RL8UTILPRCTG] AS DECIMAL(3,2)) != 0)  
      THEN CAST([RL8UTILPRCTG] AS DECIMAL(3,2))  
    ELSE 0  
     END AS [DRILLUTILIZATION]  
    FROM [CER].[PLAN_VALUES] (NOLOCK)  
) [TARGET]  
  
