CREATE VIEW [cer].[CONOPS_CER_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V] AS
  -- SELECT * FROM [CER].[CONOPS_CER_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V] WITH (NOLOCK) 
CREATE VIEW [CER].[CONOPS_CER_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V]   
AS  
  
SELECT 
LASTSHIFTINDEX AS Shiftindex,  
SITE_CODE,  
OPERID,  
NROFDAYS  
FROM dbo.OPERATOR_CONSECUTIVE_WORKDAYS WITH (NOLOCK)  
WHERE SITE_CODE = 'CER' AND UNIT_CODE = 2
  