CREATE VIEW [cer].[DRILL_ASSET_EFFICIENCY_V] AS

  
  
  
  
--SELECT * FROM [CER].[DRILL_ASSET_EFFICIENCY_V] WITH (NOLOCK)  
CREATE VIEW [CER].[DRILL_ASSET_EFFICIENCY_V]     
AS        
  
 WITH EQMTHIST AS (  
  SELECT [D].[SHIFT_DATE]  
     ,[D].[SITE_CODE]  
     ,[D].[SHIFTINDEX]  
     ,REPLACE([D].[EQUIPMENTNUMBER], ' ','') AS DRILL_ID  
     ,[D].[EQUIPMENTMODEL]  
     ,[D].[START_TIME_TS]  
     ,[D].[END_TIME_TS]  
     ,[D].[STATUS_DURATION] AS DURATION  
     ,[S].[STATUS]  
     ,[D].[MACHINESTATUSCODE] AS REASONIDX  
     ,[S].[NAME] AS REASON  
     ,[S].[CATEGORY]  
     ,CASE WHEN LAG([EQUIPMENTNUMBER], 1, 0) OVER ( ORDER BY [D].[SHIFTINDEX], [EQUIPMENTNUMBER], START_TIME_TS ) IS NULL  
  THEN 1  
  ELSE CASE WHEN [EQUIPMENTNUMBER] <> LAG([EQUIPMENTNUMBER], 1, 0) OVER ( ORDER BY [D].[SHIFTINDEX], [EQUIPMENTNUMBER], [D].[START_TIME_TS] )  
      OR [D].[MACHINESTATUSCODE] <> LAG([D].[MACHINESTATUSCODE], 1, 0) OVER ( ORDER BY [D].[SHIFTINDEX], [EQUIPMENTNUMBER], [D].[START_TIME_TS] )  
      OR [S].[STATUS] <> LAG([S].[STATUS], 1, 0) OVER ( ORDER BY [D].[SHIFTINDEX], [EQUIPMENTNUMBER], [D].[START_TIME_TS] )  
     THEN 1  
     ELSE CASE WHEN [EQUIPMENTNUMBER] <> LEAD([EQUIPMENTNUMBER], 1, 0) OVER ( ORDER BY [D].[SHIFTINDEX], [EQUIPMENTNUMBER], [D].[START_TIME_TS] )  
    OR [D].[MACHINESTATUSCODE] <> LEAD([D].[MACHINESTATUSCODE], 1, 0) OVER ( ORDER BY [D].[SHIFTINDEX], [EQUIPMENTNUMBER], [D].[START_TIME_TS] )  
    OR [S].[STATUS] <> LEAD([S].[STATUS], 1, 0) OVER ( ORDER BY [D].[SHIFTINDEX], [EQUIPMENTNUMBER], [D].[START_TIME_TS] )  
    THEN 2  
    ELSE 0  
     END  
   END  
   END AS [STATUSINDEX]  
  FROM [CER].[DRILL_UTILIZATION] [D] WITH (NOLOCK)  
  LEFT JOIN [DBO].[LH_REASON] [S] WITH (NOLOCK)  
  ON [S].[SHIFTINDEX] = [D].[SHIFTINDEX] AND [S].[SITE_CODE] = [D].[SITE_CODE]  
     AND [S].[REASON] = [D].[MACHINESTATUSCODE]  
 ),  
  
 HOS AS (  
  SELECT[SHIFT_DATE],  
      SHIFTINDEX,  
      SITE_CODE,  
    DRILL_ID,  
      [EQUIPMENTMODEL],  
    START_TIME_TS,  
    CASE WHEN DRILL_ID = LEAD(DRILL_ID, 1, 0) OVER ( ORDER BY SHIFTINDEX, DRILL_ID, START_TIME_TS )  
  AND REASONIDX = LEAD(REASONIDX, 1, 0) OVER ( ORDER BY SHIFTINDEX, DRILL_ID, START_TIME_TS )  
  AND STATUS = LEAD(STATUS, 1, 0) OVER ( ORDER BY SHIFTINDEX, DRILL_ID, START_TIME_TS )  
       AND 2 = LEAD(STATUSINDEX, 1, 0) OVER ( ORDER BY SHIFTINDEX, DRILL_ID, START_TIME_TS )  
 THEN LEAD(END_TIME_TS, 1, 0) OVER ( ORDER BY SHIFTINDEX, DRILL_ID, START_TIME_TS )  
 ELSE CASE WHEN 1 = LEAD(STATUSINDEX, 1, 0) OVER ( ORDER BY SHIFTINDEX, DRILL_ID, START_TIME_TS )  
           AND STATUSINDEX = 1  
         THEN END_TIME_TS  
         ELSE NULL  
       END  
    END AS END_TIME_TS,  
    CASE WHEN DRILL_ID = LEAD(DRILL_ID, 1, 0) OVER ( ORDER BY SHIFTINDEX, DRILL_ID, START_TIME_TS )  
  AND REASONIDX = LEAD(REASONIDX, 1, 0) OVER ( ORDER BY SHIFTINDEX, DRILL_ID, START_TIME_TS )  
  AND STATUS = LEAD(STATUS, 1, 0) OVER ( ORDER BY SHIFTINDEX, DRILL_ID, START_TIME_TS )  
       AND 2 = LEAD(STATUSINDEX, 1, 0) OVER ( ORDER BY SHIFTINDEX, DRILL_ID, START_TIME_TS )  
 THEN LEAD(DURATION, 1, 0) OVER ( ORDER BY SHIFTINDEX, DRILL_ID, START_TIME_TS )  
  ELSE CASE WHEN 1 = LEAD(STATUSINDEX, 1, 0) OVER ( ORDER BY SHIFTINDEX, DRILL_ID, START_TIME_TS )  
           AND STATUSINDEX = 1  
         THEN DURATION  
         ELSE NULL  
       END  
    END AS DURATION,  
    STATUS,  
      REASONIDX,  
    REASON,  
    CATEGORY  
  FROM EQMTHIST EH  
  WHERE STATUSINDEX != 0  
 )  
  
 SELECT SHIFTINDEX,  
     SITE_CODE,  
     DRILL_ID,  
     [EQUIPMENTMODEL] AS MODEL,  
     START_TIME_TS [STARTDATETIME],  
     END_TIME_TS [ENDDATETIME],  
     [DURATION],  
     STATUS [STATUSIDX],  
     [STATUSDESC] [STATUS],  
     CATEGORY [CATEGORYIDX],  
     [CATEGORYDESC] [CATEGORY],  
     [REASONIDX],  
     [REASON]  
 FROM (  
  
  SELECT SHIFTINDEX,  
      HOS.SITE_CODE,  
      DRILL_ID,  
      [EQUIPM