CREATE TABLE [saf].[PIT_WORKER_C] (
    [siteflag] varchar(5) NOT NULL,
    [SHIFTINDEX] numeric(38,0) NOT NULL,
    [SHIFTID] decimal(9,0) NOT NULL,
    [DbPrevious] decimal(19,0) NULL,
    [DbNext] decimal(19,0) NULL,
    [DbVersion] int NULL,
    [Id] decimal(19,0) NOT NULL,
    [DbName] varchar(32) NOT NULL,
    [DbKey] decimal(19,0) NOT NULL,
    [FieldId] varchar(20) NULL,
    [FieldNumer] int NULL,
    [FieldShifts] int NULL,
    [FieldStatus] decimal(19,0) NULL,
    [FieldLineupcrew] decimal(19,0) NULL,
    [FieldCrew] decimal(19,0) NULL,
    [FieldDept] decimal(19,0) NULL,
    [FieldName] varchar(40) NULL,
    [FieldSeniority] varchar(7) NULL,
    [FieldRegionlock] decimal(19,0) NULL,
    [FieldLoc] decimal(19,0) NULL,
    [FieldLoctime] decimal(19,0) NULL,
    [FieldRoster] decimal(19,0) NULL,
    [FieldRosterhist] decimal(19,0) NULL,
    [FieldLogincrew] decimal(19,0) NULL,
    [FieldFatgmode] decimal(19,0) NULL,
    [FieldFatgwarntype] decimal(19,0) NULL,
    [FieldFatgwarnpassed] int NULL,
    [FieldNextfatgwarndue] decimal(19,0) NULL,
    [FieldFatgwarnsent] decimal(19,0) NULL,
    [FieldFatgrespexptd] varchar(5) NULL,
    [FieldFatgddblink] varchar(12) NULL,
    [FieldArea] int NULL,
    [FieldLcomment] varchar(90) NULL,
    [UTC_CREATED_DATE] datetime NOT NULL,
    [UTC_LOGICAL_DELETED_DATE] datetime NULL
);