CREATE TABLE [saf].[PLAN_VALUES] (
    [SITEFLAG] varchar(5) NOT NULL,
    [CONTENTTYPEID] varchar(100) NOT NULL,
    [PLANNAME] varchar(50) NULL,
    [COMPLIANCEASSETID] varchar(100) NULL,
    [DATEEFFECTIVE] date NULL,
    [SHIFTINDEX] varchar(5) NULL,
    [TOTALCRUSHERTPD] decimal(18,5) NULL,
    [S1ORE] decimal(18,5) NULL,
    [S1WASTE] decimal(18,5) NULL,
    [S1STK] decimal(18,5) NULL,
    [S1P] decimal(18,5) NULL,
    [S2ORE] decimal(18,5) NULL,
    [S2WASTE] decimal(18,5) NULL,
    [S2STK] decimal(18,5) NULL,
    [S2P] decimal(18,5) NULL,
    [S3ORE] decimal(18,5) NULL,
    [S3WASTE] decimal(18,5) NULL,
    [S3STK] decimal(18,5) NULL,
    [S3P] decimal(18,5) NULL,
    [S4ORE] decimal(18,5) NULL,
    [S4WASTE] decimal(18,5) NULL,
    [S4STK] decimal(18,5) NULL,
    [S4P] decimal(18,5) NULL,
    [S5ORE] decimal(18,5) NULL,
    [S5WASTE] decimal(18,5) NULL,
    [S5STK] decimal(18,5) NULL,
    [S5P] decimal(18,5) NULL,
    [S6ORE] decimal(18,5) NULL,
    [S6WASTE] decimal(18,5) NULL,
    [S6STK] decimal(18,5) NULL,
    [S6P] decimal(18,5) NULL,
    [S7ORE] decimal(18,5) NULL,
    [S7WASTE] decimal(18,5) NULL,
    [S7STK] decimal(18,5) NULL,
    [S7P] decimal(18,5) NULL,
    [S8ORE] decimal(18,5) NULL,
    [S8WASTE] decimal(18,5) NULL,
    [S8STK] decimal(18,5) NULL,
    [S8P] decimal(18,5) NULL,
    [L002ORE] decimal(18,5) NULL,
    [L002WASTE] decimal(18,5) NULL,
    [L002STK] decimal(18,5) NULL,
    [L008ORE] decimal(18,5) NULL,
    [L008WASTE] decimal(18,5) NULL,
    [L008STK] decimal(18,5) NULL,
    [L013ORE] decimal(18,5) NULL,
    [L013WASTE] decimal(18,5) NULL,
    [L013STK] decimal(18,5) NULL,
    [TOTALORETPD] decimal(18,5) NULL,
    [TOTALORETPDSJ] decimal(18,5) NULL,
    [TOTALORETPDLS] decimal(18,5) NULL,
    [TOTALSTKTPD] decimal(18,5) NULL,
    [TOTALSJSTKTPD] decimal(18,5) NULL,
    [TOTALLSSTKTPD] decimal(18,5) NULL,
    [TOTALWASTETPD] decimal(18,5) NULL,
    [TOTALSJWASTETPD] decimal(18,5) NULL,
    [TOTALLSWASTETPD] decimal(18,5) NULL,
    [TOTALMINETPD] decimal(18,5) NULL,
    [TOTALLSTPD] decimal(18,5) NULL,
    [TOTALSJTPD] decimal(18,5) NULL,
    [LOADINGAVAILIBILITY] varchar(50) NULL,
    [LOADINGASSETEFFICIENCY] varchar(50) NULL,
    [TRUCKAVAILIBILITY] varchar(50) NULL,
    [TRUCKASSETEFFICIENCY] varchar(50) NULL,
    [AVGCOUNTREADYTRUCKS] decimal(18,5) NULL,
    [AVERAGECOUNTREADYTRUCKSSJ] decimal(18,5) NULL,
    [AVERAGECOUNTREADYTRUCKSLS] decimal(18,5) NULL,
    [EQUIVALENTFLATHAUL] decimal(18,5) NULL,
    [TOTALCYCLETIME] decimal(18,5) NULL,
    [TOTALCYCLETIMESJ] decimal(18,5) NULL,
    [TOTALCYCLETIMELS] decimal(18,5) NULL,
    [DELTAC] decimal(18,5) NULL,
    [TOTALEFH] decimal(18,5) NULL,
    [EFH_SJ] decimal(18,5) NULL,
    [EFH_LS] decimal(18,5) NULL,
    [ELECSHOVELLOADTONSONREADYHOUR] decimal(18,5) NULL,
    [ELECSHOVELAVAILABILITY] varchar(50) NULL,
    [ELECSHOVELASSETEFFICENCY] varchar(50) NULL,
    [ELECSHOVELUSEOFAVAILIBILITY] varchar(50) NULL,
    [ELECSHOVELAVGREADYNUMBERS] decimal(18,5) NULL,
    [SPOTING] decimal(18,5) NULL,
    [LOADING] decimal(18,5) NULL,
    [LOADEDTRAVEL] decimal(18,5) NULL,
    [DUMPINGATCRUSHER] decimal(18,5) NULL,
    [DUMPINGATSTOCKPILE] decimal(18,5) NULL,
    [EMPTYTRAVEL] decimal(18,5) NULL,
    [DRILLAE] decimal(18,5) NULL,
    [DRILLAVAIL] decimal(18,5) NULL,
    [DRILLUA] decimal(18,5) NULL,
    [FEETDRILLED] decimal(18,5) NULL,
    [HOLESDRILLED] decimal(18,5) NULL,
    [ID] int NOT NULL,
    [CONTENTTYPE] varchar(50) NOT NULL,
    [MODIFIED] datetime NOT NULL,
    [CREATED] datetime NOT NULL,
    [CREATEDBYID] int NOT NULL,
    [MODIFIEDBYID] int NOT NULL,
    [OWSHIDDENVERSION] int NOT NULL,
    [VERSION] decimal(10,5) NOT NULL,
    [PATH] varchar(2000) NOT NULL,
    [UTC_CREATED_DATE] datetime NULL
);