CREATE TABLE [saf].[SHIFT_LOC] (
    [siteflag] varchar(5) NOT NULL,
    [DbPrevious] decimal(19,0) NULL,
    [DbNext] decimal(19,0) NULL,
    [DbVersion] int NULL,
    [ShiftId] decimal(19,0) NOT NULL,
    [Id] decimal(19,0) NOT NULL,
    [DbName] varchar(32) NOT NULL,
    [DbKey] decimal(19,0) NOT NULL,
    [FieldId] varchar(24) NULL,
    [FieldPit] decimal(19,0) NULL,
    [FieldRegion] decimal(19,0) NULL,
    [FieldElev] decimal(19,0) NULL,
    [FieldUnit] decimal(19,0) NULL,
    [FieldStatus] decimal(19,0) NULL,
    [FieldReason] int NULL,
    [FieldReasonrec] decimal(19,0) NULL,
    [FieldAudit] decimal(19,0) NULL,
    [FieldMetadata] varchar(20) NULL,
    [FieldX] int NULL,
    [FieldY] int NULL,
    [UTC_CREATED_DATE] datetime NOT NULL,
    [UTC_LOGICAL_DELETED_DATE] datetime NULL
);