CREATE VIEW [bag2].[ASSET_EFFICIENCY_V] AS

CREATE VIEW BAG2.ASSET_EFFICIENCY_V
AS

WITH TimeZone AS(
SELECT 
	name AS TimeZoneName,
	is_currently_dst,
	CAST(CAST(current_utc_offset AS VARCHAR(3)) AS INT) AS current_utc_offset,
	CAST(CAST(current_utc_offset AS VARCHAR(3)) AS INT) - DATEPART(TZ, SYSDATETIMEOFFSET()) / 60 AS current_server_offset
FROM sys.time_zone_info
WHERE name = 'US Mountain Standard Time'
),

AllStatus AS(
SELECT
(CONVERT(INT, (DATEDIFF(DD, '7/12/2007', CAST(DATEADD(HOUR, current_utc_offset, FS.STARTTIME_UTC) AS DATE))*2) + 27412 + (SHIFTTYPE))) SHIFTINDEX,
CAST(DATEADD(HOUR, current_utc_offset, FS.STARTTIME_UTC) AS DATE) AS SHIFT_DATE,
DATEADD(HOUR, current_utc_offset, FS.STARTTIME_UTC) AS SHIFT_START_DATE_TIME,
FS.SHIFTTYPE + 1 AS SHIFT_CODE,
CASE WHEN FS.SHIFTTYPE = 0
	THEN 'Day Shift'
	ELSE 'Night Shift'
END AS SHIFT,
CAST(FC.NAME AS VARCHAR(64)) AS CREW,
CAST(SE.SITE_CODE AS VARCHAR(64)) AS SITE_CODE,
CAST(FE.NAME AS VARCHAR(64)) AS EQMT,
EQM.DISPATCH_EQUIP_CATEGORY_NUMBER AS UNIT,
MCL.NAME AS EQMTTYPE,
CASE WHEN EQM.LH_EQUIP_CATEGORY = 'Haul Truck'
	THEN 'Truck' ELSE EQM.LH_EQUIP_CATEGORY END AS UnitType,
P.PERSONNELID AS OPERID,
SE.START_TS_LOCAL AS START_TIME_TS,
SE.END_TS_LOCAL AS END_TIME_TS,
ER.dw_status_event_reason_code AS REASON,
CASE   
	WHEN ER.TIME_CATEGORY = 'Ready Production' THEN 2  
	WHEN ER.TIME_CATEGORY = 'Ready Non-Production' THEN 2  
	WHEN ER.TIME_CATEGORY = 'Operational Down' THEN 1  
	WHEN ER.TIME_CATEGORY = 'Scheduled Down' THEN 1  
	WHEN ER.TIME_CATEGORY = 'Unscheduled Down' THEN 1  
	WHEN ER.TIME_CATEGORY = 'Operational Delay' THEN 4  
	WHEN ER.TIME_CATEGORY = 'Spare' THEN 3  
	WHEN ER.TIME_CATEGORY = 'Non Guarantee' THEN 1  
	WHEN ER.TIME_CATEGORY = 'ShiftChange' THEN 5  
ELSE NULL END AS STATUS,
ER.TIME_CATEGORY,
ER.TIME_CATEGORY_CODE AS CATEGORY,
CAST(LEFT(SE.EVENT_COMMENTS, 90) AS VARCHAR(90)) AS COMMENTS
FROM BAG.FLEET_EQUIPMENT_STATUS_EVENT_V SE 
LEFT JOIN BAG.FLEET_STATUS_EVENT_REASON_V ER
	ON SE.status_event_reason_id = ER.DELAYCLASS_OID
LEFT JOIN BAG_MSMODEL.DBO.MACHINE FE WITH(NOLOCK)
	ON SE.equipment_id = FE.MACHINE_OID
LEFT JOIN BAG.LH_EQUIP_CATEGORY_MAP EQM WITH(NOLOCK)
	ON SE.EQUIPMENT_CATEGORY COLLATE SQL_Latin1_General_CP1_CI_AS = eqm.FLEET_EQUIP_CATEGORY
LEFT JOIN BAG_MSMODEL.dbo.MACHINECLASS MCL WITH(NOLOCK)
	ON FE.class = mcl.machineclass_oid
LEFT JOIN BAG_MSMODEL.dbo.SHIFT FS WITH(NOLOCK)
	ON SE.shift_id = (CAST(fs.reporting_date AS VARCHAR) + CAST(fs.shifttype AS VARCHAR))
LEFT JOIN BAG_MSMODEL.DBO.CREW FC WITH(NOLOCK)
	ON FS.CREW = FC.OID
LEFT JOIN BAG_MSHIST.dbo.CYCLE CY WITH(NOLOCK)
	ON SE.CYCLE_ID = CY.CYCLE_OID
LEFT JOIN BAG_MSMODEL.DBO.PERSON P WITH(NOLOCK)
	ON CY.PRIMARYOPERATOR = P.PERSON_OID
CROSS JOIN TimeZone
),

CombineSameStatus AS(
SELECT
	SHIFTINDEX,
	SHIFT_DATE,
	SHIFT_CODE,
	SHIFT,
	SHIFT_START_DATE_TIME,
	CREW,
	SITE_CODE,
	EQMT,
	EQMTTYPE,
	UNIT,
	UNITTYPE,
	OPERID,
	START_TIME_TS,
	END_TIME_TS,
	REASON,
	STATUS,
	CATEGORY,
	COMMENTS,
	TIME_CATEGORY,
	CASE WHEN LAG(EQMT, 1, 0) OVER (PARTITION BY SHIFTINDEX, EQMT ORDER BY Shiftindex, EQMT, START_TIME_TS ) IS NULL
			THEN 1
			ELSE CASE WHEN EQMT <> LAG(EQMT, 1, 0) OVER (PARTITION BY SHIFTINDEX, EQMT ORDER BY Shiftindex, EQMT, START_TIME_TS )
				OR REASON <> LAG(REASON, 1, 0) OVER (PARTITION BY SHIFTINDEX, EQMT ORDER BY Shiftindex, EQMT, START_TIME_TS )
				OR [Status] <> LAG([Status], 1, 0) OVER (PARTITION BY SHIFTINDEX, EQMT ORDER BY Shiftindex, EQMT, START_TIME_TS )
				THEN 1
				ELSE CASE WHEN EQMT <> LEAD(EQMT, 1, 0) OVER (PARTITION BY SHIFTINDEX, EQMT ORDER BY Shiftindex, EQMT, START_TIME_TS )
					OR REASON <> LEAD(REASON, 1, 0) OVER (PARTITION BY SHIFTINDEX, EQMT ORDER BY Shiftindex, EQMT, START_TIME_TS )
					OR [Status] <> LEAD([Status], 1, 0) OVER (PARTITION BY SHIFTINDEX, EQMT ORDER BY Shiftindex, EQMT, START_TIME_TS )
					THEN 2
					ELSE 0
				END
			END
	END AS StatusIndex
FROM AllStatus
),

Combine2 AS(
SEL