CREATE VIEW [bag2].[VIEW_MACHINECATEGORY_ETL] AS

CREATE VIEW [bag2].[VIEW_MACHINECATEGORY_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.MACHINECATEGORY_OID') AS MACHINECATEGORY_OID,
JSON_VALUE(DATA_VALUE.value, '$.ECF_CLASS_ID') AS ECF_CLASS_ID,
JSON_VALUE(DATA_VALUE.value, '$.IS_ACTIVE') AS IS_ACTIVE,
JSON_VALUE(DATA_VALUE.value, '$.NAME') AS NAME,
JSON_VALUE(DATA_VALUE.value, '$.DESCRIPTION') AS DESCRIPTION,
JSON_VALUE(DATA_VALUE.value, '$.ICONURL') AS ICONURL,
JSON_VALUE(DATA_VALUE.value, '$.STATESET') AS STATESET,
JSON_VALUE(DATA_VALUE.value, '$.CYCLEENGINE') AS CYCLEENGINE,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_TYPE') AS CHANGE_TYPE,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_ID') AS CHANGE_ID,
Getutcdate() AS UTC_CREATED_DATE
--NULL AS UTC_LOGICAL_DELETED_DATE
FROM [bag2].[MACHINECATEGORY_STAGE] LS
CROSS APPLY OPENJSON (LS.SRC_JSON) AS DATA_VALUE
