CREATE VIEW [bag2].[VIEW_LOCATION_ETL] AS

CREATE VIEW [bag2].[VIEW_LOCATION_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.LOCATION_OID') AS LOCATION_OID,
JSON_VALUE(DATA_VALUE.value, '$.IS_ACTIVE') AS IS_ACTIVE,
JSON_VALUE(DATA_VALUE.value, '$.DESCRIPTION') AS DESCRIPTION,
JSON_VALUE(DATA_VALUE.value, '$.NAME') AS NAME,
JSON_VALUE(DATA_VALUE.value, '$.REHANDLE') AS REHANDLE,
JSON_VALUE(DATA_VALUE.value, '$.ISSOURCE') AS ISSOURCE,
JSON_VALUE(DATA_VALUE.value, '$.ISSINK') AS ISSINK,
JSON_VALUE(DATA_VALUE.value, '$.ISSTATION') AS ISSTATION,
JSON_VALUE(DATA_VALUE.value, '$.ALLOWALLMATERIALS') AS ALLOWALLMATERIALS, 
JSON_VALUE(DATA_VALUE.value, '$.ALLOWTHORUGHTRAFFIC') AS ALLOWTHORUGHTRAFFIC,
JSON_VALUE(DATA_VALUE.value, '$.TRUCKCAPACITY') AS TRUCKCAPACITY,
JSON_VALUE(DATA_VALUE.value, '$.QUEUINGALLOWED') AS QUEUINGALLOWED ,
JSON_VALUE(DATA_VALUE.value, '$.TAXCLASS') AS TAXCLASS,
JSON_VALUE(DATA_VALUE.value, '$.ISPARENT') AS ISPARENT,
JSON_VALUE(DATA_VALUE.value, '$.BADCOMMSAREA') AS BADCOMMSAREA,
JSON_VALUE(DATA_VALUE.value, '$.LOADSTATE') AS LOADSTATE,
JSON_VALUE(DATA_VALUE.value, '$.SHIFTCHANGEGROUP') AS SHIFTCHANGEGROUP,
JSON_VALUE(DATA_VALUE.value, '$.EXTERNALREF') AS EXTERNALREF,
JSON_VALUE(DATA_VALUE.value, '$.EXTERNALDESC') AS EXTERNALDESC,
JSON_VALUE(DATA_VALUE.value, '$.LAYER_UPDATE_VERSION') AS LAYER_UPDATE_VERSION,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_TYPE') AS CHANGE_TYPE,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_ID') AS CHANGE_ID,
Getutcdate() AS UTC_CREATED_DATE
--NULL AS UTC_LOGICAL_DELETED_DATE
FROM [bag2].[LOCATION_STAGE] LS
CROSS APPLY OPENJSON (LS.SRC_JSON) AS DATA_VALUE
