CREATE VIEW [bag2].[VIEW_VIRTUALBEACON_ETL] AS

CREATE VIEW [bag2].[VIEW_VIRTUALBEACON_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.VIRTUALBEACON_OID') AS VIRTUALBEACON_OID,
JSON_VALUE(DATA_VALUE.value, '$.IS_ACTIVE') AS IS_ACTIVE,
JSON_VALUE(DATA_VALUE.value, '$.NAME') AS NAME,
JSON_VALUE(DATA_VALUE.value, '$.DESCRIPTION') AS DESCRIPTION,
JSON_VALUE(DATA_VALUE.value, '$.COLOUR') AS COLOUR,
JSON_VALUE(DATA_VALUE.value, '$.DATE_LAST_MODIFIED_UTC') AS DATE_LAST_MODIFIED_UTC,
JSON_VALUE(DATA_VALUE.value, '$.FLAGS') AS FLAGS,
JSON_VALUE(DATA_VALUE.value, '$.HEIGHT') AS HEIGHT,
JSON_VALUE(DATA_VALUE.value, '$.ID') AS ID,
JSON_VALUE(DATA_VALUE.value, '$.LOADERID') AS LOADERID,
JSON_VALUE(DATA_VALUE.value, '$.RADIUS') AS RADIUS,
JSON_VALUE(DATA_VALUE.value, '$.REASSIGNMT') AS REASSIGNMT,
JSON_VALUE(DATA_VALUE.value, '$.REASSIGNFULL') AS REASSIGNFULL,
JSON_VALUE(DATA_VALUE.value, '$.TYPE') AS TYPE,
JSON_VALUE(DATA_VALUE.value, '$.VERSION') AS VERSION,
JSON_VALUE(DATA_VALUE.value, '$.ZORDER') AS ZORDER,
JSON_VALUE(DATA_VALUE.value, '$.MISSED_COUNT') AS MISSED_COUNT,
JSON_VALUE(DATA_VALUE.value, '$.ROUTE_POINT_X') AS ROUTE_POINT_X,
JSON_VALUE(DATA_VALUE.value, '$.ROUTE_POINT_Y') AS ROUTE_POINT_Y,
JSON_VALUE(DATA_VALUE.value, '$.ROUTE_POINT_Z') AS ROUTE_POINT_Z,
JSON_VALUE(DATA_VALUE.value, '$.EXTERNALREF') AS EXTERNALREF,
JSON_VALUE(DATA_VALUE.value, '$.EXTERNALDESC') AS EXTERNALDESC,
JSON_VALUE(DATA_VALUE.value, '$.MODEL_UPDATE_VERSION') AS MODEL_UPDATE_VERSION,
JSON_VALUE(DATA_VALUE.value, '$.LAYER_UPDATE_VERSION') AS LAYER_UPDATE_VERSION,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_TYPE') AS CHANGE_TYPE,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_ID') AS CHANGE_ID,
Getutcdate() AS UTC_CREATED_DATE
--NULL AS UTC_LOGICAL_DELETED_DATE
FROM [bag2].[VIRTUALBEACON_STAGE] LS
CROSS APPLY OPENJSON (LS.SRC_JSON) AS DATA_VALUE
