

/******************************************************************
* PROCEDURE : [SIE].[UPSERT_CONOPS_PLAN_VALUES]   
* PURPOSE : UPSERT [UPSERT_CONOPS_PLAN_VALUES]  
* NOTES :   
* CREATED : MFAHMI  
* SAMPLE: EXEC SIE.[UPSERT_CONOPS_PLAN_VALUES]  
* MODIFIED DATE  AUTHORDESCRIPTION
*------------------------------------------------------------------
* {22 JUN 2022}  {MFAHMI}   {INITIAL CREATED}  
* {11 JUL 2023}  {MFAHMI}   {ENHANCE SCRIPT CLEANUP TO KEEP LAST 3 SHIFT AND CONVERT SHIFTID TO SIE TIME}  
* {21 JUL 2023}  {MFAHMI}   {ENHANCE TO ADD SCRIPT CLEANUP CURRENT SHIFT}
* {05 DEC 2023}  {GGOSAL1}  {Add: update table monitoring}
* {03 JUL 2025}  {GGOSAL1}  {Update SP to delete deleted data}
*******************************************************************/
CREATE  PROCEDURE [SIE].[UPSERT_CONOPS_PLAN_VALUES]  
AS  
BEGIN  

--CLEANUP DATA FROM CURRENT SHIFT
--DELETE 
--FROM  SIE.PLAN_VALUES
--WHERE SHIFTID  >= (SELECT GETDATE());
  
MERGE SIE.PLAN_VALUES AS T   
USING (
	SELECT 
		'SIE' AS SITEFLAG, 
		SHOVELNAME,
		PUSHBACKNAME,
		BENCHNAME,
		POLYGONNAME,
		DESTINATION,
		DATEADD(HOUR,-7,SHIFTID) AS SHIFTID,
		MASS_TONS,
		GRADE_ASCU,
		GRADE_EQCU,
		GRADE_MO,
		GRADE_TCU,
		EARLIESTSTARTDATE,
		LATESTFINISHDATE,
		PRODUCTIVEHOURS,
		GETUTCDATE() UTC_CREATED_DATE   
	FROM SIE.PLAN_VALUES_STG) AS S   
	ON (T.SHOVELNAME = S.SHOVELNAME 
		AND T.SITEFLAG = S.SITEFLAG
		AND T.PUSHBACKNAME = S.PUSHBACKNAME
		AND T.BENCHNAME = S.BENCHNAME 
		AND T.POLYGONNAME = S.POLYGONNAME
		AND T.DESTINATION = S.DESTINATION 
		AND T.SHIFTID = S.SHIFTID)   
WHEN MATCHED   
THEN UPDATE SET  
	 T.MASS_TONS = S.MASS_TONS
	,T.GRADE_ASCU = S.GRADE_ASCU
	,T.GRADE_EQCU = S.GRADE_EQCU
	,T.GRADE_MO = S.GRADE_MO
	,T.GRADE_TCU = S.GRADE_TCU
	,T.EARLIESTSTARTDATE = S.EARLIESTSTARTDATE
	,T.LATESTFINISHDATE = S.LATESTFINISHDATE
	,T.PRODUCTIVEHOURS = S.PRODUCTIVEHOURS
	,T.UTC_CREATED_DATE = S.UTC_CREATED_DATE
WHEN NOT MATCHED   
THEN INSERT ( 
	SITEFLAG,
	SHOVELNAME,
	PUSHBACKNAME,
	BENCHNAME,
	POLYGONNAME,
	DESTINATION,
	SHIFTID,
	MASS_TONS,
	GRADE_ASCU,
	GRADE_EQCU,
	GRADE_MO,
	GRADE_TCU,
	EARLIESTSTARTDATE,
	LATESTFINISHDATE,
	PRODUCTIVEHOURS, 
	UTC_CREATED_DATE
) VALUES( 
	S.SITEFLAG,  
	S.SHOVELNAME,
	S.PUSHBACKNAME,
	S.BENCHNAME,
	S.POLYGONNAME,
	S.DESTINATION,
	S.SHIFTID,
	S.MASS_TONS,
	S.GRADE_ASCU,
	S.GRADE_EQCU,
	S.GRADE_MO,
	S.GRADE_TCU,
	S.EARLIESTSTARTDATE,
	S.LATESTFINISHDATE,
	S.PRODUCTIVEHOURS,
	S.UTC_CREATED_DATE  
 );

--CLEANUP DATA TO KEEP LAST 3 SHIFT
--DELETE  
--FROM  SIE.PLAN_VALUES
--WHERE SHIFTID < (SELECT MIN(DATEADD("HH",-7,SHIFTID)) - 1 FROM  SIE.PLAN_VALUES_STG);

DELETE FROM  SIE.PLAN_VALUES 
WHERE NOT EXISTS  
(SELECT 1  
FROM  SIE.PLAN_VALUES_STG  AS s
WHERE
	SIE.PLAN_VALUES.SHOVELNAME = S.SHOVELNAME AND
    SIE.PLAN_VALUES.PUSHBACKNAME = S.PUSHBACKNAME AND
    SIE.PLAN_VALUES.BENCHNAME = S.BENCHNAME AND
    SIE.PLAN_VALUES.POLYGONNAME = S.POLYGONNAME AND
    SIE.PLAN_VALUES.DESTINATION = S.DESTINATION AND
    SIE.PLAN_VALUES.SHIFTID = DATEADD(HOUR,-7,S.SHIFTID)
);   
 
--Update Table Monitoring
UPDATE [dbo].[DI_JOB_CONTROL_ENTRY_TS_BASE]
SET dw_load_ts = GETUTCDATE()
WHERE job_name = 'SIE_RPM_To_SQLMI_PlanValues'
   
END  
  



