

/******************************************************************      
* PROCEDURE : [SIE].[UPSERT_CONOPS_PLAN_VALUES_PROD_SUM]     
* PURPOSE : Upsert [UPSERT_CONOPS_PLAN_VALUES_PROD_SUM]    
* NOTES     :     
* CREATED : mfahmi    
* SAMPLE    : EXEC SIE.[UPSERT_CONOPS_PLAN_VALUES_PROD_SUM]   
* MODIFIED DATE  AUTHOR    DESCRIPTION      
*------------------------------------------------------------------      
* {20 MAR 2023}  {mfahmi}   {Initial Created}      
* {05 DEC 2023}  {GGOSAL1}  {Add: update table monitoring}
*******************************************************************/      
CREATE  PROCEDURE [sie].[UPSERT_CONOPS_PLAN_VALUES_PROD_SUM]    
AS    
BEGIN    
    
MERGE SIE.PLAN_VALUES_PROD_SUM AS T     
USING (SELECT     
'SIE' AS SITEFLAG,   
CONTENTTYPEID,
PLANNAME,
COMPLIANCEASSETID,
DATEEFFECTIVE,
LOADINGAVAILIBILITY,
LOADINGASSETEFFICIENCY,
TRUCKAVAILABILITY,
TRUCKASSETEFFICIENCY,
AVGCOUNTREADYTRUCKS,
EQUIVALENTFLATHAUL,
TOTALCYCLETIME,
DELTAC,
ELECSHOVELLOADTONSONREADYHOUR,
ELECSHOVELAVAILABILITY,
ELECSHOVELASSETEFFICIENCY,
ELECSHOVELUSEOFAVAILIBILITY,
ELECSHOVELAVGREADYNUMBER,
AVERAGEPAYLOAD,
IDLETIME,
EMPTYONEWAYHAUL,
EMPTYLIFTS,
EMPTYDROPS,
SPOTING,
LOADEDTRAVEL,
DUMPINGATCRUSHER,
DUMPINGATSTOCKPILE,
EMPTYTRAVEL,
FEETDRILLEDTARGET,
HOLESDRILLEDTARGET,
TOTALEXPITTPD,
S44,
S45,
S48,
L98,
L50,
TRUCKUSEOFAVAILABILITY,
DRILLREADINESS,
DRILLASSETEFFICIENCY,
DRILLAVAILABILITY,
DRILLUSEOFAVAILABILITY,
PB61OREQ,
PB61WASTEQ,
PB62OREQ,
PB62WASTEQ,
PB81OREQ,
PB81WASTEQ,
PB82OREQ,
PB82WASTEQ,
PB99OREQ,
S43LOADING,
S44LOADING,
S48LOADING,
S45LOADING,
L50LOADING,
L98LOADING, 
Id,  
ContentType,  
Modified,  
Created,  
CreatedById,  
ModifiedById,  
Owshiddenversion,  
Version,  
Path,  
getutcdate() UTC_CREATED_DATE     
 FROM SIE.PLAN_VALUES_PROD_SUM_stg) AS S     
 ON (T.Id = S.Id AND T.SITEFLAG = S.SITEFLAG)     
    
 WHEN MATCHED     
 THEN UPDATE SET     
T.CONTENTTYPEID = S.CONTENTTYPEID
,T.PLANNAME = S.PLANNAME
,T.COMPLIANCEASSETID = S.COMPLIANCEASSETID
,T.DATEEFFECTIVE = S.DATEEFFECTIVE
,T.LOADINGAVAILIBILITY = S.LOADINGAVAILIBILITY
,T.LOADINGASSETEFFICIENCY = S.LOADINGASSETEFFICIENCY
,T.TRUCKAVAILABILITY = S.TRUCKAVAILABILITY
,T.TRUCKASSETEFFICIENCY = S.TRUCKASSETEFFICIENCY
,T.AVGCOUNTREADYTRUCKS = S.AVGCOUNTREADYTRUCKS
,T.EQUIVALENTFLATHAUL = S.EQUIVALENTFLATHAUL
,T.TOTALCYCLETIME = S.TOTALCYCLETIME
,T.DELTAC = S.DELTAC
,T.ELECSHOVELLOADTONSONREADYHOUR = S.ELECSHOVELLOADTONSONREADYHOUR
,T.ELECSHOVELAVAILABILITY = S.ELECSHOVELAVAILABILITY
,T.ELECSHOVELASSETEFFICIENCY = S.ELECSHOVELASSETEFFICIENCY
,T.ELECSHOVELUSEOFAVAILIBILITY = S.ELECSHOVELUSEOFAVAILIBILITY
,T.ELECSHOVELAVGREADYNUMBER = S.ELECSHOVELAVGREADYNUMBER
,T.AVERAGEPAYLOAD = S.AVERAGEPAYLOAD
,T.IDLETIME = S.IDLETIME
,T.EMPTYONEWAYHAUL = S.EMPTYONEWAYHAUL
,T.EMPTYLIFTS = S.EMPTYLIFTS
,T.EMPTYDROPS = S.EMPTYDROPS
,T.SPOTING = S.SPOTING
,T.LOADEDTRAVEL = S.LOADEDTRAVEL
,T.DUMPINGATCRUSHER = S.DUMPINGATCRUSHER
,T.DUMPINGATSTOCKPILE = S.DUMPINGATSTOCKPILE
,T.EMPTYTRAVEL = S.EMPTYTRAVEL
,T.FEETDRILLEDTARGET = S.FEETDRILLEDTARGET
,T.HOLESDRILLEDTARGET = S.HOLESDRILLEDTARGET
,T.TOTALEXPITTPD = S.TOTALEXPITTPD
,T.S44 = S.S44
,T.S45 = S.S45
,T.S48 = S.S48
,T.L98 = S.L98
,T.L50 = S.L50
,T.TRUCKUSEOFAVAILABILITY = S.TRUCKUSEOFAVAILABILITY
,T.DRILLREADINESS = S.DRILLREADINESS
,T.DRILLASSETEFFICIENCY = S.DRILLASSETEFFICIENCY
,T.DRILLAVAILABILITY = S.DRILLAVAILABILITY
,T.DRILLUSEOFAVAILABILITY = S.DRILLUSEOFAVAILABILITY
,T.PB61OREQ = S.PB61OREQ
,T.PB61WASTEQ = S.PB61WASTEQ
,T.PB62OREQ = S.PB62OREQ
,T.PB62WASTEQ = S.PB62WASTEQ
,T.PB81OREQ = S.PB81OREQ
,T.PB81WASTEQ = S.PB81WASTEQ
,T.PB82OREQ = S.PB82OREQ
,T.PB82WASTEQ = S.PB82WASTEQ
,T.PB99OREQ = S.PB99OREQ
,T.S43LOADING = S.S43LOADING
,T.S44LOADING = S.S44LOADING
,T.S48LOADING = S.S48LOADING
,T.S45LOADING = S.S45LOADING
,T.L50LOADING = S.L50LOADING
,T.L98LOADING =