
  
    
    
    
/******************************************************************        
* PROCEDURE : BAG2.[UPSERT_CONOPS_CYCLE_FULL]      
* PURPOSE : UPSERT [UPSERT_CONOPS_CYCLE_FULL]      
* NOTES     :       
* CREATED : MFAHMI      
* SAMPLE    : 
* 1. EXEC BAG2.[UPSERT_CONOPS_CYCLE_FULL] 'BAG2' ,'FULL', 0  
* 2. EXEC BAG2.[UPSERT_CONOPS_CYCLE_FULL] 'BAG2' ,'SHIFT', 1    
* MODIFIED DATE  AUTHOR    DESCRIPTION        
*------------------------------------------------------------------        
* {04 SEP 2024}  {MFAHMI}   {INITIAL CREATED}        
*******************************************************************/        
CREATE  PROCEDURE [bag2].[UPSERT_CONOPS_CYCLE_FULL]       
(      
@G_SITE VARCHAR(5)  ,
@G_ExtractMode VARCHAR(5),  
@G_LasfShift NUMERIC(10)   
)      
AS      
BEGIN   
DECLARE @G_SITE_ALIAS VARCHAR(5)      
SET @G_SITE_ALIAS = CASE WHEN @G_SITE = 'CLI' THEN 'CMX' WHEN @G_SITE ='BAG2' THEN 'BAG' ELSE @G_SITE END      
  
IF @G_ExtractMode = 'FULL'   
  
BEGIN  
EXEC       
(      
'MERGE ' +@G_SITE+ '.CYCLE AS T '      
+' USING (SELECT '       
+' ''' +@G_SITE_ALIAS+ ''' AS SITEFLAG'   
+' ,CYCLE_OID'
+' ,ECF_CLASS_ID'
+' ,STARTTIME_UTC'
+' ,ENDTIME_UTC'
+' ,JOBCODE'
+' ,CREATIONMODE'
+' ,VALIDATIONSEVERITY'
+' ,PRIMARYMACHINE'
+' ,PRIMARYMACHINENAME'
+' ,PRIMARYMACHINECLASS'
+' ,PRIMARYMACHINECLASSNAME'
+' ,PRIMARYMACHINECATEGORY'
+' ,PRIMARYMACHINECATEGORYNAME'
+' ,SECONDARYMACHINE'
+' ,SECONDARYMACHINENAME'
+' ,SECONDARYMACHINECLASS'
+' ,SECONDARYMACHINECLASSNAME'
+' ,SECONDARYMACHINECATEGORY'
+' ,SECONDARYMACHINECATEGORYNAME'
+' ,PRIMARYOPERATOR'
+' ,PRIMARYOPERATORNAME'
+' ,SECONDARYOPERATOR'
+' ,SECONDARYOPERATORNAME'
+' ,ESTIMATEDFUELUSED'
+' ,AVGBURNFUELUSED'
+' ,MACHINEFUELCONSUMED'
+' ,PREVIOUSCYCLE'
+' ,ASSOCIATEDCYCLE'
+' ,VALIDATION_MSG'
+' ,SOURCE_COORD_X'
+' ,SOURCE_COORD_Y'
+' ,SOURCE_COORD_Z'
+' ,SINK_COORD_X'
+' ,SINK_COORD_Y'
+' ,SINK_COORD_Z'
+' ,END_SINK_COORD_X'
+' ,END_SINK_COORD_Y'
+' ,END_SINK_COORD_Z'
+' ,DUMP_COORD_X'
+' ,DUMP_COORD_Y'
+' ,DUMP_COORD_Z'
+' ,HASPREDICTEDROADS'
+' ,AUTONOMOUS'
+' ,HASDELAYS'
+' ,CALCMATERIAL'
+' ,CALCMATERIALNAME'
+' ,DENSITY'
+' ,DENSITYNAME'
+' ,DENSITYTYPE'
+' ,DIPPERCOUNT'
+' ,DIPPERAVERAGESWINGTIME'
+' ,ENDSMU'
+' ,LOADERMATERIAL'
+' ,LOADERMATERIALNAME'
+' ,OPERMATERIAL'
+' ,OPERMATERIALNAME'
+' ,AUTOMATERIAL'
+' ,AUTOMATERIALNAME'
+' ,LOADINGTOOLMODE'
+' ,LOADREPORTCOUNT'
+' ,NOMINALPAYLOAD'
+' ,PAYLOAD'
+' ,REHANDLE'
+' ,SOURCEBLOCK'
+' ,SOURCEBLOCKLEVEL'
+' ,SOURCEBLOCKNAME'
+' ,SOURCELOCATION'
+' ,SOURCELOCATIONNAME'
+' ,STARTSMU'
+' ,LOADTRAVDIST'
+' ,MTTRAVDIST'
+' ,LOADEDHORIZONTALDISTANCE'
+' ,EMPTYHORIZONTALDISTANCE'
+' ,LOADEDEFH'
+' ,EMPTYEFH'
+' ,LOADEDRISEDISTANCE'
+' ,EMPTYRISEDISTANCE'
+' ,LOADEDFALLDISTANCE'
+' ,EMPTYFALLDISTANCE'
+' ,LOADED_COASTING_EFHDIST'
+' ,EMPTY_COASTING_EFHDIST'
+' ,COASTING_TRAVEL_TIME'
+' ,LOADEDTARGETTRAVELTIME'
+' ,EMPTYTARGETTRAVELTIME'
+' ,LOADEDEXPECTEDTRAVELTIME'
+' ,EMPTYEXPECTEDTRAVELTIME'
+' ,LOADEDACTUALTRAVELTIME'
+' ,EMPTYACTUALTRAVELTIME'
+' ,VIMSLOADEDSLOPEDISTANCE'
+' ,VIMSEMPTYSLOPEDISTANCE'
+' ,SINKBLOCK'
+' ,SINKBLOCKNAME'
+' ,SINKLOCATION'
+' ,SINKLOCATIONNAME'
+' ,PROCESSOR'
+' ,PROCESSORCLASSNAME'
+' ,PROCESSORNAME'
+' ,ENDSINKBLOCK'
+' ,ENDSINKBLOCKLEVEL'
+' ,ENDSINKBLOCKNAME'
+' ,ENDSINKLOCATION'
+' ,ENDSINKLOCATIONNAME'
+' ,TRANSMISSIONSHIFTS'
+' ,ENDPROCESSOR'
+' ,ENDPROCESSORCLASSNAME'
+' ,ENDPROCESSORNAME'
+' ,FUELUSED'
+' ,FUELLEVEL'
+' ,LASTBEACONDUMP'
+' ,LASTBEACONDUMPNAME'
+' ,LASTBEACONLOAD'
+' ,LASTBEACONLOADNAME'
+' ,LASTKNOWNMATERIAL'
+' ,LASTKNOWNMATERIALNAME'
+' ,ASSIGNEDSINKLOCATION'
+' ,ASSIGNEDSINKLOCATIONNAME'
+' ,OBSERVEDSINKLOCATION'
+' ,OBSERVEDSINKLOCATIONNAME'
+' ,ACTIVEBLEND'
+' ,FREEDESTPERCENT_MAGNITUDE'
+' ,FREEGRPDESTPERCENT_MAGNITUDE'
+' ,SPILLCYCLE'
+' ,GPSACCURACY'
+' ,BI'
+' ,