
  
    
    
    
/******************************************************************        
* PROCEDURE : BAG2.[UPSERT_CONOPS_DELAYCLASS]      
* PURPOSE : UPSERT [UPSERT_CONOPS_DELAYCLASS]      
* NOTES     :       
* CREATED : MFAHMI      
* SAMPLE    : EXEC BAG2.[UPSERT_CONOPS_DELAYCLASS] 'BAG2'       
* MODIFIED DATE  AUTHOR    DESCRIPTION        
*------------------------------------------------------------------        
* {04 SEP 2024}  {MFAHMI}   {INITIAL CREATED}        
*******************************************************************/        
CREATE  PROCEDURE [bag2].[UPSERT_CONOPS_DELAYCLASS]       
(      
@G_SITE VARCHAR(5)      
)      
AS      
BEGIN   
DECLARE @G_SITE_ALIAS VARCHAR(5)  
  
SET @G_SITE_ALIAS = CASE WHEN @G_SITE = 'CLI' THEN 'CMX' WHEN @G_SITE ='BAG2' THEN 'BAG' ELSE @G_SITE END  
EXEC       
(      
'MERGE ' +@G_SITE+ '.DELAYCLASS AS T '      
+' USING (SELECT '       
+' ''' +@G_SITE_ALIAS+ ''' AS SITEFLAG'   
+' ,DELAYCLASS_OID'
+' ,ACKNOWLEDGEMENTREQ'
+' ,INFIELD'
+' ,DELAYCATEGORY'
+' ,DESCRIPTION'
+' ,DURATION'
+' ,ID'
+' ,NAME'
+' ,IS_ACTIVE'
+' ,PRODUCTIONREPORTINGONLY'
+' ,EXTERNALDESC'
+' ,EXTERNALREF'
+' ,EMAIL'
+' ,ENGINESTOPPED'
+' ,ISVALIDFORROAD'
+' ,ISVALIDFORLOCATION'
+' ,DELAYACTIVITYCLASS'
+' ,MODEL_UPDATE_VERSION'
+' ,LAYER_UPDATE_VERSION'
+' ,GETUTCDATE() AS UTC_CREATED_DATE'
+' FROM ' +@G_SITE+ '.[VIEW_DELAYCLASS_ETL] '  
+' ) AS S '       
+' ON (T.DELAYCLASS_OID = S.DELAYCLASS_OID AND T.SITEFLAG = S.SITEFLAG) '       
+' WHEN MATCHED '       
+' THEN UPDATE SET '       
+' T.ACKNOWLEDGEMENTREQ = S.ACKNOWLEDGEMENTREQ'
+' ,T.INFIELD = S.INFIELD'
+' ,T.DELAYCATEGORY = S.DELAYCATEGORY'
+' ,T.DESCRIPTION = S.DESCRIPTION'
+' ,T.DURATION = S.DURATION'
+' ,T.ID = S.ID'
+' ,T.NAME = S.NAME'
+' ,T.IS_ACTIVE = S.IS_ACTIVE'
+' ,T.PRODUCTIONREPORTINGONLY = S.PRODUCTIONREPORTINGONLY'
+' ,T.EXTERNALDESC = S.EXTERNALDESC'
+' ,T.EXTERNALREF = S.EXTERNALREF'
+' ,T.EMAIL = S.EMAIL'
+' ,T.ENGINESTOPPED = S.ENGINESTOPPED'
+' ,T.ISVALIDFORROAD = S.ISVALIDFORROAD'
+' ,T.ISVALIDFORLOCATION = S.ISVALIDFORLOCATION'
+' ,T.DELAYACTIVITYCLASS = S.DELAYACTIVITYCLASS'
+' ,T.MODEL_UPDATE_VERSION = S.MODEL_UPDATE_VERSION'
+' ,T.LAYER_UPDATE_VERSION = S.LAYER_UPDATE_VERSION'
+' ,T.UTC_CREATED_DATE = S.UTC_CREATED_DATE '           
+' WHEN NOT MATCHED '       
+' THEN INSERT ( '       
+' SITEFLAG'
+' ,DELAYCLASS_OID'
+' ,ACKNOWLEDGEMENTREQ'
+' ,INFIELD'
+' ,DELAYCATEGORY'
+' ,DESCRIPTION'
+' ,DURATION'
+' ,ID'
+' ,NAME'
+' ,IS_ACTIVE'
+' ,PRODUCTIONREPORTINGONLY'
+' ,EXTERNALDESC'
+' ,EXTERNALREF'
+' ,EMAIL'
+' ,ENGINESTOPPED'
+' ,ISVALIDFORROAD'
+' ,ISVALIDFORLOCATION'
+' ,DELAYACTIVITYCLASS'
+' ,MODEL_UPDATE_VERSION'
+' ,LAYER_UPDATE_VERSION'
+' ,UTC_CREATED_DATE'    
+'  ) VALUES( '       
+' S.SITEFLAG'
+' ,S.DELAYCLASS_OID'
+' ,S.ACKNOWLEDGEMENTREQ'
+' ,S.INFIELD'
+' ,S.DELAYCATEGORY'
+' ,S.DESCRIPTION'
+' ,S.DURATION'
+' ,S.ID'
+' ,S.NAME'
+' ,S.IS_ACTIVE'
+' ,S.PRODUCTIONREPORTINGONLY'
+' ,S.EXTERNALDESC'
+' ,S.EXTERNALREF'
+' ,S.EMAIL'
+' ,S.ENGINESTOPPED'
+' ,S.ISVALIDFORROAD'
+' ,S.ISVALIDFORLOCATION'
+' ,S.DELAYACTIVITYCLASS'
+' ,S.MODEL_UPDATE_VERSION'
+' ,S.LAYER_UPDATE_VERSION'
+' ,S.UTC_CREATED_DATE'

+' ); '       

--Compare to stage
+'  DELETE    '
+' FROM  ' +@G_SITE+ '.[DELAYCLASS]    '  
+' WHERE NOT EXISTS    '
+' (SELECT 1    '
+' FROM  ' +@G_SITE+ '.[VIEW_DELAYCLASS_ETL]  AS stg     '
+' WHERE     '
+' stg.DELAYCLASS_OID = ' +@G_SITE+ '.[DELAYCLASS].DELAYCLASS_OID    '
+'); '   
   
 );      
END      
      
