
  
    
    
    
/******************************************************************        
* PROCEDURE : BAG2.[UPSERT_CONOPS_GRADEBLOCK]      
* PURPOSE : UPSERT [UPSERT_CONOPS_GRADEBLOCK]      
* NOTES     :       
* CREATED : MFAHMI      
* SAMPLE    : EXEC BAG2.[UPSERT_CONOPS_GRADEBLOCK] 'BAG2'       
* MODIFIED DATE  AUTHOR    DESCRIPTION        
*------------------------------------------------------------------        
* {04 SEP 2024}  {MFAHMI}   {INITIAL CREATED}        
*******************************************************************/        
CREATE  PROCEDURE [bag2].[UPSERT_CONOPS_GRADEBLOCK]       
(      
@G_SITE VARCHAR(5)      
)      
AS      
BEGIN   
DECLARE @G_SITE_ALIAS VARCHAR(5)  
  
SET @G_SITE_ALIAS = CASE WHEN @G_SITE = 'CLI' THEN 'CMX' WHEN @G_SITE ='BAG2' THEN 'BAG' ELSE @G_SITE END  
EXEC       
(        
'MERGE ' +@G_SITE+ '.GRADEBLOCK AS T '        
+' USING (SELECT '         
+' ''' +@G_SITE_ALIAS+ ''' AS SITEFLAG'     
+' ,GRADEBLOCK_OID'  
+' ,MININGFINISH_UTC'  
+' ,MININGSTART_UTC'  
+' ,HEIGHT'  
+' ,ID'  
+' ,MATERIAL'  
+' ,MINEDMASS'  
+' ,MINEDVOL'  
+' ,NAME'  
+' ,ORIGINALVOL'  
+' ,ORIGINALMASS'  
+' ,STOCKPILE'  
+' ,IS_ACTIVE'  
+' ,INUSE'  
+' ,READONLY'  
+' ,VERSION'  
+' ,HIERARCHY'  
+' ,GRADEENGINE'  
+' ,TARGETDESTINATION'  
+' ,EXTERNALREF'  
+' ,EXTERNALDESC'  
+' ,CREATETIME_UTC'  
+' ,OPENFORDUMPING'  
+' ,OPENFORLOADING'  
+' ,CARRYOPTION'  
+' ,CARRY_FROM_OID'  
+' ,ENTRY_WAYPOINT_OID'  
+' ,CONNECTING_WAYPOINT_OID'  
+' ,DESTINATION_OID'  
+' ,PROCESSOR_OID'  
+' ,MODEL_UPDATE_VERSION'  
+' ,LAYER_UPDATE_VERSION'  
+' ,GETUTCDATE() AS UTC_CREATED_DATE'  
+' FROM ' +@G_SITE+ '.[VIEW_GRADEBLOCK_ETL] '    
+' ) AS S '         
+' ON (T.GRADEBLOCK_OID = S.GRADEBLOCK_OID AND T.SITEFLAG = S.SITEFLAG) '         
+' WHEN MATCHED '         
+' THEN UPDATE SET '         
+' T.MININGFINISH_UTC = S.MININGFINISH_UTC'  
+' ,T.MININGSTART_UTC = S.MININGSTART_UTC'  
+' ,T.HEIGHT = S.HEIGHT'  
+' ,T.ID = S.ID'  
+' ,T.MATERIAL = S.MATERIAL'  
+' ,T.MINEDMASS = S.MINEDMASS'  
+' ,T.MINEDVOL = S.MINEDVOL'  
+' ,T.NAME = S.NAME'  
+' ,T.ORIGINALVOL = S.ORIGINALVOL'  
+' ,T.ORIGINALMASS = S.ORIGINALMASS'  
+' ,T.STOCKPILE = S.STOCKPILE'  
+' ,T.IS_ACTIVE = S.IS_ACTIVE'  
+' ,T.INUSE = S.INUSE'  
+' ,T.READONLY = S.READONLY'  
+' ,T.VERSION = S.VERSION'  
+' ,T.HIERARCHY = S.HIERARCHY'  
+' ,T.GRADEENGINE = S.GRADEENGINE'  
+' ,T.TARGETDESTINATION = S.TARGETDESTINATION'  
+' ,T.EXTERNALREF = S.EXTERNALREF'  
+' ,T.EXTERNALDESC = S.EXTERNALDESC'  
+' ,T.CREATETIME_UTC = S.CREATETIME_UTC'  
+' ,T.OPENFORDUMPING = S.OPENFORDUMPING'  
+' ,T.OPENFORLOADING = S.OPENFORLOADING'  
+' ,T.CARRYOPTION = S.CARRYOPTION'  
+' ,T.CARRY_FROM_OID = S.CARRY_FROM_OID'  
+' ,T.ENTRY_WAYPOINT_OID = S.ENTRY_WAYPOINT_OID'  
+' ,T.CONNECTING_WAYPOINT_OID = S.CONNECTING_WAYPOINT_OID'  
+' ,T.DESTINATION_OID = S.DESTINATION_OID'  
+' ,T.PROCESSOR_OID = S.PROCESSOR_OID'  
+' ,T.MODEL_UPDATE_VERSION = S.MODEL_UPDATE_VERSION'  
+' ,T.LAYER_UPDATE_VERSION = S.LAYER_UPDATE_VERSION'  
+' ,T.UTC_CREATED_DATE = S.UTC_CREATED_DATE '                
+' WHEN NOT MATCHED '         
+' THEN INSERT ( '         
+' SITEFLAG'  
+' ,GRADEBLOCK_OID'  
+' ,MININGFINISH_UTC'  
+' ,MININGSTART_UTC'  
+' ,HEIGHT'  
+' ,ID'  
+' ,MATERIAL'  
+' ,MINEDMASS'  
+' ,MINEDVOL'  
+' ,NAME'  
+' ,ORIGINALVOL'  
+' ,ORIGINALMASS'  
+' ,STOCKPILE'  
+' ,IS_ACTIVE'  
+' ,INUSE'  
+' ,READONLY'  
+' ,VERSION'  
+' ,HIERARCHY'  
+' ,GRADEENGINE'  
+' ,TARGETDESTINATION'  
+' ,EXTERNALREF'  
+' ,EXTERNALDESC'  
+' ,CREATETIME_UTC'  
+' ,OPENFORDUMPING'  
+' ,OPENFORLOADING'  
+' ,CARRYOPTION'  
+' ,CARRY_FROM_OID'  
+' ,ENTRY_WAYPOINT_OID'  
+' ,CONNECTING_WAYPOINT_OID'  
+' ,DESTINATION_OID'  
+' ,PROCESSOR_OID'  
+' ,MODEL_UPDATE_VERSION'  
+' ,LAYER_UPDATE_VERSION'  
+' ,UTC_CREATED_DATE'        
+'  ) VALUES( 