CREATE TABLE [cer].[pit_worker_test] (
    [siteflag] varchar(4) NOT NULL,
    [DbPrevious] bigint NULL,
    [DbNext] bigint NULL,
    [DbVersion] int NULL,
    [ID] bigint NOT NULL,
    [DBNAME] nvarchar(32) NOT NULL,
    [DbKey] bigint NOT NULL,
    [FieldId] nvarchar(20) NULL,
    [FieldNumer] int NULL,
    [FieldShifts] smallint NULL,
    [FieldStatus] bigint NULL,
    [FieldLineupcrew] bigint NULL,
    [FieldCrew] bigint NULL,
    [FieldDept] bigint NULL,
    [FieldName] nvarchar(40) NULL,
    [FieldSeniority] nvarchar(7) NULL,
    [FieldRegionlock] bigint NULL,
    [FieldLoc] bigint NULL,
    [FieldLoctime] bigint NULL,
    [FieldRoster] bigint NULL,
    [FieldRosterhist] bigint NULL,
    [FieldLogincrew] bigint NULL,
    [FieldFatgmode] bigint NULL,
    [FieldFatgwarntype] bigint NULL,
    [FieldFatgwarnpassed] int NULL,
    [FieldNextfatgwarndue] bigint NULL,
    [FieldFatgwarnsent] bigint NULL,
    [FieldFatgrespexptd] nvarchar(5) NULL,
    [FieldFatgddblink] nvarchar(12) NULL,
    [FieldArea] smallint NULL,
    [logical_delete_flag] char(1) NOT NULL,
    [orig_src_id] int NOT NULL,
    [site_code] varchar(4) NOT NULL,
    [capture_ts_utc] datetimeoffset NOT NULL,
    [integrate_ts_utc] datetimeoffset NOT NULL,
    [FIELDLCOMMENT] int NULL
);