CREATE TABLE [cer].[PLAN_VALUES_SHOVEL] (
    [SITEFLAG] varchar(5) NOT NULL,
    [CONTENTTYPEID] varchar(100) NOT NULL,
    [TITLE] varchar(100) NULL,
    [COMPLIANCEASSETID] varchar(100) NULL,
    [FECHA] date NOT NULL,
    [TURNO] varchar(100) NULL,
    [PROCESO] varchar(100) NULL,
    [PALA] varchar(100) NULL,
    [NIVEL] decimal(18,5) NULL,
    [FASE] varchar(100) NULL,
    [TONELADAS] decimal(18,5) NULL,
    [PROPORCION] decimal(18,5) NULL,
    [TCU] decimal(18,5) NULL,
    [REC] decimal(18,5) NULL,
    [MOLY] decimal(18,5) NULL,
    [ASCU] decimal(18,5) NULL,
    [CNCU] decimal(18,5) NULL,
    [FEPPM] decimal(18,5) NULL,
    [ASPPM] decimal(18,5) NULL,
    [BWIKWHTC] decimal(18,5) NULL,
    [UCSMPA] decimal(18,5) NULL,
    [RQD] decimal(18,5) NULL,
    [SCLAY] decimal(18,5) NULL,
    [KAO] decimal(18,5) NULL,
    [TOTALCLAY] decimal(18,5) NULL,
    [OXID] decimal(18,5) NULL,
    [MAGD] decimal(18,5) NULL,
    [IS] decimal(18,5) NULL,
    [PRIORIDADPALA] decimal(18,5) NULL,
    [TON_REMANENTE] decimal(18,5) NULL,
    [ID] int NOT NULL,
    [CONTENTTYPE] varchar(50) NOT NULL,
    [MODIFIED] datetime NOT NULL,
    [CREATED] datetime NOT NULL,
    [CREATEDBYID] int NOT NULL,
    [MODIFIEDBYID] int NOT NULL,
    [OWSHIDDENVERSION] int NOT NULL,
    [VERSION] decimal(10,5) NOT NULL,
    [PATH] varchar(2000) NOT NULL,
    [UTC_CREATED_DATE] datetime NULL
);