CREATE TABLE [cer].[ZZZ_lh2_shift_eqmt_b_temp] (
    [DbPrevious] bigint NULL,
    [DbNext] bigint NULL,
    [DbVersion] int NULL,
    [ShiftId] bigint NULL,
    [shift_eqmt_id] bigint NOT NULL DEFAULT ((0)),
    [shift_dbname] nvarchar(32) NOT NULL DEFAULT (''),
    [DbKey] bigint NOT NULL DEFAULT ((0)),
    [FieldId] nvarchar(12) NULL,
    [FieldPit] bigint NULL,
    [FieldRegionlock] bigint NULL,
    [FieldSize] float NULL,
    [FieldTmph] float NULL,
    [FieldReason] smallint NULL,
    [FieldUnit] bigint NULL,
    [FieldStatus] bigint NULL,
    [FieldExtraload] tinyint NULL,
    [FieldNoassign] tinyint NULL,
    [FieldLoadstart] bigint NULL,
    [FieldEqmttype] bigint NULL,
    [FieldComment] nvarchar(90) NULL,
    [FieldReasonrec] bigint NULL,
    [FieldOper] bigint NULL,
    [FieldAudit] bigint NULL,
    [FieldSubcode] int NULL,
    [FieldSubcode2] int NULL,
    [FieldSituation] nvarchar(20) NULL,
    [FieldUser] int NULL,
    [FieldMaintstart] bigint NULL,
    [FieldMaintpropose] bigint NULL,
    [FieldWarranty] tinyint NULL,
    [FieldEnghr] float NULL,
    [FieldEnghr2] float NULL,
    [FieldEnghrtime] bigint NULL,
    [FieldEnghrtime2] bigint NULL,
    [FieldIsauxil] tinyint NULL,
    [FieldPmid] nvarchar(30) NULL,
    [capture_ts_utc] datetimeoffset NOT NULL DEFAULT ('01-jan-0001 00:00:00'),
    [integrate_ts_utc] datetimeoffset NOT NULL DEFAULT ('01-jan-0001 00:00:00'),
    [logical_delete_flag] char(1) NOT NULL DEFAULT (''),
    [orig_src_id] int NOT NULL DEFAULT ((0)),
    [site_code] varchar(4) NOT NULL DEFAULT (''),
    [Shiftdate] datetime2 NULL
);