CREATE TABLE [cer].[ZZZ_lh2_shift_load_b_temp] (
    [DbPrevious] bigint NULL,
    [DbNext] bigint NULL,
    [DbVersion] int NULL,
    [ShiftId] bigint NULL,
    [shift_load_id] bigint NOT NULL DEFAULT ((0)),
    [shift_dbname] nvarchar(32) NOT NULL DEFAULT (''),
    [DbKey] bigint NOT NULL DEFAULT ((0)),
    [FieldId] nvarchar(4) NULL,
    [FieldTruck] bigint NULL,
    [FieldExcav] bigint NULL,
    [FieldGrade] bigint NULL,
    [FieldLoc] bigint NULL,
    [FieldDumprec] bigint NULL,
    [FieldTons] float NULL,
    [FieldTimearrive] int NULL,
    [FieldTimeload] int NULL,
    [FieldTimefull] int NULL,
    [FieldCalctravtime] int NULL,
    [FieldLoad] bigint NULL,
    [FieldExtraload] tinyint NULL,
    [FieldLoadtype] bigint NULL,
    [FieldDist] int NULL,
    [FieldEfh] int NULL,
    [FieldToper] bigint NULL,
    [FieldEoper] bigint NULL,
    [FieldOrigasn] nvarchar(24) NULL,
    [FieldReasnby] nvarchar(20) NULL,
    [FieldPathtravtime] int NULL,
    [FieldExptraveltime] int NULL,
    [FieldExptraveldist] int NULL,
    [FieldGpstraveldist] int NULL,
    [FieldLocactlc] nvarchar(24) NULL,
    [FieldLocacttp] smallint NULL,
    [FieldLocactrl] nvarchar(24) NULL,
    [FieldFirstdipper] int NULL,
    [FieldLastdipper] int NULL,
    [FieldBktcnt] int NULL,
    [FieldPandhbucketloads] nvarchar(12) NULL,
    [FieldAudit] bigint NULL,
    [FieldWeightst] bigint NULL,
    [FieldWeightmeas] float NULL,
    [FieldMeasuretime] bigint NULL,
    [FieldGpsxtkl] float NULL,
    [FieldGpsytkl] float NULL,
    [FieldGpsxex] float NULL,
    [FieldGpsyex] float NULL,
    [FieldGpsstatex] smallint NULL,
    [FieldGpsstattk] smallint NULL,
    [FieldGpsheadtk] smallint NULL,
    [FieldGpsveltk] smallint NULL,
    [FieldPvs3id] nvarchar(30) NULL,
    [FieldBktsum] bigint NULL,
    [FieldDumpasn] bigint NULL,
    [FieldLsizetons] float NULL,
    [FieldLsizeid] nvarchar(10) NULL,
    [FieldLsizeversion] smallint NULL,
    [FieldLsizedb] float NULL,
    [FieldFuelremain] int NULL,
    [FieldFactapply] float NULL,
    [FieldDlock] nvarchar(24) NULL,
    [FieldElock] nvarchar(24) NULL,
    [FieldEdlock] nvarchar(24) NULL,
    [FieldRlock] nvarchar(24) NULL,
    [FieldReconstat] bigint NULL,
    [FieldTimearrivemobile] bigint NULL,
    [FieldTimeloadmobile] bigint NULL,
    [FieldTimefullmobile] bigint NULL,
    [logical_delete_flag] char(1) NOT NULL DEFAULT (''),
    [orig_src_id] int NOT NULL DEFAULT ((0)),
    [site_code] varchar(4) NOT NULL DEFAULT (''),
    [Shiftdate] datetime2 NULL,
    [capture_ts_utc] datetimeoffset NOT NULL DEFAULT ('01-jan-0001 00:00:00'),
    [integrate_ts_utc] datetimeoffset NOT NULL DEFAULT ('01-jan-0001 00:00:00')
);