CREATE TABLE [cer].[ZZZ_lh2_pit_loc_b_temp] (
    [DbPrevious] bigint NULL,
    [DbNext] bigint NULL,
    [DbVersion] int NULL,
    [pit_loc_id] bigint NOT NULL DEFAULT ((0)),
    [pit_dbname] nvarchar(32) NOT NULL DEFAULT (''),
    [DbKey] bigint NOT NULL DEFAULT ((0)),
    [FieldId] nvarchar(24) NULL,
    [FieldPit] bigint NULL,
    [FieldRegion] bigint NULL,
    [FieldBlendrec] bigint NULL,
    [FieldPath] bigint NULL,
    [FieldBean] bigint NULL,
    [FieldInvbean] bigint NULL,
    [FieldHaul] float NULL,
    [FieldOre] float NULL,
    [FieldDumpfeed] float NULL,
    [FieldDumpcapy] float NULL,
    [FieldBinsize] float NULL,
    [FieldXloc] int NULL,
    [FieldYloc] int NULL,
    [FieldPathix] int NULL,
    [FieldTimedump] int NULL,
    [FieldZloc] float NULL,
    [FieldSignid] int NULL,
    [FieldUnit] bigint NULL,
    [FieldLoad] bigint NULL,
    [FieldIstiedown] tinyint NULL,
    [FieldStatus] bigint NULL,
    [FieldLinestat] bigint NULL,
    [FieldSpillage] tinyint NULL,
    [FieldSignpost] smallint NULL,
    [FieldShoptype] bigint NULL,
    [FieldDumpqueue] smallint NULL,
    [FieldPctcapy] smallint NULL,
    [FieldBays] smallint NULL,
    [FieldNopenalty] tinyint NULL,
    [FieldTimelast] int NULL,
    [FieldRadius] int NULL,
    [FieldGpstype] bigint NULL,
    [FieldReason] smallint NULL,
    [FieldIvtrec] bigint NULL,
    [FieldTdset] int NULL,
    [FieldPrior] smallint NULL,
    [FieldAvailbays] smallint NULL,
    [FieldParkqueue] smallint NULL,
    [FieldLaststattime] int NULL,
    [FieldBcntime] tinyint NULL,
    [FieldTagdate] bigint NULL,
    [FieldTageqmt] nvarchar(10) NULL,
    [FieldTrucksenroute] int NULL,
    [FieldLastassign] bigint NULL,
    [FieldLastarrive] bigint NULL,
    [FieldSpeedtrap] tinyint NULL,
    [FieldLvsproxcnt] int NULL,
    [FieldIgnunexarr] tinyint NULL,
    [FieldMetadata] nvarchar(20) NULL,
    [FieldDisablearrchk] tinyint NULL,
    [FieldIntf_data1] nvarchar(50) NULL,
    [FieldIntf_data2] nvarchar(50) NULL,
    [FieldIntf_data3] nvarchar(50) NULL,
    [logical_delete_flag] char(1) NOT NULL DEFAULT (''),
    [orig_src_id] int NOT NULL DEFAULT ((0)),
    [site_code] varchar(4) NOT NULL DEFAULT (''),
    [capture_ts_utc] datetimeoffset NOT NULL DEFAULT ('01-jan-0001 00:00:00'),
    [integrate_ts_utc] datetimeoffset NOT NULL DEFAULT ('01-jan-0001 00:00:00')
);