CREATE TABLE [cer].[ZZZ_lh2_shift_loc_b_temp] (
    [DbPrevious] bigint NULL,
    [DbNext] bigint NULL,
    [DbVersion] int NULL,
    [ShiftId] bigint NULL,
    [shift_loc_id] bigint NOT NULL DEFAULT ((0)),
    [shift_dbname] nvarchar(32) NOT NULL DEFAULT (''),
    [DbKey] bigint NOT NULL DEFAULT ((0)),
    [FieldId] nvarchar(24) NULL,
    [FieldPit] bigint NULL,
    [FieldRegion] bigint NULL,
    [FieldElev] float NULL,
    [FieldUnit] bigint NULL,
    [FieldStatus] bigint NULL,
    [FieldReason] smallint NULL,
    [FieldReasonrec] bigint NULL,
    [FieldAudit] bigint NULL,
    [FieldMetadata] nvarchar(20) NULL,
    [capture_ts_utc] datetimeoffset NOT NULL DEFAULT ('01-jan-0001 00:00:00'),
    [integrate_ts_utc] datetimeoffset NOT NULL DEFAULT ('01-jan-0001 00:00:00'),
    [logical_delete_flag] char(1) NOT NULL DEFAULT (''),
    [orig_src_id] int NOT NULL DEFAULT ((0)),
    [site_code] varchar(4) NOT NULL DEFAULT (''),
    [Shiftdate] datetime2 NULL
);