CREATE TABLE [cer].[ZZZ_lh2_pit_worker_b_temp] (
    [DbPrevious] bigint NULL,
    [DbNext] bigint NULL,
    [DbVersion] int NULL,
    [pit_worker_id] bigint NOT NULL DEFAULT ((0)),
    [pit_dbname] nvarchar(32) NOT NULL DEFAULT (''),
    [DbKey] bigint NOT NULL DEFAULT ((0)),
    [FieldId] nvarchar(20) NULL,
    [FieldNumer] int NULL,
    [FieldShifts] smallint NULL,
    [FieldStatus] bigint NULL,
    [FieldLineupcrew] bigint NULL,
    [FieldCrew] bigint NULL,
    [FieldDept] bigint NULL,
    [FieldName] nvarchar(40) NULL,
    [FieldSeniority] nvarchar(7) NULL,
    [FieldRegionlock] bigint NULL,
    [FieldLoc] bigint NULL,
    [FieldLoctime] bigint NULL,
    [FieldRoster] bigint NULL,
    [FieldRosterhist] bigint NULL,
    [FieldLogincrew] bigint NULL,
    [FieldFatgmode] bigint NULL,
    [FieldFatgwarntype] bigint NULL,
    [FieldFatgwarnpassed] int NULL,
    [FieldNextfatgwarndue] bigint NULL,
    [FieldFatgwarnsent] bigint NULL,
    [FieldFatgrespexptd] nvarchar(5) NULL,
    [FieldFatgddblink] nvarchar(12) NULL,
    [FieldArea] smallint NULL,
    [logical_delete_flag] char(1) NOT NULL DEFAULT (''),
    [orig_src_id] int NOT NULL DEFAULT ((0)),
    [site_code] varchar(4) NOT NULL DEFAULT (''),
    [capture_ts_utc] datetimeoffset NOT NULL DEFAULT ('01-jan-0001 00:00:00'),
    [integrate_ts_utc] datetimeoffset NOT NULL DEFAULT ('01-jan-0001 00:00:00')
);