CREATE TABLE [cer].[ZZZ_lh2_pit_aux_b_temp] (
    [DbPrevious] bigint NULL,
    [DbNext] bigint NULL,
    [DbVersion] int NULL,
    [pit_aux_id] bigint NOT NULL DEFAULT ((0)),
    [pit_dbname] nvarchar(32) NOT NULL DEFAULT (''),
    [DbKey] bigint NOT NULL DEFAULT ((0)),
    [FieldId] nvarchar(12) NULL,
    [FieldLoc] bigint NULL,
    [FieldExcav] bigint NULL,
    [FieldAux] bigint NULL,
    [FieldVan] bigint NULL,
    [FieldReglock] bigint NULL,
    [FieldBaysplit] int NULL,
    [FieldSendcount] int NULL,
    [FieldRcvcount] int NULL,
    [FieldTimelate] int NULL,
    [FieldClock] int NULL,
    [FieldTimeassign] int NULL,
    [FieldTimelast] int NULL,
    [FieldTimenext] int NULL,
    [FieldPanelid] smallint NULL,
    [FieldLinereason] smallint NULL,
    [FieldReason] smallint NULL,
    [FieldUnit] bigint NULL,
    [FieldUnitloc] bigint NULL,
    [FieldStatus] bigint NULL,
    [FieldLogin] bigint NULL,
    [FieldPort] smallint NULL,
    [FieldLinestat] bigint NULL,
    [FieldEqmttype] bigint NULL,
    [FieldComment] nvarchar(90) NULL,
    [FieldLinecmt] nvarchar(90) NULL,
    [FieldActsim] bigint NULL,
    [FieldActlast] bigint NULL,
    [FieldVsmstbl] smallint NULL,
    [FieldXloc] int NULL,
    [FieldYloc] int NULL,
    [FieldRadius] int NULL,
    [FieldVelocity] smallint NULL,
    [FieldHeading] smallint NULL,
    [FieldDirection] smallint NULL,
    [FieldTiedownaccepted] tinyint NULL,
    [FieldZ] int NULL,
    [FieldLaststatustime] int NULL,
    [FieldLaststatreason] smallint NULL,
    [FieldTiedownproposed] bigint NULL,
    [FieldLastbreak] bigint NULL,
    [FieldCuroper] bigint NULL,
    [FieldCurscope] bigint NULL,
    [FieldCurbreak] bigint NULL,
    [FieldFsgroup] bigint NULL,
    [FieldHpgps] bigint NULL,
    [FieldPv3sup] tinyint NULL,
    [FieldLastrftagtime] bigint NULL,
    [FieldPrestartdone] nvarchar(197) NULL,
    [FieldPresunit] bigint NULL,
    [FieldLvsproxcnt] int NULL,
    [FieldLastgpsupdate] bigint NULL,
    [FieldGpsok] tinyint NULL,
    [FieldFueltank] int NULL,
    [FieldFuelremain] int NULL,
    [FieldLastfuelcalc] bigint NULL,
    [FieldFueltime] bigint NULL,
    [FieldFuelfact] float NULL,
    [FieldOemfueltime] bigint NULL,
    [FieldHdwtype] bigint NULL,
    [FieldVansize] int NULL,
    [FieldVanoccupied] int NULL,
    [FieldMaintdate] bigint NULL,
    [FieldLastservicedate] bigint NULL,
    [FieldMainthours] int NULL,
    [FieldEnghr] float NULL,
    [FieldEnghrtime] bigint NULL,
    [FieldEqreq] nvarchar(90) NULL,
    [FieldTanksize] int NULL,
    [FieldTankremain] int NULL,
    [FieldSpray] tinyint NULL,
    [FieldGrade] nvarchar(35) NULL,
    [FieldAuxsched] bigint NULL,
    [FieldAuxtask] int NULL,
    [FieldLocnext] bigint NULL,
    [FieldLoclast] bigint NULL,
    [FieldExpected] int NULL,
    [FieldActnext] bigint NULL,
    [FieldPmid] nvarchar(30) NULL,
    [FieldTdbar] tinyint NULL,
    [FieldTdrelease] bigint NULL,
    [FieldDevver] nvarchar(16) NULL,
    [FieldDevhw] int NULL,
    [FieldDevbc] int NULL,
    [FieldDevop] int NULL,
    [FieldRuntime] float NULL,
    [FieldFuelenghr] float NULL,
    [FieldIntf_data] nvarchar(50) NULL,
    [capture_ts_utc] datetimeoffset NOT NULL DEFAULT ('01-jan-0001 00:00:00'),
    [integrate_ts_utc] datetimeoffset NOT NULL DEFAULT ('01-jan-0001 00:00:00'),
    [logical_delete_flag] char(1) NOT NULL DEFAULT (''),
    [orig_src_id] int NOT NULL DEFAULT ((0)),
    [site_code] varchar(4) NOT NULL DEFAULT ('')
);