CREATE VIEW [MOR].[CONOPS_MOR_AUTONOMOUS_TRUCK_V] AS



--select * from [MOR].[CONOPS_MOR_AUTONOMOUS_TRUCK_V]
CREATE VIEW [MOR].[CONOPS_MOR_AUTONOMOUS_TRUCK_V]
AS

SELECT DISTINCT 
	FieldId AS TruckId,
	0 AS Autonomous
FROM MOR.pit_truck_c WITH(NOLOCK)
WHERE FieldId IS NOT NULL
	AND FieldId <> ''


