CREATE VIEW [MOR].[PIT_TRUCK] AS



--SELECT * FROM MOR.PIT_TRUCK
CREATE VIEW MOR.PIT_TRUCK
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM MOROperational.dbo.PITTruck WITH(NOLOCK)



