CREATE VIEW [MOR].[PIT_AUXEQMT] AS



--SELECT * FROM MOR.PIT_AUXEQMT
CREATE VIEW MOR.PIT_AUXEQMT
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM MOROperational.dbo.PITAuxeqmt



