CREATE VIEW [MOR].[PIT_EXCAV] AS



--SELECT * FROM MOR.PIT_EXCAV
CREATE VIEW MOR.PIT_EXCAV
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM MOROperational.dbo.PITExcav



