CREATE VIEW [MOR].[PIT_WORKER] AS



--SELECT * FROM MOR.PIT_WORKER
CREATE VIEW MOR.PIT_WORKER
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM MOROperational.dbo.PITWorker



