/*****************************************************************************************
* TABLE     : DRILLBLAST_OPERATOR_INCR
* SCHEMA    : DEV_API_REF.FUSE
* SOURCE    : PROD_WG.DRILL_BLAST.DRILLBLAST_OPERATOR
* DATE: 2026-01-23 | AUTHOR: CARLOS CARRILLO
******************************************************************************************/
create or replace TABLE DEV_API_REF.FUSE.DRILLBLAST_OPERATOR_INCR (
	SYSTEM_OPERATOR_ID NUMBER(19,0) NOT NULL,
	SITE_CODE VARCHAR(5) NOT NULL COLLATE 'en-ci',
	ORIG_SRC_ID NUMBER(10,0),
	APPLICATION_OPERATOR_ID VARCHAR(255) COLLATE 'en-ci',
	OPERATOR_NAME VARCHAR(255) COLLATE 'en-ci',
	CREW_ID NUMBER(10,0),
	CREW_NAME VARCHAR(255) COLLATE 'en-ci',
	SAP_OPERATOR_ID VARCHAR(255) COLLATE 'en-ci',
	EFFECTIVE_START_DATE TIMESTAMP_NTZ(9),
	END_DATE TIMESTAMP_NTZ(9),
	SYSTEM_VERSION VARCHAR(255) COLLATE 'en-ci',
	DW_LOGICAL_DELETE_FLAG VARCHAR(1) COLLATE 'en-ci' DEFAULT 'N',
	DW_LOAD_TS TIMESTAMP_NTZ(0),
	DW_MODIFY_TS TIMESTAMP_NTZ(0)
)COMMENT='Incremental table for DRILLBLAST_OPERATOR'
;

