/*****************************************************************************************
* TABLE     : LH_LOADING_CYCLE_INCR
* SCHEMA    : DEV_API_REF.FUSE
* SOURCE    : PROD_WG.LOAD_HAUL.LH_LOADING_CYCLE
* DATE: 2026-01-27 | AUTHOR: CARLOS CARRILLO
******************************************************************************************/
create or replace TABLE DEV_API_REF.FUSE.LH_LOADING_CYCLE_INCR (
	LOADING_CYCLE_ID NUMBER(19,0) NOT NULL,
	SITE_CODE VARCHAR(4) COLLATE 'en-ci',
	ORIG_SRC_ID NUMBER(38,0),
	SHIFT_ID VARCHAR(12) COLLATE 'en-ci',
	LOADING_CYCLE_OF_SHIFT NUMBER(38,0),
	EXCAV_CYCLE_OF_SHIFT NUMBER(38,0),
	CYCLE_START_TS_UTC TIMESTAMP_NTZ(3),
	CYCLE_START_TS_LOCAL TIMESTAMP_NTZ(3),
	CYCLE_END_TS_UTC TIMESTAMP_NTZ(3),
	CYCLE_END_TS_LOCAL TIMESTAMP_NTZ(3),
	MEASURED_PAYLOAD_SHORT_TONS NUMBER(38,6),
	MEASURED_PAYLOAD_METRIC_TONS NUMBER(38,6),
	AVG_SWING_DURATION_MINS NUMBER(38,6),
	AVG_DIG_DURATION_MINS NUMBER(38,6),
	HANG_DURATION_MINS NUMBER(38,6),
	IDLE_DURATION_MINS NUMBER(38,6),
	BUCKET_COUNT NUMBER(38,0),
	EXCAV_ID NUMBER(19,0),
	TRUCK_ID NUMBER(19,0),
	EXCAV_OPERATOR_ID NUMBER(19,0),
	MATERIAL_ID NUMBER(19,0),
	LOADING_LOC_ID NUMBER(19,0),
	LOADING_CYCLE_DIG_ELEV_AVG_FEET FLOAT,
	LOADING_CYCLE_DIG_ELEV_AVG_METERS FLOAT,
	INTERRUPTED_LOADING_FLAG NUMBER(1,0),
	ASSOCIATED_HAUL_CYCLE_FLAG NUMBER(1,0),
	OVER_TRUCKED_FLAG NUMBER(1,0),
	UNDER_TRUCKED_FLAG NUMBER(1,0),
	HAUL_CYCLE_ID NUMBER(19,0),
	SYSTEM_VERSION VARCHAR(50) COLLATE 'en-ci',
	DW_LOGICAL_DELETE_FLAG VARCHAR(1) COLLATE 'en-ci' DEFAULT 'N',
	DW_LOAD_TS TIMESTAMP_NTZ(0),
	DW_MODIFY_TS TIMESTAMP_NTZ(0)
)COMMENT='Incremental table for LH_LOADING_CYCLE - MERGE-driven upserts with 3-day incremental window'
;

