CREATE VIEW [BAG].[CONOPS_BAG_EOS_IOS_STOCKPILE_V] AS

  
 
--SELECT * FROM [bag].[CONOPS_BAG_EOS_IOS_STOCKPILE_V] WITH (NOLOCK) WHERE SHIFTFLAG = 'CURR'    
CREATE VIEW [bag].[CONOPS_BAG_EOS_IOS_STOCKPILE_V]    
AS    


WITH CTE AS (
SELECT 
[SITEFLAG]  
,[SHIFTINDEX]  
,[CRUSHERLOC]   
,[COMPONENT]  
,[SENSORVALUE],
ROW_NUMBER() OVER (PARTITION BY SHIFTINDEX,CRUSHERLOC,COMPONENT ORDER BY VALUE_TS DESC) NUM  
FROM [dbo].[IOS_STOCKPILE_LEVELS] WITH (NOLOCK)  
WHERE [SITEFLAG] = 'BAG'
AND COMPONENT = 'Mill Stockpile')

SELECT
a.SITEFLAG,
a.SHIFTFLAG,
'CRUSHER 2' AS CRUSHERLOC,
CASE WHEN b.SENSORVALUE IS NULL OR b.SENSORVALUE = 0
	THEN 0 
	ELSE b.SENSORVALUE / 165000 * 100 END AS CrusherStockpile,
b.SENSORVALUE AS CrusherStockpileTons
FROM [bag].[CONOPS_BAG_SHIFT_INFO_V] a WITH (NOLOCK)
LEFT JOIN CTE b
	ON a.SHIFTINDEX = b.SHIFTINDEX
	AND b.NUM = 1

