CREATE VIEW [BAG].[CONOPS_BAG_AUTONOMOUS_TRUCK_V] AS


--select * from [bag].[CONOPS_BAG_AUTONOMOUS_TRUCK_V]
CREATE VIEW [bag].[CONOPS_BAG_AUTONOMOUS_TRUCK_V]
AS

WITH LatestStat AS(
SELECT
	PRIMARYMACHINENAME AS TruckID,
	AUTONOMOUS AS Autonomous,
	ROW_NUMBER() OVER(PARTITION BY PRIMARYMACHINENAME ORDER BY STARTTIME_UTC DESC) AS RowNum
FROM bag2.CYCLE WITH(NOLOCK)
WHERE ECF_CLASS_ID = 'XAEntity.Cycle.ProductionCycle.TruckCycle'
)

SELECT
	TruckID,
	Autonomous
FROM LatestStat
WHERE RowNum = 1


