CREATE VIEW [BAG].[CONOPS_BAG_TRUCK_TPRH] AS




--select * from [bag].[CONOPS_BAG_TRUCK_TPRH] WITH(NOLOCK)
CREATE VIEW [bag].[CONOPS_BAG_TRUCK_TPRH]
AS

SELECT 
[th].[ShiftId],
[th].[Truck],
[th].tonsHaul
FROM (
	SELECT
		SITE_CODE AS SITEFLAG,
		SHIFT_ID AS SHIFTID,
		TRUCK_NAME AS TRUCK,
		COALESCE(SUM(REPORT_PAYLOAD_SHORT_TONS),0) AS TonsHaul
	FROM BAG.FLEET_TRUCK_CYCLE_V
	GROUP BY SITE_CODE, SHIFT_ID, TRUCK_NAME
) [th]


