CREATE VIEW [BAG].[CONOPS_BAG_SUPPORT_EQMT_OPERATOR_CONSECUTIVE_WORKDAYS_V] AS


  -- SELECT * FROM [bag].[CONOPS_BAG_SUPPORT_EQMT_OPERATOR_CONSECUTIVE_WORKDAYS_V] WITH (NOLOCK) 
CREATE VIEW [bag].[CONOPS_BAG_SUPPORT_EQMT_OPERATOR_CONSECUTIVE_WORKDAYS_V]   
AS  
  
SELECT 
LASTSHIFTINDEX AS Shiftindex,  
SITE_CODE,  
OPERID,  
NROFDAYS  
FROM dbo.OPERATOR_CONSECUTIVE_WORKDAYS WITH (NOLOCK)  
WHERE SITE_CODE = 'BAG' AND UNIT_CODE NOT IN ('1','2','12')
  

