CREATE VIEW [BAG].[FLEET_SHOVEL_CYCLE_V] AS


--SELECT * FROM bag.FLEET_SHOVEL_CYCLE_V
CREATE VIEW bag.FLEET_SHOVEL_CYCLE_V
AS

WITH Last3Shift AS(
SELECT TOP 3 
	SHIFT_ID COLLATE SQL_Latin1_General_CP1_CI_AS AS SHIFT_ID,
	ROW_NUMBER() OVER(ORDER BY SHIFT_ID DESC) AS ROW_NO
FROM ConnectedOperations.bag2.MSMODEL_SHIFT
ORDER BY SHIFT_ID DESC
)

SELECT
	sc.SITE_CODE COLLATE SQL_Latin1_General_CP1_CI_AS AS SITE_CODE
	,ECF_CLASS_ID COLLATE SQL_Latin1_General_CP1_CI_AS AS ECF_CLASS_ID
	,SHIFT_ID COLLATE SQL_Latin1_General_CP1_CI_AS AS SHIFT_ID
	,TRUCK_NAME COLLATE SQL_Latin1_General_CP1_CI_AS AS TRUCK_NAME
	,TRUCK_EQUIP_CLASS COLLATE SQL_Latin1_General_CP1_CI_AS AS TRUCK_EQUIP_CLASS
	,TRUCK_OPERATOR_ID COLLATE SQL_Latin1_General_CP1_CI_AS AS TRUCK_OPERATOR_ID
	,TRUCK_OPERATOR_NAME COLLATE SQL_Latin1_General_CP1_CI_AS AS TRUCK_OPERATOR_NAME
	,SHOVEL_NAME COLLATE SQL_Latin1_General_CP1_CI_AS AS SHOVEL_NAME
	,SHOVEL_EQUIP_CLASS COLLATE SQL_Latin1_General_CP1_CI_AS AS SHOVEL_EQUIP_CLASS
	,SHOVEL_OPERATOR_ID COLLATE SQL_Latin1_General_CP1_CI_AS AS SHOVEL_OPERATOR_ID
	,SHOVEL_OPERATOR_NAME COLLATE SQL_Latin1_General_CP1_CI_AS AS SHOVEL_OPERATOR_NAME
	,DUMP_LOC_NAME COLLATE SQL_Latin1_General_CP1_CI_AS AS DUMP_LOC_NAME
	,LOAD_LOC_NAME COLLATE SQL_Latin1_General_CP1_CI_AS AS LOAD_LOC_NAME
	,MATERIAL_NAME COLLATE SQL_Latin1_General_CP1_CI_AS AS MATERIAL_NAME
	,GRADE COLLATE SQL_Latin1_General_CP1_CI_AS AS GRADE
	,LOAD_HOS
	,DUMP_HOS
	,QUEUINGATSOURCESTARTTIME_LOCAL_TS
	,LOADINGSTARTTIME_LOCAL_TS
	,DUMPINGSTARTTIME_LOCAL_TS
	,DUMPINGENDTIME_LOCAL_TS
	,MATERIAL_CODE_DISPATCH COLLATE SQL_Latin1_General_CP1_CI_AS AS MATERIAL_CODE_DISPATCH
	,REPORT_PAYLOAD_SHORT_TONS
	,MEASURED_PAYLOAD_SHORT_TONS
	,MEASURED_PAYLOAD_METRIC_TONS
	,EXTRA_LOAD
	,SOURCEBLOCKLEVEL COLLATE SQL_Latin1_General_CP1_CI_AS AS SOURCEBLOCKLEVEL
	,CASE WHEN (sc.MEASURED_PAYLOAD_SHORT_TONS >= pf.MIN_PAYLOAD OR pf.MIN_PAYLOAD IS NULL) AND TRUCK_NAME IS NOT NULL
		THEN 1
		ELSE 0 END AS PayloadFilter
	,pf.TARGET_PAYLOAD AS TargetPayload
FROM ConnectedOperations.bag2.MSHIST_HAUL_CYCLE sc WITH(NOLOCK)
LEFT JOIN dbo.PAYLOAD_FILTER_NEW pf WITH(NOLOCK)
	ON sc.SITE_CODE = pf.SITE_CODE
	AND sc.TRUCK_EQUIP_CLASS COLLATE SQL_Latin1_General_CP1_CI_AS = pf.EQMT_TYPE
WHERE ECF_CLASS_ID = 'XAEntity.Cycle.ProductionCycle.LoaderCycle'
AND SHIFT_ID >= (SELECT SHIFT_ID FROM Last3Shift WHERE ROW_NO = 3)


