CREATE VIEW [BAG].[FLEET_CYCLE_COMPONENT_DURATION_V] AS

--SELECT * FROM BAG.FLEET_CYCLE_COMPONENT_DURATION_V
CREATE VIEW BAG.FLEET_CYCLE_COMPONENT_DURATION_V
AS

WITH cteFilter AS(
SELECT
    C.CYCLE_OID
FROM [BAG_MSHIST].[dbo].[CYCLE] C WITH (NOLOCK)
WHERE C.ECF_CLASS_ID IN ('XAEntity.Cycle.ProductionCycle.TruckCycle')
    AND C.ENDTIME_UTC >=  DATEADD(DAY,-2, GETUTCDATE())
),

CycleComponent AS(
--TruckCAC
SELECT
    S.OID AS SHIFT_OID,
    S.REPORTING_DATE,
    S.SHIFTTYPE,
    C.ECF_CLASS_ID,
    C.CYCLE_OID,
    C.ASSOCIATEDCYCLE,
    C.PRIMARYMACHINE,
    C.PRIMARYMACHINENAME,
    C.SECONDARYMACHINE,
    C.SECONDARYMACHINENAME,
    C.SOURCELOCATIONNAME,
    C.PAYLOAD,
    'Truck' AS CYCLENAME,
    CAC.NAME,
    CAC.START_TIME_UTC,
    CAC.END_TIME_UTC,
    DATEDIFF(SECOND, CAC.START_TIME_UTC, CAC.END_TIME_UTC) AS DURATION
FROM cteFilter ct
INNER JOIN BAG_MSHIST.dbo.CYCLE C WITH(NOLOCK)
    ON ct.CYCLE_OID = C.CYCLE_OID
LEFT JOIN BAG_MSMODEL.dbo.SHIFT S WITH(NOLOCK)
    ON C.ENDTIME_UTC > S.STARTTIME_UTC
    AND C.ENDTIME_UTC <= S.ENDTIME_UTC
LEFT JOIN BAG_MSHIST.dbo.CYCLEACTIVITYCOMPONENT CAC WITH(NOLOCK)
    ON C.CYCLE_OID = CAC.OID --Truck Cycle OID
WHERE C.ECF_CLASS_ID IN('XAEntity.Cycle.ProductionCycle.TruckCycle')

UNION ALL

--ShovelCAC
SELECT
    S.OID AS SHIFT_OID,
    S.REPORTING_DATE,
    S.SHIFTTYPE,
    C.ECF_CLASS_ID,
    C.CYCLE_OID,
    C.ASSOCIATEDCYCLE,
    C.PRIMARYMACHINE,
    C.PRIMARYMACHINENAME,
    C.SECONDARYMACHINE,
    C.SECONDARYMACHINENAME,
    C.SOURCELOCATIONNAME,
    C.PAYLOAD,
    'Shovel' AS CYCLENAME,
    CAC.NAME,
    CAC.START_TIME_UTC,
    CAC.END_TIME_UTC,
    DATEDIFF(SECOND, CAC.START_TIME_UTC, CAC.END_TIME_UTC) AS DURATION
FROM cteFilter ct
INNER JOIN BAG_MSHIST.dbo.CYCLE C WITH(NOLOCK)
    ON ct.CYCLE_OID = C.CYCLE_OID
LEFT JOIN BAG_MSMODEL.dbo.SHIFT S WITH(NOLOCK)
    ON C.ENDTIME_UTC > S.STARTTIME_UTC
    AND C.ENDTIME_UTC <= S.ENDTIME_UTC
LEFT JOIN BAG_MSHIST.dbo.CYCLEACTIVITYCOMPONENT CAC WITH(NOLOCK)
    ON C.ASSOCIATEDCYCLE = CAC.OID --Shovel Cycle OID
WHERE C.ECF_CLASS_ID IN('XAEntity.Cycle.ProductionCycle.TruckCycle')
)

SELECT 
    SHIFT_OID,
    RIGHT(CAST(REPORTING_DATE AS VARCHAR), 6) + '00' + CAST(SHIFTTYPE + 1 AS VARCHAR) AS SHIFT_ID_CO,
    REPORTING_DATE,
    SHIFTTYPE,
    cc.ECF_CLASS_ID COLLATE SQL_Latin1_General_CP1_CI_AS AS ECF_CLASS_ID,
    CYCLE_OID,
    ASSOCIATEDCYCLE,
    PRIMARYMACHINE,
    PRIMARYMACHINENAME COLLATE SQL_Latin1_General_CP1_CI_AS AS PRIMARYMACHINENAME,
    SECONDARYMACHINE,
    SECONDARYMACHINENAME COLLATE SQL_Latin1_General_CP1_CI_AS AS SECONDARYMACHINENAME,
    SOURCELOCATIONNAME COLLATE SQL_Latin1_General_CP1_CI_AS AS SOURCELOCATIONNAME,
    260 AS REPORT_PAYLOAD_SHORT_TONS,
    (PAYLOAD / 1000) / 0.90718474 AS MEASURED_PAYLOAD_SHORT_TONS, 
    PAYLOAD / 1000 AS MEASURED_PAYLOAD_METRIC_TONS,
	CASE WHEN (PAYLOAD / 1000) / 0.90718474 >= pf.MIN_PAYLOAD OR pf.MIN_PAYLOAD IS NULL
		THEN 1
		ELSE 0 END AS PayloadFilter,
	pf.TARGET_PAYLOAD AS TargetPayload,
    SUM(CASE WHEN CYCLENAME = 'Shovel' AND cc.name = 'Hang.Time' THEN duration ELSE 0 END) AS S_HangTime,
    SUM(CASE WHEN CYCLENAME = 'Shovel' AND cc.name = 'Loading' THEN duration ELSE 0 END) AS S_Loading,
    SUM(CASE WHEN CYCLENAME = 'Shovel' AND cc.name = 'WaitForSpot' THEN duration ELSE 0 END) AS S_WaitForSpot,
    SUM(CASE WHEN CYCLENAME = 'Shovel' AND cc.name = 'Machine.Delay' THEN duration ELSE 0 END) AS S_Delay,
    SUM(CASE WHEN CYCLENAME = 'Truck' AND cc.name = 'Travelling.Empty' THEN duration ELSE 0 END) AS T_TravellingEmpty,
    SUM(CASE WHEN CYCLENAME = 'Truck' AND cc.name = 'Queuing.At.Source' THEN duration ELSE 0 END) AS T_QueuingAtSource,
    SUM(CASE WHEN CYCLENAME = 'Truck' AND cc.name = 'Spotting.At.Source' THEN duration ELSE 0 END) AS T_SpottingAtSource,
    SUM(CASE WHEN CYCLENAME = 'Truck' AND cc.name = 'WaitForLoad' THEN duration ELSE 0 END) AS T_WaitForLoad,
    SUM(CASE WHEN CYCLENAME = 'Truck' AND cc.name = 'Load