CREATE VIEW [BAG].[FLEET_LOCATION_V] AS


CREATE VIEW [BAG].[FLEET_LOCATION_V]
AS

Select
	'BAG' COLLATE SQL_Latin1_General_CP1_CI_AS AS SITE_CODE,
	L.NAME COLLATE SQL_Latin1_General_CP1_CI_AS AS LOC_NAME,
	REHANDLE,
	ISSOURCE,
	ISSINK,
	ISSTATION,
	V.ROUTE_POINT_X AS LOC_X,
	V.ROUTE_POINT_Y AS LOC_Y,
	V.ROUTE_POINT_Z AS LOC_Z
from [ConnectedOperations].[bag2].[LOCATION] L WITH (NOLOCK)
LEFT JOIN [ConnectedOperations].[bag2].[LOCATION_WAYPOINT] LW WITH (NOLOCK)
	ON L.LOCATION_OID = LW.OID
LEFT JOIN [ConnectedOperations].[bag2].[VIRTUALBEACON] V WITH (NOLOCK)
	ON LW.WAYPOINT_OID = V.VIRTUALBEACON_OID


