CREATE VIEW [mor].[CONOPS_MOR_ALERT_V] AS


-- SELECT * FROM [MOR].[CONOPS_MOR_ALERT_V] WITH (NOLOCK) WHERE shiftflag = 'CURR'
CREATE VIEW [MOR].[CONOPS_MOR_ALERT_V]
AS

	SELECT si.SHIFTFLAG
		  ,si.[SITEFLAG]
		  ,[EQMT_TYPE]
		  ,[EQMTID]
		  ,[OPERATOR_ID]
		  ,[ALERT_TYPE]
		  ,[ALERT_NAME]
		  ,[ALERT_DESCRIPTION]
		  ,[ALERT_DATE]
		  ,[DURATION]
		  ,[ALERT_GENERATED_DATETIME]
		  ,[UTC_CREATED_DATE]
	FROM [MOR].[CONOPS_MOR_SHIFT_INFO_V] si (NOLOCK)
	LEFT JOIN [MOR].[ALERT] a (NOLOCK)
	ON a.SHIFTINDEX = si.SHIFTINDEX
	   AND a.SITEFLAG = si.SITEFLAG

