CREATE VIEW [mor].[CONOPS_MOR_DRILL_OPERATOR_CONSECUTIVE_WORKDAYS_V] AS

-- SELECT * FROM [mor].[CONOPS_MOR_DRILL_OPERATOR_CONSECUTIVE_WORKDAYS_V] WITH (NOLOCK) WHERE Shiftflag = 'PREV'
CREATE VIEW [mor].[CONOPS_MOR_DRILL_OPERATOR_CONSECUTIVE_WORKDAYS_V] 
AS

	SELECT LASTSHIFTINDEX AS Shiftindex,
		   SITE_CODE,
		   OPERID,
		   NROFDAYS
	FROM dbo.OPERATOR_CONSECUTIVE_WORKDAYS WITH (NOLOCK)
	WHERE SITE_CODE = 'MOR' AND UNIT_CODE = 12

