CREATE VIEW [chi].[CONOPS_CHI_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V] AS

  -- SELECT * FROM [CHI].[CONOPS_CHI_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V] WITH (NOLOCK) 
CREATE VIEW [CHI].[CONOPS_CHI_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V]   
AS  
  
SELECT 
LASTSHIFTINDEX AS Shiftindex,  
SITE_CODE,  
OPERID,  
NROFDAYS  
FROM dbo.OPERATOR_CONSECUTIVE_WORKDAYS WITH (NOLOCK)  
WHERE SITE_CODE = 'CHI' AND UNIT_CODE = 2

