CREATE VIEW [chi].[CONOPS_CHI_AUTONOMOUS_TRUCK_V] AS



--select * from [CHI].[CONOPS_CHI_AUTONOMOUS_TRUCK_V]
CREATE VIEW [CHI].[CONOPS_CHI_AUTONOMOUS_TRUCK_V]
AS

SELECT DISTINCT
	FieldId AS TruckId,
	0 AS Autonomous
FROM CHI.pit_truck_c WITH(NOLOCK)
WHERE FieldId IS NOT NULL
	AND FieldId <> ''


