/*****************************************************************************************
* TABLE     : DRILL_BLAST__BL_DW_BLASTPROPERTYVALUE_INCR
* DATABASE  : SNOWFLAKE_WG
* SCHEMA    : dbo
* SOURCE    : Snowflake DEV_API_REF.FUSE.BL_DW_BLASTPROPERTYVALUE_INCR
* DATE      : 2026-01-28 | AUTHOR: CARLOS CARRILLO
******************************************************************************************/
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DRILL_BLAST__BL_DW_BLASTPROPERTYVALUE_INCR]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DRILL_BLAST__BL_DW_BLASTPROPERTYVALUE_INCR] (
    ORIG_SRC_ID BIGINT NOT NULL,
    SITE_CODE NVARCHAR(50) NOT NULL,
    BLASTID INT NOT NULL,
    REFRESHEDTIME DATETIME2,
    DELETED BIT,
    PARAMETER NVARCHAR(400),
    PLANNEDDATE NVARCHAR(400),
    SHOTTYPE NVARCHAR(400),
    SHOTGOAL NVARCHAR(400),
    DW_FILE_TS_UTC DATETIME2,
    DW_LOGICAL_DELETE_FLAG NVARCHAR(1) DEFAULT 'N',
    DW_LOAD_TS DATETIME2,
    DW_MODIFY_TS DATETIME2,
    CONSTRAINT PK_DRILL_BLAST__BL_DW_BLASTPROPERTYVALUE_INCR PRIMARY KEY (ORIG_SRC_ID, SITE_CODE, BLASTID)
);
END
GO

-- Create index for archival queries
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_DRILL_BLAST__BL_DW_BLASTPROPERTYVALUE_INCR_DW_MODIFY_TS')
CREATE INDEX IX_DRILL_BLAST__BL_DW_BLASTPROPERTYVALUE_INCR_DW_MODIFY_TS ON [dbo].[DRILL_BLAST__BL_DW_BLASTPROPERTYVALUE_INCR](DW_MODIFY_TS);
GO
