/*****************************************************************************************
* TABLE     : DRILL_BLAST__BL_DW_HOLE_INCR
* DATABASE  : SNOWFLAKE_WG
* SCHEMA    : dbo
* SOURCE    : Snowflake DEV_API_REF.FUSE.BL_DW_HOLE_INCR
* DATE      : 2026-01-28 | AUTHOR: CARLOS CARRILLO
******************************************************************************************/
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DRILL_BLAST__BL_DW_HOLE_INCR]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DRILL_BLAST__BL_DW_HOLE_INCR] (
    ORIG_SRC_ID BIGINT NOT NULL,
    SITE_CODE NVARCHAR(50) NOT NULL,
    ID INT NOT NULL,
    NAME NVARCHAR(500),
    MODIFIED_NAME NVARCHAR(500),
    BLASTNAME NVARCHAR(500),
    MODIFIED_BLASTNAME NVARCHAR(500),
    BLASTID INT,
    [ROW] NVARCHAR(500),
    ECHELON INT,
    STATUS NVARCHAR(500),
    LASTKNOWNDEPTH FLOAT,
    LASTKNOWNWATER FLOAT,
    LASTKNOWNWETSIDES FLOAT,
    LASTKNOWNTEMPERATURE FLOAT,
    LASTKNOWNTEMPERATURETIME DATETIME2,
    PREVIOUSTEMPERATURE FLOAT,
    PREVIOUSTEMPERATURETIME DATETIME2,
    TEMPERATURERATEOFCHANGE FLOAT,
    DESIGNTIME DATETIME2,
    DRILLEDTIME DATETIME2,
    LASTDIPDEPTH FLOAT,
    LASTDIPPEDTIME DATETIME2,
    LASTBACKFILLINGDIPDEPTH FLOAT,
    LASTBACKFILLINGDIPTIME DATETIME2,
    LASTCHARGINGDIPDEPTH FLOAT,
    LASTCHARGINGDIPTIME DATETIME2,
    CHARGEDTIME DATETIME2,
    FIREDTIME DATETIME2,
    ABANDONEDTIME DATETIME2,
    ABANDONEDCOMMENT NVARCHAR(MAX),
    MISFIRE BIT,
    MISFIRECOMMENT NVARCHAR(MAX),
    REDRILLOFHOLEID INT,
    REDRILLOFHOLENAME NVARCHAR(500),
    ISADHOC BIT,
    DESIGNCOLLARX FLOAT,
    DESIGNCOLLARY FLOAT,
    DESIGNCOLLARZ FLOAT,
    DESIGNANGLE FLOAT,
    DESIGNBEARING FLOAT,
    DESIGNDEPTH FLOAT,
    DESIGNDIAMETER FLOAT,
    DESIGNBURDEN FLOAT,
    DESIGNSPACING FLOAT,
    ACTUALCOLLARX FLOAT,
    ACTUALCOLLARY FLOAT,
    ACTUALCOLLARZ FLOAT,
    TARGETCHARGEDEPTH FLOAT,
    PLANNEDPRIMERCOUNT INT,
    LOADEDPRIMERCOUNT INT,
    LOADEDEXPLOSIVEDECKCOUNT INT,
    DIPPEDOUTSIDECHARGEDEPTHTOLERANCE BIT,
    CHARGEDOUTSIDEMASSTOLERANCE BIT,
    DRILLEDOUTSIDECOLLARTOLERANCE BIT,
    TOPMOSTSTEMMINGDECKLOADED BIT,
    STEMMEDOUTSIDELENGTHTOLERANCE BIT,
    EXPLOSIVEMASSDESIGNED FLOAT,
    EXPLOSIVEMASSLOADED FLOAT,
    EXPLOSIVEMASSRECONCILED FLOAT,
    STEMMINGLENGTHDESIGNED FLOAT,
    STEMMINGLENGTHLOADED FLOAT,
    STEMMINGLENGTHRECONCILED FLOAT,
    DESIGNTIEUPCOUNT INT,
    ACTUALTIEUPCOUNT INT,
    DESIGNDRILLCOST DECIMAL(15,5),
    CHARGESTANDOFF FLOAT,
    CHARGESTANDOFFDIRECTION NVARCHAR(50),
    REFRESHEDTIME DATETIME2,
    DELETED BIT,
    DW_FILE_TS_UTC DATETIME2,
    DW_LOGICAL_DELETE_FLAG NVARCHAR(1) DEFAULT 'N',
    DW_LOAD_TS DATETIME2,
    DW_MODIFY_TS DATETIME2,
    CONSTRAINT PK_DRILL_BLAST__BL_DW_HOLE_INCR PRIMARY KEY (ORIG_SRC_ID, SITE_CODE, ID)
);
END
GO

-- Create index for archival queries
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_DRILL_BLAST__BL_DW_HOLE_INCR_DW_MODIFY_TS')
CREATE INDEX IX_DRILL_BLAST__BL_DW_HOLE_INCR_DW_MODIFY_TS ON [dbo].[DRILL_BLAST__BL_DW_HOLE_INCR](DW_MODIFY_TS);
GO
