/*****************************************************************************************
* TABLE     : DRILL_BLAST__DRILLBLAST_SHIFT_INCR
* DATABASE  : SNOWFLAKE_WG
* SCHEMA    : dbo
* SOURCE    : Snowflake DEV_API_REF.FUSE.DRILLBLAST_SHIFT_INCR
* DATE      : 2026-01-28 | AUTHOR: CARLOS CARRILLO
******************************************************************************************/
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DRILL_BLAST__DRILLBLAST_SHIFT_INCR]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DRILL_BLAST__DRILLBLAST_SHIFT_INCR] (
    ORIG_SRC_ID INT,
    SITE_CODE NVARCHAR(5) NOT NULL,
    SHIFT_ID NVARCHAR(500) NOT NULL,
    SHIFT_DATE DATE,
    SHIFT_NAME NVARCHAR(255),
    SHIFT_DATE_NAME NVARCHAR(255),
    ATTRIBUTED_CREW_ID BIGINT,
    CREW_NAME NVARCHAR(255),
    SHIFT_NO INT,
    SHIFT_START_TS_UTC DATETIME2,
    SHIFT_END_TS_UTC DATETIME2,
    SHIFT_START_TS_LOCAL DATETIME2,
    SHIFT_END_TS_LOCAL DATETIME2,
    SYSTEM_VERSION NVARCHAR(50),
    DW_LOGICAL_DELETE_FLAG NVARCHAR(1) DEFAULT 'N',
    DW_LOAD_TS DATETIME2,
    DW_MODIFY_TS DATETIME2,
    CONSTRAINT PK_DRILL_BLAST__DRILLBLAST_SHIFT_INCR PRIMARY KEY (SITE_CODE, SHIFT_ID)
);
END
GO

-- Create index for archival queries
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_DRILL_BLAST__DRILLBLAST_SHIFT_INCR_DW_MODIFY_TS')
CREATE INDEX IX_DRILL_BLAST__DRILLBLAST_SHIFT_INCR_DW_MODIFY_TS ON [dbo].[DRILL_BLAST__DRILLBLAST_SHIFT_INCR](DW_MODIFY_TS);
GO
