/*****************************************************************************************
* TABLE     : LOAD_HAUL__LH_LOADING_CYCLE_INCR
* DATABASE  : SNOWFLAKE_WG
* SCHEMA    : dbo
* SOURCE    : Snowflake DEV_API_REF.FUSE.LH_LOADING_CYCLE_INCR
* DATE      : 2026-01-28 | AUTHOR: CARLOS CARRILLO
* NOTES     : Uses CYCLE_START_TS_LOCAL for archival (not DW_MODIFY_TS)
******************************************************************************************/
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LOAD_HAUL__LH_LOADING_CYCLE_INCR]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[LOAD_HAUL__LH_LOADING_CYCLE_INCR] (
    LOADING_CYCLE_ID BIGINT NOT NULL,
    SITE_CODE NVARCHAR(4),
    ORIG_SRC_ID BIGINT,
    SHIFT_ID NVARCHAR(12),
    LOADING_CYCLE_OF_SHIFT BIGINT,
    EXCAV_CYCLE_OF_SHIFT BIGINT,
    CYCLE_START_TS_UTC DATETIME2(3),
    CYCLE_START_TS_LOCAL DATETIME2(3),  -- Used for archival
    CYCLE_END_TS_UTC DATETIME2(3),
    CYCLE_END_TS_LOCAL DATETIME2(3),
    MEASURED_PAYLOAD_SHORT_TONS DECIMAL(38,6),
    MEASURED_PAYLOAD_METRIC_TONS DECIMAL(38,6),
    AVG_SWING_DURATION_MINS DECIMAL(38,6),
    AVG_DIG_DURATION_MINS DECIMAL(38,6),
    HANG_DURATION_MINS DECIMAL(38,6),
    IDLE_DURATION_MINS DECIMAL(38,6),
    BUCKET_COUNT BIGINT,
    EXCAV_ID BIGINT,
    TRUCK_ID BIGINT,
    EXCAV_OPERATOR_ID BIGINT,
    MATERIAL_ID BIGINT,
    LOADING_LOC_ID BIGINT,
    LOADING_CYCLE_DIG_ELEV_AVG_FEET FLOAT,
    LOADING_CYCLE_DIG_ELEV_AVG_METERS FLOAT,
    INTERRUPTED_LOADING_FLAG TINYINT,
    ASSOCIATED_HAUL_CYCLE_FLAG TINYINT,
    OVER_TRUCKED_FLAG TINYINT,
    UNDER_TRUCKED_FLAG TINYINT,
    HAUL_CYCLE_ID BIGINT,
    SYSTEM_VERSION NVARCHAR(50),
    DW_LOGICAL_DELETE_FLAG NVARCHAR(1) DEFAULT 'N',
    DW_LOAD_TS DATETIME2,
    DW_MODIFY_TS DATETIME2,
    CONSTRAINT PK_LOAD_HAUL__LH_LOADING_CYCLE_INCR PRIMARY KEY (LOADING_CYCLE_ID)
);
END
GO

-- Create index for archival queries (uses CYCLE_START_TS_LOCAL)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_LOAD_HAUL__LH_LOADING_CYCLE_INCR_CYCLE_START_TS_LOCAL')
CREATE INDEX IX_LOAD_HAUL__LH_LOADING_CYCLE_INCR_CYCLE_START_TS_LOCAL ON [dbo].[LOAD_HAUL__LH_LOADING_CYCLE_INCR](CYCLE_START_TS_LOCAL);
GO
