
  
    
    
    
/******************************************************************        
* PROCEDURE : BAG2.[UPSERT_CONOPS_PERSON]      
* PURPOSE : UPSERT [UPSERT_CONOPS_PERSON]      
* NOTES     :       
* CREATED : MFAHMI      
* SAMPLE    : EXEC BAG2.[UPSERT_CONOPS_PERSON] 'BAG2'       
* MODIFIED DATE  AUTHOR    DESCRIPTION        
*------------------------------------------------------------------        
* {04 SEP 2024}  {MFAHMI}   {INITIAL CREATED}        
*******************************************************************/        
CREATE  PROCEDURE [bag2].[UPSERT_CONOPS_PERSON]       
(      
@G_SITE VARCHAR(5)      
)      
AS      
BEGIN   
DECLARE @G_SITE_ALIAS VARCHAR(5)  
  
SET @G_SITE_ALIAS = CASE WHEN @G_SITE = 'CLI' THEN 'CMX' WHEN @G_SITE ='BAG2' THEN 'BAG' ELSE @G_SITE END  
EXEC       
(      
'MERGE ' +@G_SITE+ '.PERSON AS T '      
+' USING (SELECT '       
+' ''' +@G_SITE_ALIAS+ ''' AS SITEFLAG'   
+' ,PERSON_OID'
+' ,ECF_CLASS_ID'
+' ,IS_ACTIVE'
+' ,NAME'
+' ,MAINTENANCE_USER'
+' ,MACPASSWORD'
+' ,PERSONNELID'
+' ,ALLOCATIONDATE'
+' ,ALLOCATIONPRIORITY'
+' ,EXCLUDEFROMMACHINEALLOCATION'
+' ,SHIFTCHANGEGROUP'
+' ,TECH_LEVEL'
+' ,POSITION'
+' ,DEPARTMENT'
+' ,PRIMARY_SUPERVISOR'
+' ,HIRE_DATE'
+' ,EXTERNALREF'
+' ,EXTERNALDESC'
+' ,USERREF'
+' ,LAYER_UPDATE_VERSION'
+' ,EMT'
+' ,FIRST_RESPONDER'
+' ,BUS_DRIVER'
+' ,GETUTCDATE() AS UTC_CREATED_DATE'
+' FROM ' +@G_SITE+ '.[VIEW_PERSON_ETL] '  
+' ) AS S '       
+' ON (T.PERSON_OID = S.PERSON_OID AND T.SITEFLAG = S.SITEFLAG) '       
+' WHEN MATCHED '       
+' THEN UPDATE SET '       
+' T.ECF_CLASS_ID = S.ECF_CLASS_ID'
+' ,T.IS_ACTIVE = S.IS_ACTIVE'
+' ,T.NAME = S.NAME'
+' ,T.MAINTENANCE_USER = S.MAINTENANCE_USER'
+' ,T.MACPASSWORD = S.MACPASSWORD'
+' ,T.PERSONNELID = S.PERSONNELID'
+' ,T.ALLOCATIONDATE = S.ALLOCATIONDATE'
+' ,T.ALLOCATIONPRIORITY = S.ALLOCATIONPRIORITY'
+' ,T.EXCLUDEFROMMACHINEALLOCATION = S.EXCLUDEFROMMACHINEALLOCATION'
+' ,T.SHIFTCHANGEGROUP = S.SHIFTCHANGEGROUP'
+' ,T.TECH_LEVEL = S.TECH_LEVEL'
+' ,T.POSITION = S.POSITION'
+' ,T.DEPARTMENT = S.DEPARTMENT'
+' ,T.PRIMARY_SUPERVISOR = S.PRIMARY_SUPERVISOR'
+' ,T.HIRE_DATE = S.HIRE_DATE'
+' ,T.EXTERNALREF = S.EXTERNALREF'
+' ,T.EXTERNALDESC = S.EXTERNALDESC'
+' ,T.USERREF = S.USERREF'
+' ,T.LAYER_UPDATE_VERSION = S.LAYER_UPDATE_VERSION'
+' ,T.EMT = S.EMT'
+' ,T.FIRST_RESPONDER = S.FIRST_RESPONDER'
+' ,T.BUS_DRIVER = S.BUS_DRIVER'
+' ,T.UTC_CREATED_DATE = S.UTC_CREATED_DATE '       
+' WHEN NOT MATCHED '       
+' THEN INSERT ( '       
+' SITEFLAG'
+' ,PERSON_OID'
+' ,ECF_CLASS_ID'
+' ,IS_ACTIVE'
+' ,NAME'
+' ,MAINTENANCE_USER'
+' ,MACPASSWORD'
+' ,PERSONNELID'
+' ,ALLOCATIONDATE'
+' ,ALLOCATIONPRIORITY'
+' ,EXCLUDEFROMMACHINEALLOCATION'
+' ,SHIFTCHANGEGROUP'
+' ,TECH_LEVEL'
+' ,POSITION'
+' ,DEPARTMENT'
+' ,PRIMARY_SUPERVISOR'
+' ,HIRE_DATE'
+' ,EXTERNALREF'
+' ,EXTERNALDESC'
+' ,USERREF'
+' ,LAYER_UPDATE_VERSION'
+' ,EMT'
+' ,FIRST_RESPONDER'
+' ,BUS_DRIVER'
+' ,UTC_CREATED_DATE'
+'  ) VALUES( '       
+' S.SITEFLAG'
+' ,S.PERSON_OID'
+' ,S.ECF_CLASS_ID'
+' ,S.IS_ACTIVE'
+' ,S.NAME'
+' ,S.MAINTENANCE_USER'
+' ,S.MACPASSWORD'
+' ,S.PERSONNELID'
+' ,S.ALLOCATIONDATE'
+' ,S.ALLOCATIONPRIORITY'
+' ,S.EXCLUDEFROMMACHINEALLOCATION'
+' ,S.SHIFTCHANGEGROUP'
+' ,S.TECH_LEVEL'
+' ,S.POSITION'
+' ,S.DEPARTMENT'
+' ,S.PRIMARY_SUPERVISOR'
+' ,S.HIRE_DATE'
+' ,S.EXTERNALREF'
+' ,S.EXTERNALDESC'
+' ,S.USERREF'
+' ,S.LAYER_UPDATE_VERSION'
+' ,S.EMT'
+' ,S.FIRST_RESPONDER'
+' ,S.BUS_DRIVER'
+' ,S.UTC_CREATED_DATE'

+' ); '       

--Compare to stage
+'  DELETE    '
+' FROM  ' +@G_SITE+ '.[PERSON]    '  
+' WHERE NOT EXISTS    '
+' (SELECT 1    '
+' FROM  ' +@G_SITE+ '.[VIEW_PERSON_ETL]  AS stg     '
+' WHERE     '
+' stg.PERSON_OID = ' +@G_SITE+ '.[PERSON].PERSON_OID    '
+'); ' 
   
 );      
END      
      
