
  
    
    
    
/******************************************************************        
* PROCEDURE : BAG2.[UPSERT_CONOPS_MACHINE_IN_PIT]      
* PURPOSE : UPSERT [UPSERT_CONOPS_MACHINE_IN_PIT]      
* NOTES     :       
* CREATED : MFAHMI      
* SAMPLE    : EXEC BAG2.[UPSERT_CONOPS_MACHINE_IN_PIT] 'BAG2'       
* MODIFIED DATE  AUTHOR    DESCRIPTION        
*------------------------------------------------------------------        
* {04 SEP 2024}  {MFAHMI}   {INITIAL CREATED}        
*******************************************************************/        
CREATE  PROCEDURE [bag2].[UPSERT_CONOPS_MACHINE_IN_PIT]       
(      
@G_SITE VARCHAR(5)      
)      
AS      
BEGIN   
DECLARE @G_SITE_ALIAS VARCHAR(5)  
  
SET @G_SITE_ALIAS = CASE WHEN @G_SITE = 'CLI' THEN 'CMX' WHEN @G_SITE ='BAG2' THEN 'BAG' ELSE @G_SITE END  
EXEC       
(      
'MERGE ' +@G_SITE+ '.MACHINE_IN_PIT AS T '      
+' USING (SELECT '       
+' ''' +@G_SITE_ALIAS+ ''' AS SITEFLAG'   
+' ,MACHINE_OID'
+' ,CLASS_NAME'
+' ,STATUS'
+' ,STATUS_LAST_UPDATED_UTC'
+' ,SOFT_STATE'
+' ,LOCATION_OID'
+' ,LOCATION_LAST_UPDATED_UTC'
+' ,WAYPOINT_OID'
+' ,WAYPOINT_LAST_UPDATED_UTC'
+' ,TIME_AT_WAYPOINT_UTC'
+' ,CURRENT_OPERATOR_OID'
+' ,CURR_OPERATOR_LAST_UPDATED_UTC'
+' ,TIME_TILL_REFUEL'
+' ,TIME_TILL_CRIT_REFUEL'
+' ,JOBCODE_OID'
+' ,JOB_CODE_LAST_UPDATED_UTC'
+' ,MATERIAL_OID'
+' ,MATERIAL_LAST_UPDATED_UTC'
+' ,MATERIAL_DETERMINATION'
+' ,LAST_POSITION_REPORT_DATE_UTC'
+' ,X'
+' ,Y'
+' ,Z'
+' ,POSITION_ACCURACY'
+' ,MACHINE_SHUTDOWN'
+' ,NOT_IN_USE'
+' ,MSTATE_LOADSTATUS'
+' ,MSTATE_MANUALOVERRIDE'
+' ,MSTATE_OLDLOADSTATUS'
+' ,MSTATE_OLDSTATE'
+' ,FIELD_BAD_GPS'
+' ,SERVICE_MACHINE_OID'
+' ,LAST_LOADER_OID'
+' ,LAST_PROCESSOR_OID'
+' ,TIME_COMMENCED_SERVICE_UTC'
+' ,TIME_COMPLETED_SERVICE_UTC'
+' ,SERVICE_INFO_LAST_UPDATED_UTC'
+' ,SPEED'
+' ,HEADING'
+' ,FREEDESTPERCENT'
+' ,FREEGRPDESTPERCENT'
+' ,LOADED'
+' ,CURRENT_PAYLOAD'
+' ,CURR_PAYLOAD_LAST_UPDATED_UTC'
+' ,LAST_PAYLOAD'
+' ,LAST_MATERIAL_OID'
+' ,LAST_GRADE_BLOCK_OID'
+' ,CURRENT_GRADE_BLOCK_OID'
+' ,CUR_GRADE_BLK_LAST_UPDATED_UTC'
+' ,GRADE_BLOCK_DETERMINATION'
+' ,GRADE_BLOCK_OID'
+' ,GRADE_BLOCK_GROUP_OID'
+' ,LAST_LOADED_GRADE_BLOCK_OID'
+' ,UG_MODE'
+' ,UG_MODE_MSG_TIME_UTC'
+' ,LAST_SERVICE_AMOUNT'
+' ,LAST_SRV_AMT_LAST_UPDATED_UTC'
+' ,LAST_SERVICE_START_UTC'
+' ,LAST_SRV_STRT_LAST_UPDATED_UTC'
+' ,CHUTE_CURRENT_LEVEL'
+' ,UG_LOC_STATE'
+' ,CHUTE_DUMPED_AMOUNT'
+' ,CHUTE_TAKEN_AMOUNT'
+' ,UG_LOC_WARNING'
+' ,CHUTE_LAST_DUMPED_UTC'
+' ,CHUTE_DUMPED_RATE'
+' ,LOADER_CYCLE_MODE'
+' ,LOADER_RECIPE_OID'
+' ,CURRENT_BENCH_FILE'
+' ,DUMPED_AMOUNT_CURRENT_SHIFT'
+' ,PAYLOAD_UPDATE_SOURCE'
+' ,LOADER_RECIPE_APPLIED_UTC'
+' ,ARTICULATION'
+' ,LOADER_RECIPE_RATE'
+' ,LAST_LOAD_WAYPOINT_OID'
+' ,LAST_DUMP_WAYPOINT_OID'
+' ,AIMS_STATUS'
+' ,AIMS_MACHINE_FAULT'
+' ,AIMS_LAST_MESSAGE_UTC'
+' ,HAULAGE_ETA_UTC'
+' ,WATER_TANK_LEVEL'
+' ,WATER_REFILL_STATUS'
+' ,WATER_REFILL_STATUS_SOURCE'
+' ,WATER_REFUEL_STATUS'
+' ,ALLOCATED_WATERING_CIRCUIT_OID'
+' ,LAYOVER_REASON'
+' ,PROHIBITED_SEQ_MATERIAL_MODIFIER'
+' ,PROHIBITED_SEQ_OCCURRENCES'
+' ,RETURN_LOADED_TRUCKS_TO_QUEUE'
+' ,GETUTCDATE() AS UTC_CREATED_DATE'
+' FROM ' +@G_SITE+ '.[VIEW_MACHINE_IN_PIT_ETL] '  
+' ) AS S '       
+' ON (T.MACHINE_OID = S.MACHINE_OID AND T.SITEFLAG = S.SITEFLAG) '       
+' WHEN MATCHED '       
+' THEN UPDATE SET ' 
+' T.CLASS_NAME = S.CLASS_NAME'
+' ,T.STATUS = S.STATUS'
+' ,T.STATUS_LAST_UPDATED_UTC = S.STATUS_LAST_UPDATED_UTC'
+' ,T.SOFT_STATE = S.SOFT_STATE'
+' ,T.LOCATION_OID = S.LOCATION_OID'
+' ,T.LOCATION_LAST_UPDATED_UTC = S.LOCATION_LAST_UPDATED_UTC'
+' ,T.WAYPOINT_OID = S.WAYPOINT_OID'
+' ,T.WAYPOINT_LAST_UPDATED_UTC = S.WAYPOINT_LAST_UPDATED_UTC'
+' ,T.TIME_AT_WAYPOINT_UTC = S.TIME_AT_WAYPOINT_UTC'
+' ,T.CURRENT_OPERATOR_OID = S.CURRENT_OPERATOR_OID'
+' ,T.CURR_OPERATOR_LAST_UP