   
    
/******************************************************************        
* PROCEDURE : BAG2.[UPSERT_CONOPS_LOCATION]      
* PURPOSE : UPSERT [UPSERT_CONOPS_LOCATION]      
* NOTES     :       
* CREATED : MFAHMI      
* SAMPLE    : EXEC BAG2.[UPSERT_CONOPS_LOCATION] 'BAG2'       
* MODIFIED DATE  AUTHOR    DESCRIPTION        
*------------------------------------------------------------------        
* {19 MAR 2023}  {MFAHMI}   {INITIAL CREATED}        
*******************************************************************/        
CREATE  PROCEDURE [bag2].[UPSERT_CONOPS_LOCATION]       
(      
@G_SITE VARCHAR(5)      
)      
AS      
BEGIN   
DECLARE @G_SITE_ALIAS VARCHAR(5)  
  
SET @G_SITE_ALIAS = CASE WHEN @G_SITE = 'CLI' THEN 'CMX' WHEN @G_SITE ='BAG2' THEN 'BAG' ELSE @G_SITE END  
EXEC       
(      
'MERGE ' +@G_SITE+ '.LOCATION AS T '      
+' USING (SELECT '       
+' ''' +@G_SITE_ALIAS+ ''' AS SITEFLAG'   
+' ,LOCATION_OID'
+' ,IS_ACTIVE'
+' ,DESCRIPTION'
+' ,NAME'
+' ,REHANDLE'
+' ,ISSOURCE'
+' ,ISSINK'
+' ,ISSTATION'
+' ,ALLOWALLMATERIALS'
+' ,ALLOWTHORUGHTRAFFIC'
+' ,TRUCKCAPACITY'
+' ,QUEUINGALLOWED'
+' ,TAXCLASS'
+' ,ISPARENT'
+' ,BADCOMMSAREA'
+' ,LOADSTATE'
+' ,SHIFTCHANGEGROUP'
+' ,EXTERNALREF'
+' ,EXTERNALDESC'
+' ,LAYER_UPDATE_VERSION'
+' ,GETUTCDATE() AS UTC_CREATED_DATE'
+' FROM ' +@G_SITE+ '.[VIEW_LOCATION_ETL] '  
+' ) AS S '       
+' ON (T.LOCATION_OID = S.LOCATION_OID AND T.SITEFLAG = S.SITEFLAG) '       
+' WHEN MATCHED '       
+' THEN UPDATE SET '       
+' T.IS_ACTIVE = S.IS_ACTIVE'
+' ,T.DESCRIPTION = S.DESCRIPTION'
+' ,T.NAME = S.NAME'
+' ,T.REHANDLE = S.REHANDLE'
+' ,T.ISSOURCE = S.ISSOURCE'
+' ,T.ISSINK = S.ISSINK'
+' ,T.ISSTATION = S.ISSTATION'
+' ,T.ALLOWALLMATERIALS = S.ALLOWALLMATERIALS'
+' ,T.ALLOWTHORUGHTRAFFIC = S.ALLOWTHORUGHTRAFFIC'
+' ,T.TRUCKCAPACITY = S.TRUCKCAPACITY'
+' ,T.QUEUINGALLOWED = S.QUEUINGALLOWED'
+' ,T.TAXCLASS = S.TAXCLASS'
+' ,T.ISPARENT = S.ISPARENT'
+' ,T.BADCOMMSAREA = S.BADCOMMSAREA'
+' ,T.LOADSTATE = S.LOADSTATE'
+' ,T.SHIFTCHANGEGROUP = S.SHIFTCHANGEGROUP'
+' ,T.EXTERNALREF = S.EXTERNALREF'
+' ,T.EXTERNALDESC = S.EXTERNALDESC'
+' ,T.LAYER_UPDATE_VERSION = S.LAYER_UPDATE_VERSION'    
+' ,T.UTC_CREATED_DATE = S.UTC_CREATED_DATE '            
+' WHEN NOT MATCHED '       
+' THEN INSERT ( '       
+' SITEFLAG'
+' ,LOCATION_OID'
+' ,IS_ACTIVE'
+' ,DESCRIPTION'
+' ,NAME'
+' ,REHANDLE'
+' ,ISSOURCE'
+' ,ISSINK'
+' ,ISSTATION'
+' ,ALLOWALLMATERIALS'
+' ,ALLOWTHORUGHTRAFFIC'
+' ,TRUCKCAPACITY'
+' ,QUEUINGALLOWED'
+' ,TAXCLASS'
+' ,ISPARENT'
+' ,BADCOMMSAREA'
+' ,LOADSTATE'
+' ,SHIFTCHANGEGROUP'
+' ,EXTERNALREF'
+' ,EXTERNALDESC'
+' ,LAYER_UPDATE_VERSION'
+' ,UTC_CREATED_DATE'   
+'  ) VALUES( '       
+' S.SITEFLAG'
+' ,S.LOCATION_OID'
+' ,S.IS_ACTIVE'
+' ,S.DESCRIPTION'
+' ,S.NAME'
+' ,S.REHANDLE'
+' ,S.ISSOURCE'
+' ,S.ISSINK'
+' ,S.ISSTATION'
+' ,S.ALLOWALLMATERIALS'
+' ,S.ALLOWTHORUGHTRAFFIC'
+' ,S.TRUCKCAPACITY'
+' ,S.QUEUINGALLOWED'
+' ,S.TAXCLASS'
+' ,S.ISPARENT'
+' ,S.BADCOMMSAREA'
+' ,S.LOADSTATE'
+' ,S.SHIFTCHANGEGROUP'
+' ,S.EXTERNALREF'
+' ,S.EXTERNALDESC'
+' ,S.LAYER_UPDATE_VERSION'
+' ,S.UTC_CREATED_DATE'  
+' ); '       

  --Compare to stage
+'  DELETE    '
+' FROM  ' +@G_SITE+ '.[LOCATION]    '  
+' WHERE NOT EXISTS    '
+' (SELECT 1    '
+' FROM  ' +@G_SITE+ '.[VIEW_LOCATION_ETL]  AS stg     '
+' WHERE     '
+' stg.LOCATION_OID = ' +@G_SITE+ '.[LOCATION].LOCATION_OID    '
+'); ' 
   
 );      
END      
      
