/*****************************************************************************************
* TABLE     : LH_EQUIPMENT_STATUS_EVENT_INCR
* SCHEMA    : {{ envi }}_API_REF.FUSE
* SOURCE    : {{ RO_PROD }}_WG.LOAD_HAUL.LH_EQUIPMENT_STATUS_EVENT
* DATE: 2026-01-27 | AUTHOR: CARLOS CARRILLO
******************************************************************************************/
create or replace TABLE {{ envi }}_API_REF.FUSE.LH_EQUIPMENT_STATUS_EVENT_INCR (
	SITE_CODE VARCHAR(4) COLLATE 'en-ci' NOT NULL,
	EQUIP_ID NUMBER(19,0) NOT NULL,
	EQUIP_CATEGORY VARCHAR(64) COLLATE 'en-ci',
	ORIG_SRC_ID NUMBER(38,0),
	EQUIP_STATUS_EVENT_SK VARCHAR(8000) COLLATE 'en-ci',
	SHIFT_ID VARCHAR(8000) COLLATE 'en-ci',
	CYCLE_ID NUMBER(19,0),
	STATUS_EVENT_REASON_ID NUMBER(19,0),
	START_TS_UTC TIMESTAMP_NTZ(3),
	END_TS_UTC TIMESTAMP_NTZ(3),
	START_TS_LOCAL TIMESTAMP_NTZ(3) NOT NULL,
	END_TS_LOCAL TIMESTAMP_NTZ(3),
	DURATION_MINS NUMBER(38,12),
	EVENT_COMMENTS VARCHAR(8000) COLLATE 'en-ci',
	DISTINCT_STATUS_EVENT_FLAG NUMBER(1,0),
	PREV_STATUS_EVENT_ID VARCHAR(8000) COLLATE 'en-ci',
	NEXT_STATUS_EVENT_ID VARCHAR(8000) COLLATE 'en-ci',
	SYSTEM_VERSION VARCHAR(50) COLLATE 'en-ci',
	DW_LOGICAL_DELETE_FLAG VARCHAR(1) COLLATE 'en-ci' DEFAULT 'N',
	DW_LOAD_TS TIMESTAMP_NTZ(0),
	DW_MODIFY_TS TIMESTAMP_NTZ(0)
)COMMENT='Incremental table for LH_EQUIPMENT_STATUS_EVENT - MERGE-driven upserts with 3-day incremental window'
;
