CREATE VIEW [chi].[CONOPS_CHI_CM_HOURLY_INTERMEDIATE_STOCKPILE_V] AS




  
  
--SELECT * FROM [chi].[CONOPS_CHI_CM_HOURLY_INTERMEDIATE_STOCKPILE_V] WITH (NOLOCK) WHERE SHIFTFLAG = 'CURR'    
CREATE VIEW [chi].[CONOPS_CHI_CM_HOURLY_INTERMEDIATE_STOCKPILE_V]
AS    

SELECT 
a.[SITEFLAG]  
,a.[SHIFTFLAG]  
,0 AS [MFLStockpile]  
,0 AS [MillStockpile]
,NULL TimeInHour
FROM [chi].[CONOPS_CHI_SHIFT_INFO_V] a WITH (NOLOCK)  




