CREATE OR REPLACE PROCEDURE {{ envi }}_API_REF.FUSE.BLAST_PLAN_EXECUTION_INCR_P("NUMBER_OF_DAYS" VARCHAR(16777216) DEFAULT '3')
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
var sp_result="";
var sql_count_incr, sql_delete_incr, sql_merge, sql_delete;

sql_count_incr = `SELECT COUNT(*) AS count_check_1 
                  FROM {{ envi }}_API_REF.fuse.blast_plan_execution_incr 
                  WHERE dw_modify_ts::date < DATEADD(day, -` + NUMBER_OF_DAYS + `, CURRENT_DATE);`;

sql_delete_incr = `DELETE FROM {{ envi }}_API_REF.fuse.blast_plan_execution_incr 
                   WHERE dw_modify_ts::date < DATEADD(day, -` + NUMBER_OF_DAYS + `, CURRENT_DATE);`;

sql_merge = `MERGE INTO {{ envi }}_API_REF.fuse.blast_plan_execution_incr tgt
USING (
    SELECT 
        ORIG_SRC_ID, SITE_CODE, BENCH, PUSHBACK, PATTERN_NAME, BLAST_NAME, DRILLED_HOLE_ID,
        DRILLED_HOLE_NAME, DRILL_CYCLE_SK, BLAST_PLAN_SK, SHIFT_ID, BLAST_ID,
        SHOT_DATE_UTC, SHOT_DATE_LOCAL, BLAST_TYPE, BLAST_ENGINEER_NAME, LOADING_TRUCK_OPERATOR_NAME,
        HOLE_LOADED_TS_UTC, HOLE_LOADED_TS_LOCAL,
        HOLE_LAST_KNOWN_DEPTH_METERS, HOLE_LAST_KNOWN_DEPTH_FEET,
        HOLE_TAPED_DEPTH_METERS, HOLE_TAPED_DEPTH_FEET, HOLE_PLUGGED_FLAG,
        EXPLOSIVE_PRODUCT_BOTTOM, EXPLOSIVE_PRODUCT_TOP,
        EXPLOSIVE_PRODUCT_USED_BOTTOM_KILOGRAMS, EXPLOSIVE_PRODUCT_USED_BOTTOM_POUNDS,
        EXPLOSIVE_PRODUCT_USED_TOP_KILOGRAMS, EXPLOSIVE_PRODUCT_USED_TOP_POUNDS,
        EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_METERS, EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_FEET,
        EXPLOSIVE_PRODUCT_LENGTH_TOP_METERS, EXPLOSIVE_PRODUCT_LENGTH_TOP_FEET,
        STEMMING_LENGTH_TOTAL_METERS, STEMMING_LENGTH_TOTAL_FEET,
        STEMMING_LENGTH_BOTTOM_METERS, STEMMING_LENGTH_BOTTOM_FEET,
        STEMMING_LENGTH_TOP_METERS, STEMMING_LENGTH_TOP_FEET,
        BURDEN_METERS, BURDEN_FEET, SPACING_METERS, SPACING_FEET,
        TONS_PER_HOLE, KCALS_PER_TON, POWDER_FACTOR, MEGAJOULES_PER_TON, CONFINEMENT_FACTOR, PRIMER_COUNT,
        HOLE_TEMPERATURE_CELSIUS, HOLE_TEMPERATURE_FAHRENHEIT,
        PRODUCT_BOTTOM_COMMENTS, PRODUCT_TOP_COMMENTS, STEMMING_BOTTOM_COMMENT, STEMMING_TOP_COMMENT,
        WATER_DEPTH_METERS, WATER_DEPTH_FEET, MISFIRE_FLAG,
        DW_LOAD_TS,
        DW_MODIFY_TS,
        ''N'' AS DW_LOGICAL_DELETE_FLAG,
        CURRENT_TIMESTAMP(0)::TIMESTAMP_NTZ AS dw_load_ts_new
    FROM {{ RO_PROD }}_WG.drill_blast.blast_plan_execution
    WHERE DW_MODIFY_TS >= DATEADD(day, -` + NUMBER_OF_DAYS + `, CURRENT_TIMESTAMP())
    -- Fix: Deduplicate source to prevent MERGE duplicate row error
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ORIG_SRC_ID, SITE_CODE, BENCH, PUSHBACK, PATTERN_NAME, BLAST_NAME, DRILLED_HOLE_ID
        ORDER BY DW_MODIFY_TS DESC NULLS LAST
    ) = 1
) AS src
ON tgt.ORIG_SRC_ID = src.ORIG_SRC_ID 
   AND tgt.SITE_CODE = src.SITE_CODE 
   AND tgt.BENCH = src.BENCH 
   AND COALESCE(tgt.PUSHBACK, '''') = COALESCE(src.PUSHBACK, '''')
   AND COALESCE(tgt.PATTERN_NAME, '''') = COALESCE(src.PATTERN_NAME, '''')
   AND tgt.BLAST_NAME = src.BLAST_NAME 
   AND tgt.DRILLED_HOLE_ID = src.DRILLED_HOLE_ID
WHEN MATCHED AND HASH(src.DRILLED_HOLE_NAME, src.BLAST_TYPE, src.BLAST_ENGINEER_NAME, 
                      src.TONS_PER_HOLE, src.POWDER_FACTOR, src.MISFIRE_FLAG)
              <> HASH(tgt.DRILLED_HOLE_NAME, tgt.BLAST_TYPE, tgt.BLAST_ENGINEER_NAME, 
                      tgt.TONS_PER_HOLE, tgt.POWDER_FACTOR, tgt.MISFIRE_FLAG)
THEN UPDATE SET
    tgt.DRILLED_HOLE_NAME = src.DRILLED_HOLE_NAME,
    tgt.DRILL_CYCLE_SK = src.DRILL_CYCLE_SK,
    tgt.BLAST_PLAN_SK = src.BLAST_PLAN_SK,
    tgt.SHIFT_ID = src.SHIFT_ID,
    tgt.BLAST_ID = src.BLAST_ID,
    tgt.SHOT_DATE_UTC = src.SHOT_DATE_UTC,
    tgt.SHOT_DATE_LOCAL = src.SHOT_DATE_LOCAL,
    tgt.BLAST_TYPE = src.BLAST_TYPE,
    tgt.BLAST_ENGINEER_NAME = src.BLAST_ENGINEER_NAME,
    tgt.LOADING_TRUCK_OPERATOR_NAME = src.LOADING_TRUCK_OPERATOR_NAME,
    tgt.HOLE_LOADED_TS_UTC = src.HOLE_LOADED_TS_UTC,
    tgt.HOLE_LOADED_TS_LOCAL = src.HOLE_LOADED_TS_LOCAL,
    tgt.HOLE_LAST_KNOWN_DEPTH_METERS = src.HOLE_LAST_KNOWN_DEPTH_METERS,
    tgt.HOLE_LAST_KNOWN_DEPTH_FEET = src.HOLE_LAST_KNOWN_DEPTH_FEET,
    tgt.HOLE_TAPED_DEPTH_METERS = src.HOLE_TAPED_DEPTH_METERS,
    tgt.HOLE_TAPED_DEPTH_FEET = src.HOLE_TAPED_DEPTH_FEET,
    tgt.HOLE_PLUGGED_FLAG = src.HOLE_PLUGGED_FLAG,
    tgt.EXPLOSIVE_PRODUCT_BOTTOM = src.EXPLOSIVE_PRODUCT_BOTTOM,
    tgt.EXPLOSIVE_PRODUCT_TOP = src.EXPLOSIVE_PRODUCT_TOP,
    tgt.EXPLOSIVE_PRODUCT_USED_BOTTOM_KILOGRAMS = src.EXPLOSIVE_PRODUCT_USED_BOTTOM_KILOGRAMS,
    tgt.EXPLOSIVE_PRODUCT_USED_BOTTOM_POUNDS = src.EXPLOSIVE_PRODUCT_USED_BOTTOM_POUNDS,
    tgt.EXPLOSIVE_PRODUCT_USED_TOP_KILOGRAMS = src.EXPLOSIVE_PRODUCT_USED_TOP_KILOGRAMS,
    tgt.EXPLOSIVE_PRODUCT_USED_TOP_POUNDS = src.EXPLOSIVE_PRODUCT_USED_TOP_POUNDS,
    tgt.EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_METERS = src.EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_METERS,
    tgt.EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_FEET = src.EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_FEET,
    tgt.EXPLOSIVE_PRODUCT_LENGTH_TOP_METERS = src.EXPLOSIVE_PRODUCT_LENGTH_TOP_METERS,
    tgt.EXPLOSIVE_PRODUCT_LENGTH_TOP_FEET = src.EXPLOSIVE_PRODUCT_LENGTH_TOP_FEET,
    tgt.STEMMING_LENGTH_TOTAL_METERS = src.STEMMING_LENGTH_TOTAL_METERS,
    tgt.STEMMING_LENGTH_TOTAL_FEET = src.STEMMING_LENGTH_TOTAL_FEET,
    tgt.STEMMING_LENGTH_BOTTOM_METERS = src.STEMMING_LENGTH_BOTTOM_METERS,
    tgt.STEMMING_LENGTH_BOTTOM_FEET = src.STEMMING_LENGTH_BOTTOM_FEET,
    tgt.STEMMING_LENGTH_TOP_METERS = src.STEMMING_LENGTH_TOP_METERS,
    tgt.STEMMING_LENGTH_TOP_FEET = src.STEMMING_LENGTH_TOP_FEET,
    tgt.BURDEN_METERS = src.BURDEN_METERS,
    tgt.BURDEN_FEET = src.BURDEN_FEET,
    tgt.SPACING_METERS = src.SPACING_METERS,
    tgt.SPACING_FEET = src.SPACING_FEET,
    tgt.TONS_PER_HOLE = src.TONS_PER_HOLE,
    tgt.KCALS_PER_TON = src.KCALS_PER_TON,
    tgt.POWDER_FACTOR = src.POWDER_FACTOR,
    tgt.MEGAJOULES_PER_TON = src.MEGAJOULES_PER_TON,
    tgt.CONFINEMENT_FACTOR = src.CONFINEMENT_FACTOR,
    tgt.PRIMER_COUNT = src.PRIMER_COUNT,
    tgt.HOLE_TEMPERATURE_CELSIUS = src.HOLE_TEMPERATURE_CELSIUS,
    tgt.HOLE_TEMPERATURE_FAHRENHEIT = src.HOLE_TEMPERATURE_FAHRENHEIT,
    tgt.PRODUCT_BOTTOM_COMMENTS = src.PRODUCT_BOTTOM_COMMENTS,
    tgt.PRODUCT_TOP_COMMENTS = src.PRODUCT_TOP_COMMENTS,
    tgt.STEMMING_BOTTOM_COMMENT = src.STEMMING_BOTTOM_COMMENT,
    tgt.STEMMING_TOP_COMMENT = src.STEMMING_TOP_COMMENT,
    tgt.WATER_DEPTH_METERS = src.WATER_DEPTH_METERS,
    tgt.WATER_DEPTH_FEET = src.WATER_DEPTH_FEET,
    tgt.MISFIRE_FLAG = src.MISFIRE_FLAG,
    tgt.DW_LOAD_TS = src.DW_LOAD_TS,
    tgt.DW_MODIFY_TS = CURRENT_TIMESTAMP(0)::TIMESTAMP_NTZ
WHEN NOT MATCHED THEN INSERT (
    ORIG_SRC_ID, SITE_CODE, BENCH, PUSHBACK, PATTERN_NAME, BLAST_NAME, DRILLED_HOLE_ID,
    DRILLED_HOLE_NAME, DRILL_CYCLE_SK, BLAST_PLAN_SK, SHIFT_ID, BLAST_ID,
    SHOT_DATE_UTC, SHOT_DATE_LOCAL, BLAST_TYPE, BLAST_ENGINEER_NAME, LOADING_TRUCK_OPERATOR_NAME,
    HOLE_LOADED_TS_UTC, HOLE_LOADED_TS_LOCAL,
    HOLE_LAST_KNOWN_DEPTH_METERS, HOLE_LAST_KNOWN_DEPTH_FEET,
    HOLE_TAPED_DEPTH_METERS, HOLE_TAPED_DEPTH_FEET, HOLE_PLUGGED_FLAG,
    EXPLOSIVE_PRODUCT_BOTTOM, EXPLOSIVE_PRODUCT_TOP,
    EXPLOSIVE_PRODUCT_USED_BOTTOM_KILOGRAMS, EXPLOSIVE_PRODUCT_USED_BOTTOM_POUNDS,
    EXPLOSIVE_PRODUCT_USED_TOP_KILOGRAMS, EXPLOSIVE_PRODUCT_USED_TOP_POUNDS,
    EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_METERS, EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_FEET,
    EXPLOSIVE_PRODUCT_LENGTH_TOP_METERS, EXPLOSIVE_PRODUCT_LENGTH_TOP_FEET,
    STEMMING_LENGTH_TOTAL_METERS, STEMMING_LENGTH_TOTAL_FEET,
    STEMMING_LENGTH_BOTTOM_METERS, STEMMING_LENGTH_BOTTOM_FEET,
    STEMMING_LENGTH_TOP_METERS, STEMMING_LENGTH_TOP_FEET,
    BURDEN_METERS, BURDEN_FEET, SPACING_METERS, SPACING_FEET,
    TONS_PER_HOLE, KCALS_PER_TON, POWDER_FACTOR, MEGAJOULES_PER_TON, CONFINEMENT_FACTOR, PRIMER_COUNT,
    HOLE_TEMPERATURE_CELSIUS, HOLE_TEMPERATURE_FAHRENHEIT,
    PRODUCT_BOTTOM_COMMENTS, PRODUCT_TOP_COMMENTS, STEMMING_BOTTOM_COMMENT, STEMMING_TOP_COMMENT,
    WATER_DEPTH_METERS, WATER_DEPTH_FEET, MISFIRE_FLAG,
    DW_LOAD_TS, DW_MODIFY_TS, DW_LOGICAL_DELETE_FLAG
) VALUES (
    src.ORIG_SRC_ID, src.SITE_CODE, src.BENCH, src.PUSHBACK, src.PATTERN_NAME, src.BLAST_NAME, src.DRILLED_HOLE_ID,
    src.DRILLED_HOLE_NAME, src.DRILL_CYCLE_SK, src.BLAST_PLAN_SK, src.SHIFT_ID, src.BLAST_ID,
    src.SHOT_DATE_UTC, src.SHOT_DATE_LOCAL, src.BLAST_TYPE, src.BLAST_ENGINEER_NAME, src.LOADING_TRUCK_OPERATOR_NAME,
    src.HOLE_LOADED_TS_UTC, src.HOLE_LOADED_TS_LOCAL,
    src.HOLE_LAST_KNOWN_DEPTH_METERS, src.HOLE_LAST_KNOWN_DEPTH_FEET,
    src.HOLE_TAPED_DEPTH_METERS, src.HOLE_TAPED_DEPTH_FEET, src.HOLE_PLUGGED_FLAG,
    src.EXPLOSIVE_PRODUCT_BOTTOM, src.EXPLOSIVE_PRODUCT_TOP,
    src.EXPLOSIVE_PRODUCT_USED_BOTTOM_KILOGRAMS, src.EXPLOSIVE_PRODUCT_USED_BOTTOM_POUNDS,
    src.EXPLOSIVE_PRODUCT_USED_TOP_KILOGRAMS, src.EXPLOSIVE_PRODUCT_USED_TOP_POUNDS,
    src.EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_METERS, src.EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_FEET,
    src.EXPLOSIVE_PRODUCT_LENGTH_TOP_METERS, src.EXPLOSIVE_PRODUCT_LENGTH_TOP_FEET,
    src.STEMMING_LENGTH_TOTAL_METERS, src.STEMMING_LENGTH_TOTAL_FEET,
    src.STEMMING_LENGTH_BOTTOM_METERS, src.STEMMING_LENGTH_BOTTOM_FEET,
    src.STEMMING_LENGTH_TOP_METERS, src.STEMMING_LENGTH_TOP_FEET,
    src.BURDEN_METERS, src.BURDEN_FEET, src.SPACING_METERS, src.SPACING_FEET,
    src.TONS_PER_HOLE, src.KCALS_PER_TON, src.POWDER_FACTOR, src.MEGAJOULES_PER_TON, src.CONFINEMENT_FACTOR, src.PRIMER_COUNT,
    src.HOLE_TEMPERATURE_CELSIUS, src.HOLE_TEMPERATURE_FAHRENHEIT,
    src.PRODUCT_BOTTOM_COMMENTS, src.PRODUCT_TOP_COMMENTS, src.STEMMING_BOTTOM_COMMENT, src.STEMMING_TOP_COMMENT,
    src.WATER_DEPTH_METERS, src.WATER_DEPTH_FEET, src.MISFIRE_FLAG,
    src.dw_load_ts_new, src.dw_load_ts_new, src.DW_LOGICAL_DELETE_FLAG
)`;

sql_delete = `UPDATE {{ envi }}_API_REF.fuse.blast_plan_execution_incr tgt
SET DW_LOGICAL_DELETE_FLAG = ''Y'', DW_MODIFY_TS = CURRENT_TIMESTAMP(0)::TIMESTAMP_NTZ
WHERE NOT EXISTS (
    SELECT 1 FROM {{ RO_PROD }}_WG.drill_blast.blast_plan_execution src
    WHERE tgt.ORIG_SRC_ID = src.ORIG_SRC_ID 
      AND tgt.SITE_CODE = src.SITE_CODE 
      AND tgt.BENCH = src.BENCH 
      AND COALESCE(tgt.PUSHBACK, '''') = COALESCE(src.PUSHBACK, '''')
      AND COALESCE(tgt.PATTERN_NAME, '''') = COALESCE(src.PATTERN_NAME, '''')
      AND tgt.BLAST_NAME = src.BLAST_NAME 
      AND tgt.DRILLED_HOLE_ID = src.DRILLED_HOLE_ID
)
AND tgt.DW_LOGICAL_DELETE_FLAG = ''N''`;

try {
    // Count old records
    var stmt1 = snowflake.createStatement({sqlText: sql_count_incr});
    var resultSet1 = stmt1.execute();
    resultSet1.next();
    var old_count = resultSet1.getColumnValue(1);
    
    // Delete old records
    var stmt2 = snowflake.createStatement({sqlText: sql_delete_incr});
    stmt2.execute();
    var deleted_count = stmt2.getNumRowsAffected();
    
    // Merge new/updated records
    var stmt3 = snowflake.createStatement({sqlText: sql_merge});
    stmt3.execute();
    var merged_count = stmt3.getNumRowsAffected();
    
    // Soft delete missing records
    var stmt4 = snowflake.createStatement({sqlText: sql_delete});
    stmt4.execute();
    var soft_deleted_count = stmt4.getNumRowsAffected();
    
    sp_result = "SUCCESS: Deleted " + deleted_count + " old records, Merged " + merged_count + " records, Soft deleted " + soft_deleted_count + " records";
} catch(err) {
    sp_result = "ERROR: " + err.message;
}

return sp_result;
';
