CREATE TABLE [dbo].[CRUSHER_STATUS_STG2] (
    [SITE_CODE] varchar(5) NOT NULL,
    [HIERARCHY_ID] int NULL,
    [DOWNTIME_ID] int NULL,
    [PLANT_AREA_NAME] varchar(255) NOT NULL,
    [CALENDAR_DATE] date NULL,
    [PRODCTN_DATE] date NULL,
    [SHIFT_INDICATOR] varchar(4000) NULL,
    [START_TS] datetime NOT NULL,
    [START_DATE] date NULL,
    [START_TIME] time NULL,
    [STOP_TS] datetime NOT NULL,
    [STOP_DATE] date NULL,
    [STOP_TIME] time NULL,
    [DOWNTIME_DURATION] int NULL,
    [ACT_MINS] decimal(16,6) NULL,
    [EFF_MINS] decimal(16,6) NULL,
    [FAILURE_CODE_ID] int NULL,
    [ORIG_CODE] varchar(5) NULL,
    [EQUIP_NO_ID] int NULL,
    [DOWNTIME_TYPE] varchar(5) NULL,
    [DOWNTIME_CAT] varchar(4000) NULL,
    [PROBLEM_ID] varchar(4000) NULL,
    [CAUSE_NAME] varchar(4000) NULL,
    [EQMT] varchar(4000) NULL,
    [EQUIP_DESC] varchar(4000) NULL,
    [SAP_ID] varchar(30) NULL,
    [EQUIP_FUNC_LOC] varchar(4000) NULL,
    [DOWNTIME_EVENT_PARENT_INDICATO] int NULL,
    [FURTHER_WORK_ORDER_CODE] varchar(5) NULL,
    [GENRT_WORK_ORDER_CODE] varchar(4000) NULL,
    [WORK_ORDER_NO] varchar(4000) NULL,
    [WORK_ORDER_STATUS] varchar(4000) NULL,
    [WORK_ORDER_COMMENT] varchar(4000) NULL,
    [EQUIP_ALARM] int NULL,
    [ALARM_SELECT_FLAG] int NULL,
    [EVENT_CLOSE_STATUS_FLAG] varchar(4000) NULL,
    [WORK_ORDER_APPROVED_INDICATOR] varchar(4000) NULL,
    [PRODCTN_COST] decimal(18,2) NULL,
    [EDIT_FLAG] int NULL,
    [UPDATED_BY] varchar(50) NULL,
    [DOWNTIME_AUDIT_ID] int NULL,
    [DOWNTIME_AUDIT_TYPE] varchar(5) NULL,
    [CREATED_BY] int NULL,
    [WORK_ORDER_ORIG] varchar(4000) NULL,
    [AUTO_SPLIT_ROOT] int NULL,
    [DW_LOAD_TS] datetime NULL,
    [UTC_CREATED_DATE] datetime NULL
);