CREATE TABLE [dbo].[LH_OPER_TOTAL_SUM_STG] (
    [SHIFTINDEX] numeric(38,0) NOT NULL,
    [SHIFTDATE] date NULL,
    [SITE_CODE] varchar(4) NOT NULL,
    [CLIID] numeric(38,0) NULL,
    [DDBKEY] float NULL,
    [EQMTID] varchar(50) NOT NULL,
    [EQMTID_ORIG] varchar(50) NULL,
    [IDLETIME] float NULL,
    [LOADCNT] float NULL,
    [LOADTIME] float NULL,
    [LOCID] varchar(50) NULL,
    [LOGINTIME] float NOT NULL,
    [NAME] varchar(50) NULL,
    [OPERID] varchar(50) NULL,
    [PIT] varchar(50) NULL,
    [SPOTTIME] float NULL,
    [TMCAT00] float NULL,
    [TMCAT01] float NULL,
    [TMCAT02] float NULL,
    [TMCAT03] float NULL,
    [TMCAT04] float NULL,
    [TMCAT05] float NULL,
    [TMCAT06] float NULL,
    [TMCAT07] float NULL,
    [TMCAT08] float NULL,
    [TMCAT09] float NULL,
    [TMCAT10] float NULL,
    [TMCAT11] float NULL,
    [TMCAT12] float NULL,
    [TMCAT13] float NULL,
    [TMCAT14] float NULL,
    [TMCAT15] float NULL,
    [TMCAT16] float NULL,
    [TMCAT17] float NULL,
    [TMCAT18] float NULL,
    [TMCAT19] float NULL,
    [TOTALLOADS] float NULL,
    [TOTALTIME] float NULL,
    [TOTALTONS] float NULL,
    [UNIT] varchar(64) NULL,
    [UNIT_CODE] numeric(38,0) NULL,
    [SYSTEM_VERSION] varchar(50) NULL,
    [UTC_CREATED_DATE] datetime NULL
);