CREATE TABLE [dbo].[MAINTENANCE_CALENDAR] (
    [Id] int NOT NULL,
    [SiteCode] char(3) NOT NULL,
    [EventTitle] varchar(512) NOT NULL,
    [EventTypeCode] varchar(8) NOT NULL,
    [EquipmentTypeCode] varchar(8) NOT NULL,
    [EquipmentName] varchar(512) NOT NULL,
    [Description] varchar NOT NULL,
    [StartDateTime] datetime NOT NULL,
    [EndDateTime] datetime NOT NULL,
    [IsRecurrence] bit NOT NULL,
    [RecurrenceTypeCode] char(1) NULL,
    [RecurrenceCustomNumber] int NULL,
    [RecurrenceStartDateTime] datetime NULL,
    [RecurrenceEndDateTime] datetime NULL,
    [IsAnyRecurrenceUpdated] bit NULL,
    [CreatedBy] char(10) NOT NULL,
    [UtcCreatedDate] datetime NOT NULL,
    [LastModifiedBy] char(10) NOT NULL,
    [UtcModifiedDate] datetime NOT NULL
);