CREATE TABLE [dbo].[MMPRO_PARTICLE_SIZE] (
    [ORIG_SRC_ID] int NOT NULL,
    [SITE_CODE] varchar(4) NOT NULL,
    [SOURCE_ID] int NOT NULL,
    [LH_EQUIP_ID] varchar(200) NULL,
    [LH_BUCKET_ID] bigint NULL,
    [P10_METERS] decimal(10,3) NULL,
    [P10_INCHES] decimal(16,7) NULL,
    [P20_METERS] decimal(10,3) NULL,
    [P20_INCHES] decimal(16,7) NULL,
    [P30_METERS] decimal(10,3) NULL,
    [P30_INCHES] decimal(16,7) NULL,
    [P40_METERS] decimal(10,3) NULL,
    [P40_INCHES] decimal(16,7) NULL,
    [P50_METERS] decimal(10,3) NULL,
    [P50_INCHES] decimal(16,7) NULL,
    [P60_METERS] decimal(10,3) NULL,
    [P60_INCHES] decimal(16,7) NULL,
    [P70_METERS] decimal(10,3) NULL,
    [P70_INCHES] decimal(16,7) NULL,
    [P80_METERS] decimal(10,3) NULL,
    [P80_INCHES] decimal(16,7) NULL,
    [P90_METERS] decimal(10,3) NULL,
    [P90_INCHES] decimal(16,7) NULL,
    [TOP_SIZE_METERS] decimal(10,3) NULL,
    [TOP_SIZE_INCHES] decimal(16,7) NULL,
    [SIEVE_SIZE_METHOD] varchar(1000) NULL,
    [FINE_CUMULATIVE_METERS] decimal(12,10) NULL,
    [FINE_CUMULATIVE_INCHES] decimal(16,12) NULL,
    [FINE_THRESHOLD_METERS] decimal(12,10) NULL,
    [FINE_THRESHOLD_INCHES] decimal(16,12) NULL,
    [TOTAL_REGION_AREA] decimal(12,10) NULL,
    [TOTAL_FINE_REGION_AREA] decimal(12,10) NULL,
    [SWEBREC] varchar NULL,
    [ROSINRAMMLER] varchar NULL,
    [TIMESTAMP_UTC] datetime NOT NULL,
    [TIMESTAMP_LOCAL] datetime NULL,
    [CYCLE_UUID] varchar(8000) NULL,
    [PROCESS_MODE] varchar(1000) NULL,
    [PVALS_OPTION] varchar NULL,
    [DW_MODIFY_TS] datetime2 NULL,
    [DW_LOAD_TS] datetime2 NULL
);