CREATE VIEW [CHI].[EQUIPMENT_HOURLY_STATUS] AS

--SELECT * FROM CHI.EQUIPMENT_HOURLY_STATUS
CREATE VIEW CHI.EQUIPMENT_HOURLY_STATUS
AS

SELECT *
FROM CHI.EQUIPMENT_HOURLY_STATUS_2 WITH(NOLOCK)

