CREATE VIEW [CHI].[PIT_WORKER] AS



--SELECT * FROM CHI.PIT_WORKER
CREATE VIEW CHI.PIT_WORKER
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM CHNOperational.dbo.PITWorker



