CREATE VIEW [CHI].[PIT_AUXEQMT] AS



--SELECT * FROM CHI.PIT_AUXEQMT
CREATE VIEW CHI.PIT_AUXEQMT
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM CHNOperational.dbo.PITAuxeqmt



