CREATE VIEW [CHI].[PIT_LOC] AS



--SELECT * FROM CHI.PIT_LOC
CREATE VIEW CHI.PIT_LOC
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM CHNOperational.dbo.PITPitLoc WITH(NOLOCK)



