CREATE VIEW [CHI].[SHIFT_GRADE] AS



--SELECT * FROM CHI.SHIFT_GRADE
CREATE VIEW CHI.SHIFT_GRADE
AS

SELECT
'CHI' AS SiteFlag,
*
FROM CHNOperational.dbo.SHIFTShiftgrade WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM CHI.SHIFT_INFO)



