CREATE VIEW [CHI].[SHIFT_LOAD] AS



--SELECT * FROM CHI.SHIFT_LOAD
CREATE VIEW CHI.SHIFT_LOAD
AS

SELECT
'CHI' AS SiteFlag,
*
FROM CHNOperational.dbo.SHIFTShiftload WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM CHI.SHIFT_INFO)



