CREATE VIEW [CHI].[SHIFT_LOC] AS



--SELECT * FROM CHI.SHIFT_LOC
CREATE VIEW CHI.SHIFT_LOC
AS

SELECT
'CHI' AS SiteFlag,
*
FROM CHNOperational.dbo.SHIFTShiftloc WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM CHI.SHIFT_INFO)



