CREATE VIEW [CHI].[SHIFT_EQMT] AS




--SELECT * FROM CHI.SHIFT_EQMT
CREATE VIEW CHI.SHIFT_EQMT
AS

SELECT
'CHI' AS SiteFlag,
*
FROM CHNOperational.dbo.SHIFTShifteqmt WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM CHI.SHIFT_INFO)




