CREATE OR REPLACE FUNCTION "SENSOR_SNAPSHOT_GET"("PARAM_SITE_CODE" VARCHAR(3), "PARAM_IS_AF_PATH_FLAG" BOOLEAN, "PARAM_ATTRIBUTE_PATH_LIST" ARRAY, "PARAM_PI_POINT_LIST" ARRAY)
RETURNS TABLE ("TAG_NAME" VARCHAR(16777216), "VALUE_UTC_TS" TIMESTAMP_NTZ(9), "SENSOR_VALUE" VARCHAR(16777216), "UOM" VARCHAR(16777216), "QUALITY" VARCHAR(16777216))
LANGUAGE SQL
AS '
  WITH final AS (
    SELECT
      t.tag_name,
      t.value_utc_ts,
      t.sensor_value,
      t.uom,
      t.quality
    FROM TABLE("SENSOR_SNAPSHOT_GET"(
      PARAM_SITE_CODE,
      PARAM_IS_AF_PATH_FLAG,
      PARAM_ATTRIBUTE_PATH_LIST,
      PARAM_PI_POINT_LIST,
      30
    )) t
  )
  SELECT * FROM final
'
