CREATE VIEW [TYR].[PIT_WORKER] AS



--SELECT * FROM TYR.PIT_WORKER
CREATE VIEW TYR.PIT_WORKER
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM TYROperational.dbo.PITWorker



