CREATE VIEW [TYR].[PIT_AUXEQMT] AS



--SELECT * FROM TYR.PIT_AUXEQMT
CREATE VIEW TYR.PIT_AUXEQMT
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM TYROperational.dbo.PITAuxeqmt



