CREATE VIEW [TYR].[SHIFT_LOC] AS



--SELECT * FROM TYR.SHIFT_LOC
CREATE VIEW TYR.SHIFT_LOC
AS

SELECT
'TYR' AS SiteFlag,
*
FROM TYROperational.dbo.SHIFTShiftloc WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM TYR.SHIFT_INFO)



