CREATE VIEW [TYR].[SHIFT_GRADE] AS



--SELECT * FROM TYR.SHIFT_GRADE
CREATE VIEW TYR.SHIFT_GRADE
AS

SELECT
'TYR' AS SiteFlag,
*
FROM TYROperational.dbo.SHIFTShiftgrade WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM TYR.SHIFT_INFO)



