CREATE VIEW [TYR].[SHIFT_EQMT] AS




--SELECT * FROM TYR.SHIFT_EQMT
CREATE VIEW TYR.SHIFT_EQMT
AS

SELECT
'TYR' AS SiteFlag,
*
FROM TYROperational.dbo.SHIFTShifteqmt WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM TYR.SHIFT_INFO)




