

 
/******************************************************************    
* PROCEDURE : [Arch].[UPSERT_CONOPS_PLAN_VALUES]   
* PURPOSE : Upsert [UPSERT_CONOPS_PLAN_VALUES]  
* NOTES     :   
* CREATED : mfahmi  
* SAMPLE    : EXEC ARCH.[UPSERT_CONOPS_PLAN_VALUES]  
* MODIFIED DATE  AUTHOR    DESCRIPTION    
*------------------------------------------------------------------    
* {01 DEC 2022}  {mfahmi}   {Initial Created}    
*******************************************************************/    
CREATE  PROCEDURE [Arch].[UPSERT_CONOPS_PLAN_VALUES]  
AS  
BEGIN  
  
MERGE ARCH.PLAN_VALUES AS T   
USING (SELECT 
CASE WHEN RIGHT(shiftid,1) = 1 
THEN CONCAT(RIGHT(REPLACE(CAST(LEFT(shiftid, LEN(shiftid) - CHARINDEX('/', REVERSE(shiftid))) AS DATE),'-',''),6),'001')
ELSE CONCAT(RIGHT(REPLACE(CAST(LEFT(shiftid, LEN(shiftid) - CHARINDEX('/', REVERSE(shiftid))) AS DATE),'-',''),6),'002')
END AS FORMATSHIFTID,
CONTENTTYPEID,
SHIFTID,
COMPLIANCEASSETID,
TOTALMINED,
L01ORE,
L01WASTE_OXIDE,
L02ORE,
L02WASTE_OXIDE,
S08ORE,
S08WASTE_OXIDE,
S10ORE,
S10WASTE_OXIDE,
S11ORE,
S11WASTE_OXIDE,
S12ORE,
S12WASTE_OXIDE,
S22ORE,
S22WASTE_OXIDE,
S23ORE,
S23WASTE_OXIDE,
REHANDLE,
E1TONS,
E3TONS,
N1TONS,
N2TONS,
N3TONS,
S4TONS,
TOTALEXPITTONS,
EFH,
CRUSHER2,
DUMPINGATCRUSHER,
STOCKPILETARGETS,
ID,
CONTENTTYPE,
MODIFIED,
CREATED,
CREATEDBYID,
MODIFIEDBYID,
OWSHIDDENVERSION,
VERSION,
PATH,
getutcdate() UTC_CREATED_DATE   
 FROM ARCH.PLAN_VALUES_stg) AS S   
 ON (T.Id = S.Id)   
  
 WHEN MATCHED   
 THEN UPDATE SET  
 T.FORMATSHIFTID = S.FORMATSHIFTID
,T.CONTENTTYPEID = S.CONTENTTYPEID
,T.SHIFTID = S.SHIFTID
,T.COMPLIANCEASSETID = S.COMPLIANCEASSETID
,T.TOTALMINED = S.TOTALMINED
,T.L01ORE = S.L01ORE
,T.L01WASTE_OXIDE = S.L01WASTE_OXIDE
,T.L02ORE = S.L02ORE
,T.L02WASTE_OXIDE = S.L02WASTE_OXIDE
,T.S08ORE = S.S08ORE
,T.S08WASTE_OXIDE = S.S08WASTE_OXIDE
,T.S10ORE = S.S10ORE
,T.S10WASTE_OXIDE = S.S10WASTE_OXIDE
,T.S11ORE = S.S11ORE
,T.S11WASTE_OXIDE = S.S11WASTE_OXIDE
,T.S12ORE = S.S12ORE
,T.S12WASTE_OXIDE = S.S12WASTE_OXIDE
,T.S22ORE = S.S22ORE
,T.S22WASTE_OXIDE = S.S22WASTE_OXIDE
,T.S23ORE = S.S23ORE
,T.S23WASTE_OXIDE = S.S23WASTE_OXIDE
,T.REHANDLE = S.REHANDLE
,T.E1TONS = S.E1TONS
,T.E3TONS = S.E3TONS
,T.N1TONS = S.N1TONS
,T.N2TONS = S.N2TONS
,T.N3TONS = S.N3TONS
,T.S4TONS = S.S4TONS
,T.TOTALEXPITTONS = S.TOTALEXPITTONS
,T.EFH = S.EFH
,T.CRUSHER2 = S.CRUSHER2
,T.DUMPINGATCRUSHER = S.DUMPINGATCRUSHER
,T.STOCKPILETARGETS = S.STOCKPILETARGETS
--,T.ID = S.ID
,T.CONTENTTYPE = S.CONTENTTYPE
,T.MODIFIED = S.MODIFIED
,T.CREATED = S.CREATED
,T.CREATEDBYID = S.CREATEDBYID
,T.MODIFIEDBYID = S.MODIFIEDBYID
,T.OWSHIDDENVERSION = S.OWSHIDDENVERSION
,T.VERSION = S.VERSION
,T.PATH = S.PATH
,T.UTC_CREATED_DATE = S.UTC_CREATED_DATE
 
 WHEN NOT MATCHED   
 THEN INSERT ( 
 FORMATSHIFTID,
CONTENTTYPEID,
SHIFTID,
COMPLIANCEASSETID,
TOTALMINED,
L01ORE,
L01WASTE_OXIDE,
L02ORE,
L02WASTE_OXIDE,
S08ORE,
S08WASTE_OXIDE,
S10ORE,
S10WASTE_OXIDE,
S11ORE,
S11WASTE_OXIDE,
S12ORE,
S12WASTE_OXIDE,
S22ORE,
S22WASTE_OXIDE,
S23ORE,
S23WASTE_OXIDE,
REHANDLE,
E1TONS,
E3TONS,
N1TONS,
N2TONS,
N3TONS,
S4TONS,
TOTALEXPITTONS,
EFH,
CRUSHER2,
DUMPINGATCRUSHER,
STOCKPILETARGETS,
ID,
CONTENTTYPE,
MODIFIED,
CREATED,
CREATEDBYID,
MODIFIEDBYID,
OWSHIDDENVERSION,
VERSION,
PATH,
UTC_CREATED_DATE
  ) VALUES(   
  S.FORMATSHIFTID,
S.CONTENTTYPEID,
S.SHIFTID,
S.COMPLIANCEASSETID,
S.TOTALMINED,
S.L01ORE,
S.L01WASTE_OXIDE,
S.L02ORE,
S.L02WASTE_OXIDE,
S.S08ORE,
S.S08WASTE_OXIDE,
S.S10ORE,
S.S10WASTE_OXIDE,
S.S11ORE,
S.S11WASTE_OXIDE,
S.S12ORE,
S.S12WASTE_OXIDE,
S.S22ORE,
S.S22WASTE_OXIDE,
S.S23ORE,
S.S23WASTE_OXIDE,
S.REHANDLE,
S.E1TONS,
S.E3TONS,
S.N1TONS,
S.N2TONS,
S.N3TONS,
S.S4TONS,
S.TOTALEXPITTONS,
S.EFH,
S.CRUSHER2,
S.DUMPINGATCRUSHER,
S.STOCKPILETARGETS,
S.ID,
S.CONTENTTYPE,
S.MODIFIED,
S.CREATED,
S.CREATEDBYID