 
/******************************************************************    
* PROCEDURE : [Arch].[UPSERT_CONOPS_PLAN_VALUES_PROD_SUM]   
* PURPOSE : Upsert [UPSERT_CONOPS_PLAN_VALUES_PROD_SUM]  
* NOTES     :   
* CREATED : mfahmi  
* SAMPLE    : EXEC ARCH.[UPSERT_CONOPS_PLAN_VALUES_PROD_SUM] 
* MODIFIED DATE  AUTHOR    DESCRIPTION    
*------------------------------------------------------------------    
* {01 DEC 2022}  {mfahmi}   {Initial Created}    
*******************************************************************/    
CREATE  PROCEDURE [Arch].[UPSERT_CONOPS_PLAN_VALUES_PROD_SUM]  
AS  
BEGIN  
  
MERGE ARCH.PLAN_VALUES_PROD_SUM AS T   
USING (SELECT   
CONTENTTYPEID,
[PLAN],
COMPLIANCEASSETID,
EFFECTIVEDATE,
ORETPD,
ORETCU,
OREMO,
ROMTPD,
ROMTCU,
WASTETPD,
EXPITTPD,
INPITTPD,
TOTALTPD,
S08TPD,
S10TPD,
S11TPD,
S12TPD,
S22TPD,
S23TPD,
TRUCKAVAILABILITY,
TRUCKUSEOFAVAILABILITY,
TRUCKASSETEFFICIENCY,
SHOVELAVAILABILITY,
SHOVELUSEOFAVAILABILITY,
SHOVELASSETEFFICIENCY,
DRILLAVAILABILITY,
DRILLASSETEFFICIENCY,
ONEWAYHAUL,
EFH,
TOTALDELTAC,
STRIPPINGRATIO,
E1TONS,
S4TONS,
PLANNEDDRIVERS,
PLANNEDSUPPORT,
PLANNEDSHOVELS,
PLANNEDDRILLS,
SHIFTCHANGEEFFICIENCY,
S08EFH,
S10EFH,
S11EFH,
S12EFH,
S22EFH,
S23EFH,
CRUSHERTARGETTPD,
TRUCKLOADEDTRAVEL,
TRUCKEMPTYTRAVEL,
SHOVELIDLETIME,
SHOVELTONSPERHOUR,
TARGETFEETDRILLED,
TARGETHOLESDRILLED,
REHANDLETPD,
S08TPRH,
S10TPRH,
S11TPRH,
S12TPRH,
S22TPRH,
S23TPRH,
AVERAGEREADYTRUCKS,
AVERAGEREADYSHOVELS,
DRILLREADINESS,
SMALLCRUSHERTPD,
E1TPD,
N3TPD,
S4TPD,
ID,
CONTENTTYPE,
MODIFIED,
CREATED,
CREATEDBYID,
MODIFIEDBYID,
OWSHIDDENVERSION,
VERSION,
PATH,
getutcdate() UTC_CREATED_DATE   
 FROM ARCH.PLAN_VALUES_PROD_SUM_stg) AS S   
 ON (T.Id = S.Id)   
  
 WHEN MATCHED   
 THEN UPDATE SET   
 T.CONTENTTYPEID = S.CONTENTTYPEID
,T.[PLAN] = S.[PLAN]
,T.COMPLIANCEASSETID = S.COMPLIANCEASSETID
,T.EFFECTIVEDATE = S.EFFECTIVEDATE
,T.ORETPD = S.ORETPD
,T.ORETCU = S.ORETCU
,T.OREMO = S.OREMO
,T.ROMTPD = S.ROMTPD
,T.ROMTCU = S.ROMTCU
,T.WASTETPD = S.WASTETPD
,T.EXPITTPD = S.EXPITTPD
,T.INPITTPD = S.INPITTPD
,T.TOTALTPD = S.TOTALTPD
,T.S08TPD = S.S08TPD
,T.S10TPD = S.S10TPD
,T.S11TPD = S.S11TPD
,T.S12TPD = S.S12TPD
,T.S22TPD = S.S22TPD
,T.S23TPD = S.S23TPD
,T.TRUCKAVAILABILITY = S.TRUCKAVAILABILITY
,T.TRUCKUSEOFAVAILABILITY = S.TRUCKUSEOFAVAILABILITY
,T.TRUCKASSETEFFICIENCY = S.TRUCKASSETEFFICIENCY
,T.SHOVELAVAILABILITY = S.SHOVELAVAILABILITY
,T.SHOVELUSEOFAVAILABILITY = S.SHOVELUSEOFAVAILABILITY
,T.SHOVELASSETEFFICIENCY = S.SHOVELASSETEFFICIENCY
,T.DRILLAVAILABILITY = S.DRILLAVAILABILITY
,T.DRILLASSETEFFICIENCY = S.DRILLASSETEFFICIENCY
,T.ONEWAYHAUL = S.ONEWAYHAUL
,T.EFH = S.EFH
,T.TOTALDELTAC = S.TOTALDELTAC
,T.STRIPPINGRATIO = S.STRIPPINGRATIO
,T.E1TONS = S.E1TONS
,T.S4TONS = S.S4TONS
,T.PLANNEDDRIVERS = S.PLANNEDDRIVERS
,T.PLANNEDSUPPORT = S.PLANNEDSUPPORT
,T.PLANNEDSHOVELS = S.PLANNEDSHOVELS
,T.PLANNEDDRILLS = S.PLANNEDDRILLS
,T.SHIFTCHANGEEFFICIENCY = S.SHIFTCHANGEEFFICIENCY
,T.S08EFH = S.S08EFH
,T.S10EFH = S.S10EFH
,T.S11EFH = S.S11EFH
,T.S12EFH = S.S12EFH
,T.S22EFH = S.S22EFH
,T.S23EFH = S.S23EFH
,T.CRUSHERTARGETTPD = S.CRUSHERTARGETTPD
,T.TRUCKLOADEDTRAVEL = S.TRUCKLOADEDTRAVEL
,T.TRUCKEMPTYTRAVEL = S.TRUCKEMPTYTRAVEL
,T.SHOVELIDLETIME = S.SHOVELIDLETIME
,T.SHOVELTONSPERHOUR = S.SHOVELTONSPERHOUR
,T.TARGETFEETDRILLED = S.TARGETFEETDRILLED
,T.TARGETHOLESDRILLED = S.TARGETHOLESDRILLED
,T.REHANDLETPD = S.REHANDLETPD
,T.S08TPRH = S.S08TPRH
,T.S10TPRH = S.S10TPRH
,T.S11TPRH = S.S11TPRH
,T.S12TPRH = S.S12TPRH
,T.S22TPRH = S.S22TPRH
,T.S23TPRH = S.S23TPRH
,T.AVERAGEREADYTRUCKS = S.AVERAGEREADYTRUCKS
,T.AVERAGEREADYSHOVELS = S.AVERAGEREADYSHOVELS
,T.DRILLREADINESS = S.DRILLREADINESS
,T.SMALLCRUSHERTPD = S.SMALLCRUSHERTPD
,T.E1TPD = S.E1TPD
,T.N3TPD = S.N3TPD
,T.S4TPD = S.S4TPD
--,T.ID = S.ID
,T.CONTENTTYPE = S.CONTENTTYPE
,T.MODIFIED = S.MODIFIED
,