create or replace TABLE BL_DW_BLASTPROPERTYVALUE_INCR (
	ORIG_SRC_ID NUMBER(19,0) NOT NULL,
	SITE_CODE VARCHAR(50) NOT NULL COLLATE 'en-ci',
	BLASTID NUMBER(10,0) NOT NULL,
	REFRESHEDTIME TIMESTAMP_NTZ(9),
	DELETED BOOLEAN,
	PARAMETER VARCHAR(400) COLLATE 'en-ci',
	PLANNEDDATE VARCHAR(400) COLLATE 'en-ci',
	SHOTTYPE VARCHAR(400) COLLATE 'en-ci',
	SHOTGOAL VARCHAR(400) COLLATE 'en-ci',
	DW_FILE_TS_UTC TIMESTAMP_NTZ(9),
	DW_LOGICAL_DELETE_FLAG VARCHAR(1) COLLATE 'en-ci' DEFAULT 'N',
	DW_LOAD_TS TIMESTAMP_NTZ(0),
	DW_MODIFY_TS TIMESTAMP_NTZ(0)
)COMMENT='Incremental table for BL_DW_BLASTPROPERTYVALUE'
;
