create or replace TABLE {{ envi }}_API_REF.FUSE.DRILLBLAST_SHIFT_INCR (
	ORIG_SRC_ID NUMBER(10,0),
	SITE_CODE VARCHAR(5) NOT NULL COLLATE 'en-ci',
	SHIFT_ID VARCHAR(500) NOT NULL COLLATE 'en-ci',
	SHIFT_DATE DATE,
	SHIFT_NAME VARCHAR(255) COLLATE 'en-ci',
	SHIFT_DATE_NAME VARCHAR(255) COLLATE 'en-ci',
	ATTRIBUTED_CREW_ID NUMBER(19,0),
	CREW_NAME VARCHAR(255) COLLATE 'en-ci',
	SHIFT_NO NUMBER(10,0),
	SHIFT_START_TS_UTC TIMESTAMP_NTZ(9),
	SHIFT_END_TS_UTC TIMESTAMP_NTZ(9),
	SHIFT_START_TS_LOCAL TIMESTAMP_NTZ(9),
	SHIFT_END_TS_LOCAL TIMESTAMP_NTZ(9),
	SYSTEM_VERSION VARCHAR(50) COLLATE 'en-ci',
	DW_LOGICAL_DELETE_FLAG VARCHAR(1) COLLATE 'en-ci' DEFAULT 'N',
	DW_LOAD_TS TIMESTAMP_NTZ(0),
	DW_MODIFY_TS TIMESTAMP_NTZ(0)
)COMMENT='Incremental table for DRILLBLAST_SHIFT'
;
