/*****************************************************************************************
* TABLE     : DRILLBLAST_EQUIPMENT_INCR
* SCHEMA    : {{ envi }}_API_REF.FUSE
* SOURCE    : {{ RO_PROD }}_WG.DRILL_BLAST.DRILLBLAST_EQUIPMENT
* DATE: 2026-01-23 | AUTHOR: CARLOS CARRILLO
******************************************************************************************/
create or replace TABLE {{ envi }}_API_REF.FUSE.DRILLBLAST_EQUIPMENT_INCR (
	ORIG_SRC_ID NUMBER(10,0) NOT NULL,
	SITE_CODE VARCHAR(5) NOT NULL COLLATE 'en-ci',
	DRILL_ID NUMBER(19,0) NOT NULL,
	EQUIP_NAME VARCHAR(255) COLLATE 'en-ci',
	EQUIP_MODEL VARCHAR(255) COLLATE 'en-ci',
	SERIAL_NUMBER VARCHAR(255) COLLATE 'en-ci',
	EQUIP_CATEGORY VARCHAR(50) COLLATE 'en-ci',
	MEM_EQUIP_ID VARCHAR(255) COLLATE 'en-ci',
	EQUIP_UNIT_CODE NUMBER(10,0),
	SAP_EQUIP_NO VARCHAR(50) COLLATE 'en-ci',
	SYSTEM_VERSION VARCHAR(255) COLLATE 'en-ci',
	DW_LOGICAL_DELETE_FLAG VARCHAR(1) COLLATE 'en-ci' DEFAULT 'N',
	DW_LOAD_TS TIMESTAMP_NTZ(0),
	DW_MODIFY_TS TIMESTAMP_NTZ(0)
)COMMENT='Incremental table for DRILLBLAST_EQUIPMENT'
;
