/*****************************************************************************************
* TABLE     : LH_BUCKET_INCR
* SCHEMA    : {{ envi }}_API_REF.FUSE
* SOURCE    : {{ RO_PROD }}_WG.LOAD_HAUL.LH_BUCKET
* DATE: 2026-01-27 | AUTHOR: CARLOS CARRILLO
******************************************************************************************/
create or replace TABLE {{ envi }}_API_REF.FUSE.LH_BUCKET_INCR (
	BUCKET_ID NUMBER(19,0) NOT NULL,
	SITE_CODE VARCHAR(4) COLLATE 'en-ci',
	LOADING_CYCLE_ID NUMBER(19,0),
	LH_EQUIP_ID NUMBER(38,5),
	ORIG_SRC_ID NUMBER(38,0),
	BUCKET_OF_CYCLE NUMBER(38,0),
	SWING_EMPTY_START_TS_UTC TIMESTAMP_NTZ(3),
	SWING_EMPTY_START_TS_LOCAL TIMESTAMP_NTZ(3),
	SWING_EMPTY_END_TS_UTC TIMESTAMP_NTZ(3),
	SWING_EMPTY_END_TS_LOCAL TIMESTAMP_NTZ(3),
	DIG_START_TS_UTC TIMESTAMP_NTZ(3),
	DIG_START_TS_LOCAL TIMESTAMP_NTZ(3),
	DIG_END_TS_UTC TIMESTAMP_NTZ(3),
	DIG_END_TS_LOCAL TIMESTAMP_NTZ(3),
	SWING_FULL_START_TS_UTC TIMESTAMP_NTZ(3),
	SWING_FULL_START_TS_LOCAL TIMESTAMP_NTZ(3),
	SWING_FULL_END_TS_UTC TIMESTAMP_NTZ(3),
	SWING_FULL_END_TS_LOCAL TIMESTAMP_NTZ(3),
	TRIP_TS_UTC TIMESTAMP_NTZ(3),
	TRIP_TS_LOCAL TIMESTAMP_NTZ(3),
	DIG_X FLOAT,
	DIG_Y FLOAT,
	DIG_Z FLOAT,
	TRIP_X FLOAT,
	TRIP_Y FLOAT,
	TRIP_Z FLOAT,
	SWING_ANGLE_DEGREES FLOAT,
	BLOCK_CENTROID_X FLOAT,
	BLOCK_CENTROID_Y FLOAT,
	BLOCK_CENTROID_Z FLOAT,
	MEASURED_SHORT_TONS NUMBER(38,6),
	MEASURED_METRIC_TONS NUMBER(38,6),
	SWING_EMPTY_DURATION_MINS NUMBER(38,6),
	DIG_DURATION_MINS NUMBER(38,6),
	SWING_FULL_DURATION_MINS NUMBER(38,6),
	SYSTEM_VERSION VARCHAR(50) COLLATE 'en-ci',
	DW_LOGICAL_DELETE_FLAG VARCHAR(1) COLLATE 'en-ci' DEFAULT 'N',
	DW_LOAD_TS TIMESTAMP_NTZ(0),
	DW_MODIFY_TS TIMESTAMP_NTZ(0)
)COMMENT='Incremental table for LH_BUCKET - MERGE-driven upserts with 3-day incremental window'
;
