CREATE TYPE [dbo].[FR_DRILLING_SCORES_STG_2_IMO] AS TABLE (
    [SHIFTINDEX] numeric(18,0) NOT NULL,
    [SITE_CODE] varchar(4) NOT NULL,
    [DATE] datetime NULL,
    [SHIFT_NAME] varchar(64) NULL,
    [CREW_NAME] varchar(64) NULL,
    [OPERATORID] varchar(64) NULL,
    [OPERATORNAME] varchar(255) NULL,
    [PATTERN_NO] varchar(256) NULL,
    [PATTERN_ID] varchar(256) NOT NULL,
    [PATTERN_CREATE_DATE] datetime NOT NULL,
    [HOLE_NAME] varchar(256) NOT NULL,
    [SITE_HOLE_NAME] varchar(256) NULL,
    [HOLENUMBER] varchar(50) NULL,
    [START_HOLE_TS] datetime NOT NULL,
    [END_HOLE_TS] datetime NOT NULL,
    [HOLETIME] numeric(24,6) NULL,
    [DRILLED] numeric(1,0) NULL,
    [PENRATE] float NULL,
    [GPS_QUALITY] numeric(38,0) NULL,
    [START_POINT_X] float NULL,
    [START_POINT_Y] float NULL,
    [START_POINT_Z] float NULL,
    [ZACTUALEND] float NULL,
    [DESIGN_X_START] float NULL,
    [DESIGN_Y_START] float NULL,
    [DESIGN_Z_START] float NULL,
    [ZPLANEND] float NULL,
    [BENCH] float NULL,
    [HORIZDIFF] float NULL,
    [DEPTH] float NULL,
    [PLAN_DEPTH] float NULL,
    [DEPTHDIFF] float NULL,
    [OVER_DRILLED] numeric(1,0) NULL,
    [UNDER_DRILLED] numeric(1,0) NULL,
    [DEPTH_DIFF_FLAG] numeric(1,0) NULL,
    [HORIZ_DIFF_FLAG] numeric(1,0) NULL,
    [HORSCORE] numeric(3,0) NULL,
    [DEPTHSCORE] numeric(3,0) NULL,
    [OVERALLSCORE] numeric(10,6) NULL,
    [DRILL_HOLE] numeric(1,0) NULL,
    [DRILL_BIT_ID] varchar(50) NULL,
    [DRILL_ID] varchar(255) NOT NULL,
    [SOURCE_DRILL_SERIAL_NO] varchar(64) NULL,
    [SOURCE_SYSTEM] varchar(11) NULL,
    [RANK] numeric(18,0) NULL,
    [HOLEORD] numeric(18,0) NULL,
    [HOLEORDPATTERN] numeric(18,0) NULL,
    [WATER_DEPTH] numeric(38,9) NULL,
    [STEM_HEIGHT] numeric(38,9) NULL,
    [PROD_1_NAME] varchar(50) NULL,
    [PROD_1_WEIGHT] float NULL,
    [UTC_CREATED_DATE] datetime NULL
);