CREATE TYPE [dbo].[STATUS_EVENT_STG_2_IMO_] AS TABLE (
    [SHIFTINDEX] decimal(38,0) NOT NULL,
    [SHIFTDATE] date NOT NULL,
    [SITE_CODE] varchar(4) NOT NULL,
    [CLIID] int NULL,
    [DDBKEY] decimal(19,0) NOT NULL,
    [EQMT] varchar(50) NULL,
    [UNIT] decimal(19,0) NULL,
    [OPERID] varchar(21) NULL,
    [STARTTIME] decimal(19,0) NOT NULL,
    [ENDTIME] decimal(19,0) NULL,
    [DURATION] decimal(19,0) NULL,
    [REASON] decimal(19,0) NULL,
    [STATUS] decimal(19,0) NULL,
    [CATEGORY] decimal(19,0) NOT NULL,
    [COMMENTS] varchar(90) NULL,
    [VEVENT] decimal(19,0) NULL,
    [REASONLINK] decimal(19,0) NULL,
    [WORK_ORDER_NUMBER] varchar(8) NULL,
    [DISTRICT_CODE] varchar(4) NULL,
    [EQMTID_ORIG] varchar(50) NULL,
    [LOC] varchar(256) NULL,
    [REGION] varchar(256) NULL,
    [SYSTEM_VERSION] varchar(50) NULL,
    [DW_MODIFY_TS] datetime NULL,
    [DW_LOAD_TS] datetime NULL,
    [UTC_CREATED_DATE] datetime NULL
);