CREATE TYPE [dbo].[STATUS_EVENT_STG_2_IMO] AS TABLE (
    [shiftindex] decimal(38,0) NOT NULL,
    [shiftdate] date NOT NULL,
    [site_code] varchar(4) NOT NULL,
    [cliid] int NULL,
    [ddbkey] decimal(19,0) NOT NULL,
    [eqmt] varchar(50) NULL,
    [unit] decimal(19,0) NULL,
    [operid] varchar(21) NULL,
    [starttime] decimal(19,0) NOT NULL,
    [endtime] decimal(19,0) NULL,
    [duration] decimal(19,0) NULL,
    [reason] decimal(19,0) NULL,
    [status] decimal(19,0) NULL,
    [category] decimal(19,0) NOT NULL,
    [comments] varchar(90) NULL,
    [vevent] decimal(19,0) NULL,
    [reasonlink] decimal(19,0) NULL,
    [work_order_number] varchar(8) NULL,
    [district_code] varchar(4) NULL,
    [eqmtid_orig] varchar(50) NULL,
    [loc] varchar(256) NULL,
    [region] varchar(256) NULL,
    [system_version] varchar(50) NULL,
    [dw_modify_ts] datetime NULL,
    [dw_load_ts] datetime NULL,
    [UTC_CREATED_DATE] datetime NOT NULL
);