CREATE TABLE [dbo].[pit_reason_stg] (
    [ORIG_SRC_ID] numeric(38,0) NULL,
    [SITE_CODE] varchar(4) NULL,
    [STATUS] numeric(38,0) NULL,
    [PIT_REASON_ID] numeric(38,0) NULL,
    [DBPREVIOUS] numeric(38,0) NULL,
    [DBNEXT] numeric(38,0) NULL,
    [DBVERSION] numeric(38,0) NULL,
    [PIT_DBNAME] varchar(32) NULL,
    [DBKEY] numeric(38,0) NULL,
    [FIELDID] varchar(8) NULL,
    [FIELDDELAYTIME] numeric(38,0) NULL,
    [FIELDCATEGORY] numeric(38,0) NULL,
    [FIELDNAME] varchar(30) NULL,
    [FIELDMAINTTIME] numeric(38,0) NULL,
    [FIELDAUTO] numeric(38,0) NULL,
    [FIELDDFCT] numeric(38,0) NULL,
    [FIELDGCINCL] numeric(38,0) NULL,
    [FIELDALTNAME] varchar(50) NULL,
    [FIELDEXPECTDUR] numeric(38,0) NULL,
    [FIELDTASK] numeric(38,0) NULL,
    [FIELDLRINCL] numeric(38,0) NULL,
    [FIELDICON] varchar(20) NULL,
    [FIELDFTYPE] numeric(38,0) NULL,
    [UTC_CREATED_DATE] datetime NULL
);