CREATE TABLE [cli].[ZZZ_PLAN_VALUES_back202302] (
    [CONTENTTYPEID] varchar(100) NOT NULL,
    [ShiftID] varchar(50) NULL,
    [COMPLIANCEASSETID] varchar(100) NULL,
    [PB] varchar(50) NULL,
    [Shovel] varchar(50) NULL,
    [HolesDrilled] decimal(28,5) NULL,
    [FeetDrilled] decimal(28,5) NULL,
    [TotalTonsMoved] decimal(28,5) NULL,
    [TotalTonsMined] decimal(28,5) NULL,
    [TotalMillOreMined] decimal(28,5) NULL,
    [MillOreTonsMoved] decimal(28,5) NULL,
    [TotalTonstoCrusher] decimal(28,5) NULL,
    [StockpileTons] decimal(28,5) NULL,
    [WasteTons] decimal(28,5) NULL,
    [EFH] decimal(28,5) NULL,
    [ID] int NOT NULL,
    [CONTENTTYPE] varchar(50) NOT NULL,
    [MODIFIED] datetime NOT NULL,
    [CREATED] datetime NOT NULL,
    [CREATEDBYID] int NOT NULL,
    [MODIFIEDBYID] int NOT NULL,
    [OWSHIDDENVERSION] int NOT NULL,
    [VERSION] decimal(10,5) NOT NULL,
    [PATH] varchar(2000) NOT NULL,
    [UTC_CREATED_DATE] datetime NULL
);