CREATE VIEW [bag2].[MSMODEL_SHIFT] AS


-- MSMODEL_SHIFT

CREATE VIEW [bag2].[MSMODEL_SHIFT]
AS

SELECT 
    'BAG' AS SITE_CODE,
    CONCAT(RIGHT(SUBSTRING(REPORTING_DATE, 1, 8), 6), '00', 
        CASE 
            WHEN shifttype = 0 THEN 1
            WHEN shifttype = 1 THEN 2 
            ELSE NULL
        END) AS SHIFT_ID,
    CONCAT(RIGHT(SUBSTRING(REPORTING_DATE, 1, 8), 6), LOWER(SUBSTRING(S.name, 1, 1))) AS SHIFT_NAME,
    LOWER(SUBSTRING(S.name, 1, 1)) AS SHIFT_SUFFIX,
    LEFT(S.NAME, CHARINDEX('SHIFT', S.name) + LEN('shift') - 1) AS FULL_SHIFT_SUFFIX,
    CAST(CONVERT(DATETIME, [STARTTIME_UTC]) AT TIME ZONE 'UTC' AT TIME ZONE 'US Mountain Standard Time' AS DATE) AS SHIFT_START_DATE, -- Gerald requested in this format
    -- CAST(CAST(CONVERT(DATETIME, [STARTTIME_UTC]) AT TIME ZONE 'UTC' AT TIME ZONE 'US Mountain Standard Time' AS DATE) AS DATETIME) AS ShiftStartDate2,
    CONVERT(DATETIME, [STARTTIME_UTC]) AT TIME ZONE 'UTC' AT TIME ZONE 'US Mountain Standard Time' AS SHIFT_START_DATE_TIME,
    DATEDIFF(SECOND, CAST(CAST(CONVERT(DATETIME, [STARTTIME_UTC]) AT TIME ZONE 'UTC' AT TIME ZONE 'US Mountain Standard Time' AS DATE) AS DATETIME),
        CAST(CONVERT(DATETIME, [STARTTIME_UTC]) AT TIME ZONE 'UTC' AT TIME ZONE 'US Mountain Standard Time' AS DATETIME)) AS STARTS,
    C.NAME AS CREW_NAME,
    DATEDIFF(SECOND, STARTTIME_UTC, ENDTIME_UTC) AS SHIFT_DURATION,
    UPPER(FORMAT(CONVERT(DATE, REPORTING_DATE, 12), 'dd-MMM-yy')) AS SHIFT_DATE
FROM [ConnectedOperations].[bag2].[SHIFT] S WITH (NOLOCK)
LEFT JOIN [ConnectedOperations].[bag2].[CREW] C WITH (NOLOCK)
    ON S.CREW = C.OID;



