CREATE VIEW [bag2].[VIEW_DELAY_ETL] AS

CREATE VIEW [bag2].[VIEW_DELAY_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.DELAY_OID') AS DELAY_OID,
JSON_VALUE(DATA_VALUE.value, '$.ECF_CLASS_ID') AS ECF_CLASS_ID,
JSON_VALUE(DATA_VALUE.value, '$.ACKNOWLEDGE') AS ACKNOWLEDGE,
JSON_VALUE(DATA_VALUE.value, '$.ACKNOWLEDGED') AS ACKNOWLEDGED,
JSON_VALUE(DATA_VALUE.value, '$.CONFIRMED') AS CONFIRMED,
JSON_VALUE(DATA_VALUE.value, '$.FREQUENCY_TYPE') AS FREQUENCY_TYPE,
JSON_VALUE(DATA_VALUE.value, '$.SHIFT_TYPE') AS SHIFT_TYPE,
JSON_VALUE(DATA_VALUE.value, '$.DELAYCLASS') AS DELAYCLASS,
JSON_VALUE(DATA_VALUE.value, '$.TARGET_MACHINE') AS TARGET_MACHINE,
JSON_VALUE(DATA_VALUE.value, '$.TARGET_ROAD') AS TARGET_ROAD,
JSON_VALUE(DATA_VALUE.value, '$.TARGET_LOCATION') AS TARGET_LOCATION,
JSON_VALUE(DATA_VALUE.value, '$.DESCRIPTION') AS DESCRIPTION,
JSON_VALUE(DATA_VALUE.value, '$.FINISH_UTC') AS FINISH_UTC,
JSON_VALUE(DATA_VALUE.value, '$.OFFICECONFIRM') AS OFFICECONFIRM,
JSON_VALUE(DATA_VALUE.value, '$.REPORTEDBY_PERSON') AS REPORTEDBY_PERSON,
JSON_VALUE(DATA_VALUE.value, '$.REPORTEDBY_USER') AS REPORTEDBY_USER,
JSON_VALUE(DATA_VALUE.value, '$.START1_UTC') AS START1_UTC,
JSON_VALUE(DATA_VALUE.value, '$.STATUS') AS STATUS,
JSON_VALUE(DATA_VALUE.value, '$.PRODUCTIONREPORTINGONLY') AS PRODUCTIONREPORTINGONLY,
JSON_VALUE(DATA_VALUE.value, '$.FIELDNOTIFICATIONREQUIRED') AS FIELDNOTIFICATIONREQUIRED,
JSON_VALUE(DATA_VALUE.value, '$.ENGINESTOPPED') AS ENGINESTOPPED,
JSON_VALUE(DATA_VALUE.value, '$.WORKORDER_REF') AS WORKORDER_REF,
JSON_VALUE(DATA_VALUE.value, '$.SOURCE_SYSTEM') AS SOURCE_SYSTEM,
JSON_VALUE(DATA_VALUE.value, '$.LAST_MODIFIED_UTC') AS LAST_MODIFIED_UTC,
JSON_VALUE(DATA_VALUE.value, '$.CREATED_DATE_UTC') AS CREATED_DATE_UTC,
JSON_VALUE(DATA_VALUE.value, '$.ENDEDBY_PERSON') AS ENDEDBY_PERSON,
JSON_VALUE(DATA_VALUE.value, '$.ENDEDBY_USER') AS ENDEDBY_USER,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_TYPE') AS CHANGE_TYPE,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_ID') AS CHANGE_ID,
Getutcdate() AS UTC_CREATED_DATE
--NULL AS UTC_LOGICAL_DELETED_DATE
FROM [bag2].[DELAY_STAGE] LS
CROSS APPLY OPENJSON (LS.SRC_JSON) AS DATA_VALUE
