CREATE VIEW [bag2].[VIEW_CYCLEDELAY_ETL] AS

CREATE VIEW [bag2].[VIEW_CYCLEDELAY_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.OID') AS OID,
JSON_VALUE(DATA_VALUE.value, '$.START_TIME_UTC') AS START_TIME_UTC,
JSON_VALUE(DATA_VALUE.value, '$.END_TIME_UTC') AS END_TIME_UTC,
JSON_VALUE(DATA_VALUE.value, '$.DELAYOID') AS DELAYOID,
JSON_VALUE(DATA_VALUE.value, '$.DELAY_CLASS_OID') AS DELAY_CLASS_OID,
JSON_VALUE(DATA_VALUE.value, '$.DELAY_CLASS_NAME') AS DELAY_CLASS_NAME,
JSON_VALUE(DATA_VALUE.value, '$.DELAY_CLASS_DESC') AS DELAY_CLASS_DESC,
JSON_VALUE(DATA_VALUE.value, '$.DELAY_CATEGORY') AS DELAY_CATEGORY,
JSON_VALUE(DATA_VALUE.value, '$.ESTIMATED_DURATION_MAGNITUDE') AS ESTIMATED_DURATION_MAGNITUDE,
JSON_VALUE(DATA_VALUE.value, '$.ESTIMATED_FUEL_USED') AS ESTIMATED_FUEL_USED,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_TYPE') AS CHANGE_TYPE,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_ID') AS CHANGE_ID,
Getutcdate() AS UTC_CREATED_DATE
--NULL AS UTC_LOGICAL_DELETED_DATE
FROM [bag2].[CYCLEDELAY_STAGE] LS
CROSS APPLY OPENJSON (LS.SRC_JSON) AS DATA_VALUE
