CREATE VIEW [bag2].[VIEW_CYCLEACTIVITYCOMPONENT_ETL] AS

CREATE VIEW [bag2].[VIEW_CYCLEACTIVITYCOMPONENT_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.OID') AS OID,
JSON_VALUE(DATA_VALUE.value, '$.NAME') AS NAME,
JSON_VALUE(DATA_VALUE.value, '$.START_TIME_UTC') AS START_TIME_UTC,
JSON_VALUE(DATA_VALUE.value, '$.END_TIME_UTC') AS END_TIME_UTC,
JSON_VALUE(DATA_VALUE.value, '$.ESTIMATED_FUEL_USED') AS ESTIMATED_FUEL_USED,
JSON_VALUE(DATA_VALUE.value, '$.CREATED_DATE_UTC') AS CREATED_DATE_UTC,
JSON_VALUE(DATA_VALUE.value, '$.LAST_MODIFIED_UTC') AS LAST_MODIFIED_UTC,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_TYPE') AS CHANGE_TYPE,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_ID') AS CHANGE_ID,
Getutcdate() AS UTC_CREATED_DATE
--NULL AS UTC_LOGICAL_DELETED_DATE
FROM [bag2].[CYCLEACTIVITYCOMPONENT_STAGE] LS
CROSS APPLY OPENJSON (LS.SRC_JSON) AS DATA_VALUE
