CREATE VIEW [bag2].[VIEW_DELAYCLASS_ETL] AS

CREATE VIEW [bag2].[VIEW_DELAYCLASS_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.DELAYCLASS_OID') AS DELAYCLASS_OID,
JSON_VALUE(DATA_VALUE.value, '$.ACKNOWLEDGEMENTREQ') AS ACKNOWLEDGEMENTREQ,
JSON_VALUE(DATA_VALUE.value, '$.INFIELD') AS INFIELD,
JSON_VALUE(DATA_VALUE.value, '$.DELAYCATEGORY') AS DELAYCATEGORY,
JSON_VALUE(DATA_VALUE.value, '$.DESCRIPTION') AS DESCRIPTION,
JSON_VALUE(DATA_VALUE.value, '$.DURATION') AS DURATION,
JSON_VALUE(DATA_VALUE.value, '$.ID') AS ID,
JSON_VALUE(DATA_VALUE.value, '$.NAME') AS NAME,
JSON_VALUE(DATA_VALUE.value, '$.IS_ACTIVE') AS IS_ACTIVE,
JSON_VALUE(DATA_VALUE.value, '$.PRODUCTIONREPORTINGONLY') AS PRODUCTIONREPORTINGONLY,
JSON_VALUE(DATA_VALUE.value, '$.EXTERNALDESC') AS EXTERNALDESC,
JSON_VALUE(DATA_VALUE.value, '$.EXTERNALREF') AS EXTERNALREF,
JSON_VALUE(DATA_VALUE.value, '$.EMAIL') AS EMAIL,
JSON_VALUE(DATA_VALUE.value, '$.ENGINESTOPPED') AS ENGINESTOPPED,
JSON_VALUE(DATA_VALUE.value, '$.ISVALIDFORROAD') AS ISVALIDFORROAD,
JSON_VALUE(DATA_VALUE.value, '$.ISVALIDFORLOCATION') AS ISVALIDFORLOCATION,
JSON_VALUE(DATA_VALUE.value, '$.DELAYACTIVITYCLASS') AS DELAYACTIVITYCLASS,
JSON_VALUE(DATA_VALUE.value, '$.MODEL_UPDATE_VERSION') AS MODEL_UPDATE_VERSION,
JSON_VALUE(DATA_VALUE.value, '$.LAYER_UPDATE_VERSION') AS LAYER_UPDATE_VERSION,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_TYPE') AS CHANGE_TYPE,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_ID') AS CHANGE_ID,
Getutcdate() AS UTC_CREATED_DATE
--NULL AS UTC_LOGICAL_DELETED_DATE
FROM [bag2].[DELAYCLASS_STAGE] LS
CROSS APPLY OPENJSON (LS.SRC_JSON) AS DATA_VALUE
