CREATE VIEW [bag2].[VIEW_MACHINE_ETL] AS

CREATE VIEW [bag2].[VIEW_MACHINE_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.MACHINE_OID') AS MACHINE_OID,
JSON_VALUE(DATA_VALUE.value, '$.ECF_CLASS_ID') AS ECF_CLASS_ID,
JSON_VALUE(DATA_VALUE.value, '$.IS_ACTIVE') AS IS_ACTIVE,
JSON_VALUE(DATA_VALUE.value, '$.NAME') AS NAME,
JSON_VALUE(DATA_VALUE.value, '$.SERIALNUMBER') AS SERIALNUMBER,
JSON_VALUE(DATA_VALUE.value, '$.EXTERNALREF') AS EXTERNALREF,
JSON_VALUE(DATA_VALUE.value, '$.EXTERNALDESC') AS EXTERNALDESC,
JSON_VALUE(DATA_VALUE.value, '$.CLASS') AS CLASS,
JSON_VALUE(DATA_VALUE.value, '$.ID') AS ID,
JSON_VALUE(DATA_VALUE.value, '$.IGNOREFORASSIGNMENT') AS IGNOREFORASSIGNMENT,
JSON_VALUE(DATA_VALUE.value, '$.NONPRODUCTION') AS NONPRODUCTION,
JSON_VALUE(DATA_VALUE.value, '$.EXCLUDEFROMOPERATORALLOCATION') AS EXCLUDEFROMOPERATORALLOCATION,
JSON_VALUE(DATA_VALUE.value, '$.EXCLUDEFROMTRANSPORTALLOCATION') AS EXCLUDEFROMTRANSPORTALLOCATION,
JSON_VALUE(DATA_VALUE.value, '$.PRODUCTIVITY') AS PRODUCTIVITY,
JSON_VALUE(DATA_VALUE.value, '$.USEDYNAMICPRODUCTIVITY') AS USEDYNAMICPRODUCTIVITY,
JSON_VALUE(DATA_VALUE.value, '$.ANTENNA_OVERRIDE') AS ANTENNA_OVERRIDE,
JSON_VALUE(DATA_VALUE.value, '$.ANTENNA_X') AS ANTENNA_X,
JSON_VALUE(DATA_VALUE.value, '$.ANTENNA_Y') AS ANTENNA_Y,
JSON_VALUE(DATA_VALUE.value, '$.ANTENNA_Z') AS ANTENNA_Z,
JSON_VALUE(DATA_VALUE.value, '$.USECLASSFUELLEVELS') AS USECLASSFUELLEVELS,
JSON_VALUE(DATA_VALUE.value, '$.USECLASSBURNRATES') AS USECLASSBURNRATES,
JSON_VALUE(DATA_VALUE.value, '$.USECLASSREFUELING') AS USECLASSREFUELING,
JSON_VALUE(DATA_VALUE.value, '$.USECLASSCAPABILITIES') AS USECLASSCAPABILITIES,
JSON_VALUE(DATA_VALUE.value, '$.FUELCAPACITY') AS FUELCAPACITY,
JSON_VALUE(DATA_VALUE.value, '$.FUELTYPE') AS FUELTYPE,
JSON_VALUE(DATA_VALUE.value, '$.MINIMUMREFUELAMOUNT') AS MINIMUMREFUELAMOUNT,
JSON_VALUE(DATA_VALUE.value, '$.REFUELLEVEL') AS REFUELLEVEL,
JSON_VALUE(DATA_VALUE.value, '$.CRITICALFUELLEVEL') AS CRITICALFUELLEVEL,
JSON_VALUE(DATA_VALUE.value, '$.EXPECTEDDURATIONBETWEENREFUELS') AS EXPECTEDDURATIONBETWEENREFUELS,
JSON_VALUE(DATA_VALUE.value, '$.CURRENTFUELLEVEL') AS CURRENTFUELLEVEL,
JSON_VALUE(DATA_VALUE.value, '$.CURRENTFUELSTATUS') AS CURRENTFUELSTATUS,
JSON_VALUE(DATA_VALUE.value, '$.LASTFUELSTATUSUPDATETIME_UTC') AS LASTFUELSTATUSUPDATETIME_UTC,
JSON_VALUE(DATA_VALUE.value, '$.LASTFUELLEVELUPDATETIME_UTC') AS LASTFUELLEVELUPDATETIME_UTC,
JSON_VALUE(DATA_VALUE.value, '$.LASTREFUELTIME_UTC') AS LASTREFUELTIME_UTC,
JSON_VALUE(DATA_VALUE.value, '$.LASTREFUELQUANTITY') AS LASTREFUELQUANTITY,
JSON_VALUE(DATA_VALUE.value, '$.LASTREFUELESTIMATE') AS LASTREFUELESTIMATE,
JSON_VALUE(DATA_VALUE.value, '$.LASTDURATIONBETWEENREFUELINGS') AS LASTDURATIONBETWEENREFUELINGS,
JSON_VALUE(DATA_VALUE.value, '$.USEDYNAMICFUELBURNRATE') AS USEDYNAMICFUELBURNRATE,
JSON_VALUE(DATA_VALUE.value, '$.FUELBURNALGORITHM') AS FUELBURNALGORITHM,
JSON_VALUE(DATA_VALUE.value, '$.IDLEFUELBURNRATE') AS IDLEFUELBURNRATE,
JSON_VALUE(DATA_VALUE.value, '$.WORKINGFUELBURNRATE') AS WORKINGFUELBURNRATE,
JSON_VALUE(DATA_VALUE.value, '$.IGNORE_VIMS_FUEL_SENSOR') AS IGNORE_VIMS_FUEL_SENSOR,
JSON_VALUE(DATA_VALUE.value, '$.SHIFTCHANGEGROUP') AS SHIFTCHANGEGROUP,
JSON_VALUE(DATA_VALUE.value, '$.SHIFTCHANGE_LOCATION') AS SHIFTCHANGE_LOCATION,
JSON_VALUE(DATA_VALUE.value, '$.SHIFTCHANGE_LOADINGTOOL') AS SHIFTCHANGE_LOADINGTOOL,
JSON_VALUE(DATA_VALUE.value, '$.HAS_ONBOARD_HARDWARE') AS HAS_ONBOARD_HARDWARE,
JSON_VALUE(DATA_VALUE.value, '$.HEALTH_PLATFORM') AS HEALTH_PLATFORM,
JSON_VALUE(DATA_VALUE.value, '$.OFFICEBADGPS') AS OFFICEBADGPS,
JSON_VALUE(DATA_VALUE.value, '$.AUTO_REFUEL') AS AUTO_REFUEL,
JSON_VALUE(DATA_VALUE.value, '$.DEFAULTLOCATION') AS DEFAULTLOCATION,
JSON_VALUE(DATA_VALUE.value, '$.REFUELWINDOW') AS REFUELWINDOW,
JSON_VALUE(DATA_VALUE.value, '$.REFUELLOADSTATE') AS REFUELLOADSTATE,
JSON_VALUE(DATA_VALUE.value, '$.REFUELASSIGNDELAY') AS REFUELASSIGNDELAY,
JSON_VALUE(DATA_VALUE.value, '$.REFUELARRIVEDE