CREATE VIEW [bag2].[VIEW_GRADEBLOCK_ETL] AS

CREATE VIEW [bag2].[VIEW_GRADEBLOCK_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.GRADEBLOCK_OID') AS GRADEBLOCK_OID,
JSON_VALUE(DATA_VALUE.value, '$.MININGFINISH_UTC') AS MININGFINISH_UTC,
JSON_VALUE(DATA_VALUE.value, '$.MININGSTART_UTC') AS MININGSTART_UTC,
JSON_VALUE(DATA_VALUE.value, '$.HEIGHT') AS HEIGHT,
JSON_VALUE(DATA_VALUE.value, '$.ID') AS ID,
JSON_VALUE(DATA_VALUE.value, '$.MATERIAL') AS MATERIAL,
JSON_VALUE(DATA_VALUE.value, '$.MINEDMASS') AS MINEDMASS,
JSON_VALUE(DATA_VALUE.value, '$.MINEDVOL') AS MINEDVOL,
JSON_VALUE(DATA_VALUE.value, '$.NAME') AS NAME,
JSON_VALUE(DATA_VALUE.value, '$.ORIGINALVOL') AS ORIGINALVOL,
JSON_VALUE(DATA_VALUE.value, '$.ORIGINALMASS') AS ORIGINALMASS,
JSON_VALUE(DATA_VALUE.value, '$.STOCKPILE') AS STOCKPILE,
JSON_VALUE(DATA_VALUE.value, '$.IS_ACTIVE') AS IS_ACTIVE,
JSON_VALUE(DATA_VALUE.value, '$.INUSE') AS INUSE,
JSON_VALUE(DATA_VALUE.value, '$.READONLY') AS READONLY,
JSON_VALUE(DATA_VALUE.value, '$.VERSION') AS VERSION,
JSON_VALUE(DATA_VALUE.value, '$.HIERARCHY') AS HIERARCHY,
JSON_VALUE(DATA_VALUE.value, '$.GRADEENGINE') AS GRADEENGINE,
JSON_VALUE(DATA_VALUE.value, '$.TARGETDESTINATION') AS TARGETDESTINATION,
JSON_VALUE(DATA_VALUE.value, '$.EXTERNALREF') AS EXTERNALREF,
JSON_VALUE(DATA_VALUE.value, '$.EXTERNALDESC') AS EXTERNALDESC,
JSON_VALUE(DATA_VALUE.value, '$.CREATETIME_UTC') AS CREATETIME_UTC,
JSON_VALUE(DATA_VALUE.value, '$.OPENFORDUMPING') AS OPENFORDUMPING,
JSON_VALUE(DATA_VALUE.value, '$.OPENFORLOADING') AS OPENFORLOADING,
JSON_VALUE(DATA_VALUE.value, '$.CARRYOPTION') AS CARRYOPTION,
JSON_VALUE(DATA_VALUE.value, '$.CARRY_FROM_OID') AS CARRY_FROM_OID,
JSON_VALUE(DATA_VALUE.value, '$.ENTRY_WAYPOINT_OID') AS ENTRY_WAYPOINT_OID,
JSON_VALUE(DATA_VALUE.value, '$.CONNECTING_WAYPOINT_OID') AS CONNECTING_WAYPOINT_OID,
JSON_VALUE(DATA_VALUE.value, '$.DESTINATION_OID') AS DESTINATION_OID,
JSON_VALUE(DATA_VALUE.value, '$.PROCESSOR_OID') AS PROCESSOR_OID,
JSON_VALUE(DATA_VALUE.value, '$.MODEL_UPDATE_VERSION') AS MODEL_UPDATE_VERSION,
JSON_VALUE(DATA_VALUE.value, '$.LAYER_UPDATE_VERSION') AS LAYER_UPDATE_VERSION,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_TYPE') AS CHANGE_TYPE,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_ID') AS CHANGE_ID,
Getutcdate() AS UTC_CREATED_DATE
--NULL AS UTC_LOGICAL_DELETED_DATE
FROM [bag2].[GRADEBLOCK_STAGE] LS
CROSS APPLY OPENJSON (LS.SRC_JSON) AS DATA_VALUE
