CREATE VIEW [ABR].[CONOPS_ABR_AUTONOMOUS_TRUCK_V] AS



--select * from [ABR].[CONOPS_ABR_AUTONOMOUS_TRUCK_V]
CREATE VIEW [ABR].[CONOPS_ABR_AUTONOMOUS_TRUCK_V]
AS

SELECT DISTINCT
	FieldId AS TruckId,
	0 AS Autonomous
FROM ABR.pit_truck_c WITH(NOLOCK)
WHERE FieldId IS NOT NULL
	AND FieldId <> ''


