CREATE VIEW [ABR].[SHIFT_OPER] AS




--SELECT * FROM ABR.SHIFT_OPER
CREATE VIEW ABR.SHIFT_OPER
AS

SELECT
'ABR' AS SiteFlag,
*
FROM SCMAOperational.dbo.SHIFTShiftOper WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM ABR.SHIFT_INFO)




