CREATE VIEW [ABR].[SHIFT_GRADE] AS



--SELECT * FROM ABR.SHIFT_GRADE
CREATE VIEW ABR.SHIFT_GRADE
AS

SELECT
'ABR' AS SiteFlag,
*
FROM SCMAOperational.dbo.SHIFTShiftgrade WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM ABR.SHIFT_INFO)



