CREATE VIEW [ABR].[SHIFT_EQMT] AS




--SELECT * FROM ABR.SHIFT_EQMT
CREATE VIEW ABR.SHIFT_EQMT
AS

SELECT
'ABR' AS SiteFlag,
*
FROM SCMAOperational.dbo.SHIFTShifteqmt WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM ABR.SHIFT_INFO)




