
/******************************************************************  
* PROCEDURE : dbo.[UPSERT_CONOPS_OEE_2]
* PURPOSE	: Upsert [UPSERT_CONOPS_OEE_2]
* NOTES     : 
* CREATED	: mfahmi
* SAMPLE    : EXEC dbo.[UPSERT_CONOPS_OEE_2] 
* MODIFIED DATE		AUTHOR				DESCRIPTION  
*------------------------------------------------------------------  
* {28 NOV 2022}		{mfahmi}			{Initial Created}  
*******************************************************************/  
CREATE  PROCEDURE [dbo].[UPSERT_CONOPS_OEE_2]
AS
BEGIN

MERGE dbo.OEE_2 AS T
USING (
    SELECT 
        SITE_CODE, SHIFTINDEX, SHIFTDATE, SHIFT, READYTIME, TOTALTIME,
        SHOVELLOADCOUNT, LOADERLOADCOUNT, TOTALCYCLETIME, DELTAC,
        EQMT, HOS, CYCLECOUNT, UTC_CREATED_DATE
    FROM dbo.OEE_stg_2
) AS S
ON (
    T.SITE_CODE = S.SITE_CODE AND
    T.SHIFTINDEX = S.SHIFTINDEX AND
    T.EQMT = S.EQMT AND
    T.HOS = S.HOS
)
WHEN MATCHED THEN
    UPDATE SET
        T.SHIFTDATE = S.SHIFTDATE,
        T.SHIFT = S.SHIFT,
        T.READYTIME = S.READYTIME,
        T.TOTALTIME = S.TOTALTIME,
        T.SHOVELLOADCOUNT = S.SHOVELLOADCOUNT,
        T.LOADERLOADCOUNT = S.LOADERLOADCOUNT,
        T.TOTALCYCLETIME = S.TOTALCYCLETIME,
        T.DELTAC = S.DELTAC,
        T.CYCLECOUNT = S.CYCLECOUNT,
        T.UTC_CREATED_DATE = S.UTC_CREATED_DATE
WHEN NOT MATCHED THEN
    INSERT (
        SITE_CODE, SHIFTINDEX, SHIFTDATE, SHIFT, READYTIME, TOTALTIME,
        SHOVELLOADCOUNT, LOADERLOADCOUNT, TOTALCYCLETIME, DELTAC,
        EQMT, HOS, CYCLECOUNT, UTC_CREATED_DATE
    )
    VALUES (
        S.SITE_CODE, S.SHIFTINDEX, S.SHIFTDATE, S.SHIFT, S.READYTIME, S.TOTALTIME,
        S.SHOVELLOADCOUNT, S.LOADERLOADCOUNT, S.TOTALCYCLETIME, S.DELTAC,
        S.EQMT, S.HOS, S.CYCLECOUNT, S.UTC_CREATED_DATE
    )
WHEN NOT MATCHED BY SOURCE THEN
    DELETE;

--Update Job Control
UPDATE [dbo].[DI_JOB_CONTROL_ENTRY_TS_BASE]
SET dw_load_ts = GETUTCDATE()
WHERE job_name = 'job_conops_oee_2';

END




