
/******************************************************************  
* PROCEDURE : dbo.[UPSERT_CONOPS_LH_OPER_TOTAL_SUM_2]
* PURPOSE	: Upsert [UPSERT_CONOPS_LH_OPER_TOTAL_SUM_2]
* NOTES     : 
* CREATED	: mfahmi
* SAMPLE    : EXEC dbo.[UPSERT_CONOPS_LH_OPER_TOTAL_SUM_2]
* MODIFIED DATE		AUTHOR				DESCRIPTION  
*------------------------------------------------------------------  
* {01 DEC 2022}		{mfahmi}			{Initial Created}  
*******************************************************************/  
CREATE  PROCEDURE [dbo].[UPSERT_CONOPS_LH_OPER_TOTAL_SUM_2]
AS
BEGIN

MERGE dbo.LH_OPER_TOTAL_SUM_2 AS T
USING (
    SELECT 
        SHIFTINDEX, SHIFTDATE, SITE_CODE, CLIID, DDBKEY, EQMTID, EQMTID_ORIG, IDLETIME, LOADCNT,
        LOADTIME, LOCID, LOGINTIME, NAME, OPERID, PIT, SPOTTIME,
        TMCAT00, TMCAT01, TMCAT02, TMCAT03, TMCAT04, TMCAT05, TMCAT06, TMCAT07, TMCAT08, TMCAT09,
        TMCAT10, TMCAT11, TMCAT12, TMCAT13, TMCAT14, TMCAT15, TMCAT16, TMCAT17, TMCAT18, TMCAT19,
        TOTALLOADS, TOTALTIME, TOTALTONS, UNIT, UNIT_CODE, SYSTEM_VERSION, UTC_CREATED_DATE
    FROM dbo.LH_OPER_TOTAL_SUM_stg_2
) AS S
ON (
    T.SITE_CODE = S.SITE_CODE AND
    T.SHIFTINDEX = S.SHIFTINDEX AND
    T.EQMTID = S.EQMTID AND
    T.LOGINTIME = S.LOGINTIME
)
WHEN MATCHED THEN
    UPDATE SET
        T.SHIFTDATE = S.SHIFTDATE,
        T.CLIID = S.CLIID,
        T.DDBKEY = S.DDBKEY,
        T.EQMTID_ORIG = S.EQMTID_ORIG,
        T.IDLETIME = S.IDLETIME,
        T.LOADCNT = S.LOADCNT,
        T.LOADTIME = S.LOADTIME,
        T.LOCID = S.LOCID,
        T.NAME = S.NAME,
        T.OPERID = S.OPERID,
        T.PIT = S.PIT,
        T.SPOTTIME = S.SPOTTIME,
        T.TMCAT00 = S.TMCAT00,
        T.TMCAT01 = S.TMCAT01,
        T.TMCAT02 = S.TMCAT02,
        T.TMCAT03 = S.TMCAT03,
        T.TMCAT04 = S.TMCAT04,
        T.TMCAT05 = S.TMCAT05,
        T.TMCAT06 = S.TMCAT06,
        T.TMCAT07 = S.TMCAT07,
        T.TMCAT08 = S.TMCAT08,
        T.TMCAT09 = S.TMCAT09,
        T.TMCAT10 = S.TMCAT10,
        T.TMCAT11 = S.TMCAT11,
        T.TMCAT12 = S.TMCAT12,
        T.TMCAT13 = S.TMCAT13,
        T.TMCAT14 = S.TMCAT14,
        T.TMCAT15 = S.TMCAT15,
        T.TMCAT16 = S.TMCAT16,
        T.TMCAT17 = S.TMCAT17,
        T.TMCAT18 = S.TMCAT18,
        T.TMCAT19 = S.TMCAT19,
        T.TOTALLOADS = S.TOTALLOADS,
        T.TOTALTIME = S.TOTALTIME,
        T.TOTALTONS = S.TOTALTONS,
        T.UNIT = S.UNIT,
        T.UNIT_CODE = S.UNIT_CODE,
        T.SYSTEM_VERSION = S.SYSTEM_VERSION,
        T.UTC_CREATED_DATE = S.UTC_CREATED_DATE
WHEN NOT MATCHED THEN
    INSERT (
        SHIFTINDEX, SHIFTDATE, SITE_CODE, CLIID, DDBKEY, EQMTID, EQMTID_ORIG, IDLETIME, LOADCNT,
        LOADTIME, LOCID, LOGINTIME, NAME, OPERID, PIT, SPOTTIME,
        TMCAT00, TMCAT01, TMCAT02, TMCAT03, TMCAT04, TMCAT05, TMCAT06, TMCAT07, TMCAT08, TMCAT09,
        TMCAT10, TMCAT11, TMCAT12, TMCAT13, TMCAT14, TMCAT15, TMCAT16, TMCAT17, TMCAT18, TMCAT19,
        TOTALLOADS, TOTALTIME, TOTALTONS, UNIT, UNIT_CODE, SYSTEM_VERSION, UTC_CREATED_DATE
    )
    VALUES (
        S.SHIFTINDEX, S.SHIFTDATE, S.SITE_CODE, S.CLIID, S.DDBKEY, S.EQMTID, S.EQMTID_ORIG, S.IDLETIME, S.LOADCNT,
        S.LOADTIME, S.LOCID, S.LOGINTIME, S.NAME, S.OPERID, S.PIT, S.SPOTTIME,
        S.TMCAT00, S.TMCAT01, S.TMCAT02, S.TMCAT03, S.TMCAT04, S.TMCAT05, S.TMCAT06, S.TMCAT07, S.TMCAT08, S.TMCAT09,
        S.TMCAT10, S.TMCAT11, S.TMCAT12, S.TMCAT13, S.TMCAT14, S.TMCAT15, S.TMCAT16, S.TMCAT17, S.TMCAT18, S.TMCAT19,
        S.TOTALLOADS, S.TOTALTIME, S.TOTALTONS, S.UNIT, S.UNIT_CODE, S.SYSTEM_VERSION, S.UTC_CREATED_DATE
    )
WHEN NOT MATCHED BY SOURCE THEN
    DELETE;

--Update Job Control
UPDATE [dbo].[DI_JOB_CONTROL_ENTRY_TS_BASE]
SET dw_load_ts = GETUTCDATE()
WHERE job_name = 'job_conops_lh_oper_total_sum_2';

END

