
/******************************************************************      
* PROCEDURE : DBO.[UPSERT_CONOPS_SHOVEL_ELEVATION_EXT]    
* PURPOSE : UPSERT [UPSERT_CONOPS_SHOVEL_ELEVATION_EXT]    
* NOTES     :     
* CREATED : MFAHMI    
* SAMPLE    : EXEC DBO.[UPSERT_CONOPS_SHOVEL_ELEVATION_EXT]    
* MODIFIED DATE  AUTHOR    DESCRIPTION      
*------------------------------------------------------------------      
* {22 JUL 2023}  {MFAHMI}   {INITIAL CREATED}      
*******************************************************************/
CREATE PROCEDURE [DBO].[UPSERT_CONOPS_SHOVEL_ELEVATION_EXT] AS BEGIN MERGE [DBO].[SHOVEL_ELEVATION_EXT] AS T USING (
  SELECT 
    SITEFLAG, 
    SHIFTID, 
    SENSOR_ID, 
    SHOVELID, 
    SENSOR_VALUE, 
    VALUE_UTC_TS, 
    GETUTCDATE() UTC_CREATED_DATE 
  FROM 
    [BAG].[CONOPS_BAG_GPS_ELEVATION_V] 
  UNION ALL 
  SELECT 
    SITEFLAG, 
    SHIFTID, 
    SENSOR_ID, 
    SHOVELID, 
    SENSOR_VALUE, 
    VALUE_UTC_TS, 
    GETUTCDATE() UTC_CREATED_DATE 
  FROM 
    [CER].[CONOPS_CER_GPS_ELEVATION_V] 
  UNION ALL 
  SELECT 
    SITEFLAG, 
    SHIFTID, 
    SENSOR_ID, 
    SHOVELID, 
    SENSOR_VALUE, 
    VALUE_UTC_TS, 
    GETUTCDATE() UTC_CREATED_DATE 
  FROM 
    [CHI].[CONOPS_CHI_GPS_ELEVATION_V] 
  UNION ALL 
  SELECT 
    SITEFLAG, 
    SHIFTID, 
    SENSOR_ID, 
    SHOVELID, 
    SENSOR_VALUE, 
    VALUE_UTC_TS, 
    GETUTCDATE() UTC_CREATED_DATE 
  FROM 
    [CLI].[CONOPS_CLI_GPS_ELEVATION_V] 
  UNION ALL 
  SELECT 
    SITEFLAG, 
    SHIFTID, 
    SENSOR_ID, 
    SHOVELID, 
    SENSOR_VALUE, 
    VALUE_UTC_TS, 
    GETUTCDATE() UTC_CREATED_DATE 
  FROM 
    [MOR].[CONOPS_MOR_GPS_ELEVATION_V] 
  UNION ALL 
  SELECT 
    SITEFLAG, 
    SHIFTID, 
    SENSOR_ID, 
    SHOVELID, 
    SENSOR_VALUE, 
    VALUE_UTC_TS, 
    GETUTCDATE() UTC_CREATED_DATE 
  FROM 
    [SAF].[CONOPS_SAF_GPS_ELEVATION_V] 
  UNION ALL 
  SELECT 
    SITEFLAG, 
    SHIFTID, 
    SENSOR_ID, 
    SHOVELID, 
    SENSOR_VALUE, 
    VALUE_UTC_TS, 
    GETUTCDATE() UTC_CREATED_DATE 
  FROM 
    [SIE].[CONOPS_SIE_GPS_ELEVATION_V]
) AS S ON (
  T.SITEFLAG = S.SITEFLAG 
  AND T.SHIFTID = S.SHIFTID 
  AND T.SENSOR_ID = S.SENSOR_ID 
  AND T.VALUE_UTC_TS = S.VALUE_UTC_TS
) WHEN MATCHED THEN 
UPDATE 
SET 
  T.SHOVELID = S.SHOVELID, 
  T.SENSOR_VALUE = S.SENSOR_VALUE, 
  T.UTC_CREATED_DATE = S.UTC_CREATED_DATE WHEN NOT MATCHED THEN INSERT (
    SITEFLAG, SHIFTID, SENSOR_ID, SHOVELID, 
    SENSOR_VALUE, VALUE_UTC_TS, UTC_CREATED_DATE
  ) 
VALUES 
  (
    S.SITEFLAG, S.SHIFTID, S.SENSOR_ID, 
    S.SHOVELID, S.SENSOR_VALUE, S.VALUE_UTC_TS, 
    S.UTC_CREATED_DATE
  );
END