
/******************************************************************  
* PROCEDURE : dbo.[UPSERT_CONOPS_MMT_LOCATION]
* PURPOSE	: Upsert [UPSERT_CONOPS_MMT_LOCATION]
* NOTES     : 
* CREATED	: ggosal1
* SAMPLE    : EXEC dbo.[UPSERT_CONOPS_MMT_LOCATION] 
* MODIFIED DATE		AUTHOR				DESCRIPTION  
*------------------------------------------------------------------  
* {14 JAN 2026}		{ggosal1}			{Initial Created}  
*******************************************************************/  
CREATE  PROCEDURE [dbo].[UPSERT_CONOPS_MMT_LOCATION]
AS
BEGIN

MERGE dbo.MMT_LOCATION AS T
USING (
	SELECT SITE_CODE
		,DISPATCH_LOCATION_ID
		,LOCATION_TYPE_CODE
		,LOCATION_SUBTYPE_CODE
		,MIN_SHIFTDATE
		,MAX_SHIFTDATE
		,PIT_NAME
		,PUSHBACK_NAME
		,LOCATION_GROUP_1
		,LOCATION_GROUP_2
		,ELEV
		,LOCATION_GEO_TEXT
		,CREATED_BY
		,CREATED_TS
		,LAST_UPDATED_BY
		,LAST_UPDATED_TS
	FROM dbo.MMT_LOCATION_STG
	) AS S
	ON (
			T.SITE_CODE = S.SITE_CODE
			AND T.DISPATCH_LOCATION_ID = S.DISPATCH_LOCATION_ID
			)
WHEN MATCHED
	THEN
		UPDATE
		SET T.LOCATION_TYPE_CODE = S.LOCATION_TYPE_CODE
			,T.LOCATION_SUBTYPE_CODE = S.LOCATION_SUBTYPE_CODE
			,T.MIN_SHIFTDATE = S.MIN_SHIFTDATE
			,T.MAX_SHIFTDATE = S.MAX_SHIFTDATE
			,T.PIT_NAME = S.PIT_NAME
			,T.PUSHBACK_NAME = S.PUSHBACK_NAME
			,T.LOCATION_GROUP_1 = S.LOCATION_GROUP_1
			,T.LOCATION_GROUP_2 = S.LOCATION_GROUP_2
			,T.ELEV = S.ELEV
			,T.LOCATION_GEO_TEXT = S.LOCATION_GEO_TEXT
			,T.CREATED_BY = S.CREATED_BY
			,T.CREATED_TS = S.CREATED_TS
			,T.LAST_UPDATED_BY = S.LAST_UPDATED_BY
			,T.LAST_UPDATED_TS = S.LAST_UPDATED_TS
WHEN NOT MATCHED
	THEN
		INSERT (
			SITE_CODE
			,DISPATCH_LOCATION_ID
			,LOCATION_TYPE_CODE
			,LOCATION_SUBTYPE_CODE
			,MIN_SHIFTDATE
			,MAX_SHIFTDATE
			,PIT_NAME
			,PUSHBACK_NAME
			,LOCATION_GROUP_1
			,LOCATION_GROUP_2
			,ELEV
			,LOCATION_GEO_TEXT
			,CREATED_BY
			,CREATED_TS
			,LAST_UPDATED_BY
			,LAST_UPDATED_TS
			)
		VALUES (
			S.SITE_CODE
			,S.DISPATCH_LOCATION_ID
			,S.LOCATION_TYPE_CODE
			,S.LOCATION_SUBTYPE_CODE
			,S.MIN_SHIFTDATE
			,S.MAX_SHIFTDATE
			,S.PIT_NAME
			,S.PUSHBACK_NAME
			,S.LOCATION_GROUP_1
			,S.LOCATION_GROUP_2
			,S.ELEV
			,S.LOCATION_GEO_TEXT
			,S.CREATED_BY
			,S.CREATED_TS
			,S.LAST_UPDATED_BY
			,S.LAST_UPDATED_TS
			)
WHEN NOT MATCHED BY SOURCE
	THEN
		DELETE;

--Update Job Control
UPDATE [dbo].[DI_JOB_CONTROL_ENTRY_TS_BASE]
SET dw_load_ts = GETUTCDATE()
WHERE job_name = 'job_conops_mmt_location';

END


