

/******************************************************************  
* PROCEDURE : dbo.[UPSERT_CONOPS_DELTA_C_2]
* PURPOSE	: Upsert [UPSERT_CONOPS_DELTA_C_2]
* NOTES     : 
* CREATED	: mfahmi
* SAMPLE    : EXEC dbo.[UPSERT_CONOPS_DELTA_C_2] 
* MODIFIED DATE		AUTHOR				DESCRIPTION  
*------------------------------------------------------------------  
* {28 NOV 2022}		{mfahmi}			{Initial Created}  
*******************************************************************/  
CREATE  PROCEDURE [dbo].[UPSERT_CONOPS_DELTA_C_2]
AS
BEGIN

MERGE dbo.DELTA_C_2 AS T
USING (
    SELECT 
        CLIID, DDBKEY, SITE_CODE, START_DATE_TS, DELTAC_TS, END_DATE_TS, SHIFTINDEX, SHIFTDATE,
        YEAR_CODE, MONTH_CODE, MONTHS, SHIFT, SHIFT_CODE, CREW_CODE, CREW, HARVHOS, DIGTYPE,
        SHVTYPE, DIPPER, TRKTYPE, PAYLOAD, IDLETIME, SPOTTIME, LOADTIME, DUMPINGTIME, CRUSHERIDLE,
        TRAVELEMPTY, TRAVELLOADED, TOTALCYCLE, CALCTRAVEMPTY, CALCTRAVLOADED, HOS, TIMEFULL,
        TIMELOADED, EXCAV, SOPERID, SOPER, TRUCK, TOPERID, TOPER, LOAD_CODE, MATERIAL, BENCH,
        UNIT_CODE, UNIT, DUMPNAME, TRUCK_IDLEDELTA, SPOTDELTA, LOADDELTA, DUMPDELTA, ET_DELTA,
        LT_DELTA, DELTA_C, TOAVGDELTAC, TOSTDEVDELTAC, TOAVGIDLEDELTA, TOSTDEVIDLEDELTA,
        TOAVGSPOTDELTA, TOSTDEVSPOTDELTA, TOAVGLOADDELTA, TOSTDEVLOADDELTA, TOAVGETDELTA,
        TOSTDEVETDELTA, TOAVGLTDELTA, TOSTDEVLTDELTA, TOAVGDUMPDELTA, TOSTDEVDUMPDELTA,
        VTODELTAC3, LOAD_SEQ_NO, GRADE, EXTRALOAD, LOADTYPE, LOADTONS, MEASURETONS_SHOVEL,
        OVER_TRUCK_FLAG, UNDER_TRUCK_FLAG, DUMP_FLAG, SHOVEL_IDLE, CRUSHER_DUMP_FLAG,
        DUMP_NUMBER, LDUMP_HOS, DUMP_HOS, DUMP_OPER_ID, SHOVEL_EQMTTYPE_CODE, TRUCK_EQMTTYPE_CODE,
        SHVL_OPS_PRTL_EQUIP_GROUP_NO_CODE, TRK_OPS_PRTL_EQUIP_GROUP_NO_CODE, SHOVEL_IDLEDELTA,
        ELIFTUP, ELIFTDOWN, DISTLOADED, FLIFTUP, FLIFTDOWN, DISTEMPTY, CRUSHERDELTA,
        DUMPINGDELTA, EMPTYHAUL, LOAD_TIMEARRIVE, TIMELOAD, BEGINSPOT, HANGTIME, DUMP_TIMEARRIVE,
        TIMEDUMP, TIMEEMPTY, DUMP_TIMEARRIVE_TS, TIMEDUMP_TS, TIMEEMPTY_TS, IDLEDELTA, REGION,
        UTC_CREATED_DATE
    FROM dbo.DELTA_C_stg_2
) AS S
ON (
    T.SITE_CODE = S.SITE_CODE AND
    T.SHIFTINDEX = S.SHIFTINDEX AND
    T.DDBKEY = S.DDBKEY
)
WHEN MATCHED THEN
    UPDATE SET
        T.CLIID = S.CLIID,
        T.START_DATE_TS = S.START_DATE_TS,
        T.DELTAC_TS = S.DELTAC_TS,
        T.END_DATE_TS = S.END_DATE_TS,
        T.SHIFTDATE = S.SHIFTDATE,
        T.YEAR_CODE = S.YEAR_CODE,
        T.MONTH_CODE = S.MONTH_CODE,
        T.MONTHS = S.MONTHS,
        T.SHIFT = S.SHIFT,
        T.SHIFT_CODE = S.SHIFT_CODE,
        T.CREW_CODE = S.CREW_CODE,
        T.CREW = S.CREW,
        T.HARVHOS = S.HARVHOS,
        T.DIGTYPE = S.DIGTYPE,
        T.SHVTYPE = S.SHVTYPE,
        T.DIPPER = S.DIPPER,
        T.TRKTYPE = S.TRKTYPE,
        T.PAYLOAD = S.PAYLOAD,
        T.IDLETIME = S.IDLETIME,
        T.SPOTTIME = S.SPOTTIME,
        T.LOADTIME = S.LOADTIME,
        T.DUMPINGTIME = S.DUMPINGTIME,
        T.CRUSHERIDLE = S.CRUSHERIDLE,
        T.TRAVELEMPTY = S.TRAVELEMPTY,
        T.TRAVELLOADED = S.TRAVELLOADED,
        T.TOTALCYCLE = S.TOTALCYCLE,
        T.CALCTRAVEMPTY = S.CALCTRAVEMPTY,
        T.CALCTRAVLOADED = S.CALCTRAVLOADED,
        T.HOS = S.HOS,
        T.TIMEFULL = S.TIMEFULL,
        T.TIMELOADED = S.TIMELOADED,
        T.EXCAV = S.EXCAV,
        T.SOPERID = S.SOPERID,
        T.SOPER = S.SOPER,
        T.TRUCK = S.TRUCK,
        T.TOPERID = S.TOPERID,
        T.TOPER = S.TOPER,
        T.LOAD_CODE = S.LOAD_CODE,
        T.MATERIAL = S.MATERIAL,
        T.BENCH = S.BENCH,
        T.UNIT_CODE = S.UNIT_CODE,
        T.UNIT = S.UNIT,
        T.DUMPNAME = S.DUMPNAME,
        T.TRUCK_IDLEDELTA = S.TRUCK_IDLEDELTA,
        T.SPOTDELTA = S.SPOTDELTA,
        T.LOADDELTA = S.LOADDELTA,
        T.DUMPDELTA = S.DUMPDELTA,
        T.ET_DELTA = S.ET_DELTA,
        T.LT_DELTA = S.LT_DELTA,
        