CREATE VIEW [bag2].[MSHIST_OPERATOR] AS




CREATE VIEW [bag2].[MSHIST_OPERATOR]
AS

SELECT 
    'BAG' AS SITE_CODE,
    CONCAT(RIGHT(SUBSTRING(REPORTING_DATE, 1, 8), 6), '00', 
        CASE 
            WHEN shifttype = 0 THEN 1
            WHEN shifttype = 1 THEN 2 
            ELSE NULL
        END) AS SHIFT_ID,
    P.PERSONNELID AS OPERATOR_ID,
    P.NAME AS OPERATOR_NAME,
    L.NAME AS LOC_NAME,
    CR.NAME AS CREW_NAME
FROM [BAG_MSMODEL].[dbo].[PERSON] P WITH (NOLOCK)
LEFT JOIN [BAG_MSHIST].[dbo].[CYCLE] C WITH (NOLOCK)
    ON P.PERSON_OID = C.PRIMARYOPERATOR
LEFT JOIN [BAG_MSMODEL].[dbo].[LOCATION] L WITH (NOLOCK)
    ON C.SOURCELOCATION = L.LOCATION_OID 
LEFT JOIN [BAG_MSMODEL].[dbo].[PERSON_CREW] PC WITH (NOLOCK)
    ON P.PERSON_OID = PC.PERSON_OID
LEFT JOIN [BAG_MSMODEL].[dbo].[CREW] CR WITH (NOLOCK)
    ON CR.OID = PC.CREW_OID
LEFT JOIN [BAG_MSMODEL].[dbo].[SHIFT] S WITH (NOLOCK)
    ON C.ENDTIME_UTC >= S.STARTTIME_UTC
    AND C.ENDTIME_UTC <= S.ENDTIME_UTC;




