CREATE VIEW [bag2].[VIEW_PERSON_ETL] AS

CREATE VIEW [bag2].[VIEW_PERSON_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.PERSON_OID') AS PERSON_OID,
JSON_VALUE(DATA_VALUE.value, '$.ECF_CLASS_ID') AS ECF_CLASS_ID,
JSON_VALUE(DATA_VALUE.value, '$.IS_ACTIVE') AS IS_ACTIVE,
JSON_VALUE(DATA_VALUE.value, '$.NAME') AS NAME,
JSON_VALUE(DATA_VALUE.value, '$.MAINTENANCE_USER') AS MAINTENANCE_USER,
JSON_VALUE(DATA_VALUE.value, '$.MACPASSWORD') AS MACPASSWORD,
JSON_VALUE(DATA_VALUE.value, '$.PERSONNELID') AS PERSONNELID,
JSON_VALUE(DATA_VALUE.value, '$.ALLOCATIONDATE') AS ALLOCATIONDATE,
JSON_VALUE(DATA_VALUE.value, '$.ALLOCATIONPRIORITY') AS ALLOCATIONPRIORITY,
JSON_VALUE(DATA_VALUE.value, '$.EXCLUDEFROMMACHINEALLOCATION') AS EXCLUDEFROMMACHINEALLOCATION,
JSON_VALUE(DATA_VALUE.value, '$.SHIFTCHANGEGROUP') AS SHIFTCHANGEGROUP,
JSON_VALUE(DATA_VALUE.value, '$.TECH_LEVEL') AS TECH_LEVEL,
JSON_VALUE(DATA_VALUE.value, '$.POSITION') AS POSITION,
JSON_VALUE(DATA_VALUE.value, '$.DEPARTMENT') AS DEPARTMENT,
JSON_VALUE(DATA_VALUE.value, '$.PRIMARY_SUPERVISOR') AS PRIMARY_SUPERVISOR,
JSON_VALUE(DATA_VALUE.value, '$.HIRE_DATE') AS HIRE_DATE,
JSON_VALUE(DATA_VALUE.value, '$.EXTERNALREF') AS EXTERNALREF,
JSON_VALUE(DATA_VALUE.value, '$.EXTERNALDESC') AS EXTERNALDESC,
JSON_VALUE(DATA_VALUE.value, '$.USERREF') AS USERREF,
JSON_VALUE(DATA_VALUE.value, '$.LAYER_UPDATE_VERSION') AS LAYER_UPDATE_VERSION,
JSON_VALUE(DATA_VALUE.value, '$.EMT') AS EMT,
JSON_VALUE(DATA_VALUE.value, '$.FIRST_RESPONDER') AS FIRST_RESPONDER,
JSON_VALUE(DATA_VALUE.value, '$.BUS_DRIVER') AS BUS_DRIVER,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_TYPE') AS CHANGE_TYPE,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_ID') AS CHANGE_ID,
Getutcdate() AS UTC_CREATED_DATE
--NULL AS UTC_LOGICAL_DELETED_DATE
FROM [bag2].[PERSON_STAGE] LS
CROSS APPLY OPENJSON (LS.SRC_JSON) AS DATA_VALUE
