CREATE VIEW [bag2].[VIEW_DELAYCATEGORY_ETL] AS

CREATE VIEW [bag2].[VIEW_DELAYCATEGORY_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.DELAYCATEGORY_OID') AS DELAYCATEGORY_OID,
JSON_VALUE(DATA_VALUE.value, '$.NAME') AS NAME,
JSON_VALUE(DATA_VALUE.value, '$.COLOUR') AS COLOUR,
JSON_VALUE(DATA_VALUE.value, '$.BOLD') AS BOLD,
JSON_VALUE(DATA_VALUE.value, '$.ITALIC') AS ITALIC,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_TYPE') AS CHANGE_TYPE,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_ID') AS CHANGE_ID,
Getutcdate() AS UTC_CREATED_DATE
--NULL AS UTC_LOGICAL_DELETED_DATE
FROM [bag2].[DELAYCATEGORY_STAGE] LS
CROSS APPLY OPENJSON (LS.SRC_JSON) AS DATA_VALUE
