CREATE VIEW [bag2].[VIEW_MATERIAL_ETL] AS

CREATE VIEW [bag2].[VIEW_MATERIAL_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.MATERIAL_OID') AS MATERIAL_OID,
JSON_VALUE(DATA_VALUE.value, '$.CODECAES') AS CODECAES,
JSON_VALUE(DATA_VALUE.value, '$.COLOUR') AS COLOUR,
JSON_VALUE(DATA_VALUE.value, '$.DESCRIPTION') AS DESCRIPTION,
JSON_VALUE(DATA_VALUE.value, '$.ID') AS ID,
JSON_VALUE(DATA_VALUE.value, '$.BANKDENSITY') AS BANKDENSITY,
JSON_VALUE(DATA_VALUE.value, '$.LOOSEDENSITY') AS LOOSEDENSITY,
JSON_VALUE(DATA_VALUE.value, '$.MATUNIT') AS MATUNIT,
JSON_VALUE(DATA_VALUE.value, '$.NAME') AS NAME,
JSON_VALUE(DATA_VALUE.value, '$.IS_ACTIVE') AS IS_ACTIVE,
JSON_VALUE(DATA_VALUE.value, '$.MATERIALGROUP') AS MATERIALGROUP,
JSON_VALUE(DATA_VALUE.value, '$.EXTERNALREF') AS EXTERNALREF,
JSON_VALUE(DATA_VALUE.value, '$.EXTERNALDESC') AS EXTERNALDESC,
JSON_VALUE(DATA_VALUE.value, '$.MODEL_UPDATE_VERSION') AS MODEL_UPDATE_VERSION,
JSON_VALUE(DATA_VALUE.value, '$.LAYER_UPDATE_VERSION') AS LAYER_UPDATE_VERSION,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_TYPE') AS CHANGE_TYPE,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_ID') AS CHANGE_ID,
Getutcdate() AS UTC_CREATED_DATE
--NULL AS UTC_LOGICAL_DELETED_DATE
FROM [bag2].[MATERIAL_STAGE] LS
CROSS APPLY OPENJSON (LS.SRC_JSON) AS DATA_VALUE
