CREATE VIEW [bag2].[VIEW_CREW_ETL] AS

CREATE VIEW [bag2].[VIEW_CREW_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.OID') AS OID,
JSON_VALUE(DATA_VALUE.value, '$.NAME') AS NAME,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_TYPE') AS CHANGE_TYPE,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_ID') AS CHANGE_ID,
Getutcdate() AS UTC_CREATED_DATE
--NULL AS UTC_LOGICAL_DELETED_DATE
FROM [bag2].[CREW_STAGE] LS
CROSS APPLY OPENJSON (LS.SRC_JSON) AS DATA_VALUE
