CREATE VIEW [bag2].[VIEW_PERSON_CREW_ETL] AS

CREATE VIEW [bag2].[VIEW_PERSON_CREW_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.PERSON_OID') AS PERSON_OID,
JSON_VALUE(DATA_VALUE.value, '$.CREW_OID') AS CREW_OID,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_TYPE') AS CHANGE_TYPE,
--JSON_VALUE(DATA_VALUE.value, '$.CHANGE_ID') AS CHANGE_ID,
Getutcdate() AS UTC_CREATED_DATE
--NULL AS UTC_LOGICAL_DELETED_DATE
FROM [bag2].[PERSON_CREW_STAGE] LS
CROSS APPLY OPENJSON (LS.SRC_JSON) AS DATA_VALUE
