CREATE TABLE [bag2].[VIRTUALBEACON] (
    [SITEFLAG] varchar(5) NOT NULL,
    [VIRTUALBEACON_OID] bigint NOT NULL,
    [IS_ACTIVE] bit NOT NULL,
    [NAME] nvarchar(254) NOT NULL,
    [DESCRIPTION] nvarchar(254) NULL,
    [COLOUR] tinyint NOT NULL,
    [DATE_LAST_MODIFIED_UTC] datetime2 NULL,
    [FLAGS] tinyint NOT NULL,
    [HEIGHT] float NULL,
    [ID] int NOT NULL,
    [LOADERID] int NULL,
    [RADIUS] float NULL,
    [REASSIGNMT] bit NOT NULL,
    [REASSIGNFULL] bit NOT NULL,
    [TYPE] smallint NOT NULL,
    [VERSION] int NOT NULL,
    [ZORDER] tinyint NOT NULL,
    [MISSED_COUNT] bigint NOT NULL,
    [ROUTE_POINT_X] float NULL,
    [ROUTE_POINT_Y] float NULL,
    [ROUTE_POINT_Z] float NULL,
    [EXTERNALREF] nvarchar(254) NULL,
    [EXTERNALDESC] nvarchar(254) NULL,
    [MODEL_UPDATE_VERSION] bigint NOT NULL,
    [LAYER_UPDATE_VERSION] bigint NOT NULL,
    [UTC_CREATED_DATE] datetime NOT NULL,
    [UTC_LOGICAL_DELETED_DATE] datetime NULL
);