/*****************************************************************************************
* TABLE     : DRILL_BLAST__BL_DW_BLAST_INCR
* DATABASE  : SNOWFLAKE_WG
* SCHEMA    : dbo
* SOURCE    : Snowflake DEV_API_REF.FUSE.BL_DW_BLAST_INCR
* DATE      : 2026-01-28 | AUTHOR: CARLOS CARRILLO
******************************************************************************************/
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DRILL_BLAST__BL_DW_BLAST_INCR]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DRILL_BLAST__BL_DW_BLAST_INCR] (
    ORIG_SRC_ID BIGINT NOT NULL,
    SITE_CODE NVARCHAR(50) NOT NULL,
    ID INT NOT NULL,
    NAME NVARCHAR(1000),
    STATUS NVARCHAR(20),
    FIREDTIME DATETIME2,
    ABANDONEDTIME DATETIME2,
    ABANDONEDCOMMENT NVARCHAR(MAX),
    SUSPENDEDTIME DATETIME2,
    SUSPENDEDCOMMENT NVARCHAR(MAX),
    VOLUME FLOAT,
    HOLECOUNT INT,
    SHOTFIRERNAME NVARCHAR(500),
    REFRESHEDTIME DATETIME2,
    DELETED BIT,
    DW_FILE_TS_UTC DATETIME2,
    DW_LOGICAL_DELETE_FLAG NVARCHAR(1) DEFAULT 'N',
    DW_LOAD_TS DATETIME2,
    DW_MODIFY_TS DATETIME2,
    CONSTRAINT PK_DRILL_BLAST__BL_DW_BLAST_INCR PRIMARY KEY (ORIG_SRC_ID, SITE_CODE, ID)
);
END
GO

-- Create index for archival queries
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_DRILL_BLAST__BL_DW_BLAST_INCR_DW_MODIFY_TS')
CREATE INDEX IX_DRILL_BLAST__BL_DW_BLAST_INCR_DW_MODIFY_TS ON [dbo].[DRILL_BLAST__BL_DW_BLAST_INCR](DW_MODIFY_TS);
GO
