/*****************************************************************************************
* TABLE     : DRILL_BLAST__DRILLBLAST_OPERATOR_INCR
* DATABASE  : SNOWFLAKE_WG
* SCHEMA    : dbo
* SOURCE    : Snowflake DEV_API_REF.FUSE.DRILLBLAST_OPERATOR_INCR
* DATE      : 2026-01-28 | AUTHOR: CARLOS CARRILLO
******************************************************************************************/
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DRILL_BLAST__DRILLBLAST_OPERATOR_INCR]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DRILL_BLAST__DRILLBLAST_OPERATOR_INCR] (
    SYSTEM_OPERATOR_ID BIGINT NOT NULL,
    SITE_CODE NVARCHAR(5) NOT NULL,
    ORIG_SRC_ID INT,
    APPLICATION_OPERATOR_ID NVARCHAR(255),
    OPERATOR_NAME NVARCHAR(255),
    CREW_ID INT,
    CREW_NAME NVARCHAR(255),
    SAP_OPERATOR_ID NVARCHAR(255),
    EFFECTIVE_START_DATE DATETIME2,
    END_DATE DATETIME2,
    SYSTEM_VERSION NVARCHAR(255),
    DW_LOGICAL_DELETE_FLAG NVARCHAR(1) DEFAULT 'N',
    DW_LOAD_TS DATETIME2,
    DW_MODIFY_TS DATETIME2,
    CONSTRAINT PK_DRILL_BLAST__DRILLBLAST_OPERATOR_INCR PRIMARY KEY (SYSTEM_OPERATOR_ID, SITE_CODE)
);
END
GO

-- Create index for archival queries
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_DRILL_BLAST__DRILLBLAST_OPERATOR_INCR_DW_MODIFY_TS')
CREATE INDEX IX_DRILL_BLAST__DRILLBLAST_OPERATOR_INCR_DW_MODIFY_TS ON [dbo].[DRILL_BLAST__DRILLBLAST_OPERATOR_INCR](DW_MODIFY_TS);
GO
