/*****************************************************************************************
* TABLE     : LOAD_HAUL__LH_EQUIPMENT_STATUS_EVENT_INCR
* DATABASE  : SNOWFLAKE_WG
* SCHEMA    : dbo
* SOURCE    : Snowflake DEV_API_REF.FUSE.LH_EQUIPMENT_STATUS_EVENT_INCR
* DATE      : 2026-01-28 | AUTHOR: CARLOS CARRILLO
* NOTES     : Uses START_TS_LOCAL for archival (not DW_MODIFY_TS)
******************************************************************************************/
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LOAD_HAUL__LH_EQUIPMENT_STATUS_EVENT_INCR]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[LOAD_HAUL__LH_EQUIPMENT_STATUS_EVENT_INCR] (
    SITE_CODE NVARCHAR(4) NOT NULL,
    EQUIP_ID BIGINT NOT NULL,
    EQUIP_CATEGORY NVARCHAR(64),
    ORIG_SRC_ID BIGINT,
    EQUIP_STATUS_EVENT_SK NVARCHAR(MAX),
    SHIFT_ID NVARCHAR(MAX),
    CYCLE_ID BIGINT,
    STATUS_EVENT_REASON_ID BIGINT,
    START_TS_UTC DATETIME2(3),
    END_TS_UTC DATETIME2(3),
    START_TS_LOCAL DATETIME2(3) NOT NULL,  -- Used for archival
    END_TS_LOCAL DATETIME2(3),
    DURATION_MINS DECIMAL(38,12),
    EVENT_COMMENTS NVARCHAR(MAX),
    DISTINCT_STATUS_EVENT_FLAG TINYINT,
    PREV_STATUS_EVENT_ID NVARCHAR(MAX),
    NEXT_STATUS_EVENT_ID NVARCHAR(MAX),
    SYSTEM_VERSION NVARCHAR(50),
    DW_LOGICAL_DELETE_FLAG NVARCHAR(1) DEFAULT 'N',
    DW_LOAD_TS DATETIME2,
    DW_MODIFY_TS DATETIME2
    -- Note: No single-column PK possible, using composite
);
END
GO

-- Create index for archival queries (uses START_TS_LOCAL)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_LOAD_HAUL__LH_EQUIPMENT_STATUS_EVENT_INCR_START_TS_LOCAL')
CREATE INDEX IX_LOAD_HAUL__LH_EQUIPMENT_STATUS_EVENT_INCR_START_TS_LOCAL ON [dbo].[LOAD_HAUL__LH_EQUIPMENT_STATUS_EVENT_INCR](START_TS_LOCAL);
GO
