
/******************************************************************      
* PROCEDURE : DBO.[UPSERT_CONOPS_LH_LOAD_2]    
* PURPOSE : UPSERT [UPSERT_CONOPS_LH_LOAD_2]    
* NOTES     :     
* CREATED : MFAHMI    
* SAMPLE    : EXEC DBO.[UPSERT_CONOPS_LH_LOAD_2]    
* MODIFIED DATE  AUTHOR    DESCRIPTION      
*------------------------------------------------------------------      
* {01 DEC 2022}  {MFAHMI}   {INITIAL CREATED} 
* {16 APR 2024}  {GGOSAL1}  {Remove PK}      
*******************************************************************/      

CREATE  PROCEDURE [dbo].[UPSERT_CONOPS_LH_LOAD_2]    
AS    
BEGIN    
    
MERGE dbo.LH_LOAD_2 AS T
USING (
    SELECT
        SHIFTINDEX, SHIFTDATE, SITE_CODE, CLIID, DDBKEY, ATRTEH, ATRTFH, BEGINSPOT, CTRTEH, CTRTFH,
        DCSBOOMJAC, DCSBUCKETS, DCSLASTBKT, DCSLOADTM, DCSPROPELT, DCSSWINGAN, DCSSWINGTM, DCSTONS,
        DCSTRUCK, DISTEH, DISTFH, DMP, DUMPREC, DUMPTIME, EFHEH, EFHFH, EMPTYHAUL, EOPER,
        EX_TMCAT00, EX_TMCAT01, EX_TMCAT02, EX_TMCAT03, EX_TMCAT04, EX_TMCAT05, EX_TMCAT06,
        EX_TMCAT07, EX_TMCAT08, EX_TMCAT09, EX_TMCAT10, EX_TMCAT11, EX_TMCAT12, EX_TMCAT13,
        EX_TMCAT14, EX_TMCAT15, EX_TMCAT16, EX_TMCAT17, EX_TMCAT18, EX_TMCAT19, EXCAV, EXCAV_ORIG,
        EXCAVNEXTL, EXCAVPREVL, EXTRALOAD, FULLHAUL, GRADE, HANGTIME, HOS, IDLETIME, IEH, IFH, ILD,
        INTVL, ISP, LEYCAES, LIFT_DOWN, LIFT_UP, LIFTDIST_D, LIFTDIST_U, LOAD, LOADINGTIM,
        LOADNUMBER, LOADOLD, LOADTONS_US, LOADTYPE, LOC, MEASURETON, OPER, OT, QUEUETIME,
        SHIFTLINK, SPOTTIME, TIMEARRIVE, TIMEARRIVE_TS, TIMEFULL, TIMEFULL_TS, TIMELOAD,
        TIMELOAD_TS, TK_TMCAT00, TK_TMCAT01, TK_TMCAT02, TK_TMCAT03, TK_TMCAT04, TK_TMCAT05,
        TK_TMCAT06, TK_TMCAT07, TK_TMCAT08, TK_TMCAT09, TK_TMCAT10, TK_TMCAT11, TK_TMCAT12,
        TK_TMCAT13, TK_TMCAT14, TK_TMCAT15, TK_TMCAT16, TK_TMCAT17, TK_TMCAT18, TK_TMCAT19,
        TRUCK, TRUCK_ORIG, UT, VAL_EHAUL, VAL_FHAUL, VAL_LD, VAL_MT, VAL_SP, VAL_SPLD, VAL_SPLDMT,
        DUMPASN, LOADTONS, DLOCK, ELOCK, EDLOCK, RLOCK, TBARS0, TBARS1, TBARS2, TBARS3,
        TMBARS0_CODE, TMBARS0, TMBARS1_CODE, TMBARS1, TMBARS2_CODE, TMBARS2, TMBARS3_CODE,
        TMBARS3, TMBARS4_CODE, TMBARS4, TMBARS5_CODE, TMBARS5, SYSTEM_VERSION, UTC_CREATED_DATE
    FROM dbo.LH_LOAD_STG_2
) AS S
ON (
    T.SITE_CODE = S.SITE_CODE AND
    T.SHIFTINDEX = S.SHIFTINDEX AND
    T.DDBKEY = S.DDBKEY
)
WHEN MATCHED THEN
    UPDATE SET
        T.SHIFTDATE = S.SHIFTDATE,
        T.CLIID = S.CLIID,
        T.ATRTEH = S.ATRTEH,
        T.ATRTFH = S.ATRTFH,
        T.BEGINSPOT = S.BEGINSPOT,
        T.CTRTEH = S.CTRTEH,
        T.CTRTFH = S.CTRTFH,
        T.DCSBOOMJAC = S.DCSBOOMJAC,
        T.DCSBUCKETS = S.DCSBUCKETS,
        T.DCSLASTBKT = S.DCSLASTBKT,
        T.DCSLOADTM = S.DCSLOADTM,
        T.DCSPROPELT = S.DCSPROPELT,
        T.DCSSWINGAN = S.DCSSWINGAN,
        T.DCSSWINGTM = S.DCSSWINGTM,
        T.DCSTONS = S.DCSTONS,
        T.DCSTRUCK = S.DCSTRUCK,
        T.DISTEH = S.DISTEH,
        T.DISTFH = S.DISTFH,
        T.DMP = S.DMP,
        T.DUMPREC = S.DUMPREC,
        T.DUMPTIME = S.DUMPTIME,
        T.EFHEH = S.EFHEH,
        T.EFHFH = S.EFHFH,
        T.EMPTYHAUL = S.EMPTYHAUL,
        T.EOPER = S.EOPER,
        T.EX_TMCAT00 = S.EX_TMCAT00,
        T.EX_TMCAT01 = S.EX_TMCAT01,
        T.EX_TMCAT02 = S.EX_TMCAT02,
        T.EX_TMCAT03 = S.EX_TMCAT03,
        T.EX_TMCAT04 = S.EX_TMCAT04,
        T.EX_TMCAT05 = S.EX_TMCAT05,
        T.EX_TMCAT06 = S.EX_TMCAT06,
        T.EX_TMCAT07 = S.EX_TMCAT07,
        T.EX_TMCAT08 = S.EX_TMCAT08,
        T.EX_TMCAT09 = S.EX_TMCAT09,
        T.EX_TMCAT10 = S.EX_TMCAT10,
        T.EX_TMCAT11 = S.EX_TMCAT11,
        T.EX_TMCAT12 = S.EX_TMCAT12,
        T.EX_TMCAT13 = S.EX_TMCAT13,
        T.EX_TMCAT14 = S.EX_TMCAT14,
        T.EX_TMCAT15 = S.EX_TMCAT15,
        T.EX_TMCAT16 = S.EX_TMCAT16,
        T.EX_TMCAT17 = S.EX_TMCAT17,
        T.EX_