
/******************************************************************  
* PROCEDURE : dbo.[UPSERT_CONOPS_CRUSHER_STATUS_2]
* PURPOSE	: Upsert [UPSERT_CONOPS_CRUSHER_STATUS_2]
* NOTES     : 
* CREATED	: ggosal1
* SAMPLE    : EXEC dbo.[UPSERT_CONOPS_CRUSHER_STATUS_2] 
* MODIFIED DATE		AUTHOR				DESCRIPTION  
*------------------------------------------------------------------  
* {23 SEP 2024}		{ggosal1}			{Initial Created}  
*******************************************************************/  
CREATE PROCEDURE [dbo].[UPSERT_CONOPS_CRUSHER_STATUS_2]
AS
BEGIN

MERGE dbo.CRUSHER_STATUS_2 AS T
USING (
    SELECT 
        [SITE_CODE], [HIERARCHY_ID], [DOWNTIME_ID], [PLANT_AREA_NAME], [CALENDAR_DATE],
        [PRODCTN_DATE], [SHIFT_INDICATOR], [START_TS], [START_DATE], [START_TIME],
        [STOP_TS], [STOP_DATE], [STOP_TIME], [DOWNTIME_DURATION], [ACT_MINS],
        [EFF_MINS], [FAILURE_CODE_ID], [ORIG_CODE], [EQUIP_NO_ID], [DOWNTIME_TYPE],
        [DOWNTIME_CAT], [PROBLEM_ID], [CAUSE_NAME], [EQMT], [EQUIP_DESC],
        [SAP_ID], [EQUIP_FUNC_LOC], [DOWNTIME_EVENT_PARENT_INDICATO],
        [FURTHER_WORK_ORDER_CODE], [GENRT_WORK_ORDER_CODE], [WORK_ORDER_NO],
        [WORK_ORDER_STATUS], [WORK_ORDER_COMMENT], [EQUIP_ALARM], [ALARM_SELECT_FLAG],
        [EVENT_CLOSE_STATUS_FLAG], [WORK_ORDER_APPROVED_INDICATOR], [PRODCTN_COST],
        [EDIT_FLAG], [UPDATED_BY], [DOWNTIME_AUDIT_ID], [DOWNTIME_AUDIT_TYPE],
        [CREATED_BY], [WORK_ORDER_ORIG], [AUTO_SPLIT_ROOT], [DW_LOAD_TS],
        [UTC_CREATED_DATE]
    FROM dbo.CRUSHER_STATUS_STG_2
) AS S
ON (
    T.[SITE_CODE] = S.[SITE_CODE] AND
    T.[PLANT_AREA_NAME] = S.[PLANT_AREA_NAME] AND
    T.[START_TS] = S.[START_TS] AND
    T.[STOP_TS] = S.[STOP_TS]
)
WHEN MATCHED THEN
    UPDATE SET
        T.[HIERARCHY_ID] = S.[HIERARCHY_ID],
        T.[DOWNTIME_ID] = S.[DOWNTIME_ID],
        T.[CALENDAR_DATE] = S.[CALENDAR_DATE],
        T.[PRODCTN_DATE] = S.[PRODCTN_DATE],
        T.[SHIFT_INDICATOR] = S.[SHIFT_INDICATOR],
        T.[START_DATE] = S.[START_DATE],
        T.[START_TIME] = S.[START_TIME],
        T.[STOP_DATE] = S.[STOP_DATE],
        T.[STOP_TIME] = S.[STOP_TIME],
        T.[DOWNTIME_DURATION] = S.[DOWNTIME_DURATION],
        T.[ACT_MINS] = S.[ACT_MINS],
        T.[EFF_MINS] = S.[EFF_MINS],
        T.[FAILURE_CODE_ID] = S.[FAILURE_CODE_ID],
        T.[ORIG_CODE] = S.[ORIG_CODE],
        T.[EQUIP_NO_ID] = S.[EQUIP_NO_ID],
        T.[DOWNTIME_TYPE] = S.[DOWNTIME_TYPE],
        T.[DOWNTIME_CAT] = S.[DOWNTIME_CAT],
        T.[PROBLEM_ID] = S.[PROBLEM_ID],
        T.[CAUSE_NAME] = S.[CAUSE_NAME],
        T.[EQMT] = S.[EQMT],
        T.[EQUIP_DESC] = S.[EQUIP_DESC],
        T.[SAP_ID] = S.[SAP_ID],
        T.[EQUIP_FUNC_LOC] = S.[EQUIP_FUNC_LOC],
        T.[DOWNTIME_EVENT_PARENT_INDICATO] = S.[DOWNTIME_EVENT_PARENT_INDICATO],
        T.[FURTHER_WORK_ORDER_CODE] = S.[FURTHER_WORK_ORDER_CODE],
        T.[GENRT_WORK_ORDER_CODE] = S.[GENRT_WORK_ORDER_CODE],
        T.[WORK_ORDER_NO] = S.[WORK_ORDER_NO],
        T.[WORK_ORDER_STATUS] = S.[WORK_ORDER_STATUS],
        T.[WORK_ORDER_COMMENT] = S.[WORK_ORDER_COMMENT],
        T.[EQUIP_ALARM] = S.[EQUIP_ALARM],
        T.[ALARM_SELECT_FLAG] = S.[ALARM_SELECT_FLAG],
        T.[EVENT_CLOSE_STATUS_FLAG] = S.[EVENT_CLOSE_STATUS_FLAG],
        T.[WORK_ORDER_APPROVED_INDICATOR] = S.[WORK_ORDER_APPROVED_INDICATOR],
        T.[PRODCTN_COST] = S.[PRODCTN_COST],
        T.[EDIT_FLAG] = S.[EDIT_FLAG],
        T.[UPDATED_BY] = S.[UPDATED_BY],
        T.[DOWNTIME_AUDIT_ID] = S.[DOWNTIME_AUDIT_ID],
        T.[DOWNTIME_AUDIT_TYPE] = S.[DOWNTIME_AUDIT_TYPE],
        T.[CREATED_BY] = S.[CREATED_BY],
        T.[WORK_ORDER_ORIG] = S.[WORK_ORDER_ORIG],
        T.[AUTO_SPLIT_ROOT] = S.[AUTO_SPLIT_ROOT],
        T.[DW_LOAD_TS] = S.[DW_LOAD_TS],
        T.[UTC_CREATED_DATE] = S.[UTC_CREATED_DATE]
WHEN NOT MATCHED THEN
    INSERT (
        [SITE_CODE], [HIERARCHY_ID], [DOWNTIME_ID], [PLAN