CREATE VIEW [SIE].[CONOPS_SIE_SHIFT_BASE_TARGET_V] AS

--select * from [SIE].[CONOPS_SIE_SHIFT_BASE_TARGET_V] 
CREATE VIEW [sie].[CONOPS_SIE_SHIFT_BASE_TARGET_V]
AS

SELECT
	SITEFLAG,
	CASE WHEN CONVERT(CHAR(5), shiftid, 108) = '06:15' 
		THEN CONCAT(RIGHT(REPLACE(CAST(shiftid AS DATE),'-',''),6),'001')
		ELSE CONCAT(RIGHT(REPLACE(CAST(shiftid AS DATE),'-',''),6),'002')
		END AS shiftid,
	SUM(Mass_Tons) AS TonsMinedTarget,
	0 AS TonsMovedTarget
FROM [SIE].PLAN_VALUES WITH(NOLOCK)
GROUP BY SITEFLAG, SHIFTID

