CREATE VIEW [SIE].[CONOPS_SIE_AUTONOMOUS_TRUCK_V] AS



--select * from [SIE].[CONOPS_SIE_AUTONOMOUS_TRUCK_V]
CREATE VIEW [SIE].[CONOPS_SIE_AUTONOMOUS_TRUCK_V]
AS

SELECT DISTINCT
	FieldId AS TruckId,
	0 AS Autonomous
FROM SIE.pit_truck_c WITH(NOLOCK)
WHERE FieldId IS NOT NULL
	AND FieldId <> ''


