CREATE VIEW [SIE].[CONOPS_SIE_CRUSHER_STATUS_V] AS



--SELECT * FROM [SIE].[CONOPS_SIE_CRUSHER_STATUS_V] WITH (NOLOCK) WHERE SHIFTFLAG = 'CURR'  
CREATE VIEW [SIE].[CONOPS_SIE_CRUSHER_STATUS_V]  
AS  

SELECT
	x.SITE_CODE AS siteflag,
	s.shiftflag,
	x.SHIFTINDEX,
	CASE WHEN x.DUMPNAME IN ('CR13909O', 'A-SIDE', 'B-SIDE') THEN 'CRUSHER'
		ELSE x.DUMPNAME END AS Crusher,
	s.StatusName AS Status,
	s.ReasonDesc AS reasons,
	x.ShovelId,
	x.TIMEDUMP_TS AS StartTime
FROM(
	SELECT
		SITE_CODE,
		SHIFTINDEX,
		EXCAV AS ShovelId,
		DUMPNAME,
		TIMEDUMP_TS,
		ROW_NUMBER() OVER (PARTITION BY SITE_CODE, SHIFTINDEX ORDER BY TIMEDUMP_TS DESC) num
	FROM dbo.delta_c WITH (NOLOCK)
	WHERE SITE_CODE = 'SIE'
		AND DUMPNAME IN ('CR13909O', 'A-SIDE', 'B-SIDE')
) x
LEFT JOIN SIE.CONOPS_SIE_SHOVEL_INFO_V s
	ON x.shiftindex = s.shiftindex
	AND x.ShovelId = s.ShovelID
WHERE x.num = 1
AND s.shiftflag IS NOT NULL

