/*****************************************************************************************
* TABLE     : DRILL_BLAST__BLAST_PLAN_EXECUTION_INCR
* DATABASE  : SNOWFLAKE_WG
* SCHEMA    : dbo
* SOURCE    : Snowflake DEV_API_REF.FUSE.BLAST_PLAN_EXECUTION_INCR
* DATE      : 2026-01-28 | AUTHOR: CARLOS CARRILLO
******************************************************************************************/
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DRILL_BLAST__BLAST_PLAN_EXECUTION_INCR]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DRILL_BLAST__BLAST_PLAN_EXECUTION_INCR] (
    ORIG_SRC_ID BIGINT NOT NULL,
    SITE_CODE NVARCHAR(50) NOT NULL,
    BENCH FLOAT NOT NULL,
    PUSHBACK NVARCHAR(50) NOT NULL,
    PATTERN_NAME NVARCHAR(400) NOT NULL,
    BLAST_NAME NVARCHAR(MAX) NOT NULL,
    DRILLED_HOLE_ID BIGINT NOT NULL,
    DRILLED_HOLE_NAME NVARCHAR(500),
    DRILL_CYCLE_SK BIGINT,
    BLAST_PLAN_SK BIGINT,
    SHIFT_ID NVARCHAR(500),
    BLAST_ID BIGINT,
    SHOT_DATE_UTC NVARCHAR(50),
    SHOT_DATE_LOCAL NVARCHAR(50),
    BLAST_TYPE NVARCHAR(400),
    BLAST_ENGINEER_NAME NVARCHAR(500),
    LOADING_TRUCK_OPERATOR_NAME NVARCHAR(200),
    HOLE_LOADED_TS_UTC NVARCHAR(50),
    HOLE_LOADED_TS_LOCAL NVARCHAR(50),
    HOLE_LAST_KNOWN_DEPTH_METERS DECIMAL(38,5),
    HOLE_LAST_KNOWN_DEPTH_FEET DECIMAL(38,5),
    HOLE_TAPED_DEPTH_METERS DECIMAL(38,5),
    HOLE_TAPED_DEPTH_FEET DECIMAL(38,5),
    HOLE_PLUGGED_FLAG BIT,
    EXPLOSIVE_PRODUCT_BOTTOM BIGINT,
    EXPLOSIVE_PRODUCT_TOP BIGINT,
    EXPLOSIVE_PRODUCT_USED_BOTTOM_KILOGRAMS DECIMAL(38,5),
    EXPLOSIVE_PRODUCT_USED_BOTTOM_POUNDS DECIMAL(38,5),
    EXPLOSIVE_PRODUCT_USED_TOP_KILOGRAMS DECIMAL(38,5),
    EXPLOSIVE_PRODUCT_USED_TOP_POUNDS DECIMAL(38,5),
    EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_METERS DECIMAL(38,5),
    EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_FEET DECIMAL(38,5),
    EXPLOSIVE_PRODUCT_LENGTH_TOP_METERS DECIMAL(38,5),
    EXPLOSIVE_PRODUCT_LENGTH_TOP_FEET DECIMAL(38,5),
    STEMMING_LENGTH_TOTAL_METERS DECIMAL(38,5),
    STEMMING_LENGTH_TOTAL_FEET DECIMAL(38,5),
    STEMMING_LENGTH_BOTTOM_METERS DECIMAL(38,5),
    STEMMING_LENGTH_BOTTOM_FEET DECIMAL(38,5),
    STEMMING_LENGTH_TOP_METERS DECIMAL(38,5),
    STEMMING_LENGTH_TOP_FEET DECIMAL(38,5),
    BURDEN_METERS DECIMAL(38,5),
    BURDEN_FEET DECIMAL(38,5),
    SPACING_METERS DECIMAL(38,5),
    SPACING_FEET DECIMAL(38,5),
    TONS_PER_HOLE DECIMAL(38,5),
    KCALS_PER_TON DECIMAL(38,5),
    POWDER_FACTOR DECIMAL(38,5),
    MEGAJOULES_PER_TON DECIMAL(38,5),
    CONFINEMENT_FACTOR DECIMAL(38,5),
    PRIMER_COUNT BIGINT,
    HOLE_TEMPERATURE_CELSIUS DECIMAL(38,5),
    HOLE_TEMPERATURE_FAHRENHEIT DECIMAL(38,5),
    PRODUCT_BOTTOM_COMMENTS NVARCHAR(MAX),
    PRODUCT_TOP_COMMENTS NVARCHAR(MAX),
    STEMMING_BOTTOM_COMMENT NVARCHAR(MAX),
    STEMMING_TOP_COMMENT NVARCHAR(MAX),
    WATER_DEPTH_METERS DECIMAL(38,5),
    WATER_DEPTH_FEET DECIMAL(38,5),
    MISFIRE_FLAG BIT,
    DW_LOAD_TS DATETIME2,
    DW_MODIFY_TS DATETIME2,
    DW_LOGICAL_DELETE_FLAG NVARCHAR(1) DEFAULT 'N',
    DW_ROW_HASH NVARCHAR(64)
    -- Composite PK: ORIG_SRC_ID, SITE_CODE, BENCH, PUSHBACK, PATTERN_NAME, BLAST_NAME, DRILLED_HOLE_ID
    -- Note: Cannot include NVARCHAR(MAX) in PK, using ORIG_SRC_ID + DRILLED_HOLE_ID
);
END
GO

-- Create index for archival queries
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_DRILL_BLAST__BLAST_PLAN_EXECUTION_INCR_DW_MODIFY_TS')
CREATE INDEX IX_DRILL_BLAST__BLAST_PLAN_EXECUTION_INCR_DW_MODIFY_TS ON [dbo].[DRILL_BLAST__BLAST_PLAN_EXECUTION_INCR](DW_MODIFY_TS);
GO
