/*****************************************************************************************
* TABLE     : LOAD_HAUL__LH_BUCKET_INCR
* DATABASE  : SNOWFLAKE_WG
* SCHEMA    : dbo
* SOURCE    : Snowflake DEV_API_REF.FUSE.LH_BUCKET_INCR
* DATE      : 2026-01-28 | AUTHOR: CARLOS CARRILLO
* NOTES     : Uses TRIP_TS_LOCAL for archival (not DW_MODIFY_TS)
******************************************************************************************/
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LOAD_HAUL__LH_BUCKET_INCR]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[LOAD_HAUL__LH_BUCKET_INCR] (
    BUCKET_ID BIGINT NOT NULL,
    SITE_CODE NVARCHAR(4),
    LOADING_CYCLE_ID BIGINT,
    LH_EQUIP_ID DECIMAL(38,5),
    ORIG_SRC_ID BIGINT,
    BUCKET_OF_CYCLE BIGINT,
    SWING_EMPTY_START_TS_UTC DATETIME2(3),
    SWING_EMPTY_START_TS_LOCAL DATETIME2(3),
    SWING_EMPTY_END_TS_UTC DATETIME2(3),
    SWING_EMPTY_END_TS_LOCAL DATETIME2(3),
    DIG_START_TS_UTC DATETIME2(3),
    DIG_START_TS_LOCAL DATETIME2(3),
    DIG_END_TS_UTC DATETIME2(3),
    DIG_END_TS_LOCAL DATETIME2(3),
    SWING_FULL_START_TS_UTC DATETIME2(3),
    SWING_FULL_START_TS_LOCAL DATETIME2(3),
    SWING_FULL_END_TS_UTC DATETIME2(3),
    SWING_FULL_END_TS_LOCAL DATETIME2(3),
    TRIP_TS_UTC DATETIME2(3),
    TRIP_TS_LOCAL DATETIME2(3),  -- Used for archival
    DIG_X FLOAT,
    DIG_Y FLOAT,
    DIG_Z FLOAT,
    TRIP_X FLOAT,
    TRIP_Y FLOAT,
    TRIP_Z FLOAT,
    SWING_ANGLE_DEGREES FLOAT,
    BLOCK_CENTROID_X FLOAT,
    BLOCK_CENTROID_Y FLOAT,
    BLOCK_CENTROID_Z FLOAT,
    MEASURED_SHORT_TONS DECIMAL(38,6),
    MEASURED_METRIC_TONS DECIMAL(38,6),
    SWING_EMPTY_DURATION_MINS DECIMAL(38,6),
    DIG_DURATION_MINS DECIMAL(38,6),
    SWING_FULL_DURATION_MINS DECIMAL(38,6),
    SYSTEM_VERSION NVARCHAR(50),
    DW_LOGICAL_DELETE_FLAG NVARCHAR(1) DEFAULT 'N',
    DW_LOAD_TS DATETIME2,
    DW_MODIFY_TS DATETIME2,
    CONSTRAINT PK_LOAD_HAUL__LH_BUCKET_INCR PRIMARY KEY (BUCKET_ID)
);
END
GO

-- Create index for archival queries (uses TRIP_TS_LOCAL)
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_LOAD_HAUL__LH_BUCKET_INCR_TRIP_TS_LOCAL')
CREATE INDEX IX_LOAD_HAUL__LH_BUCKET_INCR_TRIP_TS_LOCAL ON [dbo].[LOAD_HAUL__LH_BUCKET_INCR](TRIP_TS_LOCAL);
GO
