
/******************************************************************  
* PROCEDURE : dbo.[UPSERT_CONOPS_MMT_TRUCKLOAD_C_2]
* PURPOSE : Upsert [UPSERT_CONOPS_MMT_TRUCKLOAD_C_2]
* NOTES : 
* CREATED : mfahmi
* SAMPLE: EXEC dbo.[UPSERT_CONOPS_MMT_TRUCKLOAD_C_2] 
* MODIFIED DATE  AUTHORDESCRIPTION  
*------------------------------------------------------------------  
* {05 JUN 2023}  {mfahmi}		{Initial Created}  
* {31 OCT 2023}  {ggosal1}		{Add new column OXIDE_SULFIDE_RATIO, FE_PCT, PB_PCT} 
*******************************************************************/  
CREATE  PROCEDURE [dbo].[UPSERT_CONOPS_MMT_TRUCKLOAD_C_2]
AS
BEGIN

MERGE dbo.MMT_TRUCKLOAD_C_2 AS T
USING (
    SELECT 
        LOAD_SHIFTINDEX, SITE_CODE, LOAD_DDBKEY, LOAD_EXCAV, LOAD_TRUCK, LOAD_LOC, DUMP_LOC,
        TCU_PCT, TMO_PCT, TCLAY_PCT, XCU_PCT, KAOLINITE_PCT, ASCU_PCT, SWELLING_CLAY_PCT,
        SDR_P80, DUMPTONS, OXIDE_SULFIDE_RATIO, FE_PCT, PB_PCT, TIMELOAD_TS, TIMEDUMP_TS,
        UTC_CREATED_DATE
    FROM dbo.MMT_TRUCKLOAD_C_STG_2
) AS S
ON (
    T.SITE_CODE = S.SITE_CODE AND
    T.LOAD_SHIFTINDEX = S.LOAD_SHIFTINDEX AND
    T.LOAD_DDBKEY = S.LOAD_DDBKEY
)
WHEN MATCHED THEN
    UPDATE SET
        T.LOAD_EXCAV = S.LOAD_EXCAV,
        T.LOAD_TRUCK = S.LOAD_TRUCK,
        T.LOAD_LOC = S.LOAD_LOC,
        T.DUMP_LOC = S.DUMP_LOC,
        T.TCU_PCT = S.TCU_PCT,
        T.TMO_PCT = S.TMO_PCT,
        T.TCLAY_PCT = S.TCLAY_PCT,
        T.XCU_PCT = S.XCU_PCT,
        T.KAOLINITE_PCT = S.KAOLINITE_PCT,
        T.ASCU_PCT = S.ASCU_PCT,
        T.SWELLING_CLAY_PCT = S.SWELLING_CLAY_PCT,
        T.SDR_P80 = S.SDR_P80,
        T.DUMPTONS = S.DUMPTONS,
        T.OXIDE_SULFIDE_RATIO = S.OXIDE_SULFIDE_RATIO,
        T.FE_PCT = S.FE_PCT,
        T.PB_PCT = S.PB_PCT,
        T.TIMELOAD_TS = S.TIMELOAD_TS,
        T.TIMEDUMP_TS = S.TIMEDUMP_TS,
        T.UTC_CREATED_DATE = S.UTC_CREATED_DATE
WHEN NOT MATCHED THEN
    INSERT (
        LOAD_SHIFTINDEX, SITE_CODE, LOAD_DDBKEY, LOAD_EXCAV, LOAD_TRUCK, LOAD_LOC, DUMP_LOC,
        TCU_PCT, TMO_PCT, TCLAY_PCT, XCU_PCT, KAOLINITE_PCT, ASCU_PCT, SWELLING_CLAY_PCT,
        SDR_P80, DUMPTONS, OXIDE_SULFIDE_RATIO, FE_PCT, PB_PCT, TIMELOAD_TS, TIMEDUMP_TS,
        UTC_CREATED_DATE
    )
    VALUES (
        S.LOAD_SHIFTINDEX, S.SITE_CODE, S.LOAD_DDBKEY, S.LOAD_EXCAV, S.LOAD_TRUCK, S.LOAD_LOC, S.DUMP_LOC,
        S.TCU_PCT, S.TMO_PCT, S.TCLAY_PCT, S.XCU_PCT, S.KAOLINITE_PCT, S.ASCU_PCT, S.SWELLING_CLAY_PCT,
        S.SDR_P80, S.DUMPTONS, S.OXIDE_SULFIDE_RATIO, S.FE_PCT, S.PB_PCT, S.TIMELOAD_TS, S.TIMEDUMP_TS,
        S.UTC_CREATED_DATE
    )
WHEN NOT MATCHED BY SOURCE THEN
    DELETE;

--Update Job Control
UPDATE [dbo].[DI_JOB_CONTROL_ENTRY_TS_BASE]
SET dw_load_ts = GETUTCDATE()
WHERE job_name = 'job_conops_mmt_truckload_c_2';

END


