CREATE VIEW [ABR].[CONOPS_ABR_CM_INTERMEDIATE_STOCKPILE_V] AS



  
  
--SELECT * FROM [abr].[CONOPS_ABR_CM_INTERMEDIATE_STOCKPILE_V] WITH (NOLOCK) WHERE SHIFTFLAG = 'CURR'    
CREATE VIEW [ABR].[CONOPS_ABR_CM_INTERMEDIATE_STOCKPILE_V]    
AS    


WITH CTE AS (
SELECT 
shiftindex,
CRUSHERLOC,
COMPONENT,
SENSORVALUE,
ROW_NUMBER() OVER (PARTITION BY SHIFTINDEX, CRUSHERLOC,COMPONENT ORDER BY VALUE_TS DESC) NUM  
FROM [dbo].[IOS_STOCKPILE_LEVELS] WITH (NOLOCK)
WHERE SITEFLAG = 'ELA')


SELECT 
a.[SITEFLAG]  
,a.[SHIFTFLAG]  
,s.SENSORVALUE [MFLStockpile]  
FROM [abr].[CONOPS_ABR_SHIFT_INFO_V] a WITH (NOLOCK)  
LEFT JOIN CTE [s] WITH (NOLOCK)   
ON a.SHIFTINDEX = [s].SHIFTINDEX 
AND s.CRUSHERLOC = 'C.1' AND s.COMPONENT = 'CrusherStockpile'  
AND s.NUM = 1
  

