CREATE VIEW [ABR].[EQUIPMENT_HOURLY_STATUS] AS

--SELECT * FROM ABR.EQUIPMENT_HOURLY_STATUS
CREATE VIEW ABR.EQUIPMENT_HOURLY_STATUS
AS

SELECT *
FROM ABR.EQUIPMENT_HOURLY_STATUS_2 WITH(NOLOCK)

