CREATE VIEW [ABR].[PIT_AUXEQMT] AS



--SELECT * FROM ABR.PIT_AUXEQMT
CREATE VIEW ABR.PIT_AUXEQMT
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM SCMAOperational.dbo.PITAuxeqmt



