CREATE VIEW [ABR].[PIT_LOC] AS



--SELECT * FROM ABR.PIT_LOC
CREATE VIEW ABR.PIT_LOC
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM SCMAOperational.dbo.PITPitLoc WITH(NOLOCK)



