CREATE VIEW [ABR].[PIT_WORKER] AS



--SELECT * FROM ABR.PIT_WORKER
CREATE VIEW ABR.PIT_WORKER
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM SCMAOperational.dbo.PITWorker



