CREATE VIEW [ABR].[SHIFT_LOC] AS



--SELECT * FROM ABR.SHIFT_LOC
CREATE VIEW ABR.SHIFT_LOC
AS

SELECT
'ABR' AS SiteFlag,
*
FROM SCMAOperational.dbo.SHIFTShiftloc WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM ABR.SHIFT_INFO)



