CREATE VIEW [ABR].[SHIFT_LOAD] AS



--SELECT * FROM ABR.SHIFT_LOAD
CREATE VIEW ABR.SHIFT_LOAD
AS

SELECT
'ABR' AS SiteFlag,
*
FROM SCMAOperational.dbo.SHIFTShiftload WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM ABR.SHIFT_INFO)



