CREATE VIEW [TYR].[CONOPS_TYR_ALERT_V] AS





-- SELECT * FROM [tyr].[CONOPS_TYR_ALERT_V] WITH (NOLOCK) WHERE shiftflag = 'CURR'
CREATE VIEW [TYR].[CONOPS_TYR_ALERT_V]
AS

	SELECT si.SHIFTFLAG
		  ,si.[SITEFLAG]
		  ,[EQMT_TYPE]
		  ,[EQMTID]
		  ,[OPERATOR_ID]
		  ,[ALERT_TYPE]
		  ,[ALERT_NAME]
		  ,[ALERT_DESCRIPTION]
		  ,[ALERT_DATE]
		  ,[DURATION]
		  ,[ALERT_GENERATED_DATETIME]
		  ,[UTC_CREATED_DATE]
	FROM [tyr].[CONOPS_TYR_SHIFT_INFO_V] si (NOLOCK)
	LEFT JOIN [tyr].[ALERT] a (NOLOCK)
	ON a.SHIFTINDEX = si.SHIFTINDEX
	   AND a.SITEFLAG = si.SITEFLAG


