CREATE VIEW [TYR].[PIT_LOC] AS



--SELECT * FROM TYR.PIT_LOC
CREATE VIEW TYR.PIT_LOC
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM TYROperational.dbo.PITPitLoc WITH(NOLOCK)



