CREATE VIEW [TYR].[SHIFT_LOAD] AS



--SELECT * FROM TYR.SHIFT_LOAD
CREATE VIEW TYR.SHIFT_LOAD
AS

SELECT
'TYR' AS SiteFlag,
*
FROM TYROperational.dbo.SHIFTShiftload WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM TYR.SHIFT_INFO)



