CREATE VIEW [TYR].[SHIFT_OPER] AS




--SELECT * FROM TYR.SHIFT_OPER
CREATE VIEW TYR.SHIFT_OPER
AS

SELECT
'TYR' AS SiteFlag,
*
FROM TYROperational.dbo.SHIFTShiftOper WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM TYR.SHIFT_INFO)




