



 
/******************************************************************    
* PROCEDURE : [CER].[UPSERT_CONOPS_PLAN_VALUES]   
* PURPOSE : Upsert [UPSERT_CONOPS_PLAN_VALUES]  
* NOTES     :   
* CREATED : mfahmi  
* SAMPLE    : EXEC CER.[UPSERT_CONOPS_PLAN_VALUES]  
* MODIFIED DATE  AUTHOR    DESCRIPTION    
*------------------------------------------------------------------    
* {01 DEC 2022}  {mfahmi}   {Initial Created}    
* {01 MAR 2023}  {MFAHMI}   {ADD COLUMN SITEFLAG} 
* {28 MAR 2023}  {MFAHMI}   {ADD LOGIC TO HANDLE INCORRECT TITLE} 
* {05 DEC 2023}  {GGOSAL1}  {Add: update table monitoring}
*******************************************************************/    
CREATE  PROCEDURE [cer].[UPSERT_CONOPS_PLAN_VALUES]  
AS  
BEGIN  
  
MERGE CER.PLAN_VALUES AS T   
USING (SELECT 
'CER' AS SITEFLAG, 
CONTENTTYPEID,
TITLE,
COMPLIANCEASSETID,
TOTALC1,
PITTOC21,
PITTOC22,
TOTALC2,
TOTALROM,
TOTALWASTEDELIVERED,
TOTALMATERIALMOVED,
TOTALMATERIALMINED,
CV4,
CV5,
SR4,
SR5,
CVSM,
INPIT,
LOADTONSREADYHOURELECTRICSHOVEL,
LOADTONSREADYHOURHYDRAULICSHOVEL,
AVAILABILITYHYDRAULICSHOVEL,
AVAILABILITYELECTRICSHOVEL,
ASSETEFFICIENCYELECTRICSHOVEL,
ASSETEFFICIENCYHYDRAULICSHOVEL,
USEOFAVAILABILITYELECTRICSHOVEL,
USEOFAVAILABILITYHYDRAULICSHOVEL,
DUMPTONSREADYHOURKOM930,
DUMPTONSREADYHOURCAT793,
AVAILABILITYKOM930,
AVAILABILITYCAT793,
ASSETEFFICIENCYKOM930,
ASSETEFFICIENCYCAT793,
USEOFAVAILABILITYKOM930,
USEOFAVAILABILITYCAT793,
AVGNUMBERREADYKOM930,
AVGNUMBERREADYCAT793,
EQREADYCAT793,
EQUIVFLATHAULHAULPROF,
LOADEDTRAVELTIMETIMES,
EMPTYTRAVELTIMETIMES,
LOADINGTIMETIMES,
SPOTTINGTIMETIMES,
DUMPINGTIMETIMES,
IDLEATEXCAVATORTIMES,
DUMPINGATCRUSHERTIMES,
DUMPINGATSTOCKPILETIMES,
LOADTONSREADYHOURLOADER,
AVAILABILITYLOADER,
ASSETEFFICIENCYLOADER,
USEOFAVAILABILITYLOADER,
USEOFAVAILABILITYTOTALLOADING,
ASSETEFFICIENCYTOTALLOADING,
AVAILABILITYTOTALLOADING,
LOADTONSREADYHOURTOTALLOADING,
DUMPTONSREADYHOURTOTALTRUCK,
AVAILABILITYTOTALTRUCK,
ASSETEFFICIENCYTOTALTRUCK,
TOTALCL,
TOTALCYCLEDELTA,
USEOFAVAILABILITYTOTALTRUCK,
PLACEDPOUNDSC1,
PLACEDPOUNDSC2,
PLACEDPOUNDSCL,
BLASTHOLESDAY,
DRILLEDDAYM,
PVDISPPRCTG,
PVUTILPRCTG,
PVASSETEFFPRCTG,
RL8DISPPRCTG,
RL8UTILPRCTG,
RL8ASSETEFFECTPRCTG,
SR6,
CN01,
DCVIAJEVACIO,
DCCOLAENPALAS,
DCCUADRE,
DCCARGUIO,
DCVIAJECARGADO,
DCDESCARGACHANCADO,
DCDESCARGABOTADERO,
CV6,
SR7,
SPBL,
SHOVEL06,
SHOVEL07,
SHOVEL09,
SHOVEL10,
SHOVEL11,
SHOVEL12,
SHOVEL14,
SHOVEL15,
SHOVEL16,
SHOVEL17,
SHOVEL18,
SHOVEL19,
SHOVEL20,
SHOVEL21,
EXPIT,
TOTALMILLCRUSH1,
TOTALMILLCRUSH2,
TOTALMILLCHAN,
TOTALHIDROCHAN,
PVREADINESS,
RL8READINESS,
SHIFTCHANGEMIN,
LUNCHDAYMIN,
LUNCHNIGHTMIN,
FUELMIN,
TOTALWASTEFILL,
SR8,
CV07,
PROY,
DUMPTONSREADYHOURKOM980,
AVAILABILITYKOM980,
ASSETEFFICIENCYKOM980,
USEOFAVAILABILITYKOM980,
AVGNUMBERREADYKOM980,
DUMPTONSREADYHOURCAT798,
AVAILABILITYCAT798,
ASSETEFFICIENCYCAT798,
USEOFAVAILABILITYCAT798,
AVGNUMBERREADYCAT798,
SR9,
CV8,
ID,
CONTENTTYPE,
MODIFIED,
CREATED,
CREATEDBYID,
MODIFIEDBYID,
OWSHIDDENVERSION,
VERSION,
PATH,
getutcdate() UTC_CREATED_DATE   
 FROM CER.PLAN_VALUES_STG
 where (title like 'Jan%' or
title like 'Feb%' or
title like 'Mar%' or
title like 'Apr%' or
title like 'May%' or
title like 'Jun%' or
title like 'Jul%' or
title like 'Aug%' or
title like 'Sep%' or
title like 'Oct%' or
title like 'Nov%' or
title like 'Dec%')) AS S   
 ON (T.Id = S.Id AND T.SITEFLAG = S.SITEFLAG)   
  
 WHEN MATCHED   
 THEN UPDATE SET  
 T.CONTENTTYPEID = S.CONTENTTYPEID
,T.TITLE = S.TITLE
,T.COMPLIANCEASSETID = S.COMPLIANCEASSETID
,T.TOTALC1 = S.TOTALC1
,T.PITTOC21 = S.PITTOC21
,T.PITTOC22 = S.PITTOC22
,T.TOTALC2 = S.TOTALC2
,T.TOTALROM = S.TOTALROM
,T.TOTALWASTEDELIVERED = S.TOTALWASTEDELIVERED
,T.TOTALMATERIALMOVED = S.TOTALMATERIALMOVED
,T.TOTALMATERIALMINED = S.TOTALMATERIALMINED
,T.CV4 = S.CV4
,T.CV5 = S.CV5
,T.SR4 = S.S