CREATE VIEW [TYR].[EQUIPMENT_HOURLY_STATUS] AS

--SELECT * FROM TYR.EQUIPMENT_HOURLY_STATUS
CREATE VIEW TYR.EQUIPMENT_HOURLY_STATUS
AS

SELECT *
FROM TYR.EQUIPMENT_HOURLY_STATUS_2 WITH(NOLOCK)

