/*****************************************************************************************
* TABLE     : BL_DW_BLAST_INCR
* SCHEMA    : {{ envi }}_API_REF.FUSE
* SOURCE    : {{ RO_PROD }}_WG.DRILL_BLAST.BL_DW_BLAST
* DATE: 2026-01-23 | AUTHOR: CARLOS CARRILLO
******************************************************************************************/
create or replace TABLE {{ envi }}_API_REF.FUSE.BL_DW_BLAST_INCR (
	ORIG_SRC_ID NUMBER(19,0) NOT NULL,
	SITE_CODE VARCHAR(50) NOT NULL COLLATE 'en-ci',
	ID NUMBER(10,0) NOT NULL,
	NAME VARCHAR(1000) COLLATE 'en-ci',
	STATUS VARCHAR(20) COLLATE 'en-ci',
	FIREDTIME TIMESTAMP_NTZ(9),
	ABANDONEDTIME TIMESTAMP_NTZ(9),
	ABANDONEDCOMMENT VARCHAR(5000) COLLATE 'en-ci',
	SUSPENDEDTIME TIMESTAMP_NTZ(9),
	SUSPENDEDCOMMENT VARCHAR(5000) COLLATE 'en-ci',
	VOLUME FLOAT,
	HOLECOUNT NUMBER(10,0),
	SHOTFIRERNAME VARCHAR(500) COLLATE 'en-ci',
	REFRESHEDTIME TIMESTAMP_NTZ(9),
	DELETED BOOLEAN,
	DW_FILE_TS_UTC TIMESTAMP_NTZ(9),
	DW_LOGICAL_DELETE_FLAG VARCHAR(1) COLLATE 'en-ci' DEFAULT 'N',
	DW_LOAD_TS TIMESTAMP_NTZ(0),
	DW_MODIFY_TS TIMESTAMP_NTZ(0)
)COMMENT='Incremental table for BL_DW_BLAST - MERGE-driven upserts with 3-day incremental window'
;
