
/******************************************************************
* PROCEDURE	: DBO.[SNAP_CONOPS_ASSET_EFFICIENCY]
* PURPOSE	: UPSERT [SNAP_CONOPS_ASSET_EFFICIENCY]
* NOTES		: 
* CREATED	: GGOSAL1
* SAMPLE	: EXEC DBO.[SNAP_CONOPS_ASSET_EFFICIENCY] 'SAF'
* MODIFIED DATE		AUTHOR		DESCRIPTION
*------------------------------------------------------------------
* {23 JUN 2025}		{GGOSAL1}	{INITIAL CREATED}
* {10 OCT 2025}		{GGOSAL1}	{ADD BAG 2}
*******************************************************************/

CREATE PROCEDURE [dbo].[SNAP_CONOPS_ASSET_EFFICIENCY]
(
@G_SITE VARCHAR(5)
)
AS
BEGIN

DECLARE @G_SITE_ALIAS VARCHAR(5)
DECLARE @G_SITE_JCONTROL VARCHAR(5)

SET @G_SITE_ALIAS = CASE WHEN @G_SITE = 'CLI' THEN 'CMX'
							WHEN @G_SITE = 'BAG2' THEN 'BAG' ELSE @G_SITE END

SET @G_SITE_JCONTROL = CASE WHEN @G_SITE = 'BAG2' THEN 'BAG' ELSE @G_SITE END


EXEC 
(

' DELETE FROM ' +@G_SITE+ '.ASSET_EFFICIENCY_STG ; '

+' INSERT INTO ' +@G_SITE+ '.ASSET_EFFICIENCY_STG '
+' SELECT '
+' SHIFTID,'
+' EQMT,'
+' FIELDEQMTTYPE,'
+' EQMTTYPE,'
+' UNITTYPE,'
+' STARTDATETIME,'
+' ENDDATETIME,'
+' DURATION,'
+' STATUSIDX,'
+' STATUS,'
+' CATEGORYIDX,'
+' CATEGORY,'
+' REASONIDX,'
+' REASONS,'
+' COMMENTS,'
+' GETUTCDATE() AS UTC_CREATED_DATE FROM ' +@G_SITE+ '.ASSET_EFFICIENCY_V; '

+'MERGE ' +@G_SITE+ '.ASSET_EFFICIENCY AS T '
+' USING (SELECT '
+' ''' +@G_SITE_ALIAS+ ''' AS SITEFLAG,' 
+' SHIFTID,'
+' EQMT,'
+' FIELDEQMTTYPE,'
+' EQMTTYPE,'
+' UNITTYPE,'
+' STARTDATETIME,'
+' ENDDATETIME,'
+' DURATION,'
+' STATUSIDX,'
+' STATUS,'
+' CATEGORYIDX,'
+' CATEGORY,'
+' REASONIDX,'
+' REASONS,'
+' COMMENTS,'
+' UTC_CREATED_DATE'
+' FROM ' +@G_SITE+ '.ASSET_EFFICIENCY_STG) AS S '
+' ON (T.SHIFTID = S.SHIFTID AND T.EQMT = S.EQMT AND T.STARTDATETIME = S.STARTDATETIME AND T.SITEFLAG = S.SITEFLAG) ' 
+' WHEN MATCHED ' 
+' THEN UPDATE SET ' 
+' T.FIELDEQMTTYPE = S.FIELDEQMTTYPE,'
+' T.EQMTTYPE = S.EQMTTYPE,'
+' T.UNITTYPE = S.UNITTYPE,'
+' T.ENDDATETIME = S.ENDDATETIME,'
+' T.DURATION = S.DURATION,'
+' T.STATUSIDX = S.STATUSIDX,'
+' T.STATUS = S.STATUS,'
+' T.CATEGORYIDX = S.CATEGORYIDX,'
+' T.CATEGORY = S.CATEGORY,'
+' T.REASONIDX = S.REASONIDX,'
+' T.REASONS = S.REASONS,'
+' T.COMMENTS = S.COMMENTS,'
+' T.UTC_CREATED_DATE = S.UTC_CREATED_DATE'
+' WHEN NOT MATCHED ' 
+' THEN INSERT ( '
+' SITEFLAG,' 
+' SHIFTID,'
+' EQMT,'
+' FIELDEQMTTYPE,'
+' EQMTTYPE,'
+' UNITTYPE,'
+' STARTDATETIME,'
+' ENDDATETIME,'
+' DURATION,'
+' STATUSIDX,'
+' STATUS,'
+' CATEGORYIDX,'
+' CATEGORY,'
+' REASONIDX,'
+' REASONS,'
+' COMMENTS,'
+' UTC_CREATED_DATE'
+'  ) VALUES( '
+' S.SITEFLAG,' 
+' S.SHIFTID,'
+' S.EQMT,'
+' S.FIELDEQMTTYPE,'
+' S.EQMTTYPE,'
+' S.UNITTYPE,'
+' S.STARTDATETIME,'
+' S.ENDDATETIME,'
+' S.DURATION,'
+' S.STATUSIDX,'
+' S.STATUS,'
+' S.CATEGORYIDX,'
+' S.CATEGORY,'
+' S.REASONIDX,'
+' S.REASONS,'
+' S.COMMENTS,'
+' S.UTC_CREATED_DATE'
+' ); '

+' DELETE FROM ' +@G_SITE+ '.[ASSET_EFFICIENCY] '
+' WHERE NOT EXISTS  '
+' (SELECT 1  '
+' FROM  ' +@G_SITE+ '.[ASSET_EFFICIENCY_STG]  AS STG   '
+' WHERE   '
+' STG.SHIFTID = ' +@G_SITE+ '.[ASSET_EFFICIENCY].SHIFTID AND '
+' STG.EQMT = ' +@G_SITE+ '.[ASSET_EFFICIENCY].EQMT AND '
+' STG.STARTDATETIME = ' +@G_SITE+ '.[ASSET_EFFICIENCY].STARTDATETIME) '

+' UPDATE [dbo].[DI_JOB_CONTROL_ENTRY_TS_BASE] '
+' SET dw_load_ts = GETUTCDATE() '
+' WHERE job_name = ''job_conops_asset_efficiency_' +@G_SITE_JCONTROL+ ''''

);
END
  




