

/******************************************************************  
* PROCEDURE : dbo.[UPSERT_CONOPS_DELTA_C_2]
* PURPOSE	: Upsert [UPSERT_CONOPS_DELTA_C_2]
* NOTES     : 
* CREATED	: mfahmi
* SAMPLE    : EXEC dbo.[UPSERT_CONOPS_DELTA_C_2] 
* MODIFIED DATE		AUTHOR				DESCRIPTION  
*------------------------------------------------------------------  
* {28 NOV 2022}		{mfahmi}			{Initial Created}  
*******************************************************************/  
CREATE  PROCEDURE [dbo].[UPSERT_CONOPS_DELTA_C_2]
AS
BEGIN

DELETE FROM dbo.DELTA_C_2

INSERT INTO dbo.DELTA_C_2(
CLIID
,DDBKEY
,SITE_CODE
,START_DATE_TS
,DELTAC_TS
,END_DATE_TS
,SHIFTINDEX
,SHIFTDATE
,YEAR_CODE
,MONTH_CODE
,MONTHS
,SHIFT
,SHIFT_CODE
,CREW_CODE
,CREW
,HARVHOS
,DIGTYPE
,SHVTYPE
,DIPPER
,TRKTYPE
,PAYLOAD
,IDLETIME
,SPOTTIME
,LOADTIME
,DUMPINGTIME
,CRUSHERIDLE
,TRAVELEMPTY
,TRAVELLOADED
,TOTALCYCLE
,CALCTRAVEMPTY
,CALCTRAVLOADED
,HOS
,TIMEFULL
,TIMELOADED
,EXCAV
,SOPERID
,SOPER
,TRUCK
,TOPERID
,TOPER
,LOAD_CODE
,MATERIAL
,BENCH
,UNIT_CODE
,UNIT
,DUMPNAME
,TRUCK_IDLEDELTA
,SPOTDELTA
,LOADDELTA
,DUMPDELTA
,ET_DELTA
,LT_DELTA
,DELTA_C
,TOAVGDELTAC
,TOSTDEVDELTAC
,TOAVGIDLEDELTA
,TOSTDEVIDLEDELTA
,TOAVGSPOTDELTA
,TOSTDEVSPOTDELTA
,TOAVGLOADDELTA
,TOSTDEVLOADDELTA
,TOAVGETDELTA
,TOSTDEVETDELTA
,TOAVGLTDELTA
,TOSTDEVLTDELTA
,TOAVGDUMPDELTA
,TOSTDEVDUMPDELTA
,VTODELTAC3
,LOAD_SEQ_NO
,GRADE
,EXTRALOAD
,LOADTYPE
,LOADTONS
,MEASURETONS_SHOVEL
,OVER_TRUCK_FLAG
,UNDER_TRUCK_FLAG
,DUMP_FLAG
,SHOVEL_IDLE
,CRUSHER_DUMP_FLAG
,DUMP_NUMBER
,LDUMP_HOS
,DUMP_HOS
,DUMP_OPER_ID
,SHOVEL_EQMTTYPE_CODE
,TRUCK_EQMTTYPE_CODE
,SHVL_OPS_PRTL_EQUIP_GROUP_NO_CODE
,TRK_OPS_PRTL_EQUIP_GROUP_NO_CODE
,SHOVEL_IDLEDELTA
,ELIFTUP
,ELIFTDOWN
,DISTLOADED
,FLIFTUP
,FLIFTDOWN
,DISTEMPTY
,CRUSHERDELTA
,DUMPINGDELTA
,EMPTYHAUL
,LOAD_TIMEARRIVE
,TIMELOAD
,BEGINSPOT
,HANGTIME
,DUMP_TIMEARRIVE
,TIMEDUMP
,TIMEEMPTY
,DUMP_TIMEARRIVE_TS
,TIMEDUMP_TS
,TIMEEMPTY_TS
,IDLEDELTA
,REGION
,UTC_CREATED_DATE)

 SELECT 
 CLIID
,DDBKEY
,SITE_CODE
,START_DATE_TS
,DELTAC_TS
,END_DATE_TS
,SHIFTINDEX
,SHIFTDATE
,YEAR_CODE
,MONTH_CODE
,MONTHS
,SHIFT
,SHIFT_CODE
,CREW_CODE
,CREW
,HARVHOS
,DIGTYPE
,SHVTYPE
,DIPPER
,TRKTYPE
,PAYLOAD
,IDLETIME
,SPOTTIME
,LOADTIME
,DUMPINGTIME
,CRUSHERIDLE
,TRAVELEMPTY
,TRAVELLOADED
,TOTALCYCLE
,CALCTRAVEMPTY
,CALCTRAVLOADED
,HOS
,TIMEFULL
,TIMELOADED
,EXCAV
,SOPERID
,SOPER
,TRUCK
,TOPERID
,TOPER
,LOAD_CODE
,MATERIAL
,BENCH
,UNIT_CODE
,UNIT
,DUMPNAME
,TRUCK_IDLEDELTA
,SPOTDELTA
,LOADDELTA
,DUMPDELTA
,ET_DELTA
,LT_DELTA
,DELTA_C
,TOAVGDELTAC
,TOSTDEVDELTAC
,TOAVGIDLEDELTA
,TOSTDEVIDLEDELTA
,TOAVGSPOTDELTA
,TOSTDEVSPOTDELTA
,TOAVGLOADDELTA
,TOSTDEVLOADDELTA
,TOAVGETDELTA
,TOSTDEVETDELTA
,TOAVGLTDELTA
,TOSTDEVLTDELTA
,TOAVGDUMPDELTA
,TOSTDEVDUMPDELTA
,VTODELTAC3
,LOAD_SEQ_NO
,GRADE
,EXTRALOAD
,LOADTYPE
,LOADTONS
,MEASURETONS_SHOVEL
,OVER_TRUCK_FLAG
,UNDER_TRUCK_FLAG
,DUMP_FLAG
,SHOVEL_IDLE
,CRUSHER_DUMP_FLAG
,DUMP_NUMBER
,LDUMP_HOS
,DUMP_HOS
,DUMP_OPER_ID
,SHOVEL_EQMTTYPE_CODE
,TRUCK_EQMTTYPE_CODE
,SHVL_OPS_PRTL_EQUIP_GROUP_NO_CODE
,TRK_OPS_PRTL_EQUIP_GROUP_NO_CODE
,SHOVEL_IDLEDELTA
,ELIFTUP
,ELIFTDOWN
,DISTLOADED
,FLIFTUP
,FLIFTDOWN
,DISTEMPTY
,CRUSHERDELTA
,DUMPINGDELTA
,EMPTYHAUL
,LOAD_TIMEARRIVE
,TIMELOAD
,BEGINSPOT
,HANGTIME
,DUMP_TIMEARRIVE
,TIMEDUMP
,TIMEEMPTY
,DUMP_TIMEARRIVE_TS
,TIMEDUMP_TS
,TIMEEMPTY_TS
,IDLEDELTA
,REGION
,UTC_CREATED_DATE
 FROM dbo.DELTA_C_stg_2
 
END



