
/******************************************************************    
* PROCEDURE : dbo.[UPSERT_CONOPS_DRILL_UTILIZATION_2]  
* PURPOSE : Upsert [UPSERT_CONOPS_DRILL_UTILIZATION_2]  
* NOTES     :   
* CREATED : ggosal1 
* SAMPLE    : EXEC dbo.[UPSERT_CONOPS_DRILL_UTILIZATION_2] 'cer'
* MODIFIED DATE  AUTHOR    DESCRIPTION    
*------------------------------------------------------------------    
* {23 FEB 2023}  {ggosal1}   {Initial Created}    
* {07 MAR 2023}  {mfahmi}    {enhance the logic using Merge by PK columns}  
* {31 JUL 2023}  {ggosal1}   {Add filter for BAG, source system <> Modular}  
* {16 JAN 2025}  {ggosal1}   {Add filter for MOR, source system <> Modular / RCS (Waiting final decision)} 
* {25 SEP 2025}  {ggosal1}   {Add Site Code Change for El Abra} 
*******************************************************************/    
CREATE  PROCEDURE [dbo].[UPSERT_CONOPS_DRILL_UTILIZATION_2]  
(  
@G_SITE VARCHAR(5)  
)  
AS  
BEGIN

IF @G_SITE = 'BAG'
BEGIN
	DELETE FROM bag.DRILL_UTILIZATION_STG_2
	WHERE SOURCE_SYSTEM = 'Modular'
END

ELSE IF @G_SITE = 'MOR'
BEGIN
	DELETE FROM mor.DRILL_UTILIZATION_STG_2
	WHERE SOURCE_SYSTEM = 'Modular'
END

ELSE IF @G_SITE = 'ELA'
BEGIN
	SET @G_SITE = 'ABR'
END

EXEC   
(  

'MERGE ' +@G_SITE+ '.DRILL_UTILIZATION_2 AS T'  
+' USING ('
+' SELECT ' 
+' SITE_CODE'
+' ,SHIFTINDEX'
+' ,SHIFT_DATE'
+' ,SHIFTSTART'
+' ,SHIFTEND'
+' ,SHIFT'
+' ,MACHINESTATUSCODE'
+' ,EQUIPMENTNUMBER'
+' ,EQUIPMENTMODEL'
+' ,START_TIME_TS'
+' ,END_TIME_TS'
+' ,SHIFT_TIME'
+' ,HOS'
+' ,STARTTIME'
+' ,ENDTTIME'
+' ,STATUS_DURATION'
+' ,READYTIME'
+' ,OPERATIONALDOWNTIME'
+' ,SCHEDULEDDOWNTIME'
+' ,UNSCHEDULEDDOWNTIME'
+' ,DELAYTIME'
+' ,SPARETIME'
+' ,SHIFTCHANGETIME'
+' ,UNCLASSIFIEDTIME'
+' ,SOURCE_SYSTEM' 
+' ,UTC_CREATED_DATE'
+' FROM ' +@G_SITE+ '.DRILL_UTILIZATION_STG_2 ) AS S   '
+'  ON (T.SITE_CODE = S.SITE_CODE   '
+' AND T.SHIFTINDEX = S.SHIFTINDEX   '
+' AND T.EQUIPMENTNUMBER = S.EQUIPMENTNUMBER   '
+' AND T.START_TIME_TS = S.START_TIME_TS  '
--+' AND T.END_TIME_TS = S.END_TIME_TS   '
--+' AND T.HOS = S.HOS	'
+' AND T.SOURCE_SYSTEM = T.SOURCE_SYSTEM '
+')'   

+' WHEN MATCHED   '
+'  THEN UPDATE SET '
--+' T.SITE_CODE = S.SITE_CODE '
--+' ,T.SHIFTINDEX = S.SHIFTINDEX '
+' T.SHIFT_DATE = S.SHIFT_DATE '
+' ,T.SHIFTSTART = S.SHIFTSTART '
+' ,T.SHIFTEND = S.SHIFTEND '
+' ,T.SHIFT = S.SHIFT '
+' ,T.MACHINESTATUSCODE = S.MACHINESTATUSCODE '
--+' ,T.EQUIPMENTNUMBER = S.EQUIPMENTNUMBER '
+' ,T.EQUIPMENTMODEL = S.EQUIPMENTMODEL '
--+' ,T.START_TIME_TS = S.START_TIME_TS '
+' ,T.END_TIME_TS = S.END_TIME_TS '
+' ,T.SHIFT_TIME = S.SHIFT_TIME '
+' ,T.HOS = S.HOS '
+' ,T.STARTTIME = S.STARTTIME '
+' ,T.ENDTTIME = S.ENDTTIME '
+' ,T.STATUS_DURATION = S.STATUS_DURATION '
+' ,T.READYTIME = S.READYTIME '
+' ,T.OPERATIONALDOWNTIME = S.OPERATIONALDOWNTIME '
+' ,T.SCHEDULEDDOWNTIME = S.SCHEDULEDDOWNTIME '
+' ,T.UNSCHEDULEDDOWNTIME = S.UNSCHEDULEDDOWNTIME '
+' ,T.DELAYTIME = S.DELAYTIME '
+' ,T.SPARETIME = S.SPARETIME '
+' ,T.SHIFTCHANGETIME = S.SHIFTCHANGETIME '
+' ,T.UNCLASSIFIEDTIME = S.UNCLASSIFIEDTIME '
--+' ,T.SOURCE_SYSTEM = S.SOURCE_SYSTEM '
+' ,T.UTC_CREATED_DATE = S.UTC_CREATED_DATE '
+' WHEN NOT MATCHED    '
+'  THEN INSERT (    '
+' SITE_CODE'
+' ,SHIFTINDEX'
+' ,SHIFT_DATE'
+' ,SHIFTSTART'
+' ,SHIFTEND'
+' ,SHIFT'
+' ,MACHINESTATUSCODE'
+' ,EQUIPMENTNUMBER'
+' ,EQUIPMENTMODEL'
+' ,START_TIME_TS'
+' ,END_TIME_TS'
+' ,SHIFT_TIME'
+' ,HOS'
+' ,STARTTIME'
+' ,ENDTTIME'
+' ,STATUS_DURATION'
+' ,READYTIME'
+' ,OPERATIONALDOWNTIME'
+' ,SCHEDULEDDOWNTIME'
+' ,UNSCHEDULEDDOWNTIME'
+' ,DELAYTIME'
+' ,SPARETIME'
+' ,SHIFTCHANGETIME'
+' ,UNCLASSIFIEDTIME'
+' ,SOURCE_SYSTEM' 
+' ,UTC_CREATED_DATE'
+' ) VALUES( '
+' S.SITE_CODE '
+' ,S.SHIFTINDEX '
+' ,S.SHIFT_DATE '
+' ,S.SHIFTSTART '
+' ,S.SHIFTEND '
+' ,S.SHIFT '
+' ,S.MACHINESTATUSCODE '
+' ,S.EQUIPMENTNUMBER '
+' ,S.EQUIPM