


  
/******************************************************************    
* PROCEDURE : DBO.[UPSERT_CONOPS_SHIFT_INFO]  
* PURPOSE : UPSERT [UPSERT_CONOPS_SHIFT_INFO]  
* NOTES     :   
* CREATED : LWASINI  
* SAMPLE    : EXEC DBO.[UPSERT_CONOPS_SHIFT_INFO] 'MOR'  
* MODIFIED DATE  AUTHOR    DESCRIPTION    
*------------------------------------------------------------------    
* {25 OCT 2022}  {LWASINI}   {INITIAL CREATED}    
* {01 MAR 2023}  {MFAHMI}   {ADD COLUMN SITEFLAG}    
*******************************************************************/    
CREATE  PROCEDURE [dbo].[UPSERT_CONOPS_SHIFT_INFO]  
(  
@G_SITE VARCHAR(5)  
)  
AS  
BEGIN
DECLARE @G_SITE_ALIAS VARCHAR(5)

SET @G_SITE_ALIAS = CASE WHEN @G_SITE = 'CLI' THEN 'CMX' ELSE @G_SITE END

EXEC   
(  
'MERGE ' +@G_SITE+ '.SHIFT_INFO AS T '  
+'USING ( SELECT ' 
+' ''' +@G_SITE_ALIAS+ ''' AS SITEFLAG' 
+' ,LAG (SHIFTID) OVER (ORDER BY SHIFTID) AS PREVSHIFTID'  
+' ,SHIFTID'  
+' ,LEAD(SHIFTID) OVER (ORDER BY SHIFTID) AS NEXTSHIFTID'  
+',SHIFTNAME'  
+',DBNAME'  
+',SHIFTYEAR'  
+',SHIFTMONTH'  
+',SHIFTDAY'  
+',SHIFTSUFFIX'  
+',FULLSHIFTSUFFIX'  
+',SHIFTSTARTSECSINCEMIDNIGHT'  
+',SHIFTSTARTTIMESTAMP'  
+',SHIFTSTARTTIMESTAMPUTC'  
+',SHIFTSTARTDATE'  
+',SHIFTSTARTDATETIME'  
+',FULLSHIFTNAME'  
+',HOLIDAY'  
+',CREW'  
+',SHIFTDURATION'  
+',SHIFTDATE'  
+',UTC_CREATED_DATE'  
+',UTC_LOGICAL_DELETED_DATE'  
+' FROM ' +@G_SITE+ '.SHIFT_INFO_STG) AS S '  
 +'ON (T.SHIFTID = S.SHIFTID AND T.SITEFLAG = S.SITEFLAG)'  
+' WHEN MATCHED'  
+' THEN UPDATE SET '   
+' T.PREVSHIFTID = S.PREVSHIFTID'  
+',T.NEXTSHIFTID = S.NEXTSHIFTID'  
+',T.SHIFTNAME = S.SHIFTNAME'  
+',T.DBNAME = S.DBNAME'  
+',T.SHIFTYEAR = S.SHIFTYEAR'  
+',T.SHIFTMONTH = S.SHIFTMONTH'  
+',T.SHIFTDAY = S.SHIFTDAY'  
+',T.SHIFTSUFFIX = S.SHIFTSUFFIX'  
+',T.FULLSHIFTSUFFIX = S.FULLSHIFTSUFFIX'  
+',T.SHIFTSTARTSECSINCEMIDNIGHT = S.SHIFTSTARTSECSINCEMIDNIGHT'  
+',T.SHIFTSTARTTIMESTAMP = S.SHIFTSTARTTIMESTAMP'  
+',T.SHIFTSTARTTIMESTAMPUTC = S.SHIFTSTARTTIMESTAMPUTC'  
+',T.SHIFTSTARTDATE = S.SHIFTSTARTDATE'  
+',T.SHIFTSTARTDATETIME = S.SHIFTSTARTDATETIME'  
+',T.FULLSHIFTNAME = S.FULLSHIFTNAME'  
+',T.HOLIDAY = S.HOLIDAY'  
+',T.CREW = S.CREW'  
+',T.SHIFTDURATION = S.SHIFTDURATION'  
+',T.SHIFTDATE = S.SHIFTDATE'  
+',T.UTC_CREATED_DATE = S.UTC_CREATED_DATE'  
+',T.UTC_LOGICAL_DELETED_DATE = S.UTC_LOGICAL_DELETED_DATE'  
+' WHEN NOT MATCHED'  
+' THEN INSERT ('  
+'  SITEFLAG' 
+' ,PREVSHIFTID'  
+' ,SHIFTID'  
+' ,NEXTSHIFTID'  
+',SHIFTNAME'  
+',DBNAME'  
+',SHIFTYEAR'  
+',SHIFTMONTH'  
+',SHIFTDAY'  
+',SHIFTSUFFIX'  
+',FULLSHIFTSUFFIX'  
+',SHIFTSTARTSECSINCEMIDNIGHT'  
+',SHIFTSTARTTIMESTAMP'  
+',SHIFTSTARTTIMESTAMPUTC'  
+',SHIFTSTARTDATE'  
+',SHIFTSTARTDATETIME'  
+',FULLSHIFTNAME'  
+',HOLIDAY'  
+',CREW'  
+',SHIFTDURATION'  
+',SHIFTDATE'  
+',UTC_CREATED_DATE'  
+',UTC_LOGICAL_DELETED_DATE'  
+'  ) VALUES('  
+' S.SITEFLAG' 
+' ,S.PREVSHIFTID'  
+' ,S.SHIFTID'  
+' ,S.NEXTSHIFTID'  
+',S.SHIFTNAME'  
+',S.DBNAME'  
+',S.SHIFTYEAR'  
+',S.SHIFTMONTH'  
+',S.SHIFTDAY'  
+',S.SHIFTSUFFIX'  
+',S.FULLSHIFTSUFFIX'  
+',S.SHIFTSTARTSECSINCEMIDNIGHT'  
+',S.SHIFTSTARTTIMESTAMP'  
+',S.SHIFTSTARTTIMESTAMPUTC'  
+',S.SHIFTSTARTDATE'  
+',S.SHIFTSTARTDATETIME'  
+',S.FULLSHIFTNAME'  
+',S.HOLIDAY'  
+',S.CREW'  
+',S.SHIFTDURATION'  
+',S.SHIFTDATE'  
+',S.UTC_CREATED_DATE'  
+',S.UTC_LOGICAL_DELETED_DATE'  
+' );'  
/*+'  UPDATE T'  
+' SET'  
+' FROM ' +@G_SITE+ '.SHIFT_INFO AS T '  
+' LEFT JOIN ' +@G_SITE+ '.SHIFT_INFO_STG AS S '  
+' ON ( '  
+' T.SHIFTID = S.SHIFTID) ; '*/  
 );  
END  
  
