

/******************************************************************  
* PROCEDURE : dbo.[UPSERT_CONOPS_DRILL_PLAN]
* PURPOSE	: Upsert [UPSERT_CONOPS_DRILL_PLAN]
* NOTES     : 
* CREATED	: lwasini
* SAMPLE    : EXEC dbo.[UPSERT_CONOPS_DRILL_PLAN] 
* MODIFIED DATE		AUTHOR				DESCRIPTION  
*------------------------------------------------------------------  
* {25 OCT 2022}		{lwasini}			{Initial Created}  
*******************************************************************/  
CREATE  PROCEDURE [dbo].[UPSERT_CONOPS_DRILL_PLAN]
AS
BEGIN

MERGE mor.drill_plan AS T 
USING (SELECT 
	 Id
	,WorkOrderId
	,Name
	,PlanId
	,OriginalPlanId
	,Comment
	,StartDate
	,StopDate
	,Area
	,CubicMass
	,Tons
	,AverageFaceHeight
	,IsDone
	,IsReadOnly
	,FirstRowBurden
	,SecondToNthRowBurden
	,Spacing
	,CoordinateSystemName
	,CoordinateSystemOrientation
	,ExternalTranslationVectorToOriginX
	,ExternalTranslationVectorToOriginY
	,ExternalTranslationVectorToOriginZ
	,Bearing
	,ReferenceHoleName
	,IsAutoGenerated
	,IsArchived
	,CreateDate
	,ModifiedDate
	,Author
	,FleetOrderId
	,DrillPlanGeofenceId
	,DrillPlanHoleSequenceId
	,IsAutonomous
	,DrillPlanHazardId
	,UTC_CREATED_DATE 
	,UTC_LOGICAL_DELETED_DATE
 FROM mor.drill_plan_stg
 WHERE CHANGE_TYPE IN ('U','I')) AS S 
 ON (T.Id = S.Id ) 
 WHEN MATCHED 
 THEN UPDATE SET 
	T.WorkOrderId = S.WorkOrderId
	,T.Name = S.Name
	,T.PlanId = S.PlanId
	,T.OriginalPlanId = S.OriginalPlanId
	,T.Comment = S.Comment
	,T.StartDate = S.StartDate
	,T.StopDate = S.StopDate
	,T.Area = S.Area
	,T.CubicMass = S.CubicMass
	,T.Tons = S.Tons
	,T.AverageFaceHeight = S.AverageFaceHeight
	,T.IsDone = S.IsDone
	,T.IsReadOnly = S.IsReadOnly
	,T.FirstRowBurden = S.FirstRowBurden
	,T.SecondToNthRowBurden = S.SecondToNthRowBurden
	,T.Spacing = S.Spacing
	,T.CoordinateSystemName = S.CoordinateSystemName
	,T.CoordinateSystemOrientation = S.CoordinateSystemOrientation
	,T.ExternalTranslationVectorToOriginX = S.ExternalTranslationVectorToOriginX
	,T.ExternalTranslationVectorToOriginY = S.ExternalTranslationVectorToOriginY
	,T.ExternalTranslationVectorToOriginZ = S.ExternalTranslationVectorToOriginZ
	,T.Bearing = S.Bearing
	,T.ReferenceHoleName = S.ReferenceHoleName
	,T.IsAutoGenerated = S.IsAutoGenerated
	,T.IsArchived = S.IsArchived
	,T.CreateDate = S.CreateDate
	,T.ModifiedDate = S.ModifiedDate
	,T.Author = S.Author
	,T.FleetOrderId = S.FleetOrderId
	,T.DrillPlanGeofenceId = S.DrillPlanGeofenceId
	,T.DrillPlanHoleSequenceId = S.DrillPlanHoleSequenceId
	,T.IsAutonomous = S.IsAutonomous
	,T.DrillPlanHazardId = S.DrillPlanHazardId 
	,T.UTC_CREATED_DATE = S.UTC_CREATED_DATE 
	,T.UTC_LOGICAL_DELETED_DATE = S.UTC_LOGICAL_DELETED_DATE 
 WHEN NOT MATCHED 
 THEN INSERT ( 
	 Id
	,WorkOrderId
	,Name
	,PlanId
	,OriginalPlanId
	,Comment
	,StartDate
	,StopDate
	,Area
	,CubicMass
	,Tons
	,AverageFaceHeight
	,IsDone
	,IsReadOnly
	,FirstRowBurden
	,SecondToNthRowBurden
	,Spacing
	,CoordinateSystemName
	,CoordinateSystemOrientation
	,ExternalTranslationVectorToOriginX
	,ExternalTranslationVectorToOriginY
	,ExternalTranslationVectorToOriginZ
	,Bearing
	,ReferenceHoleName
	,IsAutoGenerated
	,IsArchived
	,CreateDate
	,ModifiedDate
	,Author
	,FleetOrderId
	,DrillPlanGeofenceId
	,DrillPlanHoleSequenceId
	,IsAutonomous
	,DrillPlanHazardId
	,UTC_CREATED_DATE 
	,UTC_LOGICAL_DELETED_DATE 
  ) VALUES( 
	 S.Id
	,S.WorkOrderId
	,S.Name
	,S.PlanId
	,S.OriginalPlanId
	,S.Comment
	,S.StartDate
	,S.StopDate
	,S.Area
	,S.CubicMass
	,S.Tons
	,S.AverageFaceHeight
	,S.IsDone
	,S.IsReadOnly
	,S.FirstRowBurden
	,S.SecondToNthRowBurden
	,S.Spacing
	,S.CoordinateSystemName
	,S.CoordinateSystemOrientation
	,S.ExternalTranslationVectorToOriginX
	,S.ExternalTranslationVectorToOriginY
	,S.ExternalTranslationVectorToOriginZ
	,S.Bearing
	,S.ReferenceHoleName
	,S.IsAutoGenerated
	,S.IsArchived
	,S.CreateDate
	,S.ModifiedDate
	,S.Auth