

 
/******************************************************************    
* PROCEDURE : [dbo].[UPSERT_CONOPS_ALERT]     
* PURPOSE : Upsert [UPSERT_CONOPS_PLAN_VALUES]  
* NOTES     :   
* CREATED : mfahmi  
* SAMPLE    : EXEC [dbo].[UPSERT_CONOPS_ALERT] 'BAG'  
* MODIFIED DATE  AUTHOR    DESCRIPTION    
*------------------------------------------------------------------    
* {10 MAY 2023}  {mfahmi}   {Initial Created}    
*******************************************************************/    
CREATE  PROCEDURE [dbo].[UPSERT_CONOPS_ALERT]  
(            
@G_SITE  VARCHAR(5)            
          
)   
AS  
BEGIN  
--SET NOCOUNT ON 

--DECLARE @G_SITE VARCHAR(5)
--SET @G_SITE ='MOR'        
           
IF @G_SITE = 'MOR'  

BEGIN
  
MERGE MOR.ALERT AS T   
USING (
SELECT 
SHIFTINDEX AS SHIFTINDEX,
siteflag AS SITEFLAG,
EqmtType AS EQMT_TYPE,
EQUIPMENTNUMBER AS EQMTID,
OPERATORID AS OPERATOR_ID,
AlertType AS ALERT_TYPE,
AlertName AS ALERT_NAME,
AlertDesciption AS ALERT_DESCRIPTION,
END_TIME_TS AS ALERT_DATE,
STATUS_DURATION AS DURATION,
GeneratedDate AS ALERT_GENERATED_DATETIME,
getutcdate() AS UTC_CREATED_DATE
FROM MOR.[CONOPS_MOR_ALARM_DRILL_OPERATOR_BREAK_V]

UNION ALL

SELECT SHIFTINDEX AS SHIFTINDEX,
siteflag AS SITEFLAG,
EqmtType AS EQMT_TYPE,
EQUIPMENTNUMBER AS EQMTID,
OPERATORID AS OPERATOR_ID,
AlertType AS ALERT_TYPE,
AlertName AS ALERT_NAME,
AlertDesciption AS ALERT_DESCRIPTION,
END_TIME_TS AS ALERT_DATE,
STATUS_DURATION AS DURATION,
GeneratedDate AS ALERT_GENERATED_DATETIME,
getutcdate() AS UTC_CREATED_DATE 
FROM MOR.CONOPS_MOR_ALARM_TRUCK_SHOVEL_OPERATOR_BREAK_V

) AS S   
 ON (T.SHIFTINDEX = S.SHIFTINDEX 
 AND T.SITEFLAG = S.SITEFLAG
 AND T.EQMTID = S.EQMTID
 AND T.ALERT_TYPE = S.ALERT_TYPE)   
  
 WHEN MATCHED   
 THEN UPDATE SET  
 T.EQMT_TYPE = S.EQMT_TYPE
,T.OPERATOR_ID = S.OPERATOR_ID
,T.ALERT_NAME = S.ALERT_NAME
,T.ALERT_DESCRIPTION = S.ALERT_DESCRIPTION
,T.ALERT_DATE = S.ALERT_DATE
,T.DURATION = S.DURATION
,T.ALERT_GENERATED_DATETIME = S.ALERT_GENERATED_DATETIME
,T.UTC_CREATED_DATE = S.UTC_CREATED_DATE
 
 WHEN NOT MATCHED   
 THEN INSERT (
 SHIFTINDEX,
SITEFLAG,
EQMT_TYPE,
EQMTID,
OPERATOR_ID,
ALERT_TYPE,
ALERT_NAME,
ALERT_DESCRIPTION,
ALERT_DATE,
DURATION,
ALERT_GENERATED_DATETIME,
UTC_CREATED_DATE
  ) VALUES( 
  S.SHIFTINDEX,
S.SITEFLAG,
S.EQMT_TYPE,
S.EQMTID,
S.OPERATOR_ID,
S.ALERT_TYPE,
S.ALERT_NAME,
S.ALERT_DESCRIPTION,
S.ALERT_DATE,
S.DURATION,
S.ALERT_GENERATED_DATETIME,
S.UTC_CREATED_DATE
 ); 

DELETE FROM MOR.ALERT 
WHERE SHIFTINDEX < (SELECT SHIFTINDEX - 3            
FROM [DBO].[SHIFT_INFO_V]            
WHERE SITEFLAG = 'MOR' AND SHIFTFLAG ='CURR')    
   
END  
    
--SET NOCOUNT OFF 

ELSE IF @G_SITE = 'BAG'  

BEGIN
  
MERGE BAG.ALERT AS T   
USING (
SELECT 
SHIFTINDEX AS SHIFTINDEX,
siteflag AS SITEFLAG,
EqmtType AS EQMT_TYPE,
EQUIPMENTNUMBER AS EQMTID,
OPERATORID AS OPERATOR_ID,
AlertType AS ALERT_TYPE,
AlertName AS ALERT_NAME,
AlertDesciption AS ALERT_DESCRIPTION,
END_TIME_TS AS ALERT_DATE,
STATUS_DURATION AS DURATION,
GeneratedDate AS ALERT_GENERATED_DATETIME,
getutcdate() AS UTC_CREATED_DATE
FROM BAG.[CONOPS_BAG_ALARM_DRILL_OPERATOR_BREAK_V]

UNION ALL

SELECT SHIFTINDEX AS SHIFTINDEX,
siteflag AS SITEFLAG,
EqmtType AS EQMT_TYPE,
EQUIPMENTNUMBER AS EQMTID,
OPERID AS OPERATOR_ID,
AlertType AS ALERT_TYPE,
AlertName AS ALERT_NAME,
AlertDesciption AS ALERT_DESCRIPTION,
END_TIME_TS AS ALERT_DATE,
STATUS_DURATION AS DURATION,
GeneratedDate AS ALERT_GENERATED_DATETIME,
getutcdate() AS UTC_CREATED_DATE 
FROM BAG.CONOPS_BAG_ALARM_TRUCK_SHOVEL_OPERATOR_BREAK_V

) AS S   
 ON (T.SHIFTINDEX = S.SHIFTINDEX 
 AND T.SITEFLAG = S.SITEFLAG
 AND T.EQMTID = S.EQMTID
 AND T.ALERT_TYPE = S.ALERT_TYPE)   
  
 WHEN MATCHED   
 THEN UPDATE SET  
 T.EQMT_TYPE = S.EQMT_TYPE
,T.OPERATOR_ID = S.OPERATOR_ID
,T.ALERT_NAME = S.ALERT_NAME
,T.ALERT_DESCRIP