CREATE VIEW [bag2].[MSHIST_MINE_LOCATION] AS


-- MINE LOCATION

CREATE VIEW [bag2].[MSHIST_MINE_LOCATION]
AS

SELECT
    'BAG' AS SITE_CODE,
    L.NAME AS LOC_NAME,
    V.ROUTE_POINT_X AS LOC_X,
    V.ROUTE_POINT_Y AS LOC_Y,
    V.ROUTE_POINT_Z AS LOC_Z,
    MCA.NAME AS EQUIP_CATEGORY_NAME, -- Yet to be confirmed
    DC.EXTERNALREF AS STATUS_EVENT_REASON_CODE -- Yet to be confirmed
    -- DELAYCLASS.NAME AS REASON_NAME Already in equipment table
FROM [ConnectedOperations].[bag2].[LOCATION] L WITH (NOLOCK)
LEFT JOIN [ConnectedOperations].[bag2].[LOCATION_WAYPOINT] LW WITH (NOLOCK)
    ON L.LOCATION_OID = LW.OID
LEFT JOIN [ConnectedOperations].[bag2].[VIRTUALBEACON] V WITH (NOLOCK)
    ON LW.WAYPOINT_OID = V.VIRTUALBEACON_OID
LEFT JOIN [ConnectedOperations].[bag2].[CYCLE] C WITH (NOLOCK)
    ON C.SOURCELOCATION = L.LOCATION_OID -- Whether we need to take the destination location
LEFT JOIN [ConnectedOperations].[bag2].[MACHINECLASS] MC WITH (NOLOCK)
    ON C.PRIMARYMACHINECLASS = MC.MACHINECLASS_OID
LEFT JOIN [ConnectedOperations].[bag2].[MACHINECATEGORY] MCA WITH (NOLOCK)
    ON MC.CATEGORY = MCA.MACHINECATEGORY_OID
LEFT JOIN [ConnectedOperations].[bag2].[CYCLEDELAY] CD WITH (NOLOCK)
    ON C.CYCLE_OID = CD.OID
LEFT JOIN [ConnectedOperations].[bag2].[DELAYCLASS] DC WITH (NOLOCK)
    ON CD.DELAY_CLASS_OID = DC.DELAYCLASS_OID;


