CREATE VIEW [bag2].[VIEW_CYCLE_ETL] AS

CREATE VIEW [bag2].[VIEW_CYCLE_ETL]   
AS      
SELECT 
JSON_VALUE(DATA_VALUE.value, '$.CYCLE_OID') AS CYCLE_OID,
JSON_VALUE(DATA_VALUE.value, '$.ECF_CLASS_ID') AS ECF_CLASS_ID,
JSON_VALUE(DATA_VALUE.value, '$.STARTTIME_UTC') AS STARTTIME_UTC,
JSON_VALUE(DATA_VALUE.value, '$.ENDTIME_UTC') AS ENDTIME_UTC,
JSON_VALUE(DATA_VALUE.value, '$.JOBCODE') AS JOBCODE,
JSON_VALUE(DATA_VALUE.value, '$.CREATIONMODE') AS CREATIONMODE,
JSON_VALUE(DATA_VALUE.value, '$.VALIDATIONSEVERITY') AS VALIDATIONSEVERITY,
JSON_VALUE(DATA_VALUE.value, '$.PRIMARYMACHINE') AS PRIMARYMACHINE,
JSON_VALUE(DATA_VALUE.value, '$.PRIMARYMACHINENAME') AS PRIMARYMACHINENAME,
JSON_VALUE(DATA_VALUE.value, '$.PRIMARYMACHINECLASS') AS PRIMARYMACHINECLASS,
JSON_VALUE(DATA_VALUE.value, '$.PRIMARYMACHINECLASSNAME') AS PRIMARYMACHINECLASSNAME,
JSON_VALUE(DATA_VALUE.value, '$.PRIMARYMACHINECATEGORY') AS PRIMARYMACHINECATEGORY,
JSON_VALUE(DATA_VALUE.value, '$.PRIMARYMACHINECATEGORYNAME') AS PRIMARYMACHINECATEGORYNAME,
JSON_VALUE(DATA_VALUE.value, '$.SECONDARYMACHINE') AS SECONDARYMACHINE,
JSON_VALUE(DATA_VALUE.value, '$.SECONDARYMACHINENAME') AS SECONDARYMACHINENAME,
JSON_VALUE(DATA_VALUE.value, '$.SECONDARYMACHINECLASS') AS SECONDARYMACHINECLASS,
JSON_VALUE(DATA_VALUE.value, '$.SECONDARYMACHINECLASSNAME') AS SECONDARYMACHINECLASSNAME,
JSON_VALUE(DATA_VALUE.value, '$.SECONDARYMACHINECATEGORY') AS SECONDARYMACHINECATEGORY,
JSON_VALUE(DATA_VALUE.value, '$.SECONDARYMACHINECATEGORYNAME') AS SECONDARYMACHINECATEGORYNAME,
JSON_VALUE(DATA_VALUE.value, '$.PRIMARYOPERATOR') AS PRIMARYOPERATOR,
JSON_VALUE(DATA_VALUE.value, '$.PRIMARYOPERATORNAME') AS PRIMARYOPERATORNAME,
JSON_VALUE(DATA_VALUE.value, '$.SECONDARYOPERATOR') AS SECONDARYOPERATOR,
JSON_VALUE(DATA_VALUE.value, '$.SECONDARYOPERATORNAME') AS SECONDARYOPERATORNAME,
JSON_VALUE(DATA_VALUE.value, '$.ESTIMATEDFUELUSED') AS ESTIMATEDFUELUSED,
JSON_VALUE(DATA_VALUE.value, '$.AVGBURNFUELUSED') AS AVGBURNFUELUSED,
JSON_VALUE(DATA_VALUE.value, '$.MACHINEFUELCONSUMED') AS MACHINEFUELCONSUMED,
JSON_VALUE(DATA_VALUE.value, '$.PREVIOUSCYCLE') AS PREVIOUSCYCLE,
JSON_VALUE(DATA_VALUE.value, '$.ASSOCIATEDCYCLE') AS ASSOCIATEDCYCLE,
JSON_VALUE(DATA_VALUE.value, '$.VALIDATION_MSG') AS VALIDATION_MSG,
JSON_VALUE(DATA_VALUE.value, '$.SOURCE_COORD_X') AS SOURCE_COORD_X,
JSON_VALUE(DATA_VALUE.value, '$.SOURCE_COORD_Y') AS SOURCE_COORD_Y,
JSON_VALUE(DATA_VALUE.value, '$.SOURCE_COORD_Z') AS SOURCE_COORD_Z,
JSON_VALUE(DATA_VALUE.value, '$.SINK_COORD_X') AS SINK_COORD_X,
JSON_VALUE(DATA_VALUE.value, '$.SINK_COORD_Y') AS SINK_COORD_Y,
JSON_VALUE(DATA_VALUE.value, '$.SINK_COORD_Z') AS SINK_COORD_Z,
JSON_VALUE(DATA_VALUE.value, '$.END_SINK_COORD_X') AS END_SINK_COORD_X,
JSON_VALUE(DATA_VALUE.value, '$.END_SINK_COORD_Y') AS END_SINK_COORD_Y,
JSON_VALUE(DATA_VALUE.value, '$.END_SINK_COORD_Z') AS END_SINK_COORD_Z,
JSON_VALUE(DATA_VALUE.value, '$.DUMP_COORD_X') AS DUMP_COORD_X,
JSON_VALUE(DATA_VALUE.value, '$.DUMP_COORD_Y') AS DUMP_COORD_Y,
JSON_VALUE(DATA_VALUE.value, '$.DUMP_COORD_Z') AS DUMP_COORD_Z,
JSON_VALUE(DATA_VALUE.value, '$.HASPREDICTEDROADS') AS HASPREDICTEDROADS,
JSON_VALUE(DATA_VALUE.value, '$.AUTONOMOUS') AS AUTONOMOUS,
JSON_VALUE(DATA_VALUE.value, '$.HASDELAYS') AS HASDELAYS,
JSON_VALUE(DATA_VALUE.value, '$.CALCMATERIAL') AS CALCMATERIAL,
JSON_VALUE(DATA_VALUE.value, '$.CALCMATERIALNAME') AS CALCMATERIALNAME,
JSON_VALUE(DATA_VALUE.value, '$.DENSITY') AS DENSITY,
JSON_VALUE(DATA_VALUE.value, '$.DENSITYNAME') AS DENSITYNAME,
JSON_VALUE(DATA_VALUE.value, '$.DENSITYTYPE') AS DENSITYTYPE,
JSON_VALUE(DATA_VALUE.value, '$.DIPPERCOUNT') AS DIPPERCOUNT,
JSON_VALUE(DATA_VALUE.value, '$.DIPPERAVERAGESWINGTIME') AS DIPPERAVERAGESWINGTIME,
JSON_VALUE(DATA_VALUE.value, '$.ENDSMU') AS ENDSMU,
JSON_VALUE(DATA_VALUE.value, '$.LOADERMATERIAL') AS LOADERMATERIAL,
JSON_VALUE(DATA_VALUE.value, '$.LOADERMATERIALNAME') AS LOADERMATERIALNAME,
JSON_VALUE(DATA_VALUE.value, '$.OPERMATERIAL') AS OPERMATERIAL,
JS