CREATE VIEW [CER].[SHIFT_OPER] AS




--SELECT * FROM CER.SHIFT_OPER
CREATE VIEW CER.SHIFT_OPER
AS

SELECT
'CER' AS SiteFlag,
*
FROM CVEOperational.dbo.SHIFTShiftOper WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM CER.SHIFT_INFO)




