CREATE VIEW [CER].[SHIFT_GRADE] AS



--SELECT * FROM CER.SHIFT_GRADE
CREATE VIEW CER.SHIFT_GRADE
AS

SELECT
'CER' AS SiteFlag,
*
FROM CVEOperational.dbo.SHIFTShiftgrade WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM CER.SHIFT_INFO)



