CREATE OR REPLACE PROCEDURE {{ envi }}_API_REF.FUSE.BLAST_PLAN_INCR_P("NUMBER_OF_DAYS" VARCHAR(16777216) DEFAULT '3')
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
/*****************************************************************************************
* PURPOSE   : Merge data from BLAST_PLAN into BLAST_PLAN_INCR
* SOURCE    : {{ RO_PROD }}_WG.DRILL_BLAST.BLAST_PLAN
* TARGET    : {{ envi }}_API_REF.FUSE.BLAST_PLAN_INCR
* BUSINESS KEY: BLAST_PLAN_SK
* INCREMENTAL COLUMN: PLAN_CREATION_TS_LOCAL (Business timestamp - plan creation time)
* HASH CHECK: TRUE DELTA DETECTION
* COLUMNS: 66 (ALL columns - COMPLETE COVERAGE)
* DATE: 2026-01-29 | AUTHOR: CARLOS CARRILLO
* FIX: Complete 66-column coverage - NO columns omitted
******************************************************************************************/

var sp_result="";
var sql_count_incr, sql_delete_incr, sql_merge, sql_delete;
var rs_count_incr, rs_delete_incr, rs_merge, rs_delete;
var rs_records_incr, rs_deleted_records_incr, rs_merged_records, rs_delete_records;

sql_count_incr = `SELECT COUNT(*) AS count_check_1 
                  FROM {{ envi }}_API_REF.fuse.blast_plan_incr 
                  WHERE PLAN_CREATION_TS_LOCAL::date < DATEADD(day, -` + NUMBER_OF_DAYS + `, CURRENT_DATE);`;

sql_delete_incr = `DELETE FROM {{ envi }}_API_REF.fuse.blast_plan_incr 
                   WHERE PLAN_CREATION_TS_LOCAL::date < DATEADD(day, -` + NUMBER_OF_DAYS + `, CURRENT_DATE);`;

sql_merge = `MERGE INTO {{ envi }}_API_REF.fuse.blast_plan_incr tgt
USING (
    SELECT *,
           ''N'' AS dw_logical_delete_flag_new,
           CURRENT_TIMESTAMP(0)::TIMESTAMP_NTZ AS dw_load_ts_new
    FROM {{ RO_PROD }}_WG.DRILL_BLAST.BLAST_PLAN
    WHERE PLAN_CREATION_TS_LOCAL >= DATEADD(day, -` + NUMBER_OF_DAYS + `, CURRENT_DATE)
) AS src
ON tgt.BLAST_PLAN_SK = src.BLAST_PLAN_SK

WHEN MATCHED AND HASH(src.BLAST_NAME, src.BLAST_TYPE, src.DRILLED_HOLE_NAME, src.DEPTH_FEET,
                      src.CHARGE_RULE_NAME, src.POWDER_FACTOR, src.DW_MODIFY_TS)
              <> HASH(tgt.BLAST_NAME, tgt.BLAST_TYPE, tgt.DRILLED_HOLE_NAME, tgt.DEPTH_FEET,
                      tgt.CHARGE_RULE_NAME, tgt.POWDER_FACTOR, tgt.DW_MODIFY_TS)
THEN UPDATE SET
    tgt.ORIG_SRC_ID = src.ORIG_SRC_ID, tgt.SITE_CODE = src.SITE_CODE, tgt.BENCH = src.BENCH,
    tgt.PUSHBACK = src.PUSHBACK, tgt.PATTERN_NAME = src.PATTERN_NAME, tgt.BLAST_NAME = src.BLAST_NAME,
    tgt.PLAN_CREATION_TS_UTC = src.PLAN_CREATION_TS_UTC, tgt.PLAN_CREATION_TS_LOCAL = src.PLAN_CREATION_TS_LOCAL,
    tgt.DESIGN_BY = src.DESIGN_BY, tgt.DRILL_CYCLE_SK = src.DRILL_CYCLE_SK, tgt.BLAST_ID = src.BLAST_ID,
    tgt.DRILLED_HOLE_ID = src.DRILLED_HOLE_ID, tgt.BLAST_TYPE = src.BLAST_TYPE, tgt.BLAST_GOAL = src.BLAST_GOAL,
    tgt.BLAST_DATE_UTC = src.BLAST_DATE_UTC, tgt.DRILLED_HOLE_NAME = src.DRILLED_HOLE_NAME,
    tgt.DRILLED_HOLE_FLAG = src.DRILLED_HOLE_FLAG,
    tgt.HOLE_START_METERS_X = src.HOLE_START_METERS_X, tgt.HOLE_START_METERS_Y = src.HOLE_START_METERS_Y,
    tgt.HOLE_START_METERS_Z = src.HOLE_START_METERS_Z,
    tgt.HOLE_START_FEET_X = src.HOLE_START_FEET_X, tgt.HOLE_START_FEET_Y = src.HOLE_START_FEET_Y,
    tgt.HOLE_START_FEET_Z = src.HOLE_START_FEET_Z,
    tgt.DEPTH_METERS = src.DEPTH_METERS, tgt.DEPTH_FEET = src.DEPTH_FEET,
    tgt.CHARGE_RULE_NAME = src.CHARGE_RULE_NAME, tgt.EXPLOSIVE_PRODUCT_BOTTOM = src.EXPLOSIVE_PRODUCT_BOTTOM,
    tgt.EXPLOSIVE_PRODUCT_TOP = src.EXPLOSIVE_PRODUCT_TOP, tgt.EXPLOSIVE_PRODUCT_COUNT = src.EXPLOSIVE_PRODUCT_COUNT,
    tgt.EXPLOSIVE_PRODUCT_USED_BOTTOM_KILOGRAMS = src.EXPLOSIVE_PRODUCT_USED_BOTTOM_KILOGRAMS,
    tgt.EXPLOSIVE_PRODUCT_USED_BOTTOM_POUNDS = src.EXPLOSIVE_PRODUCT_USED_BOTTOM_POUNDS,
    tgt.EXPLOSIVE_PRODUCT_USED_TOP_KILOGRAMS = src.EXPLOSIVE_PRODUCT_USED_TOP_KILOGRAMS,
    tgt.EXPLOSIVE_PRODUCT_USED_TOP_POUNDS = src.EXPLOSIVE_PRODUCT_USED_TOP_POUNDS,
    tgt.EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_METERS = src.EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_METERS,
    tgt.EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_FEET = src.EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_FEET,
    tgt.EXPLOSIVE_PRODUCT_LENGTH_TOP_METERS = src.EXPLOSIVE_PRODUCT_LENGTH_TOP_METERS,
    tgt.EXPLOSIVE_PRODUCT_LENGTH_TOP_FEET = src.EXPLOSIVE_PRODUCT_LENGTH_TOP_FEET,
    tgt.STEMMING_LENGTH_TOTAL_METERS = src.STEMMING_LENGTH_TOTAL_METERS,
    tgt.STEMMING_LENGTH_TOTAL_FEET = src.STEMMING_LENGTH_TOTAL_FEET,
    tgt.STEMMING_LENGTH_BOTTOM_METERS = src.STEMMING_LENGTH_BOTTOM_METERS,
    tgt.STEMMING_LENGTH_BOTTOM_FEET = src.STEMMING_LENGTH_BOTTOM_FEET,
    tgt.STEMMING_LENGTH_TOP_METERS = src.STEMMING_LENGTH_TOP_METERS,
    tgt.STEMMING_LENGTH_TOP_FEET = src.STEMMING_LENGTH_TOP_FEET,
    tgt.AIR_BAG_ELEVATION_METERS = src.AIR_BAG_ELEVATION_METERS,
    tgt.AIR_BAG_ELEVATION_FEET = src.AIR_BAG_ELEVATION_FEET, tgt.AIR_BAG_FLAG = src.AIR_BAG_FLAG,
    tgt.AIR_ELEVATION_METERS = src.AIR_ELEVATION_METERS, tgt.AIR_ELEVATION_FEET = src.AIR_ELEVATION_FEET,
    tgt.AIR_FLAG = src.AIR_FLAG,
    tgt.BURDEN_METERS = src.BURDEN_METERS, tgt.BURDEN_FEET = src.BURDEN_FEET,
    tgt.SPACING_METERS = src.SPACING_METERS, tgt.SPACING_FEET = src.SPACING_FEET,
    tgt.TONS_PER_HOLE = src.TONS_PER_HOLE, tgt.HOLE_REMOVED_FLAG = src.HOLE_REMOVED_FLAG,
    tgt.KCALS_PER_TON = src.KCALS_PER_TON, tgt.POWDER_FACTOR = src.POWDER_FACTOR,
    tgt.MEGAJOULES_PER_TON = src.MEGAJOULES_PER_TON, tgt.CONFINEMENT_FACTOR = src.CONFINEMENT_FACTOR,
    tgt.TIMING_RATIO = src.TIMING_RATIO, tgt.TARGET_P80 = src.TARGET_P80,
    tgt.REACTIVE_GROUND_FLAG = src.REACTIVE_GROUND_FLAG, tgt.PRIMER_COUNT = src.PRIMER_COUNT,
    tgt.DW_MODIFY_TS = CURRENT_TIMESTAMP(0)::TIMESTAMP_NTZ

WHEN NOT MATCHED THEN INSERT (
    BLAST_PLAN_SK, ORIG_SRC_ID, SITE_CODE, BENCH, PUSHBACK, PATTERN_NAME, BLAST_NAME,
    PLAN_CREATION_TS_UTC, PLAN_CREATION_TS_LOCAL, DESIGN_BY, DRILL_CYCLE_SK, BLAST_ID,
    DRILLED_HOLE_ID, BLAST_TYPE, BLAST_GOAL, BLAST_DATE_UTC, DRILLED_HOLE_NAME, DRILLED_HOLE_FLAG,
    HOLE_START_METERS_X, HOLE_START_METERS_Y, HOLE_START_METERS_Z,
    HOLE_START_FEET_X, HOLE_START_FEET_Y, HOLE_START_FEET_Z,
    DEPTH_METERS, DEPTH_FEET, CHARGE_RULE_NAME,
    EXPLOSIVE_PRODUCT_BOTTOM, EXPLOSIVE_PRODUCT_TOP, EXPLOSIVE_PRODUCT_COUNT,
    EXPLOSIVE_PRODUCT_USED_BOTTOM_KILOGRAMS, EXPLOSIVE_PRODUCT_USED_BOTTOM_POUNDS,
    EXPLOSIVE_PRODUCT_USED_TOP_KILOGRAMS, EXPLOSIVE_PRODUCT_USED_TOP_POUNDS,
    EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_METERS, EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_FEET,
    EXPLOSIVE_PRODUCT_LENGTH_TOP_METERS, EXPLOSIVE_PRODUCT_LENGTH_TOP_FEET,
    STEMMING_LENGTH_TOTAL_METERS, STEMMING_LENGTH_TOTAL_FEET,
    STEMMING_LENGTH_BOTTOM_METERS, STEMMING_LENGTH_BOTTOM_FEET,
    STEMMING_LENGTH_TOP_METERS, STEMMING_LENGTH_TOP_FEET,
    AIR_BAG_ELEVATION_METERS, AIR_BAG_ELEVATION_FEET, AIR_BAG_FLAG,
    AIR_ELEVATION_METERS, AIR_ELEVATION_FEET, AIR_FLAG,
    BURDEN_METERS, BURDEN_FEET, SPACING_METERS, SPACING_FEET,
    TONS_PER_HOLE, HOLE_REMOVED_FLAG, KCALS_PER_TON, POWDER_FACTOR,
    MEGAJOULES_PER_TON, CONFINEMENT_FACTOR, TIMING_RATIO, TARGET_P80,
    REACTIVE_GROUND_FLAG, PRIMER_COUNT,
    DW_LOAD_TS, DW_MODIFY_TS, DW_LOGICAL_DELETE_FLAG
) VALUES (
    src.BLAST_PLAN_SK, src.ORIG_SRC_ID, src.SITE_CODE, src.BENCH, src.PUSHBACK, src.PATTERN_NAME, src.BLAST_NAME,
    src.PLAN_CREATION_TS_UTC, src.PLAN_CREATION_TS_LOCAL, src.DESIGN_BY, src.DRILL_CYCLE_SK, src.BLAST_ID,
    src.DRILLED_HOLE_ID, src.BLAST_TYPE, src.BLAST_GOAL, src.BLAST_DATE_UTC, src.DRILLED_HOLE_NAME, src.DRILLED_HOLE_FLAG,
    src.HOLE_START_METERS_X, src.HOLE_START_METERS_Y, src.HOLE_START_METERS_Z,
    src.HOLE_START_FEET_X, src.HOLE_START_FEET_Y, src.HOLE_START_FEET_Z,
    src.DEPTH_METERS, src.DEPTH_FEET, src.CHARGE_RULE_NAME,
    src.EXPLOSIVE_PRODUCT_BOTTOM, src.EXPLOSIVE_PRODUCT_TOP, src.EXPLOSIVE_PRODUCT_COUNT,
    src.EXPLOSIVE_PRODUCT_USED_BOTTOM_KILOGRAMS, src.EXPLOSIVE_PRODUCT_USED_BOTTOM_POUNDS,
    src.EXPLOSIVE_PRODUCT_USED_TOP_KILOGRAMS, src.EXPLOSIVE_PRODUCT_USED_TOP_POUNDS,
    src.EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_METERS, src.EXPLOSIVE_PRODUCT_LENGTH_BOTTOM_FEET,
    src.EXPLOSIVE_PRODUCT_LENGTH_TOP_METERS, src.EXPLOSIVE_PRODUCT_LENGTH_TOP_FEET,
    src.STEMMING_LENGTH_TOTAL_METERS, src.STEMMING_LENGTH_TOTAL_FEET,
    src.STEMMING_LENGTH_BOTTOM_METERS, src.STEMMING_LENGTH_BOTTOM_FEET,
    src.STEMMING_LENGTH_TOP_METERS, src.STEMMING_LENGTH_TOP_FEET,
    src.AIR_BAG_ELEVATION_METERS, src.AIR_BAG_ELEVATION_FEET, src.AIR_BAG_FLAG,
    src.AIR_ELEVATION_METERS, src.AIR_ELEVATION_FEET, src.AIR_FLAG,
    src.BURDEN_METERS, src.BURDEN_FEET, src.SPACING_METERS, src.SPACING_FEET,
    src.TONS_PER_HOLE, src.HOLE_REMOVED_FLAG, src.KCALS_PER_TON, src.POWDER_FACTOR,
    src.MEGAJOULES_PER_TON, src.CONFINEMENT_FACTOR, src.TIMING_RATIO, src.TARGET_P80,
    src.REACTIVE_GROUND_FLAG, src.PRIMER_COUNT,
    src.dw_load_ts_new, CURRENT_TIMESTAMP(0)::TIMESTAMP_NTZ, src.dw_logical_delete_flag_new
);`;

sql_delete = `UPDATE {{ envi }}_API_REF.fuse.blast_plan_incr tgt
              SET dw_logical_delete_flag = ''Y'', dw_modify_ts = CURRENT_TIMESTAMP(0)::TIMESTAMP_NTZ
              WHERE tgt.dw_logical_delete_flag = ''N''
              AND NOT EXISTS (SELECT 1 FROM {{ RO_PROD }}_WG.DRILL_BLAST.BLAST_PLAN src
                  WHERE src.BLAST_PLAN_SK = tgt.BLAST_PLAN_SK);`;

try {
    snowflake.execute({sqlText: "BEGIN WORK;"});
    rs_count_incr = snowflake.execute({sqlText: sql_count_incr});
    rs_count_incr.next();
    rs_records_incr = rs_count_incr.getColumnValue(''COUNT_CHECK_1'');
    rs_deleted_records_incr = rs_records_incr > 0 ? snowflake.execute({sqlText: sql_delete_incr}).getNumRowsAffected() : 0;
    rs_merge = snowflake.execute({sqlText: sql_merge});
    rs_merged_records = rs_merge.getNumRowsAffected();
    rs_delete = snowflake.execute({sqlText: sql_delete});
    rs_delete_records = rs_delete.getNumRowsAffected();
    sp_result = "Deleted: " + rs_deleted_records_incr + ", Merged: " + rs_merged_records + ", Archived: " + rs_delete_records;
    snowflake.execute({sqlText: "COMMIT WORK;"});
    return sp_result;
} catch (err) { snowflake.execute({sqlText: "ROLLBACK WORK;"}); throw err; }
';

