CREATE OR REPLACE PROCEDURE {{ envi }}_API_REF.FUSE.DRILL_CYCLE_INCR_P("NUMBER_OF_DAYS" VARCHAR(16777216) DEFAULT '3')
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
/*****************************************************************************************
* PURPOSE   : Merge data from DRILL_CYCLE into DRILL_CYCLE_INCR
* SOURCE    : {{ RO_PROD }}_WG.DRILL_BLAST.DRILL_CYCLE
* TARGET    : {{ envi }}_API_REF.FUSE.DRILL_CYCLE_INCR
* BUSINESS KEY: DRILL_CYCLE_SK
* INCREMENTAL COLUMN: END_HOLE_TS_LOCAL (Business timestamp - hole completion time)
* HASH CHECK: TRUE DELTA DETECTION
* COLUMNS: 108 (ALL columns - COMPLETE COVERAGE)
* DATE: 2026-01-29 | AUTHOR: CARLOS CARRILLO
* FIX: Complete 108-column coverage - NO columns omitted
******************************************************************************************/

var sp_result="";
var sql_count_incr, sql_delete_incr, sql_merge, sql_delete;
var rs_count_incr, rs_delete_incr, rs_merge, rs_delete;
var rs_records_incr, rs_deleted_records_incr, rs_merged_records, rs_delete_records;

sql_count_incr = `SELECT COUNT(*) AS count_check_1 
                  FROM {{ envi }}_API_REF.fuse.drill_cycle_incr 
                  WHERE END_HOLE_TS_LOCAL::date < DATEADD(day, -` + NUMBER_OF_DAYS + `, CURRENT_DATE);`;

sql_delete_incr = `DELETE FROM {{ envi }}_API_REF.fuse.drill_cycle_incr 
                   WHERE END_HOLE_TS_LOCAL::date < DATEADD(day, -` + NUMBER_OF_DAYS + `, CURRENT_DATE);`;

sql_merge = `MERGE INTO {{ envi }}_API_REF.fuse.drill_cycle_incr tgt
USING (
    SELECT *,
           ''N'' AS dw_logical_delete_flag_new,
           CURRENT_TIMESTAMP(0)::TIMESTAMP_NTZ AS dw_load_ts_new
    FROM {{ RO_PROD }}_WG.DRILL_BLAST.DRILL_CYCLE
    WHERE END_HOLE_TS_LOCAL >= DATEADD(day, -` + NUMBER_OF_DAYS + `, CURRENT_TIMESTAMP())
) AS src
ON tgt.DRILL_CYCLE_SK = src.DRILL_CYCLE_SK

WHEN MATCHED AND HASH(src.DRILL_HOLE_STATUS, src.ACTUAL_DRILL_HOLE_DEPTH_FEET, src.DRILL_DURATION, 
                      src.END_HOLE_TS_LOCAL, src.DRILL_HOLE_PENETRATION_RATE_AVG_FEET_HOUR,
                      src.BENCH, src.PUSHBACK, src.PATTERN_NAME, src.DRILL_ID, src.DW_MODIFY_TS)
              <> HASH(tgt.DRILL_HOLE_STATUS, tgt.ACTUAL_DRILL_HOLE_DEPTH_FEET, tgt.DRILL_DURATION, 
                      tgt.END_HOLE_TS_LOCAL, tgt.DRILL_HOLE_PENETRATION_RATE_AVG_FEET_HOUR,
                      tgt.BENCH, tgt.PUSHBACK, tgt.PATTERN_NAME, tgt.DRILL_ID, tgt.DW_MODIFY_TS)
THEN UPDATE SET
    tgt.ORIG_SRC_ID = src.ORIG_SRC_ID, tgt.SITE_CODE = src.SITE_CODE,
    tgt.BENCH = src.BENCH, tgt.PUSHBACK = src.PUSHBACK, tgt.PATTERN_NAME = src.PATTERN_NAME,
    tgt.ORIGINAL_PATTERN_NAME = src.ORIGINAL_PATTERN_NAME, tgt.DRILL_HOLE_SHIFT_ID = src.DRILL_HOLE_SHIFT_ID,
    tgt.DRILL_ID = src.DRILL_ID, tgt.DRILL_BIT_ID = src.DRILL_BIT_ID, tgt.SYSTEM_OPERATOR_ID = src.SYSTEM_OPERATOR_ID,
    tgt.DRILL_HOLE_ID = src.DRILL_HOLE_ID, tgt.DRILL_HOLE_NAME = src.DRILL_HOLE_NAME,
    tgt.DRILL_PLAN_SK = src.DRILL_PLAN_SK, tgt.DRILL_HOLE_STATUS = src.DRILL_HOLE_STATUS,
    tgt.IS_HOLE_PLANNED_FLAG = src.IS_HOLE_PLANNED_FLAG,
    tgt.START_HOLE_TS_UTC = src.START_HOLE_TS_UTC, tgt.END_HOLE_TS_UTC = src.END_HOLE_TS_UTC,
    tgt.OPERATOR_LOGIN_TS_UTC = src.OPERATOR_LOGIN_TS_UTC, tgt.OPERATOR_LOGOUT_TS_UTC = src.OPERATOR_LOGOUT_TS_UTC,
    tgt.PROPEL_START_TS_UTC = src.PROPEL_START_TS_UTC, tgt.PROPEL_END_TS_UTC = src.PROPEL_END_TS_UTC,
    tgt.PARK_POSITION_START_TS_UTC = src.PARK_POSITION_START_TS_UTC, tgt.PARK_POSITION_END_TS_UTC = src.PARK_POSITION_END_TS_UTC,
    tgt.LEVEL_START_TS_UTC = src.LEVEL_START_TS_UTC, tgt.LEVEL_END_TS_UTC = src.LEVEL_END_TS_UTC,
    tgt.DRILL_START_TS_UTC = src.DRILL_START_TS_UTC, tgt.DRILL_END_TS_UTC = src.DRILL_END_TS_UTC,
    tgt.RETRACT_START_TS_UTC = src.RETRACT_START_TS_UTC, tgt.RETRACT_END_TS_UTC = src.RETRACT_END_TS_UTC,
    tgt.START_HOLE_TS_LOCAL = src.START_HOLE_TS_LOCAL, tgt.END_HOLE_TS_LOCAL = src.END_HOLE_TS_LOCAL,
    tgt.OPERATOR_LOGIN_TS_LOCAL = src.OPERATOR_LOGIN_TS_LOCAL, tgt.OPERATOR_LOGOUT_TS_LOCAL = src.OPERATOR_LOGOUT_TS_LOCAL,
    tgt.PROPEL_START_TS_LOCAL = src.PROPEL_START_TS_LOCAL, tgt.PROPEL_END_TS_LOCAL = src.PROPEL_END_TS_LOCAL,
    tgt.PARK_POSITION_START_TS_LOCAL = src.PARK_POSITION_START_TS_LOCAL, tgt.PARK_POSITION_END_TS_LOCAL = src.PARK_POSITION_END_TS_LOCAL,
    tgt.LEVEL_START_TS_LOCAL = src.LEVEL_START_TS_LOCAL, tgt.LEVEL_END_TS_LOCAL = src.LEVEL_END_TS_LOCAL,
    tgt.DRILL_START_TS_LOCAL = src.DRILL_START_TS_LOCAL, tgt.DRILL_END_TS_LOCAL = src.DRILL_END_TS_LOCAL,
    tgt.RETRACT_START_TS_LOCAL = src.RETRACT_START_TS_LOCAL, tgt.RETRACT_END_TS_LOCAL = src.RETRACT_END_TS_LOCAL,
    tgt.PLAN_CREATION_TS_LOCAL = src.PLAN_CREATION_TS_LOCAL,
    tgt.DRILL_HOLE_DURATION_SECONDS = src.DRILL_HOLE_DURATION_SECONDS, tgt.AUTODRILL_DURATION_SECONDS = src.AUTODRILL_DURATION_SECONDS,
    tgt.TIME_BETWEEN_DRILL_HOLES_SECONDS = src.TIME_BETWEEN_DRILL_HOLES_SECONDS,
    tgt.SYSTEM_DRILL_STATE_DURATION_SECONDS = src.SYSTEM_DRILL_STATE_DURATION_SECONDS,
    tgt.SYSTEM_SETUP_STATE_DURATION_SECONDS = src.SYSTEM_SETUP_STATE_DURATION_SECONDS,
    tgt.SYSTEM_AUTO_LEVEL_DURATION_SECONDS = src.SYSTEM_AUTO_LEVEL_DURATION_SECONDS,
    tgt.SYSTEM_AUTO_DELEVEL_DURATION_SECONDS = src.SYSTEM_AUTO_DELEVEL_DURATION_SECONDS,
    tgt.PROPEL_DURATION = src.PROPEL_DURATION, tgt.PARK_POSITION_DURATION = src.PARK_POSITION_DURATION,
    tgt.LEVEL_DURATION = src.LEVEL_DURATION, tgt.DRILL_DURATION = src.DRILL_DURATION, tgt.RETRACT_DURATION = src.RETRACT_DURATION,
    tgt.ACTUAL_DRILL_HOLE_DEPTH_FEET = src.ACTUAL_DRILL_HOLE_DEPTH_FEET, tgt.ACTUAL_DRILL_HOLE_DEPTH_METERS = src.ACTUAL_DRILL_HOLE_DEPTH_METERS,
    tgt.ACTUAL_DRILL_HOLE_START_FEET_X = src.ACTUAL_DRILL_HOLE_START_FEET_X, tgt.ACTUAL_DRILL_HOLE_START_FEET_Y = src.ACTUAL_DRILL_HOLE_START_FEET_Y,
    tgt.ACTUAL_DRILL_HOLE_START_FEET_Z = src.ACTUAL_DRILL_HOLE_START_FEET_Z,
    tgt.ACTUAL_DRILL_HOLE_END_FEET_X = src.ACTUAL_DRILL_HOLE_END_FEET_X, tgt.ACTUAL_DRILL_HOLE_END_FEET_Y = src.ACTUAL_DRILL_HOLE_END_FEET_Y,
    tgt.ACTUAL_DRILL_HOLE_END_FEET_Z = src.ACTUAL_DRILL_HOLE_END_FEET_Z,
    tgt.ACTUAL_DRILL_HOLE_START_METERS_X = src.ACTUAL_DRILL_HOLE_START_METERS_X, tgt.ACTUAL_DRILL_HOLE_START_METERS_Y = src.ACTUAL_DRILL_HOLE_START_METERS_Y,
    tgt.ACTUAL_DRILL_HOLE_START_METERS_Z = src.ACTUAL_DRILL_HOLE_START_METERS_Z,
    tgt.ACTUAL_DRILL_HOLE_END_METERS_X = src.ACTUAL_DRILL_HOLE_END_METERS_X, tgt.ACTUAL_DRILL_HOLE_END_METERS_Y = src.ACTUAL_DRILL_HOLE_END_METERS_Y,
    tgt.ACTUAL_DRILL_HOLE_END_METERS_Z = src.ACTUAL_DRILL_HOLE_END_METERS_Z,
    tgt.GPS_ACCURACY = src.GPS_ACCURACY, tgt.ACTUAL_DRILL_HOLE_LONGITUDE = src.ACTUAL_DRILL_HOLE_LONGITUDE,
    tgt.ACTUAL_DRILL_HOLE_LATITUDE = src.ACTUAL_DRILL_HOLE_LATITUDE,
    tgt.AUTODRILL_USAGE_PCT = src.AUTODRILL_USAGE_PCT, tgt.DRILL_HOLE_PENETRATION_RATE_AVG_FEET_HOUR = src.DRILL_HOLE_PENETRATION_RATE_AVG_FEET_HOUR,
    tgt.INSTANTANOUS_PENRATE_MWD_METERS_HOUR = src.INSTANTANOUS_PENRATE_MWD_METERS_HOUR,
    tgt.INSTANTANOUS_PENRATE_MWD_FEET_HOUR = src.INSTANTANOUS_PENRATE_MWD_FEET_HOUR,
    tgt.BEARING = src.BEARING, tgt.DRILL_TOWER_ANGLE_DEGREE_CALCULATED = src.DRILL_TOWER_ANGLE_DEGREE_CALCULATED,
    tgt.DRILL_TOWER_ANGLE_DEGREE_SYSTEM = src.DRILL_TOWER_ANGLE_DEGREE_SYSTEM,
    tgt.DRILL_HOLE_DUPLICATED_FLAG = src.DRILL_HOLE_DUPLICATED_FLAG, tgt.DRILL_HOLE_UPSIDE_DOWN_FLAG = src.DRILL_HOLE_UPSIDE_DOWN_FLAG,
    tgt.DRILL_HOLE_START_END_TIME_INVALID_FLAG = src.DRILL_HOLE_START_END_TIME_INVALID_FLAG,
    tgt.DRILL_HOLE_START_END_TIME_OVERLAP_FLAG = src.DRILL_HOLE_START_END_TIME_OVERLAP_FLAG,
    tgt.DRILL_HOLE_DEPTH_INVALID_FLAG = src.DRILL_HOLE_DEPTH_INVALID_FLAG,
    tgt.DRILL_HOLE_ANGLE_INVALID_FLAG = src.DRILL_HOLE_ANGLE_INVALID_FLAG,
    tgt.DRILL_HOLE_POSITION_INVALID_FLAG = src.DRILL_HOLE_POSITION_INVALID_FLAG,
    tgt.DRILL_HOLE_OFF_TARGET_FEET = src.DRILL_HOLE_OFF_TARGET_FEET, tgt.DRILL_HOLE_OFF_TARGET_METERS = src.DRILL_HOLE_OFF_TARGET_METERS,
    tgt.DRILL_HOLE_HORIZONTAL_ACCURACY_PCT = src.DRILL_HOLE_HORIZONTAL_ACCURACY_PCT,
    tgt.DRILL_HOLE_VERTICAL_ACCURACY_PCT = src.DRILL_HOLE_VERTICAL_ACCURACY_PCT,
    tgt.OVERDRILL_UNDERDRILL_FLAG = src.OVERDRILL_UNDERDRILL_FLAG,
    tgt.OVERDRILL_UNDERDRILL_FEET = src.OVERDRILL_UNDERDRILL_FEET, tgt.OVERDRILL_UNDERDRILL_METERS = src.OVERDRILL_UNDERDRILL_METERS,
    tgt.DRILLING_STOPS_COUNT = src.DRILLING_STOPS_COUNT, tgt.DRILL_HOLE_REDRILL_FLAG = src.DRILL_HOLE_REDRILL_FLAG,
    tgt.AIR_PRESSURE_PSI = src.AIR_PRESSURE_PSI, tgt.FEED_FORCE_NEWTONS = src.FEED_FORCE_NEWTONS,
    tgt.ROTATION_TORQUE_NM = src.ROTATION_TORQUE_NM, tgt.BIT_SPEED_RPM = src.BIT_SPEED_RPM, tgt.WATER_FLOW_GPM = src.WATER_FLOW_GPM,
    tgt.ACTUAL_MCF_BLOCK_ID = src.ACTUAL_MCF_BLOCK_ID, tgt.DESIGN_MCF_BLOCK_ID = src.DESIGN_MCF_BLOCK_ID,
    tgt.SYSTEM_VERSION = src.SYSTEM_VERSION,
    tgt.DW_MODIFY_TS = CURRENT_TIMESTAMP(0)::TIMESTAMP_NTZ

WHEN NOT MATCHED THEN INSERT (
    DRILL_CYCLE_SK, ORIG_SRC_ID, SITE_CODE, BENCH, PUSHBACK, PATTERN_NAME, ORIGINAL_PATTERN_NAME,
    DRILL_HOLE_SHIFT_ID, DRILL_ID, DRILL_BIT_ID, SYSTEM_OPERATOR_ID, DRILL_HOLE_ID, DRILL_HOLE_NAME,
    DRILL_PLAN_SK, DRILL_HOLE_STATUS, IS_HOLE_PLANNED_FLAG,
    START_HOLE_TS_UTC, END_HOLE_TS_UTC, OPERATOR_LOGIN_TS_UTC, OPERATOR_LOGOUT_TS_UTC,
    PROPEL_START_TS_UTC, PROPEL_END_TS_UTC, PARK_POSITION_START_TS_UTC, PARK_POSITION_END_TS_UTC,
    LEVEL_START_TS_UTC, LEVEL_END_TS_UTC, DRILL_START_TS_UTC, DRILL_END_TS_UTC,
    RETRACT_START_TS_UTC, RETRACT_END_TS_UTC,
    START_HOLE_TS_LOCAL, END_HOLE_TS_LOCAL, OPERATOR_LOGIN_TS_LOCAL, OPERATOR_LOGOUT_TS_LOCAL,
    PROPEL_START_TS_LOCAL, PROPEL_END_TS_LOCAL, PARK_POSITION_START_TS_LOCAL, PARK_POSITION_END_TS_LOCAL,
    LEVEL_START_TS_LOCAL, LEVEL_END_TS_LOCAL, DRILL_START_TS_LOCAL, DRILL_END_TS_LOCAL,
    RETRACT_START_TS_LOCAL, RETRACT_END_TS_LOCAL, PLAN_CREATION_TS_LOCAL,
    DRILL_HOLE_DURATION_SECONDS, AUTODRILL_DURATION_SECONDS, TIME_BETWEEN_DRILL_HOLES_SECONDS,
    SYSTEM_DRILL_STATE_DURATION_SECONDS, SYSTEM_SETUP_STATE_DURATION_SECONDS,
    SYSTEM_AUTO_LEVEL_DURATION_SECONDS, SYSTEM_AUTO_DELEVEL_DURATION_SECONDS,
    PROPEL_DURATION, PARK_POSITION_DURATION, LEVEL_DURATION, DRILL_DURATION, RETRACT_DURATION,
    ACTUAL_DRILL_HOLE_DEPTH_FEET, ACTUAL_DRILL_HOLE_DEPTH_METERS,
    ACTUAL_DRILL_HOLE_START_FEET_X, ACTUAL_DRILL_HOLE_START_FEET_Y, ACTUAL_DRILL_HOLE_START_FEET_Z,
    ACTUAL_DRILL_HOLE_END_FEET_X, ACTUAL_DRILL_HOLE_END_FEET_Y, ACTUAL_DRILL_HOLE_END_FEET_Z,
    ACTUAL_DRILL_HOLE_START_METERS_X, ACTUAL_DRILL_HOLE_START_METERS_Y, ACTUAL_DRILL_HOLE_START_METERS_Z,
    ACTUAL_DRILL_HOLE_END_METERS_X, ACTUAL_DRILL_HOLE_END_METERS_Y, ACTUAL_DRILL_HOLE_END_METERS_Z,
    GPS_ACCURACY, ACTUAL_DRILL_HOLE_LONGITUDE, ACTUAL_DRILL_HOLE_LATITUDE,
    AUTODRILL_USAGE_PCT, DRILL_HOLE_PENETRATION_RATE_AVG_FEET_HOUR,
    INSTANTANOUS_PENRATE_MWD_METERS_HOUR, INSTANTANOUS_PENRATE_MWD_FEET_HOUR,
    BEARING, DRILL_TOWER_ANGLE_DEGREE_CALCULATED, DRILL_TOWER_ANGLE_DEGREE_SYSTEM,
    DRILL_HOLE_DUPLICATED_FLAG, DRILL_HOLE_UPSIDE_DOWN_FLAG,
    DRILL_HOLE_START_END_TIME_INVALID_FLAG, DRILL_HOLE_START_END_TIME_OVERLAP_FLAG,
    DRILL_HOLE_DEPTH_INVALID_FLAG, DRILL_HOLE_ANGLE_INVALID_FLAG, DRILL_HOLE_POSITION_INVALID_FLAG,
    DRILL_HOLE_OFF_TARGET_FEET, DRILL_HOLE_OFF_TARGET_METERS,
    DRILL_HOLE_HORIZONTAL_ACCURACY_PCT, DRILL_HOLE_VERTICAL_ACCURACY_PCT,
    OVERDRILL_UNDERDRILL_FLAG, OVERDRILL_UNDERDRILL_FEET, OVERDRILL_UNDERDRILL_METERS,
    DRILLING_STOPS_COUNT, DRILL_HOLE_REDRILL_FLAG,
    AIR_PRESSURE_PSI, FEED_FORCE_NEWTONS, ROTATION_TORQUE_NM, BIT_SPEED_RPM, WATER_FLOW_GPM,
    ACTUAL_MCF_BLOCK_ID, DESIGN_MCF_BLOCK_ID, SYSTEM_VERSION,
    DW_LOGICAL_DELETE_FLAG, DW_LOAD_TS, DW_MODIFY_TS
) VALUES (
    src.DRILL_CYCLE_SK, src.ORIG_SRC_ID, src.SITE_CODE, src.BENCH, src.PUSHBACK, src.PATTERN_NAME, src.ORIGINAL_PATTERN_NAME,
    src.DRILL_HOLE_SHIFT_ID, src.DRILL_ID, src.DRILL_BIT_ID, src.SYSTEM_OPERATOR_ID, src.DRILL_HOLE_ID, src.DRILL_HOLE_NAME,
    src.DRILL_PLAN_SK, src.DRILL_HOLE_STATUS, src.IS_HOLE_PLANNED_FLAG,
    src.START_HOLE_TS_UTC, src.END_HOLE_TS_UTC, src.OPERATOR_LOGIN_TS_UTC, src.OPERATOR_LOGOUT_TS_UTC,
    src.PROPEL_START_TS_UTC, src.PROPEL_END_TS_UTC, src.PARK_POSITION_START_TS_UTC, src.PARK_POSITION_END_TS_UTC,
    src.LEVEL_START_TS_UTC, src.LEVEL_END_TS_UTC, src.DRILL_START_TS_UTC, src.DRILL_END_TS_UTC,
    src.RETRACT_START_TS_UTC, src.RETRACT_END_TS_UTC,
    src.START_HOLE_TS_LOCAL, src.END_HOLE_TS_LOCAL, src.OPERATOR_LOGIN_TS_LOCAL, src.OPERATOR_LOGOUT_TS_LOCAL,
    src.PROPEL_START_TS_LOCAL, src.PROPEL_END_TS_LOCAL, src.PARK_POSITION_START_TS_LOCAL, src.PARK_POSITION_END_TS_LOCAL,
    src.LEVEL_START_TS_LOCAL, src.LEVEL_END_TS_LOCAL, src.DRILL_START_TS_LOCAL, src.DRILL_END_TS_LOCAL,
    src.RETRACT_START_TS_LOCAL, src.RETRACT_END_TS_LOCAL, src.PLAN_CREATION_TS_LOCAL,
    src.DRILL_HOLE_DURATION_SECONDS, src.AUTODRILL_DURATION_SECONDS, src.TIME_BETWEEN_DRILL_HOLES_SECONDS,
    src.SYSTEM_DRILL_STATE_DURATION_SECONDS, src.SYSTEM_SETUP_STATE_DURATION_SECONDS,
    src.SYSTEM_AUTO_LEVEL_DURATION_SECONDS, src.SYSTEM_AUTO_DELEVEL_DURATION_SECONDS,
    src.PROPEL_DURATION, src.PARK_POSITION_DURATION, src.LEVEL_DURATION, src.DRILL_DURATION, src.RETRACT_DURATION,
    src.ACTUAL_DRILL_HOLE_DEPTH_FEET, src.ACTUAL_DRILL_HOLE_DEPTH_METERS,
    src.ACTUAL_DRILL_HOLE_START_FEET_X, src.ACTUAL_DRILL_HOLE_START_FEET_Y, src.ACTUAL_DRILL_HOLE_START_FEET_Z,
    src.ACTUAL_DRILL_HOLE_END_FEET_X, src.ACTUAL_DRILL_HOLE_END_FEET_Y, src.ACTUAL_DRILL_HOLE_END_FEET_Z,
    src.ACTUAL_DRILL_HOLE_START_METERS_X, src.ACTUAL_DRILL_HOLE_START_METERS_Y, src.ACTUAL_DRILL_HOLE_START_METERS_Z,
    src.ACTUAL_DRILL_HOLE_END_METERS_X, src.ACTUAL_DRILL_HOLE_END_METERS_Y, src.ACTUAL_DRILL_HOLE_END_METERS_Z,
    src.GPS_ACCURACY, src.ACTUAL_DRILL_HOLE_LONGITUDE, src.ACTUAL_DRILL_HOLE_LATITUDE,
    src.AUTODRILL_USAGE_PCT, src.DRILL_HOLE_PENETRATION_RATE_AVG_FEET_HOUR,
    src.INSTANTANOUS_PENRATE_MWD_METERS_HOUR, src.INSTANTANOUS_PENRATE_MWD_FEET_HOUR,
    src.BEARING, src.DRILL_TOWER_ANGLE_DEGREE_CALCULATED, src.DRILL_TOWER_ANGLE_DEGREE_SYSTEM,
    src.DRILL_HOLE_DUPLICATED_FLAG, src.DRILL_HOLE_UPSIDE_DOWN_FLAG,
    src.DRILL_HOLE_START_END_TIME_INVALID_FLAG, src.DRILL_HOLE_START_END_TIME_OVERLAP_FLAG,
    src.DRILL_HOLE_DEPTH_INVALID_FLAG, src.DRILL_HOLE_ANGLE_INVALID_FLAG, src.DRILL_HOLE_POSITION_INVALID_FLAG,
    src.DRILL_HOLE_OFF_TARGET_FEET, src.DRILL_HOLE_OFF_TARGET_METERS,
    src.DRILL_HOLE_HORIZONTAL_ACCURACY_PCT, src.DRILL_HOLE_VERTICAL_ACCURACY_PCT,
    src.OVERDRILL_UNDERDRILL_FLAG, src.OVERDRILL_UNDERDRILL_FEET, src.OVERDRILL_UNDERDRILL_METERS,
    src.DRILLING_STOPS_COUNT, src.DRILL_HOLE_REDRILL_FLAG,
    src.AIR_PRESSURE_PSI, src.FEED_FORCE_NEWTONS, src.ROTATION_TORQUE_NM, src.BIT_SPEED_RPM, src.WATER_FLOW_GPM,
    src.ACTUAL_MCF_BLOCK_ID, src.DESIGN_MCF_BLOCK_ID, src.SYSTEM_VERSION,
    src.dw_logical_delete_flag_new, src.dw_load_ts_new, CURRENT_TIMESTAMP(0)::TIMESTAMP_NTZ
);`;

sql_delete = `UPDATE {{ envi }}_API_REF.fuse.drill_cycle_incr tgt
              SET dw_logical_delete_flag = ''Y'', dw_modify_ts = CURRENT_TIMESTAMP(0)::TIMESTAMP_NTZ
              WHERE tgt.dw_logical_delete_flag = ''N''
              AND NOT EXISTS (SELECT 1 FROM {{ RO_PROD }}_WG.DRILL_BLAST.DRILL_CYCLE src
                  WHERE src.DRILL_CYCLE_SK = tgt.DRILL_CYCLE_SK);`;

try {
    snowflake.execute({sqlText: "BEGIN WORK;"});
    rs_count_incr = snowflake.execute({sqlText: sql_count_incr});
    rs_count_incr.next();
    rs_records_incr = rs_count_incr.getColumnValue(''COUNT_CHECK_1'');
    rs_deleted_records_incr = rs_records_incr > 0 ? snowflake.execute({sqlText: sql_delete_incr}).getNumRowsAffected() : 0;
    rs_merge = snowflake.execute({sqlText: sql_merge});
    rs_merged_records = rs_merge.getNumRowsAffected();
    rs_delete = snowflake.execute({sqlText: sql_delete});
    rs_delete_records = rs_delete.getNumRowsAffected();
    sp_result = "Deleted: " + rs_deleted_records_incr + ", Merged: " + rs_merged_records + ", Archived: " + rs_delete_records;
    snowflake.execute({sqlText: "COMMIT WORK;"});
    return sp_result;
} catch (err) { snowflake.execute({sqlText: "ROLLBACK WORK;"}); throw err; }
';

