CREATE VIEW [dbo].[BLAST_FACT] AS


CREATE   view [dbo].[BLAST_FACT] as 

SELECT
    A.ID, 
    A.NAME,
    A.STATUS,
    CAST(A.FIREDTIME AS DATE) AS BLAST_DATE,
    A.HOLECOUNT AS ACTUAL_HOLE_COUNT,
    CAST(B.PLANNEDDATE AS DATE) AS PLANNED_BLAST_DATE,
    CASE 
        WHEN CAST(A.FIREDTIME AS DATE) = CAST(B.PLANNEDDATE AS DATE) THEN 1
        ELSE 0
    END AS BLAST_DATE_COMPLIANCE,
    A.VOLUME,
    (A.VOLUME * 35.3146667 * 165) / 2000 AS TONS_PER_SHOT,
    COUNT(*) AS pattern_planned_hole_count
FROM DBO.BL_DW_BLAST A
LEFT JOIN DBO.BL_DW_BLASTPROPERTYVALUE B
    ON A.ID = B.BLASTID

LEFT JOIN DBO.DRILL_PLAN DP
    ON A.NAME = dp.PATTERN_NAME
GROUP BY 
    A.ID, A.NAME, A.STATUS, CAST(A.FIREDTIME AS DATE), A.HOLECOUNT, CAST(B.PLANNEDDATE AS DATE), A.VOLUME;
