CREATE TABLE [dbo].[BLAST_PRODUCT] (
    [ORIG_SRC_ID] bigint NOT NULL,
    [SITE_CODE] varchar(50) NOT NULL,
    [ID] int NOT NULL,
    [TYPE_ID] decimal(3,0) NULL,
    [TYPE_NAME] varchar NULL,
    [NAME] varchar(200) NULL,
    [DESCRIPTION] varchar NULL,
    [CODE] varchar(5) NULL,
    [ACTIVE] bit NULL,
    [COLOUR] varchar NULL,
    [REVISION_ID] int NULL,
    [DENSITY] float NULL,
    [ENERGY_DENSITY] float NULL,
    [DETONATION_VELOCITY_MIN] float NULL,
    [DETONATION_VELOCITY_MAX] float NULL,
    [MASS] float NULL,
    [LENGTH] float NULL,
    [DIAMETER] float NULL,
    [SYMBOL] varchar NULL,
    [PROPAGATION_RATE] float NULL,
    [CORE_LOAD] float NULL,
    [FAMILY_ID] int NULL,
    [FAMILY_NAME] varchar(200) NULL,
    [FAMILY_DESCRIPTION] varchar NULL,
    [DELAY] float NULL,
    [INVENTORY_UNITS] decimal(3,0) NULL,
    [SHORT_NAME] varchar(5) NULL,
    [MAXIMUM_CHANNELS] int NULL,
    [MAXIMUM_DETONATORS] int NULL,
    [MAXIMUM_WIRE_LENGTH] float NULL,
    [MAXIMUM_LEAD_LENGTH] float NULL,
    [INITIATION_SYSTEM] varchar(100) NULL,
    [MAXIMUM_DETONATORS_PER_BLAST] int NULL,
    [DENSITY_TABLE] varchar NULL,
    [DETONATOR_TYPE] varchar(100) NULL,
    [LOGGER_TYPE] varchar(100) NULL,
    [BLASTER_TYPE] varchar(100) NULL,
    [MAXIMUM_DETONATORS_PER_LOGGER] int NULL,
    [ROLL_LENGTH] float NULL,
    [COST] decimal(15,5) NULL,
    [DENSITY_LOWER_TOLERANCE] float NULL,
    [DENSITY_UPPER_TOLERANCE] float NULL,
    [INTEGRATION_ID] varchar(100) NULL,
    [DW_DML_TYPE] varchar(1) NULL,
    [DW_LOGICAL_DELETE_FLAG] varchar(1) NULL,
    [DW_MODIFY_TS] datetime2 NULL,
    [DW_LOAD_TS] datetime2 NULL,
    [DW_FILE_TS_UTC] datetime2 NULL
);