CREATE TABLE [dbo].[DRILLBLAST_STATUS_EVENT_REASON] (
    [ORIG_SRC_ID] bigint NULL,
    [SITE_CODE] varchar(4) NOT NULL,
    [STATUS_EVENT_REASON_ID] bigint NOT NULL,
    [STATUS_EVENT_REASON_CODE] varchar(254) NULL,
    [STATUS_EVENT_REASON_NAME] varchar(30) NULL,
    [EXPECTED_DURATION_MINS] decimal(38,6) NULL,
    [TIME_CATEGORY_CODE] bigint NULL,
    [TIME_CATEGORY] varchar(256) NULL,
    [TIME_CATEGORY_1] varchar(256) NULL,
    [TIME_CATEGORY_2] varchar(256) NULL,
    [MAINT_EVENT_FLAG] bit NULL,
    [UNPLANNED_MAINT_FLAG] bit NULL,
    [PLANNED_MAINT_FLAG] bit NULL,
    [OPER_EVENT_FLAG] bit NULL,
    [SYSTEM_VERSION] varchar(50) NULL,
    [DW_LOAD_TS] datetime2 NULL,
    [DW_MODIFY_TS] datetime2 NULL
);