CREATE TABLE [dbo].[FR_BLAST_VIDEO] (
    [ORIG_SRC_ID] bigint NULL,
    [BLAST_VIDEO_ID] bigint NULL,
    [BLAST_DESIGN_ID] bigint NULL,
    [URL] varchar NULL,
    [OVERBREAK] varchar(20) NULL,
    [FLYROCK] varchar(20) NULL,
    [RELIEF] varchar(20) NULL,
    [FUMES] varchar(20) NULL,
    [PROBLEMHOLE] bit NULL,
    [LIVEHOLE] bit NULL,
    [RADARSLOPEMOVEMENT] bit NULL,
    [FAULTSPRESENT] bit NULL,
    [COMMENTS] varchar(100) NULL,
    [CREATEDBY] varchar(50) NULL,
    [CREATEDONUTC] datetime NULL,
    [MODIFIEDBY] varchar(50) NULL,
    [MODIFIEDONUTC] datetime NULL,
    [ISDELETED] bit NULL,
    [NOTAVAILABLE] bit NULL,
    [DW_LOGICAL_DELETE_FLAG] varchar(1) NULL,
    [DW_MODIFY_TS] datetimeoffset NULL,
    [DW_LOAD_TS] datetimeoffset NULL
);