CREATE TABLE [dbo].[FRG_BLOCK_MODEL_BLOCK] (
    [ORIG_SRC_ID] int NULL,
    [SITE_CODE] varchar(5) NOT NULL,
    [CENTROID_X] decimal(10,1) NOT NULL,
    [CENTROID_Y] decimal(10,1) NOT NULL,
    [CENTROID_Z] decimal(10,1) NOT NULL,
    [BLOCK_SK] bigint NULL,
    [FAULT_CODE] decimal(10,1) NULL,
    [RQD] decimal(10,1) NULL,
    [P80] decimal(10,1) NULL,
    [TOP_SIZE] decimal(10,1) NULL,
    [DRILL_PEN_RATE] decimal(10,1) NULL,
    [ROCK_TYPE] decimal(10,1) NULL,
    [QKP_PCT] decimal(10,1) NULL,
    [MUSCOVITE_PCT] decimal(10,1) NULL,
    [SWELLING_CLAY_PCT] decimal(10,1) NULL,
    [TCLAY_PCT] decimal(10,1) NULL,
    [BIOTITE_PCT] decimal(10,1) NULL,
    [CHLORITE_PCT] decimal(10,1) NULL,
    [PREDICTED_P80_FRAG] decimal(10,1) NULL,
    [FRAG_INDEX] decimal(10,1) NULL,
    [BLAST_ENERGY] decimal(10,1) NULL,
    [HARDNESS] decimal(10,1) NULL,
    [FILE_NAME] varchar(500) NULL,
    [DW_LOGICAL_DELETE_FLAG] varchar(1) NULL,
    [DW_MODIFY_TS] datetime NULL,
    [DW_LOAD_TS] datetime NULL
);