
    
/******************************************************************        
* PROCEDURE : BAG2.[UPSERT_CONOPS_DELAY_FULL]      
* PURPOSE : UPSERT [UPSERT_CONOPS_DELAY_FULL]      
* NOTES     :       
* CREATED : MFAHMI      
* SAMPLE    : 
* 1. EXEC BAG2.[UPSERT_CONOPS_DELAY_FULL] 'BAG2' ,'FULL', 0  
* 2. EXEC BAG2.[UPSERT_CONOPS_DELAY_FULL] 'BAG2' ,'SHIFT', 1      
* MODIFIED DATE  AUTHOR    DESCRIPTION        
*------------------------------------------------------------------        
* {19 MAR 2023}  {MFAHMI}   {INITIAL CREATED}        
*******************************************************************/        
CREATE  PROCEDURE [bag2].[UPSERT_CONOPS_DELAY_FULL]       
(          
@G_SITE VARCHAR(5),  
@G_ExtractMode VARCHAR(5),  
@G_LasfShift NUMERIC(10)   
  
)          
AS          
BEGIN     
  
DECLARE @G_SITE_ALIAS VARCHAR(5)      
SET @G_SITE_ALIAS = CASE WHEN @G_SITE = 'CLI' THEN 'CMX' WHEN @G_SITE ='BAG2' THEN 'BAG' ELSE @G_SITE END      
  
IF @G_ExtractMode = 'FULL'   
  
BEGIN   
EXEC       
(      
'MERGE ' +@G_SITE+ '.DELAY AS T '      
+' USING (SELECT '       
+' ''' +@G_SITE_ALIAS+ ''' AS SITEFLAG'   
+' ,DELAY_OID'
+' ,ECF_CLASS_ID'
+' ,ACKNOWLEDGE'
+' ,ACKNOWLEDGED'
+' ,CONFIRMED'
+' ,FREQUENCY_TYPE'
+' ,SHIFT_TYPE'
+' ,DELAYCLASS'
+' ,TARGET_MACHINE'
+' ,TARGET_ROAD'
+' ,TARGET_LOCATION'
+' ,DESCRIPTION'
+' ,FINISH_UTC'
+' ,OFFICECONFIRM'
+' ,REPORTEDBY_PERSON'
+' ,REPORTEDBY_USER'
+' ,START1_UTC'
+' ,STATUS'
+' ,PRODUCTIONREPORTINGONLY'
+' ,FIELDNOTIFICATIONREQUIRED'
+' ,ENGINESTOPPED'
+' ,WORKORDER_REF'
+' ,SOURCE_SYSTEM'
+' ,LAST_MODIFIED_UTC'
+' ,CREATED_DATE_UTC'
+' ,ENDEDBY_PERSON'
+' ,ENDEDBY_USER'
+' ,GETUTCDATE() AS UTC_CREATED_DATE'
+' FROM ' +@G_SITE+ '.[DELAY_STAGE_FULL] '  
+' ) AS S '       
+' ON (T.DELAY_OID = S.DELAY_OID AND T.SITEFLAG = S.SITEFLAG) '       
+' WHEN MATCHED '       
+' THEN UPDATE SET '       
+' T.ECF_CLASS_ID = S.ECF_CLASS_ID'
+' ,T.ACKNOWLEDGE = S.ACKNOWLEDGE'
+' ,T.ACKNOWLEDGED = S.ACKNOWLEDGED'
+' ,T.CONFIRMED = S.CONFIRMED'
+' ,T.FREQUENCY_TYPE = S.FREQUENCY_TYPE'
+' ,T.SHIFT_TYPE = S.SHIFT_TYPE'
+' ,T.DELAYCLASS = S.DELAYCLASS'
+' ,T.TARGET_MACHINE = S.TARGET_MACHINE'
+' ,T.TARGET_ROAD = S.TARGET_ROAD'
+' ,T.TARGET_LOCATION = S.TARGET_LOCATION'
+' ,T.DESCRIPTION = S.DESCRIPTION'
+' ,T.FINISH_UTC = S.FINISH_UTC'
+' ,T.OFFICECONFIRM = S.OFFICECONFIRM'
+' ,T.REPORTEDBY_PERSON = S.REPORTEDBY_PERSON'
+' ,T.REPORTEDBY_USER = S.REPORTEDBY_USER'
+' ,T.START1_UTC = S.START1_UTC'
+' ,T.STATUS = S.STATUS'
+' ,T.PRODUCTIONREPORTINGONLY = S.PRODUCTIONREPORTINGONLY'
+' ,T.FIELDNOTIFICATIONREQUIRED = S.FIELDNOTIFICATIONREQUIRED'
+' ,T.ENGINESTOPPED = S.ENGINESTOPPED'
+' ,T.WORKORDER_REF = S.WORKORDER_REF'
+' ,T.SOURCE_SYSTEM = S.SOURCE_SYSTEM'
+' ,T.LAST_MODIFIED_UTC = S.LAST_MODIFIED_UTC'
+' ,T.CREATED_DATE_UTC = S.CREATED_DATE_UTC'
+' ,T.ENDEDBY_PERSON = S.ENDEDBY_PERSON'
+' ,T.ENDEDBY_USER = S.ENDEDBY_USER'
+' ,T.UTC_CREATED_DATE = S.UTC_CREATED_DATE '           
+' WHEN NOT MATCHED '       
+' THEN INSERT ( '       
+' SITEFLAG'
+' ,DELAY_OID'
+' ,ECF_CLASS_ID'
+' ,ACKNOWLEDGE'
+' ,ACKNOWLEDGED'
+' ,CONFIRMED'
+' ,FREQUENCY_TYPE'
+' ,SHIFT_TYPE'
+' ,DELAYCLASS'
+' ,TARGET_MACHINE'
+' ,TARGET_ROAD'
+' ,TARGET_LOCATION'
+' ,DESCRIPTION'
+' ,FINISH_UTC'
+' ,OFFICECONFIRM'
+' ,REPORTEDBY_PERSON'
+' ,REPORTEDBY_USER'
+' ,START1_UTC'
+' ,STATUS'
+' ,PRODUCTIONREPORTINGONLY'
+' ,FIELDNOTIFICATIONREQUIRED'
+' ,ENGINESTOPPED'
+' ,WORKORDER_REF'
+' ,SOURCE_SYSTEM'
+' ,LAST_MODIFIED_UTC'
+' ,CREATED_DATE_UTC'
+' ,ENDEDBY_PERSON'
+' ,ENDEDBY_USER'
+' ,UTC_CREATED_DATE'     
+'  ) VALUES( '       
+' S.SITEFLAG'
+' ,S.DELAY_OID'
+' ,S.ECF_CLASS_ID'
+' ,S.ACKNOWLEDGE'
+' ,S.ACKNOWLEDGED'
+' ,S.CONFIRMED'
+' ,S.FREQUENCY_TYPE'
+' ,S.SHIFT_TYPE'
+' ,S.DELAYCLASS'
+' ,S.TARGET_MACHINE'
+' ,S.TARGET_ROAD'
+' ,S.TARGET_LOCATION'
+' ,S.DESCRIPTION'
