
  
    
    
    
/******************************************************************        
* PROCEDURE : BAG2.[UPSERT_CONOPS_MACHINE]      
* PURPOSE : UPSERT [UPSERT_CONOPS_MACHINE]      
* NOTES     :       
* CREATED : MFAHMI      
* SAMPLE    : EXEC BAG2.[UPSERT_CONOPS_MACHINE] 'BAG2'       
* MODIFIED DATE  AUTHOR    DESCRIPTION        
*------------------------------------------------------------------        
* {04 SEP 2024}  {MFAHMI}   {INITIAL CREATED}        
*******************************************************************/        
CREATE  PROCEDURE [bag2].[UPSERT_CONOPS_MACHINE]       
(      
@G_SITE VARCHAR(5)      
)      
AS      
BEGIN   
DECLARE @G_SITE_ALIAS VARCHAR(5)  
  
SET @G_SITE_ALIAS = CASE WHEN @G_SITE = 'CLI' THEN 'CMX' WHEN @G_SITE ='BAG2' THEN 'BAG' ELSE @G_SITE END  
EXEC       
(      
'MERGE ' +@G_SITE+ '.MACHINE AS T '      
+' USING (SELECT '       
+' ''' +@G_SITE_ALIAS+ ''' AS SITEFLAG'   
+' ,MACHINE_OID'
+' ,ECF_CLASS_ID'
+' ,IS_ACTIVE'
+' ,NAME'
+' ,SERIALNUMBER'
+' ,EXTERNALREF'
+' ,EXTERNALDESC'
+' ,CLASS'
+' ,ID'
+' ,IGNOREFORASSIGNMENT'
+' ,NONPRODUCTION'
+' ,EXCLUDEFROMOPERATORALLOCATION'
+' ,EXCLUDEFROMTRANSPORTALLOCATION'
+' ,PRODUCTIVITY'
+' ,USEDYNAMICPRODUCTIVITY'
+' ,ANTENNA_OVERRIDE'
+' ,ANTENNA_X'
+' ,ANTENNA_Y'
+' ,ANTENNA_Z'
+' ,USECLASSFUELLEVELS'
+' ,USECLASSBURNRATES'
+' ,USECLASSREFUELING'
+' ,USECLASSCAPABILITIES'
+' ,FUELCAPACITY'
+' ,FUELTYPE'
+' ,MINIMUMREFUELAMOUNT'
+' ,REFUELLEVEL'
+' ,CRITICALFUELLEVEL'
+' ,EXPECTEDDURATIONBETWEENREFUELS'
+' ,CURRENTFUELLEVEL'
+' ,CURRENTFUELSTATUS'
+' ,LASTFUELSTATUSUPDATETIME_UTC'
+' ,LASTFUELLEVELUPDATETIME_UTC'
+' ,LASTREFUELTIME_UTC'
+' ,LASTREFUELQUANTITY'
+' ,LASTREFUELESTIMATE'
+' ,LASTDURATIONBETWEENREFUELINGS'
+' ,USEDYNAMICFUELBURNRATE'
+' ,FUELBURNALGORITHM'
+' ,IDLEFUELBURNRATE'
+' ,WORKINGFUELBURNRATE'
+' ,IGNORE_VIMS_FUEL_SENSOR'
+' ,SHIFTCHANGEGROUP'
+' ,SHIFTCHANGE_LOCATION'
+' ,SHIFTCHANGE_LOADINGTOOL'
+' ,HAS_ONBOARD_HARDWARE'
+' ,HEALTH_PLATFORM'
+' ,OFFICEBADGPS'
+' ,AUTO_REFUEL'
+' ,DEFAULTLOCATION'
+' ,REFUELWINDOW'
+' ,REFUELLOADSTATE'
+' ,REFUELASSIGNDELAY'
+' ,REFUELARRIVEDELAY'
+' ,TRAVELEMPTYFUELBURNRATE'
+' ,TRAVELFULLFUELBURNRATE'
+' ,RECORDNOMINALNOTACTUALPAYLOAD'
+' ,TKPHRATE'
+' ,USECLASSTYRES'
+' ,TKPHMAXPERCENT'
+' ,FRONTTYRETREAD'
+' ,USECLASSPAYLOAD'
+' ,MAXPAYLOAD'
+' ,NOMINALPAYLOAD'
+' ,PAYLOADACCURACY'
+' ,OVERLOAD'
+' ,UNDERLOAD'
+' ,HEAPEDCAPACITY'
+' ,STRUCKCAPACITY'
+' ,REARDISTRIBUTIONEMPTY'
+' ,REARDISTRIBUTIONLOADED'
+' ,FRONTDISTRIBUTIONEMPTY'
+' ,FRONTDISTRIBUTIONLOADED'
+' ,OPERATINGMODE'
+' ,DEFAULTMATERIAL'
+' ,IGNORESASSIGNMATERIAL'
+' ,SKIPSTARTLOADINGASSGN'
+' ,USEPREDICTEDMATERIAL'
+' ,ASSIGNONMATERIALCHANGE'
+' ,USEGRADEPROCESSOR'
+' ,ASSIGNABILITY'
+' ,TRUCKSATATIME'
+' ,RATE'
+' ,STATIONARY'
+' ,MACHINESATATIME'
+' ,MAXQUEUESIZE'
+' ,PORT_NUM'
+' ,IP_ADDRESS'
+' ,TPSPORT'
+' ,TPSHOST'
+' ,LATEST'
+' ,LATESTMESSAGETIME_UTC'
+' ,LATESTERROR'
+' ,LATESTERRORTIME_UTC'
+' ,LATESTERRORMESG'
+' ,OVERRIDE_CLASS_CABLE_LENGTH'
+' ,ELECTRIC_CABLE_LENGTH'
+' ,MAX_HOLE_DEPTH'
+' ,AVAILABLE_FOR_TELEREMOTE'
+' ,TURNING_CIRCLE'
+' ,TRAM_SPEED'
+' ,LOAD_PLAN_OID'
+' ,MATERIAL'
+' ,CHUTE_TOTAL_CAPACITY'
+' ,MODEL_UPDATE_VERSION'
+' ,USELOADERPAYLOAD'
+' ,USECLASSTRUCKTIMES'
+' ,LAYER_UPDATE_VERSION'
+' ,ASSIGNFOROBSTACLECLEARING'
+' ,USE_VIMS_TKPH_INFO'
+' ,USE_DIESEL_EXHAUST_FLUID'
+' ,DIESEL_EXHAUST_FLUID_CAPACITY'
+' ,CURRENT_DEF_LEVEL'
+' ,AIMS_ID'
+' ,WARNING_DEF_LEVEL'
+' ,CRITICAL_DEF_LEVEL'
+' ,DATA_BRIDGE_REF'
+' ,ENDPOINT_ID'
+' ,ACTIVE_LATENCY_SECS'
+' ,INACTIVE_LATENCY_SECS'
+' ,NORMAL_FLOW_LATENCY_SECS'
+' ,CEASE_FLOW_LATENCY_SECS'
+' ,IS_CRUSHER'
+' ,HAS_ROCK_BREAKER'
+' ,OVER_SIZE_DETECTION'
+' ,WEIGH_BRIDGE'
+' ,ALLOW_ON_TRAFFIC'
+' ,PSEUDOLITE_ID'
+' ,STOP_REQUIRED'
+' ,SIMULTANEOUS_DUMPING'
+' ,INPUT_MASS_F