
  
    
    
    
/******************************************************************        
* PROCEDURE : BAG2.[UPSERT_CONOPS_MACHINECLASS]      
* PURPOSE : UPSERT [UPSERT_CONOPS_MACHINECLASS]      
* NOTES     :       
* CREATED : MFAHMI      
* SAMPLE    : EXEC BAG2.[UPSERT_CONOPS_MACHINECLASS] 'BAG2'       
* MODIFIED DATE  AUTHOR    DESCRIPTION        
*------------------------------------------------------------------        
* {04 SEP 2024}  {MFAHMI}   {INITIAL CREATED}        
*******************************************************************/        
CREATE  PROCEDURE [bag2].[UPSERT_CONOPS_MACHINECLASS]       
(      
@G_SITE VARCHAR(5)      
)      
AS      
BEGIN   
DECLARE @G_SITE_ALIAS VARCHAR(5)  
  
SET @G_SITE_ALIAS = CASE WHEN @G_SITE = 'CLI' THEN 'CMX' WHEN @G_SITE ='BAG2' THEN 'BAG' ELSE @G_SITE END  
EXEC       
(      
'MERGE ' +@G_SITE+ '.MACHINECLASS AS T '      
+' USING (SELECT '       
+' ''' +@G_SITE_ALIAS+ ''' AS SITEFLAG'   
+' ,MACHINECLASS_OID'
+' ,ECF_CLASS_ID'
+' ,IS_ACTIVE'
+' ,NAME'
+' ,MANUFACTURER'
+' ,DESCRIPTION'
+' ,USEFUEL'
+' ,FUELCAPACITY'
+' ,ALLOWALLMATERIALS'
+' ,FUELTYPE'
+' ,MINIMUMREFUELAMOUNT'
+' ,REFUELLEVEL'
+' ,CRITICALFUELLEVEL'
+' ,EXPECTEDDURATIONBETWEENREFUELS'
+' ,USEDYNAMICFUELBURNRATE'
+' ,FUELBURNALGORITHM'
+' ,IDLEFUELBURNRATE'
+' ,WORKINGFUELBURNRATE'
+' ,IGNORE_VIMS_FUEL_SENSOR'
+' ,AUTO_STOP_DELAY_TYPE'
+' ,CATEGORY'
+' ,ONBOARD_PLATFORM_ID'
+' ,CONFIGURATION_NAME'
+' ,OPERATOR_INTERFACE'
+' ,CAMERAS'
+' ,CAMERAS_AND_RADAR'
+' ,PROXIMITY_AWARENESS'
+' ,CUSTOM_CONFIGURATION'
+' ,HEALTH_PLATFORM'
+' ,CANBETOWED'
+' ,INFRASTRUCTURE'
+' ,MAXIMUMSPEED'
+' ,BODYWEIGHT'
+' ,CHASSISWEIGHT'
+' ,DUMPHEIGHT'
+' ,FRONTDISTRIBUTIONEMPTY'
+' ,FRONTDISTRIBUTIONLOADED'
+' ,FRONTTYRETREAD'
+' ,GROSSVEHICLEWEIGHT'
+' ,HEAPEDCAPACITY'
+' ,HEIGHTTOCANOPYROCKGUARDRAIL'
+' ,LOADINGHEIGHT'
+' ,MAXPAYLOAD'
+' ,MAXSPEEDLOADED'
+' ,NOMINALPAYLOAD'
+' ,OVERLOAD'
+' ,PAYLOADACCURACY'
+' ,PAYLOADWITHSTDLINEARWEIGHT'
+' ,PRODMANSYSMOD'
+' ,REARDISTRIBUTIONEMPTY'
+' ,REARDISTRIBUTIONLOADED'
+' ,STANDARDLINEARWEIGHT'
+' ,STRUCKCAPACITY'
+' ,UNDERLOAD'
+' ,WHEELBASE'
+' ,AVGSPEEDLOADED'
+' ,AVGSPEEDEMPTY'
+' ,GRADEBLOCK_UPDATABLE'
+' ,REFUELWINDOW'
+' ,REFUELLOADSTATE'
+' ,REFUELASSIGNDELAY'
+' ,REFUELARRIVEDELAY'
+' ,TRAVELEMPTYFUELBURNRATE'
+' ,TRAVELFULLFUELBURNRATE'
+' ,TKPHLOWESTRATE'
+' ,TKPHMAXPERCENT'
+' ,DIPPERCAPACITY'
+' ,DIPPERLOADCAPACITY'
+' ,LOWERHCTEMPTY'
+' ,DUMPHCTLOADED'
+' ,WIDTHOVERTYRES'
+' ,HYDRAULICTANKCAPACITY'
+' ,TREADWIDTH'
+' ,GROUNDCLEARANCE'
+' ,HYDRAULICSYSTEMCAPACITY'
+' ,TOTALHCT'
+' ,RAISEHCTLOADED'
+' ,CCWSLEWLIMIT'
+' ,CWSLEWLIMIT'
+' ,REACHRADIUS'
+' ,SLEWRATELOADED'
+' ,SLEWRATEUNLOADED'
+' ,ENGINE_TYPE'
+' ,ELECTRIC_CABLE_LENGTH'
+' ,MAX_HOLE_DEPTH'
+' ,AUTONOMY_CAPABLE'
+' ,TELEREMOTE_CAPABLE'
+' ,TURNING_CIRCLE'
+' ,TRAM_SPEED'
+' ,EXTERNALREF'
+' ,EXTERNALDESC'
+' ,USELOADERPAYLOAD'
+' ,MAXARTICULATION'
+' ,PATHPLAN_VEHICLE_CONFIG'
+' ,PATHPLAN_ADDL_WIDTH'
+' ,LAYER_UPDATE_VERSION'
+' ,USE_DIESEL_EXHAUST_FLUID'
+' ,DIESEL_EXHAUST_FLUID_CAPACITY'
+' ,BIN_LOCATION_OFFSET'
+' ,WARNING_DEF_LEVEL'
+' ,CRITICAL_DEF_LEVEL'
+' ,IS_CRUSHER'
+' ,HAS_ROCK_BREAKER'
+' ,ADDL_NARROW_AREA_TEMPLATE_WIDTH'
+' ,GETUTCDATE() AS UTC_CREATED_DATE'
+' FROM ' +@G_SITE+ '.[VIEW_MACHINECLASS_ETL] '  
+' ) AS S '       
+' ON (T.MACHINECLASS_OID = S.MACHINECLASS_OID AND T.SITEFLAG = S.SITEFLAG) '       
+' WHEN MATCHED '       
+' THEN UPDATE SET '       
+' T.ECF_CLASS_ID = S.ECF_CLASS_ID'
+' ,T.IS_ACTIVE = S.IS_ACTIVE'
+' ,T.NAME = S.NAME'
+' ,T.MANUFACTURER = S.MANUFACTURER'
+' ,T.DESCRIPTION = S.DESCRIPTION'
+' ,T.USEFUEL = S.USEFUEL'
+' ,T.FUELCAPACITY = S.FUELCAPACITY'
+' ,T.ALLOWALLMATERIALS = S.ALLOWALLMATERIALS'
+' ,T.FUELTYPE = S.FUELTYPE'
+' ,T.MINIMUMREFUELAMOUNT = S.MINIMUMREFUELAMOUNT'
+' ,T.REFUELLEVEL = S.REFUELL