CREATE TABLE [CLI].[PIT_WORKER] (
    [DBPREVIOUS] decimal(19,0) NULL,
    [DBNEXT] decimal(19,0) NULL,
    [DBVERSION] int NULL,
    [ID] decimal(19,0) NOT NULL,
    [DBNAME] varchar(32) NOT NULL,
    [DBKEY] decimal(19,0) NOT NULL,
    [FIELDID] varchar(20) NULL,
    [FIELDNUMER] int NULL,
    [FIELDSHIFTS] int NULL,
    [FIELDSTATUS] decimal(19,0) NULL,
    [FIELDLINEUPCREW] decimal(19,0) NULL,
    [FIELDCREW] decimal(19,0) NULL,
    [FIELDDEPT] decimal(19,0) NULL,
    [FIELDNAME] varchar(40) NULL,
    [FIELDSENIORITY] varchar(7) NULL,
    [FIELDREGIONLOCK] decimal(19,0) NULL,
    [FIELDLOC] decimal(19,0) NULL,
    [FIELDLOCTIME] decimal(19,0) NULL,
    [FIELDROSTER] decimal(19,0) NULL,
    [FIELDROSTERHIST] decimal(19,0) NULL,
    [FIELDLOGINCREW] decimal(19,0) NULL,
    [FIELDFATGMODE] decimal(19,0) NULL,
    [FIELDFATGWARNTYPE] decimal(19,0) NULL,
    [FIELDFATGWARNPASSED] int NULL,
    [FIELDNEXTFATGWARNDUE] decimal(19,0) NULL,
    [FIELDFATGWARNSENT] decimal(19,0) NULL,
    [FIELDFATGRESPEXPTD] varchar(5) NULL,
    [FIELDFATGDDBLINK] varchar(12) NULL,
    [FIELDAREA] int NULL,
    [FIELDLCOMMENT] varchar(90) NULL,
    [UTC_CREATED_DATE] datetime NOT NULL,
    [UTC_LOGICAL_DELETED_DATE] datetime NULL
);