CREATE TABLE [ABR].[PLAN_VALUES] (
    [SiteFlag] varchar(5) NOT NULL,
    [FormatShiftId] varchar(50) NULL,
    [ContentTypeID] varchar(100) NOT NULL,
    [ColorTag] varchar(100) NULL,
    [ShiftID] varchar(50) NULL,
    [ComplianceAssetID] varchar(100) NULL,
    [Pala] varchar(50) NULL,
    [Destino] varchar(50) NULL,
    [Tons] decimal(18,9) NULL,
    [CuT] decimal(18,9) NULL,
    [QLT] decimal(18,9) NULL,
    [CuRC] decimal(18,9) NULL,
    [CuRR] decimal(18,9) NULL,
    [SCKM] decimal(18,9) NULL,
    [SClay] decimal(18,9) NULL,
    [Trucks] decimal(18,9) NULL,
    [Trucks_Hours] decimal(18,9) NULL,
    [DFS] decimal(18,9) NULL,
    [UDF] decimal(18,9) NULL,
    [AEF] decimal(18,9) NULL,
    [Id] int NOT NULL,
    [ContentType] varchar(50) NOT NULL,
    [Modified] datetime NOT NULL,
    [Created] datetime NOT NULL,
    [CreatedById] int NOT NULL,
    [ModifiedById] int NOT NULL,
    [Owshiddenversion] int NOT NULL,
    [Version] decimal(10,5) NOT NULL,
    [Path] varchar(2000) NOT NULL,
    [UTC_CREATED_DATE] datetime NULL
);