CREATE TABLE [ABR].[SHIFT_EQMT] (
    [siteflag] varchar(5) NOT NULL,
    [DbPrevious] decimal(19,0) NULL,
    [DbNext] decimal(19,0) NULL,
    [DbVersion] int NULL,
    [ShiftId] int NOT NULL,
    [Id] decimal(19,0) NOT NULL,
    [DbName] varchar(32) NOT NULL,
    [DbKey] decimal(19,0) NOT NULL,
    [FieldId] varchar(12) NULL,
    [FieldPit] decimal(19,0) NULL,
    [FieldRegionlock] decimal(19,0) NULL,
    [FieldSize] decimal(19,0) NULL,
    [FieldTmph] decimal(19,0) NULL,
    [FieldReason] smallint NULL,
    [FieldUnit] decimal(19,0) NULL,
    [FieldStatus] decimal(19,0) NULL,
    [FieldExtraload] int NULL,
    [FieldNoassign] int NULL,
    [FieldLoadstart] decimal(19,0) NULL,
    [FieldEqmttype] decimal(19,0) NULL,
    [FieldComment] varchar(90) NULL,
    [FieldReasonrec] decimal(19,0) NULL,
    [FieldOper] decimal(19,0) NULL,
    [FieldAudit] decimal(19,0) NULL,
    [FieldSubcode] int NULL,
    [FieldSubcode2] int NULL,
    [FieldSituation] varchar(20) NULL,
    [FieldUser] int NULL,
    [FieldMaintstart] decimal(19,0) NULL,
    [FieldMaintpropose] decimal(19,0) NULL,
    [FieldWarranty] int NULL,
    [FieldEnghr] decimal(19,0) NULL,
    [FieldEnghr2] decimal(19,0) NULL,
    [FieldEnghrtime] decimal(19,0) NULL,
    [FieldEnghrtime2] decimal(19,0) NULL,
    [FieldIsauxil] int NULL,
    [FieldPmid] varchar(30) NULL,
    [UTC_CREATED_DATE] datetime NOT NULL,
    [UTC_LOGICAL_DELETED_DATE] datetime NULL
);