CREATE TABLE [dbo].[OPERATOR_CONSECUTIVE_WORKDAYS_STG_2_IMO] (
    [SITE_CODE] varchar(4) NOT NULL,
    [UNIT_CODE] int NULL,
    [OPERID] varchar(60) NOT NULL,
    [FIRSTSHIFTINDEX] int NOT NULL,
    [LASTSHIFTINDEX] int NULL,
    [NROFDAYS] int NULL,
    [UTC_CREATED_DATE] datetime NULL
);