/*****************************************************************************************
* TABLE     : DRILL_BLAST__DRILLBLAST_EQUIPMENT_INCR
* DATABASE  : SNOWFLAKE_WG
* SCHEMA    : dbo
* SOURCE    : Snowflake DEV_API_REF.FUSE.DRILLBLAST_EQUIPMENT_INCR
* DATE      : 2026-01-28 | AUTHOR: CARLOS CARRILLO
******************************************************************************************/
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DRILL_BLAST__DRILLBLAST_EQUIPMENT_INCR]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DRILL_BLAST__DRILLBLAST_EQUIPMENT_INCR] (
    ORIG_SRC_ID INT NOT NULL,
    SITE_CODE NVARCHAR(5) NOT NULL,
    DRILL_ID BIGINT NOT NULL,
    EQUIP_NAME NVARCHAR(255),
    EQUIP_MODEL NVARCHAR(255),
    SERIAL_NUMBER NVARCHAR(255),
    EQUIP_CATEGORY NVARCHAR(50),
    MEM_EQUIP_ID NVARCHAR(255),
    EQUIP_UNIT_CODE INT,
    SAP_EQUIP_NO NVARCHAR(50),
    SYSTEM_VERSION NVARCHAR(255),
    DW_LOGICAL_DELETE_FLAG NVARCHAR(1) DEFAULT 'N',
    DW_LOAD_TS DATETIME2,
    DW_MODIFY_TS DATETIME2,
    CONSTRAINT PK_DRILL_BLAST__DRILLBLAST_EQUIPMENT_INCR PRIMARY KEY (ORIG_SRC_ID, SITE_CODE, DRILL_ID)
);
END
GO

-- Create index for archival queries
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_DRILL_BLAST__DRILLBLAST_EQUIPMENT_INCR_DW_MODIFY_TS')
CREATE INDEX IX_DRILL_BLAST__DRILLBLAST_EQUIPMENT_INCR_DW_MODIFY_TS ON [dbo].[DRILL_BLAST__DRILLBLAST_EQUIPMENT_INCR](DW_MODIFY_TS);
GO
