/*****************************************************************************************
* TABLE     : DRILL_BLAST__DRILL_PLAN_INCR
* DATABASE  : SNOWFLAKE_WG
* SCHEMA    : dbo
* SOURCE    : Snowflake DEV_API_REF.FUSE.DRILL_PLAN_INCR
* DATE      : 2026-01-28 | AUTHOR: CARLOS CARRILLO
******************************************************************************************/
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DRILL_BLAST__DRILL_PLAN_INCR]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DRILL_BLAST__DRILL_PLAN_INCR] (
    DRILL_PLAN_SK BIGINT NOT NULL,
    ORIG_SRC_ID BIGINT,
    SITE_CODE NVARCHAR(5),
    BENCH DECIMAL(38,1),
    PUSHBACK NVARCHAR(MAX),
    PATTERN_NAME NVARCHAR(510),
    ORIGINAL_PATTERN_NAME NVARCHAR(510),
    PLAN_CREATION_TS_UTC NVARCHAR(50),
    PLAN_CREATION_TS_LOCAL NVARCHAR(50),
    DESIGN_BY NVARCHAR(100),
    HOLE_NAME NVARCHAR(256),
    HOLE_DIAMETER_MM DECIMAL(38,5),
    HOLE_DIAMETER_INCHES DECIMAL(38,5),
    HOLE_DEPTH_METERS DECIMAL(38,5),
    HOLE_DEPTH_FEET DECIMAL(38,5),
    HOLE_START_METERS_X DECIMAL(38,5),
    HOLE_START_METERS_Y DECIMAL(38,5),
    HOLE_START_METERS_Z DECIMAL(38,5),
    HOLE_END_METERS_X DECIMAL(38,5),
    HOLE_END_METERS_Y DECIMAL(38,5),
    HOLE_END_METERS_Z DECIMAL(38,5),
    HOLE_START_FEET_X DECIMAL(38,5),
    HOLE_START_FEET_Y DECIMAL(38,5),
    HOLE_START_FEET_Z DECIMAL(38,5),
    HOLE_END_FEET_X DECIMAL(38,5),
    HOLE_END_FEET_Y DECIMAL(38,5),
    HOLE_END_FEET_Z DECIMAL(38,5),
    BURDEN FLOAT,
    SPACING FLOAT,
    TONS_PER_HOLE NVARCHAR(MAX),
    BLASTABILITY_INDEX NVARCHAR(MAX),
    RQD NVARCHAR(MAX),
    UCS NVARCHAR(MAX),
    PREDICTED_PENRATE NVARCHAR(MAX),
    PROJECTED_MECHANICAL_SPECIFIC_ENERGY NVARCHAR(MAX),
    TARGET_P80 NVARCHAR(MAX),
    SHOT_GOAL NVARCHAR(MAX),
    SYSTEM_VERSION NVARCHAR(20),
    DW_LOAD_TS DATETIME2,
    DW_MODIFY_TS DATETIME2,
    DW_LOGICAL_DELETE_FLAG NVARCHAR(1) DEFAULT 'N',
    DW_ROW_HASH NVARCHAR(64),
    CONSTRAINT PK_DRILL_BLAST__DRILL_PLAN_INCR PRIMARY KEY (DRILL_PLAN_SK)
);
END
GO

-- Create index for archival queries
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_DRILL_BLAST__DRILL_PLAN_INCR_DW_MODIFY_TS')
CREATE INDEX IX_DRILL_BLAST__DRILL_PLAN_INCR_DW_MODIFY_TS ON [dbo].[DRILL_BLAST__DRILL_PLAN_INCR](DW_MODIFY_TS);
GO
