/*****************************************************************************************
* TABLE     : LOAD_HAUL__LH_HAUL_CYCLE_INCR
* DATABASE  : SNOWFLAKE_WG
* SCHEMA    : dbo
* SOURCE    : Snowflake DEV_API_REF.FUSE.LH_HAUL_CYCLE_INCR
* DATE      : 2026-01-28 | AUTHOR: CARLOS CARRILLO
******************************************************************************************/
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LOAD_HAUL__LH_HAUL_CYCLE_INCR]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[LOAD_HAUL__LH_HAUL_CYCLE_INCR] (
    HAUL_CYCLE_ID BIGINT NOT NULL,
    SITE_CODE NVARCHAR(4),
    ORIG_SRC_ID BIGINT,
    SHIFT_ID_AT_LOADING_END NVARCHAR(12),
    SHIFT_ID_AT_DUMP_END NVARCHAR(12),
    MATERIAL_ID BIGINT,
    ROUTING_SHAPE_ID BIGINT,
    LOADING_LOC_ID BIGINT,
    LOADING_LOC_NAME NVARCHAR(255),
    LOADING_LOC_COORD_X FLOAT,
    LOADING_LOC_COORD_Y FLOAT,
    LOADING_LOC_ELEV FLOAT,
    LOADING_METHOD NVARCHAR(50),
    DUMP_LOC_ID BIGINT,
    DUMP_LOC_NAME NVARCHAR(255),
    DUMP_LOC_COORD_X FLOAT,
    DUMP_LOC_COORD_Y FLOAT,
    DUMP_LOC_ELEV FLOAT,
    CATEGORY_MATERIAL NVARCHAR(50),
    CATEGORY_SOURCE_DESTINATION NVARCHAR(100),
    EXCAV_ID BIGINT,
    EXCAV_OPERATOR_ID BIGINT,
    TRUCK_ID BIGINT,
    TRUCK_LOADING_OPERATOR_ID BIGINT,
    TRUCK_DUMPING_OPERATOR_ID BIGINT,
    REPORT_PAYLOAD_SHORT_TONS DECIMAL(38,6),
    NOMINAL_PAYLOAD_SHORT_TONS DECIMAL(38,6),
    MEASURED_PAYLOAD_METRIC_TONS DECIMAL(38,6),
    AUTONOMOUS_FLAG TINYINT,
    OVERLOAD_FLAG TINYINT,
    CYCLE_START_TS_UTC DATETIME2(3),
    CYCLE_END_TS_UTC DATETIME2(3),
    CYCLE_START_TS_LOCAL DATETIME2(3),
    CYCLE_END_TS_LOCAL DATETIME2(3),
    EMPTY_TRAVEL_START_TS_UTC DATETIME2(3),
    EMPTY_TRAVEL_END_TS_UTC DATETIME2(3),
    EMPTY_TRAVEL_START_TS_LOCAL DATETIME2(3),
    EMPTY_TRAVEL_END_TS_LOCAL DATETIME2(3),
    EMPTY_TRAVEL_DURATION_MINS DECIMAL(38,6),
    EMPTY_TRAVEL_DISTANCE_FEET DECIMAL(38,6),
    EMPTY_TRAVEL_DISTANCE_METERS DECIMAL(38,6),
    LOADING_START_TS_UTC DATETIME2(3),
    LOADING_END_TS_UTC DATETIME2(3),
    LOADING_START_TS_LOCAL DATETIME2(3),
    LOADING_END_TS_LOCAL DATETIME2(3),
    LOADING_DURATION_MINS DECIMAL(38,6),
    FULL_TRAVEL_START_TS_UTC DATETIME2(3),
    FULL_TRAVEL_END_TS_UTC DATETIME2(3),
    FULL_TRAVEL_START_TS_LOCAL DATETIME2(3),
    FULL_TRAVEL_END_TS_LOCAL DATETIME2(3),
    FULL_TRAVEL_DURATION_MINS DECIMAL(38,6),
    FULL_TRAVEL_DISTANCE_FEET DECIMAL(38,6),
    FULL_TRAVEL_DISTANCE_METERS DECIMAL(38,6),
    DUMPING_START_TS_UTC DATETIME2(3),
    DUMPING_END_TS_UTC DATETIME2(3),
    DUMPING_START_TS_LOCAL DATETIME2(3),
    DUMPING_END_TS_LOCAL DATETIME2(3),
    DUMPING_DURATION_MINS DECIMAL(38,6),
    CYCLE_DURATION_MINS DECIMAL(38,6),
    DELTA_C_MINS DECIMAL(38,6),
    FUEL_USED_IN_CYCLE_GALLONS DECIMAL(38,6),
    TCU_PCT DECIMAL(38,6),
    XCU_PCT DECIMAL(38,6),
    INSOL_PCT DECIMAL(38,6),
    SYSTEM_VERSION NVARCHAR(50),
    DW_LOGICAL_DELETE_FLAG NVARCHAR(1) DEFAULT 'N',
    DW_LOAD_TS DATETIME2,
    DW_MODIFY_TS DATETIME2,
    CONSTRAINT PK_LOAD_HAUL__LH_HAUL_CYCLE_INCR PRIMARY KEY (HAUL_CYCLE_ID)
);
END
GO

-- Create index for archival queries
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_LOAD_HAUL__LH_HAUL_CYCLE_INCR_DW_MODIFY_TS')
CREATE INDEX IX_LOAD_HAUL__LH_HAUL_CYCLE_INCR_DW_MODIFY_TS ON [dbo].[LOAD_HAUL__LH_HAUL_CYCLE_INCR](DW_MODIFY_TS);
GO
