CREATE TABLE [BAG].[SHIFT_LOC] (
    [SITEFLAG] varchar(5) NOT NULL,
    [DBPREVIOUS] decimal(19,0) NULL,
    [DBNEXT] decimal(19,0) NULL,
    [DBVERSION] int NULL,
    [SHIFTID] decimal(19,0) NOT NULL,
    [ID] decimal(19,0) NOT NULL,
    [DBNAME] varchar(32) NOT NULL,
    [DBKEY] decimal(19,0) NOT NULL,
    [FIELDID] varchar(24) NULL,
    [FIELDPIT] decimal(19,0) NULL,
    [FIELDREGION] decimal(19,0) NULL,
    [FIELDELEV] decimal(19,0) NULL,
    [FIELDUNIT] decimal(19,0) NULL,
    [FIELDSTATUS] decimal(19,0) NULL,
    [FIELDREASON] int NULL,
    [FIELDREASONREC] decimal(19,0) NULL,
    [FIELDAUDIT] decimal(19,0) NULL,
    [FIELDMETADATA] varchar(20) NULL,
    [FIELDX] int NULL,
    [FIELDY] int NULL,
    [UTC_CREATED_DATE] datetime NOT NULL,
    [UTC_LOGICAL_DELETED_DATE] datetime NULL
);