CREATE VIEW [dbo].[ACTIVE_PATTERN_HOLE_STATUS] AS




CREATE view [dbo].[ACTIVE_PATTERN_HOLE_STATUS] as 
/*
WITH DHC AS (
    SELECT
        pattern_name AS PATTERN_ID,
        hole_name,
        site_code,
        pushback,
        plan_creation_ts_local,
        ROW_NUMBER() OVER (
            PARTITION BY pattern_name, hole_name, site_code
            ORDER BY plan_creation_ts_local DESC
        ) AS rn
    FROM DBO.drill_plan
    WHERE pattern_name IS NOT NULL AND hole_name IS NOT NULL
),
hole_rows AS (
    SELECT
        CASE 
            WHEN dplan.site_code = 'MOR' THEN
                CASE 
                    WHEN TRY_CAST(LEFT(dplan.original_plan_id, 3) AS INT) IS NULL THEN SUBSTRING(dplan.original_plan_id, 4, 5)
                    WHEN TRY_CAST(LEFT(dplan.original_plan_id, 10) AS INT) IS NOT NULL THEN dplan.original_plan_id
                    ELSE LEFT(dplan.original_plan_id, 5)
                END
            ELSE dplan.original_plan_id
        END AS pattern_no,
        DPLAN.ORIGINAL_PLAN_ID,
        DH.HOLE_NAME AS DRILLED_HOLE_ID,
        PLH.ORIGINAL_HOLE_ID AS PLANNED_HOLE_ID,
        RIG.RIG_NAME AS DRILL_ID,
        CASE
            WHEN DH.END_HOLE_TIME IS NULL AND DH.START_HOLE_TIME IS NULL THEN 'UNDRILLED'
            WHEN DH.STATUS = 0 THEN 'UNSPECIFIED'
            WHEN DH.STATUS = 1 THEN 'UNDRILLED'
            WHEN DH.STATUS = 2 THEN 'SUCCESS, DRILLED'
            WHEN DH.STATUS = 3 THEN 'FAIL'
            WHEN DH.STATUS = 4 THEN 'OTHERS'
            WHEN DH.STATUS = 5 THEN 'ABORTED'
            WHEN DH.STATUS = 6 THEN 'REDRILLED'
        END AS DRILL_HOLE_STATUS,
        DH.START_HOLE_TIME AS START_HOLE_TS,
        CASE WHEN DH.START_HOLE_TIME >= DATEADD(HOUR, -6, GETDATE()) THEN 1 ELSE 0 END AS active_hole_flag,
        CASE WHEN DH.START_HOLE_TIME >= DATEADD(HOUR, -6, GETDATE()) THEN PLH.SITE_CODE + '_' + RIG.RIG_NAME ELSE NULL END AS SITE_DRILL_ACTIVE,
        CASE 
            WHEN DH.END_HOLE_TIME > DH.START_HOLE_TIME AND (DH.RAW_START_POINT_Z - DH.RAW_END_POINT_Z) * 3.28084 > 2 THEN
                ((DH.RAW_START_POINT_Z - DH.RAW_END_POINT_Z) * 3.28084) /
                NULLIF(CAST(DATEDIFF(SECOND, DH.START_HOLE_TIME, DH.END_HOLE_TIME) / 3600.0 AS DECIMAL(18,2)), 0)
        END AS AVG_PENETRATE_RATE,
        CASE 
            WHEN (DH.RAW_START_POINT_Z - DH.RAW_END_POINT_Z) * 3.28084 > 2 THEN (DH.RAW_START_POINT_Z - DH.RAW_END_POINT_Z) * 3.28084
        END AS DRILLED_DEPTH,
        CASE 
            WHEN (COALESCE(DH.RAW_START_POINT_Z, PLH.RAW_START_POINT_Z) - PLH.RAW_END_POINT_Z) * 3.28084 > 2 THEN
                (COALESCE(DH.RAW_START_POINT_Z, PLH.RAW_START_POINT_Z) - PLH.RAW_END_POINT_Z) * 3.28084
        END AS PLAN_DEPTH,
        CASE WHEN (COALESCE(DH.RAW_START_POINT_Z, PLH.RAW_START_POINT_Z) - PLH.RAW_END_POINT_Z) * 3.28084 > 57 THEN 57 
             WHEN (COALESCE(DH.RAW_START_POINT_Z, PLH.RAW_START_POINT_Z) - PLH.RAW_END_POINT_Z) * 3.28084<=57 AND (COALESCE(DH.RAW_START_POINT_Z, PLH.RAW_START_POINT_Z) - PLH.RAW_END_POINT_Z) * 3.28084>2 THEN (COALESCE(DH.RAW_START_POINT_Z, PLH.RAW_START_POINT_Z) - PLH.RAW_END_POINT_Z) * 3.28084
             END AS PLAN_DEPTH_ADJUSTED,
        DH.RAW_START_POINT_Y * 3.28084 AS START_POINT_X,
        PLH.RAW_START_POINT_Y * 3.28084 AS DESIGN_X_START,
        PLH.RAW_START_POINT_X * 3.28084 AS DESIGN_Y_START,
        PLH.HOLE_NAME AS DESIGNED_AS_HOLENAME,
        DHC.PUSHBACK,
        DHC.plan_creation_ts_local,
        ROW_NUMBER() OVER (PARTITION BY PLH.RAW_START_POINT_Y, PLH.RAW_START_POINT_X ORDER BY DPLAN.SRC_CREATE_TS DESC) AS rn
    FROM DBO.RCS_PLANNED_HOLE PLH
    LEFT JOIN DBO.RCS_DRILLED_HOLE DH
        ON PLH.SITE_CODE = DH.SITE_CODE
        AND PLH.DRILL_PLAN_ID = DH.DRILL_PLAN_ID
        AND PLH.ORIGINAL_HOLE_ID = DH.HOLE_ID
    LEFT JOIN DBO.RCS_DRILL_PLAN DPLAN
        ON PLH.SITE_CODE = DPLAN.SITE_CODE
        AND PLH.DRILL_PLAN_ID = DPLAN.DRILL_PLAN_ID
    LEFT JOIN DBO.RCS_RIG RIG
        ON DH.SITE_COD