CREATE VIEW [dbo].[BLASTLINEUP] AS



CREATE view [dbo].BLASTLINEUP as 
SELECT 
  BLAST_NAME AS SHOTNO,
  BLAST_DATE_UTC AS PLANDATE
FROM (
    SELECT 
        BLAST_NAME,
        BLAST_DATE_UTC,
        ROW_NUMBER() OVER (PARTITION BY BLAST_NAME ORDER BY BLAST_DATE_UTC DESC) AS RN
    FROM dbo.BLAST_PLAN
    WHERE BLAST_DATE_UTC >= DATEADD(day, -30, GETDATE())
) t
WHERE t.RN = 1;


