CREATE VIEW [cli].[CONOPS_CLI_CM_HOURLY_INTERMEDIATE_STOCKPILE_V] AS




  
  
--SELECT * FROM [cli].[CONOPS_CLI_CM_HOURLY_INTERMEDIATE_STOCKPILE_V] WITH (NOLOCK) WHERE SHIFTFLAG = 'CURR'    
CREATE VIEW [cli].[CONOPS_CLI_CM_HOURLY_INTERMEDIATE_STOCKPILE_V]
AS    

WITH CTE AS (
SELECT 
	shiftindex,
	CRUSHERLOC,
	COMPONENT,
	SENSORVALUE,
	CASE WHEN DATEPART(MINUTE,VALUE_TS) BETWEEN 0 AND 5 THEN VALUE_TS END AS TimeInHour
FROM [dbo].[IOS_STOCKPILE_LEVELS] WITH (NOLOCK)
WHERE SITEFLAG = 'CLI'
),

MFLStockpile AS(
SELECT
	SHIFTINDEX,
	SENSORVALUE AS MFLStockpile,
	TimeInHour
FROM CTE
WHERE CRUSHERLOC = '' 
	AND COMPONENT = ''
),

MillStockpile AS(
SELECT
	SHIFTINDEX,
	SENSORVALUE AS MillStockpile,
	TimeInHour
FROM CTE
WHERE CRUSHERLOC = 'Crusher 1' 
	AND COMPONENT = 'CrusherStockpile'
)


SELECT 
a.[SITEFLAG]
,a.[SHIFTFLAG]
,0 AS [MFLStockpile]
,m.[MillStockpile]
,CAST(CONCAT(FORMAT([m].TimeInHour, 'yyyy-MM-dd HH'), ':00:00') AS Datetime) AS TimeInHour
FROM [CLI].[CONOPS_CLI_SHIFT_INFO_V] a WITH (NOLOCK)
LEFT JOIN MillStockpile [m] WITH (NOLOCK) 
	ON a.SHIFTINDEX = [m].SHIFTINDEX 
WHERE m.TimeInHour IS NOT NULL

  




