CREATE VIEW [cli].[CONOPS_CLI_DRILL_OPERATOR_CONSECUTIVE_WORKDAYS_V] AS

-- SELECT * FROM [cli].[CONOPS_CLI_DRILL_OPERATOR_CONSECUTIVE_WORKDAYS_V] WITH (NOLOCK) WHERE Shiftflag = 'PREV'
CREATE VIEW [cli].[CONOPS_CLI_DRILL_OPERATOR_CONSECUTIVE_WORKDAYS_V] 
AS

	SELECT LASTSHIFTINDEX AS Shiftindex,
		   'CMX' SITE_CODE,
		   OPERID,
		   NROFDAYS
	FROM dbo.OPERATOR_CONSECUTIVE_WORKDAYS WITH (NOLOCK)
	WHERE SITE_CODE = 'CLI' AND UNIT_CODE = 12

