CREATE VIEW [cli].[CONOPS_CLI_OPERATOR_ALARM_DELAY_V] AS


-- SELECT * FROM [CLI].[CONOPS_CLI_OPERATOR_ALARM_DELAY_V] WITH (NOLOCK) WHERE Shiftflag = 'PREV'
CREATE VIEW [CLI].[CONOPS_CLI_OPERATOR_ALARM_DELAY_V]
AS

	SELECT [SHIFTFLAG]
		  ,[SITEFLAG]
		  ,[OperatorId]
		  ,Drill_ID AS [EQMTID]
		  ,'DELAY' AS [ALERT_TYPE]
		  ,CONCAT('DELAY - ', [REASONIDX]) AS [ALERT_NAME]
		  ,[REASON] AS [ALERT_DESCRIPTION]
		  ,[AlertDateTime] AS [GeneratedDate]
	FROM [CLI].[CONOPS_CLI_OPERATOR_DRILL_DELAY_V] WITH (NOLOCK)
	UNION ALL
	SELECT [SHIFTFLAG]
		  ,[SITEFLAG]
		  ,[OperatorId]
		  ,ShovelID AS [EQMTID]
		  ,'DELAY' AS [ALERT_TYPE]
		  ,CONCAT('DELAY - ', [REASONIDX]) AS [ALERT_NAME]
		  ,[REASONS] AS [ALERT_DESCRIPTION]
		  ,[StartDateTime] AS [GeneratedDate]
	FROM [CLI].[CONOPS_CLI_OPERATOR_SHOVEL_DELAY_V] WITH (NOLOCK)
	UNION ALL
	SELECT [SHIFTFLAG]
		  ,[SITEFLAG]
		  ,[OperatorId]
		  ,[TruckId] AS [EQMTID]
		  ,'DELAY' AS [ALERT_TYPE]
		  ,CONCAT('DELAY - ', [REASONIDX]) AS [ALERT_NAME]
		  ,[REASONS] AS [ALERT_DESCRIPTION]
		  ,[StartDateTime] AS [GeneratedDate]
	FROM [CLI].[CONOPS_CLI_OPERATOR_TRUCK_DELAY_V] WITH (NOLOCK)

