CREATE VIEW [cli].[CONOPS_CLI_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V] AS
-- SELECT * FROM [CLI].[CONOPS_CLI_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V] WITH (NOLOCK) 
CREATE VIEW [CLI].[CONOPS_CLI_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V]   
AS  
  
SELECT 
LASTSHIFTINDEX AS Shiftindex,  
SITE_CODE,  
OPERID,  
NROFDAYS  
FROM dbo.OPERATOR_CONSECUTIVE_WORKDAYS WITH (NOLOCK)  
WHERE SITE_CODE = 'CLI' AND UNIT_CODE = 2
  