CREATE VIEW [SAF].[CONOPS_SAF_AUTONOMOUS_TRUCK_V] AS



--select * from [SAF].[CONOPS_SAF_AUTONOMOUS_TRUCK_V]
CREATE VIEW [SAF].[CONOPS_SAF_AUTONOMOUS_TRUCK_V]
AS

SELECT DISTINCT
	FieldId AS TruckId,
	0 AS Autonomous
FROM SAF.pit_truck_c WITH(NOLOCK)
WHERE FieldId IS NOT NULL
	AND FieldId <> ''


