CREATE VIEW [SAF].[PIT_AUXEQMT] AS



--SELECT * FROM SAF.PIT_AUXEQMT
CREATE VIEW SAF.PIT_AUXEQMT
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM SAFOperational.dbo.PITAuxeqmt



