CREATE VIEW [SAF].[SHIFT_LOC] AS



--SELECT * FROM SAF.SHIFT_LOC
CREATE VIEW SAF.SHIFT_LOC
AS

SELECT
'SAF' AS SiteFlag,
*
FROM SAFOperational.dbo.SHIFTShiftloc WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM SAF.SHIFT_INFO)



