CREATE VIEW [SAF].[SHIFT_GRADE] AS



--SELECT * FROM SAF.SHIFT_GRADE
CREATE VIEW SAF.SHIFT_GRADE
AS

SELECT
'SAF' AS SiteFlag,
*
FROM SAFOperational.dbo.SHIFTShiftgrade WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM SAF.SHIFT_INFO)



