CREATE VIEW [SIE].[CONOPS_SIE_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V] AS


-- SELECT * FROM [SIE].[CONOPS_SIE_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V] WITH (NOLOCK) 
CREATE VIEW [SIE].[CONOPS_SIE_SHOVEL_OPERATOR_CONSECUTIVE_WORKDAYS_V]   
AS  
  
SELECT 
LASTSHIFTINDEX AS Shiftindex,  
SITE_CODE,  
OPERID,  
NROFDAYS  
FROM dbo.OPERATOR_CONSECUTIVE_WORKDAYS WITH (NOLOCK)  
WHERE SITE_CODE = 'SIE' AND UNIT_CODE = 2


