CREATE VIEW [SIE].[EQUIPMENT_HOURLY_STATUS] AS

--SELECT * FROM SIE.EQUIPMENT_HOURLY_STATUS
CREATE VIEW SIE.EQUIPMENT_HOURLY_STATUS
AS

SELECT *
FROM SIE.EQUIPMENT_HOURLY_STATUS_2 WITH(NOLOCK)

