CREATE VIEW [SIE].[PIT_WORKER] AS



--SELECT * FROM SIE.PIT_WORKER
CREATE VIEW SIE.PIT_WORKER
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM SIEOperational.dbo.PITWorker



