CREATE VIEW [SIE].[PIT_LOC] AS



--SELECT * FROM SIE.PIT_LOC
CREATE VIEW SIE.PIT_LOC
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM SIEOperational.dbo.PITPitLoc WITH(NOLOCK)



