CREATE VIEW [SIE].[PIT_AUXEQMT] AS



--SELECT * FROM SIE.PIT_AUXEQMT
CREATE VIEW SIE.PIT_AUXEQMT
AS

SELECT
*
,GETUTCDATE() AS UTC_CREATED_DATE
,NULL AS UTC_LOGICAL_DELETED_DATE
FROM SIEOperational.dbo.PITAuxeqmt



