CREATE VIEW [SIE].[SHIFT_OPER] AS




--SELECT * FROM SIE.SHIFT_OPER
CREATE VIEW SIE.SHIFT_OPER
AS

SELECT
'SIE' AS SiteFlag,
*
FROM SIEOperational.dbo.SHIFTShiftOper WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM SIE.SHIFT_INFO)




