CREATE VIEW [SIE].[SHIFT_EQMT] AS




--SELECT * FROM SIE.SHIFT_EQMT
CREATE VIEW SIE.SHIFT_EQMT
AS

SELECT
'SIE' AS SiteFlag,
*
FROM SIEOperational.dbo.SHIFTShifteqmt WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM SIE.SHIFT_INFO)




