CREATE VIEW [SIE].[SHIFT_LOC] AS



--SELECT * FROM SIE.SHIFT_LOC
CREATE VIEW SIE.SHIFT_LOC
AS

SELECT
'SIE' AS SiteFlag,
*
FROM SIEOperational.dbo.SHIFTShiftloc WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM SIE.SHIFT_INFO)



