CREATE VIEW [SIE].[SHIFT_GRADE] AS



--SELECT * FROM SIE.SHIFT_GRADE
CREATE VIEW SIE.SHIFT_GRADE
AS

SELECT
'SIE' AS SiteFlag,
*
FROM SIEOperational.dbo.SHIFTShiftgrade WITH(NOLOCK)
WHERE ShiftId >= (SELECT MIN(SHIFTID) FROM SIE.SHIFT_INFO)



