CREATE VIEW [sie].[CONOPS_SIE_CM_HOURLY_INTERMEDIATE_STOCKPILE_V] AS




  
  
--SELECT * FROM [sie].[CONOPS_SIE_CM_HOURLY_INTERMEDIATE_STOCKPILE_V] WITH (NOLOCK) WHERE SHIFTFLAG = 'CURR'    
CREATE VIEW [sie].[CONOPS_SIE_CM_HOURLY_INTERMEDIATE_STOCKPILE_V]
AS    

WITH CTE AS (
SELECT 
	shiftindex,
	CRUSHERLOC,
	COMPONENT,
	SENSORVALUE,
	CASE WHEN DATEPART(MINUTE,VALUE_TS) BETWEEN 0 AND 5 THEN VALUE_TS END AS TimeInHour
FROM [dbo].[IOS_STOCKPILE_LEVELS] WITH (NOLOCK)
WHERE SITEFLAG = 'SIE'
),

MFLStockpile AS(
SELECT
	SHIFTINDEX,
	SENSORVALUE AS MFLStockpile,
	TimeInHour
FROM CTE
WHERE CRUSHERLOC = '' 
	AND COMPONENT = ''
),

MillStockpile AS(
SELECT
	SHIFTINDEX,
	SENSORVALUE AS MillStockpile,
	TimeInHour
FROM CTE
WHERE CRUSHERLOC = 'Crusher' 
	AND COMPONENT = 'CrusherStockpile'
)


SELECT 
a.[SITEFLAG]
,a.[SHIFTFLAG]
,0 AS [MFLStockpile]
,m.[MillStockpile]
,CAST(CONCAT(FORMAT([m].TimeInHour, 'yyyy-MM-dd HH'), ':15:00') AS Datetime) AS TimeInHour
FROM [SIE].[CONOPS_SIE_SHIFT_INFO_V] a WITH (NOLOCK)
LEFT JOIN MillStockpile [m] WITH (NOLOCK) 
	ON a.SHIFTINDEX = [m].SHIFTINDEX 
WHERE m.TimeInHour IS NOT NULL
  
  




