CREATE VIEW [sie].[CONOPS_SIE_DB_DRILL_ASSET_EFFICIENCY_TARGET_V] AS

  
--SELECT * FROM [SIE].[CONOPS_SIE_DB_DRILL_ASSET_EFFICIENCY_TARGET_V] WHERE SHIFTFLAG = 'CURR'  
CREATE VIEW [SIE].[CONOPS_SIE_DB_DRILL_ASSET_EFFICIENCY_TARGET_V]  
AS  
  
SELECT CAST(RIGHT([YEAR], 2) + FORMAT(CAST([MONTH] AS NUMERIC), '00') AS NUMERIC) [SHIFTID],  
    'SIE' AS [SITEFLAG],  
    [DRILLAVAILABILITY],  
    [DRILLASSETEFFICIENCY],  
    [DRILLUTILIZATION]  
FROM (  
 SELECT REVERSE(PARSENAME(REPLACE(REVERSE([DATEEFFECTIVE]), '-', '.'), 1)) AS [YEAR],  
     REVERSE(PARSENAME(REPLACE(REVERSE([DATEEFFECTIVE]), '-', '.'), 2)) AS [MONTH],  
     ISNULL([DRILLAVAILABILITY], 0) AS [DRILLAVAILABILITY],  
     ISNULL([DRILLASSETEFFICIENCY], 0) AS [DRILLASSETEFFICIENCY],  
     ISNULL([DRILLUSEOFAVAILABILITY], 0) AS [DRILLUTILIZATION]  
    FROM [SIE].[PLAN_VALUES_PROD_SUM] (NOLOCK)  
) [TARGET]  
  
