CREATE VIEW [sie].[CONOPS_SIE_DB_DRILL_SCORE_TARGET_V] AS


--select * from [sie].[CONOPS_SIE_DB_DRILL_SCORE_TARGET_V] where shiftflag = 'curr'
CREATE VIEW [sie].[CONOPS_SIE_DB_DRILL_SCORE_TARGET_V]
AS

SELECT CAST(Right([Year], 2) + FORMAT(CAST([Month] AS numeric), '00') AS numeric) [ShiftId],
	   'SIE' AS [siteflag],
	   [DRILLAVAILABILITY],
	   [DRILLASSETEFFICIENCY],
	   [DRILLUTILIZATION],
	   [TARGETFEETDRILLED],
	   [TARGETHOLESDRILLED]
FROM (
	SELECT REVERSE(PARSENAME(REPLACE(REVERSE([DATEEFFECTIVE]), '-', '.'), 1)) AS [Year],
		   REVERSE(PARSENAME(REPLACE(REVERSE([DATEEFFECTIVE]), '-', '.'), 2)) AS [Month],
		   ISNULL([DRILLAVAILABILITY], 0) AS [DRILLAVAILABILITY],
		   ISNULL([DRILLASSETEFFICIENCY], 0) AS [DRILLASSETEFFICIENCY],
		   ISNULL([DRILLUSEOFAVAILABILITY], 0) AS [DRILLUTILIZATION],
		   ISNULL([FEETDRILLEDTARGET], 0) AS [TARGETFEETDRILLED],
		   ISNULL([HOLESDRILLEDTARGET], 0) AS [TARGETHOLESDRILLED]
    FROM [sie].[PLAN_VALUES_PROD_SUM] (NOLOCK)
) [target]

